### PR TITLE
Clean build warnings and nuget config

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Review by allenjzhang — COMMENTED** [review]
How did the binary got in? Do we need to open an item to track [completely remove](https://docs.github.com/en/github/managing-large-files/removing-files-from-a-repositorys-history#removing-a-file-that-was-added-in-an-earlier-commit) these binary files from GitHub history?

**Comment by allenjzhang** [comment]
BTW, since you modified the Search test proj, our track1 consistency checker caught that folder. For the purpose of this PR, this error can be ignored. Feel free to force merge once ready.

**Comment by chamons** [comment]
**Be very** careful with rewriting history to nuke binaries. It could cause issues with the large (78) other PRs:

`We recommend merging or closing all open pull requests before removing files from your repository.`

I would consider getting sign off from at least one architect before moving forward.

**Comment by weshaggard** [comment]
>How did the binary got in? Do we need to open an item to track completely remove these binary files from GitHub history?

Those binaries were checked in a long while ago and while it would be great to remove them from the history we are not going to do that. As @chamons mentions this would cause issues as we would be required to rewrite history and force push to master which we do not want to do. Not only would it mess up existing work and clones but it would also invalidate all our release tags and other branches. We have no plans to rewrite history our repo.

**Comment by weshaggard** [comment]
BTW those packages I deleted from the repo are still referenced so I moved them to our Azure Devops Feed so they can still be resolved.

**Comment by weshaggard** [comment]
search builds in net - mgmt - ci is unrelated these changes as @allenjzhang  mentioned so I'm ignoring that failure for this PR.

**Pull request merged**
