### PR TITLE
Made dictionaries for connection string elements case-insensitive

### LINKED ISSUE #17641: [BUG] Storage QueueClient doesn't support emulator connection string in upper case
**Describe the bug**

The constructor of `QueueClient` accepting connection string throws an exception when the connection string uses upper case:

>UseDevelopmentStorage=True

Looking at [the source code](https://github.com/Azure/azure-sdk-for-net/blob/edc38aea91411c55b32a937a3cf32ffce7d493c6/sdk/storage/Azure.Storage.Common/src/Shared/StorageConnectionString.cs#L627) I see the dictionaries for connection string elements are not case-insensitive.

```c#
IDictionary<string, string> result = new Dictionary<string, string>(settings);
```

**Expected behavior**

The constructor of  `QueueClient` is case-insensetive.

**Actual behavior (include Exception or Stack Trace)**

I'm getting an exception:

```
Message: 
      System.FormatException: No valid combination of account information found.
      Stack Trace: 
        <>c.<Parse>b__67_0(String err)
        StorageConnectionString.ParseCore(String connectionString, StorageConnectionString& accountInformation, Action`1 error)
        StorageConnectionString.Parse(String connectionString)
        QueueClient.ctor(String connectionString, String queueName, QueueClientOptions options)
        QueueClient.ctor(String connectionString, String queueName)
        ConsoleApp1.CreateQueueClient() line 60
```

**To Reproduce**

```c#
var queueClient =  new QueueClient("UseDevelopmentStorage=True", "test");
```

Also can be easily reproduced online: https://dotnetfiddle.net/WI0mdS

**Environment:**
 - Name and version of the Library package used:
```
Azure.Storage.Queues 12.5.0
```
 - Hosting platform or OS and .NET runtime version:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
 - IDE and version:
```
Microsoft Visual Studio Enterprise 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084
```

### PR DESCRIPTION
**Pull request by abatishchev**
Attempt to resolve #17641.

### CODE REVIEW

**Review by amnguye — APPROVED** [review]
Let's merge this PR over the other.

**Comment by amnguye** [comment]
We also need to write a lot more tests with cases for AllRequired, Optional, AtLeastOne, None, MatchesAll because there are more changes that the tests in this PR do not cover. The tests in this PR only covers checking if the Setting accepts upper and lower case.

Here's the github issue to address this https://github.com/Azure/azure-sdk-for-net/issues/17856

**Comment by abatishchev** [comment]
@amnguye sounds good. can you please merge this PR then? I don't have permissions. I closed the another one.

**Comment by amnguye** [comment]
Could you also update the [changelog](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/CHANGELOG.md) to reflect the changes you made. Maybe adding
"- Fixed bug where parsing the connection string for setting values only accepted lowercase values" would be fine

**Comment by abatishchev** [comment]
Sure, updated the changelog.

**Pull request merged**
