### PR TITLE
Add tracing for batch functions

### LINKED ISSUE #30161: [FEATURE REQ] Implement tracing in ServiceBus WebJobs Extension for batch processing
### Library name

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Please describe the feature.

There is [nothing in the extension](https://github.com/azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs) that traces servicebus batch receive .

We don't need it in EventHubs extension because EventHubs processor does it [here in SDK](https://github.com/azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L590)

And here's  how it's done for EventGrid in [WebJobs extension](https://github.com/azure/azure-sdk-for-net/blob/main/sdk/eventgrid/Microsoft.Azure.WebJobs.Extensions.EventGrid/src/EventGridExtensionConfigProvider.cs#L187)

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/30161

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

**Comment by lmolkova** [comment]
Thank you, @JoshLove-msft!!

**Pull request merged**
