### PR TITLE
Servicebus/fix correlation rule filter clone

### PR DESCRIPTION
**Pull request by kolkinn**
Prevent a null value for CorrelationId from throwing an exception when cloning a CorrelationRuleFilter.

When cloning a CorrelationRuleFilter it would previously pass the CorrelationId as a constructor parameter, where the CorrelationId was required to have a non-empty value. This has the unfortunate effect of causing all cloning operations on filters without a CorrelationId to fail.

Sample repro code:
```csharp
var ruleOptions = new CreateRuleOptions("rule", new CorrelationRuleFilter
{
    Subject = "something"
});
var existingRule = await _client.GetRuleAsync("topic", "subscription", "rule");
if (new CreateRuleOptions(existingRule) == ruleOptions) // Crashes
{
    _logger.LogInformation("Rule already up to date");
}
```

### CODE REVIEW

**Comment by JoshLove-msft** [comment]
@mikaelkolkinn can you include the XML that you get back for this rule? I wouldn't have expected that you can get back a correlation rule filter without a CorrelationId.

**Comment by mikaelkolkinn** [comment]
@JoshLove-msft Here is the response with an actual rule from a call using `_client.GetRulesAsync(...)`. I've changed out all the names, but the structure is the same. The way I understood the documentation, a correlation rule could be for any property or properties, not requiring the CorrelationId to be filtered? https://docs.microsoft.com/en-us/azure/service-bus-messaging/topic-filters#filters

```xml
<feed xmlns="http://www.w3.org/2005/Atom">
  <title type="text">Rules</title>
  <id>https://somenamespace.servicebus.windows.net/sbt-some-topic/Subscriptions/some-subscription/rules?api-version=2017-04&amp;enrich=False&amp;$skip=0&amp;$top=100</id>
  <updated>2021-03-19T20:10:59Z</updated>
  <link rel="self" href="https://somenamespace.servicebus.windows.net/sbt-some-topic/Subscriptions/some-subscription/rules?api-version=2017-04&amp;enrich=False&amp;$skip=0&amp;$top=100" />
  <entry xml:base="https://somenamespace.servicebus.windows.net/sbt-some-topic/Subscriptions/some-subscription/rules?api-version=2017-04&amp;enrich=False&amp;$skip=0&amp;$top=100">
    <id>https://somenamespace.servicebus.windows.net/sbt-some-topic/Subscriptions/some-subscription/rules/customRule1?api-version=2017-04</id>
    <title type="text">customRule1</title>
    <published>2021-03-18T12:34:14Z</published>
    <updated>2021-03-18T12:34:14Z</updated>
    <link rel="self" href="rules/customRule1?api-version=2017-04" />
    <content type="application/xml">
      <RuleDescription xmlns="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
        <Filter i:type="CorrelationFilter">
          <Properties>
            <KeyValueOfstringanyType>
              <Key>CustomPropertyName</Key>
              <Value i:type="d5p1:string" xmlns:d5p1="http://www.w3.org/2001/XMLSchema">ExpectedPropertyValue</Value>
            </KeyValueOfstringanyType>
          </Properties>
        </Filter>
        <Action i:type="EmptyRuleAction" />
        <CreatedAt>2021-03-18T12:34:14.4277005Z</CreatedAt>
        <Name>customRule1</Name>
      </RuleDescription>
    </content>
  </entry>
</feed>
```

**Comment by JoshLove-msft** [comment]
Ah yes, my mistake. Thanks for the reply.

**Review by jsquire — APPROVED** [review]
Thank you very much for your contribution, @mikaelkolkinn.   The changes look good to me;  the CI failures look to be related to a transient issue in the build and not the PR itself.   I kicked off the failed bits again.

I'll defer to @JoshLove-msft for final approval.

**Review by JoshLove-msft — APPROVED** [review]

**Pull request merged**
