### PR TITLE
Add READMEs for Samples

### PR DESCRIPTION
**Pull request by tg-msft**

### CODE REVIEW

**Review by pakrym — APPROVED** [review]
Core LGTM, the front-matter thing is ugly :(

**Review by annelo-msft — APPROVED** [review]
LGTM

**Review by heaths — APPROVED** [review]
Key Vault and general files changes look good.

**Review by jsquire — APPROVED** [review]
Event Hubs assets look good.   I'll loop back and copy/paste/link the details for configuring the environment to run things.

Is there an issue or related that I can read to get up to speed on what we're up to?

**Comment by tg-msft** [comment]
Yes - I'll send a link on Teams

**Comment by annelo-msft** [comment]
If you send the link DM could you CC me?

**Comment by tg-msft** [comment]
Included a link on our Teams channel, but the gist is that this header will get our samples picked up in the global [sample browser](https://docs.microsoft.com/en-us/samples/browse/).

**Review by JoshLove-msft — APPROVED** [review]

**Pull request merged**
