### PR TITLE
Keyvault sample changes

### PR DESCRIPTION
**Pull request by amitbapat**
HelloKeyVault application changed to use X509 cert based authentication, as that is the recommended authentication mechanism.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@amitbapat__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ambapat). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by kirthik** [comment]
@amitbapat : Could you please squash both commits into one. We are trying to move to a model where there is one commit per check in.

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by amitbapat** [comment]
@kirthik I'm new to git. How do squash two commits into one?

**Comment by kirthik** [comment]
@amitbapat Please look at Squashing commits section in this link - https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by amitbapat** [comment]
Is there any other action pending for me for this to go through?

**Pull request merged**
