### PR TITLE
Update Information Protection SDK Clients

### PR DESCRIPTION
**Pull request by bashahee**
SDK clients of Information Protection were updated according to changes introduced in corresponding swagger. No new clients were added.
This PR is based on https://github.com/Azure/azure-rest-api-specs/pull/9053 swagger spec review PR.

### CODE REVIEW

**Comment by bashahee** [comment]
@isra-fel @erich-wang Hi, can you please review?

**Review by isra-fel — CHANGES_REQUESTED** [review]
Please update release notes in csproj file. Thanks

**Comment by bashahee** [comment]
@isra-fel Existing release notes are valid for this PR.

**Review by isra-fel — APPROVED** [review]
Great

**Pull request merged**
