### PR TITLE
EventGrid: Regenerate .NET SDK for API version 2020-01-01-preview

### PR DESCRIPTION
**Pull request by ahamad-MS**
Regenerate the .NET SDK files for API vesion 2020-01-01-preview and add new test cases for the new functionalities and its related recorded sessions.

The latest pull request for the Swagger spec review is located here: https://github.com/Azure/azure-rest-api-specs/pull/7681

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @ahamad-MS , could you
- Add a link to the swagger spec review PR(s) in the description
- Update versions if necessary
Thanks

**Comment by ahamad-MS** [comment]
Hello @isra-fel .. The link for the PR for the Swagger is added to the description section. However, not sure what version files you are referring to. Kindly advise if there is any additional files needs to be updated other than generated ones and test cases. thanks,.

**Comment by isra-fel** [comment]
> Hello @isra-fel .. The link for the PR for the Swagger is added to the description section. However, not sure what version files you are referring to. Kindly advise if there is any additional files needs to be updated other than generated ones and test cases. thanks,.

I mean the versions in `.csproj` and `AssemblyInfo.cs`. If you're going to release the SDK you need to bump up the version. You can do it in this PR or another.

**Comment by ahamad-MS** [comment]
@isra-fel Thanks. Fixed.

**Comment by isra-fel** [comment]
Hi @ahamad-MS the versions in `AssemblyInfo.cs` should strictly follow 4-digit convention. I updated that to `5.1.0.0`.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
