### PR TITLE
Update tests for Policy SDK version 2018-03-01

### PR DESCRIPTION
**Pull request by mentat9**
## Description
NOTE: This update does NOT include a swagger change. Consequently, the below boxes for updating generate.cmd/generate.ps1 and project versions are not checked.

This update adds tests to cover the most recent update to the Governance Policy swagger.

Current REST spec for Governance Policy is here:
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2018-03-01
Most recent changes were in this PR:
https://github.com/Azure/azure-rest-api-specs/pull/3032

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [X] Please add REST spec PR link to the SDK PR
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by dsgouda** [comment]
@mentat9 Please fix the failing managementgroup tests. You may have to re-record the tests

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please regenerate the code using the generate.ps1 [here ](https://github.com/mentat9/azure-sdk-for-net/blob/b8e596e532afe3f2eac50442072bd8a39989eb39/src/SDKs/Resource/Management.ResourceManager/generate.ps1)
Please commit all the files generated/modified

**Comment by mentat9** [comment]
>Please regenerate the code using the generate.ps1 here 

Is it normal to do a regeneration when there is no swagger change?

**Comment by dsgouda** [comment]
@mentat9 I assumed you were adding changes to the SDK too. Please disregard the regeneration

**Comment by mentat9** [comment]
> @mentat9 Please fix the failing managementgroup tests. You may have to re-record the tests

Thing is, those aren't my tests and they don't record successfully on my machine. Playback, OTOH is working fine, so I don't understand why they aren't working on the server. Any ideas?

**Comment by mentat9** [comment]
@dsgouda, the tests have been re-recorded, but they still fail in the server build. Neither I nor Raj (the test owner) know how to fix this break. These tests all run fine locally in both of our dev environments. Can you help?

**Comment by dsgouda** [comment]
@mentat9  taking a look

**Comment by mentat9** [comment]
@dsgouda did you learn anything about the break?

**Comment by dsgouda** [comment]
Tried re-running the build without success, will have to debug myself. @shahabhijeet could you take a look at it too?

**Comment by dsgouda** [comment]
@mentat9 Please check if you copied over the recorded test into the `SessionRecords` directory.
You can use [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/tools/HelperUtilities/psScripts/Copy-SessionRecords.ps1) script too.

**Comment by shahabhijeet** [comment]
@rajshah11 can you review this PR.

**Review by rajshah11 — APPROVED** [review]
@dsgouda @shahabhijeet LGTM. I also ran the tests again and the changes made to ManagementGroups.Test project were fine. The build ran fine locally. Not sure why the build is failing here though.

**Comment by mentat9** [comment]
I think I might have figured it out. It looks like someone left behind some old unused test recordings under: src\SDKs\Resource\Resource.Tests\SessionRecords\ResourceGroups.Tests.LiveManagementGroupsTests.When the management group SDK was removed from the resources SDK, these should have been deleted. I'm guessing server test discovery is finding these and trying to run them, but they are outdated.

Hopefully, that is the problem. If so, I don't understand why my build was the first to break. I would have expected every build since the MG code was removed from the Resource SDK should have broken.

**Comment by mentat9** [comment]
I have no idea what this failure in the Travis build means:

>"The command "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893" failed and exited with 2 during ."

But I've seen it before and it had nothing to do with my PR: it was something broken in the build environment. @dsgouda (or someone), can you force a retry on the Travis build?

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
