### PR TITLE
[ADLS] - Adding existing Account APIs

### PR DESCRIPTION
**Pull request by ro-joowan**
### REST spec PR link to the SDK PR

- https://github.com/Azure/azure-rest-api-specs/pull/2013
- https://github.com/Azure/azure-rest-api-specs/pull/1857
- https://github.com/Azure/azure-rest-api-specs/pull/1807
- https://github.com/Azure/azure-rest-api-specs/pull/1745

### [ADLS] Changes in 2.3.3-preview

**Breaking changes**

- Changed the `ODataQuery` parameter type from `DataLakeAnalyticsAccount` to `DataLakeAnalyticsAccountBasic` for these APIs:
    - Account_List
    - Account_ListByResourceGroup

**Notes**

- Added two more states to `DataLakeStoreAccountStatus` enum: `Undeleting` and `Canceled`
- Added new Account APIs:
    - Account_CheckNameAvailability
    - Location_GetCapability
    - Operation_List

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
1) Get latest updates from upstream (if you have not done so in last 3 weeks)
2) Then execute msbuild build.proj to update your build tools
3) Then regenerate your SDK using generate.cmd (this will regenerate couple of additional files)
4) build you project (ether IDE or command line)
5) Then update your PR
With the latest changes, every regeneration will generate couple of additional meta data files that are needed in each PR.

**Comment by ro-joowan** [comment]
@shahabhijeet I followed those steps already as you noted them in my initial PR: https://github.com/Azure/azure-sdk-for-net/pull/3954

**Comment by shahabhijeet** [comment]
@ro-joowan please include all those files, they are required.

**Comment by ro-joowan** [comment]
@shahabhijeet Thank you pointing them out in detail! The process makes more sense now. I have updated this PR.

**Review by shahabhijeet — APPROVED** [review]
Once CI passes, this PR is ready to be merged.

**Pull request merged**
