### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by markdeed**
Updating header

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
@markdeed can you tell me more about this change? Which branch are you referring to?

**Comment by markdeed** [comment]
Hi Please disregard my request. I was lost in the azure tutorials, and
thought I was downloading a tutorial code example.

regards
Mark Deed

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Review by KrzysztofCwalina — CHANGES_REQUESTED** [review]
Should this go into the contributor's guide as opposed to the root README?

**Comment by kurtzeborn** [comment]
The opener thinks this should be closed.  I agree.  It appears to have been a misunderstanding.

**Pull request closed without merging**
