### PR TITLE
Changes for new CZR feature 2020-12-01 api

### PR DESCRIPTION
**Pull request by arpja**
Adding new changes for 2020-12-01 api version.

### CODE REVIEW

**Comment by arpja** [comment]
> @arpja Please fix the failing checks.

Hi @YalinLi0312, 
Please review changes now, I have fixed the compile and test failures.

**Comment by arpja** [comment]
Hi @YalinLi0312,
I closed the PR by mistake, reopened it immediately. 
Please review now.

**Comment by arpja** [comment]
Hi @YalinLi0312 @nisha-bhatia,
Could you please review this PR? 
I have fixed the compile and test failures.

**Comment by arpja** [comment]
Hi @YalinLi0312, @markcowl @allenjzhang @bquantump @m-nash @nisha-bhatia,
Could anyone of you please approve this PR if it looks ok? 
Our powershell release is awaiting this change. 
Would appreciate quicker review for this PR.

**Comment by YalinLi0312** [comment]
@arpja Could you provide the swagger review PR link for the updates in this PR?

**Comment by arpja** [comment]
Hi @YalinLi0312
Here is the swagger review PR:
https://github.com/Azure/azure-rest-api-specs/pull/12171

**Comment by arpja** [comment]
Hello @YalinLi0312 
any thoughts? let me know if you have any comments

**Comment by YalinLi0312** [comment]
@arpja Could you:
 - Check in the metadata TXT file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
 - Update api tag in `AzSdk.RP.props`, release notes in csproj
 - Update versions in csproj and `assemblyinfo.cs` if you are going to release

Thanks

**Comment by arpja** [comment]
Hi @YalinLi0312 
Updated the PR

**Comment by arpja** [comment]
Hi @YalinLi0312 
I'm seeing this strange behavior where merge validation fails for generated files with a compile error that an interface is not implemented by a class (Logs: https://dev.azure.com/azure-sdk/public/_build/results?buildId=692080&view=logs&j=ad07b744-5a1a-5d54-7693-fcb02e666633&t=88540a4e-0b51-541f-e623-7b2636eab300 )
When I resolve the error by manually adding the required method in class the merge validation fails again stating that the code is not generated (Logs: https://dev.azure.com/azure-sdk/public/_build/results?buildId=691912&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=3374e909-b3a0-5fde-4fba-1f1bb546637f) 

Can you please let me know if I'm missing something?

**Comment by YalinLi0312** [comment]
We are not allowed to have any manual change in the generated source code now ([here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=691912&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=3374e909-b3a0-5fde-4fba-1f1bb546637f&l=2120)). I think either swagger or codgen tool has some problems.

**Comment by arpja** [comment]
Thanks @YalinLi0312 
how do I get help with generated code failing to compile?

**Pull request closed without merging**
