### PR TITLE
Tags on subscription and deployment

### PR DESCRIPTION
**Pull request by ramoka178**

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @ramoka178  it looks this PR is still a WIP. Please notify me when ready for review. Thanks

P.S. it has conflicts. Please resolve it so that CI could be run.

**Comment by ramoka178** [comment]
Hello @isra-fel : I have fixed the conflicts and updated the PR, could this be reviewed?

Swagger PR corresponding to the SDK changes: https://github.com/Azure/azure-rest-api-specs/pull/8268

**Review by hamidtirmizi — APPROVED** [review]

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @ramoka178 , most of the PR looks good to me. I have a few comments:
1. This cannot be merged until the swagger spec is merged, and once it's done, please regenerate with the checked in spec (not local spec)
1. Please check in the metadata txt of your module under `eng/mgmt/mgmtmetadata`
1. Please update the release notes section in your csproj file

Thanks

**Comment by ramoka178** [comment]
Hi @isra-fel : Swagger repo is merged with this PR https://github.com/Azure/azure-rest-api-specs/pull/8268

I generated the code and also re-recorded the tests

**Comment by isra-fel** [comment]
Hey @ramoka178  test records could not be found. Did you forget to copy and check in some of the json files?

**Comment by ramoka178** [comment]
Hello @isra-fel : I've updated the missing Session records, the checks have passed now.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
