### PR TITLE
Updating sdk to latest 04-01

### PR DESCRIPTION
**Pull request by MehaKaushik**

### CODE REVIEW

**Comment by MehaKaushik** [comment]
@allenjzhang please review and merge

**Comment by MehaKaushik** [comment]
@isra-fel can you please merge this

**Review by allenjzhang — CHANGES_REQUESTED** [review]
Please update Azure.Rp.props with correct api version.

**Comment by MehaKaushik** [comment]
@allenjzhang  Done

**Comment by MehaKaushik** [comment]
@allenjzhang can you please re-run the CI

**Review by allenjzhang — APPROVED** [review]

**Comment by MehaKaushik** [comment]
@allenjzhang can you help with the CI

**Comment by allenjzhang** [comment]
The check was caused by track 2 pipeline which is still pending csproj PR. Can be ignored.

**Pull request merged**
