### PR TITLE
Update ANF SDK for 2019-10-01 API

### PR DESCRIPTION
**Pull request by leonardbf**
API PR Azure/azure-rest-api-specs#7908
Internal ticket ANF-450

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @leonardbf , since you're using new api version, please update api tag in `AzSdk.RP.props`.
And a reminder: if you are going to release, update the verisons in csproj and assemblyinfo.cs
Thanks

**Comment by leonardbf** [comment]
> Hi @leonardbf , since you're using new api version, please update api tag in `AzSdk.RP.props`.
> And a reminder: if you are going to release, update the verisons in csproj and assemblyinfo.cs
> Thanks

Ah yes, an oversight. Updated.

**Comment by leonardbf** [comment]
@isra-fel there seems to have been some disconnect error in the pipeline after pushing my change. Can you tell me how I retrigger the pipeline or maybe do it for me. Thanks.

**Comment by leonardbf** [comment]
@isra-fel or @erich-wang could someone restart the pipeline please. I'm hoping this will resolve the disconnect error that occured. And it would be really great if the update with review corrections could be approved and merged. As well as needing this SDK for out update service, we need it now for developing the new PS cmdlets. Thanks.

**Comment by isra-fel** [comment]
Hi @leonardbf I just want to double check that you didn't introduce any breaking change although the api version was updated. Is that correct?
Because if there is breaking change, the major version needs to be updated.

**Comment by leonardbf** [comment]
@isra-fel There are new request operations and a change to the volume properties object. I would say at least the second of these is a breaking change. However I believe there have been breaking changes with almost every version of the SDK but only the minor number has ever been updated. Is this new to update the major number or was it previously handled wrongly?

**Comment by isra-fel** [comment]
In fact, if a breaking change is introduced, the major version must be updated, so we might be doing it wrong.

But I looked again at the changed files, I assume you were talking about adding `public bool? IsRestoring`? Adding an optional property isn't necessarily a breaking change, users' scripts may still work. In that case, we can just update the minor version

**Comment by leonardbf** [comment]
> In fact, if a breaking change is introduced, the major version must be updated, so we might be doing it wrong.
> 
> But I looked again at the changed files, I assume you were talking about adding `public bool? IsRestoring`? Adding an optional property isn't necessarily a breaking change, users' scripts may still work. In that case, we can just update the minor version

ok, thanks. So can it now be approved and merged?

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
