### PR TITLE
Updating Microsoft.Security to composite v2

### PR DESCRIPTION
**Pull request by chlahav**

### CODE REVIEW

**Comment by chlahav** [comment]
@orparnes @eliagrady for tracking

**Review by dsgouda — CHANGES_REQUESTED** [review]
@chlahav please bump the Nuget package version to `0.12.0-preview` in csproj and assemblyInfo.cs files.

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
Per offline conversation, @chlahav is ready to publish a stable Nuget package, `1.0.0` should be the next version

**Pull request merged**
