### PR TITLE
[Storage] Support SRP new API version 2023-05-01

### PR DESCRIPTION
**Pull request by blueww**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by blueww** [comment]
@ArthurMa1978 

I have added following changes:
1. Add test cases 
2. add change log
3. rebase on latest main branch
4. Since [spelling check failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3877390&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f), added "Nfsv" to ".vscode/cspell.json"
5. Since there are s[everal warning reported in verify generated code](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3877392&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f), add some rename in [this commit](https://github.com/Azure/azure-sdk-for-net/pull/44571/commits/f9c9bb6bc5eff414728680cb7e51ade02777ac6c)
  - StorageAccountCreateParameters.properties.enableExtendedGroups: IsExtendedGroupEnabled
  - StorageAccountUpdateParameters.properties.enableExtendedGroups: IsExtendedGroupEnabled
  - StorageTaskAssignmentProperties.enabled: IsEnabled
However, there are still other warning. 

There's still 3 concerns:
1. CI still fail for following error, althrough I have rebased to latest main, and re-generated. 

> Generated code is not up to date.
>     You may need to rebase on the latest main, 
>     run 'eng\scripts\Update-Snippets.ps1' if you modified sample snippets or other *.md files (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#updating-sample-snippets), 
>     run 'eng\scripts\Export-API.ps1' if you changed public APIs (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#public-api-additions). 
>     run 'dotnet build /t:GenerateCode' to update the generated code and samples.

2. As I mentioned in Teams, Delete task assignment fail for following exception. But 204 is a valid return code per [swagger](https://github.com/triciarosario/azure-rest-api-specs/blob/39d38e6dbf422fd05aabd64bf5663f115d920fcd/specification/storage/resource-manager/Microsoft.Storage/stable/2023-05-01/storageTaskAssignments.json#L197). Currently I temperately catch the error to make test pass, but this should be resolved before SDK is released.

> Azure.RequestFailedException
>   HResult=0x80131500
>   Message=Service request failed.
> Status: 204 (No Content)
>  
> Service request succeeded. Response content and headers are not included to avoid logging sensitive data.
>  
>   Source=Azure.ResourceManager.Storage
>   StackTrace:
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 285
>    at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 275
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
>    at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 105
>    at Azure.Core.OperationInternal.<UpdateStatusAsync>d__9.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternal.cs:line 110
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
>    at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 105
>    at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 83
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
>    at Azure.Core.OperationPoller.WaitForCompletionResponse(OperationInternalBase operation, Nullable`1 delayHint, CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 35
>    at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 202
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponse(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 165
>    at Azure.ResourceManager.Storage.StorageArmOperation.WaitForCompletionResponse(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\storage\Azure.ResourceManager.Storage\src\Generated\LongRunningOperation\StorageArmOperation.cs:line 83

3. The "maxpagesize" in list task assignment API is defined as string in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/125223f5737a5082e02bc7ef7981e5c819c7330c/specification/storage/resource-manager/Microsoft.Storage/stable/2023-05-01/storageTaskAssignments.json#L278), which makes it's string in SDK. Should we change it to int in SDK? (Per my test, only int string like "6" works on server, other string like "a1" not work. )
I will confirm with feature team if this should be a int value, but swagger should can't be changed on this API version.

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by ArthurMa1978** [comment]
> @ArthurMa1978
> 
> I have added following changes:
> 
> 1. Add test cases
> 2. add change log
> 3. rebase on latest main branch
> 4. Since [spelling check failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3877390&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f), added "Nfsv" to ".vscode/cspell.json"
> 5. Since there are s[everal warning reported in verify generated code](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3877392&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f), add some rename in [this commit](https://github.com/Azure/azure-sdk-for-net/pull/44571/commits/f9c9bb6bc5eff414728680cb7e51ade02777ac6c)
> 
> * StorageAccountCreateParameters.properties.enableExtendedGroups: IsExtendedGroupEnabled
> * StorageAccountUpdateParameters.properties.enableExtendedGroups: IsExtendedGroupEnabled
> * StorageTaskAssignmentProperties.enabled: IsEnabled
>   However, there are still other warning.
> 
> There's still 3 issues:
> 
> 1. CI still fail for following error, althrough I have rebased to latest main, and re-generated.
> 
> > Generated code is not up to date.
> > You may need to rebase on the latest main,
> > run 'eng\scripts\Update-Snippets.ps1' if you modified sample snippets or other *.md files (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#updating-sample-snippets),
> > run 'eng\scripts\Export-API.ps1' if you changed public APIs (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#public-api-additions).
> > run 'dotnet build /t:GenerateCode' to update the generated code and samples.
> 
> 2. As I mentioned in Teams, Delete task assignment fail for following exception. But 204 is a valid return code per [swagger](https://github.com/triciarosario/azure-rest-api-specs/blob/39d38e6dbf422fd05aabd64bf5663f115d920fcd/specification/storage/resource-manager/Microsoft.Storage/stable/2023-05-01/storageTaskAssignments.json#L197). Currently I temperately catch the error to make test pass, but this should be resolved before SDK is released.
> 
> > Azure.RequestFailedException
> > HResult=0x80131500
> > Message=Service request failed.
> > Status: 204 (No Content)
> > Service request succeeded. Response content and headers are not included to avoid logging sensitive data.
> > Source=Azure.ResourceManager.Storage
> > StackTrace:
> > at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 285
> > at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 275 at System.Threading.Tasks.ValueTask`1.get_Result()
> > at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53 at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 105 at Azure.Core.OperationInternal.<UpdateStatusAsync>d__9.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternal.cs:line 110 at System.Threading.Tasks.ValueTask`1.get_Result()
> > at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53 at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 105 at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 83 at System.Threading.Tasks.ValueTask`1.get_Result()
> > at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53 at Azure.Core.OperationPoller.WaitForCompletionResponse(OperationInternalBase operation, Nullable`1 delayHint, CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 35
> > at Azure.Core.OperationInternalBase.d__19.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 202
> > at System.Threading.Tasks.ValueTask`1.get_Result() at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
> > at Azure.Core.OperationInternalBase.WaitForCompletionResponse(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 165
> > at Azure.ResourceManager.Storage.StorageArmOperation.WaitForCompletionResponse(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\storage\Azure.ResourceManager.Storage\src\Generated\LongRunningOperation\StorageArmOperation.cs:line 83
> 
> 3. The "maxpagesize" in list task assignment API is defined as string in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/125223f5737a5082e02bc7ef7981e5c819c7330c/specification/storage/resource-manager/Microsoft.Storage/stable/2023-05-01/storageTaskAssignments.json#L278), which makes it's string in SDK. Should we change it to int in SDK? (Per my test, only int string like "6" works on server, other string like "a1" not work. )
>    I will confirm with feature team if this should be a int value, but swagger should can't be changed on this API version.


> @ArthurMa1978
> 
> I have added following changes:
> 
> 1. Add test cases
> 2. add change log
> 3. rebase on latest main branch
> 4. Since [spelling check failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3877390&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f), added "Nfsv" to ".vscode/cspell.json"
> 5. Since there are s[everal warning reported in verify generated code](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3877392&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f), add some rename in [this commit](https://github.com/Azure/azure-sdk-for-net/pull/44571/commits/f9c9bb6bc5eff414728680cb7e51ade02777ac6c)
> 
> * StorageAccountCreateParameters.properties.enableExtendedGroups: IsExtendedGroupEnabled
> * StorageAccountUpdateParameters.properties.enableExtendedGroups: IsExtendedGroupEnabled
> * StorageTaskAssignmentProperties.enabled: IsEnabled
>   However, there are still other warning.
> 
> There's still 3 issues:
> 
> 1. CI still fail for following error, althrough I have rebased to latest main, and re-generated.
> 
> > Generated code is not up to date.
> > You may need to rebase on the latest main,
> > run 'eng\scripts\Update-Snippets.ps1' if you modified sample snippets or other *.md files (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#updating-sample-snippets),
> > run 'eng\scripts\Export-API.ps1' if you changed public APIs (https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#public-api-additions).
> > run 'dotnet build /t:GenerateCode' to update the generated code and samples.
> 
> 2. As I mentioned in Teams, Delete task assignment fail for following exception. But 204 is a valid return code per [swagger](https://github.com/triciarosario/azure-rest-api-specs/blob/39d38e6dbf422fd05aabd64bf5663f115d920fcd/specification/storage/resource-manager/Microsoft.Storage/stable/2023-05-01/storageTaskAssignments.json#L197). Currently I temperately catch the error to make test pass, but this should be resolved before SDK is released.
> 
> > Azure.RequestFailedException
> > HResult=0x80131500
> > Message=Service request failed.
> > Status: 204 (No Content)
> > Service request succeeded. Response content and headers are not included to avoid logging sensitive data.
> > Source=Azure.ResourceManager.Storage
> > StackTrace:
> > at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 285
> > at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 275 at System.Threading.Tasks.ValueTask`1.get_Result()
> > at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53 at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 105 at Azure.Core.OperationInternal.<UpdateStatusAsync>d__9.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternal.cs:line 110 at System.Threading.Tasks.ValueTask`1.get_Result()
> > at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53 at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 105 at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 83 at System.Threading.Tasks.ValueTask`1.get_Result()
> > at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53 at Azure.Core.OperationPoller.WaitForCompletionResponse(OperationInternalBase operation, Nullable`1 delayHint, CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 35
> > at Azure.Core.OperationInternalBase.d__19.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 202
> > at System.Threading.Tasks.ValueTask`1.get_Result() at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
> > at Azure.Core.OperationInternalBase.WaitForCompletionResponse(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 165
> > at Azure.ResourceManager.Storage.StorageArmOperation.WaitForCompletionResponse(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\storage\Azure.ResourceManager.Storage\src\Generated\LongRunningOperation\StorageArmOperation.cs:line 83
> 
> 3. The "maxpagesize" in list task assignment API is defined as string in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/125223f5737a5082e02bc7ef7981e5c819c7330c/specification/storage/resource-manager/Microsoft.Storage/stable/2023-05-01/storageTaskAssignments.json#L278), which makes it's string in SDK. Should we change it to int in SDK? (Per my test, only int string like "6" works on server, other string like "a1" not work. )
>    I will confirm with feature team if this should be a int value, but swagger should can't be changed on this API version.

2. If the resource exist then the delete operation should not return 204, 204 means the resource doesn't exist when calling delete.
3. If the value is int string then the format should be string.

**Comment by blueww** [comment]
Hi @ArthurMa1978 

For # 2: 
According to LATEST  RPC - [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#delete-resource-asynchronously](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-resource-manager-rpc%2Fblob%2Fmaster%2Fv1.0%2Fasync-api-reference.md%23delete-resource-asynchronously&data=05%7C02%7Cweiwei%40microsoft.com%7Ce51fc0f8afe24e1d92f208dc558d60d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638479312960590409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=dz4tXR9l1vA%2FxW1CM15XIEyKQX4gdIw25IHWh3YsLl0%3D&reserved=0) "If the DELETE completes successfully, the URL that was returned in the Location header MUST now return a 200 OK or 204 NoContent to indicate success and the resource MUST disappear."
Feature team we the swagger reviewed by ARM, They expect us to ONLY return 204
1.	Swagger Validation Throws error if for an Async LRO delete supports any status code other than 204 : [https://github.com/Azure/azure-openapi-validator/blob/main/docs/delete-response-codes.md#output-message](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-openapi-validator%2Fblob%2Fmain%2Fdocs%2Fdelete-response-codes.md%23output-message&data=05%7C02%7Cweiwei%40microsoft.com%7Ce51fc0f8afe24e1d92f208dc558d60d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638479312960601712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=pYFAu4VajI9wEKgy4zvpBV0QVnpS2lsj22s2amk8HYE%3D&reserved=0)

**Comment by blueww** [comment]
for # 3,

Feature team has confirmed they will fix swagger to use int in the future release.
So to avoid breaking SDK in the future, could we use SDK side configure to change the type from string to int?

**Comment by ArthurMa1978** [comment]
> for # 3,
> 
> Feature team has confirmed they will fix swagger to use int in the future release. So to avoid breaking SDK in the future, could we use SDK side configure to change the type from string to int?

How about remove this property for this version? otherwise we have to handle breaking changes in new version no matter string or int now

**Comment by ArthurMa1978** [comment]
> Hi @ArthurMa1978
> 
> For # 2: According to LATEST RPC - [https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#delete-resource-asynchronously](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-resource-manager-rpc%2Fblob%2Fmaster%2Fv1.0%2Fasync-api-reference.md%23delete-resource-asynchronously&data=05%7C02%7Cweiwei%40microsoft.com%7Ce51fc0f8afe24e1d92f208dc558d60d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638479312960590409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=dz4tXR9l1vA%2FxW1CM15XIEyKQX4gdIw25IHWh3YsLl0%3D&reserved=0) "If the DELETE completes successfully, the URL that was returned in the Location header MUST now return a 200 OK or 204 NoContent to indicate success and the resource MUST disappear." Feature team we the swagger reviewed by ARM, They expect us to ONLY return 204
> 
> 1. Swagger Validation Throws error if for an Async LRO delete supports any status code other than 204 : [https://github.com/Azure/azure-openapi-validator/blob/main/docs/delete-response-codes.md#output-message](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-openapi-validator%2Fblob%2Fmain%2Fdocs%2Fdelete-response-codes.md%23output-message&data=05%7C02%7Cweiwei%40microsoft.com%7Ce51fc0f8afe24e1d92f208dc558d60d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638479312960601712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=pYFAu4VajI9wEKgy4zvpBV0QVnpS2lsj22s2amk8HYE%3D&reserved=0)

After digging into the code, we think this might be a bug in the Azure.Core LRO implementation, issue https://github.com/Azure/azure-sdk-for-net/issues/44640 was opened, and will follow up with core team to get fixing.

**Pull request merged**
