### PR TITLE
ADL Updates

### PR DESCRIPTION
**Pull request by begoldsm**
- Update Job property InnerError -> innerError (finally fixed on the server side)
- Update error messages to reflect the objects returned for ADLS filesystem (as per WebHDFS spec)
- Update tests to test these changes.

### CODE REVIEW

**Comment by markcowl** [comment]
@begoldsm This needs the definitions for PORTABLE and DNXCORE50 in the project.json file, as discussed

**Comment by begoldsm** [comment]
@markcowl thanks for reminding me! I just fixed it on my side. Perhaps we should have this included in the codegen functionality, since the ifdefs are autogenned and assume certain names, we should have those auto inserted into the project.json.

**Comment by begoldsm** [comment]
@markcowl it looks like automatic re-trigger of CI isn't working right now for this PR. I just manually retriggered the run here:
http://azuresdkci.cloudapp.net/job/sdk-for-net/2634/

**Comment by markcowl** [comment]
@begoldsm looks liek there's a localfeed addition in this PR: DataLake.StoreUploader.0.10.2-preview.symbols.nupkg  Is this soemthign you want to clean up?

**Comment by begoldsm** [comment]
@markcowl good catch. I removed it just now, thanks!

**Comment by markcowl** [comment]
@begoldsm still there.  This would be a good opportunity to rebase your commits on the dev branch so the history will be a bit tidier.

**Comment by begoldsm** [comment]
@markcowl done and done. It was still there because I inadvertently made the change in my other branch of the repo :).

**Pull request merged**
