### PR TITLE
Prepare for release- Azure.Core & System.ClientModel

### PR DESCRIPTION
**Pull request by m-redding**

### CODE REVIEW

**Review by annelo-msft — APPROVED** [review]
Do you want to re-release Azure.Core.Experimental as well?  I think it is fine not too.

**Comment by m-redding** [comment]
I think Azure.Core.Experimental is fine not to release since there is a workaround, packages consuming it can just take a direct dependency on STJ if needed.

**Comment by m-redding** [comment]
Need to unblock this PR and the ci has passed, it's just not getting reflected here, 
see: https://dev.azure.com/azure-sdk/public/_build/results?buildId=4214902&view=logs&jobId=f669214d-3e75-537b-cfb3-85562ffe7390

**Pull request merged**
