### PR TITLE
AutoPr-DataFactory-arsunda-REST Spec PrNumber 5468

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by hvermis** [comment]
@dsgouda Is it possible to add spec PR-s to these auto-prs from which they were generated?

**Comment by hvermis** [comment]
@arsunda, please add serialization/deserialization test for your new activity

**Comment by dsgouda** [comment]
@hvermis we have this enabled now

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
