### PR TITLE
Updated hybrid compute project

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
* Based on a newer API version
* Updated tests

Spec: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/hybridcompute/resource-manager/

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
There is no global.json in my project. Please advise how I should deal with this build failure.

**Comment by TylerLeonhardt** [comment]
Thanks @weshaggard - looks like CI is green now :)

**Review by allenjzhang — CHANGES_REQUESTED** [review]
Could you:

 - Add a link to the openapi spec review PR here

 - Check in the metadata TXT file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)

 - Update api tag in `AzSdk.RP.props`, release notes in csproj

 - Update versions in csproj and `assemblyinfo.cs` if you are going to release and version has not bee updated.
 
Thanks

**Comment by TylerLeonhardt** [comment]
@allenjzhang 

> Add a link to the openapi spec review PR here

Is the link to the spec in master what you're looking for? I've added that to the description.

**Comment by TylerLeonhardt** [comment]
@allenjzhang also, is there a doc somewhere on how I can request a release when this PR goes in?

**Comment by TylerLeonhardt** [comment]
Can someone look at this please?

**Comment by TylerLeonhardt** [comment]
Anyone?

**Review by allenjzhang — APPROVED** [review]

**Comment by allenjzhang** [comment]
Merged. I apologize for the delay. This PR somehow disappeared from our triage board.

**Pull request merged**
