### PR TITLE
Updated the BillingRP sdk for backward compatibility

### PR DESCRIPTION
**Pull request by asarkar84**
Updated the BillingRP sdk for backward compatibility
Spec PR link: https://github.com/Azure/azure-rest-api-specs/pull/10048

### CODE REVIEW

**Comment by asarkar84** [comment]
@isra-fel Please take a look at this PR.

**Review by isra-fel — CHANGES_REQUESTED** [review]
Could you

- Update api tag in `AzSdk.RP.props`, release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release

Thanks

**Comment by asarkar84** [comment]
> Could you
> 
> * Update api tag in `AzSdk.RP.props`, release notes in csproj
> * Update versions in csproj and `assemblyinfo.cs` if you are going to release
> 
> Thanks

@isra-fel I have updated the version number and release note in csproj and assemblyInfo.cs. There is no update needed in API Tag. Thank you!

**Comment by asarkar84** [comment]
@isra-fel Please take a look.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
