### PR TITLE
GuestConfiguration SDK update to support ARC senario

### PR DESCRIPTION
**Pull request by gehuang-dut**
Update GuestConfiguration SDK to match newest GuestConfiguration Service Api interface. 

Swagger change approved here:
https://github.com/Azure/azure-rest-api-specs/pull/9595

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hello @gehuang-dut please 
- Check in the metadata TXT file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release
- Write test cases to cover new operations

Thanks

**Comment by gehuang-dut** [comment]
> 
> 
> Hello @gehuang-dut please
> 
>     * Check in the metadata TXT file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
> 
>     * Update release notes in csproj
> 
>     * Update versions in csproj and `assemblyinfo.cs` if you are going to release
> 
>     * Write test cases to cover new operations
> 
> 
> Thanks

Addressed. Thanks.

It will be great if the documentation bellow can be added to SDK repo front-page directly =)

https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec

**Review by isra-fel — APPROVED** [review]
LGTM!

**Comment by isra-fel** [comment]
> It will be great if the documentation bellow can be added to SDK repo front-page directly =)
Good point. Thanks

This "license/cla" status is not passing. I suppose it's because the PR is raised by you but the commits are authored by another user @msft-gehuan (looks like it's your account), so please
- Make sure @msft-gehuan joins Azure orgnization: https://aka.ms/AzureGithub
- Or author the commits by your current account @gehuang-dut

**Comment by gehuang-dut** [comment]
> This "license/cla" status is not passing. I suppose it's because the PR is raised by you but the commits are authored by another user @msft-gehuan (looks like it's your account), so please
> 
>     * Make sure @msft-gehuan joins Azure orgnization: https://aka.ms/AzureGithub
> 
>     * Or author the commits by your current account @gehuang-dut

kick off a new build and the license error is gone. But looks the auto check is extremely slow today. Hitting the run-out-of-time error twice. Looks the system is in unstable status.

**Review by isra-fel — APPROVED** [review]

**Comment by gehuang-dut** [comment]
Thank you.

**Pull request merged**
