### PR TITLE
Update Track2 MGMT Template

### PR DESCRIPTION
**Pull request by HarveyLink**
- Remove old test common reference
 - Add new package reference

### CODE REVIEW

**Comment by markcowl** [comment]
@HarveyLink What validation have you done with the new template?  It would be nice to have at least a manual run of the new template re-generatign an existing service, to verify that it fixes this issue

**Review by markcowl — CHANGES_REQUESTED** [review]
What validation have you done with the new template? It would be nice to have at least a manual run of the new template re-generatign an existing service, to verify that it fixes this issue

**Comment by YalinLi0312** [comment]
> @HarveyLink What validation have you done with the new template? It would be nice to have at least a manual run of the new template re-generatign an existing service, to verify that it fixes this issue

@HarveyLink  and I have fixed the issue in all services when cleaning up TestCommon(https://github.com/Azure/azure-sdk-for-net/pull/15891), this template updates are based on the testCommon cleanup.

**Review by YalinLi0312 — APPROVED** [review]

**Comment by HarveyLink** [comment]
> What validation have you done with the new template? It would be nice to have at least a manual run of the new template re-generatign an existing service, to verify that it fixes this issue

I've validated the empty template creation and building. The change should be good.

**Review by markcowl — APPROVED** [review]

**Pull request merged**
