### PR TITLE
Fixing Typo in Synapse Spark SDK Example

### PR DESCRIPTION
**Pull request by akshatb1**
Fixing Typo in Synapse Spark SDK Example

### CODE REVIEW

**Review by jsquire — APPROVED** [review]
Hi @akshatb1.   Thank you for your contribution.  The changes look good to me; I'll take ownership of getting this merged once you're able to agree to the license.

**Comment by akshatb1** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by akshatb1** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by akshatb1** [comment]
> Hi @akshatb1. Thank you for your contribution. The changes look good to me; I'll take ownership of getting this merged once you're able to agree to the license.

Hi @jsquire , Thanks for reviewing the change. I have agreed to the license.

**Pull request merged**
