### PR TITLE
Test version upgrade

### PR DESCRIPTION
**Pull request by live1206**

### CODE REVIEW

**Comment by jsquire** [comment]
Please include Live test passes as well.

**Comment by live1206** [comment]
> Please include Live test passes as well.

@jsquire Could you help me understand how to include the live tests run? Do we have any existing CI for them?

**Comment by jsquire** [comment]
> > Please include Live test passes as well.
> 
> @jsquire Could you help me understand how to include the live tests run? Do we have any existing CI for them?

Every CI pipeline also has a "tests" pipeline that runs the full live test pass.   You kick them off the same way as CI.     For example, since Event Grid is included in this, I'll kick the live tests pipeline for them..   You'll want to do the same for each library that triggered CI here, and a random samplling.

**Pull request closed without merging**
