### PR TITLE
Fix OOM that could happen on certain HEAD requests

### PR DESCRIPTION
**Pull request by matthchr**
- HEAD for "GetFileProperties" style requests could hit an OutOfMemory exception
  if the file being examined had a large length.
- Added a changelog.md file for better release notes management.

### CODE REVIEW

**Comment by matthchr** [comment]
Not sure why I am showing up as cla-required.

**Comment by matthchr** [comment]
This is related to [this bug fix in AutoRest](https://github.com/Azure/autorest/issues/1456), which is impacting one of our customers.

**Comment by shahabhijeet** [comment]
@matthchr I believe the two new tests that are added are testing the route where the bug was fixed, because it's hard to know what the new tests are doing and if they are indeed testing the bug fix.
Please let us know if they are.

**Comment by matthchr** [comment]
@shahabhijeet Yes -- the two tests cover exactly the case that was triggering the OOM exception. I ran them before I made the change and they failed, then I made the change (regenerated with the new AutoRest code which has the fix) and they passed.

**Pull request merged**
