### PR TITLE
Rename PartitionManager class to StorageManager

### LINKED ISSUE #9497: [EventHubs] Rename PartitionManager class to StorageManager
## Summary

In the last couple of months, the Event Hubs client SDK has gone through a lot of changes, and it has been decided that the name `PartitionManager` does not properly suits its type anymore. For this reason, it will be renamed to `StorageManager`.

The type is `internal` and, therefore, this change is not a breaking one.

It's important to note that currently the `PartitionManager` type dwells in the `Azure.Messaging.EventHubs.Processor` project but, when #9198 is merged, it will be moved to `Azure.Messaging.EventHubs.Shared`.

## Goal

Make sure that the type has been renamed and any mention to a "partition manager" has been updated as well, be it in code or in comments. This should apply to all three projects: `Azure.Messaging.EventHubs`, `Azure.Messaging.EventHubs.Processor` and `Azure.Messaging.EventHubs.Shared`, if applicable.

Tests should still pass constantly.

### PR DESCRIPTION
**Pull request by Marusyk**
Simple renaming

Fixes #9497

Please review
Thank you in advance

### CODE REVIEW

**Review by kinelski — COMMENTED** [review]
Thank you for your contribution, @Marusyk!

It seems you fixed the issue, but you ended up including updates in the `Microsoft.Azure.EventHubs` and `Microsoft.Azure.EventHubs.Processor` projects as well. These correspond to older versions of the Event Hubs SDK (< 5.0.0), and we don't want to rename their `PartitionManager`.

If you take another look at issue #9497, you'll see the projects we are concerned about are `Azure.Messaging.EventHubs`, `Azure.Messaging.EventHubs.Processor` and `Azure.Messaging.EventHubs.Shared`, which are also covered by your PR.

If possible, could you undo your changes to the unrelated projects? I can definitely get the PR approved after that and, once you give it the thumbs up, we can get it merged.

**Review by jsquire — CHANGES_REQUESTED** [review]
Thanks very much for your contribution, @Marusyk!   The changes look good to me, overall.   Apologies for any confusion but, as @kinelski mentioned, we'd like to keep these scoped to the `Azure.Messaging.EventHubs` family of projects.

If you'd be so kind as to revert the changes in the `Microsoft.Azure.EventHubs` projects, I think we should be pretty close to being able to get this merged in.

**Comment by jsquire** [comment]
I saw the changes come through and gave this another pass.  It looks like there is still one set of changes to `Microsoft.Azure.EventHubs.Processor` that we'll need to revert.    Beyond that, looking good!

**Review by jsquire — APPROVED** [review]
LGTM.   Thank you, again, for your contribution @Marusyk!     I think we're ready to merge.   If you would be so kind, would you just leave a comment to let us know that you're not making any further changes and I'll kick off the merge.

**Comment by Marusyk** [comment]
Thank you for review and your time.
I'm not going to make any change.

**Pull request merged**
