### PR TITLE
docs(dpg): add link to quick start tutorial in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by archerzz**
part of #26454

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by lirenhe — APPROVED** [review]

**Review by annelo-msft — COMMENTED** [review]
Oh, good idea to add this to contributing.md!

It looks like we will need to update the generation instructions elsewhere in the file as well, so people don't get the wrong instructions from elsewhere in this long file.  It looks like areas to update should be:
- https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md?plain=1#L358 
- https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md?plain=1#L413

We should remove/update any instructions that we don't want people following anymore.

**Review by annelo-msft — APPROVED** [review]

**Pull request merged**
