### PR TITLE
Update Authorization API to 2020-04-01-preview

### PR DESCRIPTION
**Pull request by dagoroz**
This change updates the Authorization client code to target new functionality introduced in the 2020-04-01-preview version.
Mainly the addition of conditions and descriptions to role assignments

Includes:
* updated client code
* updated session records to reflect missing changes
* added new tests for those changes
* recorded previously skipped test

API Spec: https://github.com/Azure/azure-rest-api-specs/pull/9971

### CODE REVIEW

**Comment by isra-fel** [comment]
The changes LGTM. But you need to update the versions before releasing: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#signing-and-publishing-nuget-packges

**Comment by isra-fel** [comment]
Was this closed by accident? @dagoroz

**Comment by dagoroz** [comment]
@isra-fel No.
I discussed with our PM and they want multiple versions to be released but if I publish this one first it would break semantic versioning.

I will merge the required specs first then come back to the SDKs

**Comment by dagoroz** [comment]
@isra-fel 
I solved this whole situation offline.
this PR is good to go, the swagger has been merged in rest-api-spec and everything :)

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
