### PR TITLE
Added more convenient method to rename database

### PR DESCRIPTION
**Pull request by jaredmoo**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by jaredmoo** [comment]
@kosta-bizetic I have done version bump and release notes for automatic tuning. Please check that the release notes sound good.

**Comment by kosta-bizetic** [comment]
@jaredmoo They are good. Thanks

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
missing meta data file that shows which spec was used to generated the SDK.
If you use generate.cmd, this file is updated automatically

**Comment by jaredmoo** [comment]
There was no regen in this change. I added manually written code.

**Comment by shahabhijeet** [comment]
@azuresdkci retest this please

**Comment by shahabhijeet** [comment]
@jaredmoo all customization should be added under Customization layer.
This can be done by creating a Customization directory and arrange all your hand-written code.
This will help when the next time you regen, your existing code under customization directory will not be modified during regen.

**Comment by jaredmoo** [comment]
That is what I did. I added file `src/SDKs/SqlManagement/Management.Sql/DatabasesOperations.cs`, etc, all the generated files are under `src/SDKs/SqlManagement/Management.Sql/Generated/`.

**Comment by shahabhijeet** [comment]
@jaredmoo the usual behavior for customization is to create a directory called customization.
Because honestly the entire SDK is generated, so the generated directory should not be their.
Other SDKs currently offer this convention and it helps to isolate hand-written code from generated.

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
