### PR TITLE
Update package icon to use the Azure icon

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

**Review by chidozieononiwu — APPROVED** [review]

**Review by AlexGhiondea — CHANGES_REQUESTED** [review]
Marking as request changes so this doesn't get accidentally merged 🙂.

**Comment by KrzysztofCwalina** [comment]
I think we want the icon just for track 2 packages. Track one packages should stay on the old icon

**Review by KrzysztofCwalina — CHANGES_REQUESTED** [review]
I think we want the icon just for track 2 packages. Track one packages should stay on the old icon

**Review by KrzysztofCwalina — APPROVED** [review]

**Review by AlexGhiondea — APPROVED** [review]

**Pull request merged**
