### PR TITLE
AutoPr-MachineLearning-xinzouMicrosoft-REST Spec PrNumber 5241

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by dsgouda** [comment]
@azuresdkci Retest this please

**Comment by dsgouda** [comment]
The generated SDK is failing to compile

**Comment by dsgouda** [comment]
@xinzouMicrosoft the auto generated Sdk fails to compile for some reason, please generate the code using generate.ps1 and open a PR against the repo

**Comment by xinzouMicrosoft** [comment]
@dsgouda, do I need to take any action? I see you commented I should generate code and see PR, but you also close this issue. I'm some confused. please help confirm. Thanks!

**Comment by dsgouda** [comment]
@xinzouMicrosoft please generate the SDK using [this](https://github.com/adxsdknet/azure-sdk-for-net/blob/353784c803fee9fe4fbb57292b0df098cca1867a/src/SDKs/MachineLearning/Management.MachineLearning/generate.cmd) script and open a new PR

**Pull request closed without merging**
