### PR TITLE
[DataFactory] Enable Avro Dataset in SDK

### PR DESCRIPTION
**Pull request by yuzhangyi**

### CODE REVIEW

**Comment by erich-wang** [comment]
@yuzhangyi  , please:
1. Provide the swagger spec PR link related to this PR
2. Please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)

**Comment by yuzhangyi** [comment]
> @yuzhangyi  , please:
> 
> Provide the swagger spec PR link related to this PR
> Please follow the instruction

The public swagger is here: https://github.com/Azure/azure-rest-api-specs/pull/6560

**Review by erich-wang — CHANGES_REQUESTED** [review]
I do not see any update for this comment:
>Please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)

**Comment by erich-wang** [comment]
@yuzhangyi , is this PR still valid?

> I do not see any update for this comment:
> 
> > Please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)

**Comment by yuzhangyi** [comment]
> @yuzhangyi , is this PR still valid?
> 
> I do not see any update for this comment:
> 
> Please follow the instruction

Hi, @erich-wang , this PR is still valid, for related change in public swagger, I have added the link in comment. For the link "instruction", I cannot open it with 404 error, so can you help give the guidance about what I need to do? Thanks

**Comment by erich-wang** [comment]
> > @yuzhangyi , is this PR still valid?
> > I do not see any update for this comment:
> > Please follow the instruction
> 
> Hi, @erich-wang , this PR is still valid, for related change in public swagger, I have added the link in comment. For the link "instruction", I cannot open it with 404 error, so can you help give the guidance about what I need to do? Thanks

@yuzhangyi , the link points to private repo, you should login first and you github account should  have joined Azure organization.

**Comment by yuzhangyi** [comment]
Close this PR firstly and will use newest public swagger to generate SDK in next week.

**Pull request closed without merging**
