### PR TITLE
Remove all Track 1 mgmt. plane SDK code

### LINKED ISSUE #40721: Wipe out all Track 1 source code

### PR DESCRIPTION
**Pull request by ArthurMa1978**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/40721, all Track 1 SDKs  have been removed.
Remaining works: 
1. EngSys & Pipeline related settings, will be removed after this pr merged.
2. Some data plane SDKs are still using Track 1 mgmt. plane libs, should be migrated to Track 2.

### CODE REVIEW

**Review by ArcturusZhang — APPROVED** [review]

**Review by jsquire — APPROVED** [review]

**Comment by jsquire** [comment]
image

YAY!!!!! 

Don't forget to delete any pipelines that are related to areas that no longer exist, please!   We've got a bunch of abandoned ones starting to accumulate.

**Pull request merged**
