### PR TITLE
Key Vault client and samples update

### PR DESCRIPTION
**Pull request by pomortaz**
Ease up the validation on JsonWebKey to avoid breaking client on deserialization. 
Updating sample code to use the new version of the key vault client. 
Update docs. 
Changed the accessibility on the ObjectIdentity fields.

### CODE REVIEW

**Comment by pomortaz** [comment]
@rohmano can you please review?

**Comment by markcowl** [comment]
@pomortaz should we wait for @rohmano review?

**Comment by rohmano** [comment]
@pomortaz @markcowl yes, I will get to this tomorrow.

**Comment by rohmano** [comment]
@pomortaz Looks good, signed off!
@markcowl Please merge.

**Comment by markcowl** [comment]
@pomortaz I see a bunch of small changes in generated code, but no change was made to generate.cmd.  Do these come from a change in the spec or a change in the AutoRest version used?  In either case, geenrate.cmd should be updated to reflect this.

**Comment by pomortaz** [comment]
@markcowl the spec is changed slightly and the code is generated without changing the AutoRest version. So no update to generate.cmd. The code is also not fully generated because the generated code couldn't meet all the changes to the data-plane SDK.

**Pull request merged**
