### PR TITLE
Search SDK: Fixing Timeout and removing unneeded projects from the so…

### LINKED ISSUE #2604: Search SDK: Not possible to set HttpClient.Timeout on new Azure.Search SDK (3.0.1)
We updated to latest version now, since we want to run to the lastest Azure.Search API version.
However, following error occured:

```
var indexClient = _searchConnection.Indexes.GetClient(indexName);
indexClient.HttpClient.Timeout = TimeSpan.FromSeconds(3);
```

The second line is no longer possible. I could however change the timeout for _searchConnection (SearchServiceClient) but that timeout dosnt follow when creating a client. Will you fix this or how is your suggestion? To have 1min and 30s timeout is not acceptable for us (default).

### PR DESCRIPTION
**Pull request by bitsforthought**
…lution

## Description

Fixes #2604

Now when you call `searchClient.Indexex.GetClient()`, it will propagate the `Timeout` value set on the searchClient's `HttpClient`.

FYI @markcowl: We're removing project references to TestFramework, HttpRecorder, and the ClientRuntime libraries. We prefer NuGet references over project references for the Search SDK solution for a couple reasons:

- It speeds up build times.
- It avoids build errors when the dependent projects change in unpredictable ways.
- It avoids the dreaded "An item with the same key has already been added" build error (see https://github.com/dotnet/cli/issues/1860)

Finally, we're also bumping the version of the data plane SDK to 3.0.2 and fixing some typos.

There are no Swagger or generated code changes for this PR.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [X] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by brjohnstmsft** [comment]
FYI @chaosrealm @seansaleh

**Comment by chaosrealm** [comment]
:dart:

**Comment by hovsepm** [comment]
@brjohnstmsft Travis build is broken due to coreclr package unavailability for Ubuntu. We do not have any ETA when this will be fixed yet. Please contact me via IM if you need this to be merged ASAP.

**Comment by brjohnstmsft** [comment]
@hovsepm Thanks for letting me know. It's not super urgent. I'll check back with you in a few days.

**Comment by hovsepm** [comment]
@brjohnstmsft Travis is fixed and this PR is merged.

**Comment by brjohnstmsft** [comment]
@hovsepm Thanks!

**Pull request merged**
