### PR TITLE
Microsoft.Azure.Management.Storage 7.0.0

### PR DESCRIPTION
**Pull request by JasonYang-MSFT**
## Description

This PR include three changes:
1. adding SKU.list() operation, refer to swagger PR: Azure/azure-rest-api-specs#1579.
2. renaming networkAcl to networkRuleSet: Azure/azure-rest-api-specs#1494.
3. upgrade autorest to newest.

Swagger Spec: https://github.com/Azure/azure-rest-api-specs/blob/current/specification/storage/resource-manager/Microsoft.Storage/2017-06-01/storage.json

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by JasonYang-MSFT** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/1494

**Comment by JasonYang-MSFT** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/1579

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Please provide the description of this PR.
Rest Spec PR link.
Also why are you bumping up major version in a preview nuget package?

**Comment by JasonYang-MSFT** [comment]
hi @shahabhijeet , Spec PR link and description are added.
There is a breaking change in this PR(renamed networkAcl to networkRuleSet).
Though this is only a preview SDK, we usually bump up major version once there is breaking change.

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
