### PR TITLE
https://github.com/Azure/azure-sdk-for-net/issues/958

### PR DESCRIPTION
**Pull request by chuanboz**
Avro serializer bug: Array schema are incorrectly generated as known type of any collection member in that class. #958

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chuanboz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by chuanboz** [comment]
for the contribution license agreement, there are 3 options, shall I choose option 1 or 2?
I'm Microsoft Employee.

**Comment by ogail** [comment]
@chuanboz some of this code is auto-generated you need to change the specs behind it so it does not get overridden

**Comment by chuanboz** [comment]
@ogail @djoelz 
please discard this pull request, the latest one that is sync to hdinsight dev branch and fixed all review comments is in below link.
https://github.com/hdinsight/azure-sdk-for-net/pull/56

**Pull request closed without merging**
