### PR TITLE
AutoPr-Compute-vamuzumd-REST Spec PrNumber 5740

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by hyonholee** [comment]
@shahabhijeet could you merge this PR?  we need to publish fixed SDK by today.  Thanks

**Review by dsgouda — APPROVED** [review]
LGTM

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
Jenkins build has passed

**Pull request merged**
