### PR TITLE
[Datafactory] Enable Avro Dataset in SDK

### PR DESCRIPTION
**Pull request by yuzhangyi**

### CODE REVIEW

**Comment by erich-wang** [comment]
@yuzhangyi , please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec) to update the PR. Considering swagger spec is the contract between SDK and service team, any change in master branch should be ready for generating SDK. I think you don't worry about that the generated code contains someone else's change.

**Review by erich-wang — CHANGES_REQUESTED** [review]
Please add related swagger spec PR related to this PR as well.

**Comment by yuzhangyi** [comment]
> ger spec PR related to this PR as well

Related change of public swagger is here: https://github.com/Azure/azure-rest-api-specs/pull/6816

**Comment by yuzhangyi** [comment]
> @yuzhangyi , please follow the instruction to update the PR. Considering swagger spec is the contract between SDK and service team, any change in master branch should be ready for generating SDK. I think you don't worry about that the generated code contains someone else's change.

I have updated it based on the "instruction", @erich-wang, please help review it again, thanks!

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
