### PR TITLE
Fix build issue with FileConventions signing

### PR DESCRIPTION
**Pull request by matthchr**

### CODE REVIEW

**Comment by matthchr** [comment]
@hovsepm -- If @itowlson is okay with this then you can merge it -- please wait for his confirmation though.

**Comment by itowlson** [comment]
Looks okay to me - thanks @matthchr!

**Comment by matthchr** [comment]
@hovsepm Feel free to merge this

**Comment by hovsepm** [comment]
http://azuresdkci.cloudapp.net/view/2-.NET%20SDK/job/sdk-for-net-sign/1271/
once this will pass I'll merge.

**Pull request merged**
