### PR TITLE
Prevent pump from stop processing by ignoring ObjectDisposedException

### PR DESCRIPTION
**Pull request by petrformanek**
## Description

Fix for [issue 687](https://github.com/Azure/azure-service-bus-dotnet/issues/687).

### CODE REVIEW

**Comment by petrformanek** [comment]
Hello @axisc can anybody approve this PR?

**Comment by ramya-rao-a** [comment]
@binzywu, Can you have someone from your team take a look at this PR?

**Comment by ramya-rao-a** [comment]
@binzywu Assigning you as the reviewer for now, let me know if you want to move it to anyone else.
cc @AlexGhiondea

**Review by axisc — APPROVED** [review]

**Comment by inech** [comment]
It's actually a duplicate of https://github.com/Azure/azure-sdk-for-net/pull/6483

**Review by nemakam — CHANGES_REQUESTED** [review]
Thanks for the PR, but as suggested by @inech, it's a duplicate of #6483 
This PR will be closed.

**Pull request closed without merging**
