### PR TITLE
AutoPr-KeyVault-KarishmaGhiya-REST Spec PrNumber 5563

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by weshaggard** [comment]
@shahabhijeet Any idea whether or not this Auto-PR should have been generated? It is based off a change to a config for js in the sepc repo at https://github.com/Azure/azure-rest-api-specs/pull/5563. Perhaps this triggered because of another earlier PR that didn't get merged based on a spec update but I wanted to be sure this is expected or if we should close it since it isn't related?

**Comment by dsgouda** [comment]
@weshaggard The last commit to the directory was on Feb 13 [here](https://github.com/Azure/azure-rest-api-specs/commit/ee6addc89d50430213ddd299ee006e504b4b302d#diff-df87df607a2fee30c652fc0c340d0650), a day before we enabled auto generation of Net Sdk PRs

**Comment by weshaggard** [comment]
@dsgouda so should we let this PR merge or is there some other process to getting things in-sync?

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@weshaggard Feel free to merge once Rest spec PR is merged.

**Pull request merged**
