### PR TITLE
Removing unnecessary properties from TeradataLinkedService

### PR DESCRIPTION
**Pull request by adiedrich**
Remove obsolete properties from TeradataLinkedService for Azure Data Factory

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adiedrich__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by yugangw-msft** [comment]
retest this please

**Comment by yugangw-msft** [comment]
retest this please

**Comment by ogail** [comment]
@azuresdkci add to whitelist

**Pull request merged**
