### PR TITLE
fix(doc): Fix markdown for API design doc

### PR DESCRIPTION
**Pull request by abhipsaMisra**

### CODE REVIEW

**Review by drwill-ms — APPROVED** [review]

**Review by bikamani — APPROVED** [review]

**Review by vinagesh — APPROVED** [review]

**Comment by abhipsaMisra** [comment]
@pakrym Does the check-enforcer require a code-owner approval (even for merging into feature branches)? The tool has been stuck "in-progress", so I am trying to figure out what checks are missing for us.

**Comment by pakrym** [comment]
Please ping the "Engineering System" channel on Teams, they own the check-enforcer.

**Comment by weshaggard** [comment]
check-enforcer is not turning green because there are no other ci checks setup and running for your changes. Given this is only a md file change we can ignore this but we should get a ci job setup for changes under iot when code starts to change.

**Pull request merged**
