### PR TITLE
Fix double dispose in BlobBatch

### PR DESCRIPTION
**Pull request by AlexanderSher**
Make `BlobBatch` resilient to multiple disposes

### CODE REVIEW

**Comment by seanmcc-msft** [comment]
We should update the Blob Batch changelog - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs.Batch/CHANGELOG.md

Let's hold off on merging this until after the GA release we are doing today.

**Review by JoshLove-msft — APPROVED** [review]

**Review by seanmcc-msft — APPROVED** [review]

**Comment by seanmcc-msft** [comment]
The build is failing for an unrelated reason.

**Comment by seanmcc-msft** [comment]
CI is fixed in main

**Pull request merged**
