### PR TITLE
[do not merge]Dev/xiowei/perf maintenance

### PR DESCRIPTION
**Pull request by vanbasten2323**
## Description
Added MaintenanceStatus to the response field of Get-AzureVM command; Added new command InitiateMaintenance which calls the RDFE API PerformMaintenanceOnRoleOperation.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vanbasten2323__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (xiowei). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by huangpf** [comment]
@markcowl For ASM, shall we target branch master or branch AutoRest?

**Comment by markcowl** [comment]
Please rebase your changes on the tip of the branch.

**Comment by huangpf** [comment]
@markcowl I think @vanbasten2323 needs to send the pull request against ```master``` branch.

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by cormacpayne** [comment]
Waiting for spec to be merged: https://github.com/Azure/hydra-specs-pr/pull/1373

**Comment by markcowl** [comment]
@vanbasten2323 The specs pr is marked as 'do not merge'  Closing this until you merge the spec

**Pull request closed without merging**
