### PR TITLE
[ContainerRegistry] Remove Track-1 Pipeline

### PR DESCRIPTION
**Pull request by ShivangiReja**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by benbp** [comment]
@ShivangiReja do you need me to delete the underlying pipeline as well? Currently the automation is only additive.

**Comment by ShivangiReja** [comment]
@benbp Yes, we need to delete the underlying pipeline, since we are deprecating track-1 package.

**Review by benbp — APPROVED** [review]

**Comment by benbp** [comment]
@ShivangiReja I cleaned up the pipelines.

**Comment by ShivangiReja** [comment]
Thanks @benbp!

**Pull request merged**
