### PR TITLE
[Azure.Core.Amqp] Fix AmqpMessageBodyTests

### PR DESCRIPTION
**Pull request by 0xced**
The `DateTime` and `DateTimeOffset` test values in `AmqpMessageBodyTests.s_amqpValues` were created with `DateTimeOffset.Parse`, which would fail with the following exception when run on a system with a non-US culture:
```
System.TypeInitializationException : The type initializer for 'Azure.Core.Amqp.Tests.AmqpMessageBodyTests' threw an exception.
  ----> System.FormatException : String was not recognized as a valid DateTime.
   at Azure.Core.Amqp.Tests.AmqpMessageBodyTests..ctor()
--FormatException
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input)
   at Azure.Core.Amqp.Tests.AmqpMessageBodyTests..cctor()
```

By using `new DateTimeOffset(2021, 3, 24, 0, 0, 0, TimeSpan.Zero)` instead of `DateTimeOffset.Parse("3/24/21")` we ensure that the tests pass on any system regardless of its configured culture.

### CODE REVIEW

**Review by jsquire — APPROVED** [review]
Hi @0xced.   Thank you for your contribution and for helping to improve the Azure SDK experience.  The change looks good to me.   

The CI failures that we're seeing appear to be related to a missing file in another area.   Would you be so kind as to try rebasing your changes onto the latest from `main` and see if that resolves?

**Comment by jsquire** [comment]
@JoshLove-msft:   Would you mind taking a look as well?   I think the CI failures may be related to one of the recent Event Grid changes...

**Comment by 0xced** [comment]
> Would you be so kind as to try rebasing your changes onto the latest from main and see if that resolves?

The latest commit on main (cbad4bb143cd1e8c59afbb3f52dc864d708f2522) is from three days ago and I just did this pull request today on top of this commit so there's nothing new I can rebase on. Maybe another branch needs to be merged on `main` first?

**Comment by JoshLove-msft** [comment]
Created https://github.com/Azure/azure-sdk-for-net/pull/22012

**Pull request merged**
