### PR TITLE
Switch to using Azure.Core preview 8 package

### PR DESCRIPTION
**Pull request by pakrym**
It's out https://www.nuget.org/packages/Azure.Core/1.0.0-preview.8 !

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

**Comment by weshaggard** [comment]
Should we also remove https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/Directory.Build.props#L36? While I don't think it impacts this particular update it seems like it is redundant and likely to only cause confusion.

**Comment by pakrym** [comment]
Didn't know that line exists, why was it required?

**Comment by jsquire** [comment]
> Didn't know that line exists, why was it required?

Pretty sure its a legacy artifact from before the "props" reference for Core was a thing.   That said, in order to not potentially introduce risk during the release, can we please leave as-is and I'll investigate removing it in the next PR that I put out?

**Comment by pakrym** [comment]
We are still using props reference to Azure.Core but I'll leave `Azure.Messaging.EventHubs/Directory.Build.props` as is as part of this PR.

**Comment by jsquire** [comment]
> We are still using props reference to Azure.Core but I'll leave `Azure.Messaging.EventHubs/Directory.Build.props` as is as part of this PR.

I mean that I'm fairly sure that line was added before we moved to the "props" file for referencing core.  I recall another approach that we used earlier, about the time that I needed the `TokenCredential` dependency.

**Comment by weshaggard** [comment]
>Pretty sure its a legacy artifact from before the "props" reference for Core was a thing. That said, in order to not potentially introduce risk during the release, can we please leave as-is and I'll investigate removing it in the next PR that I put out?

That is fine as long as messaging ends up with the correct package version in its dependencies.

**Pull request merged**
