### PR TITLE
Added DataLake Gen1 -> Gen2 mapping

### PR DESCRIPTION
**Pull request by seanmcc-msft**

### CODE REVIEW

**Review by gapra-msft — APPROVED** [review]

**Comment by tg-msft** [comment]
Should we call this DataLakeGen2MigrationGuide.md?  And any reason to use HTML tables instead of [markdown tables?](https://www.markdownguide.org/extended-syntax/#tables)

**Comment by seanmcc-msft** [comment]
This file's name and HTML tables match https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-datalake/GEN1_GEN2_MAPPING.md and https://github.com/Azure/azure-sdk-for-python/pull/8751

**Comment by seanmcc-msft** [comment]
@xiafu-msft wrote the original doc, and chose to use HTML tables because they offered more flexibility than markdown tables.

**Comment by tg-msft** [comment]
Should we change these to `DataLakeGen2MigrationGuide.md` everywhere?  I don't know that `Mapping.md` is as obvious as `MigrationGuide.md`.  It might also be good to link to these from the DataLake readmes.

**Comment by seanmcc-msft** [comment]
Talk to @xiafu-msft and @gapra-msft, they took the lead on this.

**Pull request merged**
