### PR TITLE
StorSimple : Taking the clone and virtual disk changes

### PR DESCRIPTION
**Pull request by parvezah**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@parvezah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (parvezah). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
add to whitelist

**Comment by avirupch** [comment]
Are the clone file changes intended?

**Comment by avirupch** [comment]
Also, update the build number in Microsoft.WindowsAzure.Management.StorSimple.nuget.proj in case you require a new .NET sdk nuget package.

**Pull request merged**
