### PR TITLE
Introducing new Microsoft.Azure.Monitor.dll for the Monitor team (formerly Insights)

### PR DESCRIPTION
**Pull request by gucalder**
## Description

Introducing a new folder in this repo: **monitor**, which contains the code generated from the new Swagger specs folders called monitor, arm-monitor (PR merged recently https://github.com/Azure/azure-rest-api-specs/pull/936).

With this we are effectively introducing a new SDK dll called **Microsoft.Azure.Monitor.dll** intended to replace _Microsoft.Azure.Insights.dll_. 
The contents of the dlls are almost identical with these differences:
- Monitor.dll does **not** contain the _old Metrics API_
- Some minor improvements derived from the process of validation of the Swagger spec.
- One change due to the resolution of an issue with the Python CLI generation.
- The **Events** operations were renamed to **ActivityLogs**, but their calls remain unchanged.

This name change is intended to avoid confusions with AppInsights artifacts and to align with the new name of our team.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by gucalder** [comment]
The errors don't seem to be coming from our code, but from Data Lake's.

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@twitchax  Please let us know how to handle this - should this be a new package, or a new version of Insights?  It looks liek the namespaces in AzureRm have not changed.  Needf to reach out to the PMs on the team to decide.

**Comment by twitchax** [comment]
Based on previous discussions with them, this should be a separate package, and the old package will no longer ship (it was in preview).

**Comment by twitchax** [comment]
Synced with them, and this should be a new package.

**Comment by twitchax** [comment]
@markcowl: discussed the deprecation of the "Insights" package and redirection to the "Monitor" package...got the go ahead.

**Pull request merged**
