### PR TITLE
Fix the timing-out problem in UsGov cloud

### PR DESCRIPTION
**Pull request by zedy-wj**
1. Fix Issue #13669

2. Azure Form Recognizer is not available in Azure China Cloud now, so we should not run form recognizer live tests in this cloud. [Details](https://azure.microsoft.com/en-us/global-infrastructure/services/?products=cognitive-services)

### CODE REVIEW

**Comment by maririos** [comment]
Change so far LGTM. You could always remove lines https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/tests.yml#L18-L20 and remove `China` from the `SupportedClouds` https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/tests.yml#L21

**Comment by zedy-wj** [comment]
@maririos - Removed China cloud from tests.yml file.

**Review by maririos — APPROVED** [review]
The test here has been fixed. Thanks @zedy-wj for your work!

**Pull request merged**
