### PR TITLE
Update Azure Batch C# library to version 5.0

### PR DESCRIPTION
**Pull request by matthchr**
- Add FileHelpers library
- Add support for PATCH

### CODE REVIEW

**Comment by matthchr** [comment]
Note to reviewer: We have already squashed a bunch of commits, so ideally we don't have to squash any more (there really are ~30 commits worth of work done here).

If that's not okay let us know and we can figure out what we need to do

**Comment by hovsepm** [comment]
@matthchr Please add license header to all the source files.

**Comment by matthchr** [comment]
Good eye @hovsepm -- will do.

**Comment by matthchr** [comment]
@hovsepm The test files too?

**Comment by matthchr** [comment]
@hovsepm License added to the top of the CS files and removed the file you pointed out where we had a comment suggesting that it shouldn't exist.

**Comment by kirthik** [comment]
test this please

**Comment by matthchr** [comment]
@hovsepm Looks like everything is passing now. Thanks @kirthik

**Pull request merged**
