### PR TITLE
Add Authorized Key Parameter

### PR DESCRIPTION
**Pull request by dihan0604**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dihan0604__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dihan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@dihan0604 Please pull the latest - there are merge conflicts - also, please add a test for the new functionality

@DeepakRajendranMsft  can you review this change

**Comment by dihan0604** [comment]
Add Nilambari.

Thanks
Ding

**Comment by nupurkot** [comment]
LGTM

**Comment by dihan0604** [comment]
Have addressed the comment and ask Nupur looked. There are already test coverage for this API and we have add tests in powershell for testing this extra parameter

**Comment by dihan0604** [comment]
Please merge it so that i can generate package to verify power shell change.

**Pull request merged**
