### PR TITLE
Hotfix/sb patch 7.1.1

### PR DESCRIPTION
**Pull request by JoshLove-msft**

### CODE REVIEW

**Comment by JoshLove-msft** [comment]
@weshaggard should it be possible to run the test pipeline from this patch PR?

**Comment by JoshLove-msft** [comment]
> @weshaggard should it be possible to run the test pipeline from this patch PR?

Nevermind I guess I need to use the devops UI.

**Review by jsquire — APPROVED** [review]
LGTM

**Review by pakrym — APPROVED** [review]

**Pull request merged**
