### PR TITLE
[Do-Not-Merge]Generated sdk for "Added application profile for VM and VMSS to specs"

### PR DESCRIPTION
**Pull request by D1v38om83r**
Api pull request https://github.com/Azure/azure-rest-api-specs/pull/11431

Do not merge, this PR is to confirm that .Net SDK code can be generated from Swagger change.

### CODE REVIEW

**Comment by bquantump** [comment]
@D1v38om83r Please try the debug steps for the check enforcer.

**Comment by bquantump** [comment]
@D1v38om83r any update on this? If we don't hear anything back, we will close this at the end of this week.

**Comment by D1v38om83r** [comment]
> @D1v38om83r any update on this? If we don't hear anything back, we will close this at the end of this week.

The PR was to prove that the SDK could be generated from the updated Swagger specs. The PR is not intended to be merged. We can't add the tests yet because of ARM manifest deployment issue. Can you please a some documentation on how to perform "Please try the debug steps for the check enforcer" if it is required for this PR to be considered valid?

**Comment by bquantump** [comment]
> > @D1v38om83r
> >             
> >             Bhaskar Brahma
> >             FTE any update on this? If we don't hear anything back, we will close this at the end of this week.
> 
> The PR was to prove that the SDK could be generated from the updated Swagger specs. The PR is not intended to be merged. We can't add the tests yet because of ARM manifest deployment issue. Can you please a some documentation on how to perform "Please try the debug steps for the check enforcer" if it is required for this PR to be considered valid?

https://github.com/Azure/azure-sdk-for-net/pull/16805#issuecomment-724422035

**Comment by D1v38om83r** [comment]
> > > @D1v38om83r
> > > ```
> > >         Bhaskar Brahma
> > >         FTE any update on this? If we don't hear anything back, we will close this at the end of this week.
> > > ```
> > 
> > 
> > The PR was to prove that the SDK could be generated from the updated Swagger specs. The PR is not intended to be merged. We can't add the tests yet because of ARM manifest deployment issue. Can you please a some documentation on how to perform "Please try the debug steps for the check enforcer" if it is required for this PR to be considered valid?
> 
> [#16805 (comment)](https://github.com/Azure/azure-sdk-for-net/pull/16805#issuecomment-724422035)

I have tried all the commands listed in that auto generated commend except for override. https://github.com/Azure/azure-sdk-for-net/pull/16805/checks?check_run_id=1482047782 doesn't lead to any logs, I only have a link to the repo for check-enforcer which has a additional command /check-enforcer reset, but that doesn't do anything either. 

Where can I get the logs to debug the check-enforcer?

**Comment by bquantump** [comment]
> > > > @D1v38om83r
> > > >             
> > > >             Bhaskar Brahma
> > > >             FTE
> > > > ```
> > > >         Bhaskar Brahma
> > > >         FTE any update on this? If we don't hear anything back, we will close this at the end of this week.
> > > > ```
> > > 
> > > 
> > > The PR was to prove that the SDK could be generated from the updated Swagger specs. The PR is not intended to be merged. We can't add the tests yet because of ARM manifest deployment issue. Can you please a some documentation on how to perform "Please try the debug steps for the check enforcer" if it is required for this PR to be considered valid?
> > 
> > 
> > [#16805 (comment)](https://github.com/Azure/azure-sdk-for-net/pull/16805#issuecomment-724422035)
> 
> I have tried all the commands listed in that auto generated commend except for override. https://github.com/Azure/azure-sdk-for-net/pull/16805/checks?check_run_id=1482047782 doesn't lead to any logs, I only have a link to the repo for check-enforcer which has a additional command /check-enforcer reset, but that doesn't do anything either.
> 
> Where can I get the logs to debug the check-enforcer?

@weshaggard

**Comment by jsquire** [comment]
Hi @D1v38om83r.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by D1v38om83r** [comment]
> Hi @D1v38om83r. There hasn't been recent engagement on this PR. Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

We are now adding recorded tests for the newly created SDK.

**Comment by Sandido** [comment]
Swagger PR is being reverted, feature requires further development.

**Pull request closed without merging**
