### PR TITLE
Storage/test infra/test fixture abstraction

### PR DESCRIPTION
**Pull request by jaschrep-msft**
With the adoption of a new test class inheritance pattern for cross-service tests, it has become harder to keep test service version declarations in sync. Each service has to separately declare it's service versions with the attribute, and now that not every test inherits from `BlobTestBase` (or equivalent), they don't get the service version declarations that was made there.

This PR extends `ClientTestFixtureAttribute` in each service package and gives that sub-class an empty constructor that calls into its base constructor the way individual attribute declarations were previously invoking it. Now that class is the only place those declarations need to be updated and any test class can add that attribute to get all of the up-to-date testing service version management for free.

Did not extend to Queues tests because this doesn't appear to be a concern there.

### CODE REVIEW

**Comment by jaschrep-msft** [comment]
This appears to cause no changes in testing. Tests continued to pass locally, and Visual Studio Test Explorer detected the same tests before and after the change, including recognizing service versions and sync/async configurations for test fixtures.

**Review by seanmcc-msft — APPROVED** [review]
Approved, but let's run the live tests before merging.

**Comment by seanmcc-msft** [comment]
Also we need to run the weekly tests after the nightly tests pass

**Pull request merged**
