### PR TITLE
Update ARM-Network SDK with IPv6 and IDNS Properties.

### PR DESCRIPTION
**Pull request by ankurchoubeymsft**
Updates SDK generated with updated swagger spec and includes IPv6 and IDNS Properties. Also added test cases and session records for the new properties added. Incremented project and assembly version.

### CODE REVIEW

**Comment by DeepakRajendranMsft** [comment]
LGTM

**Comment by DeepakRajendranMsft** [comment]
@hovsepm  the CI build not kicked off for this PR. Can we kick that off please? thanks

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by ankurchoubeymsft** [comment]
@azuresdkci : Is there any other action/check required for the PR?

**Pull request merged**
