### PR TITLE
Adding Microsoft analyzers to Azure Search SDK

### PR DESCRIPTION
**Pull request by Yahnoosh**
We have recently enabled new set of language analyzers in our GA API version. This change adds these analyzers to the SDK.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Yahnoosh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by Yahnoosh** [comment]
Azure Search SDK, We have recently enabled new set of language analyzers in our GA API version. This change adds these analyzers to the SDK.

**Comment by azurecla** [comment]
Hi __@Yahnoosh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@Yahnoosh__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by ogail** [comment]
@azuresdkci add to whitelist

**Pull request merged**
