### PR TITLE
[StreamAnalytics] Update sdk to 2020-03-01-preview version

### PR DESCRIPTION
**Pull request by sunsw1994**
swagger pr: https://github.com/Azure/azure-rest-api-specs/pull/10673
tag: package-2020-03-preview

1. Add missing features for ASA streaming job 
2. Add ASA cluster and private endpoint related sdk

### CODE REVIEW

**Review by allenjzhang — CHANGES_REQUESTED** [review]
Could you:

 - Check in the metadata TXT file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)

 - Update api tag in `AzSdk.RP.props`, release notes in csproj

 - Update versions in csproj and `assemblyinfo.cs` if you are going to release
 
Thanks

**Comment by sunsw1994** [comment]
@allenjzhang  addressed comments, could you help us to re-review that, thank you a lot.

**Review by allenjzhang — CHANGES_REQUESTED** [review]
Thank you for your recent update. Can you make two minor changes, and we will be all good.
1. Update the version number in assemblyinfo.cs
2. Add some meaning release notes in the csproj. They will show up front and center on nuget to give user context on the new release of libraries. It is particularly helpful since the major version has changed.

**Comment by sunsw1994** [comment]
> Thank you for your recent update. Can you make two minor changes, and we will be all good.
> 
> 1. Update the version number in assemblyinfo.cs
> 2. Add some meaning release notes in the csproj. They will show up front and center on nuget to give user context on the new release of libraries. It is particularly helpful since the major version has changed.

Thanks for your comments. Updated.

**Comment by sunsw1994** [comment]
@allenjzhang addressed comments, could you help us to re-review that, thank you a lot.

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
