### PR TITLE
Add Basic Sku Definition

### PR DESCRIPTION
**Pull request by solankisamir**
## Description
---

 Add SKU definition to .NET nuget
 Corresponding HYAK Spec PR is here https://github.com/Azure/hydra-specs-pr/pull/1399

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by solankisamir** [comment]
@shahabhijeet can you take a look? This is small change we must to take on hyak based .net repository.

**Comment by shahabhijeet** [comment]
@solankisamir I am not sure if this PR can be merged, this PR is almost impossible to make it.
We are not taking any changes on hyak based SDK, unless you have a migrating feature or a really high customer impact hot fix.
If it's customer impact hot fix, pleaes provide the impact analysis

**Comment by solankisamir** [comment]
@shahabhijeet we have a migration in process https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/ApiManagement, which is missing a few changes before we release it. This issue is impacting customers right now and this is the fastest mitigation we can do now. We have received multiple customer requests to support it in powershell, hence the change.

**Comment by solankisamir** [comment]
@ailn  does not work on this repository, adding @KedarJoshi.

**Comment by shahabhijeet** [comment]
@solankisamir as I said, it has to be a customer issue that has a considerable impact.
We are not accepting any requests as of now. I am sorry but this PR will not be accepted in this form.

**Pull request closed without merging**
