### PR TITLE
Documentation update for the Azure Support management SDK

### PR DESCRIPTION
**Pull request by shahbj79**
- This change updates Azure Support management SDK with documentation updates from latest swagger file. No code change.
- Here is the link to API [Spec ](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/support/resource-manager/Microsoft.Support/stable/2020-04-01/support.json)

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Please update `AssemblyFileVersion` in `AssemblyInfo.cs`. Thanks

**Comment by shahbj79** [comment]
> Please update `AssemblyFileVersion` in `AssemblyInfo.cs`. Thanks

Fixed

**Comment by shahbj79** [comment]
@isra-fel @erich-wang - looks like some tests under Azure.Messaging.EventHubs are failing. Can you please check?

**Review by isra-fel — APPROVED** [review]

**Comment by ganganarayanan** [comment]
@isra-fel Is there an update on this? When can we push the release for PS?

**Pull request merged**
