### PR TITLE
Added HttpAuthorization

### PR DESCRIPTION
**Pull request by seanmcc-msft**
After Core has shipped, we will remote `HttpAuthorization` from Azure.Storage.Common.

### CODE REVIEW

**Review by kasobol-msft — APPROVED** [review]
lgtm

**Review by amnguye — APPROVED** [review]

**Comment by pakrym** [comment]
Did we get an API approval for this?

**Comment by seanmcc-msft** [comment]
Yes, @tg-msft mentioned this at 38:30 in [STG 79 Feature Info](https://msit.microsoftstream.com/video/7aba0840-98dc-b561-357b-f1ebf9654aef).

**Comment by pakrym** [comment]
Can you please start an email thread with @KrzysztofCwalina and @tg-msft and get more official approval for this API?

**Comment by seanmcc-msft** [comment]
Added you to the existing email thread.

**Comment by seanmcc-msft** [comment]
@tg-msft, any idea why Build Analyze is failing?  I have merged main -> this branch, ran Export-API.ps1, Update-Snippets.ps1, and ran dotnet build /t:GenerateCode in the sdk\core\Azure.Core\src directory.

**Comment by kasobol-msft** [comment]
> @tg-msft, any idea why Build Analyze is failing? I have merged main -> this branch, ran Export-API.ps1, Update-Snippets.ps1, and ran dotnet build /t:GenerateCode in the sdk\core\Azure.Core\src directory.

It seems to be unhappy about Storage.Commons (Core runs this step for all packages)

**Comment by seanmcc-msft** [comment]
@kasobol-msft, I think I need to bring `HttpAuthorization` back in Azure.Storage.Common so we can pass the package reference CI steps.

**Comment by kasobol-msft** [comment]
> @kasobol-msft, I think I need to bring `HttpAuthorization` back in Azure.Storage.Common so we can pass the package reference CI steps.

That can't stay in storage commons (assuming we didn't GA that by accident), we can't have same type in both assemblies. 

@pakrym did `UseProjectReferenceToAzureClients` stopped working or it doesn't work transitively? looks like only `PackageRef` jobs failed.

**Comment by pakrym** [comment]
>or it doesn't work transitively

Yep, you have to set it on the `dotnet build` invocation so all projects get it. It doesn't flow with Project-to-project references.

**Comment by seanmcc-msft** [comment]
TODO add comment with link to https://github.com/Azure/azure-sdk-for-net/issues/21875 in Azure.Storage.Common.csproj

**Comment by seanmcc-msft** [comment]
@tg-msft, @KrzysztofCwalina, could you approve this PR?

**Review by tg-msft — APPROVED** [review]
Looks great!

**Pull request merged**
