### PR TITLE
Add DefaultLanguage and DefaultStringIndexType

### LINKED ISSUE #22887: Use StringIndexType from Azure.Core and default to UTF-16
There was some talk about putting `StringIndexType` into Azure.Core, and @annatisch suggested we default it to UTF-16 if not hide it all together.

/cc @maririos

### PR DESCRIPTION
**Pull request by heaths**
Resolves #22887

### CODE REVIEW

**Comment by heaths** [comment]
@maririos, @tg-msft, @iscai-msft, and @rokulka this is to do something similar to Text Analytics and address #22887. Text Analytics has a `DefaultLanguage` but does not have an option for `StringIndexType`. Instead, it has several methods that allow passing it in, but with `QueryTextOptions` it's a model property. We could completely unroll the model and have methods with numerous parameters, but I think this way is more congruent with default options in other service clients.

Thoughts?

I wanted to post a draft before adding additional unit and live integration tests.

**Comment by heaths** [comment]
I also wanted to add that I think this jives better with .NET recommendations. Should `QueryText` take more parameters later, we'd add an options class anyway like the one that already gets generated. Overloads that take an options class tend to be the be-all-end-all overloads where anything is possible.

**Comment by maririos** [comment]
>@maririos, @tg-msft, @iscai-msft, and @rokulka this is to do something similar to Text Analytics and address #22887. Text Analytics has a DefaultLanguage but does not have an option for StringIndexType. Instead, it has several methods that allow passing it in, but with QueryTextOptions it's a model property. We could completely unroll the model and have methods with numerous parameters, but I think this way is more congruent with default options in other service clients.
Thoughts?

Although we do this in Text Analytics, we don't do it in Form Recognizer or Document Translation. We leave it up to the service to use their default value. The main reason we have it is in case someone doesn't want to set the property per call. I haven't heard good things or bad things about it though, so it also depends on what the scenario for language is in this library.

Something to consider before adding it:
- Are there any cases where not specifying a language is different than directly specifying `en`? 
- Do you do any string manipulation work in the library that depends on the StringIndexType? Is there an advantage to expose it instead of having it hidden, wait for feedback or specific asks and so, consider exposing it in the future?

**Comment by heaths** [comment]
> Are there any cases where not specifying a language is different than directly specifying "en"?

Not that I'm aware. As discussed offline, I still like the idea of declaring this default (to set a client-wide default) but can keep the default null and let the service default apply. Probably will still document it, but maybe include a link to the service docs so users can check. This way we're not tightly coupling. @iscai-msft @rokulka what do you think?

> Do you do any string manipulation work in the library that depends on the StringIndexType? Is there an advantage to expose it instead of having it hidden, wait for feedback or specific asks and so, consider exposing it in the future?

Probably not. I'll do like you did in TA for now and we'll wait for feedback. 🙏

**Review by iscai-msft — APPROVED** [review]

**Review by maririos — APPROVED** [review]

**Comment by rokulka** [comment]
@heaths  - Agree with both the changes.

**Pull request merged**
