### PR TITLE
[FR] Enable tests

### LINKED ISSUE #16827: Table bounding box not returned consistently
Seeing this currently in Custom Forms but need more testing to see if it is because of deployment or a bug from the service

### LINKED ISSUE #18216: Business Cards returns Appearance.Style.Name == print
The Business Cards endpoint is returning `print` as an `Appearance.Style.Name` value. And although it is designed as an extensible enum and this doesn't brake the SDK it seems like a service bug.
Once fixed, respective tests need to be enabled.

->  https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/SessionRecords/FormRecognizerClientLiveTests/StartRecognizeBusinessCardsIncludeFieldElements.json#L216

### LINKED ISSUE #18813: Enable prebuilt tests that use files from URL
Service randomly throws `InvalidImageURL`. We are disabling the affected test for now to avoid flakiness. We have a thread with the service team to look more into this. once we have more information, we should enable tests again.

### LINKED ISSUE #19375: InvalidURL now throw in POST instead of GET method
For now we are disabling the affected tests.

The question is, is this a breaking change? is this allowed? Follow up with service team and SDK team

Similar issue: https://github.com/Azure/azure-sdk-for-net/issues/19829

### PR DESCRIPTION
**Pull request by maririos**
Enables a bunch of ignored tests as service has been fixing/adding features:
- Fixes https://github.com/Azure/azure-sdk-for-net/issues/18813 Enables all `xxURL` tests again as the service fixed the bug.
- They also reverted their `throw on Post` behavior so Fixes https://github.com/Azure/azure-sdk-for-net/issues/19375
- Fixes: https://github.com/Azure/azure-sdk-for-net/issues/16827 Table bounding box is now returned from Custom Forms endpoint
- Fixes https://github.com/Azure/azure-sdk-for-net/issues/18216 BC doesn't return wrong `StyleName` values
- Model name is now returned in trained with no labels

It also makes a rename to the file `StyleName` to match the name type `TextStyleName`

### CODE REVIEW

**Review by kinelski — APPROVED** [review]
LGTM

**Review by kristapratico — APPROVED** [review]
what a beautiful PR!

**Comment by maririos** [comment]
>what a beautiful PR!

It feels amazing

**Pull request merged**
