### PR TITLE
Update GitIgnore

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Update GitIgnore for vscode settings

### CODE REVIEW

**Review by heaths — APPROVED** [review]
Makes sense to avoid people accidentally checking these in, but makes me wonder (different issue to consider) if we shouldn't check in workspace settings, etc., that we want people to use (selectively un-ignoring .vscode/settings.json, for example)?

**Review by weshaggard — APPROVED** [review]
I'm good with the change but curious what prompted it. Is there an issue tracking it or something that happened recently to trigger adding it?

**Comment by chidozieononiwu** [comment]
> I'm good with the change but curious what prompted it. Is there an issue tracking it or something that happened recently to trigger adding it?

I installed an extension that added that folder. I noticed the other repos ignore that folder so I am just updating dotnet

**Pull request merged**
