### PR TITLE
[Event Hubs] Fix Snippet Syntax

### PR DESCRIPTION
**Pull request by jsquire**
# Summary

The focus of these changes is to update the snippet syntax from the legacy comment style (/*@@*/) to the compiler conditional for a few instances that were overlooked in the initial migration.   Riding along is a fix for a merge error that snuck into the solution file.

### CODE REVIEW

**Review by JoshLove-msft — APPROVED** [review]

**Comment by jsquire** [comment]
There seems to have been an issue connecting the PR to the CI pipeline.   The CI was successful and can be found [[here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1229344&view=results)].

**Pull request merged**
