### PR TITLE
skip-url-encoding for ScopeParameter to avoid unnecessary url-encoding

### PR DESCRIPTION
**Pull request by Grayer123**
Apply the following swagger changes in dotnet SDK, and updated the corresponding test cases:
- https://github.com/Azure/azure-rest-api-specs/pull/9272
- https://github.com/Azure/azure-rest-api-specs/pull/9363

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi, please regenerate after your spec PRs are all merged. Thanks

**Comment by Grayer123** [comment]
Hello @isra-fel, the swagger pr got merged, and I regenerated the sdk client. Thanks

**Review by isra-fel — CHANGES_REQUESTED** [review]
Please
- Update release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release

Thanks

**Comment by Grayer123** [comment]
Hello @isra-fel, updated the nuget version and release note.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
