### PR TITLE
Exclude some attributes from API listing

### PR DESCRIPTION
**Pull request by heaths**
The CompilerGeneratedAttribute and EditorBrowsableAttribute are noisy in the API listing and not really necessary.

### CODE REVIEW

**Comment by heaths** [comment]
I removed EditorBrowsableAttribute since we discussed that originally, but after talking about how to best overload a method with default parameters and add EditorBrowsable, I wonder if we should keep it. @tg-msft thoughts?

**Review by heaths — COMMENTED** [review]
I reviewed the Key Vault files and they look fine.

**Review by tg-msft — APPROVED** [review]
Nice job getting rid of the annoying `[CompilerGenerated]`.

I'd vote for keeping `[EditorBrowsable]` in there.  It doesn't show up in ApiView and following the versioning pattern for optional params that you recently documented just confuses everyone.  I don't think we use `[EditorBrowsable]` so often that it's an annoyance.

**Comment by pakrym** [comment]
I agree about `[EditorBrowsable]`. In many cases we manually add it and considering https://github.com/Azure/azure-sdk-tools/issues/366 I think people want to see it.

**Review by pakrym — APPROVED** [review]
Except lets bring the [EditorBrowasble] back.

**Review by pakrym — APPROVED** [review]

**Pull request merged**
