### PR TITLE
Update DevTestLabs to a release version 1.02 => api-version 2016-05-15

### PR DESCRIPTION
**Pull request by iouri-s**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@iouri-s__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (iouris). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@iouri-s I think this requires at least minor version bump. you have removed ICostInsightOperations

**Comment by iouri-s** [comment]
Sure thing.

**Comment by iouri-s** [comment]
From http://semver.org/:

9.A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. **A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version**. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

All the previous version was -preview; therefore we shall not abide by the usual compatibility requirements.

**Pull request merged**
