### PR TITLE
Update to latest APICompat version

### PR DESCRIPTION
**Pull request by weshaggard**
Update the latest version of ApiCompat and also switch to the newer dotnet-eng feed that the dotnet team uses.

FYI @ericstj

### CODE REVIEW

**Review by ericstj — APPROVED** [review]

**Comment by weshaggard** [comment]
@ericstj any thoughts on the new failures? 

```
C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.20467.1\build\Microsoft.DotNet.ApiCompat.targets(82,5): error : CannotChangeAttribute : Attribute 'System.Runtime.CompilerServices.AsyncStateMachineAttribute' on 'Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(System.String)' changed from '[AsyncStateMachineAttribute(typeof(BlobBaseClient.<DownloadToAsync>d__56))]' in the contract to '[AsyncStateMachineAttribute(typeof(BlobBaseClient.<DownloadToAsync>d__57))]' in the implementation. [D:\a\1\s\sdk\storage\Azure.Storage.Blobs\src\Azure.Storage.Blobs.csproj]
```

Seems like it is failing on compiler generated attributes now.

**Comment by weshaggard** [comment]
I just pushed a change to ignore those attributes.

**Comment by weshaggard** [comment]
```
C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.20467.1\build\Microsoft.DotNet.ApiCompat.targets(82,5): error : CannotRemoveAttribute : Attribute 'System.Runtime.CompilerServices.IsReadOnlyAttribute' exists on 'Azure.AI.TextAnalytics.TextAnalyticsError.ErrorCode.get()' in the contract but not the implementation. [D:\a\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Azure.AI.TextAnalytics.csproj]
C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.20467.1\build\Microsoft.DotNet.ApiCompat.targets(82,5): error : CannotRemoveAttribute : Attribute 'System.Runtime.CompilerServices.IsReadOnlyAttribute' exists on 'Azure.AI.TextAnalytics.TextAnalyticsError.Message.get()' in the contract but not the implementation. [D:\a\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Azure.AI.TextAnalytics.csproj]
C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.20467.1\build\Microsoft.DotNet.ApiCompat.targets(82,5): error : CannotRemoveAttribute : Attribute 'System.Runtime.CompilerServices.IsReadOnlyAttribute' exists on 'Azure.AI.TextAnalytics.TextAnalyticsError.Target.get()' in the contract but not the implementation. [D:\a\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Azure.AI.TextAnalytics.csproj]
C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.20467.1\build\Microsoft.DotNet.ApiCompat.targets(82,5): error : CannotRemoveAttribute : Attribute 'System.Runtime.CompilerServices.IsReadOnlyAttribute' exists on 'Azure.AI.TextAnalytics.TextAnalyticsWarning.Message.get()' in the contract but not the implementation. [D:\a\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Azure.AI.TextAnalytics.csproj]
C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.20467.1\build\Microsoft.DotNet.ApiCompat.targets(82,5): error : CannotRemoveAttribute : Attribute 'System.Runtime.CompilerServices.IsReadOnlyAttribute' exists on 'Azure.AI.TextAnalytics.TextAnalyticsWarning.WarningCode.get()' in the contract but not the implementation. [D:\a\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Azure.AI.TextAnalytics.csproj]
C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.20467.1\build\Microsoft.DotNet.ApiCompat.targets(96,5): error : ApiCompat failed for 'D:\a\1\s\artifacts\bin\Azure.AI.TextAnalytics\Debug\netstandard2.0\Azure.AI.TextAnalytics.dll' [D:\a\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Azure.AI.TextAnalytics.csproj]
```

@maririos after the apicompat tool update we started detecting this potential breaking change made at https://github.com/Azure/azure-sdk-for-net/pull/14556. We should take a closer look to make sure we are OK with this change.

**Comment by maririos** [comment]
Thanks you @weshaggard. My understanding is that the properties on structs `TextAnalyticsError` and `TextAnalyticsWarning` are `readonly`, so making the struct itself immutable is not a breaking change. I wonder why it got flagged.
do you know it there something I miss?

**Comment by ericstj** [comment]
Could be APICompat being pedantic about the attribute application.  I don't think we have any higher-level understanding of the IsReadOnlyAttribute than just comparison.  The compiler probably understands a readonly struct is completely readonly but perhaps APICompat does not.  cc @safern

**Review by heaths — APPROVED** [review]

**Comment by weshaggard** [comment]
@ericstj I don't know enough about compat around isreadonly. Do you think this is a potential break we need to worry about? If not should we baseline this or should we add IsReadOnlyAttribute to your list of attributes to ignore?

**Comment by ericstj** [comment]
I would just baseline this one.  I think in general you want to pay attention to readonly differences.

**Comment by weshaggard** [comment]
@maririos I added these issues to the baseline file for textanalytics. That baseline file should be able to be removed after the next GA.

**Comment by maririos** [comment]
Thank you so much Wes!

**Comment by safern** [comment]
Maybe we should consider the `ReadOnlyAttribute` as special when doing the diff and check if the member owner type has it, if so then don't flag it as a difference?

**Comment by ericstj** [comment]
So far API compact doesn’t apply a lot of policy on top of attributes where it would need to understand the meaning of attributes. Most attributes in the framework have some meaning and could have compatibility rules associated with them. I think there’s a bigger chunk of work then just read only here.

**Comment by safern** [comment]
I created: https://github.com/dotnet/arcade/issues/6222

**Pull request merged**
