### PR TITLE
Fix casing

### PR DESCRIPTION
**Pull request by JoshLove-msft**

### CODE REVIEW

**Comment by pakrym** [comment]
Wana add a test? Assert that you don't have 2 capital letters in a row in names?

**Review by pakrym — APPROVED** [review]

**Comment by JoshLove-msft** [comment]
> Wana add a test? Assert that you don't have 2 capital letters in a row in names?

SignalRService..

**Comment by pakrym** [comment]
```C#
var exclusions = new [] { "SignalR"};
var s = ..;
foreach (var ex in exclusions)
{
	s = s.Replace(ex, "");
}

for (int i = 1; i < s.Lenght; i++)
{
	if (char.IsUpperCase(s[i - 1]) && char.IsUpperCase(s[i]))
	{
		Assert.Fail();
 	}
}
```

**Pull request merged**
