### PR TITLE
Removing location property from record set resource as not tracked. Changing session recordings for tests.

### PR DESCRIPTION
**Pull request by vladrai**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vladrai__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vladrai). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist.

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@vladrai Could you please squash all commits into one? We are trying to move to a model where there is one commit per check in.

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
LGTM once the build passes

**Pull request merged**
