### PR TITLE
Authorization package update

### PR DESCRIPTION
**Pull request by namratab**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@namratab__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nbaliga). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
add to whitelist

**Comment by amarzavery** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@namratab Please rebuild the project and also include any new generated files

**Comment by amarzavery** [comment]
@azuresdkci test this please

**Comment by amarzavery** [comment]
@azuresdkci test this please

**Comment by amarzavery** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@azuresdkci test this please

**Comment by yugangw-msft** [comment]
add to whitelist

**Pull request merged**
