### PR TITLE
Fix package casing issue breaking build on Linux

### PR DESCRIPTION
**Pull request by nguerrera**
Building this repo was failing for me on Linux due to nunit vs NUnit casing. 

Fixed by normalizing to NUnit, matching https://www.nuget.org/packages/NUnit/

### CODE REVIEW

**Comment by mikeharder** [comment]
@nguerrera: Any idea why this is failing for you on Linux, but it seems to work for other people, it works on our Linux build agents, etc?  Is there something special about you Linux distro or config?

**Comment by nguerrera** [comment]
@mikeharder Great question and I have no idea.

This is what I have:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by nguerrera** [comment]
Maybe something broke in a newer SDK?

**Comment by nguerrera** [comment]
These are the errors without this patch:

```
/home/nicholg/src/azure-sdk-for-net/sdk/core/Microsoft.Azure.Core.NewtonsoftJson/tests/Microsoft.Azure.Core.NewtonsoftJson.Tests.csproj : error : The package reference 'NUnit' must have a version defined in '/home/nicholg/src/azure-sdk-for-net/eng/Packages.Data.props'.
/home/nicholg/src/azure-sdk-for-net/sdk/digitaltwins/Azure.DigitalTwins.Core/tests/Azure.DigitalTwins.Core.Tests.csproj : error : The package reference 'NUnit' must have a version defined in '/home/nicholg/src/azure-sdk-for-net/eng/Packages.Data.props'.
/home/nicholg/src/azure-sdk-for-net/sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Azure.Messaging.EventHubs.Processor.Tests.csproj : error : The package reference 'NUnit' must have a version defined in '/home/nicholg/src/azure-sdk-for-net/eng/Packages.Data.props'.
/home/nicholg/src/azure-sdk-for-net/sdk/eventhub/Azure.Messaging.EventHubs.Shared/tests/Azure.Messaging.EventHubs.Shared.Tests.csproj : error : The package reference 'NUnit' must have a version defined in '/home/nicholg/src/azure-sdk-for-net/eng/Packages.Data.props'.
/home/nicholg/src/azure-sdk-for-net/sdk/eventhub/Azure.Messaging.EventHubs/tests/Azure.Messaging.EventHubs.Tests.csproj : error : The package reference 'NUnit' must have a version defined in '/home/nicholg/src/azure-sdk-for-net/eng/Packages.Data.props'.
/home/nicholg/src/azure-sdk-for-net/sdk/eventgrid/Azure.Messaging.EventGrid/tests/Azure.Messaging.EventGrid.Tests.csproj : error : The package reference 'NUnit' must have a version defined in '/home/nicholg/src/azure-sdk-for-net/eng/Packages.Data.props'.
/home/nicholg/src/azure-sdk-for-net/sdk/extensions/Microsoft.Extensions.Azure/tests/Microsoft.Extensions.Azure.Tests.csproj : error : The package reference 'NUnit' must have a version defined in '/home/nicholg/src/azure-sdk-for-net/eng/Packages.Data.props'.
/home/nicholg/src/azure-sdk-for-net/sdk/digitaltwins/Azure.ResourceManager.DigitalTwins/tests/Azure.ResourceManager.DigitalTwins.Tests.csproj : error : The package reference 'NUnit' must have a version defined in '/home/nicholg/src/azure-sdk-for-net/eng/Packages.Data.props'.
/home/nicholg/src/azure-sdk-for-net/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Azure.Messaging.ServiceBus.Tests.csproj : error : The package reference 'NUnit' must have a version defined in '/home/nicholg/src/azure-sdk-for-net/eng/Packages.Data.props'.
```

**Comment by weshaggard** [comment]
Hmmm... I know we haven't moved our agents to ubuntu 20.04 yet and I know we had some interesting string comparison issues come on there so I suspect this might be related to that somehow.

**Review by weshaggard — APPROVED** [review]

**Comment by mikeharder** [comment]
@nguerrera: Before you merge this, let me create a quick PR to bump our build agent to Ubuntu 20 and see if it fails there.

**Comment by mikeharder** [comment]
Draft PR testing Ubuntu 20: https://github.com/Azure/azure-sdk-for-net/pull/16016

**Comment by nguerrera** [comment]
@mikeharder Hmm that passed? Which SDK version is being used?

**Comment by weshaggard** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/master/global.json#L6 we are using 3.1.301

**Comment by mikeharder** [comment]
> @mikeharder Hmm that passed? Which SDK version is being used?

Yes, it did pass but I'm not sure what is different.  Let me try on a clean Ubuntu 20.04 VM.

This might be a bug in some of our custom build logic -- maybe we are comparing case-sensitive when it should be case-insensitive?  This is the source of the error message but I'm not very familiar with this code:

https://github.com/Azure/azure-sdk-for-net/blob/4a7444beedb6423b4dd70fd9c93fa03e241c5e74/eng/Microsoft.Build.CentralPackageVersions/2.0.46/Sdk/Sdk.targets#L170-L173

**Comment by mikeharder** [comment]
I will also update my test PR to use SDK 3.1.403 (matching the original repro).

**Review by RezaJooyandeh — APPROVED** [review]

**Review by heaths — APPROVED** [review]
Key Vault and Search changes LGTM, but I echo the concern this may be a regression in the .NET toolchain (I'm not aware of other toolchains' package managers being case-sensitive).

**Comment by mikeharder** [comment]
This does look like a regression in the .NET SDK:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=578706&view=logs&j=b08a78d6-c9ce-53c1-53b1-9a5d436f78f6&t=756e146f-7609-5d03-4e3a-e5bd2f3174ad&l=31

The build passes on Ubuntu 20.04 with SDK 3.1.301, but fails on Ubuntu 20.04 with SDK 3.1.402.  I'll run a few more tests to find exactly which OS/SDK versions trigger the issue.

**Comment by mikeharder** [comment]
Also fails on Ubuntu 18.04 with SDK 3.1.402.  So the Ubuntu version is not relevant.  This appears to be a regression in the .NET SDK on all Ubuntu versions.

**Comment by nguerrera** [comment]
cc @dsplaisted @nkolev92 Does this ring a bell?

**Comment by dsplaisted** [comment]
Looks like the error is coming from the [CentralPackageVersions SDK](https://github.com/microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions). @jeffkl

Also FYI @cristinamanum @adgrv

**Comment by jeffkl** [comment]
I'm surprised, the condition that generates the error is in MSBuild and is not file system dependent.  The Microsoft.Build.CentralPackageVersions SDK relies on `<PackageReference Update="NUnit" Version="1.0" />` syntax, which should be case insensitive.

FYI @rainersigwald

**Comment by jsquire** [comment]
Hi @nguerrera.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by pakrym** [comment]
This change is part of https://github.com/Azure/azure-sdk-for-net/pull/16947

Closing.

**Comment by nguerrera** [comment]
@pakrym Thanks for taking care of that. I was out for a month.

**Pull request closed without merging**
