### PR TITLE
.NET clients for operations on managed server

### PR DESCRIPTION
**Pull request by toki95**
Adding .Net clients for get, list and cancel managed server management operation API.

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @toki95 the changes look good generally. Please

- put link to swagger review PR(s) in comments, and
- ~~check in the `.txt` file generated when you run `generate.ps1` or autorest~~[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec) **Edit:** did you run autorest directly instead of generate.ps1? Was it because running generate.ps1 causes error?

Thanks

**Comment by toki95** [comment]
Here is a link to Swagger PR:
https://github.com/Azure/azure-rest-api-specs/pull/8243

**I am waiting on another swagger PR** (the one which enables .NET clients generation) to be merged before we merge this PR.: https://github.com/Azure/azure-rest-api-specs/pull/8558

**Comment by toki95** [comment]
Yes, I used autorest directly since generate.ps1 was failing.

**Comment by isra-fel** [comment]
> Yes, I used autorest directly since generate.ps1 was failing.

Hi, our suggestion is to edit your `generate.ps1` and change `-AutoRestVersion "latest"` into `-AutoRestVersion "2.0.4413"`, and still use it to generate code (because it also generates metadata that is helpful for debug tracing).

**Comment by toki95** [comment]
@isra-fel I have run the generate.ps1 script as you suggested and added metadata files.

**Review by isra-fel — APPROVED** [review]
LGTM!

**Pull request merged**
