### PR TITLE
Timeout for httpclient for VM metadata service and suppress statsbeat instrumentation

### PR DESCRIPTION
**Pull request by vishweshbankwar**
The change will result in following error for non-Azure VM environments

```
OpenTelemetry-AzureMonitor-Exporter - EventId: [10], EventName: [VmMetadataFailed], Message: [Failed to get Azure VM Metadata due to an exception. If not hosted in an Azure VM this can safely be ignored. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at

### CODE REVIEW

**Comment by cijothomas** [comment]
> OpenTelemetry-AzureMonitor-Exporter - EventId: [10], EventName: [VmMetadataFailed], Message: [Failed to get Azure VM Metadata due to an exception. If not hosted in an Azure VM this can safely be ignored. System.AggregateException: One or more errors occurred. (A task was canceled.)

Its not clear what end-users are supposed to do when they see this message.
Lets say the user is on Azure VM and see this message - what should they do?
Or say that the user is non on Azure VM, and see this message - what should they do?
Should they do anything differently based on if the app is on Azure VM vs non Azure VM?

**Comment by TimothyMothra** [comment]
If we want something more specific than the "A task was canceled.", we would need to catch the `TaskCanceledException` and provide a different message. "Connecting to Azure Metadata Service Timedout".

**Comment by TimothyMothra** [comment]
> Its not clear what end-users are supposed to do when they see this message. 

Lets use the same message we use for other Statsbeat errors. `This is only for internal telemetry and can safely be ignored.`

**Review by TimothyMothra — COMMENTED** [review]
LGTM.

**Review by rajkumar-rangaraj — APPROVED** [review]

**Comment by cijothomas** [comment]
> > Its not clear what end-users are supposed to do when they see this message.
> 
> Lets use the same message we use for other Statsbeat errors. `This is only for internal telemetry and can safely be ignored.`

LGTM.

**Pull request merged**
