### PR TITLE
API Version 2019-08-01-preview

### PR DESCRIPTION
**Pull request by rileymckenna**
Added Peering Service to SDK 
Added Tests to support new service

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hey @rileymckenna , seems there are some CI errors. Could you fix them then request a review?

Besides, please put a link to the swagger review PR in comments, and follow the instructions [here](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-directory-structure-and-sdk-generation) and make sure you git add the generated `eng\mgmt\mgmtmetadata\<rpName>.txt`.

**Comment by isra-fel** [comment]
Oh and I would highly recommend keep the commit history clean. Here is [how to](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md#cleaning-up-commits)

**Comment by rileymckenna** [comment]
@isra-fel I rebased and passing tests. Awaiting [ARM](https://github.com/Azure/azure-rest-api-specs/pull/6886) this is staged.

**Comment by rileymckenna** [comment]
Can one of the admins verify this patch?

**Comment by rileymckenna** [comment]
@isra-fel ARM signed off on PR.

**Comment by isra-fel** [comment]
Hey @rileymckenna , just one thing -- please also check in the generated `eng\mgmt\mgmtmetadata\<rpName>.txt` in PR. Thanks

**Comment by isra-fel** [comment]
@rileymckenna I have some questions:
- Why did you delete `resources_resource-manager.txt` -- generation log for another module
- There shouldn't be a `peering_resource-manager.txt` inside `src/SDKs/_metadata/`, if you generate your code by running `generate.ps1`, it should appear in `eng/mgmt/mgmtmetadata/`

Thanks

**Pull request closed without merging**
