### PR TITLE
[FarmBeats] Rename service directory to `agrifood`

### LINKED ISSUE #21593: [BUG] Folder structure change for FarmBeats.
Can the folder structure for FarmBeats SDK be changed from 'azure-sdk-for-net/sdk/farmbeats' to 'azure-sdk-for-net/sdk/agrifood'.

FarmBeats is a product name and is susceptible to change. Hence, we prefer to use AgriFood.

### PR DESCRIPTION
**Pull request by ellismg**
Fixes #21593

### CODE REVIEW

**Review by ramya-rao-a — APPROVED** [review]

**Comment by benbp** [comment]
@ellismg let me know after you merge this so I can delete the old farmbeats pipelines.

**Comment by ellismg** [comment]
@benbp This has been merged now, feel free to delete the old - farbeats - pieplines.

**Pull request merged**
