### PR TITLE
[Cognitive Services - QnA Maker] Package page description

### PR DESCRIPTION
**Pull request by diberry**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by diberry** [comment]
@AlexGhiondea - anything else I need to do? 

#sign-off

**Comment by AlexGhiondea** [comment]
@diberry this looks good! Have you checked the generated package to make sure the links show up as you want it on Nuget.org?

**Comment by diberry** [comment]
@AlexGhiondea How do I see the generated package? There isn't a link in this PR.

**Comment by AlexGhiondea** [comment]
@diberry can you try running `dotnet pack` from the project? That should generate the .nupkg file which you can then inspect with NuGet Package Explorer.

**Comment by diberry** [comment]
@AlexGhiondea verified in package page build. #sign-off

**Review by AlexGhiondea — APPROVED** [review]

**Pull request closed without merging**
