### PR TITLE
Adding MediaJobOutputProgressEventData and corresponding test

### PR DESCRIPTION
**Pull request by jinshang-msft**
## Description

Added MediaJobOutputProgressEventData type and corresponding test based on the change in azure-rest-api-specs repository committed [here](https://github.com/Azure/azure-rest-api-specs/commit/56c4282b8956d47913682edc72a534c60951fbcf) and also the [link](https://github.com/Azure/azure-rest-api-specs/pull/5027) to the PR in REST specs.

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by Chuansssss** [comment]
@dsgouda Just linked Github account to my Microsoft email account. Is there any further steps I have to take?

**Comment by dsgouda** [comment]
Please navigate to the link posted and join the `Azure` org on the portal

**Comment by Chuansssss** [comment]
@dsgouda Be added in Azure org

**Review by dsgouda — CHANGES_REQUESTED** [review]
How was this code generated? Please generate the code using the generate.ps1 script [here](https://github.com/Azure/azure-sdk-for-net/blob/aff93cbd02b2e4a6c499bc86b7a8de8f32de389f/src/SDKs/EventGrid/DataPlane/generate.ps1) and update the PR
Please update the Nuget version number to `3.1.0` in the csproj and the `PackageReleaseNotes` too

**Comment by Chuansssss** [comment]
@dsgouda The code I submitted was originally generated by the .ps1 script you provided.

**Comment by dsgouda** [comment]
WHen the code is generated using generate.ps1 script it should also update a .txt file, please commit the .txt file too

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by Chuansssss** [comment]
@dsgouda Thanks :)

**Pull request merged**
