### PR TITLE
Updating RP API version to 2015-08-15 for getvaults

### PR DESCRIPTION
**Pull request by avneeshrai**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@avneeshrai__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (avrai). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@sriramvu - Please update the api-version to 2015-08-15 across all the operations. Having an updated value assigned to a constant in the spec and then referring that constant every where would be the best approach.

**Comment by amarzavery** [comment]
@sriramvu - What about SiteRecoveryTests? I dont see the tests being recorded using the new api-version. Can you please record them and update the PR with test recording files?

**Comment by amarzavery** [comment]
@sriramvu - Please add coverage for the current code changes.

**Comment by stankovski** [comment]
@sriramvu please pull from upstream and update the PR

**Pull request merged**
