### PR TITLE
[Azure Cognitive Search] Creating new SDK version to match new management-plane API Version 2020-03-13 

### PR DESCRIPTION
**Pull request by tjacobhi**
SDK version to point to swagger changes from this [PR - Updated default tag to latest stable version. #9085](https://github.com/Azure/azure-rest-api-specs/pull/9085).

Due to data-plane tests being dependent on the generated management-plane code, all session records were re-recorded. This PR contains no changes to generated data-plane SDK code. There is planned work to separate the dependency between data-plane tests and management-plane generated code.

Is based off PR https://github.com/Azure/azure-sdk-for-net/pull/12376
New PR is created due to accidental rebase messing up git history on the other PR, causing me to close it.

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @tjacobhi you may have noticed but the data plane CI are still not passing :(

**Comment by brjohnstmsft** [comment]
@tjacobhi I'm not sure what changed to cause those tests to start failing, but it's definitely unrelated to your changes. Feel free to disable those tests to unblock yourself.

**Comment by tjacobhi** [comment]
Thanks @brjohnstmsft, I set the failing test to skip for the time being.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
