### PR TITLE
Change storage account output information.

### PR DESCRIPTION
**Pull request by wenjlu-lgy**

### CODE REVIEW

**Comment by wenjlu-lgy** [comment]
@bganapa a minor change for azure stack new srp, could you help to check it?

**Comment by bganapa** [comment]
Was there a change in swagger spec that triggered this?

**Comment by wenjlu-lgy** [comment]
> Was there a change in swagger spec that triggered this?

Yes, the one in spec is already checked in.

**Comment by isra-fel** [comment]
@wenjlu-lgy your PR contains breaking changes such as renaming a model class, plesae put a link to your swagger review PR here, and also update the major version number.

**Comment by wenjlu-lgy** [comment]
> @wenjlu-lgy your PR contains breaking changes such as renaming a model class, plesae put a link to your swagger review PR here, and also update the major version number.

So I should update the version number from 1.9.0 to 2.0.0, right?

**Comment by wenjlu-lgy** [comment]
> > @wenjlu-lgy your PR contains breaking changes such as renaming a model class, plesae put a link to your swagger review PR here, and also update the major version number.
> 
> So I should update the version number from 1.9.0 to 2.0.0, right?
Here's the pr link https://github.com/Azure/azure-rest-api-specs/commit/e99d1c20d3cc621a38af09d3c146149812a87e38#diff-02ee76c268524d9c18f32bc098eff02b

**Comment by wenjlu-lgy** [comment]
@isra-fel The pr link for spec is https://github.com/Azure/azure-rest-api-specs/pull/7591, the version is upgraded from 1.9.1 to 2.0.0

**Comment by isra-fel** [comment]
Please also check in `eng/mgmt/mgmtmetadata/<yourservicename>.txt`, which is generated when you run `generate.ps1`. Other changes look good to me
Thanks

**Comment by wenjlu-lgy** [comment]
> Please also check in `eng/mgmt/mgmtmetadata/<yourservicename>.txt`, which is generated when you run `generate.ps1`. Other changes look good to me
> Thanks

It's already checked in as https://github.com/Azure/azure-sdk-for-net/blob/master/eng/mgmt/mgmtmetadata/azsadmin_resource-manager_storage.txt, anything needs to change?

**Comment by isra-fel** [comment]
Yeah, it's already there, but when you run `generated.ps1` that file should be updated. And you should check in that change.

If the file was not changed during generation, please follow these steps to [update build tools](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools) then run `generate.ps1` again. Thanks

**Comment by wenjlu-lgy** [comment]
> Yeah, it's already there, but when you run `generated.ps1` that file should be updated. And you should check in that change.
> 
> If the file was not changed during generation, please follow these steps to [update build tools](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools) then run `generate.ps1` again. Thanks

done.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
