### PR TITLE
Diagnostic Scope: AddTag function should be NoOp for Sampled out activity

### PR DESCRIPTION
**Pull request by sourabh1007**
As part of this PR, making sure `AddTag` should add information in the activity, only if it is not sample out activity otherwise it should be `NoOp`.

### CODE REVIEW

**Comment by jsquire** [comment]
@lmolkova:  Would you please offer your thoughts?

**Review by JoshLove-msft — APPROVED** [review]

**Review by lmolkova — COMMENTED** [review]
LGTM! Is it possible to adda test for it?

**Comment by sourabh1007** [comment]
> LGTM! Is it possible to adda test for it?

added test

**Review by lmolkova — APPROVED** [review]
Thank you!

**Pull request merged**
