### PR TITLE
AutoPr-StorageSync-anpint-REST Spec PrNumber 5210

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by ankushbindlish2** [comment]
@dsgouda spec is merged now : https://raw.githubusercontent.com/Azure/azure-rest-api-specs-pr/master/specification/storagesync/resource-manager/readme.md?token=AhR6h9EI_UdSfDjyprMIH4Iwo103bA4yks5cpPH9wA%3D%3D

**Comment by ankushbindlish2** [comment]
@dsgouda @adxsdknet How do we contribute to fix errors ?

**Comment by dsgouda** [comment]
@azuresdkci retest this please

**Review by ankushbindlish2 — APPROVED** [review]

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
