### PR TITLE
Add back GetIfExists by using NullableResponse<T>

### LINKED ISSUE #2159: Add back GetIfExists once NullableResponse<T> is available in Azure.Core
Once this issue gets finished https://github.com/Azure/azure-sdk-for-net/issues/27852 we will need to add back into the generator to create the `GetIfExists` method using the `NullableResonse<T>` as the response type

### PR DESCRIPTION
**Pull request by RodgeFu**
Fixes https://github.com/Azure/autorest.csharp/issues/2159
Autorest.csharp side PR: https://github.com/Azure/autorest.csharp/pull/3692

Include NullableResponse file from shared code so that we can refer to it in sdk code

### CODE REVIEW

**Comment by RodgeFu** [comment]
not ready for review. More change is expected. add the "Do Not Merge" label.

**Comment by RodgeFu** [comment]
Ready for review, remove 'Do Not Merge' label. Corresponding fix in autorest.csharp repo is https://github.com/Azure/autorest.csharp/pull/3692

**Comment by RodgeFu** [comment]
@weshaggard , could you help to review this PR? this PR is for fixing issue https://github.com/Azure/autorest.csharp/issues/2159 which needs the NoValueResponse from shared code so that we can return it in GetIfExists when it doesn't exist. thanks.

in case you are interested, the autorest.csharp side PR is at https://github.com/Azure/autorest.csharp/pull/3692

**Comment by weshaggard** [comment]
I'd defer this review to @m-nash

**Comment by RodgeFu** [comment]
thanks @weshaggard.
@m-nash , could you help to review the PR. thanks.

**Review by ArthurMa1978 — APPROVED** [review]

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
