### PR TITLE
Add support for Microsoft.OperationalInsights/Workspaces/DataSources

### PR DESCRIPTION
**Pull request by haitch**
We use data sources to config Log Analytics workspace where to fetch the data from.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@haidaocht__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (haitch). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by haidaocht** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Pull request merged**
