### PR TITLE
Added support for using sever level rule in vulnerability assessment baseline operations

### PR DESCRIPTION
**Pull request by yaakoviyun**
Added support for using sever level rule in vulnerability assessment
baseline operations

### CODE REVIEW

**Comment by yaakoviyun** [comment]
@dsgouda - this is the updated PR.

Can you please merge?

**Comment by shahabhijeet** [comment]
@yaakoviyun please do the following checks:
1) GEnerate the sdk using generate.ps1
2) Build at least once before submitting the PR, because the build adds the necessary meta data to the SDK

**Comment by yaakoviyun** [comment]
@shahabhijeet - the current code is after msbuild and code generation.

I've rebuild the code and no more changes exists.

**Comment by yaakoviyun** [comment]
@shahabhijeet - ping

**Review by dsgouda — CHANGES_REQUESTED** [review]
@yaakoviyun Please run [this](https://github.com/yaakoviyun/azure-sdk-for-net/blob/15edc1c78cc5c41b4d77a12656f03e50088155de/src/SDKs/SqlManagement/Management.Sql/generate.ps1) script to generate the code. This should update a log txt file please commit those changes too

**Comment by yaakoviyun** [comment]
@dsgouda , @shahabhijeet - Done.

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
