### PR TITLE
Update SecurityInsights SDK [preview2]

### PR DESCRIPTION
**Pull request by dicolanl**
- [X] Swagger review PR(s) link in PR description, and the PR(s) is merged
https://github.com/Azure/azure-rest-api-specs/pull/12415
- [X] Metadata file `eng/mgmt/mgmtmetadata_{RP}.txt` is updated
- [X] Versions in `*.csproj` and `AssemblyInfo.cs` are updated, and follows semver
- [X] Release notes in `*.csproj` is updated
- [X] If there's a API-version update, the API tags in `Az.Sdk.props` are updated
- [X] Generated code is not touched
- [X] Proper test coverage

-Regenerated code using latest API.
--API - added teams to OfficeDataConnector
-Updated strings in tests
-Recorded new test sessionrecords

### CODE REVIEW

**Comment by bquantump** [comment]
Please look into fixing the CI or we will close this.

**Comment by dicolanl** [comment]
hi @bquantump 
I tried pinging @allenjzhang on teams and didnt get a reply.  I dont understand why the error is occuring?  
i used autorest to generate the code.  I only changed my test code and test recordings.  Why is it saying there is manually entered code when i didnt manually enter anything?

**Comment by dicolanl** [comment]
@bquantump ran generate.ps1  looks like the pipelines finished successfully now

**Comment by bquantump** [comment]
Please ensure the following check list is completed:

https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#appendix-a-pr-review-checklist

**Comment by dicolanl** [comment]
@bquantump Done added the check list to the initial PR and ensured each step is completed.

**Review by bquantump — APPROVED** [review]

**Pull request merged**
