### PR TITLE
Swallow NotImplementedException in EventSource name deduplication logic

### LINKED ISSUE #24055: Azure Blob Storage Crash Xamarin.iOS [BUG]
**Describe the bug**
Using Azure blob storage V12 SDK and when i upload a picture to azure our app crashes

Ekran Resmi 2021-09-16 23 31 56

Exception Detail:
Message: The method or operation is not implemented.
Stack Trace: 

  at System.Diagnostics.Tracing.EventSource.GetSources () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Diagnostics.Tracing/EventSource.cs:318 
  at Azure.Core.Diagnostics.AzureEventSource.DeduplicateName (System.String eventSourceName) [0x00010] in <0aa90fe0646d47bc95bff520717dbf16>:0 
  at Azure.Core.Diagnostics.AzureEventSource..ctor (System.String eventSourceName) [0x00000] in <0aa90fe0646d47bc95bff520717dbf16>:0 
  at Azure.Core.Diagnostics.AzureCoreEventSource..ctor () [0x00000] in <0aa90fe0646d47bc95bff520717dbf16>:0 
  at Azure.Core.Diagnostics.AzureCoreEventSource..cctor () [0x00000] in <0aa90fe0646d47bc95bff520717dbf16>:0 

**Environment:**
 - Azure.Storage.Blobs: 12.10.0
- Xamarin.Forms: 5.0.0.2083

Shared project:
Ekran Resmi 2021-09-16 23 34 29

Xamarin.ios project:

Ekran Resmi 2021-09-16 23 35 04

Visual Studio Community 2019 for Mac
Version 8.10.9 (build 3)
Installation UUID: 1613872f-990d-40c4-8289-a37e7258a654
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

Mono Framework MDK
Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

Roslyn (Language Service)
3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

NuGet
Version: 5.9.0.7134

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/5.0.401/Sdks
SDK Versions:
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9

.NET Core 3.1 SDK
SDK: 3.1.413

Xamarin.Profiler
Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

Xamarin.Android
Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/muhammetsahin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.1
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Microsoft OpenJDK for Mobile
Java SDK: /Users/muhammetsahin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:43:52 UTC

Android Device Manager
Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:44:10 UTC

Apple Developer Tools
Xcode 12.5.1 (18212)
Build 12E507

Xamarin.Mac
Version: 7.14.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

Xamarin.iOS
Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

Build Information
Release ID: 810090003
Git revision: 156eb53c9c668cb7ff4311ae3d1dab894549848b
Build date: 2021-09-08 07:26:54-04
Build branch: release-8.10

Operating System
Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Jun 23 00:26:31 PDT 2021
    root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

Enabled user installed extensions
LiveXAML 1.3.51
Log Monitor 0.2
Library Manager 0.2
NuGet Package Explorer 0.6
MvvmCross Template pack 2.1.0

### PR DESCRIPTION
**Pull request by pakrym**
Fixes: https://github.com/Azure/azure-sdk-for-net/issues/24055

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

**Comment by Candelit** [comment]
Hi.
I am part of the now closed report #24055 submitted by Muhammet Sahin and we fins ourselves blocked from publishing our xamarin based mobile app to Appstore due to this.
All worked/works fine for some reason while testing the same build of the app from AppCenter, but as we now move to the next phase and add it to Appstore and Testflight, this issue emerged...

In what timeframe can we get access to a fix for testing in our app?

Best regards
Thomas Odell Balkeståhl

**Comment by pakrym** [comment]
In addition, there is a nightly feed: pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json you can get the latest set of packages and test the fix.

**Comment by Candelit** [comment]
Hi.
We have tried to downgrade, but it got even worse, now the app won't even start at all. We get 2-3 crashes at start and then it is dead.
Do you know if the deployment via Testflight/Appstore affects this in any way? Anything that 'manipulates' the versions of the packages?
Most likely, it is as you say, that the bug was introduced in aug, but we had a working app in AppCenter(Microsoft) and the exact same build published on Testflight triggered the bug.

**Comment by Candelit** [comment]
Update:
We have now managed to get our app running. It was due to the bug in azure.storage/azure.core, but also in relation to the experimental flags in Xamarin.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/experimental-flags
(With 'we' I'm referring to our big hero @muhammetsahin who managed to solve it with no blame to himself)

**Pull request merged**
