### PR TITLE
Adding support for multiple keys from a single secret

### PR DESCRIPTION
**Pull request by pwiens**
This adds support for multiple keys for AzureKeyVaultConfigurationProvider. #16577

### CODE REVIEW

**Comment by pakrym** [comment]
I don't think this feature is specific to KeyVaul and belongs to `KeyVaultSecretManager`. A similar requirement can be put for any configuration source and I think is better accomplished by something like wrapping the IConfiguration instance.

**Comment by jsquire** [comment]
Hi @pwiens.  Thank you for helping to improve the Azure SDK experience and for your contribution.   I've added some tags for tracking purposes; I see that @pakrym has already begun providing feedback.

**Comment by jsquire** [comment]
Hi @pwiens.  Thank you, again, for your contribution.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by jsquire** [comment]
Thank you for your contribution.  Since there hasn't been recent engagement, I'm going to close this out.  Please feel free to reopen if you'd like to continue working on these changes.

**Pull request closed without merging**
