### PR TITLE
Upgrade Azure.Core dependency for patch release

### PR DESCRIPTION
**Pull request by schaabs**
Upgrade Azure.Core dependency to latest which contains the fix corresponding to this patch.

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Comment by weshaggard** [comment]
@schaabs doesn't look like the default triggers like working when targeting the hotfix branch. You should be able to manually trigger the build in DevOps UI.

**Comment by weshaggard** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1032935&view=results I triggered in manually.

**Pull request merged**
