### PR TITLE
Fix MsiUnavailableError when IMDS endpoint availability is delayed.

### LINKED ISSUE #18312: [BUG] ManagedIdentityCredential fails sometimes in AKS
**Describe the bug**
We are using the `ManagedIdentityCredential` class to get access tokens for managed identities. We are deploying the application to AKS, where we are using https://github.com/Azure/aad-pod-identity.

The instance of the `ManagedIdentityCredential` is a singleton.

Sometimes after starting a new pod, we get the exception `Azure.Identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.` everytime when the pod is trying to get the access token. If the pod is able to start without this exception, the exception is never observed during the lifetime of the pod.

The problem seems to be that there might be a delay after starting up the pod, after which the IMDS endpoint is available for the pod in AKS. When the pod is trying to get the access token before the endpoint is available, it has some bad state, where it will never be able to recover from.

The cause of the issue is probably this code: https://github.com/Azure/azure-sdk-for-net/blob/705f3296529b2e30e16bfe42fdd2245511a5c0b0/sdk/identity/Azure.Identity/src/ManagedIdentityClient.cs#L51-L67

The `ManagedIdentityClient` tries several strategies to get a `ManagedIdentitySource`. If all of them fail, it sets the value of `_identitySourceAsyncLock` to `null` and will therefore never try to resolve the `ManagedIdentitySource` again.

**Expected behavior**
The exception should not occur or it should be possible to recover from this failed state when the IMDS endpoint gets available.

**Actual behavior**
The exception occurs and it is not possible to recover from the failed state.

**To Reproduce**

1. Deploy AKS
2. Deploy the aad-pod-identity services
3. Deploy a pod using the ManagedIdentityCredentials
4. Pray for observing the exception
5. Observe the exception

**Environment:**
 - AKS 1.17.11
 - AAD Pod Identity 1.7.1
 - Azure.Identity 1.2.3

### PR DESCRIPTION
**Pull request by PSanetra**
Fixes #18312

Related: https://github.com/Azure/aad-pod-identity/issues/846

### CODE REVIEW

**Comment by jsquire** [comment]
Hi @PSanetra.  Thank you for your interest in helping to improve the Azure SDK experience and for your contribution.  I've added some tags and looped in the team members best able to offer feedback.

**Comment by jsquire** [comment]
@schaabs, @christothes:  Would one of you please be so kind as to review and offer your thoughts?

**Comment by christothes** [comment]
Hi @PSanetra - Thank you for your contribution. However, as [discussed in the linked issue](https://github.com/Azure/azure-sdk-for-net/issues/18312#issuecomment-771843460), the concern with this fix is that for scenarios where the endpoint is not available and `ChainedTokenCredential` is being used, this would introduce a delay on each request to `GetToken`. I think the workaround you are currently using (to retry with a new instance of the credential) or the [AKS pod workaround](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/pod-identity/test-pod-identity/templates/job.yaml#L23) would be preferable in this case.

**Comment by PSanetra** [comment]
Hi, I am ok with closing this issue, but I would propose to introduce a general solution to this issue into the [aad-pod-identity](https://github.com/Azure/aad-pod-identity) project like @bohlenc has mentioned in this comment (applying the workaround per default in AKS via a mutation admission webhook): https://github.com/Azure/azure-sdk-for-net/issues/18312#issuecomment-781729340

I think it is not acceptable that users have to run into this issue and find a workaround for it.

**Comment by christothes** [comment]
> Hi, I am ok with closing this issue, but I would propose to introduce a general solution to this issue into the [aad-pod-identity](https://github.com/Azure/aad-pod-identity) project like @bohlenc has mentioned in this comment (applying the workaround per default in AKS via a mutating admission webhook): [#18312 (comment)](https://github.com/Azure/azure-sdk-for-net/issues/18312#issuecomment-781729340)
> 
> I think it is not acceptable that users have to run into this issue and find a workaround for it.

Thanks @PSanetra - Would you mind creating an issue to track this over there?

**Comment by deyanp** [comment]
@christothes , @PSanetra is there an aad-pod-identity issue created for this?

We also run into this issue (however we have hardcoded ManagedIdentityCredential instead of DefaultAzureCredential), and frankly said it was a bit difficult to find these github issues and understand what is the problem (nmi logs did not help either) ...

Both workarounds sound awkward to me:
1) we have to create a new instance of XxxCredential - for what purpose, and how would we know???
2) we have to change the deployments of all our pods to initContainer - why would we do that and *how* would we know that we have to do that?

It sounds to me like in both cases a very very low-level detail surfaces way up and affects clients ... I don't think that is a great idea ..

**Pull request closed without merging**
