### PR TITLE
[Fluent] Regenerated fluent interfaces, fixed impls, tests

### PR DESCRIPTION
**Pull request by martinsawicki**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@martinsawicki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (marcins). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
src\ResourceManagement\Azure.Fluent\Fluent.Tests\VirtualMachineExtensionImageTests.cs file is missing license header.

**Comment by hovsepm** [comment]
file: src\ResourceManagement\Azure.Fluent\Fluent.Tests\VirtualMachineExtensionImageTests.cs 
```
            // Lazy listing
            foreach (var extensionImage in extensionImages)
            {
                Assert.NotNull(extensionImage);
                count++;
                if (count >= maxListing)
                {
                    break;
                }
            }
            Assert.True(count == maxListing);
```
What is this code supposed to test? It would be nice to convert this logic to LINQ.

**Comment by hovsepm** [comment]
src\ResourceManagement\Azure.Fluent\Fluent.Tests\VirtualMachineScaleSetTests.cs file does not have license header.

**Comment by hovsepm** [comment]
file Fluent/src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/ResourceManager2.cs and class name should be change to ResourceManager

**Pull request merged**
