### PR TITLE
Search SDK: Adding support for ETags and AccessConditions for Indexers, Indexes, and DataSources

### PR DESCRIPTION
**Pull request by seansaleh**
@brjohnstmsft

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@seansaleh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by brjohnstmsft** [comment]
Sean is a MSFT employee; No CLA required

**Comment by brjohnstmsft** [comment]
:metal:

**Comment by azurecla** [comment]
Hi __@seansaleh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Pull request merged**
