### PR TITLE
Change duplicate matrix name in live test template

### PR DESCRIPTION
**Pull request by benbp**
This fixes a duplicate name entry in the test matrix.

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
FYI @pakrym

**Review by kinelski — APPROVED** [review]

**Comment by benbp** [comment]
metricsadvisor live tests are failing, but I was just using them to make sure the template was valid. The actual test issues are functional and don't have to do with this change.

**Pull request merged**
