### PR TITLE
Ignore nuget packages cache in Component Detection

### PR DESCRIPTION
**Pull request by pakrym**

### CODE REVIEW

**Comment by pakrym** [comment]
Confirmed that this fixes the warning: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1196128&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=833edf1b-3669-5dbb-11e6-ee7d22230825

**Review by heaths — APPROVED** [review]
Nice find!

**Comment by pakrym** [comment]
Failure is know and unrelated

**Pull request merged**
