### PR TITLE
EventHub: updated Package and added new test BYOK and Clusters

### PR DESCRIPTION
**Pull request by v-Ajnava**
Swagger PR Links : 
https://github.com/Azure/azure-rest-api-specs/pull/9207
https://github.com/Azure/azure-rest-api-specs/pull/9245
https://github.com/Azure/azure-rest-api-specs/pull/9321
https://github.com/Azure/azure-rest-api-specs/pull/9335

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi, we updated our folder structure quite log ago. Every project should be in `/sdk`. Please remove `src/SDKs` and everything in it.

Besides, please generate your sdk using this script `sdk/eventhub/Microsoft.Azure.Management.EventHub/src/generate.ps1`. It should also generate a metadata file in `/eng/mgmt/mgmtmetada` please also check it in.

Thanks

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @v-Ajnava  please
- Add a link to the openapi spec review PR here
- Update release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release

Thanks

**Comment by v-Ajnava** [comment]
@isra-fel, added all swagger PRs regarding changes, added release notes and updated version.  please review and let me know if any changes needed

**Review by isra-fel — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
