### PR TITLE
Remove ETag and ETagFilter

### PR DESCRIPTION
**Pull request by pakrym**
Having a strongly typed ETag doesn't seem to have any benefits over having it be just a string considering it's a transparent value that customers are not going to interpret it in any way. 

It's also inefficient to transform string into byte[] and back to string all the time.

### CODE REVIEW

**Comment by maririos** [comment]
I am ok with it. It will also be consistent with how other languages are managing ETags.

**Review by jsquire — APPROVED** [review]
I like it, but you may want to double-check with Krzysztof, as I think he may have been involved with the decision to add it.

**Review by maririos — APPROVED** [review]

**Comment by KrzysztofCwalina** [comment]
I am totally on board with changing the representation from byte[] to string. But I am not sure removing the type altogether is the right choice. As you mentioned, the type should be an opaque value and string is not. String let's people compare it in strange ways (case insensitive, culture specific, etc.). We want ETag to be like a GUID.

@JeffreyRichter, @johanste, @bterlson, @JonathanGiles, thoughts?

**Comment by JeffreyRichter** [comment]
Etags are opaque string values so a type wrapping a string makes the most sense to me


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://azure.microsoft.com/training/distributed-cloud-apps/>)

________________________________

**Comment by pakrym** [comment]
@KrzysztofCwalina do you want to keep `ETagFilter`, it's not being used at all?

**Comment by johanste** [comment]
The one(?) twist to etags being opaque - the format for a strong vs weak etag is [defined in RFC 7232](https://tools.ietf.org/html/rfc7232#section-2.1). Which (IMHO) makes an even stronger case for keeping them as strings.

**Comment by bterlson** [comment]
FWIW in JS these are always strings. They start life as string header values, might get passed around to various etag helper libraries that expect strings as well.

I do often wish we had an opaque string type (e.g. Intl.* APIs would return these) but alas…

**Pull request closed without merging**
