### PR TITLE
Reduce size of CheckEnforcer PR message

### PR DESCRIPTION
**Pull request by christothes**
This change reduces the large Check Enforcer message to link to a markdown file with the detailed text.

### CODE REVIEW

**Comment by weshaggard** [comment]
The change looks correct from a technical standpoint but I'm curious what is prompting you to make this change. Is there a particular issue with having the large comment in the exceptional cases when there is no pipeline triggered.

**Comment by christothes** [comment]
> The change looks correct from a technical standpoint but I'm curious what is prompting you to make this change. Is there a particular issue with having the large comment in the exceptional cases when there is no pipeline triggered.

Yes, It's not uncommon to get this for PRs that, for whatever reason, are slow to trigger pipelines. The main concern is that it takes up a lot of real estate in the PR comments view and doesn't really need to be inline (rather than a link to the verbose content).

**Review by weshaggard — APPROVED** [review]

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
You can also use `<details>`

**Comment by christothes** [comment]
> You can also use `<details>`

Where do you mean?

**Comment by pakrym** [comment]
https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2

**Comment by christothes** [comment]
> https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2

Ah - Thanks. But I don't think this prevents the big message from hitting your inbox 😄

**Review by jsquire — APPROVED** [review]

**Comment by weshaggard** [comment]
>@weshaggard - Do you know why this PR is generating so many skipped pipelines?

New DevOps feature we are trying to disable it. See EngSys channel for more info.

**Pull request merged**
