### PR TITLE
OpenAI null collection fix

### PR DESCRIPTION
**Pull request by HiltonGiesenow**
This is my first contribution to this project so I know it's not great right now - I'm struggling to get the test environment working without forcing things through in Debug mode. This fix relates to https://github.com/Azure/azure-sdk-for-net/issues/40810 though - I've put some more details in that issue.

### CODE REVIEW

**Comment by jsquire** [comment]
Thank you for your contribution, @HiltonGiesenow!  I'm not sure this is the approach that we would want to use for addressing #40810, as all Azure SDK models should have any collection property initialized and a `null` value should not be possible.  This seems like the OpenAI library may be violating that constraint.

@joseharriaga:  Would you please take a look at the OpenAI side of this and offer thoughts?

**Comment by HiltonGiesenow** [comment]
Thanks @jsquire for looking into this. Of course, totally happy if you think we should toss the PR, but maybe some background would at least help explain what I was seeing. I have an overload that takes in a List of Functions, but sometimes I don't want to pass Functions, so I have it as an optional parameter, defaulting to `null`. Unfortunately, the [check](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/Optional.cs#L14) inside of `IsCollectionDefined` was returning `true`, so as a result when the [serialization was trying to iterate over the Functions list](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/src/Custom/ChatCompletions/ChatCompletionsOptions.Serialization.cs#L32), it was throwing a null reference exception.

An alternative could be to modify the serialization code to check for null, e.g.:

```
if (Optional.IsCollectionDefined(Functions) && Functions != null)
``` 

but then the same check should be added on lines 72, 87, etc.

**Comment by joseharriaga** [comment]
Hello, @HiltonGiesenow. Thank you for bringing this to our attention! @jsquire is correct that all collection properties must be initialized, and a `null` value shouldn't be possible. The root cause of this issue is that the `Functions` property has a setter. Collection properties must not be settable as per our guidelines. More info here:
🔗 https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values

For the case when you don't want to pass any functions as part of your request, you don't have to set the `Functions` property. It is initialized as an empty collection, and you can just leave it like that. 🙂

I have prepared this PR to remove the setter of the `Functions` property:
🔗 https://github.com/Azure/azure-sdk-for-net/pull/41152

**Comment by HiltonGiesenow** [comment]
At the end of the day, you guys will implement as you see fit, so this is just my two cents, but I'd really suggest NOT going this route. Removing the setter is the _easiest_ approach but actually the _worst_ from an end developer perspective. Here's my current scenario:

```
private async Task CallLlm(..., IEnumerable<FunctionDefinition> functions = null)
var chatCompletionsOptions = new ChatCompletionsOptions(openAiDeploymentName, messages)
{
    Functions = functions,
    Temperature = 0.4f,
};
...
```

Being that the parameter is nullable, I can pass it or not pass it as needed, based on my scenario. However, the code above currently does NOT work (hence this discussion), because the serialization fails, as described. It's failing because, even though the code is currently checking if this collection is initialized (as well as other collections), it's doing so in a way that doesn't cater for this scenario above correctly. 

If we ignore my scenario entirely for a moment, and assume I always DO have a value, the change you're proposing (removing the setter), would make even the above simple code more annoying, as follows:

```
private async Task CallLlm(..., IEnumerable<FunctionDefinition> functions = null)
var chatCompletionsOptions = new ChatCompletionsOptions(openAiDeploymentName, messages)
{
    Temperature = 0.4f,
};
chatCompletionsOptions.Functions.AddRange(functions);
...

I now need, essentially, *3* steps to initialize `ChatCompletionsOptions` (the normal constructor, the additional properties, and extra code). Incidentally, you can see it's already an issue for me because how I'm composing my `messages` collection - I have a function that returns me a 'standard' message history in some cases as an IEnumerable, but I can't pass that in the initializer because `Messages` already has no setter!

In an ideal world, I'd simply be able to write the following:

```
var chatCompletionsOptions = new ChatCompletionsOptions
{
    DeploymentName = openAiDeploymentName,
    Messages = messages,
    Functions = functions,
    Temperature = 0.4f,
};
```
and the `Write` method that's throwing the exception would be doing better checks.

Incidentally, the 'guidelines' link you pointed to refers exactly in that paragraph to "replacing" the contents of the collection, which could definitely be better with AddRange. In this case we're talking about **Initialization** (i.e. Constructor), which I would suggest is a different scenario. A better answer altogether, for both `Functions` AND `Messages`, might actually be to use [the `init` accessor](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-the-init-accessor) - this is exactly what the keyword is designed for. Curiously, that same section of the guideline, in the last line, says "The general rule is that null and empty (0 item) collections or arrays should be treated the same.", and to be frank, this entire discussion is happening because the code is NOT treating null and empty collections the same.

**Pull request closed without merging**
