### PR TITLE
add Resource Usage and EdgeNode to CDN

### PR DESCRIPTION
**Pull request by csmengwan**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@csmengwan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (qinwa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by cormacpayne** [comment]
@csmengwan can you update the `generate.cmd` file with the version of AutoRest you used to generate this code, as well as a link to the rest-api-specs PR that this code is generated from?

**Comment by csmengwan** [comment]
@cormacpayne 
Hi, what should be the newest version of the autoRest I should use here?

**Comment by cormacpayne** [comment]
LGTM

**Comment by cormacpayne** [comment]
@csmengwan please update the `AssemblyInfo.cs` file with the new version of Cdn: https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Cdn/Microsoft.Azure.Management.Cdn/Properties/AssemblyInfo.cs#L24

LGTM once that is fixed

**Pull request merged**
