### PR TITLE
[ADLA] - [HOTFIX] - Adding an InnerError property to JobInnerError.cs

### PR DESCRIPTION
**Pull request by ro-joowan**
* Swagger repo -- fork of Azure/current: git reset --hard 9556a7371292a1362ac0b3eb5fbfd2f06f3d5859: https://github.com/Azure/azure-rest-api-specs/commit/9556a7371292a1362ac0b3eb5fbfd2f06f3d5859

  * This is because this commit is right before Ben's update from version 3.0.1 to version 3.1.0-preview, as shown here: https://github.com/Azure/azure-rest-api-specs/commits/current?before=d8aba4a6092b536a0eec12ca66dbbcc26406136c+280

  * Code gen based on my Swagger fork: https://github.com/ro-joowan/azure-rest-api-specs/commits/hotfix-inner-error

* SDK repo -- fork of Azure/psSdkJson6: git reset --hard 20ceebb0da7c0918325831066d52b9a03aa52c8a

  * This is because this was the last commit for ADLA version 3.0.1 -- this hotfix version is 3.0.2

  * Commit-list view: https://github.com/Azure/azure-sdk-for-net/commits/psSdkJson6?after=2ffd522a97aa6f88749d30e22355b6aa928ea3e5+139

* This change was approved before in a past PR: https://github.com/Azure/azure-sdk-for-net/pull/3666

  * This is because this was already addressed in version 3.1.2-preview

* Primary change is in here: src\SDKs\DataLake.Analytics\Management.DataLake.Analytics\Generated\Models\JobInnerError.cs

* I submitted a separate PR for the changelog update: https://github.com/Azure/azure-sdk-for-net/pull/3792

  * This is because this is the only change that needs to be merged to psSdkJson6

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by ro-joowan** [comment]
@shahabhijeet Please note that I ran the following for both branches (Azure:adl-hotfix-3-0-2-inner-error and ro-joowan:ro-joowan-adl-hotfix-3-0-2-inner-error):

git reset --hard 20ceebb

**Comment by ro-joowan** [comment]
@shahabhijeet Did the test fail because of the "git reset"?

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Pull request merged**
