### PR TITLE
Network version update and ApplicationGateway New features

### PR DESCRIPTION
**Pull request by akshaysngupta**
This PR contains following changes:
1)	ApplicationGateway Ssl Policy custom cipher suites feature [new properties added to Sslpolicy Property of ApplciationGatewayPropertiesFormat]
2)	Get AvailableSslOption feature [new resource ApplicationGatewayAvailableSslOptions and child resource ApplicationGatewayPredefinedPolicy]
3)	Redirect Configuration feature [new child resource ApplicationGatewayRedirectConfiguration for Application Gateway, new properties in UrlPathMap, PathRules and RequestRoutingRule]
4)	Azure Websites feature [new properties in ApplicationGatewayBackendHttpSettingsPropertiesFormat, ApplicationGatewayProbePropertiesFormat, schema for property ApplicationGatewayProbeHealthResponseMatch]
5) Version update for Network related services
6) Tests in success state.

Associated pull request:
https://github.com/Azure/azure-rest-api-specs/pull/1285
https://github.com/Azure/azure-rest-api-specs/pull/1340
https://github.com/Azure/azure-rest-api-specs/pull/1323
https://github.com/Azure/azure-rest-api-specs/pull/1344

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@azuresdkci add to whitelist

**Comment by shahabhijeet** [comment]
@akshaysngupta add to white list

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Please bump up version of the nuget as well as assemblyfileversion.
As this is a breaking change due to api version change, will need to bump up Major version.

**Comment by shahabhijeet** [comment]
@akshaysngupta please have Deepak approve or anyone from network approve these changes.

**Comment by akshaysngupta** [comment]
I have changed the major version to 11.0.0.0 in assembly. I am not able to find project.json for Network.

**Comment by akshaysngupta** [comment]
I have changed the major version to 11.0.0.0 in Network.csproj

**Comment by shahabhijeet** [comment]
@akshaysngupta this is good to go, once @DeepakRajendranMsft approves it.

**Review by DeepakRajendranMsft — APPROVED** [review]

**Comment by shahabhijeet** [comment]
@akshaysngupta please pull latest and revert your version change to accommodate already changed files in this PR https://github.com/Azure/azure-sdk-for-net/pull/3414

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
