### PR TITLE
ADL Updates for .NET

### PR DESCRIPTION
**Pull request by begoldsm**
- Code gen update using latest AutoRest Tools
- Performance updates for file and folder upload and download
- Swagger updates for ADL Job, catalog and filesystem
- Custom "exists" functionality for some of our APIs (waiting for issue: https://github.com/Azure/autorest/issues/787)
- Rerun tests

### CODE REVIEW

**Comment by markcowl** [comment]
@begoldsm Please clean up the commits, by rebasing, or cherry-picking these commits into a new branch

**Comment by begoldsm** [comment]
@markcowl I rebased down to five commits. It looks like the PR changed a little though (127 files modified originally and now 126). I am doing some investigation to see what, if anything, actually changed while the CI runs.

**Comment by begoldsm** [comment]
I think I figured it out. My recording are bad. Hold please while I re-record.

**Comment by markcowl** [comment]
@begoldsm The breaking change tool detected breaking changes in your API without a major version bump.  Please consider mitigating the changes with customizations, or updating the major version.

**Comment by begoldsm** [comment]
@markcowl is this a hard requirement now? These "breaking changes" are in code that was pure placeholder code while we ironed out the full contract, so there are no real breaks that are happening here. I can do a major version bump, but I would prefer not to if we can avoid it.

**Comment by begoldsm** [comment]
@markcowl it looks like I fixed my tests and got everything in good shape. Can we get this merged? I will have one more PR after this for a swagger update that is currently in progress, but I think we can separate out these two PRs :).

**Comment by markcowl** [comment]
@begoldsm In the future, please work on making these PRs a more manageable size./  The size of this PR means that it has to be the last priority in the queue, as it requires syncing with your change locally just to review it.

**Comment by begoldsm** [comment]
@markcowl will do! In the future I will do AutoRest updates separately from core feature work. This PR ended up including both core code changes as well as an update to the latest AutoRest codegen package, which I agree makes checking the changes harder. My next change will be a small pure swagger change, I promise :)

**Comment by markcowl** [comment]
@begoldsm  Thanks for the fix to the test evironment, btw

**Pull request merged**
