### PR TITLE
Update version info

### PR DESCRIPTION
**Pull request by leonardbf**
Changes in this version: #7704

### CODE REVIEW

**Comment by leonardbf** [comment]
@yuemlu I made the version changes directly on the master branch of my fork. packageReleaseNotes were already updated but version in csproj was not. Also updated assemblyfileversion. Note that the diff of the PR shows all the files of the previous PR. I hope this is not a problem.

**Comment by isra-fel** [comment]
`AzureApiTag` in `AzSdk.RP.props` also needs to be updated, since you've change the api version

**Comment by isra-fel** [comment]
Otherwise it looks good to me @leonardbf

**Comment by leonardbf** [comment]
> `AzureApiTag` in `AzSdk.RP.props` also needs to be updated, since you've change the api version

@isra-fel Ok, updated

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
