### PR TITLE
Clients for new MI CRUD APIs

### PR DESCRIPTION
**Pull request by toki95**
The only difference from previous versions is another field and different response codes.

### CODE REVIEW

**Comment by allenjzhang** [comment]
> 		<Version>1.45.0-preview</Version>

Version update?

---
Refers to: sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/src/Microsoft.Azure.Management.Sql.csproj:10 in d5a5535. [](commit_id = d5a55355b69c7500ed77d3d456c54e5b2ae5c59e, deletion_comment = False)

**Comment by allenjzhang** [comment]
> <Project Sdk="Microsoft.NET.Sdk">

please update commit id in eng\mgmt\mgmtmetadata\sql_resource-manager.txt 

---
Refers to: sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/src/Microsoft.Azure.Management.Sql.csproj:1 in d5a5535. [](commit_id = d5a55355b69c7500ed77d3d456c54e5b2ae5c59e, deletion_comment = False)

**Review by allenjzhang — CHANGES_REQUESTED** [review]
Please review comments, make appropriate changes, and assign back to me. Thanks.

**Comment by toki95** [comment]
> Please review comments, make appropriate changes, and assign back to me. Thanks.

Done :)

**Comment by amolagar5** [comment]
@allenjzhang \ @toki95 , Please go ahead and merge these changes. Once Done I will update my PR to take these changes and update the version to 1.46, that way its cleaner and do not need merging of 2 PRs. Please let me know if that is not possible.

**Comment by toki95** [comment]
@allenjzhang can we merge this? :)

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
