### PR TITLE
ServiceBus Unsubscribe from receiver link

### PR DESCRIPTION
**Pull request by danielmarbach**
While fishing in the code I found this opportunity of unsubscribing. Not 100% sure if those changes are ok but I figured I send it in for a review in case you want to take it.

### CODE REVIEW

**Review by SeanFeldman — APPROVED** [review]

**Comment by jsquire** [comment]
@nemakam:  The changes look reasonable to me, but I lack a depth of understanding in this area of the codebase.   Would you be so kind as to give it a look and share your thoughts?

**Review by jsquire — APPROVED** [review]

**Comment by nemakam** [comment]
@danielmarbach - Curios as to how did you come across this? Was this causing a problem or just coincidentally ran into it?
These changes look good, but I think it might not cover all the cases. 
If one link closes due to some reason, we also recreate the links. In your PR, we are taking care of the latest link that was created and ensuring you are unsubscribing it. Alternatively, we can can remove this handler within `OnSendReceiveLinkClosed` which gets called every time the link is closed.

**Comment by nemakam** [comment]
On second thoughts, is this actually a bug? We call `ActiveClientLinkManager.Close()` when we want to close the sender/receiver, and at that point in time, the producer(`AmqpLink`) of the event itself is about to be garbage collected. So there is no memory leak in this case.
There is no advantage of this PR.
Anything that you think I'm missing? Any reason you think this PR is still worth merging? 
There is nothing wrong with the PR itself, but wonder if its gonna make any difference.

**Review by nemakam — CHANGES_REQUESTED** [review]
Blocking PR till the discussions are done.

**Comment by danielmarbach** [comment]
@nemakam I was experimenting a bit with the SDK (looking what would have to be done to do proper cancellation support). I stumbled over the handlers not being deregistered. I was aware that it probably wouldn't make a difference. Normally when I manage code bases I try to be mindful about event registration and deregistration to not fall into memory leak traps so I wondered if it would be good practice to do just do it. At the end I figured I'll send it in and see what you think. 

Happy for this to be closed if no value is seen in it (it is just code after all ;) )

**Pull request closed without merging**
