### PR TITLE
Fix casing in namespaces and files.

### PR DESCRIPTION
**Pull request by azabbasi**
We agreed to move to use IoT (capital T) instead of Iot in .NET track2 for package names and namespaces.

### CODE REVIEW

**Comment by digimaun** [comment]
What about the directory name? It is still `sdk/modelsrepository/Azure.Iot.*`

**Review by drwill-ms — APPROVED** [review]
If you want to rename files, it can't just be on case alone. You'll otherwise need to rename it to something different (commit to master) and then do a second rename to IoT.

**Review by digimaun — APPROVED** [review]

**Comment by azabbasi** [comment]
> If you want to rename files, it can't just be on case alone. You'll otherwise need to rename it to something different (commit to master) and then do a second rename to IoT.

I made two separate commits and it seems to have done the trick.

**Comment by azabbasi** [comment]
> What about the directory name? It is still `sdk/modelsrepository/Azure.Iot.*`

it should be fixed now.

**Comment by drwill-ms** [comment]
> I made two separate commits and it seems to have done the trick.

I'm not sure what is going to happen when you squash and it goes to master though, so keep an eye on it then.

**Comment by azabbasi** [comment]
> > I made two separate commits and it seems to have done the trick.
> 
> I'm not sure what is going to happen when you squash and it goes to master though, so keep an eye on it then.

Worked as expected.

**Pull request merged**
