### PR TITLE
Partner APIs for Express Route with fixes

### PR DESCRIPTION
**Pull request by vinayada1**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
@vinayada1 I don't see the related spec updates to make these properties read/write
Please provide spec PR link

**Review by dsgouda — CHANGES_REQUESTED** [review]
@vinayada1 does not look like you have generated this code using generate.ps1/generate.cmd scripts
Also, this looks like an additive change to the SDK, please bump the package version to `18.0.1-preview`

**Comment by vinayada1** [comment]
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/2795
@dsgouda : I did generate the code using generate.cmd since my swagger is checked in. Do you see any issues? Will update the package version

**Comment by vinayada1** [comment]
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/2795

@dsgouda : I did generate the code using generate.cmd. Do you see any issues? Will update the package version

**Comment by dsgouda** [comment]
@vinayada1  If you generate the code using generate.cmd related information will be logged in a txt file. We can't see that file in this PR.

**Comment by vinayada1** [comment]
@dsgouda Added network_resource-manager.txt file. Sorry.....overlooked that this was a modified file not an untracked file. The diff seemed like not related so had skipped it.

**Review by dsgouda — APPROVED** [review]
LGTM subject to builds passing.

**Pull request merged**
