### PR TITLE
Add generic Resources.Update method and test

### PR DESCRIPTION
**Pull request by jaredmoo**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by jaredmoo** [comment]
Latest published version is 1.6.0-preview and version is already bumped to 1.7.0-preview.

**Comment by shahabhijeet** [comment]
@vivsriaus can you check why Resource tests are failing? This is blocking this PR.

**Comment by shahabhijeet** [comment]
@azuresdkci retest this please

**Comment by shahabhijeet** [comment]
@jaredmoo please provide the PR for your swagger changes.

**Comment by jaredmoo** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/2061

**Comment by jaredmoo** [comment]
I have regenerated from latest swagger using C:\git\azure-sdk-for-net\src\sdks\Resource\Management.ResourceManager\generate.cmd .

**Comment by shahabhijeet** [comment]
@jaredmoo please reopen once this is ready to be merged.
if you want to track test debt workItem, please open a new issue to track it.

**Pull request closed without merging**
