### PR TITLE
Adding support for Vault upgrade for site recovery and backup vaults.

### PR DESCRIPTION
**Pull request by megjhu**
…kup and SiteRecovery resources

## Description

Adding suppport for Vault upgrade for site recovery and backup vaults.
Migrating customers from RDFE vaults to ARM.
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [Yes ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ Yes] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ Yes] Title of the pull request is clear and informative.
- [ Yes] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [Yes ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ NA] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [NA] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [NA ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by cormacpayne** [comment]
Hydra spec: https://github.com/Azure/hydra-specs-pr/pull/1379

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by cormacpayne** [comment]
@azuresdkci test this please

**Comment by cormacpayne** [comment]
LGTM

**Pull request merged**
