### PR TITLE
Stop defaulting region as it breaks UsGov/China resource deployments

### PR DESCRIPTION
**Pull request by JoshLove-msft**
We hardcoded the region to westus3 when the default was changed because we were seeing latency and flaky tests. This broke the weekly test pipelines since the default region doesn't get picked up for other clouds. Testing out removing the hardcoded westus3 to see if tests are stable.

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

**Comment by benbp** [comment]
@JoshLove-msft we support per cloud locations as well if it's needed in the future, e.g. https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/389/Configuring-Tests?anchor=test-environment-architecture

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft we support per cloud locations as well if it's needed in the future, e.g. https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/389/Configuring-Tests?anchor=test-environment-architecture

Good to know!

**Pull request merged**
