### PR TITLE
Fix #13671: [Flaky test] BearerTokenAuthenticationPolicy_SucceededFailedSucceeded

### LINKED ISSUE #13671: [Flaky test] BearerTokenAuthenticationPolicy_SucceededFailedSucceeded
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=467483&view=ms.vss-test-web.build-test-results-tab&runId=12156290&resultId=100265&paneView=debug

```
Error message
Expected: <System.InvalidOperationException>
But was:  null


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.BearerTokenAuthenticationPolicy_SucceededFailedSucceeded() in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 196

```

### PR DESCRIPTION
**Pull request by AlexanderSher**

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
Did net - core - ci hang?

**Comment by AlexanderSher** [comment]
I've been cancelling it to rerun tests multiple times

**Comment by pakrym** [comment]
Did you try running it locally in an infinite loop?

**Comment by AlexanderSher** [comment]
Yes. But I can try to run it in parallel

**Pull request merged**
