### PR TITLE
ADL Swagger update based on swagger validation

### PR DESCRIPTION
**Pull request by begoldsm**
This is an update based on the swagger validation tests. It also:
1. Makes it possible to add storage accounts during ADLA account
creation
2. Switch GetDebugDataPath to a GET (which it will be going forward)
3. Remove unused objects
4. Remove invalid return types (USqlSecrets are never returned from
CREATE calls, so this was a bug).

### CODE REVIEW

**Comment by markcowl** [comment]
@begoldsm Mostly looks good.  You will need to update generate.cmd to point to the commit containing the spec in the rest-api-specs repo.  You *should* also use the latest nightly for autorest (20161201, I believe).

Also, please include a link to the PR to the specs repo in your PR comments.

**Comment by begoldsm** [comment]
@markcowl oh great! I will update to the latest nightly now and re-run (hopefully the "using" issue is resolved) and here is a link to the PR: https://github.com/Azure/azure-rest-api-specs/pull/764

I will ping when the changes are done for generate.cmd and CI is passing again.

**Comment by begoldsm** [comment]
@markcowl https://github.com/Azure/azure-rest-api-specs/pull/764 and the updates are in for generate and the latest AutoRest nightly.

**Comment by begoldsm** [comment]
@markcowl can you take a look? CI is passing.

**Comment by begoldsm** [comment]
@markcowl for some reason my push of "Update to latest nightly" didn't go through until I made a trivial change after it. Please wait until this CI finishes and then it should be good to merge.

**Pull request merged**
