### PR TITLE
[AppConfig] 1.2.1 Hotfix Release Prep

### PR DESCRIPTION
**Pull request by jsquire**
# Summary

The focus of these changes is to remove the public surface added in the 1.3.x line to prepare for a hotfix release based on 1.2.0.   These changes already exist in `main` and are being brought over to a hotfix branch for release purposes.

### CODE REVIEW

**Comment by ShivangiReja** [comment]
Can we remove the snapshot samples and examples from the readme documentation as well?

**Comment by jsquire** [comment]
> Can we remove the snapshot samples and examples from the readme documentation as well?

Good catch.   I completely forgot those were there!

**Comment by jsquire** [comment]
The API View generated for this has a lot of noise due to suppressing the beta Snapshot API surface.   The comparison between this version (1.2.1) and the current GA (1.2.0) can be found [here](https://apiview.dev/Assemblies/Review/3c3fdb93337c4d5085b13f1c968e5aa7?diffRevisionId=3cab01bcc3814ee4a7a0adade12841dd&diffOnly=False&revisionId=d3b199a1b1a54b8187c4f5552146dce5&doc=False).

**Review by ShivangiReja — APPROVED** [review]

**Pull request merged**
