### PR TITLE
[Cognitive Services] March release (Add GetUsages operation, addnew/remove some API Kind)

### PR DESCRIPTION
**Pull request by felixwa**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by felixwa** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/2544
https://github.com/Azure/azure-rest-api-specs/pull/2627

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please execute the following steps
- `msbuild build.proj`
- `msbuild build.proj /t:Build /p:Scope=SDKs\DataFactory`

Please commit any artifacts/changes generated by these steps

**Comment by felixwa** [comment]
@dsgouda , I suppose you mean
msbuild build.proj
**msbuild.exe build.proj /t:build /p:Scope=SDKs\CognitiveService\management**

But anyway I executed both msbuild.exe build.proj /t:build /p:Scope=SDKs\CognitiveService\management and msbuild build.proj /t:Build /p:Scope=SDKs\DataFactory and did not find anything new generated.

**Comment by felixwa** [comment]
C:\GitHub\azure-sdk-for-net>msbuild build.proj
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/14/2018 12:17:11 PM.
Project "C:\GitHub\azure-sdk-for-net\build.proj" on node 1 (default targets).
GetLatestBuildTools:
  Updating tools ....
Init:
  Build tools update complete. Please execute specific target to complete you build process (e.g. msbuild build.proj /t
  :RunTests /p:Scope=SDKs\Compute)
Done Building Project "C:\GitHub\azure-sdk-for-net\build.proj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:23.11

C:\GitHub\azure-sdk-for-net>msbuild.exe build.proj /t:build /p:Scope=SDKs\CognitiveService\management
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/14/2018 12:17:42 PM.
Project "C:\GitHub\azure-sdk-for-net\build.proj" on node 1 (build target(s)).
CategorizeProjects:
  Categorizing Projects.....
  SDKProjects ....... 0

  TestSDKProjects ....... 0
  UnSupported Projects ....... 0
RestoreLatestProjects:
  Now Restoring ;;
BuildAzSdkProjects:
  IsBuildingInVS: false
  IsCIBuild: true
Done Building Project "C:\GitHub\azure-sdk-for-net\build.proj" (build target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.19

C:\GitHub\azure-sdk-for-net>msbuild build.proj /t:Build /p:Scope=SDKs\DataFactory
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/14/2018 12:17:53 PM.
Project "C:\GitHub\azure-sdk-for-net\build.proj" on node 1 (Build target(s)).
CategorizeProjects:
  Categorizing Projects.....
  SDKProjects ....... 1

  TestSDKProjects ....... 1
  UnSupported Projects ....... 0
RestoreLatestProjects:
  Now Restoring C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\Microsoft.Azure.Management.Data
  Factory.csproj;C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\DataFactory.Tests\DataFactory.Tests.csproj;
Project "C:\GitHub\azure-sdk-for-net\build.proj" (1) is building "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Mana
gement.DataFactory\Microsoft.Azure.Management.DataFactory.csproj" (2) on node 1 (Restore target(s)).
Restore:
  Committing restore...
  Assets file has not changed. Skipping assets file writing. Path: C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Man
  agement.DataFactory\obj\project.assets.json
  Restore completed in 72.74 ms for C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\Microsoft.A
  zure.Management.DataFactory.csproj.

  NuGet Config files used:
      C:\GitHub\azure-sdk-for-net\NuGet.Config
      C:\Users\felixwa\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
      C:\Program Files (x86)\NuGet\Config\ServiceFabricSDK.config

  Feeds used:
      C:\GitHub\azure-sdk-for-net\tools/LocalNugetFeed
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
      C:\Program Files\Microsoft SDKs\Service Fabric\packages
      D:\LocalNuGet
      http://wanuget/MSNugetMirror/nuget/
      http://wanuget/Official/nuget/
      https://api.nuget.org/v3/index.json
      https://msblox.pkgs.visualstudio.com/_packaging/AzureGenevaMonitoring/nuget/v3/index.json
      https://www.myget.org/F/autorest/api/v3/index.json
      https://www.nuget.org/api/v2/
Done Building Project "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\Microsoft.Azure.Manageme
nt.DataFactory.csproj" (Restore target(s)).

Project "C:\GitHub\azure-sdk-for-net\build.proj" (1) is building "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Data
Factory.Tests\DataFactory.Tests.csproj" (4) on node 1 (Restore target(s)).
Restore:
  Committing restore...
  Assets file has not changed. Skipping assets file writing. Path: C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Man
  agement.DataFactory\obj\project.assets.json
  Restore completed in 19.11 ms for C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\Microsoft.A
  zure.Management.DataFactory.csproj.
  Committing restore...
  Assets file has not changed. Skipping assets file writing. Path: C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Dat
  aFactory.Tests\obj\project.assets.json
  Restore completed in 41.77 ms for C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\DataFactory.Tests\DataFactory.Test
  s.csproj.

  NuGet Config files used:
      C:\GitHub\azure-sdk-for-net\NuGet.Config
      C:\Users\felixwa\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
      C:\Program Files (x86)\NuGet\Config\ServiceFabricSDK.config

  Feeds used:
      C:\GitHub\azure-sdk-for-net\tools/LocalNugetFeed
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
      C:\Program Files\Microsoft SDKs\Service Fabric\packages
      C:\Program Files\dotnet\sdk\NuGetFallbackFolder
      D:\LocalNuGet
      http://wanuget/MSNugetMirror/nuget/
      http://wanuget/Official/nuget/
      https://api.nuget.org/v3/index.json
      https://msblox.pkgs.visualstudio.com/_packaging/AzureGenevaMonitoring/nuget/v3/index.json
      https://www.myget.org/F/autorest/api/v3/index.json
      https://www.nuget.org/api/v2/
Done Building Project "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\DataFactory.Tests\DataFactory.Tests.csproj" (Re
store target(s)).

BuildAzSdkProjects:
  IsBuildingInVS: false
  IsCIBuild: true
  Building SDK Projects ..... C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\Microsoft.Azure.M
  anagement.DataFactory.csproj for net452
Project "C:\GitHub\azure-sdk-for-net\build.proj" (1) is building "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Mana
gement.DataFactory\Microsoft.Azure.Management.DataFactory.csproj" (2:21) on node 1 (Build target(s)).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the i
nput files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
_CopyFilesMarkedCopyLocal:
  Touching "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\obj\Debug\net452\Microsoft.Azure.Ma
  nagement.DataFactory.csproj.CopyComplete".
GenerateBuildRuntimeConfigurationFiles:
Skipping target "GenerateBuildRuntimeConfigurationFiles" because all output files are up-to-date with respect to the in
put files.
CopyFilesToOutputDirectory:
  Microsoft.Azure.Management.DataFactory -> C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\bin
  \Debug\net452\Microsoft.Azure.Management.DataFactory.dll
CleanupEmptyRefsFolder:
  Directory "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\bin\Debug\net452\refs" doesn't exi
  st. Skipping.
Done Building Project "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\Microsoft.Azure.Manageme
nt.DataFactory.csproj" (Build target(s)).

BuildAzSdkProjects:
  Building SDK Projects ..... C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\Microsoft.Azure.M
  anagement.DataFactory.csproj for netstandard1.4
Project "C:\GitHub\azure-sdk-for-net\build.proj" (1) is building "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Mana
gement.DataFactory\Microsoft.Azure.Management.DataFactory.csproj" (2:22) on node 1 (Build target(s)).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the i
nput files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
GenerateBuildDependencyFile:
Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
GenerateBuildRuntimeConfigurationFiles:
Skipping target "GenerateBuildRuntimeConfigurationFiles" because all output files are up-to-date with respect to the in
put files.
CopyFilesToOutputDirectory:
  Microsoft.Azure.Management.DataFactory -> C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\bin
  \Debug\netstandard1.4\Microsoft.Azure.Management.DataFactory.dll
CleanupEmptyRefsFolder:
  Directory "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\bin\Debug\netstandard1.4\refs" doe
  sn't exist. Skipping.
Done Building Project "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Management.DataFactory\Microsoft.Azure.Manageme
nt.DataFactory.csproj" (Build target(s)).

BuildAzSdkProjects:
  Building Test Projects ..... C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\DataFactory.Tests\DataFactory.Tests.csp
  roj for netcoreapp1.1
Project "C:\GitHub\azure-sdk-for-net\build.proj" (1) is building "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\Data
Factory.Tests\DataFactory.Tests.csproj" (4:11) on node 1 (Build target(s)).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the i
nput files.
CoreGenerateProgramFile:
Skipping target "CoreGenerateProgramFile" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
_CopyFilesMarkedCopyLocal:
  Touching "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\DataFactory.Tests\obj\Debug\netcoreapp1.1\DataFactory.Test
  s.csproj.CopyComplete".
_CopyOutOfDateSourceItemsToOutputDirectory:
Skipping target "_CopyOutOfDateSourceItemsToOutputDirectory" because all output files are up-to-date with respect to th
e input files.
GenerateBuildDependencyFile:
Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
GenerateBuildRuntimeConfigurationFiles:
Skipping target "GenerateBuildRuntimeConfigurationFiles" because all output files are up-to-date with respect to the in
put files.
CopyFilesToOutputDirectory:
  DataFactory.Tests -> C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\DataFactory.Tests\bin\Debug\netcoreapp1.1\DataF
  actory.Tests.dll
CleanupEmptyRefsFolder:
  Directory "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\DataFactory.Tests\bin\Debug\netcoreapp1.1\refs" doesn't e
  xist. Skipping.
Done Building Project "C:\GitHub\azure-sdk-for-net\src\SDKs\DataFactory\DataFactory.Tests\DataFactory.Tests.csproj" (Bu
ild target(s)).

Done Building Project "C:\GitHub\azure-sdk-for-net\build.proj" (Build target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.87

C:\GitHub\azure-sdk-for-net>git status
On branch MarchRelease
Your branch is up-to-date with 'origin/MarchRelease'.

nothing to commit, working tree clean

C:\GitHub\azure-sdk-for-net>

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
