### PR TITLE
Update .Net MGMT AppConfiguration API version to 2020-06-01

### PR DESCRIPTION
**Pull request by HarveyLink**
Update .Net MGMT AppConfiguration API version to 2020-06-01

### CODE REVIEW

**Review by erich-wang — CHANGES_REQUESTED** [review]
Please update the section 1.0.0-preview.2 in Changlog.md, the `(Unreleased)` should be removed.

**Comment by HarveyLink** [comment]
> Please update the section 1.0.0-preview.2 in Changlog.md, the `(Unreleased)` should be removed.

@erich-wang , Changelog.md is updated, `General New Features` part is quoted from https://github.com/Azure/azure-rest-api-specs/pull/9976

**Comment by allenjzhang** [comment]
> > Please update the section 1.0.0-preview.2 in Changlog.md, the `(Unreleased)` should be removed.
> 
> @erich-wang , Changelog.md is updated, `General New Features` part is quoted from [Azure/azure-rest-api-specs#9976](https://github.com/Azure/azure-rest-api-specs/pull/9976)

I still see `(Unreleased)` in the changelog.md.

**Comment by HarveyLink** [comment]
> > > Please update the section 1.0.0-preview.2 in Changlog.md, the `(Unreleased)` should be removed.
> > 
> > 
> > @erich-wang , Changelog.md is updated, `General New Features` part is quoted from [Azure/azure-rest-api-specs#9976](https://github.com/Azure/azure-rest-api-specs/pull/9976)
> 
> I still see `(Unreleased)` in the changelog.md.

If the `(Unreleased)` is removed, the accurate release date time must be followed, CI will fail due to no release date, so it will not be removed until we get the proper date.

**Pull request closed without merging**
