### PR TITLE
Update repo structure container registry 3

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Move DataPlane libraries to new sdk folder.
Update repo structure.

### CODE REVIEW

**Comment by chidozieononiwu** [comment]
@Azure/azure-sdk-eng

**Review by weshaggard — APPROVED** [review]
LGTM - Please ping the owner of this library in the PR so they are aware of this change coming in.

**Comment by chidozieononiwu** [comment]
@shahabhijeet 
@dsgouda

**Comment by chidozieononiwu** [comment]
@sajayantony

**Pull request merged**
