### PR TITLE
Areddish/training 3.1

### PR DESCRIPTION
**Pull request by areddish**
Update SDK for Training V3.1 release

1. Added three new methods to support suggesting tags and regions in projects using a trained iteration to help in labelling: 
    - SuggestTagsAndRegions
    - QuerySuggestedImageCount
    - QuerySuggestedImages

2. Added more types to ProjectSettings
3. Added more export targets

[Swagger PR #7074](https://github.com/Azure/azure-rest-api-specs/pull/7074)

### CODE REVIEW

**Comment by areddish** [comment]
Getting this started for feedback & will regenerate metadata once Swagger PR is completed to have metadata reference master fork/branch

**Comment by areddish** [comment]
Ping @AlexGhiondea and @erich-wang .. this has been sitting unreviewed for awhile now.

**Comment by isra-fel** [comment]
@kurtzeborn could you review this data plane PR, thanks?

**Review by AlexGhiondea — APPROVED** [review]
This seems to add new public APIs. Will this release with an updated version?

**Review by AlexGhiondea — APPROVED** [review]

**Comment by pakrym** [comment]
@areddish can you please rebase this PR

**Pull request merged**
