### PR TITLE
Support "New" in TableClient LINQ Expressions

### PR DESCRIPTION
**Pull request by gliljas**
The previous table clients (Cosmos and older) supported `x => x.DateTime > new DateTime(....)` in expressions, but this now throws an exception.

Supporting "New" shouldn't be different from supporting e.g method calls.

### CODE REVIEW

**Review by christothes — COMMENTED** [review]
Looks great, would you mind just adding a changelog entry?

**Comment by gliljas** [comment]
I'll add to the change log.

Should I merge the two (ExpressionVisitor from the other branch and tests from this)?

**Comment by christothes** [comment]
> I'll add to the change log.
> 
> Should I merge the two (ExpressionVisitor from the other branch and tests from this)?

Yes, please.

**Comment by gliljas** [comment]
Done. I also added a couple of fixes which prevented a full green test run on my computer, which runs with Swedish culture and comma as decimal separator.

**Review by christothes — APPROVED** [review]
Thanks for this contribution!

**Pull request merged**
