### PR TITLE
Use bug report form

### PR DESCRIPTION
**Pull request by pakrym**
Inspired by https://github.com/dotnet/runtime/issues/new?assignees=&labels=&template=01_bug_report.yml

### CODE REVIEW

**Comment by pakrym** [comment]
You can see the sample form at https://github.com/pakrym/issue-template-tests/issues/new?assignees=&labels=&template=01_bug_report.yml&title=%5BBUG%5D

**Comment by pakrym** [comment]
If we agree to proceed I'll convert other templates as well.

**Review by jsquire — APPROVED** [review]
This is fantastic!   I had no idea that you could do this.    If we get the set in the .NET repo revised to where we think we like them, I'm happy to take on getting them pushed across our repos.

**Comment by pakrym** [comment]
I've migrated other templates. You can see the sample at https://github.com/pakrym/issue-template-tests/issues/new/choose

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
