### PR TITLE
Updating Blueprint SDK to use latest swagger (doc updates + RG tagging + lock mode change)

### PR DESCRIPTION
**Pull request by stuartko**
A minor update to the Blueprint SDK that adds support for RG tagging (see PR https://github.com/Azure/azure-rest-api-specs/pull/5263 and ResourceGroupDefinition.cs), updates lock mode constants, and takes recent description updates made by our documentation writers.

### CODE REVIEW

**Review by filizt — COMMENTED** [review]
Is this from the latest swagger? I can't see the AssignmentLockMode changes.

**Comment by filizt** [comment]
> ChangeNotes for 0.10.0 (breaking changes):

Should we remove these comments? Or add the tags update to it?

---
Refers to: src/SDKs/Blueprint/Management.Blueprint/Microsoft.Azure.Management.Blueprint.csproj:16 in 51d3d10. [](commit_id = 51d3d10dcf1959eab4efeb8c41bb48d7d1d064ea, deletion_comment = False)

**Comment by stuartko** [comment]
> Is this from the latest swagger? I can't see the AssignmentLockMode changes.

I've now integrated your changes and updated the release notes/version.

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please generate the code using [generate.ps1](https://github.com/Azure/azure-sdk-for-net/blob/58086fb590a1b3c926fa8f1a02a4f492051effbd/src/SDKs/Blueprint/Management.Blueprint/generate.ps1) script and commit all changes generated.

**Comment by stuartko** [comment]
> Please generate the code using [generate.ps1](https://github.com/Azure/azure-sdk-for-net/blob/58086fb590a1b3c926fa8f1a02a4f492051effbd/src/SDKs/Blueprint/Management.Blueprint/generate.ps1) script and commit all changes generated.

Done.

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
will merge once CIs pass

**Pull request merged**
