### PR TITLE
WORK:5249248:- Point2Site and SKU/Resize Gateway support. Also, recorded tests after swagger conversion

### PR DESCRIPTION
**Pull request by Nilambari**

### CODE REVIEW

**Comment by DeepakRajendranMsft** [comment]
Please update the client version in the assembly and nuspec to 3.0.1

**Comment by dihan0604** [comment]
I have used 3.0.1 in PR: Add Authorized Key Parameter, could you use 3.0.2 ?

**Comment by Nilambari** [comment]
@DeepakRajendranMsft  Actually with AutoRest branch, there is no Microsoft.Azure.Management.Network.nuspec file present. I think the equivalent file is the project.json where I have modified client version along with in AssemblyFule.

**Comment by Nilambari** [comment]
Addressed the review comments. Can you Please help with the merge? Thanks!

**Pull request merged**
