### PR TITLE
Correcting Region and other enum constants to use proper .NET enum naming/capitalization conventions

### PR DESCRIPTION
**Pull request by martinsawicki**
(includes cleaning up affected samples by removing compilation warnings and other issues)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@martinsawicki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (marcins). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@martinsawicki please pull from upstream and resolve conflicts. I've merged test framework integration PR and that created a merge conflict in your PR.

**Comment by martinsawicki** [comment]
pulled form upstream.
would be helpful to process before any other Fluent PRs, as the merge conflict resolution was quite painful ;-)

**Comment by anuchandy** [comment]
LGTM

**Pull request merged**
