### PR TITLE
[ServiceBus] Add a failing test that demonstrates getting rules from a subscription with forwarding throws

### PR DESCRIPTION
**Pull request by danielmarbach**
This adds a failing test to demonstrate that the rule manager GetRules throws on an subscription with forwarding enabled with the following exception

```
System.InvalidOperationException : Cannot create a message browser on an entity with auto-forwarding enabled. Reference:df63bf1d-195a-4e70-be4d-3c14f3...

System.InvalidOperationException : Cannot create a message browser on an entity with auto-forwarding enabled. Reference:df63bf1d-195a-4e70-be4d-3c14f3441168, TrackingId:b5a2105b-0ae5-4093-86b4-c561d093979f_B40, SystemTracker:servicebusplaygrounddaniel:Topic:27ecec18-cba9-getrulesfroment|default-subscription, Timestamp:2023-03-09T21:02:39 Reference:4751a456-c309-430f-b242-6cc3091bea6f, TrackingId:d61f8eef-6e34-4c45-8f57-80dbf9b3e7ef_G18, SystemTracker:NoSystemTracker, Timestamp:2023-03-09T21:02:39
For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
```

but

```csharp
var otherRules = await serviceBusAdministrationClient.GetRulesAsync(topicScope.TopicName, topicScope.SubscriptionNames[0]).ToEnumerableAsync();
```

correctly returns the default rule.

My expectation would be that fetching rules should work independent of the entity doing forwarding or not. I think this is a service bug and not a rule manager problem

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by danielmarbach** [comment]
@JoshLove-msft @m-redding any thoughts? Is this being tracked somewhere? Do I need to turn this into an issue?

**Comment by danielmarbach** [comment]
Ping

**Comment by JoshLove-msft** [comment]
> Ping

Can you clarify what the goal of this PR is? It sounds like you are saying this is a service bug. If you want to add a test that covers the current behavior it would need to pass before we can merge it.

**Comment by danielmarbach** [comment]
@JoshLove-msft I created this PR to demonstrate the problem I raised in https://github.com/Azure/azure-sdk-for-net/issues/31625. Now I was wondering since it is a service problem whether I should simply close this PR or whether you would like to keep this one around. That's why I originally pinged on https://github.com/Azure/azure-sdk-for-net/pull/34816#issuecomment-1545154917 but I see my comment is unclear. I guess I will just close this one

**Pull request closed without merging**
