### PR TITLE
Make AmqpMessageId and AmqpAddress a readonly struct

### PR DESCRIPTION
**Pull request by danielmarbach**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by jsquire — APPROVED** [review]
LGTM, but I'd like @JoshLove-msft to offer thoughts, just in case there's some scenario that I'm not thinking of.

**Comment by jsquire** [comment]
Looks like CI is failing on Analyze due to needing to export the API.

**Comment by danielmarbach** [comment]
Will fix the API export. Sorry that is something I never remember to run :(

**Comment by jsquire** [comment]
> Will fix the API export. Sorry that is something I never remember to run :(

You're not alone there.  :smile:

**Review by JoshLove-msft — APPROVED** [review]
LGTM!

**Pull request merged**
