### PR TITLE
Custom Vision Training v3.3 and Prediction v3.1 Updates

### PR DESCRIPTION
**Pull request by areddish**
Update SDK to use

- Custom Vision Training v3.3
- Custom Vision Prediction v3.1

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @areddish please put a link to your openapi spec PR here, thanks

**Comment by areddish** [comment]
Hi @isra-fel, the spec PR is https://github.com/Azure/azure-rest-api-specs/pull/9522

Note that these changes are data-plane

**Comment by isra-fel** [comment]
Sorry, my bad :p

**Comment by areddish** [comment]
Ping @AlexGhiondea  for review, or should this be assigned to someone else for review?

**Review by AlexGhiondea — APPROVED** [review]

**Pull request merged**
