### PR TITLE
Auto rest

### PR DESCRIPTION
**Pull request by skomarag**
HI,

This changeset contains
1. Generated code with swagger which added new field
2. Tests in Network and COmpute
3. COde changes to support MultiIpconfig for Azure

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@skomarag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (skomar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by kirthik** [comment]
@skomarag : This PR has a number of commits unrelated to your change. Did you mean to send a PR against `master` branch or `AutoRest` branch?

**Comment by markcowl** [comment]
@skomarag This is way too many commits - please rebase these changes on the AutoRest branch, and please update the PR title to be more descriptive.

**Comment by markcowl** [comment]
@skomarag Kirthi is probably right about the intended branch target

**Comment by markcowl** [comment]
@skomarag This should be targeted at AutoRest, I believe, so closing this PR

**Pull request closed without merging**
