### PR TITLE
Hide DynamicDataProperty

### PR DESCRIPTION
**Pull request by annelo-msft**
Addresses https://github.com/Azure/azure-sdk-for-net/issues/35944

- [ ] Make DynamicDataProperty internal and implement IDynamicMetaObjectProvider to fulfill its public contract

### CODE REVIEW

**Review by heaths — COMMENTED** [review]
The code looks fine, but I admit I'm not understanding the overall change. How did this work before? Reading through the PDF about `IDynamicMetaObjectProvider`, I'm curious how this worked before without it. You made the type `internal` but there was no other impact on the public API so this clearly wasn't a type returned by any public contract.

Given I've only reviews some of the DynamicData PRs, I don't feel I have the context to sign off but maybe we could chat briefly offline. From the test, I *think* the idea is that you were able to return a discrete type before but it wasn't necessary dynamic, but now it can be. Is that correct? And that's why you needed to implement `IDynamicMetaObjectProvider`?

**Comment by annelo-msft** [comment]
> The code looks fine, but I admit I'm not understanding the overall change. How did this work before? 

It worked prior to this change because DynamicDataProperty was a public type.  The DLR was resolving the items returned from [ObjectEnumerator](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/DynamicData/DynamicData.ObjectEnumerator.cs#L17), which implements `IEnumerable<DynamicDataProperty>` as `DynamicDataProperty` types, and then accessing their public members.

If we were only to change DynamicDataProperty to internal, the DLR might be able to resolve the type, but it would also know that callers outside the assembly no longer have access to the type or its members.  So trying to call `.Name` or `.Value` on the dynamic item will throw a Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.  Specifically, you'd get:
`Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : 'System.ValueType' does not contain a definition for 'Name'`, so it looks it actually resolves to the public base type of the internal type.

IDynamicMetaObjectProvider is a public interface, so I we can still return the type from the enumerator and anyone accessing it outside the assembly (through the dynamic keyword) will see it as an implementation of that interface.  They can only see the interface, not the internal type, but this is sufficient for us to implement the dynamic bindings to the member names.

**Comment by heaths** [comment]
Thank you! That explain everything.

**Review by heaths — APPROVED** [review]
Thanks for the clarification on how it was used. That explains everything. It was the lack of any other change to the public API that had me confused, but your explanation about `ObjectEnumerator` - also an `internal` - was key.

**Pull request merged**
