### PR TITLE
Make ConnectionStringParser public for consumers to use it

### PR DESCRIPTION
**Pull request by tomkerkhove**
Make ConnectionStringParser public for consumers to use it

### CODE REVIEW

**Comment by jsquire** [comment]
Hi @tomkerkhove.   Thank you for your contribution.   Because this impacts he pubic API surface, this change would need to be coordinated across languages and subject to review and approval by the Azure SDK architecture board.  As a result, this isn't a change that we can accept without some diligence.

To be transparent, the area of connection string builders/parsers is one where some conversation is taking place and our plans have not yet been solidified.  As we don't yet have a design or timeline, I'm going to close this out for now.  Thank you, again, for your interest in helping to improve the Azure SDK experience and for your contribution.

**Comment by SeanFeldman** [comment]
> To be transparent, the area of connection string builders/parsers is one where some conversation is taking place and our plans have not yet been solidified. As we don't yet have a design or timeline, I'm going to close this out for now. Thank you, again, for your interest in helping to improve the Azure SDK experience and for your contribution.

I'll just add that I'm happy to see the message about the connection string is not just the message I brought up in the past.

**Comment by tomkerkhove** [comment]
Hm sad to hear this is not coming soon, this is an essential piece for working with connection string, certainly given entity-scoped connection strings are not supported (#15864).

Happy to see this will, hopefully, come through https://github.com/Azure/azure-sdk-for-net/issues/15892.

**Comment by jsquire** [comment]
To clarify, my intent was not to imply a timeline.  This is an active workstream and is something that we'd like to include in the short term.

**Pull request closed without merging**
