### PR TITLE
SDK Updated with latest version of Network cloud API 2023-07-01

### PR DESCRIPTION
**Pull request by priyamshet**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by mbashtovaya** [comment]
@archerzz we've reached out on the chat regarding pipeline issues, but would appreciate if you can look at it. it is not clear what is failing and why.

**Review by archerzz — COMMENTED** [review]
@mbashtovaya The PR itself looks good to me, since it contains only removal of codes. However, I reviewed the whole SDK interface as this is the GA release, and I have comments not suitable to put here.
Can you check them in https://apiview.dev/Assemblies/Review/c5e4ddf1a5ad41c1946bcb83676ea8f4 ? Thanks.

**Comment by priyamshet** [comment]
@archerzz  Thanks for the review , we have few questions on the feedback you provided https://apiview.dev/Assemblies/Review/c5e4ddf1a5ad41c1946bcb83676ea8f4 , appreciate if you could clarify them.

**Comment by priyamshet** [comment]
@archerzz Thanks so much for the review.

 We have addressed most of the comments, But have question on few https://apiview.dev/Assemblies/Review/c5e4ddf1a5ad41c1946bcb83676ea8f4 , appreciate if you could clarify them.

**Review by archerzz — APPROVED** [review]

**Review by ArthurMa1978 — CHANGES_REQUESTED** [review]
I'm working on the final polish

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
