### PR TITLE
Remove upper limit for DedicatedHostGroup's PlatformFaultDomainCount and DedicatedHost's PlatformFaultDomain

### PR DESCRIPTION
**Pull request by dochung4**

### CODE REVIEW

**Comment by dochung4** [comment]
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/10813

**Comment by dochung4** [comment]
@bquantump , can you please review?

**Comment by bquantump** [comment]
This looks like this needs to be a version change, please follow this check list:

 Swagger review PR(s) link in PR description, and the PR(s) is merged
 Metadata file eng/mgmt/mgmtmetadata_{RP}.txt is updated
 Versions in *.csproj and AssemblyInfo.cs are updated, and follows semver
 Release notes in *.csproj is updated
 If there's a API-version update, the API tags in Az.Sdk.props are updated
 Generated code is not touched

**Review by bquantump — CHANGES_REQUESTED** [review]
This looks like this needs to be a version change, please follow this check list:

- Swagger review PR(s) link in PR description, and the PR(s) is merged
- Metadata file eng/mgmt/mgmtmetadata_{RP}.txt is updated
- Versions in *.csproj and AssemblyInfo.cs are updated, and follows semver
- Release notes in *.csproj is updated
- If there's a API-version update, the API tags in Az.Sdk.props are updated
- Generated code is not touched

**Comment by bquantump** [comment]
@dochung4 Any update here? Else I will close this.

**Comment by dochung4** [comment]
@bquantump , I pushed a new iteration. Please take a look.

- Swagger review PR(s) link in PR description, and the PR(s) is merged
    -> Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/10813, which has already been merged. I am not sure whether there is a separate place for "PR description", but if there is, please let me know.
 - Metadata file eng/mgmt/mgmtmetadata_{RP}.txt is updated
    -> Done
 - Versions in *.csproj and AssemblyInfo.cs are updated, and follows semver
    -> Done
 - Release notes in *.csproj is updated
    -> Done
 - If there's a API-version update, the API tags in Az.Sdk.props are updated
    -> There is no API-version update
 - Generated code is not touched
    -> If you are referring to "sdk\compute\Microsoft.Azure.Management.Compute\src\Generated", then it is actually expected to be touched, and I confirm that the changes there are correct.

**Comment by dochung4** [comment]
@bquantump , can you please review?

**Review by bquantump — APPROVED** [review]

**Pull request merged**
