### PR TITLE
Reverting Blob Storage Support for ParameterBindingData in webjobs

### PR DESCRIPTION
**Pull request by amnguye**
Reverts https://github.com/Azure/azure-sdk-for-net/pull/31757

This is in reference to attempt to resolve this github issue.
https://github.com/Azure/azure-sdk-for-net/issues/34467

Created a github issue to eventually renable this feature.
https://github.com/Azure/azure-sdk-for-net/issues/34509

### CODE REVIEW

**Review by seanmcc-msft — APPROVED** [review]

**Comment by seanmcc-msft** [comment]
Might want to update the changelog

**Review by liliankasem — APPROVED** [review]

**Comment by amnguye** [comment]
waiting on offline discussions to resolve before further progress with this PR

**Comment by amnguye** [comment]
Closing in preference to Azure Functions Core Tools being released over reverting this support.

**Pull request closed without merging**
