### PR TITLE
Updating BlackForest Environment

### PR DESCRIPTION
**Pull request by diveeran**
Added the environment settings for the Azure Blackforest.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@v-diveer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by v-diveer** [comment]
completed the cla

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by azurecla** [comment]
__@v-diveer__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by markcowl** [comment]
@v-diveer We are handling GermanCloud support in a separate PR, so closing this for now.

**Comment by colemickens** [comment]
Were the endpoints added after all? Don't see them in master or pr.

**Comment by colemickens** [comment]
Ping? Does .NET SDK support Germany Cloud at all right now?

**Pull request closed without merging**
