### PR TITLE
[WIP] Add cancellation token support to MessageReceiver ReceiveAsync.

### LINKED ISSUE #258: CancellationToken support
## Actual Behavior
ReceiveAsync and ReceiveBatchAsync wait until a message is present on the queue. To shut down, the Abort() method must be invoked or a timeout added (which will lead to pointless loops); the Abort() will abort all the receive calls, the only way around is breaking the guidelines of the lifetime and create multiple clients in the application for the same queue (not tested and might fail if the internal cache of queues returns the same).

## Expected Behavior
An overload of the receive methods supporting a cancellation token to exit gracefully a call.

Thank you.

### PR DESCRIPTION
**Pull request by pvginkel**
Implemented cancellation token support in Microsoft.Azure.Amqp and incorporated into `MessageReceiver.ReceiveAsync`.

There are a number of tickets requesting cancellation token support for this method, with different reasons. The primary reason I see this functionality is critical is to be able to manage lock tokens. With the existing functionality, the following scenario is very tricky to implement correctly:

* There is a continuous receive loop, starting work based on incoming messages and tracking lock tokens;
* If work completes, the lock token is completed;
* If the receive loop ends, all lock tokens that weren't yet completed are abandoned.

The problem is that there are race conditions between closing the receiver and the managing the lock tokens. The following can happen:

* `ReceiveAsync` completes with new messages;
* Parallel to that, the application shuts down:
  * All outstanding lock tokens are abandoned;
  * `CloseAsync` is called;
* While the shut down is happening, new lock tokens are still being added to be abandoned.

This race condition ensures that we cannot cleanly shut down an application. If this would be because of scale down, this means that the messages that couldn't be abandoned would be stuck until the lock expires.

With these changes, the workflow would work as follows:

* The application shuts down;
* A `TaskCompletionSource` is prepared for signalling of the end of the receive loop;
* The cancellation token given to `ReceiveAsync` is signalled;
* The task of the `TaskCompletionSource` is awaited;
* Any outstanding lock tokens are abandoned;
* `CloseAsync` is called.

Depends on https://github.com/Azure/azure-amqp/pull/150.
Closes https://github.com/Azure/azure-service-bus-dotnet/issues/258 and others.

### CODE REVIEW

**Comment by pvginkel** [comment]
> Can one of the admins verify this patch?

This depends on https://github.com/Azure/azure-amqp/pull/150, so will require that to be merged and released first. I'm not sure how work over repositories is synced. Should I maybe have marked this as `[WIP]`?

**Comment by jsquire** [comment]
//cc: @SeanFeldman

**Comment by pvginkel** [comment]
@nemakam changed the title. Sure I can add some test cases. That'll probably the weekend though.

**Comment by pvginkel** [comment]
@SeanFeldman I understand there are processes involved around this. I have no problem following this path.

There's a bigger issue however with the AMQP library changes. I'm getting pushback there. See e.g. https://github.com/Azure/azure-amqp/pull/150#issuecomment-525035240. The issue being raised is that this functionality should not be necessary, because the AMQP library is properly implementing the protocol and the only reason for getting this change is to work around limitations of Azure Service Bus, i.e. the requirement of the client having to release locks. A suggestion was offered to set `AmqpLinkSettings.Source.DefaultOutcome` to `AmqpConstants.ReleasedOutcome`, but this setting also is ignored by Azure Service Bus and does not have the effect of releasing the messages when closing the receiver.

I appreciate that the AMQP library is a standard protocol implementation and not an Azure Service Bus implementation, but the current Azure SDK library is depending on it, and with the current available functionality I cannot implement a proper shutdown sequence. Honestly it's all a bit puzzling to me since even the AMQP library has "Azure" in the NuGet name, and the comments in that PR thread admit that all of this is a result of the implementation choices made in Azure Service Bus.

Is there any way this process can be streamlined? Do I try to convince the Microsoft.Azure.Amqp team on my own or would anyone from this thread be able to champion these changes?

**Comment by SeanFeldman** [comment]
Adding @nemakam

**Comment by pvginkel** [comment]
@nemakam added a few unit tests with different scenarios and added the new overloads to the `IMessageReceiver` interface. These tests by their nature do introduce delays, and aren't exact because of timer jitter. To be specific, I'm testing on ranges (so a timeout of 2 seconds should complete between 1.8 and 3 seconds), so this can introduce sporadic issues. I'm not sure how best to handle this, and couldn't find good examples in the code base.

**Comment by jsquire** [comment]
Thank you, @pvginkel, for your contribution. 

There's a new version of the Service Bus client in progress with API support for cancellation tokens.  Since this being stalled for some time, I'm going to close this out.    @nemakam, @pvginkel, please feel free to reopen if this is still something that you'd like to pursue.

**Pull request closed without merging**
