### PR TITLE
Updating Security Center client

### PR DESCRIPTION
**Pull request by MatanShabtay**
Regenerating SecurityCenter client from swagger.

**APIs added:**
1. apdativeNetworkHardenings
2.allowedConnections
3.topology

Added UTs for operations without tests such as AdaptiveApplicationControls

### CODE REVIEW

**Comment by MatanShabtay** [comment]
@isra-fel  / @erich-wang  I will appreciate your review here

**Comment by isra-fel** [comment]
Since Microsoft.Azure.Management.SecurityCenter 2.0.0 was released, Matan, I think you need to update the versions in `Microsoft.Azure.Management.SecurityCenter.csproj` and `AssemblyInfo.cs`. Others LGTM.

Sorry about the inconvenience again.

**Comment by MatanShabtay** [comment]
> Since Microsoft.Azure.Management.SecurityCenter 2.0.0 was released, Matan, I think you need to update the versions in `Microsoft.Azure.Management.SecurityCenter.csproj` and `AssemblyInfo.cs`, plus the release notes in csproj
> 
> Others LGTM.
> Sorry about the inconvenience again.

Done

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
