### PR TITLE
Add bing AutoSuggest API

### PR DESCRIPTION
**Pull request by gu-wei**
Add bing AutoSuggest API:

generated stub code from spec file
add wrapper code and proj files
add test code

### CODE REVIEW

**Review by dsgouda — APPROVED** [review]
LGTM
@gu-wei Thanks for integrating all the feedback

**Comment by dsgouda** [comment]
Will merge on CIs passing

**Comment by dsgouda** [comment]
@gu-wei Please join the Azure org [here](http://aka.ms/azuregithub) which should kick off the Jenkins build.

**Comment by dsgouda** [comment]
@azuresdkci Retest this please

**Comment by dsgouda** [comment]
@gu-wei  Build is kicked off, waiting to pass, will merge once done

**Comment by gu-wei** [comment]
nuget: https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Search.AutoSuggest/
thank you for the help!

**Pull request merged**
