### PR TITLE
Add support for nested polymorphic objects in Firewall Policy

### PR DESCRIPTION
**Pull request by gimotwanMSFT**
The autogenerated code for Firewall Policy is incorrect since the
PolymorphicJsonConverter used does not support nested polymorphism

We have FirewallPolicyRule with Derived Types: FirewallPolicyFilterRule
and FirewallPolicyNatRule.

These derived types have one/more FirewallPolicyRuleCondition(s), with
Derived Types: NetworkRuleCondition and ApplicationRuleCondition.

We need to customize the initialization of the NetworkManagementClient
to add a polymorphicJsonConverter that accepts the two class types and
discriminator fields. Also, the PolyMorphicJsonConverter<T1, T2> is a wrapper over the PolymorphicJsonConverter<T1> available in the Microsoft.Rest.Serialization assembly.

### CODE REVIEW

**Comment by gimotwanMSFT** [comment]
How do I add unit tests to verify this change?

**Comment by isra-fel** [comment]
> How do I add unit tests to verify this change?

You can add tests in your module's test project, i.e.  `sdk\network\Microsoft.Azure.Management.Network\tests\Tests`

**Review by anton-evseev — APPROVED** [review]

**Comment by gimotwanMSFT** [comment]
@isra-fel  I've added unit tests. Also, the changes have been approved by Anton from our team.

**Comment by weshaggard** [comment]
@isra-fel @erich-wang It looks like the necessary changes were made and signed off so I'm helping @gimotwanMSFT and merging this to unblock progress. If there are further changes requested please work with @gimotwanMSFT.

**Pull request merged**
