### PR TITLE
Update public api generator to 9.3

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
Looks like the build failure is related to another test in the repo and not introduced due to my changes right?

**Comment by pakrym** [comment]
Failures are unrelated.

**Review by pakrym — APPROVED** [review]

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
Hey @danielmarbach, do you have the CLA signed (https://cla.opensource.microsoft.com/)?

**Comment by danielmarbach** [comment]
Yeah not the first time I contributed to this repo so technically there should be a track record of my CLA somewhere

**Comment by pakrym** [comment]
Thank you @danielmarbach

**Pull request merged**
