### PR TITLE
Use HttpClient non-validating header enumeration

### PR DESCRIPTION
**Pull request by pakrym**
Depends on getting .NET 6 support and https://github.com/dotnet/runtime/issues/62024

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
This bot does not give up easily.

**Comment by JoshLove-msft** [comment]
@christothes should we merge this?

**Comment by JoshLove-msft** [comment]
> > @christothes should we merge this?
> 
> As I recall, it required an update to the version of .NET we require for version 6.

According to this comment, the bug is fixed - https://github.com/Azure/azure-sdk-for-net/pull/25515#issuecomment-1045426765

**Comment by JoshLove-msft** [comment]
> > > Yes, I meant that to consume the fix, we need to bump the .NET version in the props.
> > 
> > 
> > Can you clarify which version you are referring to?
> 
> I believe [this](https://github.com/Azure/azure-sdk-for-net/blob/main/global.json#L6) needs to be at least [6.02](https://github.com/dotnet/runtime/issues/62024#issuecomment-995598008)

But that's the SDK version. Isn't this in issue in the .NET runtime that was fixed? Won't customers get the correct behavior if they have the latest .NET 6 runtime?
/cc @weshaggard

**Comment by JoshLove-msft** [comment]
> Yes I think this should be a runtime fix not a sdk change.

@christothes pointed out that we may need to update the SDK version to ensure that the proper runtime is used in our tests.

**Comment by weshaggard** [comment]
I think this branch is too outdated. We should try and pull this change on top of the latest changes in main, ideally a rebase not a merge.

**Comment by pakrym** [comment]
This is a good change. Free perf on the hot path. Consider merging. cc @christothes @JoshLove-msft @KrzysztofCwalina

**Comment by JoshLove-msft** [comment]
Hello @pakrym and Happy New Year!!

This was added by @AlexanderSher in https://github.com/Azure/azure-sdk-for-net/commit/19e5837f0dba54582650579b17f7f3bbeb21b6ce.

**Comment by JoshLove-msft** [comment]
>  [  ](https://camo.githubusercontent.com/b1f257f5b8b095be2b3782d48cb0191207724e040f4ca87c6336e932201a8957/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6d56713373334f553473306162747a704f492f67697068792e676966) [ ](https://camo.githubusercontent.com/b1f257f5b8b095be2b3782d48cb0191207724e040f4ca87c6336e932201a8957/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6d56713373334f553473306162747a704f492f67697068792e676966)

I hope not - you are missed my friend!

**Pull request closed without merging**
