### PR TITLE
[AzConfig] Hide request id

### PR DESCRIPTION
**Pull request by maririos**
Solves issue: https://github.com/Azure/azure-sdk-for-net-lab/issues/120

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
The PR looks good. 
But there is an architectural decision we need to make and record in guidelines: are request IDs something that stays constant between retires, or each retry should have a new request ID. @JeffreyRichter, @johanste, any opinions on this?

**Comment by JeffreyRichter** [comment]
The request Id remains the same across retries.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://azure.microsoft.com/training/distributed-cloud-apps/>)

________________________________

**Comment by maririos** [comment]
I thought about that too and saw issue https://github.com/Azure/Azconfig-DotnetSdk/issues/50#issuecomment-467152143 from the service team, where the result is in concordance with Jeff.

**Comment by KrzysztofCwalina** [comment]
@JeffreyRichter, it might be worth adding to our guidelines.

**Review by KrzysztofCwalina — APPROVED** [review]

**Pull request merged**
