### PR TITLE
Regenerate .NET SDK for Front Door to Include Recent Swagger Changes

### PR DESCRIPTION
**Pull request by jessicl-ms**
**Summary:**

Regenerating .NET SDK for Front Door to include recent [Swagger changes](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/frontdoor/resource-manager/Microsoft.Network/stable/2019-05-01/frontdoor.json) that added the following parameters:

- HealthProbeSettingsUpdateParameters: HealthProbeMethod (Configures which HTTP method to use to probe the backends defined under backendPools) and EnabledState (Operational status of the Front Door load balancer.)
- BackendPoolsSettings: sendRecvTimeoutSeconds (Send and receive timeout on forwarding request to the backend. When timeout is reached, the request fails and returns.)
- CustomHttpsConfiguration: minimumTlsVersion (The minimum TLS version required from the clients to establish an SSL handshake with Front Door.)

**How Verified:**

- Modified unit test to include new parameters

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @jessicl-ms , please fix the CI errors, and you might as well want to update the tags in `AzSdk.RP.props`

**Comment by jessicl-ms** [comment]
> Hi @jessicl-ms , please fix the CI errors, and you might as well want to update the tags in `AzSdk.RP.props`

I updated the tags in AzSdk.RP.props. Will work on figuring out why the unrelated WAF tests are failing.

**Comment by eschwabe** [comment]
>                                                 Action = "Redirect",

This is causing the WAF unit tests to fail when running in record mode. Change it to the following to make the tests work.
RuleId = "942100"

---
Refers to: sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/tests/ScenarioTests/FrontDoorTests.cs:226 in 50ef286. [](commit_id = 50ef28635baaa832bd419d2cbffcf5010c58cee8, deletion_comment = False)

**Comment by jessicl-ms** [comment]
Hi @isra-fel A couple of the ci are failing with this error 
error : Failed to resolve SDK 'Microsoft.Build.CentralPackageVersions/2.0.36'. Package restore was successful but a package with the ID of "Microsoft.Build.CentralPackageVersions" was not installed. I'm unable to repro this locally. Have you seen this error before? Is this a build issue caused by a version update? Thanks!

**Review by isra-fel — APPROVED** [review]

**Comment by isra-fel** [comment]
@jessicl-ms Re-run the piplines, all passed. I'll just go and merge it.

**Comment by jessicl-ms** [comment]
> @jessicl-ms Re-run the piplines, all passed. I'll just go and merge it.

Thank you!

**Pull request merged**
