### PR TITLE
Removing unnecessary tags

### PR DESCRIPTION
**Pull request by postmeback**
It is just a typo fix.

### CODE REVIEW

**Comment by sharon-dinara** [comment]
Thanks for the clarification on wording. Actually still wondering how the reserved boolean is used - what behavior change does it drive within the App Service?

**Comment by postmeback** [comment]
Hi,

Can it be reviewed ?

**Comment by live1206** [comment]
@postmeback This file is generated by autorest.csharp, we can't simply change it directly in this PR. 
It needs a proper fix in the generator, created https://github.com/Azure/autorest.csharp/issues/3455 for it.

**Comment by live1206** [comment]
As described in https://github.com/Azure/autorest.csharp/issues/3455#issuecomment-1571404722, we will not fix this description since .NET SDK Track 1 is deprecated.

**Comment by postmeback** [comment]
Okay

**Pull request closed without merging**
