### PR TITLE
Add Language Identification to <code> in SnippetGenerator

### PR DESCRIPTION
**Pull request by scbedd**
Hey @pakrym I've been recommended to make this change to resolve the issues with code display.

### CODE REVIEW

**Comment by pakrym** [comment]
Correct me if I'm wrong but the case that originally didn't work had language attribute on it.

**Comment by pakrym** [comment]
Yeah, https://ceapex.visualstudio.com/Engineering/_workitems/edit/227459/?triage=true

**Comment by scbedd** [comment]
Yes, but I'm wondering if they've bugfixed some stuff as well. The DigitalTwins stuff didn't render properly either.  I guess this means I'll have to update my test DLL and prove it to them again.

**Comment by jsquire** [comment]
Hi @scbedd.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by jsquire** [comment]
Since there hasn't been recent engagement, I'm going to close this out.  Please feel free to reopen if you'd like to continue working on these changes.

**Pull request closed without merging**
