### PR TITLE
Fix tests broken by backend changes

### PR DESCRIPTION
**Pull request by mentat9**
Recreated this PR since all of the sdk files got moved.

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@mentat9 please pull latest from upstream.
I had marked your test project not be built in CI
You can get the latest from upstream and adjust the values in your test project approriately
```
<PropertyGroup>
    <ExcludeFromBuild>true</ExcludeFromBuild>
    <ExcludeFromTest>true</ExcludeFromTest>
</PropertyGroup>
```

**Comment by mentat9** [comment]
Done, thanks @shahabhijeet. All checks passed now.

**Comment by mentat9** [comment]
@shahabhijeet can we merge this? I don't think anything else is needed except your signoff.

**Comment by erich-wang** [comment]
@mentat9 , if ExcludeFromTest and ExcludeFromBuild are present in your test csproj, make sure their value are false, otherwise you tests won't be run from CI

**Comment by mentat9** [comment]
OK, so it looks you guys disabled the Resource tests because the Linux test harness isn't able to resolve project references. Should I disable them again?

**Comment by mentat9** [comment]
Thanks @erich-wang.

**Pull request merged**
