### PR TITLE
Enable xml doc comments for our client libraries

### PR DESCRIPTION
**Pull request by weshaggard**
As part of enabling this a number of xml doc comments needed to be fixed or
warnings temporarily disabled to get a clean build. Follow-up issues will
be filed for each class of warnings that needed to be disabled.

PTAL @AlexGhiondea @chidozieononiwu @tg-msft @pakrym

### CODE REVIEW

**Comment by weshaggard** [comment]
I've filed https://github.com/Azure/azure-sdk-for-net/issues/6871 and https://github.com/Azure/azure-sdk-for-net/issues/6870 as follow-up issues to fix some of the doc comment issues I didn't address in this PR. With this PR I fixed a lot of trivial issues but my main goal was to get the xml doc files generating.

**Comment by weshaggard** [comment]
I filed a couple more issues https://github.com/Azure/azure-sdk-for-net/issues/6873 and https://github.com/Azure/azure-sdk-for-net/issues/6872

**Review by pakrym — APPROVED** [review]
LGTM

**Comment by tg-msft** [comment]
Manually editing the generated code is not ideal.  Can we just exclude /Generated/*RestClient.cs for now?  All of that's going to be blown over the next time we need to make any change.

**Comment by weshaggard** [comment]
>Manually editing the generated code is not ideal. Can we just exclude /Generated/*RestClient.cs for now? All of that's going to be blown over the next time we need to make any change.

I don't know of any good way to skip those files as the they generate errors and not warnings as most of them are invalid xml. The only option would be to disable xml doc  generation completely which means no docs at all.

**Comment by tg-msft** [comment]
Alright, I'll front load that work.  Heads up @pakrym that you'll need to avoid any of your renames requiring generator changes until I get this addressed.

**Review by AlexGhiondea — APPROVED** [review]

**Review by maririos — APPROVED** [review]

**Pull request merged**
