### PR TITLE
Utilize formatted message from AzureEventSourceListener in LogEvent

### LINKED ISSUE #44028: Azure.Monitor.OpenTelemetry.AspNetCore.Internals.AzureSdkCompat.AzureEventSourceLogForwarder double formats event messages
https://github.com/Azure/azure-sdk-for-net/blob/c4418cd3e85f2e01a92b702414244647ff3695df/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Internals/AzureSdkCompat/AzureEventSourceLogForwarder.cs#L70

calls `LogEvent`, but ignores the formatted string coming from the `s` parameter.

`LogEvent` then calls _formatMessage here:
https://github.com/Azure/azure-sdk-for-net/blob/c4418cd3e85f2e01a92b702414244647ff3695df/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Internals/AzureSdkCompat/AzureEventSourceLogForwarder.cs#L34

which is defined as:
https://github.com/Azure/azure-sdk-for-net/blob/c4418cd3e85f2e01a92b702414244647ff3695df/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/Internals/AzureSdkCompat/AzureEventSourceLogForwarder.cs#L64

Then `EventSource.Format()` calls:
https://github.com/Azure/azure-sdk-for-net/blob/2a0e020ae9348cb31af769027efd6b1491595a9d/sdk/core/Azure.Core/src/Shared/EventSourceEvent.cs#L58

This seems to effectively calls `EventSourceEventFormatting.Format` twice.

(related to https://github.com/Azure/azure-sdk-for-net/pull/43947#issuecomment-2111253949)

### PR DESCRIPTION
**Pull request by christothes**
closes #44028 

@lmolkova - If this fix makes sense, there are other files where we should make this fix.

### CODE REVIEW

**Comment by pharring** [comment]
I think the desire in the original code is to defer formatting the message until/unless it's absolutely needed. In particular, you want to avoid (expensive) formatting if the log level would otherwise filter the event entirely.

I would propose an alternative where we add a second (overloaded) constructor to `AzureEventSourceListener` that takes a simpler `Action<EventWrittenArgs>`. Callers that don't need the formatted message can use that constructor.

See this: https://github.com/pharring/azure-sdk-for-net/compare/dev/pharring/EventSourceEventFormattingPerf...pharring:azure-sdk-for-net:dev/pharring/AddAzureEventSourceListenerConstructorOverload?expand=1

**Comment by pharring** [comment]
Yes, you are missing something. In this PR, message formatting (likely a string allocation) still happens unconditionally inside `AzureEventSourceListener` in order to evaluate the arguments to call the `LogEvent` callback, passing the fully-evaluated `formattedMessage` to `LogEvent`. If the log level is set high/low enough that the event will be filtered, then the fully formatted message is never used -- meaning it was a wasted allocation.

**Comment by christothes** [comment]
Does the EventSource not avoid the eager formatting when it calls `IsEnabled` before calling `WriteEvent`?

**Comment by pharring** [comment]
> Does the EventSource not avoid the eager formatting when it calls IsEnabled before calling WriteEvent?

Yes, it does. However, this listener subscribes to events at "Verbose" level (meaning everything) and the `AzureEventSourceListener` uses calls `EnableEvents` without passing a keyword mask -- also meaning "all events".

**Pull request closed without merging**
