### PR TITLE
Enable Sub-Heading Verification

### PR DESCRIPTION
**Pull request by scbedd**
The real question is which readmes fail validation with this rule enabled.

### CODE REVIEW

**Review by czubair — APPROVED** [review]
The only note is that or Java, theri heading is "Include the package"

**Review by tg-msft — APPROVED** [review]
This looks great.  It couldn't find 0.6.0 yet so I kicked the CI again.

If a README has the right sections with slightly different names, it'd be great to change those names now.  Otherwise let's file bugs on each of the offending READMEs for @czubair to track.

**Comment by scbedd** [comment]
@tg-msft That's my plan. 

For those where it's a simple title update, I'll do so. Where those sections are entirely missing I will add exceptions for those and reach out to the owners so that they are aware they need to update

**Comment by scbedd** [comment]
@czubair I'll make certain to remember this for Java.

Also, this is taking me a bit longer because the examples are ending up present in the package as headers, which is breaking the hierarchy of the document. Need to come up with a workaround.

**Comment by scbedd** [comment]
@tg-msft we're actually super close.

Adding an exception for Azure.Core/readme. Not certain if we want to do anything different given it's presence as the `core`. 

```
sdk/core/Azure.Core/README.md is missing headers with patterns:
 * ^Getting started$ -> Install the [Pp]ackage
 * ^Getting started$ -> Prerequisites
 * ^Getting started$ -> Authenticate the [Cc]lient
```

These are Missing `Authenticate the Client`

```
/sdk/storage/Azure.Storage.Blobs/README.md
/sdk/storage/Azure.Storage.Blobs.Batch/README.md
/sdk/storage/Azure.Storage.Blobs.Cryptography/README.md
/sdk/storage/Azure.Storage.Common/README.md
/sdk/storage/Azure.Storage.Files.DataLake/README.md
/sdk/storage/Azure.Storage.Files.Shares/README.md
/sdk/storage/Azure.Storage.Queues/README.md
/sdk/synapse/Microsoft.Azure.Synapse/README.md
```

Give that most of the examples are using az cli to create these, you HAVE the auth creds :P 

We can add boilerplate or just remove it as a required section. I'm totally ok with fixing this one before merging though.

**Review by jsquire — APPROVED** [review]
LGTM

**Comment by annelo-msft** [comment]
May I ask you to remove FormRecognizer from the README exceptions list as well?  It should be compliant now.

**Review by annelo-msft — APPROVED** [review]

**Comment by tg-msft** [comment]
All of the Storage READMEs were written before this new `Authenticate the Client` requirement.  I think it's fine to exclude them as part of this PR.  I filed https://github.com/Azure/azure-sdk-for-net/issues/11492 to track.

**Review by JoshLove-msft — APPROVED** [review]

**Review by ShivangiReja — APPROVED** [review]

**Pull request merged**
