### PR TITLE
Convert ValueTask to a Task before blocking

### LINKED ISSUE #10904: Task extensions synchronously complete ValueTasks
In the Core project [TaskExtensions](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs), `GetAwaiter().GetResult()` is called on ValueTasks. According to this [article by Stephen Cleary](https://blog.stephencleary.com/2020/03/valuetask.html):

> However, this will not work for value tasks. You simply cannot block on value tasks. If you must block (again, this is never ideal), then you’ll need to convert the value task to a reference task by calling AsTask, and then block on that reference task.

So the extensions may work but are dependent on undefined behaviour. `AsTask()` should be called on the ValueTask first before consuming it synchronously.

### PR DESCRIPTION
**Pull request by pakrym**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/10904

### CODE REVIEW

**Comment by pakrym** [comment]
@AlexanderSher ping :)

**Comment by AlexanderSher** [comment]
`EnsureCompleted` shouldn't be called on non-completed `ValueTask` at all, that's what we check in `VerifyTaskCompleted`. We're using `EnsureCompleted` in the policies that may be executed in any TaskScheduler/SynContext combination and sync waiting on incomplete task can easily hang user code.

If debug-only exception isn't enough and throwing `InvalidOperationException` for release build isn't an option, we need to discuss it further. Is there any real repro behind #10904?

**Comment by pakrym** [comment]
I understand that we should never be calling EnsureCompleted() on non-completed tasks but if the case we accidentally do I'd like to make a best effort and keep customers apps working. Even if sync-over-async is suboptimal and might cause other issues in 90% of the cases it will work just fine.

**Comment by AlexanderSher** [comment]
Then we need additional check to ensure that we're trying to wait incomplete task synchronously only on threadpool, something like:
```cs
(SynchronizationContext.Current == null || SynchronizationContext.Current.GetType() == typeof(SynchronizationContext)) && TaskScheduler.Current == TaskScheduler.Default
```
I'd prefer to throw exception rather than introduce possible deadlock.

**Comment by pakrym** [comment]
Do you think it's required considering we are using `ConfigureAwait(false)` everywhere?

**Comment by AlexanderSher** [comment]
In a sync code path `ConfigureAwait(false)` doesn't change anything even if used. In async code path, user can add custom policy that interacts with UI (progress bar or abort/retry message) that may bring execution of the following policy into sync context or task scheduler.

**Comment by pakrym** [comment]
This situation would only happen when sync code accidentally runs an async code path.

I'm not saying there is no way to deadlock at all but considering we use `ConfigureAwait(false)` in all our async code the probability that one of our calls would need to be scheduled on sync context we also don't _often_ call back into customers code this solution would work in 90% on the unlikely cases we miss with analyzers.

**Comment by AlexanderSher** [comment]
> we also don't often call back into customers code 

I would say it is an expected scenario when user adds UI interaction as per retry policy. How else can I update UI to provide notification that request has failed and is going to retry?

**Comment by pakrym** [comment]
What are you proposing? Throwing an exception in the case where customers code would've had a high chance of working? There is also no workaround customer can do if we throw an exception, they can always workaround blocking sync-over async and get their code working.

**Comment by AlexanderSher** [comment]
Yes, I think user must be aware that we have a bug in our code that can potentially hang an application. If we throw an exception, user will know where the bug is and apply workaround. If we hang, it would be much harder to figure out why.

The workaround is simple: explicitly call failing API method using `Task.Run` so that sync context isn't captured.

**Comment by pakrym** [comment]
Hm, good point, let me try the changes.

**Pull request closed without merging**
