### PR TITLE
BlobClient.OpenWriteAsync()

### PR DESCRIPTION
**Pull request by jaschrep-msft**
SDK Changes

- `OpenWrite`/`Async` added to `BlobClient`, calls into `BlockBlobClient` `OpenWrite`/`Async`.
- `BlobClient.OpenWriteAsync()` will wrap a `BlockBlobWriteStream` in a `CryptoStream` to be written to when using client-side encryption.
  - While callers are already expected to call `Dispose()` properly on a write stream, they MUST call it here to finish writing the blob contents if they are using client-side encryption. `FlushAsync()` isn't enough. This is due to the nature of `CryptoStream` when in write mode.

Test Changes

- Open write tests in BlockBlobClientTests moved to abstract class `Azure.Storage.Common/test/Shared/OpenWriteTestBase.cs`.
- Added `abstract BlobBaseClientOpenWriteTests`, `BlockBlobClientOpenWriteTests`, `BlobClientOpenWriteTests`, and `ClientSideEncryptedBlobClientOpenWriteTests`. These implement the client-specific methods to run the tests and allow these three classes to run the same exact tests with different clients.
  - Client-side encryption gets its own child class because client-side encryption tests that touch the service can only be run live due to the nature of key generation. It's difficult to branch recordable vs live tags on single tests, so a child class with the [LiveOnly] attribute on the test class was made.
  - Original recordings worked for ported block blob tests, aside from a few that were just generating different names for blobs due to RNG usage.

NOT in this PR

- Porting other client's open write tests to use the centralized tests, like we have done with open read. #25621

Potential Confusion in PR

- New methods in `ClientSideEncryptor` and `BlobClientSideEncryptor`.
  - Chicken and egg problem to deal with.
  - Creating a writable `CryptoStream` requires an already-existing `StorageWriteStream` for it to forward transformed content to. But we need the crypto metadata we got while generating the `CryptoStream`'s encryption provider BEFORE we make the `StorageWriteStream`, as StorageWriteStreams need metadata on creation. The way `using` statements are needed makes this even harder.
  - Solution was to inject the `OpenWrite()` call into the `CryptoStream` generation, letting us call it in between provider and stream generation, when we have the necessary metadata.

### CODE REVIEW

**Comment by jaschrep-msft** [comment]
Resolves #18780

**Review by seanmcc-msft — APPROVED** [review]
Approved pending live tests.  Also, @amnguye can you take a look?

**Review by amnguye — APPROVED** [review]

**Pull request merged**
