### PR TITLE
CognitiveServices.Vision.Face: add FaceClient constructor with "endpoint" parameter

### PR DESCRIPTION
**Pull request by MaxHorstmann**
## Description
This adds another constructor to [Microsoft.Azure.CognitiveServices.Vision.Face.FaceClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.vision.face.faceclient?view=azure-dotnet#constructors), which accepts an `endpoint` parameter. 

Since the client can't work without an endpoint, it seems to me that this would be a sensible minor customization.

See for example [this](https://docs.microsoft.com/en-us/azure/cognitive-services/face/quickstarts/csharp-detect-sdk#create-and-use-the-face-client) code snippet in the quickstart, which could then be simplified to

```
FaceClient faceClient = new FaceClient(new ApiKeyServiceClientCredentials(subscriptionKey), faceEndpoint);
```

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ n/a ] Please add REST spec PR link to the SDK PR
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ n/a ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ n/a ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ n/a ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by dsgouda** [comment]
@deathly809 Could someone from the `Vision.Face` service take a look at this.

**Comment by deathly809** [comment]
@dsgouda Wrong person? ha ha

**Comment by dsgouda** [comment]
Whoops, yeah 😄

**Comment by dsgouda** [comment]
@lebronJ Could someone from the Vision.Face service take a look at this.

**Comment by MaxHorstmann** [comment]
> AFAIK, this SDK is auto-generated from Swagger, so I think this might not be the right place for this change.

My understanding is that the code in the [Generated](https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Vision/Face/Face/Generated) folder is auto-generated, and the [Customizations](https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Vision/Face/Face/Customizations) is for manual customizations on top of the generated code. Note that there already is [another such customization](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Vision/Face/Face/Customizations/ApiKeyServiceClientCredentials.cs). My proposal is to add another one.

**Comment by lebronJ** [comment]
> > AFAIK, this SDK is auto-generated from Swagger, so I think this might not be the right place for this change.
> 
> My understanding is that the code in the [Generated](https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Vision/Face/Face/Generated) folder is auto-generated, and the [Customizations](https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Vision/Face/Face/Customizations) folder is the place for manual customizations on top of the generated code. Note that there already is [another such customization](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Vision/Face/Face/Customizations/ApiKeyServiceClientCredentials.cs). My proposal is to add another one.

Thanks for your explanation and understood. But I still recommend to let @yangyuan be  Assignee/Reviewer since this is more like a platform-level change. (This can also be applied to other SDKs).

**Comment by lebronJ** [comment]
> This constructor is surely, better designed than the auto-generated constructors. But I don't like the idea of adding a hand-written constructor.
> 
> 1. Other Cognitive Services APIs. I had conversations with other teams before. I don't think I can push this change to other Cognitive Services APIs.
> 2. Other language SDKs. Most of the languages have the concept of `constructor` and have similar issue.
> 3. FYR... [Azure/autorest#2962](https://github.com/Azure/autorest/issues/2962)
> 
> @lebronJ so, as I explained, we don't have plans for adding this constructor for other Cognitive Services APIs.
> If Face SDK prefer to have it, I won't stand on the the way.

@MaxHorstmann Please refer to the GitHub issue above which is exactly same as your concern.
I totally agree with @yangyuan 's comments and would prefer to keep Face API's client SDK consistent with other Cognitive Service APIs. Hope this also makes sense to you.

**Comment by MaxHorstmann** [comment]
> @MaxHorstmann Please refer to the GitHub issue above which is exactly same as your concern.
> I totally agree with @yangyuan 's comments and would prefer to keep Face API's client SDK consistent with other Cognitive Service APIs. Hope this also makes sense to you.

👍 Makes perfect sense, a generic solution for mandatory constructor parameters is way more desirable here.

**Pull request closed without merging**
