### PR TITLE
Fix namespace of internal shared type

### PR DESCRIPTION
**Pull request by JoshLove-msft**

### CODE REVIEW

**Review by annelo-msft — COMMENTED** [review]
For context - is this needed because the namespace change was missed when moving these in from Experimental?

**Review by christothes — COMMENTED** [review]
I think we need to update all clients that reference this type also.

**Comment by JoshLove-msft** [comment]
> For context - is this needed because the namespace change was missed when moving these in from Experimental?

No, I just noticed that the namespace for this shared type was Azure.Monitor.Query which seemed wrong given that the type was used in other libraries like Tables.

**Comment by JoshLove-msft** [comment]
> I think we need to update all clients that reference this type also.

Yes, I think I updated them all. The latest CI failures were unrelated.

**Review by christothes — APPROVED** [review]

**Comment by JoshLove-msft** [comment]
> > No, I just noticed that the namespace for this shared type was Azure.Monitor.Query which seemed wrong given that the type was used in other libraries like Tables.
> 
> Have the types GA'ed? Is it a breaking change?

This is an internal shared type so it doesn't impact the API surface anywhere.

**Comment by annelo-msft** [comment]
> No, I just noticed that the namespace for this shared type was Azure.Monitor.Query which seemed wrong given that the type was used in other libraries like Tables.

Cool, thanks!

**Pull request merged**
