### PR TITLE
[FR] Add API version to new methods in 2.1-preview.x

### PR DESCRIPTION
**Pull request by maririos**
- Update methods docstrings to include information about the version.
- Add tests for new methods not supported in `v2.0`
- Update Readme with table on version support (like Python [here](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/formrecognizer/azure-ai-formrecognizer#install-the-package))
- Update changelog

Part of https://github.com/Azure/azure-sdk-for-net/issues/19132

### CODE REVIEW

**Review by kristapratico — APPROVED** [review]
For new parameters added in 2.1, would it make sense to also include the supported service version disclaimer? E.g. `modelName` on `StartTraining`?

**Comment by maririos** [comment]
>For new parameters added in 2.1, would it make sense to also include the supported service version disclaimer? E.g. modelName on StartTraining?

Yes! and also for new properties.
I want to do it in a separate PR just to keep things small. It is the last thing remaining for the multi-version effort.

**Review by kinelski — APPROVED** [review]
LGTM. Is it worth testing what happens when trying to use a custom model created with a different version? I slightly remember someone mentioning a service error related to that, but I'm not sure if it was a bug or the expected behavior.

**Comment by maririos** [comment]
>Is it worth testing what happens when trying to use a custom model created with a different version? I slightly remember someone mentioning a service error related to that, but I'm not sure if it was a bug or the expected behavior.

If a user trains a model with v2.0 and then tries to use that model against a recognition endpoint targeting v2.1 the service returns an error. It is expected behavior and the service has been improving the message to make it clear to users.
Not sure adding a test for that will bring value to the SDK as there is nothing we can do about it.

**Review by mssfang — APPROVED** [review]
LGTM!

**Pull request merged**
