### PR TITLE
Regenerate Managed Identity SDK from updated swagger

### PR DESCRIPTION
**Pull request by angosms**
* Regen .NET SDK
* Fix tests

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @angosms  , please
- Add a link to the swagger spec review PR in the description
- Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release
- Add  new tests for new operations
Thanks

**Comment by isra-fel** [comment]
Ping on this @angosms :)

**Comment by angosms** [comment]
Hey @isra-fel, we are still wainting on some feedback on a PR from Swagger team to finalize this.

In the meantime, I have a question about a GET operation that we added as an extension resource (ie. GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.WEB/SITES/PROVIDERS/**MICROSOFT.MANAGEDIDENTITY/IDENTITIES/**)

Is there guidance on how to test those? Since we'd need to create another resource from a different RP to test that we can get the identity.

**Comment by isra-fel** [comment]
Hi @angosms , your test project can depend on other module's SDK, just reference it in the csproj and you can use it in tests.

**Comment by angosms** [comment]
* Add a link to the swagger spec review PR in the description
https://github.com/Azure/azure-rest-api-specs/pull/8352/
* [Done] Include the .txt file generated when you run generate.ps1(details)
* [Done] Update release notes in csproj
* [Done] Update versions in csproj and assemblyinfo.cs if you are going to release
*  [N/A] Add new tests for new operations
Managed Identities only provides a GET on an extension resource "/{scope}/providers/Microsoft.ManagedIdentity/identities/default". We can not be expected to test all RPs onboarded to us. It is the responsibility of our partner RPs to test this. I believe Microsoft.Compute already tests for this.

**Review by isra-fel — APPROVED** [review]
Looks great

**Pull request merged**
