### PR TITLE
Send metadata header on IMDS probe request.

### PR DESCRIPTION
**Pull request by isaacbanner**
We have a customer service case indicating that the 400 on the probe request is creating noise in their monitoring. Adding the flag to the probe call so that it returns back a non-4xx response.

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

**Review by nonik0 — APPROVED** [review]

**Comment by isaacbanner** [comment]
@nonik0 is this good to merge?

**Comment by jsquire** [comment]
@nonik0:  Would you be so kind as to offer your insight on whether this is good to merge?

**Comment by nonik0** [comment]
Apologies for the delay, I was on leave all November. The new changes to add the header look good to me!

@jsquire In the future, you can also cc @anaismiller on future PRs, etc. for AppAuth.

**Comment by jsquire** [comment]
> @jsquire In the future, you can also cc @anaismiller on future PRs, etc. for AppAuth.

Thanks for the heads-up.   Will do!

**Pull request merged**
