### PR TITLE
Normalize Key Vault test timeouts

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Review by christothes — APPROVED** [review]

**Comment by heaths** [comment]
We're going to hold off on this for now.

**Comment by heaths** [comment]
At this point I can probably just re-enable them based on what other languages have experienced since re-enabling theirs. Never heard explicit confirmation that the underlying service perf issue was fixed, but seems it has been.

**Review by benbp — APPROVED** [review]

**Pull request merged**
