### PR TITLE
AppAuthentication: Add support for User Assigned Identity on Azure App Service / Functions

### PR DESCRIPTION
**Pull request by noelbundick**
## Description

This PR adds support for User Assigned Identity on Azure App Service / Functions. 

It flows the `clientid` parameter to the `MSI_ENDPOINT` request per [the docs](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity#using-the-rest-protocol) and enables applications to retrieve an access token for the specified user-assigned identity

> Note: `clientid` is not a typo, the parameter names differ between App Service & IMDS

The necessary unit tests are included - I've updated them to match the style of the existing System/User Assigned Identity tests for VMs.

A working sample Function that uses this code can be found at [noelbundick/azure-utilities](https://github.com/noelbundick/azure-utilities)

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] ~~Please add REST spec PR link to the SDK PR~~ N/A
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] ~~If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.~~ N/A
- [ ] ~~The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.~~ N/A
- [ ] ~~The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.~~ N/A

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@azuresdkci retest this please

**Comment by noelbundick** [comment]
@nonik0 @varunsh-msft I'm happy to have the feature in or whatever

But it sure looks like you've just copy/pasted my contribution, made some very minor changes, then committed it separately in 8bc1f817522f64ddd2e4461919a5e55b7bb2f538 without any attribution to me as the author (i.e. Git commit history & a merged PR) without so much as a comment/conversation here.

I'd like to raise a red flag about how this open-source repo is being run, because that's quite uncool. I spent a good chunk of time testing & validating this, and it feels like you're taking my effort and effectively passing off as your own. That sucks, and right now I'm not inclined to spend any of my time making any future contributions

**Comment by nonik0** [comment]
@noelbundick First, I would like to apologize to you directly--I am _very_ sorry! As you can see above, we were notified of your pull request just yesterday when myself and @varunsh-msft were tagged. Unfortunately, this was already after we had made our own changes and submitted our own pull request. The Azure SDK repo is fairly large and so our team doesn't directly monitor all the pull requests that come into this repo. If we had we seen your pull request earlier, we would have gladly accepted your changes (and saved ourselves the time!) because as you allude to--yours and our changes are very similar.

That being said, your changes were NOT stolen. The API call changes for adding the App Services support for user-assigned identities were fairly straightforward, and couple with the fact that you did a good job to adhere to the established code/test patterns, both changes came out very similar.

Once again, I am sorry for missing your _much_ earlier pull request. We will look into this notification gap with the SDK team and work to ensure this won't happen again in the future, as we definitely do not want to discourage you from any further future contributions.

**Comment by noelbundick** [comment]
@nonik0 thanks for the follow-up! We’re good! 

Like you said - hope we can improve the notification process. This PR had been the oldest open PR on the entire Azure SDK for... well, nearly since it was submitted. I’ve watched commits land and had more or less just stopped watching this one

Glad to see the functionality land - I think it will really help our devs build secure apps on App Service

I’ll go ahead and close out this PR since it’s now redundant

**Pull request closed without merging**
