### PR TITLE
Getting update management changes result from PR #3095

### PR DESCRIPTION
**Pull request by finiteattractor**
Updating generated code based of swagger PR:
https://github.com/Azure/azure-rest-api-specs/pull/3095

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please generate the code using generate.cmd or generate.ps1 similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/generate.ps1) and commit all the files modified

**Comment by finiteattractor** [comment]
@dsgouda thanks! will update...

**Review by dsgouda — CHANGES_REQUESTED** [review]
There are some additive changes made here, please bump the version to `3.0.3-preview` in the csproj

**Comment by dsgouda** [comment]
Looks good apart from the minor comment

**Comment by finiteattractor** [comment]
cool! will add this, thanks!!

**Comment by dsgouda** [comment]
@finiteattractor Perhaps I forgot to mention but, we need to update the AssemblyInfo.cs [here](https://github.com/finiteattractor/azure-sdk-for-net/blob/4323c71c2fb31d2bc739db9787df6336401b731a/src/SDKs/Automation/Management.Automation/Properties/AssemblyInfo.cs#L11) so that `AssemblyFileVersion` matches the updated nuget package version (`3.0.3`)

**Comment by finiteattractor** [comment]
Good catch Thanks! will update.

**Review by dsgouda — APPROVED** [review]

**Pull request merged**
