### PR TITLE
Adding Managed disks support for HDI SDK

### PR DESCRIPTION
**Pull request by epkalyanr**
## Description

The changes in this pull request are related to adding support for Managed disks for the SDK. The managed disks are used for kafka today and we need to provide new fields to the customers to enable them to use the managed disks. We have introduced a new List in the cluster create parameters which enables the customers to set the data disks properties. The SDK unit tests have been rerecorded since we have introduced a new data model for the datadisks.
The PR for the hyak spec update : https://github.com/Azure/hydra-specs-pr/pull/1383
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by epkalyanr** [comment]
@markcowl I have made changes as per your comments on the following PR 
https://github.com/Azure/azure-sdk-for-net/pull/3044

**Comment by epkalyanr** [comment]
@shefaliv @nemanja88

**Review by shefaliv — APPROVED** [review]

**Comment by shefaliv** [comment]
The swagger work is already in progress, but the timelines are still being worked out by Ganeshan/Matthew. Matthew is currently OOF but let's keep that thread open. These changes need to ship though so let's not block these on that please!

Thanks!

**Comment by markcowl** [comment]
@epkalyanr See offlien conversation on AutoRest conversion

**Pull request merged**
