### PR TITLE
Add new public key for client libraries

### LINKED ISSUE #5985: Create new fully signed strong name key for track 2 client libraries
For our new track 2 client libraries we want to use a new strong name key so that is a full key so that anyone can build and sign our libraries. We no longer use strong names for security and thus they are only for identity so we should eliminate some of the hoops needed for building and using our libraries.

### PR DESCRIPTION
**Pull request by weshaggard**
For our new client libraries we want to use a full public/private
key for our libraries as we no longer use strong name identity
for security reasons and we want to make building our libraries
easier for anyone. The strong name public key is only for identity
purposes now.

The public key for AzureSDKClient is: 92742159e12e44c8

fixes https://github.com/Azure/azure-sdk-for-net/issues/5985.

cc @AlexGhiondea @KrzysztofCwalina

@KrzysztofCwalina can you add this key to the .NET guidelines?

### CODE REVIEW

**Comment by weshaggard** [comment]
cc @chidozieononiwu

**Comment by weshaggard** [comment]
@AlexGhiondea @KrzysztofCwalina  I'm merging this to get the change in before we ship another preview but please let me know if there are concerns and I will address them later.

**Comment by KrzysztofCwalina** [comment]
> @KrzysztofCwalina can you add this key to the .NET guidelines?

Is this something that we want individual developers to do, or it will happen automatically? I want .net guidelines to be only the things we want developers to do.

**Comment by weshaggard** [comment]
As long as developers follow the correct convention then it will just happen automatically but I do think it may still be worth calling it out even if it is just for reference.

**Pull request merged**
