### PR TITLE
Dev/hydra changes

### PR DESCRIPTION
**Pull request by priydes**
Azure SDK changes for IaaS Classic to ARM migration.
Updated code for Compute and Network.
This changes also updates the api-version t0 2016-03-01
Corresponding changes in recorded sessions.
Added tests for Compute and Network.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@priydes__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (priydes). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hyonholee** [comment]
Please update Compute and Network version numbers.

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Pull request merged**
