### PR TITLE
Nithin/sdkupdates 2019 06 version

### PR DESCRIPTION
**Pull request by nithinpnp**
changes - 
 We have added optional fields for WebhookReceiver model in Swagger Spec. Updating the SDK to reflect the same.  
incremented the version number .

### CODE REVIEW

**Comment by erich-wang** [comment]
@nithinpnp, could you share the swagger specs PR link related to this change?

**Review by erich-wang — CHANGES_REQUESTED** [review]
@nithinpnp , please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#signing-and-publishing-nuget-packges) to:
- Update AssemblyVersion and AssemblyFileVersion in AssemblyInfo.cs if needed
- Update AzureApiTag in AzSDk.RP.props

**Comment by nithinpnp** [comment]
@erich-wang . The instructions to follow link is broken , Could you please get the latest link ?

**Comment by erich-wang** [comment]
@nithinpnp , it is private repo and you should log in first. BTW, you should have joined Azure organization in github already, right? If not, please checkout https://repos.opensource.microsoft.com/.

**Comment by nithinpnp** [comment]
@erich-wang  https://github.com/Azure/azure-rest-api-specs/pull/6218 
this is the pull request for swagger spec that got approved.

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
