### PR TITLE
[StorSimple] Merging the changes from the private repo done in build release to public repo

### PR DESCRIPTION
**Pull request by parvezah**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@parvezah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (parvezah). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@parvezah Still merge conflicts - see yugang's email for details.

**Comment by yugangw-msft** [comment]
could you address the invalid xml element tag? You can open up the CI console log and tsee the list. 
Customization\Helpers\LegacyApplianceConfigParser.cs(139,26): warning CS1572: XML comment on 'Microsoft.WindowsAzure.Management.StorSimple.LegacyApplianceConfigParser.LegacyApplianceConfigParser(Microsoft.WindowsAzure.Management.StorSimple.IServiceSecretEncryptor)' has a param tag for 'client', but there is no parameter by that name [D:\workspace\sdk-for-net\src\ServiceManagement\StorSimple\StorSimple\StorSimple.csproj]

**Comment by yugangw-msft** [comment]
there is one more in the console log:

Tests\DeviceJobTests.cs(161,26): warning CS1572: XML comment on 'StorSimple.Tests.Tests.DeviceJobTests.CreateSupportingVolumeAndBackupPolicy(Microsoft.WindowsAzure.Management.StorSimple.Models.DeviceInfo)' has a param tag for 'details', but there is no parameter by that name [D:\workspace\sdk-for-net\src\ServiceManagement\StorSimple\StorSimple.Tests\StorSimple.Tests.csproj]

**Pull request merged**
