### PR TITLE
AutoPr-Batch-jafreck-REST Spec PrNumber 5720

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by jafreck** [comment]
@sarangan12 can you review?

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@jafreck Will open a manual PR for this

**Comment by jafreck** [comment]
@dsgouda can you reopen this PR if CI has recovered?

**Comment by dsgouda** [comment]
Jenkins passed in previous run, will override.

**Pull request merged**
