### PR TITLE
{AzureStorage} fix the typo for the source blob size

### LINKED ISSUE #35139: Is threshold for operation 256 MB or 256MiB
Document says 256MB. However, it could be a bit consusing is it actually 256 MB (256*1000*1000) or 256 MiB (256*1024*1024)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3675f97-eaf6-3c6e-5533-bf935de7910e
* Version Independent ID: 72c75a5f-ad7f-637f-df96-276b5af503a9
* Content: [BlobBaseClient.SyncCopyFromUriAsync Method (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.synccopyfromuriasync?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by navba-MSFT**
fixes Azure/azure-sdk-for-net#35139

This PR has fix for the typo for the source blob size.

The Maximum blob size for the source blob is 256 mebibytes (MiB) and not 256 MB. Refer: https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.synccopyfromuriasync?view=azure-dotnet

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by amnguye** [comment]
There's no changes needed. The existing documentation is correct.

Our REST docs say 
"The size of the source blob can be up to a maximum length of 256 mebibytes (MiB)."
image
https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url?tabs=azure-ad

Please follow up with the customer and correct their understanding of the API. Thanks.

**Review by amnguye — CHANGES_REQUESTED** [review]
No changes needed. Current documentation is correct.

**Comment by amnguye** [comment]
Ah I see your point, I got them backwards.

**Review by amnguye — APPROVED** [review]

**Comment by navba-MSFT** [comment]
> We should be good to merge. The pipeline failures are unrelated to your changes. Let me rerun them again just to see if they will run green, or else we can just override it

@amnguye Since all the checks are passed, could you please merge it once you get a chance ?

**Pull request merged**
