### PR TITLE
SDK add Quota command and models. Add Tests for Quota

### PR DESCRIPTION
**Pull request by rahuls-microsoft**
1. SDK pickup Quota files for  models and commands from - https://github.com/AzureSDKAutomation/azure-sdk-for-net/commits/sdkAutomation/Microsoft.Azure.Management.Reservations - Auto generated by SDK Team.
2. Add Tests for Quota.

### CODE REVIEW

**Comment by rahuls-microsoft** [comment]
We are in public preview. Please expedite the SDK release.

 As we need  to the SDK public link at - https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/quotaapi

**Comment by rahuls-microsoft** [comment]
@erich-wang - Please review it. We need to release the SDK to public site, as the RP is in Public Preview.
Thanks.

**Comment by rahuls-microsoft** [comment]
@erich-wang _ Please review the PR. We need to publish the SDK to public site as the RP is in Public Preview.

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @rahuls-microsoft , the SDK should be generated by running `generate.ps1` as our guideline says, and it will also update https://github.com/Azure/azure-sdk-for-net/blob/master/eng/mgmt/mgmtmetadata/reservations_resource-manager.txt . Be sure to check that in.
Thanks

**Review by isra-fel — APPROVED** [review]
LGTM

**Review by erich-wang — APPROVED** [review]

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
