### PR TITLE
[DocumentIntelligence] Enabling live testing

### PR DESCRIPTION
**Pull request by kinelski**
This PR enables live testing for the Document Intelligence SDK.

It fixes two issues that were preventing the pipeline from working:
- It changes the test resource region to `eastus` to support the latest preview REST API version.
- It overrides the `IsEnvironmentReadyAsync` method in the Test Framework to ensure that the recently created test resource is ready before starting tests. Without this step we'd get frequent 401 errors.

### CODE REVIEW

**Comment by kinelski** [comment]
Azure Pipelines successfully started running 1 pipeline(s).

**Review by joseharriaga — APPROVED** [review]

**Pull request merged**
