### PR TITLE
Update example to use AzureCredentials instead of CredFile

### PR DESCRIPTION
**Pull request by awesley**
According to https://github.com/Azure/azure-sdk-for-net/blob/4c6f0794b9a27a386fc43ddd5396dcf327b9f340/AUTH.md

Using a credential file is not necessary the best practice for authenticating against Azure.  Programmatic keys are a good choice for any "API first" documentation, so this update makes that change.  

It also includes a comment with the entire namespace of the `AzureCredentialsFactory` type because it exists in multiple namespaces.  They may all be valid, but this one works and a comment may lower the barrier of entry if someone were to hit that problem.

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@azuresdkci add to whitelist

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@azuresdkci add to white list

**Comment by shahabhijeet** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by Nepomuceno** [comment]
I like pretty much using the credential file, makes the things a lot easier.

**Comment by hovsepm** [comment]
Converted to a github issue.

**Pull request closed without merging**
