### PR TITLE
track2 .NET SDK generation for dataprotection for 2023-12

### PR DESCRIPTION
**Pull request by abhinitkumar01**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by jsquire — CHANGES_REQUESTED** [review]
@abhinitkumar01:

Your account lacks the required public GitHub organizations and permissions required of an internal contributor.  Please review the Azure SDK onboarding documentation and use the associated Teams channel for support.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

You can verify the state of your account by running the [Validate-AzsdkCodeOwner](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/scripts/Validate-AzsdkCodeOwner.ps1) script from the Azure SDK tools repository.

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

**Comment by abhinitkumar01** [comment]
@archerzz , can you please review this.

**Review by archerzz — APPROVED** [review]
If you are going to release a new version, don't forget to update `CHANGELOG.md`. See [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=signing-and-publishing-nuget-packges) for details.

**Comment by jsquire** [comment]
Account issues have been resolved.   Still requires CODEOWNERS updates to move forward.

**Comment by archerzz** [comment]
@abhinitkumar01 Please take a look at my comment. Thanks.

**Comment by abhinitkumar01** [comment]
@archerzz I have updated the changelog file for requesting a new release.

**Comment by abhinitkumar01** [comment]
> Account issues have been resolved. Still requires CODEOWNERS updates to move forward.

@jsquire 
Regarding CODEOWNERS, I will not be necessarily maintaining it going forward, as other folks would be updating it as and when new features are pushed. Can you please help me with that part.

**Comment by jsquire** [comment]
> > Account issues have been resolved. Still requires CODEOWNERS updates to move forward.
> 
> @jsquire Regarding CODEOWNERS, I will not be necessarily maintaining it going forward, as other folks would be updating it as and when new features are pushed. Can you please help me with that part.

Which team owns this package?   If that is not the Azure SDK team, then we'll need to add a set of owners responsible for support when customer issues are opened.   If that is not you, directly, please work with your team to find the right contacts or to create a GitHub team to be added, which your team can update when owners change.

**Comment by hiaga** [comment]
@jsquire this library is owned by Azure BCDR team, specifically we own the swagger changes and create PRs to update the .NET SDK taking help from .NET SDK team. However, Azure .NET SDK team takes care of all the polishing or major issues which are SDK specific. Please suggest further

**Comment by hiaga** [comment]
if we need to add CODEOWNERS please add me (@hiaga ) and abhinit (@abhinitkumar01 ) for now as a github team. We'll add relevent folks as and when needed

**Pull request closed without merging**
