### PR TITLE
AutoPr-NetApp-leonardbf-REST Spec PrNumber 6086

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by erich-wang** [comment]
@leonardbf , if you still need to merge this PR, please:

This doesn't match the new repo structure. Please see https://github.com/Azure/azure-sdk-for-net/issues/5213 for the guidelines or follow the structure of one of the azurestack libraries which was recently moved into this new structure https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/azurestack/Microsoft.AzureStack.Management.AzureBridge.Admin

The overall process could be find at [here](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md), especially the [steps](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-directory-structure-and-sdk-generation) for new service

**Review by erich-wang — CHANGES_REQUESTED** [review]
please update as I comments

**Comment by leonardbf** [comment]
@erich-wang I do not need this pull request. It seems to have been auto-generated from an older swagger commit.

**Comment by erich-wang** [comment]
Close this PR per comment from partner.

**Pull request closed without merging**
