### PR TITLE
Speeding up load balancer and app gateway live tests 

### PR DESCRIPTION
**Pull request by martinsawicki**
with resourceGroup.beginDeleting rather than the synch delete

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@martinsawicki please do another commit to kick off the cI job.

**Comment by martinsawicki** [comment]
done

**Comment by martinsawicki** [comment]
@hovsepm I've done two extra commits already but it appears to keep getting hung this time

**Comment by martinsawicki** [comment]
ok, now it looks like it finally passed

**Comment by hovsepm** [comment]
reviewing...

**Pull request merged**
