### PR TITLE
ADF - runtime SDK breaking changes

### PR DESCRIPTION
**Pull request by alextolp**
We will bump up the version today with another pull request

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alextolp__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by yugangw-msft** [comment]
add to whitelist

**Comment by markcowl** [comment]
@alextolp Please add the version update to nuget.proj

**Comment by alextolp** [comment]
Bgold09 will make the version update today.

-Alex

On Jul 31, 2015, at 2:11 PM, Mark Cowlishaw <notifications@github.com<mailto:notifications@github.com>> wrote:


@alextolp<https://github.com/alextolp> Please add the version update to nuget.proj

-

**Comment by bgold09** [comment]
I'll be sending a PR containing additional breaking changes which will bump the nuget version. Please merge this change first.

**Pull request merged**
