### PR TITLE
Properly identify response trace messages

### LINKED ISSUE #10825: Azure.Core pipeline tracing is misleading and inconsistent
While diagnosing a different issue, I found trace messages to be misleading and inconsistent.

1. Responses are logged like: `Request [requestId] content: <content>`. At least at a glance, that looks like request content. Maybe something like `Response [requestId] content: <content>`. The "requestId" will still be consistent across requests/responses so you can pair them up.
2. There are various different instances of "... content: " vs. "... Content " (no colon). It should be consistent, and I recommend the colon as a clear delimiter.

### PR DESCRIPTION
**Pull request by heaths**
Also decodes application/x-www-form-urlencoded content. Fixes #10825

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Comment by heaths** [comment]
@jsquire some Event Hub tests are failing - 3/4 of which are because of an enumeration (collection) being modified, but only only for net461. Could you check on these issues?

**Comment by jsquire** [comment]
@heaths:  Looking through the CI failures, I think that I found the set that you were referring to; investigating.

**Comment by jsquire** [comment]
Apologies for the inconvenience.

I've got a PR out to ignore these in the short term while I take a deeper look.  I'll take ownership of opening an issue to track if I don't get a fix PR out later this morning.

**Comment by heaths** [comment]
Fortunately - though oddly - rerunning them passed. One seemed environmental, but the other three I would think should fail consistently.

**Comment by jsquire** [comment]
The root for all is a race condition in the processor test.   I'm still working to get the right hooks for setting a completion source for background processing in some of these, so results are non-deterministic and tend to work locally and then get angry in CI.  In this case, something ran that used a diagnostic source after the test completed, which upset the diagnostic tests that have to run isolated.

**Pull request merged**
