### PR TITLE
Update Azure Maps SDK code owners

### PR DESCRIPTION
**Pull request by dubiety**
Update Azure Maps SDK code owners

### CODE REVIEW

**Review by jsquire — CHANGES_REQUESTED** [review]
@dubiety:

The account `jecmenicanikola` lacks the required public GitHub organizations and permissions required of an internal contributor.  They cannot be used in CODEOWNERS until that is corrected.

Please review the Azure SDK onboarding documentation and use the associated Teams channel for support.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

You can verify the state of their account by running the [Validate-AzsdkCodeOwner](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/scripts/Validate-AzsdkCodeOwner.ps1) script from the Azure SDK tools repository.

**Review by jsquire — APPROVED** [review]
Account issues confirmed resolved.

**Comment by dubiety** [comment]
Thank you very much!

**Pull request merged**
