### PR TITLE
[Event Hubs Client] Track One: Diagnostic Test Fixes

### PR DESCRIPTION
**Pull request by jsquire**
# Summary

The intent of these changes is to fix the assertions for failing live tests after the names for activities were shortened.

# Last Upstream Rebase

Thursday, August 8, 2019  8:34am (EDT)

# Related and Follow-Up Issues

- [Shorten diagnostics event names](https://github.com/Azure/azure-sdk-for-net/issues/7186) (#7186)

### CODE REVIEW

**Comment by jsquire** [comment]
@serkantkaraca:  We both overlooked this yesterday.   If you wouldn't mind giving this a quick pass, I'd appreciate it.

**Review by tg-msft — APPROVED** [review]

**Comment by pakrym** [comment]
> names activities were shortened

Why?

**Comment by jsquire** [comment]
> > names activities were shortened
> 
> Why?

Please note this is the track one client library.   I'll leave it to @serkantkaraca to offer any context beyond that which he offered in his PR yesterday.   _(see: related issues in the summary)_

**Comment by jsquire** [comment]
Since it looks as if there are some points of discussion that were introduced on the referenced PR, I'm going to merge this to fix nightly failures and let @serkantkaraca cover any changes in the scope of adjustments that he chooses to make with the corresponding activity names.

**Pull request merged**
