### PR TITLE
Make DedicatedHostGroup.properties.supportAutomaticPlacement default to false

### PR DESCRIPTION
**Pull request by dochung4**
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/11697

Dedicated host group automatic placement feature is currently in a limited public preview, available in a few regions for whitelisted subscriptions. It is planned to be GA'ed in some public regions in December. The initial plan was to default DedicatedHostGroup.properties.supportAutomaticPlacement to true, but recently we have agreed to default the value to false as we GA. Changing the default to false has already been made on the service side.

This PR updates only the description to the "supportAutomaticPlacement" property.

### CODE REVIEW

**Comment by YalinLi0312** [comment]
@dochung4 Could you fix the failed CI tests?

**Comment by dochung4** [comment]
> @dochung4 Could you fix the failed CI tests?

@YalinLi0312 , can you please share the log for the failure? I am not able to find it.

**Comment by dochung4** [comment]
> > @dochung4 Could you fix the failed CI tests?
> 
> @YalinLi0312 , can you please share the log for the failure? I am not able to find it.

@YalinLi0312 , is there any update?

**Comment by YalinLi0312** [comment]
@dochung4 Please:
* Update release notes in `src/Microsoft.Azure.Management.Compute.csproj`
* Update the API tags in `Az.Sdk.props` if there's an API-version update

**Comment by dochung4** [comment]
> @dochung4 Please:
> 
> * Update release notes in `src/Microsoft.Azure.Management.Compute.csproj`
> * Update the API tags in `Az.Sdk.props` if there's an API-version update
> * Make sure have proper test coverage

- Updated Microsoft.Azure.Management.Compute.csproj
- There is no API-version update
- The existing test TestNonZonalDedicatedHostGroupInstanceViewAndAutomaticPlacement() already tests the property.

**Review by YalinLi0312 — APPROVED** [review]

**Pull request merged**
