### PR TITLE
[AzureMonitorExporter] new SLN for both Exporter and Distro

### PR DESCRIPTION
**Pull request by TimothyMothra**
## Goal
Currently, our dev team is switching between two solutions, Exporter and Distro.
I want to streamline our dev workflow by replacing the current Exporter and Distro solution (sln) files with a single solution for both projects in the root monitor directory.
This is the same approach that KeyVault uses ([link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/keyvault)).

## Changes
- add `Azure.Monitor.OpenTelemetry.sln` in the `monitor` directory.
  image
  image

### CODE REVIEW

**Comment by rajkumar-rangaraj** [comment]
We only own 2 components in monitor folder. Do you think it makes sense to place the solution in the monitor folder? Won't it confuse other project owners of monitor?

We might need an approval from Azure SDK team to merge this change.

**Comment by TimothyMothra** [comment]
@rajkumar-rangaraj 

Got feedback from Jesse. 
> there's no particular restriction.   So long as it's named something that is obvious to those working on the Monitor libraries, it should be just fine.

**Comment by rajkumar-rangaraj** [comment]
Should we keep `Azure.Monitor.OpenTelemetry.AspNetCore` and `Azure.Monitor.OpenTelemetry.Exporter` with a new proposed solution?

**Comment by TimothyMothra** [comment]
> Should we keep `Azure.Monitor.OpenTelemetry.AspNetCore` and `Azure.Monitor.OpenTelemetry.Exporter` with a new proposed solution?

No strong opinion, but i think we can save ourselves extra maintenance by having only 1 sln instead of 3.

**Review by rajkumar-rangaraj — APPROVED** [review]

**Pull request merged**
