### PR TITLE
Remove deprecated Application Insights SDK

### PR DESCRIPTION
**Pull request by heaths**
Relates to #37660

### CODE REVIEW

**Comment by vishweshbankwar** [comment]
@heaths Is this related to the build errors on this https://github.com/Azure/azure-sdk-for-net/pull/37657

**Comment by heaths** [comment]
> @heaths Is this related to the build errors on this #37657

No. We're removing sources for deprecated packages. See #37660 I linked in the description for more information. Keeping source for deprecated (unsupported) packages has undue costs. It's not like we can never bring it back if we need to: it's still in git - just won't be in `HEAD`.

**Comment by heaths** [comment]
No longer any builds to trigger

**Review by jsquire — APPROVED** [review]

**Pull request merged**
