### PR TITLE
Audit devops sdk

### PR DESCRIPTION
**Pull request by OlegSternbergIBM**
Added ServerDevOpsAuditSettings SDK to support DevOps server auditing policy storing and retrieval

Link to swagger PR:
https://github.com/Azure/azure-rest-api-specs/pull/11836

### CODE REVIEW

**Comment by m-nash** [comment]
@Oleza1972 can you add the spec PR link that this change is associated with?

**Comment by allenjzhang** [comment]
The version jump from 1.47 to 1.49. [Nuget](https://www.nuget.org/packages/Microsoft.Azure.Management.Sql) shows latest is 1.47 so should have bumped to 1.48.

**Comment by Oleza1972** [comment]
> @Oleza1972 can you add the spec PR link that this change is associated with?

https://github.com/Azure/azure-rest-api-specs/pull/11836

**Comment by Oleza1972** [comment]
> The version jump from 1.47 to 1.49. [Nuget](https://www.nuget.org/packages/Microsoft.Azure.Management.Sql) shows latest is 1.47 so should have bumped to 1.48.

Done

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
