### PR TITLE
Update Azure Resource Management Core Readme File

### PR DESCRIPTION
**Pull request by v-yilinhu**
Fix issue https://github.com/Azure/azure-sdk-for-net/issues/24922

@scottaddie, @AlexGhiondea, @archerzz for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@scottaddie, @AlexGhiondea, @archerzz  Please help review this PR.

**Review by scottaddie — APPROVED** [review]

**Comment by v-xuto** [comment]
@scottaddie Please help us merge this PR. Thanks.

**Review by archerzz — APPROVED** [review]
LGTM
Thanks.

**Comment by v-xuto** [comment]
@archerzz  Do you have permission to merge this PR? If so, please help me merge.

**Pull request merged**
