### PR TITLE
ServiceBus: Fix for space in property names

### PR DESCRIPTION
**Pull request by sazeesha**
Reference : https://github.com/Azure/azure-rest-api-specs/pull/879

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by cormacpayne — CHANGES_REQUESTED** [review]
@sazeesha Hey Zeeshan, a few additional things that need to be included in this PR:

1) You need to update the [generate.cmd](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/ServiceBus/Microsoft.Azure.Management.ServiceBus/generated.cmd) file with the version of AutoRest that you use to generate this code, as well as update the Swagger spec you used

2) You need to update the [project.json](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/ServiceBus/Microsoft.Azure.Management.ServiceBus/project.json#L2) and [AssemblyInfo.cs](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/ServiceBus/Microsoft.Azure.Management.ServiceBus/Properties/AssemblyInfo.cs#L23) files with the version you are bumping ServiceBus to for publishing (0.0.2-preview)

**Comment by cormacpayne** [comment]
@azuresdkci test this please

**Comment by sazeesha** [comment]
@cormacpayne I have made the changes you  requested. Can you please merge it?

**Comment by cormacpayne** [comment]
@sazeesha you need to update `AssemblyInfo.cs` before this can be merged

**Comment by sazeesha** [comment]
@cormacpayne : based on our chat discussion we decided to not update the AssemblyInfo.cs as it being 1.0.2 was a mistaken when it was initially checked in

**Review by cormacpayne — APPROVED** [review]

**Comment by cormacpayne** [comment]
LGTM

**Pull request merged**
