### PR TITLE
Bump to PublicApiApprover 9.1

### PR DESCRIPTION
**Pull request by danielmarbach**
Related to Azure Service Bus

I released today the [new major version](https://github.com/JakeGinnivan/ApiApprover/releases/tag/9.0.0) of PublicApiApprover. It uses now stable ordering that should be platform independent

### CODE REVIEW

**Comment by danielmarbach** [comment]
The build server proofs that the linux version is now also stable

**Comment by danielmarbach** [comment]
Isn't this pretty much a no brainer to review? :)

**Review by SeanFeldman — APPROVED** [review]
Here's your no brainer 😛

**Comment by danielmarbach** [comment]
Bumped to 9.1 and rebased

**Review by nemakam — APPROVED** [review]

**Pull request merged**
