### PR TITLE
Fixed namespace issue in Configuration project Resources Desinger File. Added unit tests.

### PR DESCRIPTION
**Pull request by MichaelCommo**
Fixed issue with namespacing string in the Resources Designer file. Added unit tests that exercise the resources file to ensure this bug doesn't regress.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MichaelCommo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by MichaelCommo** [comment]
@hovsepm: I fixed a namespacing issue in the resources designer file. Bug predates my last pull-request. I have a new pull request that resolves this issue, as well as new unit tests added to ensure this doesn't happen again.

Error can be found in this issue: https://github.com/Azure/azure-sdk-for-net/issues/2454

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@MichaelCommo you will have to update package version in assemblyinfo.cs and nuget.proj files otherwise we will not be able to publish a nuget package.

**Comment by MichaelCommo** [comment]
@hovsepm: thanks for the reminder on bumping the package version. Should be all set.

**Comment by MichaelCommo** [comment]
@hovsepm: thanks, much appreciated! I'll await the next publish.

**Comment by hovsepm** [comment]
@MichaelCommo I've unlisted version 3.2.2 from nuget.org and published 3.2.3. Please take a look and let me know if everything works now.

**Comment by MichaelCommo** [comment]
Setting up a test now. I'll let you know shortly. Though, according to the new unit tests I added in this change set, this should resolve the issue.

**Comment by MichaelCommo** [comment]
Update: v3.2.3 resolves the issue. Thanks

**Pull request merged**
