### PR TITLE
add a function to convert primitive type to RequestContent

### PR DESCRIPTION
**Pull request by chunyu3**
# Contributing to the Azure SDK

- Add a function in RequestContentHelper to convert primitive type to RequestContent

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by ArcturusZhang — APPROVED** [review]

**Review by archerzz — COMMENTED** [review]
Can we have some test in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/tests/RequestContentHelperTests.cs

**Review by annelo-msft — COMMENTED** [review]
I agree with @archerzz's comment about adding a test.  It would also be helpful to update the PR description with an explanation of why this method is needed and how it will be used.  Will it work for all `object` types?  What happens if I pass, for example, a `MemoryStream` to it?  We should make sure that it does the right thing for expected types and throws an exception with a helpful message for cases that aren't expected.

**Comment by chunyu3** [comment]
> I agree with @archerzz's comment about adding a test. It would also be helpful to update the PR description with an explanation of why this method is needed and how it will be used. Will it work for all `object` types? What happens if I pass, for example, a `MemoryStream` to it? We should make sure that it does the right thing for expected types and throws an exception with a helpful message for cases that aren't expected.

Thanks @annelo-msft . Current `RequestContent.Create` will convert string to RequestContent without quote.
e.g. If the content of the string is "foo", RequestContent.Create will return foo (without quotes).
When an operation use a string as body parameter, it will be serialized incorrectly. So we need a method to convert string to RequestContent which contains quotes.
There are three options:

1. update the RequestContent.Create(string content) to contain quotes
2. write a specific method for string in RequestContentHelper (e.g. RequestContentHelper.FromString)
3. write a method for all framework type (such as string, bool, long and so on) in RequestContentHelper

For #1, RequestContent in Azure.Core library, and return string without quotes may be the expected behavior. So I think it is better not to update this.
For #2, #3, in order to provide a consistent behavior when we convert framework type body in SDK, I prefer to #3. Otherwise, in SDK, it will call `RequestContentHelper.FromString` for string type body, and  `RequestContent.Create` for others. It is not consistent.

So I add this method `RequestContentHelper.FromObject` for all framework types.

I added tests for string, and bool now.

**Comment by chunyu3** [comment]
hello @annelo-msft I have added the tests. I will merge this PR first, if there any further comment, I will resolve in another PR. thanks.

**Pull request merged**
