### PR TITLE
Search SDK: Upgrading to the latest version of AutoRest

### PR DESCRIPTION
**Pull request by bitsforthought**
Changes:
- The latest version of AutoRest now has support for better version numbers in the `UserAgent` header, so the equivalent logic in the Search SDK has been deprecated.
- The summary comment on parameter groups is now more generic, so we don't need to hand-edit `SearchRequestOptions.cs` anymore.
- AutoRest now automatically adds "Gets or sets" to C# properties, which changed some of the generated code.

@chaosrealm @seansaleh FYI

### CODE REVIEW

**Comment by chaosrealm** [comment]
LGTM

**Comment by markcowl** [comment]
@brjohnstmsft Need an update to the package / assembly version.

**Comment by brjohnstmsft** [comment]
This is a preview version that hasn't shipped yet; No version update needed.

**Comment by markcowl** [comment]
@brjohnstmsft You can now create your own branches in the repo.  The policy now is to leave master / AutoRest for code that we want to ship, and if you need to collaborate on soem work, do that in a separate branch.  If no collaboration is necessary, this can remain in your fork.

**Comment by brjohnstmsft** [comment]
@markcowl Noted for future reference. However, that ship has sailed as far as this version of the Search SDK goes. We are maybe a few weeks from shipping what's currently in the AutoRest branch (2.x-preview). While we can create a new branch for those few weeks, I don't see the point since the Search SDK in the AutoRest branch is already in a "non-shippable state" (to clarify, tests are passing and we certainly *could* ship it, but it does not yet offer new features beyond the last 1.x version that shipped, so there would be no point).

**Pull request merged**
