### PR TITLE
Fixing scenario id, adding support for case manipulation on target

### PR DESCRIPTION
**Pull request by vchske**

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @vchske , please put a link of the swagger spec PR, thanks.

**Comment by vchske** [comment]
@isra-fel The swagger PR this is based on is https://github.com/Azure/azure-rest-api-specs/pull/6885

**Comment by vchske** [comment]
The top two checks (ci Build and ci Test MacOS) have been running for 24 hours. That doesn't seem right. Can someone take a look at this?

**Comment by vchske** [comment]
To be clearer, the two tasks (build and test macos) looks like they finished yesterday but their status is stuck.

**Review by isra-fel — APPROVED** [review]

**Comment by isra-fel** [comment]
Yeah, they actually have passed.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=87998&view=results

**Pull request merged**
