### PR TITLE
Feature: Support for Custom Endpoint in OpenAIClient

### PR DESCRIPTION
**Pull request by sangyuxiaowu**
This PR addresses the issue [#4152](https://github.com/microsoft/semantic-kernel/issues/4152) and [#39284](https://github.com/Azure/azure-sdk-for-net/issues/39284), which request the ability to connect to custom endpoints that expose an OpenAI compatible API using the `OpenAIClient` class. 

Changes:
- A public method `SetIsConfiguredForAzureOpenAI` was added to the `OpenAIClient` class. This method allows setting the value of the private field `_isConfiguredForAzureOpenAI`, enabling the client to connect to any endpoint.

This change will make it possible for the Semantic Kernel to interact with hosted Open Source models with technologies like vLLM, llama.cpp, etc., and allow applications to specify the Endpoint, useful in cases where applications cannot directly access OpenAI’s official endpoints and need to use an intermediary server for filtering.

Please review and let me know if any changes are required.

### CODE REVIEW

**Review by allerion-systems — APPROVED** [review]
--- redacted ---

**Comment by sangyuxiaowu** [comment]
> @microsoft-github-policy-service agree

**Comment by sangyuxiaowu** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Review by allerion-systems — APPROVED** [review]

**Comment by koteus** [comment]
@sangyuxiaowu It looks like the code is refactored the and there is no more `_isConfiguredForAzureOpenAI`. For details see my comment on another related PR

https://github.com/Azure/azure-sdk-for-net/pull/44179#issuecomment-2159340267

I hope it helps ;)

**Pull request closed without merging**
