### PR TITLE
Mhang/use media comp static resource

### PR DESCRIPTION
**Pull request by mikehang-msft**
# Contributing to the Azure SDK
Updated Media Composition to use static test resource.

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by mikehang-msft** [comment]
\azp run net - Azure.Communication.MediaComposition - tests

**Comment by minnieliu** [comment]
\azp run net - Azure.Communication.MediaComposition - tests

**Review by minnieliu — APPROVED** [review]

**Comment by mikehang-msft** [comment]
close and will raise another PR.

**Pull request closed without merging**
