### PR TITLE
Adding Database Operation Updates for Database Copy Operations

### PR DESCRIPTION
**Pull request by dominiqa**
Adding Database Operation Updates for Database Copy Operations

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dominiqa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by yugangw-msft** [comment]
do you have related PR from hydra-specs-pr?

**Comment by devigned** [comment]
I think it's related to:  https://github.com/Azure/hydra-specs-pr/pull/1068

**Comment by dominiqa** [comment]
Yes it is.

**Comment by stankovski** [comment]
@dominiqa have the latest updates in hydra-specs-pr made it into this PR?

**Comment by dominiqa** [comment]
Yes, they have.  The need for this second PR is due to a missing file from the first PR I submitted.

**Pull request merged**
