### PR TITLE
Enable spell check storage public API

### PR DESCRIPTION
**Pull request by danieljurek**
# All SDK Contribution checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] **Please open PR in `Draft` mode if it is:**
	- Work in progress or not intended to be merged.
	- Encountering multiple pipeline failures and working on fixes.
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md).**

### [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code. (Track 2 only)
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK. Please double check nuget.org current release version.

## Additional management plane SDK specific contribution checklist: 
Note: Only applies to `Microsoft.Azure.Management.[RP]` or `Azure.ResourceManager.[RP]`
 
- [ ] Include updated [management metadata](https://github.com/Azure/azure-sdk-for-net/tree/master/eng/mgmt/mgmtmetadata).
- [ ] Update AzureRP.props to add/remove version info to maintain up to date API versions.

### Management plane SDK Troubleshooting
- If this is very first SDK for a services and you are adding new service folders directly under /SDK, please add `new service` label and/or contact assigned reviewer.
- If the check fails at the `Verify Code Generation` step, please ensure:
	- Do not modify any code in generated folders.
	- Do not selectively include/remove generated files in the PR.
	- Do use `generate.ps1/cmd` to generate this PR instead of calling `autorest` directly.
	Please pay attention to the @microsoft.csharp version output after running `generate.ps1`. If it is lower than current released version (2.3.82), please run it again as it should pull down the latest version.
	
	**Note: We have recently updated the PSH module called by `generate.ps1` to emit additional data. This would help reduce/eliminate the Code Verification check error. Please run following command**:

	    `dotnet msbuild eng/mgmt.proj /t:Util /p:UtilityName=InstallPsModules`

### Old outstanding PR cleanup
 Please note:
	If PRs (including draft) has been out for more than 60 days and there are no responses from our query or followups, they will be closed to maintain a concise list for our reviewers.

### CODE REVIEW

**Comment by danieljurek** [comment]
@kasobol-msft -- This PR enables CI failure for spelling errors in the Public API surface. Many of these look like false positives. You can find out more about how to configure the spell checker to handle these false positives at https://aka.ms/azsdk/engsys/spellcheck

```
/mnt/vss/_work/1/s/sdk/storage/Azure.ResourceManager.Storage/api/Azure.ResourceManager.Storage.netstandard2.0.cs:151:26 - Unknown word (Skus)
/mnt/vss/_work/1/s/sdk/storage/Azure.ResourceManager.Storage/api/Azure.ResourceManager.Storage.netstandard2.0.cs:153:19 - Unknown word (Skus)
/mnt/vss/_work/1/s/sdk/storage/Azure.ResourceManager.Storage/api/Azure.ResourceManager.Storage.netstandard2.0.cs:245:54 - Unknown word (Skus)
/mnt/vss/_work/1/s/sdk/storage/Azure.ResourceManager.Storage/api/Azure.ResourceManager.Storage.netstandard2.0.cs:245:69 - Unknown word (Skus)
/mnt/vss/_work/1/s/sdk/storage/Azure.ResourceManager.Storage/api/Azure.ResourceManager.Storage.netstandard2.0.cs:517:84 - Unknown word (Aadds)
/mnt/vss/_work/1/s/sdk/storage/Azure.ResourceManager.Storage/api/Azure.ResourceManager.Storage.netstandard2.0.cs:1513:76 - Unknown word (Gzrs)
/mnt/vss/_work/1/s/sdk/storage/Azure.ResourceManager.Storage/api/Azure.ResourceManager.Storage.netstandard2.0.cs:1515:76 - Unknown word (Ragrs)
/mnt/vss/_work/1/s/sdk/storage/Azure.ResourceManager.Storage/api/Azure.ResourceManager.Storage.netstandard2.0.cs:1516:76 - Unknown word (Ragzrs)
/mnt/vss/_work/1/s/sdk/storage/Azure.ResourceManager.Storage/api/Azure.ResourceManager.Storage.netstandard2.0.cs:1536:9 - Unknown word (Deprovisioning)
 2/12 ./sdk/storage/Azure.Storage.Blobs.Batch/api/Azure.Storage.Blobs.Batch.netstandard2.0.cs 33.63ms
 3/12 ./sdk/storage/Azure.Storage.Blobs.ChangeFeed/api/Azure.Storage.Blobs.ChangeFeed.netstandard2.0.cs 26.42ms X
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Blobs.ChangeFeed/api/Azure.Storage.Blobs.ChangeFeed.netstandard2.0.cs:98:72 - Unknown word (Undelete)
 4/12 ./sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs 115.18ms X
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs:176:80 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs:177:80 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs:179:109 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs:180:109 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs:520:73 - Unknown word (Rehydrated)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs:1280:9 - Unknown word (Posix)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs:1315:17 - Unknown word (Ragrs)
 5/12 ./sdk/storage/Azure.Storage.Common/api/Azure.Storage.Common.netstandard2.0.cs 25.82ms
 6/12 ./sdk/storage/Azure.Storage.Files.DataLake/api/Azure.Storage.Files.DataLake.netstandard2.0.cs 70.84ms X
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.DataLake/api/Azure.Storage.Files.DataLake.netstandard2.0.cs:210:88 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.DataLake/api/Azure.Storage.Files.DataLake.netstandard2.0.cs:211:117 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.DataLake/api/Azure.Storage.Files.DataLake.netstandard2.0.cs:325:94 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.DataLake/api/Azure.Storage.Files.DataLake.netstandard2.0.cs:326:123 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.DataLake/api/Azure.Storage.Files.DataLake.netstandard2.0.cs:874:9 - Unknown word (Posix)
 7/12 ./sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.netstandard2.0.cs 72.84ms X
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.netstandard2.0.cs:330:79 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.netstandard2.0.cs:331:108 - Unknown word (Undelete)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.netstandard2.0.cs:378:50 - Unknown word (Ntfs)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.netstandard2.0.cs:392:293 - Unknown word (Ntfs)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.netstandard2.0.cs:392:372 - Unknown word (Ntfs)
/mnt/vss/_work/1/s/sdk/storage/Azure.Storage.Files.Shares/api/Azure.Storage.Files.Shares.netstandard2.0.cs:402:17 - Unknown word (Ntfs)
 8/12 ./sdk/storage/Azure.Storage.Queues/api/Azure.Storage.Queues.netstandard2.0.cs 30.54ms
 9/12 ./sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/api/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs.netstandard2.0.cs 11.97ms
10/12 ./sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/api/Microsoft.Azure.WebJobs.Extensions.Storage.Common.netstandard2.0.cs -
11/12 ./sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/api/Microsoft.Azure.WebJobs.Extensions.Storage.Queues.netstandard2.0.cs 25.51ms
12/12 ./sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage/api/Microsoft.Azure.WebJobs.Extensions.Storage.netstandard2.0.cs -
CSpell: Files checked: 10, Issues found: 28 in 5 files

```

**Comment by danieljurek** [comment]
To go forward here I recommend we set up the exceptions for the false positives and include those in this PR.

**Comment by kasobol-msft** [comment]
> To go forward here I recommend we set up the exceptions for the false positives and include those in this PR.

This is great. I can confirm these hits are false positives. Would you mind setting up the exclusion file? or do you want us to take this forward?

**Comment by kasobol-msft** [comment]
In favor of https://github.com/Azure/azure-sdk-for-net/pull/22205

**Pull request closed without merging**
