### PR TITLE
Fist iotfirmwaredefense update SDK to swagger 2024-01-10

### PR DESCRIPTION
**Pull request by eatkimchee**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by eatkimchee** [comment]
Hi, I've attempted to push the recordings to the assets repo but getting permission failures. I requested to join the azure-sdk-write-iot group but have not heard from them yet

**Comment by eatkimchee** [comment]
Hi @m-nash the PR is ready for review, thanks!

**Comment by eatkimchee** [comment]
Hi @KrzysztofCwalina, @tg-msft, @archerzz, @ArcturusZhang , @ArthurMa1978  could we please have this PR reviewed? I keep having to rebase it from main because of other wide sweeping changes being merged into the repo. We are planning to announce GA at the end of next month so would very much like to get merged in order to make the release cutoff window. thanks!

**Comment by eatkimchee** [comment]
here we go again 🤦

**Comment by eatkimchee** [comment]
@ArthurMa1978   We have sign off from @MSEvanhi that we can proceed with this release without typespec, as it won't be strictly enforced until next month
https://github.com/Azure/sdk-release-request/issues/4958#issuecomment-1960092239

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
