### PR TITLE
Fix Version of OpenTelemetry.Extensions.AzureMonitor in package list

### PR DESCRIPTION
**Pull request by weshaggard**
Also update the AnalyzeDeps to not fail if the Version property doesn't exists but instead just skip it.

cc @jsquire

### CODE REVIEW

**Review by benbp — APPROVED** [review]

**Review by jsquire — APPROVED** [review]
Thanks, Wes!

**Comment by weshaggard** [comment]
@jsquire onto the next layer of the onion for the aggregate-reports pipeline.

**Pull request merged**
