### PR TITLE
Dotnet SDK changes for 2019-10-01 Tags API for resources and subscriptions

### PR DESCRIPTION
**Pull request by Grayer123**
Update Generated code; 
Add tag related test cases; 
Update SessionRecords due to API version change.

Links to the swagger spec review PR:

- https://github.com/Azure/azure-rest-api-specs/pull/7716 (Swagger specifications for 2019-10-01 Tags API for resources and subscriptions);

- https://github.com/Azure/azure-rest-api-specs/pull/8043 (Apply fix api-version and ScopeDeployment from 2019-08-01 to 2019-10-01);

- https://github.com/Azure/azure-rest-api-specs/pull/8184 (Revert change "fix api-version from method property to client property" for Resources within 2019-08-01 and 2019-10-01);

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @Grayer123  please remember to remove the "[Draft]" or "WIP" or anything like that otherwise the review request might have been ignored...

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @Grayer123 , could you
- Add a link to the swagger spec review PR in the description
- Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release

Thanks

**Comment by Grayer123** [comment]
Hello @isra-fel, we have a question regarding autorest swagger to generate sdk code. When we specify an api parameter like:
_{            
    "name": "api-version",
    "in": "query",
    "required": true,
    "type": "string",
    "description": "The API version to use for the operation."
}_
in the "parameters": [] for an api operation in swagger, 
it actually generate a parameter in SDK api operation like:
 void CreateOrUpdate (... **string api-version**...);
 
But if we specify like this:
_{
    "$ref": "#/parameters/ApiVersionParameter"
}_
(We define _ApiVersionParameter_ with the same definition as above in the Parameters {} section at the bottom of swagger file)
in the swagger "parameters": [], in the SDK generated operation, it will generate like:
**void CreateOrUpdate (...)**, without string api-version as a parameter.
Then we need to rely on the **ResourceManagementClient.ApiVersion** for this one.

We want to know what's the difference here for generating code with different defining methods, which related to a previous swagger change we made.

Many thanks.

**Comment by isra-fel** [comment]
Hi @Grayer123 I'm not sure about how C# generator handle them different. I suppose you can submit an issue in https://github.com/Azure/autorest.csharp

**Comment by Grayer123** [comment]
Hello @isra-fel, thanks for the info, I have created a new issue within autorest. 
Added links to the swagger spec review PR in the description; included the .txt file generated by generate.ps1; modified release notes and updated assembly version.

Also, for the above failed checks: 
one is related to Microsoft.Azure.EventHubs.Tests, which I did not make any changes. (only modified Microsoft.Azure.Management.Resource);
another one is related to "Git checkout failed".

Could you please help us re-trigger new checks? Thanks.

**Comment by Grayer123** [comment]
Hello @isra-fel, the error went away when I re-merged from the master branch. Could you please kindly do a review of this pr?

**Review by hamidtirmizi — APPROVED** [review]

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @Grayer123 , just one thing left: please update [AzSdk.RP.props](https://github.com/Azure/azure-sdk-for-net/blob/66ecc8f18ba2a35e53a350ee825c2afeba402de0/sdk/resources/Microsoft.Azure.Management.Resource/AzSdk.RP.props) so that correct API version can be displayed on nuget.org page. Then I will merge the PR. THanks

**Comment by Grayer123** [comment]
Hello @isra-fel, I have updated AzSdk.RP.props, please review one more time. Thanks

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
