### PR TITLE
2024-05 Fleet .NET sdk generation

### PR DESCRIPTION
**Pull request by frantran**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by frantran** [comment]
affected by breaking change issue:

/Users/francis/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.20467.1/build/Microsoft.DotNet.ApiCompat.targets(82,5): error : MembersMustExist : Member 'public System.Nullable<Azure.ResourceManager.ContainerServiceFleet.Models.NodeImageSelectionType> Azure.ResourceManager.ContainerServiceFleet.Models.ContainerServiceFleetManagedClusterUpdate.SelectionType.get()' does not exist in the implementation but it does exist in the contract. [/Users/francis/go/src/goms.io/dotnet-stuff/autoupgrade-api/azure-sdk-for-net/sdk/fleet/Azure.ResourceManager.ContainerServiceFleet/src/Azure.ResourceManager.ContainerServiceFleet.csproj::TargetFramework=netstandard2.0]
/Users/francis/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.20467.1/build/Microsoft.DotNet.ApiCompat.targets(82,5): error : MembersMustExist : Member 'public void Azure.ResourceManager.ContainerServiceFleet.Models.ContainerServiceFleetManagedClusterUpdate.SelectionType.set(System.Nullable<Azure.ResourceManager.ContainerServiceFleet.Models.NodeImageSelectionType>)' does not exist in the implementation but it does exist in the contract. [/Users/francis/go/src/goms.io/dotnet-stuff/autoupgrade-api/azure-sdk-for-net/sdk/fleet/Azure.ResourceManager.ContainerServiceFleet/src/Azure.ResourceManager.ContainerServiceFleet.csproj::TargetFramework=netstandard2.0]
/Users/francis/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.20467.1/build/Microsoft.DotNet.ApiCompat.targets(96,5): error : ApiCompat failed for '/Users/francis/go/src/goms.io/dotnet-stuff/autoupgrade-api/azure-sdk-for-net/artifacts/bin/Azure.ResourceManager.ContainerServiceFleet/Debug/netstandard2.0/Azure.ResourceManager.ContainerServiceFleet.dll' [/Users/francis/go/src/goms.io/dotnet-stuff/autoupgrade-api/azure-sdk-for-net/sdk/fleet/Azure.ResourceManager.ContainerServiceFleet/src/Azure.ResourceManager.ContainerServiceFleet.csproj::TargetFramework=netstandard2.0]

**Comment by frantran** [comment]
> affected by breaking change issue:
> 
> /Users/francis/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.20467.1/build/Microsoft.DotNet.ApiCompat.targets(82,5): error : MembersMustExist : Member 'public System.Nullable<Azure.ResourceManager.ContainerServiceFleet.Models.NodeImageSelectionType> Azure.ResourceManager.ContainerServiceFleet.Models.ContainerServiceFleetManagedClusterUpdate.SelectionType.get()' does not exist in the implementation but it does exist in the contract. [/Users/francis/go/src/goms.io/dotnet-stuff/autoupgrade-api/azure-sdk-for-net/sdk/fleet/Azure.ResourceManager.ContainerServiceFleet/src/Azure.ResourceManager.ContainerServiceFleet.csproj::TargetFramework=netstandard2.0] /Users/francis/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.20467.1/build/Microsoft.DotNet.ApiCompat.targets(82,5): error : MembersMustExist : Member 'public void Azure.ResourceManager.ContainerServiceFleet.Models.ContainerServiceFleetManagedClusterUpdate.SelectionType.set(System.Nullable<Azure.ResourceManager.ContainerServiceFleet.Models.NodeImageSelectionType>)' does not exist in the implementation but it does exist in the contract. [/Users/francis/go/src/goms.io/dotnet-stuff/autoupgrade-api/azure-sdk-for-net/sdk/fleet/Azure.ResourceManager.ContainerServiceFleet/src/Azure.ResourceManager.ContainerServiceFleet.csproj::TargetFramework=netstandard2.0] /Users/francis/.nuget/packages/microsoft.dotnet.apicompat/5.0.0-beta.20467.1/build/Microsoft.DotNet.ApiCompat.targets(96,5): error : ApiCompat failed for '/Users/francis/go/src/goms.io/dotnet-stuff/autoupgrade-api/azure-sdk-for-net/artifacts/bin/Azure.ResourceManager.ContainerServiceFleet/Debug/netstandard2.0/Azure.ResourceManager.ContainerServiceFleet.dll' [/Users/francis/go/src/goms.io/dotnet-stuff/autoupgrade-api/azure-sdk-for-net/sdk/fleet/Azure.ResourceManager.ContainerServiceFleet/src/Azure.ResourceManager.ContainerServiceFleet.csproj::TargetFramework=netstandard2.0]

this has now been resolved by adding a Customized file:
https://github.com/Azure/azure-sdk-for-net/pull/46353/files#diff-092e8332bd077ec9161832ca9892da33d16aa977bcca61cfb1d1d377dd3cd935

**Review by archerzz — APPROVED** [review]
LGTM. Two comments:
- Since there is addition of API, it would be better to add test cases.
- For changelog, just briefly mentioned the major changes, like adding a new long running api regarding auto upgrade profile

**Comment by frantran** [comment]
> LGTM. Two comments:
> 
> * Since there is addition of API, it would be better to add test cases.
> * For changelog, just briefly mentioned the major changes, like adding a new long running api regarding auto upgrade profile

all of the Fleet API is under: https://github.com/Azure/azure-sdk-for-net/pull/46353/files#diff-4364392af29788976b63b9405105729260745e447155ddaa04e454e69fa00e6a

I already added testing out the AutoUpgrade API.

For the changelog, already added a  similar comment to yours

**Pull request merged**
