### PR TITLE
Adding CodeSimplifier to code generation process

### PR DESCRIPTION
**Pull request by tbombach**
# Updated:
- (**Commit 1**) `autorest.gen.cmd` to call `CodeSimplifier.exe` after using AutoRest.

Adding:
- (**Commit 2**) `CodeSimplifier` src, which takes a folder of .cs files and uses Roslyn to reduce fully qualified names when possible
  - Most relevant: `Program.cs`
- (**Commit 3**) `CodeSimplifier.exe` in tools folder

For some reason, Github isn't expanding all of the diffs for some reason. Check out https://github.com/tbombach/azure-sdk-for-net/tree/code-simplifier/tools/CodeSimplifier/src/CodeSimplifier to browse the files in my fork

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tbombach__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tbombach). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@tbombach  Thanks!  What is the rationale behind checking in the binaries rather than building as part of building the repo?  Also, can you clarify if current generate.cmd files would not work to regenerate code, and what modifications need to be made to allow correct generation (I believe this is just updeting the autorest version).  Can we document the change in the README>md for the repo.

**Comment by tbombach** [comment]
@markcowl Thanks for the feedback! I added some steps to `Readme.md`, that explain how using `generate.cmd` will result in simplified names in generated code. Current `generate.cmd` files will continue to work for code, and I've updated the instructions to include which nightly AutoRest they should use to get the full benefit of name reduction.

As for checking in the CodeSimplifier binary, here's my rationale:
If we want the CodeSimplifier project to be built on-demand, we would have to add a `msbuild` step to `autorest.gen.cmd` (since `build.proj` only builds during a PR, not when an author is generating their client code). I think it's preferable that `autorest.gen.cmd` just uses the executable, rather than doing a project build every time the client needs to be regenerated. The tradeoff is that any changes to the `CodeSimplifier` src also require updating the binary as an extra step. I'm open to either way, but I'd lean towards only rebuilding the binary when we need `CodeSimplifier` changes (which shouldn't be very often). If we're okay with that approach, I'll also add instructions for copying the executable for `CodeSimplifier`.

**Comment by tbombach** [comment]
Closing this PR, since the changes will be made to AutoRest

**Pull request closed without merging**
