### PR TITLE
Supporting Availability set as input for Vmware to Azure and Hyper V to Azure in Site Recovery service

### PR DESCRIPTION
**Pull request by vidyadharijami**
Supporting Availability set as input for Vmware to Azure and Hyper V to Azure in Site Recovery service

### CODE REVIEW

**Comment by vidyadharijami** [comment]
@m-nash Can you please review this PR.

**Comment by m-nash** [comment]
Can you add the swagger PR to this PR?

**Comment by vidyadharijami** [comment]
> Can you add the swagger PR to this PR?

Here is the Swagger PR
https://github.com/Azure/azure-rest-api-specs/pull/12368

**Comment by m-nash** [comment]
Assigning to Allen to look into ci error

**Comment by allenjzhang** [comment]
Went thru generate.ps1 locally and confirmed that there are a lot more changes than what's in the PR. Vidya will regenerate and push another commit.

**Comment by allenjzhang** [comment]
Exception granted for this PR.

**Pull request merged**
