### PR TITLE
Prep for Storage WebJobs GA release

### PR DESCRIPTION
**Pull request by seanmcc-msft**

### CODE REVIEW

**Review by amnguye — APPROVED** [review]

**Comment by seanmcc-msft** [comment]
@jsquire I think there might be an issue with the "storage - ci - functions" pipeline.

**Comment by jsquire** [comment]
> @jsquire I think there might be an issue with the "storage - ci - functions" pipeline.

@seanmcc-msft:  It wasn't classified, so DevOps disabled it.   I clicked the buttons, should be active now.   You'll likely need to do the same for the other pipelines that were created yesterday.   Looks like the EngSys automation to classify on creation isn't done yet.

**Comment by seanmcc-msft** [comment]
> > @jsquire I think there might be an issue with the "storage - ci - functions" pipeline.
> 
> @seanmcc-msft: It wasn't classified, so DevOps disabled it. I clicked the buttons, should be active now. You'll likely need to do the same for the other pipelines that were created yesterday. Looks like the EngSys automation to classify on creation isn't done yet.

@jsquire is there documentation for these steps?  I am not familiar with this process.

**Comment by jsquire** [comment]
> > > @jsquire I think there might be an issue with the "storage - ci - functions" pipeline.
> > 
> > 
> > @seanmcc-msft: It wasn't classified, so DevOps disabled it. I clicked the buttons, should be active now. You'll likely need to do the same for the other pipelines that were created yesterday. Looks like the EngSys automation to classify on creation isn't done yet.
> 
> @jsquire is there documentation for these steps? I am not familiar with this process.

If you go to the pipeline, you'll see a big yellow banner at the top yelling at you.  That has a link for help that describes the process.   After you classify, it's Settings => Enable => Save Changes.

**Comment by seanmcc-msft** [comment]
@jsquire what service do I assign the pipelines to?

**Comment by jsquire** [comment]
> @jsquire what service do I assign the pipelines to?

I've been using:  Azure SDK => Peter Marcu => Azure SDK

**Comment by seanmcc-msft** [comment]
@jsquire I don't have permissions:

image

**Pull request merged**
