### PR TITLE
Reservations SDK with tests updated

### PR DESCRIPTION
**Pull request by corquiri**
Most recent .Net SDK already merged to master. This PR is to fix failing test. I verified that both below works:

msbuild build.proj /t:Build /p:Scope=SDKs\Reservations
msbuild build.proj /t:RunTests /p:Scope=SDKs\Reservations

### CODE REVIEW

**Comment by corquiri** [comment]
I also need to publish this package to NuGet, please let me know if I have all the requirement ready.

**Comment by corquiri** [comment]
netcore build failed with error:
The command "sudo apt-get update" failed and exited with 100 during .
Could someone help me why I am getting this error?

**Comment by dsgouda** [comment]
> 
> 
> netcore build failed with error:
> The command "sudo apt-get update" failed and exited with 100 during .
> Could someone help me why I am getting this error?

We are working on fixing it, should be unrelated to this change

**Review by dsgouda — CHANGES_REQUESTED** [review]
Confirming tests fixed [here](https://azuresdkci.westus2.cloudapp.azure.com/view/Signing%20and%20Publishing/job/NetCore-SDK-Sign/535/)
@corquiri Please update the Assembly Version and PackageReleaseNotes in csproj/AssemblyInfo.cs files if you wish to publish a Nuget for this

**Comment by dsgouda** [comment]
@corquiri  Please pull from latest master and update the PR to fix the Travis failures

**Comment by corquiri** [comment]
@dsgouda I have pulled latest master and bumped up the version. Could you please review and merge this request?

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@corquiri Tests are still failing [here](https://azuresdkci.westus2.cloudapp.azure.com/job/CI-NetSDK_U/2324/console)
PTAL and fix them

**Comment by corquiri** [comment]
That failure was introduced by PR : https://github.com/Azure/azure-sdk-for-net/pull/5889 
Which is separate task from this PR. @gautam714 will be working on fixing test.

**Pull request merged**
