### PR TITLE
Batch - Management Plane Version 8.0.0

### PR DESCRIPTION
**Pull request by jafreck**

### CODE REVIEW

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please update the `AssemblyInfo.cs` file

**Review by xingwu1 — APPROVED** [review]

**Comment by jafreck** [comment]
@dsgouda I have made the requested change to update AssemblyInfo to the correct version.

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
Will merge once CIs pass

**Comment by dsgouda** [comment]
@jafreck have you joined the Azure org [here](https://aka.ms/azuregithub)

**Comment by jafreck** [comment]
> @jafreck have you joined the Azure org [here](https://aka.ms/azuregithub)

Yes, I am a member. However, it appears as though the CI is stuck.

**Comment by dsgouda** [comment]
@azuresdkci Retest this please

**Pull request merged**
