### PR TITLE
Add Microsoft.Network to the list of namespaces to register

### PR DESCRIPTION
**Pull request by vladca**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vladca__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vladca). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
I'm not sure this is the right fix.  This only registers network if the DnsClient is used - why would it not be registered when the generic resources client is used (which could also access network resources), or other network clients?

**Comment by vladca** [comment]
Thanks for the comment, Mark. Sure thing, the owners of the the generic resources client and other network clients can add on top of my change if they wish.

**Comment by ogail** [comment]
@vladca based on the discussion I assume another PR will be sent that has a different change

**Pull request closed without merging**
