### PR TITLE
FormRecognizer Receipt SDK PR

### PR DESCRIPTION
**Pull request by ramparab**

### CODE REVIEW

**Comment by dsgouda** [comment]
@ramparab Please link the REST spec PR

**Comment by ramparab** [comment]
REST spec PR: 
https://github.com/Azure/azure-rest-api-specs/pull/6042

**Comment by ramparab** [comment]
@AlexGhiondea: Please review this PR and let me know if you need any additional information.

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Please reopen this PR manually. The directory structure has been changed and the generated PR is not correct.
The current PR has been generated in multiple directories and it is not correct. This is unfortunate due to the directory restructure done for data plane projects only.

**Comment by ramparab** [comment]
Created new PR:
https://github.com/Azure/azure-sdk-for-net/pull/6466

**Pull request closed without merging**
