### PR TITLE
Updating SDK package to include Quota APIs

### PR DESCRIPTION
**Pull request by rahuls-microsoft**
1. Updated Version and PackageReleaseNotes

### CODE REVIEW

**Comment by rahuls-microsoft** [comment]
https://github.com/AzureSDKAutomation/azure-sdk-for-net/pull/1220
I am assuming based the previous automated SDK generation the files are already merged to master.
I updating the version and PackageReleaseNotes.

Please let me know, if any further steps are required to release to Public site.
Doc Link - https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/quotaapi

**Review by isra-fel — CHANGES_REQUESTED** [review]
Looks OK but [this line](https://github.com/Azure/azure-sdk-for-net/blob/4a641d6e27099ed77b96e068bd3b30edd8f184c1/sdk/reservations/Microsoft.Azure.Management.Reservations/src/Properties/AssemblyInfo.cs#L11) also needs to be updated

**Comment by rahuls-microsoft** [comment]
I don't see the Quota API and model in source.
How was - https://sdkautomation.blob.core.windows.net/sdkautomation-pipeline/Azure/azure-rest-api-specs/9724/azure-sdk-for-net/Azure/azure-sdk-for-net/Microsoft.Azure.Management.Reservations/Microsoft.Azure.Management.Reservations.1.13.0-preview.nupkg generated. We need to get the sources from 
https://github.com/AzureSDKAutomation/azure-sdk-for-net/pull/1220

**Comment by rahuls-microsoft** [comment]
> Looks OK but [this line](https://github.com/Azure/azure-sdk-for-net/blob/4a641d6e27099ed77b96e068bd3b30edd8f184c1/sdk/reservations/Microsoft.Azure.Management.Reservations/src/Properties/AssemblyInfo.cs#L11) also needs to be updated

Updated the version.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
