### PR TITLE
[docs] root README update (link fixes+)

### PR DESCRIPTION
**Pull request by mmacy**
* Fix links and move to relative links for in-repo files
* Sentence-style capitalization for headings (MS Cloud Style Guide and MS Writing Style Guide standard)
* Clarification on READMEs as getting started guides

### CODE REVIEW

**Comment by mmacy** [comment]
@scbedd Another one, Scott - is this something you can review?

**Comment by scbedd** [comment]
@mmacy I can most certainly try! I will take a look at this one + #6192 later today if no one else has.

**Review by KrzysztofCwalina — APPROVED** [review]

**Comment by scbedd** [comment]
@KrzysztofCwalina beat me to the punch :P 

Thanks sir!

**Comment by KrzysztofCwalina** [comment]
@mmacy, should we merge it?

**Comment by mmacy** [comment]
@KrzysztofCwalina Yes, please.

**Pull request merged**
