### PR TITLE
Update SystemEventTypeMappings.cs

### PR DESCRIPTION
**Pull request by xioyi**

### CODE REVIEW

**Review by Kishp01 — APPROVED** [review]

**Review by ahamad-MS — APPROVED** [review]
LGTM

**Comment by xioyi** [comment]
@azuresdkci Would you please merge this PR? Thanks,

**Comment by jsquire** [comment]
@xioyi : Apologies for the delay;  if you'd still like to merge, would you be kind enough to rebase to `master` and resolve the failing tests?

**Comment by jsquire** [comment]
@ahamad-MS:  As the approver, would you be so kind as to either merge or add the `auto-merge` tag to ensure that the PR is completed?   Since you've already approved, I added the tag to this item.

**Comment by jsquire** [comment]
Hi @xioyi.  Thank you for your contribution.  Since there hasn't been recent engagement, I'm going to close this out.  Please feel free to reopen if you'd like to continue working on these changes.

**Pull request closed without merging**
