### PR TITLE
[HOLD}: update description for all properties, new autorest client and vnet get on vnet peering from vnet

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by DeepakRajendranMsft** [comment]
swagger: https://github.com/Azure/azure-rest-api-specs/pull/695

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, Garrett just made changes (https://github.com/Azure/autorest/pull/1617) to AutoRest that bring back the usings and get rid of the long references in the generated code. Would you mind regenerating this code with the latest nightly build?

**Comment by markcowl** [comment]
@DeepakRajendranMsft  Please update to the latest version of the nightlies, as Cormac suggests

**Comment by markcowl** [comment]
@DeepakRajendranMsft Per email discussion will close by EOD if there is no movement

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft please re-open the PR when the comments can be addressed

**Pull request closed without merging**
