### PR TITLE
Remove query keys from Microsoft.Search tests

### PR DESCRIPTION
**Pull request by mattgotteiner**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by mattmsft** [comment]
@weshaggard

**Review by weshaggard — DISMISSED** [review]

**Comment by weshaggard** [comment]
@mattmsft looks like there are some tests that also need to be updated based on this change. https://dev.azure.com/azure-sdk/public/_build/results?buildId=2670890&view=ms.vss-test-web.build-test-results-tab

seems like there are some tests that are looking for an exact string.

**Comment by archerzz** [comment]
@mattmsft Could you please take a look at Wes's comment above?

Besides, to prevent unintentional leak of secrets, you might want to consider write your own sanitizer: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core.TestFramework#sanitizing

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by mattmsft** [comment]
Thank you for taking care of this. Much appreciated.

**Pull request merged**
