### PR TITLE
Update Azure.AI.TextAnalytics to latest Swagger

### PR DESCRIPTION
**Pull request by nisha-bhatia**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by nisha-bhatia** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/28608

**Comment by maririos** [comment]
ohh interesting that when running codegen, the legacy project generated a file too.

@jsquire or @JoshLove-msft do you know if there is a way to tell codegen to ignore the legacy project?

**Comment by jsquire** [comment]
@maririos : That looks like an API export.  If that was triggered by codegen, it's probably scoped to running against the service directory.   Because there isn't an API for that project, we did not generate one originally.   If we had, there probably would have been no change and no additional asset in this PR.

The interesting part for me is that ExportApi seems to be running against projects marked as "not a shipping library" - which I don't believe it should be.

**Review by maririos — APPROVED** [review]
I don't want to block your PR because of the addition of the legacy file. We will keep looking into it separately

**Pull request merged**
