### PR TITLE
[dec-rollup] Add changelog, comments and readme for Microsoft.E…

### PR DESCRIPTION
**Pull request by pakrym**
Cherry pick Microsoft.Extensions.Azure changes into release/dec-rollup branch

### CODE REVIEW

**Comment by pakrym** [comment]
Hey, @danieljurek seems that CI checks do not like this PR, any concerns with merging this?

**Comment by danieljurek** [comment]
🤔 strange. Having a look...

**Comment by weshaggard** [comment]
It is because they don't have branch triggers for `release/*`. Feel free to ignore the mgmt pipeline, and I since the core pipeline is the same as the client pipeline it is safe to ignore that one as well. I will however update the triggers for the client pipeline to help fix this.

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
