### PR TITLE
Added JobAccountOperations

### PR DESCRIPTION
**Pull request by jaredmoo**
The Azure SQL DB JobAccount feature is going into private preview soon. This commit adds the SDK for JobAccount CRUD.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jaredmoo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jaredmoo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jaredmoo** [comment]
@akromm @jamestao

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@akromm can you please assign someone to review this PR?

**Comment by jaredmoo** [comment]
Tests have passed, but for what it's worth the elastic pool test that Hovsep re-recorded a few weeks ago was still failing on my machine. Not sure what's going on with that.

**Comment by jaredmoo** [comment]
To clarify, it was failing on master branch without my change. I didn't regress it :)

**Comment by akromm** [comment]
I sign-off on this.

**Comment by jamestao** [comment]
Looks good to me.

**Comment by jaredmoo** [comment]
Thanks Adam & James. Awaiting merge.

**Pull request merged**
