### PR TITLE
 Merging Changes to enable Read Scale feature for Azure Sql DB

### PR DESCRIPTION
**Pull request by ziwa-msft**
The link to the hydra-spec is here: https://github.com/Azure/hydra-specs-pr/pull/1360

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ziwa-msft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ziwa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@ziwa-msft there are merge conflicts, please update your PR

**Comment by markcowl** [comment]
@ziwa-msft Please remove the [Merge Conflict] label in the title onse you have fixed the merge conflicts.

**Comment by shahabhijeet** [comment]
@ziwa-msft merge conflicts are still persisting. PR cannot be merged in this current state.

**Comment by shahabhijeet** [comment]
@ziwa-msft yes please close this PR if you think this is not the right PR

**Pull request closed without merging**
