### PR TITLE
AzureStackAdmin module TP2 Refresh 1 changes

### PR DESCRIPTION
**Pull request by bganapa**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bganapa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bganapa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bganapa** [comment]
Note that the PR lists any commits but most of them are already merged in to master with this PR https://github.com/Azure/azure-sdk-for-net/pull/2113 . Not sure why this PR lists them as well. Only the Last 4 commits should have been listed, The files changed lists only the changed files though https://github.com/Azure/azure-sdk-for-net/pull/2510/files

**Comment by markcowl** [comment]
@bganapa Please clean up the commits, you can use the guide here for some suggestions on how to do this:

Also please add a link to the PR for the associated spec change in the subscription.

**Comment by bganapa** [comment]
@markcowl Could you please point me to the guide?

**Comment by bganapa** [comment]
@markcowl The tests are passing, This should be good to merge

**Pull request merged**
