### PR TITLE
Change location of the pipeline test resources directory

### PR DESCRIPTION
**Pull request by gfeitosa-msft**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by ilyapaliakou-msft — APPROVED** [review]

**Comment by besh2014** [comment]
Why the pipeline test resources directory should be changed?

**Comment by gfeitosa-msft** [comment]
> Why the pipeline test resources directory should be changed?

Currently pipeline fails because test environment expects a variable called `COMMUNICATION_CLIENT_SECRET`, but the way the script works it generates the variable name based on the folder containing the test resources: 
image

For this reason the test-resources json and scripts were moved directly to the `./communication` folder. This change fixes this reference, also fixing the name of the env variable ([successful pipeline execution example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3790375&view=logs&j=76b7f760-7857-5526-9942-d88b580eb83a&t=52d165ea-e3ea-5fe0-2432-0318a30f8ee5)):

image

**Comment by gfeitosa-msft** [comment]
Failures in int still relate to resource provider script failing. The errors now seem to no longer be related to limit of resource groups as previously observed. Now RP fails returning 500:

image

**Pull request merged**
