### PR TITLE
Add artifact-level condition to skip TagRepository job

### PR DESCRIPTION
**Pull request by Mohit-Chakraborty**

### CODE REVIEW

**Comment by weshaggard** [comment]
@Mohit-Chakraborty while I'm not opposed to the flexibility here I'm curious what releases we don't want to create tags for that goes against our standard guidelines.

**Comment by Mohit-Chakraborty** [comment]
> I'm curious what releases we don't want to create tags for that goes against our standard guidelines.

@weshaggard, the motivation for this change is to skip release steps for some packages that are mixed with others in the same service directory.
With these switches (only one missing BTW), I can get the release pipeline to look like [what I want](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1006318&view=results) if I can also turn off the 'TagRepository' job (notice that one job remaining in the undesired packages).

[This is the change](https://github.com/Azure/azure-sdk-for-net/compare/mohitc/SkipRelease) I will make in the pipeline definition.

**Comment by weshaggard** [comment]
I guess I'm still interested in why we are disabling all the release steps for those other packages. How would we ever ship those?

**Comment by Mohit-Chakraborty** [comment]
> I guess I'm still interested in why we are disabling all the release steps for those other packages. How would we ever ship those?

No, the ones we want to disable are track 1 packages. We want to only ship the one track 2 package.
If there is ever a need to update a track 1 package, we can always update the ci.yml file to enable their release.

**Comment by weshaggard** [comment]
For other services like servicebus and eventhubs we chose to split track 1 and track 2 into different pipelines, see https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/ci.data.yml as example. That might be something you want to do in the case of search as well.

**Comment by Mohit-Chakraborty** [comment]
I feel this is a more elegant solution. No increase in number of pipelines and then having to remember which one is for which purpose. Plus, one of the two (track 1 pipeline) would practically never be used. With this, we understand and control the process.

**Comment by weshaggard** [comment]
Not trying to push back on this particular feature as I think it is fine in isolation but I'm not as sure about the reasons for applying it in this case.

If you are already going to have to edit the pipeline to ship these packages why not just comment out or delete the artifacts from the list of artifacts in the ci.yml file? That will accomplish the same goal and also eliminate other issues and noise in the release pipeline stage.

**Comment by Mohit-Chakraborty** [comment]
I can do that, yes. Two reasons I want to avoid that -
1. Will this cause the Microsoft.* artifacts to not build at all? My understanding is that the same .yml file is used for both CI builds and release builds.
2. I was hoping that the build and signing steps can still run on the assemblies during release to not regress them accidentally, and only skip the 'Release' jobs.
image

**Comment by weshaggard** [comment]
Building and testing will still happen but things none of the release process will happen. Including signing but we should probably also avoid the signing cost and risk if we aren't planning to release.

**Comment by weshaggard** [comment]
You have have a search for places like https://github.com/Azure/azure-sdk-for-net/blob/main/eng/pipelines/templates/stages/archetype-net-release.yml#L40 to see what we end up doing with the Artifact list.

**Comment by Mohit-Chakraborty** [comment]
Thanks, yes, that's where I found that one release job was not conditioned with an artifact property. So, I thought we can add it and then I can control the process with properties in the service-level .yml file.

If you think deleting the Microsoft.* packages from the artifacts list makes more sense, I will do that instead.

**Comment by weshaggard** [comment]
I'd suggest just commenting them out and then adding a comment that if we need to release these again in the future we should uncomment the artifact.

**Comment by weshaggard** [comment]
The comment also allows you to specify why they are not included. If we plan to remove the source code from main then we can also remove them completely from the artifact list as well.

**Comment by Mohit-Chakraborty** [comment]
Commenting out the track1 packages from the artifacts list looks good from the [build pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1023617&view=results) perspective. So, I will take that approach.

Thanks for your comments and suggestions.

**Pull request closed without merging**
