### PR TITLE
Regenerate for 2019-07-01/Microsoft.Resources.

### PR DESCRIPTION
**Pull request by Tiano2017**

### CODE REVIEW

**Comment by Tiano2017** [comment]
@erich-wang I'm not sure why the CI runs are failing. All the test cases passed on my local box. Any suggestions?

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @Tiano2017 , every management plane PR should include a `.txt` file for tracking. I tried `generate.ps1` and it worked perfectly. 
P.S. You might want to edit it and change the tag before runing.

Detailed instruction [here](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-directory-structure-and-sdk-generation), step 8. Please let me know if you get any trouble

**Comment by Tiano2017** [comment]
@isra-fel I had to some changes to make it work. updated the PR.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
