### PR TITLE
Log x-ms-request-id for tests only

### PR DESCRIPTION
**Pull request by heaths**
Helps follow up with the service team if any service issues occur during nightly live test runs.

### CODE REVIEW

**Comment by christothes** [comment]
Is this logging issue specific to Key Vault? If not is there a way we can do this centrally in the test framework?

**Comment by heaths** [comment]
I asked @pakrym about it, but just want to get something sooner than later. If anything, we should probably ask other .NET track 2 SDKs if they don't mind. I can't imagine it being a problem, but should ask.

I'd just put something in `RecordingTestBase.InstrumentClientOptions` like we do to adjust timeouts for recorded tests.

**Comment by pakrym** [comment]
This header is not very consistent across the services and I'm not sure it's worth doing across the board.

**Review by christothes — APPROVED** [review]

**Comment by schaabs** [comment]
Shouldn't the clients for Key Vault send this by default rather than just sending it in the tests?

**Comment by heaths** [comment]
The concern is that this is PII and we wouldn't want it leaked by default. But for tests, it's limited to either your machine (local tests) or cloud machines which use generated service principals. For local tests, for this to leak you'd have to send it yourself. It already did show up in test recording JSONs.

**Pull request merged**
