### PR TITLE
Support account names when using custom domains

### LINKED ISSUE #10539: [BUG] Connection strings with explicit hostname endpoint does not resolve correctly
**Describe the bug**
The connection string from [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-the-well-known-account-name-and-key) does not parse correctly if the endpoints are replaced with custom hostnames.

An example is the connection string 

```
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;
```
This previously worked in M.A.S.B v. 11. This is used to let docker containers connect to the storage emulator running on the host.

**Expected behavior**
The connection string should parse correctly and set the account name to `devstoreaccount1`.

**Actual behavior (include Exception or Stack Trace)**
The generated Uri in `BlobUriBuilder` does not correctly include the account name.

**To Reproduce**

This test in `ContainerClientTests.cs` does not pass:

```
        [Test]
        [ServiceVersion(Min = BlobClientOptions.ServiceVersion.V2019_02_02)]
        public void Ctor_ConnectionString_ReferenceDevelopmentStorage_WithCustomHostnameEndpoints()
        {
            // From https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-the-well-known-account-name-and-key
            // but with hostnames instead of IP's in endpoint specification
            var connectionString = @"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;";

            var containerName = "containername";

            BlobContainerClient container = InstrumentClient(new BlobContainerClient(connectionString, containerName));

            var builder = new BlobUriBuilder(container.Uri);

            Assert.AreEqual(containerName, builder.BlobContainerName);
            Assert.AreEqual("", builder.BlobName);
            Assert.AreEqual("devstoreaccount1", builder.AccountName);
        }
```

**Environment:**
 - Azure.Storage.Blobs, master
 - Windows 10 .NET Core 3.1
 - Visual Studio 16.5

### PR DESCRIPTION
**Pull request by rmja**
Fixes #10539

### CODE REVIEW

**Comment by seanmcc-msft** [comment]
@tg-msft, what do you think?

**Comment by tg-msft** [comment]
I think we should do something here.  My biggest concerns are not breaking any existing (working) scenarios and making sure this works for Federated Azure and Azure Stack.

@JoshLove-msft  - could you weigh in with a few quick thoughts as you spent a bunch of time on this in the past?

**Comment by JoshLove-msft** [comment]
> I think we should do something here. My biggest concerns are not breaking any existing (working) scenarios and making sure this works for Federated Azure and Azure Stack.
> 
> @JoshLove-msft - could you weigh in with a few quick thoughts as you spent a bunch of time on this in the past?

It looks like with these changes, the AccountName is assumed to be populated after the host name for custom hosts.
```
var blobUriBuilder = new BlobUriBuilder(new Uri("https://www.mycustomname.com/container/blob"));
Console.WriteLine(blobUriBuilder.AccountName); // prints container
```
If I'm not mistaken, the format of the Uri from the issue being fixed and also mentioned in https://github.com/Azure/azure-sdk-for-net/issues/10539 is specific to the dev store account. As such, would it make sense to add a special case for the dev store account Uri when setting the AccountName? I think we have some existing logic around this in StorageConnectionString.cs.

**Review by zidad — APPROVED** [review]

**Comment by rmja** [comment]
Closing this one in favor of https://github.com/Azure/azure-sdk-for-net/pull/13124 which was merged

**Pull request closed without merging**
