### PR TITLE
SDK changes and test samples for AzureMySql connector, including linkedservice, dataset and source.

### PR DESCRIPTION
**Pull request by gadongji**
## Description

Related swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/1911
AutoRest is generating a lot of noise and please focus on AzureMySql part.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by gadongji** [comment]
The SDK is generated using AutoRest 2.0.4166

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
@gadongji missing spec PR link
Also missing .txt file that is generated when you use the Spec PR commit to generate the SDK using generate.cmd

**Comment by gadongji** [comment]
The spec PR was included in the description. and here is the link: https://github.com/Azure/azure-rest-api-specs/pull/1911

**Comment by gadongji** [comment]
The SDK is generated by AutoRest 2.0.4168

**Comment by gadongji** [comment]
@shahabhijeet, the changes you requested have been made. Please help review my PRs and merge them asap. Thanks a lot!

**Comment by bgold09** [comment]
approved via internal item [97894](https://msdata.visualstudio.com/Azure%20Data%20Factory/_workitems/edit/97894)

**Comment by cormacpayne** [comment]
@gadongji Milan's PR was merged earlier this morning: https://github.com/Azure/azure-sdk-for-net/pull/3812

Please pull in the latest changes from the `psSdkJson6` branch into your branch to resolve the merge conflicts and cleanup any potential overlapping changes.

**Comment by gadongji** [comment]
@cormacpayne I have merged with latest changes and resolved conflicts, please help review and merge again, THX!

**Comment by smilenow** [comment]
Please look at #3824  to prevent double merging. I propose that close this PR after #3824 merged.

**Comment by gadongji** [comment]
Hi @cormacpayne, we have created a new PR (https://github.com/Azure/azure-sdk-for-net/pull/3824) which merges three SDK changes from ADMS side to reduce merge conflicts. These three changes are all expected to be included in Nov. release. Please first try to merge the new PR and close this one if succeed. Otherwise, please merge this one on failure. Thanks a lot!

**Pull request closed without merging**
