### PR TITLE
 SDK update for ADF ExecuteSsisPackageActivity

### PR DESCRIPTION
**Pull request by yuanliu-ms**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by yuanliu-ms** [comment]
The REST spec PR link is: https://github.com/Azure/azure-rest-api-specs/pull/2102

**Comment by yuanliu-ms** [comment]
I use generate.cmd file to generate the SDK. But I don't know why the datafactory_resource-manager.txt file didn't update the REST spec commit version information.

**Comment by yuanliu-ms** [comment]
Hi @shahabhijeet , could you review the PR? We are quite closed to our time line. Thanks a lot for your help!

**Comment by yuanliu-ms** [comment]
Hi @shahabhijeet , I already merged the conflicts. Could you help review?  By the way, why the "default" check is keep in "waiting for status to be reported" status since I have no conflict now?

**Comment by shahabhijeet** [comment]
@hvermis can you approve this PR

**Review by hvermis — APPROVED** [review]

**Comment by yuanliu-ms** [comment]
@shahabhijeet , could u help merge my change to master branch?

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Please onboard using aka.ms/azuregithub
This seems you are not authorized to kick off CI jobs.
Once you get onboarded the CI job will be kicked off and once the CI passes this PR will be ready to be reviewed.

**Comment by yuanliu-ms** [comment]
Hi @shahabhijeet , all checks have passed now. Please help review and merge the PR. Thanks a lot.

**Comment by yuanliu-ms** [comment]
ping @shahabhijeet ... Could you help take a look?

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
1) Get latest updates from upstream (if you have not done so in last 3 weeks)
2) Then execute msbuild build.proj to update your build tools
3) Then regenerate your SDK (this will regenerate couple of additional files)
4) build you project (ether IDE or command line)
5) Then update your PR
With the latest changes, every regeneration will generate couple of additional meta data files that are needed in each PR.

**Comment by yuanliu-ms** [comment]
@shahabhijeet , I have synced with the latest code, regenerate the SDK and send out a new iteration of the PR. All checks have passed. Could you take a look?

**Comment by shahabhijeet** [comment]
@yuanliu-ms you are not using generate.cmd to generate your sdk.
We have enabled a feature that involves using a separate flag to generate your SDK, using generate.cmd will allow you to take advantage of that feature. This feature will allow you to tag your API version to your nuget package.

**Comment by yuanliu-ms** [comment]
@shahabhijeet Use generate.cmd to generate SDK. Please review.

**Review by shahabhijeet — APPROVED** [review]

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
