### PR TITLE
[DataFactory] Set computeType, coreCount to object type to allow expressions

### PR DESCRIPTION
**Pull request by Jingshu923**
Swagger PR:
Set computeType, coreCount to object type to allow expressions：https://github.com/Azure/azure-rest-api-specs/pull/10897

Change PartitionOption to object to allow expression :https://github.com/Azure/azure-rest-api-specs/pull/11613

### CODE REVIEW

**Review by markcowl — CHANGES_REQUESTED** [review]
Please add at least one test to validate the change. You will also need to update the version in the csproj and assemblyinfo.cs files

**Comment by Jingshu923** [comment]
@markcowl  Added a test case, the versions in the files will not be updated in this PR until we have a sdk release.

**Comment by Jingshu923** [comment]
@markcowl  Could you please review this PR again?

**Comment by markcowl** [comment]
@Jingshu923 We should not use the master branch for work in progress.  If this is not ready to be released, then please keep this in your fork, or we can create a feature branch.  We should not update the master branch until you are ready to release.

**Review by markcowl — APPROVED** [review]

**Pull request merged**
