### PR TITLE
New Kusto version

### PR DESCRIPTION
**Pull request by lucygoldbergmicrosoft**
1. New kusto version 
2. Add cluster/database principal assignment resources

The approved swagger spec review PR is: https://github.com/Azure/azure-rest-api-specs/pull/7832

### CODE REVIEW

**Review by isra-fel — DISMISSED** [review]
Hi @lucygoldbergmicrosoft  Could you
- Add a link to the swagger spec review PR in the description
- Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update api tag in `AzSdk.RP.props`, release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release

Thanks

**Comment by lucygoldbergmicrosoft** [comment]
@isra-fel , added changes as requested.

**Review by markcowl — APPROVED** [review]

**Comment by lucygoldbergmicrosoft** [comment]
@markcowl , @isra-fel , are there any more steps to do before we can merge this since it's approved already?

**Comment by markcowl** [comment]
@lucygoldbergmicrosoft There was an intermittent failure in the ci.  I have kicked it off, once it passes, we can merge.

**Pull request merged**
