### PR TITLE
Support single role restore for Azure Stack infrastructure backup

### PR DESCRIPTION
**Pull request by kaisxu**
Generated by Azure/azure-rest-api-specs commit 5afe3f875b75a0e97520b97b3bebb405f0f7819a

### CODE REVIEW

**Review by erich-wang — CHANGES_REQUESTED** [review]
@kaisxu, could you please share the swagger spec PR link related to this change?

**Comment by kaisxu** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/6315

**Comment by kaisxu** [comment]
@erich-wang Any other change needed?

**Comment by kaisxu** [comment]
@bganapa Could you pls review this change?

**Comment by erich-wang** [comment]
@kaisxu , do you need update nuget package version for this change? If yes, please update **Version** in csproj

**Comment by kaisxu** [comment]
Thanks @erich-wang . Version updated.

**Comment by erich-wang** [comment]
@kaisxu , could you please also update commit comment? "generated" is too general.

**Comment by kaisxu** [comment]
@erich-wang updated.

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
