### PR TITLE
Changes to Add Operation Status Polling for Azure Sql Database Failover Group Cmdlets in Autodr

### PR DESCRIPTION
**Pull request by ziwa-msft**
## Description

Fixing 2 long running operation pollings for Failover Group operations:

I have added support for long running operation status polling for the following two cmdlets:
    - Switch-AzureRmSqlDatabaseFailoverGroup
    - Remove-AzureRmSqlDatabaseFailoverGroup

Adding these changes, the 2 cmdlets above will wait for the operation to finish, then return.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x ] Title of the pull request is clear and informative.
- [x ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Please add descriptive title to the PR.
Make sure you describe what this PR is about, use the template to check applicable items.
Need version bump to publish. As you are changing return type, that's breaking change, will need major version bump.
I don't see any tests for this change?

**Review by jaredmoo — APPROVED** [review]

**Comment by ziwa-msft** [comment]
@shahabhijeet Hi Abhijeet. Jared has approved this PR after I have made the change to rebase on his checkin. Would you please also take a look and approve if you see fit please? Thanks

**Comment by ziwa-msft** [comment]
Title and Description Update.

**Comment by jaredmoo** [comment]
@ziwa-msft looks like you didn't do this from the checklist: The project.json and AssemblyInfo.cs files have been updated with the new version of the SDK.

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
