### PR TITLE
New Microsoft.Subscription SDK release

### PR DESCRIPTION
**Pull request by navysingla**

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi, please do not remove exisitng test cases.

**Comment by navysingla** [comment]
> Hi, please do not remove exisitng test case

But if the test cases are for the old APIs that we no longer want to support, then we need to remove them, right?

**Comment by isra-fel** [comment]
We need to adjust them to cover the new APIs 🤔

**Comment by navysingla** [comment]
Creating new PR from latest master

**Pull request closed without merging**
