### PR TITLE
fix: pass attributes defined in the ResourceBuilder along with azure monitor telemetry 

### LINKED ISSUE #40951: [FEATURE REQ] OpenTelemetry logging not passing Resource attributes
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0

### Describe the bug

Set attributes to ResourceBuilder. These attributes are not appearing as custom properties in AppInsights

```csharp
var loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddOpenTelemetry(options =>
    {
       options.SetResourceBuilder(ResourceBuilder.CreateDefault()
          .AddService(serviceName: "MyService", serviceVersion: "1.0.0")
          .AddAttributes(new Dictionary<string, object>() { { "prop1", "value" }}));
        options.AddAzureMonitorLogExporter();
    });
});
```

I am not sure if this is a missing feature or a bug.

### Expected behavior

`prop1` with value `value` is expected to appear as a custom property in AppInsights on the log message (similar to ILogger scopes).

Ref: [AddAttributes](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/customizing-the-sdk/README.md#resource)

### Actual behavior

Attributes do not appear.

### Reproduction Steps

Set up OpenTelemtry logging with Azure App Insights.
Customize the "resource" with ResourceBuilder.CreateDefault() and an attributes collection.

### Environment

.NET 8

### Workaround

My workaround for now: Creating a LogProcessor and manually extending the log message's Attributes collection.

### PR DESCRIPTION
**Pull request by mumby0168**
Closes #40951 #40630 #35487

This is my first PR to this area, I have read the guide but anything I need to add please let me know :)

One question I do have, is that the idea of OTEL and the resource attributes are sent once per batch of signals, I know this PR sends it per telemetry item, is there another option or is this not supported by the azure monitor SDK?

### CODE REVIEW

**Comment by mumby0168** [comment]
> @mumby0168 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
>  > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by cijothomas — CHANGES_REQUESTED** [review]
Supporting Resource should be coordinated with other languages as well, and need some spec/mapping defined before implementing.

See previous PR which also details the need for design first : https://github.com/Azure/azure-sdk-for-net/pull/36027

**Comment by mumby0168** [comment]
> Supporting Resource should be coordinated with other languages as well, and need some spec/mapping defined before implementing.
> 
> See previous PR which also details the need for design first : #36027

Hi, who is this sat with at the moment is this within Microsoft or in the wider OTEL community?

Is there an option to wrap this in an experimental feature or via configuration potentially so people can opt in at there own will?

Thanks,
Billy

**Comment by mumby0168** [comment]
> This is a pure Microsoft/Azure Monitor decision, nothing to do with OTel community.

Is this on-going and due anytime soon, or anything that can be done to get an ETA?

**Comment by cijothomas** [comment]
> > This is a pure Microsoft/Azure Monitor decision, nothing to do with OTel community.
> 
> Is this on-going and due anytime soon, or anything that can be done to get an ETA?

@mattmccleary Is there an ETA we can provide?

**Comment by mattmccleary** [comment]
> > > This is a pure Microsoft/Azure Monitor decision, nothing to do with OTel community.
> > 
> > 
> > Is this on-going and due anytime soon, or anything that can be done to get an ETA?
> 
> @mattmccleary Is there an ETA we can provide?

No dates yet, it's on the agenda to discuss w/ our backend team to ensure we are aligned w/ upcoming changes to how resource metadata is stored in Log Analytics and used to power experiences in Azure Monitor.
FYI - @OsvaldoRosado

**Pull request closed without merging**
