### PR TITLE
Add Azure Batch C# client (autogenerated, tooling, testing, and handcrafted helpers)

### PR DESCRIPTION
**Pull request by matthchr**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matthchr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (matthchr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by matthchr** [comment]
@hovsepm CI will fail unless Dev14 is enabled for the Jenkins build I think

**Comment by matthchr** [comment]
This change is really large, but I did change some stuff in your build infrastructure (it's really minor but you should review it).  Check out these commits to see it:

"Fix build issue related to missing documentation file"
"Make build.proj include test folders recursively"

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Pull request merged**
