### PR TITLE
[ServiceBus] Fix AadTokenProvider audience to ServiceBusAudience constant

### PR DESCRIPTION
**Pull request by bainian12345**
Fix AadTokenProvider audience to ServiceBusAudience constant instead of taking the input from user.

### CODE REVIEW

**Review by serkantkaraca — CHANGES_REQUESTED** [review]
:clock1:

**Review by serkantkaraca — APPROVED** [review]
:shipit:

**Review by jsquire — APPROVED** [review]

**Comment by pakrym** [comment]
What was this merged with checks failing?

**Comment by jsquire** [comment]
Apologies;  that's on me.  I was asked to merge (due to lack of permissions for others)  and did so based on the request without doing due diligence.  I should have caught that.

**Pull request merged**
