### PR TITLE
Added OpenAIClient constructors that accept an end point uri and API Key

### PR DESCRIPTION
**Pull request by nsxdavid**
This change allows for using a specified non-Azure endpoint when constructing an OpenAIClient.  This was previously not possible.

The use-case is for alternative OpenAI uris, for example test or alternate API end points, and to allow use of other OpenAI-compatible endpoints (for example: Groq).

The existing set of constructors for the OpenAiClient do not contemplate, nor allow, specifying a uri end point while also using a non-Azure service.  And because certain internal states (like _isConfiguredForAzureOpenAI) are managed by the constructors there exists no workaround either.

These changes are minor, merely wrapping other constructors and setting this one internal state appropriately.

No tests were created because none of the OpenAiClient constructors have explicit tests, and the framework developed for testing these services does not contemplate this scenario in a way that could be easily injected. Only the idea of an Azure and a hard-coded (in the SDK) end point for Non-Azure clients is supported.  This presumption runs deep in the base test mechanisms, and I wasn't able to find even a hacky way to get it in there that felt reasonable.

All existing tests pass with this change. and these two new constructors work fine tested externally (for what that is worth).

### CODE REVIEW

**Comment by nsxdavid** [comment]
@microsoft-github-policy-service agree

**Comment by AshD** [comment]
Thanks @nsxdavid Once this is a part of the library. I can remove my hacks to get non Open AI endpoints to work with this library :-)

Does Groq work with this library when streaming the data? Non streaming worked for me.

**Review by nsxdavid — COMMENTED** [review]
@AshD I've not tried streaming yet myself, but like most AI services, I suspect their OpenAI compatibility layer is up to the task.  I will note that one thing you still can't do is make a connection to an API that does not require authentication.  A good example of this is running a local LLM like ollama.  I might look into this as well, if this PR is accepted.

**Comment by koteus** [comment]
Looks like `this._isConfiguredForAzureOpenAI` is no longer in the codebase and OpenAIClient itself is replaced by the one from `OpenAI` package, which seems to be the official dotnet implementation, it is currently preprelease (https://github.com/openai/openai-dotnet/blob/OpenAI_2.0.0-beta.3/src/Custom/OpenAIClient.cs).

I am using Microsoft's Semantic Kernel framework which uses this Azure SDK and I want to specify a different OpenAI compatible server which lives on a custom URL.

```
kernelBuilder.AddOpenAIChatCompletion(
    serviceId: "llama-3-8b",
    modelId: config.GetValue<string>("MY_MODEL_LLAMA-3-8B")!,
    openAIClient: new OpenAIClient(
        endpoint: new Uri(config.GetValue<string>("MY_ENDPOINT")!),
        tokenCredential: new BearerTokenCredential(
            config.GetValue<string>("MY_BEARER_TOKEN")!
        ),
        options: new OpenAIClientOptions
        {
            Transport = new HttpClientTransport(httpClient),
        }
    )
);
```
and when using it the endpoints are all Azure specific. I was also thinking that this is because of `_isConfiguredForAzureOpenAI`. Could someone from maintainers comment on this please? Any ideas how we can use it in this case? Thanks!

**Pull request closed without merging**
