### PR TITLE
Make pipelines internal

### LINKED ISSUE #7825: Storage: Make the pipeline internal
Several of our `client.Pipeline` properties are `protected virtual` and we should switch that to `internal virtual`.

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes #7825

### CODE REVIEW

**Review by tg-msft — APPROVED** [review]

**Review by pakrym — APPROVED** [review]
LGTM

**Comment by JoshLove-msft** [comment]
@amnguye @seanmcc-msft I would like to merge this in by EOD Wednesday, if possible. Please if you can take a look, thanks!

**Review by amnguye — APPROVED** [review]

**Comment by pakrym** [comment]
Why the restart?

**Comment by tg-msft** [comment]
CheckEnforcer was hung (or taking an unreasonable amount of time).  Filed #7892 to help track these too.  _(Thanks for the reminder.)_

**Pull request merged**
