### PR TITLE
Adding Marketpalce service

### PR DESCRIPTION
**Pull request by olrakovs-zz**
Adding  azure marketpalce service to azure sdk

### CODE REVIEW

**Comment by olrakovs** [comment]
@isra-fel  and @erich-wang 
Can you please explain me how  do I trigger CI jobs?

**Review by isra-fel — APPROVED** [review]
LGTM

**Comment by olrakovs** [comment]
Hey @isra-fel ,
Did someone from CI and MGMT reviewed the PR?

**Comment by isra-fel** [comment]
Nope. It was just waiting for the checks to finish 😀

**Pull request merged**
