### PR TITLE
[Apim] Autorest based .NET client on 2018-01-01 version with Tests

### PR DESCRIPTION
**Pull request by solankisamir**
REST Spec: 
https://github.com/Azure/azure-rest-api-specs/pull/2292
https://github.com/Azure/azure-rest-api-specs/pull/2585

## Description
*** Resource Management APIs ***
- Added support for Basic Sku
- Added support for Intermediate Certificates
- Added support for creating MSI and KeyVault integration
- Added support for querying NetworkStatus endpoint

*** Management APIs ***
- Added support for creating an API by importing a WSDL document, containing multiple Service endpoints
- GetEntityTag API for all resources, to retrieve the ETag of the entity, to be used when Updating/Deleting the Entity.
- API support for API Revisions, API Releases and Api VersionSets
- API support for API Schemas.
- API support for Backend Reconnect.
- API support for Tag.
- API support for Diagnostics
- API support for Application insights Logger
- API support for managing Notifications, Notification Recipients and Notification Users.
- API support for Portal settings including SignIn, Signup and Delegation.
- API support for Importing Policies using Link
- Added support for Exporting Soap APIs in WSDL Format.
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@azuresdkci retest this please

**Comment by solankisamir** [comment]
@promoisha @KedarJoshi @darrelmiller can you take a look at your areas?

**Comment by shahabhijeet** [comment]
>     <AzureApiTag />

Missing API version.

---
Refers to: src/SDKs/ApiManagement/AzSdk.RP.props:4 in 17c608c. [](commit_id = 17c608c0fe3decf6d0f15f1af7c5d1c32b395f7a, deletion_comment = False)

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Please use generate.cmd to generate you SDK.
That will ensure all the needed meta data files are generated.
Once sdk is generated using generate.cmd, built it atleast once as below
msbuild build.proj /t:Build /p:Scope=SDKs\ApiManagement
This will add/update additional meta data file that are needed in order to get the PR accepted.
Also I see you have not bumped up your SDK version, you will have to do that in .csproj as well as AssemblyInfo.cs
Bump AssemblyVersion only when you have bumping Major version.

**Comment by solankisamir** [comment]
@shahabhijeet I had updated the *.csproj and AssemblyInfo file, but somehow GIT was not showing in diff.
You can check the *.csproj in psSdkJson6 and compare to 2018_01_01_client branch. We have bumped the major version to 4.0.0.0
Incorporated your comments, around extra metadata artifacts

**Pull request merged**
