### PR TITLE
Fix nullref exception when ScaledAssetDimensionsWrapper is null

### PR DESCRIPTION
**Pull request by RamonArguelles**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by RamonArguelles** [comment]
When a job has been submitted, but hasn't finished processing yet, ScaledAssetDimensionsWrapper is null. Same will be for a job that has finished, but failed before scaled asset dimensions could be calculated (for example, when the file format is invalid). 

ScaledAssetDimensionsWrapper is an internal property. When the customer tries to access the public property, ScaledAssetDimensions, the logic that runs in the code is:

        public System.Numerics.Vector3? ScaledAssetDimensions { get => ScaledAssetDimensionsWrapper == null ? null : ScaledAssetDimensionsWrapper; }

This code should be simply returning null. However, I suspect there is an optimization happening here, and the code is likely being optimized, even on Debug, to do this:

        public System.Numerics.Vector3? ScaledAssetDimensions { get => ScaledAssetDimensionsWrapper; }

I know this, because, in the current implementation, the implicit conversion operator from Azure.MixedReality.ObjectAnchors.Conversion.Models.Vector3 to System.Numerics.Vector3 is getting invoked:

        public static implicit operator System.Numerics.Vector3(Vector3 v) => v.data;

And this is causing a null-ref, since Vector3 v is null. The implicit conversion operator should NOT be called in this case. But is, and the only explanation I can give is my suggestion above: code is being optimized.

With my proposed fix, I'm forcing an explicit cast. This way, the compiler does not apply the optimization, and leaves the code as it was actually intended. The end result: the implicit operator is no longer invoked when the value is null, and it is invoked explicitly when the value isn't null.

I've tested this with our sample code, and we behave as expected in both scenarios now.

**Comment by RamonArguelles** [comment]
@craigktreasure

**Comment by craigktreasure** [comment]
If `ScaledAssetDimensionsWrapper` can be `null`, then we should mark it as nullable, right? That would better represent the value and allow you to instead call `HasValue` on it to reliably determine if it is `null` or not. The cast seems a bit dodgy to me.

**Review by craigktreasure — CHANGES_REQUESTED** [review]
If `ScaledAssetDimensionsWrapper` can be `null`, then we should mark it as nullable, right? That would better represent the value and allow you to instead call `HasValue` on it to reliably determine if it is `null` or not. The cast seems a bit dodgy to me.

**Comment by craigktreasure** [comment]
> If `ScaledAssetDimensionsWrapper` can be `null`, then we should mark it as nullable, right? That would better represent the value and allow you to instead call `HasValue` on it to reliably determine if it is `null` or not. The cast seems a bit dodgy to me.

Talked offline. I've confused the model `Vector3` with `System.Numerics.Vector3`. The model `Vector3` type has an implicit converter.

Should we instead make the converter explicit rather than implicit?

**Review by craigktreasure — APPROVED** [review]

**Pull request merged**
