### PR TITLE
Fix some Cognitive Language test errors

### PR DESCRIPTION
**Pull request by heaths**
Fixes errors introduced in #35228

### CODE REVIEW

**Comment by heaths** [comment]
@annelo-msft @KrzysztofCwalina this is a good example of what not having models might lead to. In part, though, it's because we don't validate inputs for our test framework and I had a typo I copied/pasted in several tests. The other issue was that an object was nested one level too deep - all things that models over anonymous types or dynamic types would've prevented.

**Review by annelo-msft — APPROVED** [review]
Thanks, @heaths, it's a good call-out, and I think a known risk of hand-authoring JSON (i.e. not using compiled model types) using any method.

I'm curious, did these tests pass before?  How did you discover the issue?

**Comment by heaths** [comment]
> Thanks, @heaths, it's a good call-out, and I think a known risk of hand-authoring JSON (i.e. not using compiled model types) using any method.
> 
> I'm curious, did these tests pass before? How did you discover the issue?

The recorded tests pass because we don't validate requests - only responses. The live tests failed because I missed an "e" on the end of `projectName` and misplaced the `task` object one level too deep on another request.

**Review by pallavit — APPROVED** [review]

**Comment by annelo-msft** [comment]
> The recorded tests pass because we don't validate requests - only responses. The live tests failed because I missed an "e" on the end of `projectName` and misplaced the `task` object one level too deep on another request.

That's good feedback.  We may want to recommend in our docs that end-to-end testing is a best practice to avoid this kind of error.  I'll make a note on the docs PR.

**Comment by heaths** [comment]
> That's good feedback. We may want to recommend in our docs that end-to-end testing is a best practice to avoid this kind of error. I'll make a note on the docs PR.

We don't currently recommend they have end-to-end testing? Or do you mean that they run live tests prior to submitting initial tests? To record they would've had to. This is a case where we don't check the request like we do the responses. Perhaps we could by recording our own byte count for a quick test and drill into body matching for requests. /cc @JoshLove-msft @christothes

**Comment by JoshLove-msft** [comment]
> Perhaps we could by recording our own byte count for a quick test and drill into body matching for requests. /cc @JoshLove-msft @christothes

Can you clarify why we are not matching requests here? Is it because it is disabled for this specific library? Request body matching is on by default.

**Comment by JoshLove-msft** [comment]
> > Perhaps we could by recording our own byte count for a quick test and drill into body matching for requests. /cc @JoshLove-msft @christothes
> 
> Can you clarify why we are not matching requests here? Is it because it is disabled for this specific library? Request body matching is on by default.

Here is the [recommended workaround](https://github.com/Azure/azure-sdk-for-net/issues/22219#issuecomment-1267307531) - we should probably add this to the Test Framework docs.

**Pull request merged**
