### PR TITLE
Update to R4.5 RP standard

### PR DESCRIPTION
**Pull request by leonardbf**
This replaces the initial PR for this change https://github.com/Azure/azure-sdk-for-net/pull/6815.
It relates to the new swagger https://github.com/Azure/azure-rest-api-specs/tree/master/specification/netapp/resource-manager/Microsoft.NetApp/stable/2019-06-01.
The PR for the last swagger update https://github.com/Azure/azure-rest-api-specs/pull/6395 against which this SDK was generated.

### CODE REVIEW

**Comment by leonardbf** [comment]
@erich-wang I hope this is now correct.

**Comment by erich-wang** [comment]
@leonardbf, please
1. Please provide the swagger spec **PR** in Azure/azure-rest-api-specs so that I could understand what's in PR and whether it is merged
2. Not sure how did you generate source code in this PR, the recommended way is listed as step vi in [process document](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#build)

**Comment by leonardbf** [comment]
> @leonardbf, please
> 
> 1. Please provide the swagger spec **PR** in Azure/azure-rest-api-specs so that I could understand what's in PR and whether it is merged
> 2. Not sure how did you generate source code in this PR, the recommended way is listed as step vi in [process document](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#build)

1. The swagger PR is here https://github.com/Azure/azure-rest-api-specs/pull/6395.
2. The code was generated using the generate.ps1 file. Of course that was against the old structure and the code files had to then be moved to the new directory.

**Comment by erich-wang** [comment]
@leonardbf 
1. Please follow **step 8** in [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-directory-structure-and-sdk-generation). It will really help us a lot to review your PR if it contains sdk\_metadata\<rpName>.txt which is generated by generate.ps1

2. Please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#creating-pr)

> If **ExcludeFromTest** and **ExcludeFromBuild** are present in your test csproj, make sure their value are false, otherwise you tests won't be run from CI

**Comment by leonardbf** [comment]
> @leonardbf
> 
> 1. Please follow **step 8** in [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-directory-structure-and-sdk-generation). It will really help us a lot to review your PR if it contains sdk_metadata<rpName>.txt which is generated by generate.ps1
> 2. Please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#creating-pr)
> 
> > If **ExcludeFromTest** and **ExcludeFromBuild** are present in your test csproj, make sure their value are false, otherwise you tests won't be run from CI

@erich-wang 
I've been trying ensure compliance with the steps of the process you linked but I'm having some issues (Note that I have performed the "git clean -xdf" and pulled from upstream as described in the doc)
1) Primarily I'd like to be able to rerun the generate.ps1 but I see "Could not find root for output directory since script is not run from SDK repo, please provide this using the -SdkRepoPath parameter". I've tried using both this param and SdkGenerationDirectory which I've seen elsewhere but always get "A parameter cannot be found that matches parameter name"
2) I've tried rebuilding both the solution but get messages for every service that asset files are not found. It recommends a nuget restore. I tried this on my own NetApp service but it says everything is up to date. Not sure how I would do this for all services.
3) I see warning messages during the build and within VS for my solution that System.Runtime is not present. When I try to add it, it complains that it cannot be found.

Can you help with these, most importantly the first, so I can update the PR with the metadata.
Thanks.

**Comment by erich-wang** [comment]
> > @leonardbf
> > 
> > 1. Please follow **step 8** in [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-directory-structure-and-sdk-generation). It will really help us a lot to review your PR if it contains sdk_metadata.txt which is generated by generate.ps1
> > 2. Please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#creating-pr)
> > 
> > > If **ExcludeFromTest** and **ExcludeFromBuild** are present in your test csproj, make sure their value are false, otherwise you tests won't be run from CI
> 
> @erich-wang
> I've been trying ensure compliance with the steps of the process you linked but I'm having some issues (Note that I have performed the "git clean -xdf" and pulled from upstream as described in the doc)
> 
> 1. Primarily I'd like to be able to rerun the generate.ps1 but I see "Could not find root for output directory since script is not run from SDK repo, please provide this using the -SdkRepoPath parameter". I've tried using both this param and SdkGenerationDirectory which I've seen elsewhere but always get "A parameter cannot be found that matches parameter name"
> 2. I've tried rebuilding both the solution but get messages for every service that asset files are not found. It recommends a nuget restore. I tried this on my own NetApp service but it says everything is up to date. Not sure how I would do this for all services.
> 3. I see warning messages during the build and within VS for my solution that System.Runtime is not present. When I try to add it, it complains that it cannot be found.
> 
> Can you help with these, most importantly the first, so I can update the PR with the metadata.
> Thanks.

@leonardbf , the error you mentioned should already been fixed a few days ago. If the issue remains, please 
1. Delete folder %userprofile%Documents\WindowsPowerShell\Modules\CodeGenerationModules 
2. run **msbuild build.proj /t:Util /p:UtilityName=InstallPsModules**
3. Close all PowerShell and start new PowerShell console, then run generate.ps1
Please let me know if the issue remains

**Comment by leonardbf** [comment]
@erich-wang I've closed this PR and created a new clean one with all the changes https://github.com/Azure/azure-sdk-for-net/pull/6851.

**Pull request closed without merging**
