### PR TITLE
Attempt fix GetMetrics_ReturnsExpectedResult failing in live tests

### PR DESCRIPTION
**Pull request by amnguye**
Our live tests started failing across the board for the `GetMetrics_ReturnsExpectedResult` tests after this PR change was made.

https://github.com/Azure/azure-sdk-for-net/pull/34193

Still trying to figure if there's a bug in the QueueMetricsProvider when it was moved out of QueueListener or the tests itself.

### CODE REVIEW

**Review by seanmcc-msft — APPROVED** [review]

**Comment by amnguye** [comment]
The failures on the live test pipelines are unrelated to this PR.

**Pull request merged**
