### PR TITLE
Clean up repository resources

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Clean up remaining repository resources.

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]
Looks good just find the correct merge order for eng/common.

**Comment by chidozieononiwu** [comment]
@tg-msft can do you know why this [failure ](https://dev.azure.com/azure-sdk/public/_build/results?buildId=450461&view=logs&j=b08a78d6-c9ce-53c1-53b1-9a5d436f78f6&t=756e146f-7609-5d03-4e3a-e5bd2f3174ad&l=15579)occurred

**Comment by tg-msft** [comment]
Yes, it's a new regression tracked by #13221.

**Pull request merged**
