### PR TITLE
Merge Management.Sql backport branch into mainline branch

### PR DESCRIPTION
**Pull request by jaredmoo**
## Description
We recently added support for SQL Managed Instance, Managed Instance database, and Managed Instance failover groups to the mainline psSdkJson6 branch in PR #4244 and released as 1.15.0-preview. 

We then realised that we wanted to backport this change to before the 1.14.0-preview breaking changes, so in PR #4257 we cherry picked these changes into the new backport branch 'ManagementSql-CloudLifter' and released as 1.13.1-preview.

In order to reconcile these cherry picks and keep history healthy moving forward, we need to merge from the backport branch (ManagementSql-CloudLifter) into the mainline branch (psSdkJson6). This PR does that. There are no files changed, just merged from ManagementSql-CloudLifter into psSdkJson6 and then resolved conflicts.

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by jaredmoo** [comment]
@ziwa-msft and @shahabhijeet FYI. This is not urgent (does not block any release).

**Comment by shahabhijeet** [comment]
This PR has 0 files

**Comment by jaredmoo** [comment]
There are no files changed, but there are merge conflicts that were resolved. All of them were resolved by 'keep ours', i.e. keep the psSdkJson6 change (not SqlMgmt-CloudLifter).

**Comment by shahabhijeet** [comment]
I still don't know why you would like to merge it. What happens if you don't merge it?
because you are honoring all the files from latest psSdkJson6, so does it really matter if you are mege?

**Comment by jaredmoo** [comment]
Cherry picking in general is bad (Raymond Chen wrote a fascinating series of articles about it: https://blogs.msdn.microsoft.com/oldnewthing/20180323-01/?p=98325 ). There will soon be another PR for short-term retention going into SqlMgmt-CloudLifter branch, and when that PR lands we want to merge it into psSdkJson6 so that both branches have the same changes for the new feature. Merging this now resolved conflicts and will make that future merge easier. 

If you want, we can hold off on this for now until that short term retention change lands in SqlMgmt-CloudLifter.

**Comment by shahabhijeet** [comment]
yes let's hold off on this one.

**Comment by jaredmoo** [comment]
No problem.

**Pull request closed without merging**
