### PR TITLE
Updating the Datafactory SDK from swagger repo, preparing release

### PR DESCRIPTION
**Pull request by hvermis**

### CODE REVIEW

**Comment by wenbof** [comment]
@hvermis there is one change(sent out for more than one week now) not checked in which needs to be in the SDK by end of this month.

**Comment by hvermis** [comment]
@wenbof  Let's do that in a separate PR to minimize the risk of not making it.

**Comment by wenbof** [comment]
@hvermis Hopefully we can make that by end of this month. it is a hard date. Thanks.

**Comment by erich-wang** [comment]
@hvermis , could you please share swagger spec PR link related to this change? I need to understand what's change in the spec PR and whether it is merged?

**Review by HaoQian-MS — APPROVED** [review]

**Review by zhangyd2015 — APPROVED** [review]

**Comment by hvermis** [comment]
@erich-wang  I generated the .Net code from the public repo url, ADF readme file. So this code corresponds exactly to whatever is merged in swagger repo. Here are the PRs in swagger repo:
https://github.com/Azure/azure-rest-api-specs/pull/6631
https://github.com/Azure/azure-rest-api-specs/pull/6548
https://github.com/Azure/azure-rest-api-specs/pull/6607
https://github.com/Azure/azure-rest-api-specs/pull/6568

**Review by erich-wang — APPROVED** [review]

**Review by TinaHu1 — APPROVED** [review]

**Review by wenbof-zz — APPROVED** [review]

**Review by xiaoyingQQ — APPROVED** [review]

**Review by davidzhaoyue — APPROVED** [review]

**Pull request merged**
