### PR TITLE
Avoid throwing exception when  deserializing from empty queues (Issue 3709)

### PR DESCRIPTION
**Pull request by adibalsa**
Proposed fix for issue: https://github.com/Azure/azure-sdk-for-net/issues/3709

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by hovsepm** [comment]
@azuresdkci test this please.

**Comment by shahabhijeet** [comment]
@adibalsa we are currently not accepting any PRs for Hyak based SDK.
New AutoRest based SDK will be out in next couple of weeks.
Closing it for now. If you feel strongly please open the same PR or an issue clarifying the need to do this prior to new SDK being released.

**Review by wawon-msft — COMMENTED** [review]
Is there any reason why we cannot use something like this.stream.length?

**Comment by adibalsa** [comment]
Hi @shahabhijeet, will new AutoRest based SDK include the fix ? 
I made the fix because I'm implementing the solution described at http://anthonychu.ca/post/event-hubs-archive-azure-data-lake-analytics-usql/. It's based on calling the Avro Extractor from a USQL statement, and that gets exception when the queue is empty. This beahaviour break the extraction process of events from Data Lake Store and  it's not acceptable.
I'm using now a custom build of the SDK including the fix and it works as expected.  I'm ok with that for now, but I need you to include the fix in the next releases.
Let me Know if you need help to port the fix to the new AutoRest based SDK, I'm willing to contribute. 
@wawon-msft  , I think that explains why I can't use this.stream.length (I'm calling the extractor from a USQL stetement).

**Pull request closed without merging**
