### PR TITLE
Elgrady az security microsoft.security sdk fix generation (track1)

### PR DESCRIPTION
**Pull request by eliagrady**
# Microsoft.Security SDK fixes

WIP, depends on PR: https://github.com/Azure/azure-rest-api-specs/pull/24938

This PR should be (hopefully) the last 'track1' SDK release before Microsoft.Security will be migrating to track2 SDKs.

### CODE REVIEW

**Comment by ArthurMa1978** [comment]
@eliagrady The Track 1 SDK will no longer be supported in the near future. You can still modify the Track 1 code for Powershell purposes, but you cannot publish any Track 1 packages at this time.

**Comment by eliagrady** [comment]
> @eliagrady The Track 1 SDK will no longer be supported in the near future. You can still modify the Track 1 code for Powershell purposes, but you cannot publish any Track 1 packages at this time.

Yes, we're interested in getting one last SDK release before the deadline for releasing Track1 SDK and shifting our focus towards Track2 - the Track1 SDK has not been updated for too long.

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by ArthurMa1978** [comment]
@eliagrady why did you mark this pr as `Do Not Merge` ?

**Comment by eliagrady** [comment]
> @eliagrady Elia Grady FTE why did you mark this pr as `Do Not Merge` ?

I'm working on refactoring and completing a full sweep of tests to the APIs listed in this SDK - many tests are either missing, stale, incorrect or simply written in a synchronous manner. Once I cover all APIs with proper tests and the quality of it is sufficient I will remove the label and update the PR with tests and recorded sessions for the SDK to actually be usable and useful to customers to consume.

Until then - this is incomplete work.

**Review by archerzz — APPROVED** [review]

**Comment by archerzz** [comment]
@eliagrady This PR is still tagged as `Do Not Merge`. Is it completed now?

**Comment by eliagrady** [comment]
> @eliagrady This PR is still tagged as `Do Not Merge`. Is it completed now?

Unfortunately we did not get clearance for releasing an update to our track1 SDK version. 
We'll be working towards releasing a track2 SDK version instead.

**Pull request closed without merging**
