### PR TITLE
Event Grid: Regenerate new .NET SDK and record tests for new GA service API version 2020-06-01

### PR DESCRIPTION
**Pull request by ahamad-MS**
## Event Grid .Net SDK 6.0.0 (2020-06)
- Add support to new GA service API version 2020-06-01.
- The new GA'ed features include:
	* Event delivery schema,
	* Input mapping,
	* Custom input schema event delivery schema,
	* Cloud event V10 schema,
	* Service bus topic as destination,
	* Azure function as destination,
	* Webhook batching,
	* Secure webhook (AAD support),
        * ImmutableId support, IpFiltering, and
        * Private Link.
- Add Changelog.md with latest nuget packages history and link it in the release notes. This is to address the suggestion per issue https://github.com/Azure/azure-sdk-for-net/issues/12252

### CODE REVIEW

**Comment by ahamad-MS** [comment]
Hello @isra-fel , @erich-wang .l Kindly help merging this PR. thanks

**Review by isra-fel — COMMENTED** [review]
Hi @ahamad-MS , I noticed that this PR deleted a lot of code. Just want to confirm that those belong to the "additional features that are still in preview" you mentioned in the release nots, correct?

Besides, when generating from a new api version, please update the api tags in `AzSdk.RP.props`.
And the versions in `AssemblyInfo.cs` as well.

Thanks

**Comment by ahamad-MS** [comment]
Thanks @isra-fel  .. Yes, all the deleted code is related to features that are still in review..

api version is updated in assymblyinfo and az.Sdk files. 

thanks

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
