### PR TITLE
Adds ConfigureAwait(false) in SDK Common Auth

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
@nemakam I have another treasure for you 🤣

**Comment by Ivan-Abragimovich** [comment]
Guys, does anybody have ETA when this can be merged?

**Comment by nemakam** [comment]
@kurtzeborn @weshaggard @AlexGhiondea - This PR hasn't been triaged yet?

**Comment by nemakam** [comment]
+@loarabia -> Any idea about the PR triage?

**Comment by Ivan-Abragimovich** [comment]
Gentlemen, please, could someone review this PR? 
It so annoying to investigate deadlocks

**Review by AlexGhiondea — APPROVED** [review]
Are there other places that need this?

**Comment by danielmarbach** [comment]
I can check on the weekend. Last time I looked in the SDK these where the only places but the situation could have changed

**Comment by danielmarbach** [comment]
Nonetheless I hope this question doesn't prevent this PR from being merged

**Comment by Ivan-Abragimovich** [comment]
I apologize for my ignorance, but now I see that merging of this PR is blocked,
because of "The base branch restricts merging to authorized users."

Could please someone explain what does that mean?

P.S.
Special thanks @AlexGhiondea for review!

**Comment by AlexGhiondea** [comment]
Merged.

**Comment by danielmarbach** [comment]
@AlexGhiondea I sent in https://github.com/Azure/azure-sdk-for-net/pull/8059

**Pull request merged**
