### PR TITLE
[Pipeline Test] Update generate code for check

### PR DESCRIPTION
**Pull request by HarveyLink**

### CODE REVIEW

**Comment by jsquire** [comment]
Hi @HarveyLink.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by HarveyLink** [comment]
> Hi @HarveyLink. There hasn't been recent engagement on this PR. Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

Hi @jsquire ,the PR is still a active work, we are testing on the MGMT Track 1 pipeline code-gen force check. Thank you for the kindly reminding.

**Comment by jsquire** [comment]
Hi @HarveyLink.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream by removing the `no-recent-activity` label?  Otherwise, we'll close this out in 7 days.

**Pull request closed without merging**
