### PR TITLE
Upgrade DotNetCoreInstaller to UseDotNet

### PR DESCRIPTION
**Pull request by chidozieononiwu**

### CODE REVIEW

**Review by heaths — APPROVED** [review]
Per @weshaggard should the Framework version also be updated, or even just be set to 2.1.x to grab the latest patch version (if not too nondeterministic).

**Comment by weshaggard** [comment]
>Per @weshaggard should the Framework version also be updated, or even just be set to 2.1.x to grab the latest patch version (if not too nondeterministic).

@chidozieononiwu can you please file an issue to update the runtime version.

**Comment by chidozieononiwu** [comment]
> > Per @weshaggard
> >             
> >             Wes Haggard
> >             FTE should the Framework version also be updated, or even just be set to 2.1.x to grab the latest patch version (if not too nondeterministic).
> 
> @chidozieononiwu Dozie Ononiwu FTE can you please file an issue to update the runtime version.

What should it be updated to? The latest?

**Comment by weshaggard** [comment]
Yes we should update it to the latest runtime that is on our hosted images.

**Comment by weshaggard** [comment]
@chidozieononiwu actually in the issue I'd like to ask the question of @AlexGhiondea to see if we need to move past netcore 2.1 or stay there and add a netcore 3.x test leg as well.

**Comment by chidozieononiwu** [comment]
> netcore 2.1 or stay there and add a netcore 3.x test leg as well.

Issue created [here](https://github.com/Azure/azure-sdk-for-net/issues/11014)

**Pull request merged**
