### PR TITLE
Release to remove JSON.NET ver cap imposed by Key Vault

### LINKED ISSUE #3003: Update Newtonsoft.Json version in Microsoft.Azure.KeyVault.WebKey
Not sure if this would be considered as a duplicate of #3002 but we are running into an issue with the Microsoft.Azure.KeyVault package. The dependency Microsoft.Azure.KeyVault.WebKey dependency has restricted the Newtonsoft.Json dependency to be < 10.0.0 and we have updated our stack in ASP.NET Core to 10.0.1. We consume this package so I'm wondering if the dependency will be updated soon?

cc @Eilon

### PR DESCRIPTION
**Pull request by RandalliLama**
## Description
ASP.NET requires a version of JSON.NET greater than the one allowed by the nuget dependency declaration for the Microsoft.Azure.KeyVault.WebKey assembly.  It appears that the port to VS2017 has already removed that restriction.  The change in this PR is simply to up the version of that assembly and the root Key Vault assembly, Microsoft.Azure.KeyVault.WebKey, in order to release new versions of these assemblies and nuget packages that do not have a cap on the version of the JSON.NET dependency.

fixes #3003 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x ] Title of the pull request is clear and informative.
- [ x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by fhokholdMSFT — APPROVED** [review]

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@azuresdkci add to whitelist

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Pull request merged**
