### PR TITLE
add generation1-convenience-client flag

### PR DESCRIPTION
**Pull request by chunyu3**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

We will set 'data-plane' as autorest.csharp codegen default target. and will add new tag 'generation1-convenience-client' tag for the HLC Client Library.

In order to upgrade to the new autorest.csharp which will use 'data-plane' as default target, we need to migrate current SDKs in azure-sdk-for-net step by step as following:

1. Add new flag 'generation1-convenience-client' to all HLC SDKs
2. Merge change in autorest.csharp https://github.com/Azure/autorest.csharp/pull/2146
3. Upgrade autorest.csharp version and Remove old flag (data-plane) from the DPG SDKs

This pull request is #1

### CODE REVIEW

**Review by lirenhe — COMMENTED** [review]
Could you provide some description on why adding 'generation1-convenience-client'?
I saw a couple of people are added for reviewer and they may lack the context of this change.

**Comment by chunyu3** [comment]
We will set 'data-plane' as autorest.csharp codegen default tag. and will add new tag 'generation1-convenience-client' tag for the HLC Client Library. 
This pull request is to add the new flag for all the .NET HLC Client Library package.

After the Pull request is merged, we will upgrade the autorest.csharp version which will add 'data-plane' as default tag. That is, if no flag(azure-arm or generation1-convenience-client) is set, the autorest.csharp will generate DPG library.

**Comment by chunyu3** [comment]
The check 'net-synapse -ci' failed because the 'Microsoft.Azure.Synapse' package has invalid CHANGELOG.md file. And the issue is not caused by the pull request.

**Review by lirenhe — APPROVED** [review]

**Comment by heaths** [comment]
@chunyu3 can you describe what this new setting does? Ideally, it would make a nice PR description as opposed to the default PR template meant more for external contributors to read and replace.

**Comment by lirenhe** [comment]
@heaths, i see the explaination of this PR in the description, do you still have question related to the new settings?

**Pull request merged**
