### PR TITLE
Add Directory.Build.Props to TextAnalytics.Legacy

### PR DESCRIPTION
**Pull request by chidozieononiwu**
- Mark Azure.AI.TextAnalytics.Legacy.Shared as a IsTestSupportProject

### CODE REVIEW

**Review by jsquire — APPROVED** [review]

**Review by maririos — APPROVED** [review]
Thank you!

**Comment by maririos** [comment]
@chidozieononiwu  The CI failures
```
eng\service.proj(42,5): Error : No Projects found with patttern [..\sdk\textanalytics/Azure.AI.TextAnalytics.Legacy\**\*.csproj], please make sure you have passed in the correct ServiceDirectory.
```

Started after we made Azure.AI.TextAnalytics.Legacy an artifact here https://github.com/Azure/azure-sdk-for-net/pull/28863 and the reason was so we could reject that project from the publish step on the release pipeline.
Now that we released, is there a better way to handle this situation?

**Comment by chidozieononiwu** [comment]
> @chidozieononiwu The CI failures
> 
> ```
> eng\service.proj(42,5): Error : No Projects found with patttern [..\sdk\textanalytics/Azure.AI.TextAnalytics.Legacy\**\*.csproj], please make sure you have passed in the correct ServiceDirectory.
> ```
> 
> Started after we made Azure.AI.TextAnalytics.Legacy an artifact here #28863 and the reason was so we could reject that project from the publish step on the release pipeline. Now that we released, is there a better way to handle this situation?

I think we can remove this from ci.yml for now.

**Comment by maririos** [comment]
> I think we can remove this from ci.yml for now.

For now it will be ok, but next time the package needs to be released, the team will face the same problem where they need to disable `Azure.AI.TextAnalytics.Legacy` from shipping

**Comment by chidozieononiwu** [comment]
> > I think we can remove this from ci.yml for now.
> 
> For now it will be ok, but next time the package needs to be released, the team will face the same problem where they need to disable `Azure.AI.TextAnalytics.Legacy` from shipping

Thats what this change is about. `Azure.AI.TextAnalytics.Legacy` will no longer be included in the build.

**Comment by jsquire** [comment]
I verified this in the release pipeline after this was merged.    It looks like we're all fixed up.  The TA package was the only one created and it has only the expected build output.    https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1590344&view=results

Thanks @chidozieononiwu!

**Pull request merged**
