### PR TITLE
Fix Anchor github.io landing page anchor links

### PR DESCRIPTION
**Pull request by scbedd**
@mikeharder pointed out that on [this page](https://azure.github.io/azure-sdk-for-net/) the anchor links do not work properly.

image

This PR should still work on github, but also react properly in html rendering.

### CODE REVIEW

**Review by mikeharder — APPROVED** [review]

**Comment by mikeharder** [comment]
@scbedd: Same issue in Java:

https://azure.github.io/azure-sdk-for-java

Maybe we need to check all anchors across all our docs?

**Comment by weshaggard** [comment]
cc @sima-zhu 

Is this just a github.io anchor problem? I know that when @sima-zhu was looking at the link stuff some I believe we figured out that the anchors don't always translate from the MD to all the places we convert them to html.

**Comment by sima-zhu** [comment]
@weshaggard I believe this is the right fix for azure.github.io page. 
My testing is based on index.html in blob. 
Like the archor link in this page: https://azuresdkdocs.blob.core.windows.net/$web/java/azure-search-documents/11.2.0-beta.1/overview-summary.html#Create-a-SearchIndexClient

These two pages has different way of converting md to html.
azure.github.io has `id` associate with section which anchor link is able to target.
image

However, the blob page does not have `id` with the section, which failed to retrieve the anchor link
image

**Comment by mikeharder** [comment]
In plain HTML, anchor tags are case-sensitive.  github.com uses JavaScript to make anchor tags be case-insensitive, but other sites like github.io do not.  So content hosted outside of github.com needs to either:

1. Ensure the same casing is used for source and target anchors
2. Add JavaScript to make case-insensitive links work correctly

I prefer option 1 since it's simpler and better aligns with the HTML spec.

**Comment by sima-zhu** [comment]
The link verification script is able to check the case for anchor link, but it only fixes partial problem as the blob page is still having the lost link problem.

We have an issue related to standardized the md to html conversion. I think that's the long-term solution of fixing the problem. 
https://github.com/Azure/azure-sdk-tools/issues/929

**Comment by mikeharder** [comment]
I think the most robust solution might be to insert our own anchors rather than relying on the ones auto-generated from header text:

https://stackoverflow.com/a/7335259

So anytime we wanted to link to a section, we would manually insert an anchor point in the section heading, then link to whatever anchor name we chose.

**Comment by scbedd** [comment]
@mikeharder it probably would be more robust, but it's also a bit finicky. We'll be asking devs to submit PRs with random anchor tags in them. It seems like if we're going to insist on additional specific work, it'd be easier to just ask people to lower-case the anchors right?

**Comment by mikeharder** [comment]
> @mikeharder it probably would be more robust, but it's also a bit finicky. We'll be asking devs to submit PRs with random anchor tags in them. It seems like if we're going to insist on additional specific work, it'd be easier to just ask people to lower-case the anchors right?

I think it depends on how the markdown is converted to HTML and what we want to rely on.  If we are OK relying on the GitHub auto-generated anchors, then yes using lower-case when targeting the anchor is the simplest solution.

But I believe these auto-generated anchors are specific to GitHub markdown.  If we wanted a solution to work in all flavors of markdown, we would need to insert our own anchors.

**Comment by sima-zhu** [comment]
@mikeharder I tested the user-defined tag `<a name="foo">`, and it is actually working for index.html on blob page as well. If we want to force user to use the html anchor link, we'd better to update the guideline and have link-verification script to check against the anchor links.

**Comment by weshaggard** [comment]
@sima-zhu before we do that we should look to see if docfx, which is what we use to convert the MD to html has any options to generate the anchors or not.

**Comment by sima-zhu** [comment]
> @sima-zhu before we do that we should look to see if docfx, which is what we use to convert the MD to html has any options to generate the anchors or not.

Sure, I believe docfx is doing the right thing, and we only need to take care of case sensitive. Java is using python script to convert md to html, which needs to investigate whether we can use docfx to replace it.

**Comment by scbedd** [comment]
Hey Folks, this PR doesn't do any harm and solves the issue for .NET right now. Please continue discussion in this issue that I just filed: https://github.com/Azure/azure-sdk/issues/1843

**Pull request merged**
