### PR TITLE
enable healthcare samples

### PR DESCRIPTION
**Pull request by mshaban-msft**
solves #21471

### CODE REVIEW

**Comment by mohamedshabanofficial** [comment]
@maririos 
do i need to run tests locally to get recorded tests for the samples?

**Comment by maririos** [comment]
@mohamedshabanofficial 

>do i need to run tests locally to get recorded tests for the samples?

No. Although our samples run as tests, we don't record them because they are meant to be run only in `live` environments or scenarios. So for example, only in our nightly builds. It happens thanks for this https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/tests/samples/Sample7_AnalyzeHealthcareEntitiesBatch.cs#L13

A way to test it locally is by setting an environment variable `AZURE_TEST_MODE:live`. Our you could use the CI to test it for you (although you can't debug).
I just queue a build that will ran the samples. Hopefully they will pass

**Review by maririos — APPROVED** [review]
Everything looks green, so I guess no point in having them disabled.
Thank you!

**Pull request merged**
