### PR TITLE
Remove unnecessary JsonConverter

### LINKED ISSUE #10441: Hide JsonConverter from EntityCategory
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/src/EntityCategory.cs#L16

### PR DESCRIPTION
**Pull request by maririos**
Fixes: https://github.com/Azure/azure-sdk-for-net/issues/10441

### CODE REVIEW

**Review by annelo-msft — APPROVED** [review]

**Comment by AlexanderSher** [comment]
What test verifies that `EntityCategory` serialization still works?

**Comment by maririos** [comment]
>What test verifies that EntityCategory serialization still works?

@AlexanderSher the [RecognizeEntitiesCategories ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/tests/TextAnalyticsClientLiveTests.cs#L1016)test

**Comment by AlexanderSher** [comment]
So it isn't really deserialized anywhere by itself, it is explicitly instantiated in `CategorizedEntity` constructor. If there are no other cases than this one, then LGTM.

**Comment by maririos** [comment]
Thanks Alexander!

**Pull request merged**
