### PR TITLE
Reset Sql version back to 1.37

### PR DESCRIPTION
**Pull request by jaredmoo**
The version should not have been changed to 2.0. There may be minor breaking changes between -preview versions.

### CODE REVIEW

**Comment by SanjaMalesevic** [comment]
Minor version is not upgraded here, it is the same as before. Should we upgrade this to 1.38?

**Comment by isra-fel** [comment]
Yeah you're right. It's a preview module, I guess it's fine to make breaking changes.
I'll merge this one now.
@SanjaMalesevic please submit another PR to bump up version for release. Thanks!

**Review by isra-fel — APPROVED** [review]

**Comment by SanjaMalesevic** [comment]
> Yeah you're right. It's a preview module, I guess it's fine to make breaking changes.
> I'll merge this one now.
> @SanjaMalesevic please submit another PR to bump up version for release. Thanks!

@isra-fel , should I create a new PR where Version will be updated to 1.38.0-preview?

**Comment by jaredmoo** [comment]
No, 1.37 is the correct version. See that https://www.nuget.org/packages/Microsoft.Azure.Management.Sql is currently at 1.36.

**Pull request merged**
