### PR TITLE
Update to R4 RP standard

### PR DESCRIPTION
**Pull request by leonardbf**
Correction to swagger error handler.
Addition of volume create from snapshot in swagger.
Removal of volume id as required parameter in snapshot creation.
Swagger PR https://github.com/Azure/azure-rest-api-specs/pull/5683
Internal ticket NFSAAS-2317

### CODE REVIEW

**Comment by leonardbf** [comment]
There is a validation pipeline failure which does not appear to be related to the PR changes. See https://dev.azure.com/azure-sdk/public/_build/results?buildId=27029. Some input on this would be useful. Thanks.

**Comment by dsgouda** [comment]
@leonardbf Please link the REST spec PR too

**Comment by dsgouda** [comment]
@weshaggard Please take a look at the failing test cases

**Comment by leonardbf** [comment]
Added swagger PR (https://github.com/Azure/azure-rest-api-specs/pull/5683) in the description.

**Review by dsgouda — APPROVED** [review]
LGTM pending CI passes

**Comment by weshaggard** [comment]
Known flaky test. See https://github.com/Azure/azure-sdk-for-net/issues/6056.

**Pull request merged**
