### PR TITLE
Generate .NET SDK against public swagger

### PR DESCRIPTION
**Pull request by arpit-gagneja**
# Description

We have checked in our public swagger, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dnsresolver/resource-manager/Microsoft.Network/preview/2020-04-01-preview/dnsresolver.json.

This PR is generating SDK against this public swagger. When this PR gets merged to feature branch, we want to take it forward to release branch for initial public release.

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by arpit-gagneja** [comment]
@Yao725 @markcowl: Looks like check-enforcer is running for a long time now. It's my first time creating a PR for this repo. Do I need to set up the CI pipeline first? 

To give reviewers more context, we have previously checked the code in the feature branch. Now with the public swagger released, we want to release the SDK for public preview. We are targetting March 04 release cutoff date. (https://github.com/Azure/azure-sdk-for-net/milestone/102) 

I am assuming that the action item on me is to make sure that the tests are passing. I will need to re-record tests as a couple of our resources have been changed in the public swagger. Please correct me here if there are more things.

**Comment by Yao725** [comment]
Hi @arpit-gagneja, I noticed that you generated track 1 SDK, but your team has never released the corresponding track 1 SDK, right? If not, I would suggest you to generate the track 2 SDK using the latest generator, because we are not accepting onboarding track 1 SDK for new service now.

**Comment by arpit-gagneja** [comment]
@Yao725: Thanks for the response! Can you please help me with the below questions?

- What's the difference between track 1 SDK and track 2 SDK? If you can provide me an example of track 2 SDK repo and the autorest version the repo used, that'd be great!
- I noticed you ran the CI pipeline but no job ran. Do I need to configure the CI myself?
- We are targeting March 4th deadline to get all of our changes in. Is there a process that we need to follow to get our changes in the next release other than the track 2 SDK changes you mentioned?

**Comment by Yao725** [comment]
Hi @arpit-gagneja 
1. For the difference between track 1 and track 2 SDK, you can refer to this [link](https://devblogs.microsoft.com/azure-sdk/introducing-the-new-azure-sdk-resource-management-libraries-for-net/). And the track 2 SDK is still in the azure-sdk-for-net repo, the folder in main branch that begins with the Azure.ResourceManager is track 2 mgmt. plane SDK, like sdk/compute/Azure.ResourceManager.Compute. And you can see the autorest version [here](https://github.com/Azure/azure-sdk-for-net/blob/40124cfe1659f3cbe8fb6c8a7a83ab1b0dd4b5dc/eng/Packages.Data.props#L154).
2. Yeah, for new service, you need provide the ci file.
3. You just need to generate the track 2 SDK, add the test and we will review the PR. After all of these are done, we can do the release. One more thing that need to be mentioned is, all of the packages depend on the Azure.ResourceManager package which we are still working on in the main branch, so I create a feature branch based on the previous release, you can follow these steps to onboard the new SDK:
- Fork the azure-sdk-for-net repo and clone the [feature branch](https://github.com/Azure/azure-sdk-for-net/tree/feature/mgmt-track2-dnsResolvers) to your local machine
- Read this readme [azure-sdk-for-net/eng/templates at main · Azure/azure-sdk-for-net (github.com)](https://github.com/Azure/azure-sdk-for-net/tree/main/eng/templates) to install the mgmt track 2 sdk template and generate corresponding template for your RP
- Replace the link of the required field in the autorest.md with a permalink to the exact version of the readme file in swagger repo
- Add these configuration to the generated autorest.md
```yaml
library-name: your serivice name

namespace: Azure.ResourceManager.ServiceName

clear-output-folder: true

skip-csproj: true

output-folder: Generated/

mgmt-debug:

    show-request-path: true

```
- Change to the azure-sdk-for-net/sdk/your service/Azure.ResourceManager.YourSerivce/src and run this command: dotnet build /t:GenerateCode to generate code
- Build the generated code, if success, please add the test case. You can see other track 2 SDK to figure out how to write test.
- Open a PR to merge the change into the feature branch.

**Comment by arpit-gagneja** [comment]
> Hi @arpit-gagneja
> 
> 1. For the difference between track 1 and track 2 SDK, you can refer to this [link](https://devblogs.microsoft.com/azure-sdk/introducing-the-new-azure-sdk-resource-management-libraries-for-net/). And the track 2 SDK is still in the azure-sdk-for-net repo, the folder in main branch that begins with the Azure.ResourceManager is track 2 mgmt. plane SDK, like sdk/compute/Azure.ResourceManager.Compute. And you can see the autorest version [here](https://github.com/Azure/azure-sdk-for-net/blob/40124cfe1659f3cbe8fb6c8a7a83ab1b0dd4b5dc/eng/Packages.Data.props#L154).
> 2. Yeah, for new service, you need provide the ci file.
> 3. You just need to generate the track 2 SDK, add the test and we will review the PR. After all of these are done, we can do the release. One more thing that need to be mentioned is, all of the packages depend on the Azure.ResourceManager package which we are still working on in the main branch, so I create a feature branch based on the previous release, you can follow these steps to onboard the new SDK:
> 
> * Fork the azure-sdk-for-net repo and clone the [feature branch](https://github.com/Azure/azure-sdk-for-net/tree/feature/mgmt-track2-dnsResolvers) to your local machine
> * Read this readme [azure-sdk-for-net/eng/templates at main · Azure/azure-sdk-for-net (github.com)](https://github.com/Azure/azure-sdk-for-net/tree/main/eng/templates) to install the mgmt track 2 sdk template and generate corresponding template for your RP
> * Replace the link of the required field in the autorest.md with a permalink to the exact version of the readme file in swagger repo
> * Add these configuration to the generated autorest.md
> 
> ```yaml
> library-name: your serivice name
> 
> namespace: Azure.ResourceManager.ServiceName
> 
> clear-output-folder: true
> 
> skip-csproj: true
> 
> output-folder: Generated/
> 
> mgmt-debug:
> 
>     show-request-path: true
> ```
> 
> * Change to the azure-sdk-for-net/sdk/your service/Azure.ResourceManager.YourSerivce/src and run this command: dotnet build /t:GenerateCode to generate code
> * Build the generated code, if success, please add the test case. You can see other track 2 SDK to figure out how to write test.
> * Open a PR to merge the change into the feature branch.

Thanks, Yao for the detailed answers! I will get started on it soon.

**Comment by arpit-gagneja** [comment]
@Yao725: I have created track 2 SDK changes in https://github.com/Azure/azure-sdk-for-net/pull/27153. You can close this PR.
I will add the tests iteratively. Can you please take a look at the code changes?

**Comment by Yao725** [comment]
Close this one as this RP already has a track 2 SDK PR.

**Pull request closed without merging**
