### PR TITLE
Beta-4 plumping work set 1

### PR DESCRIPTION
**Pull request by anuchandy**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anuchandy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anuchan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
> using Microsoft.Azure.Management.Resource.Fluent;

Please add license header ;) 

---
Refers to: src/ResourceManagement/Azure.Fluent/Fluent.Tests/ResourceManager/ResourceGroupsTests.cs:1 in 91b0e12. [](commit_id = 91b0e12aec2f7f7b0431b7829a9c309226d216bd, deletion_comment = False)

**Comment by hovsepm** [comment]
other than that LGTM.

**Comment by anuchandy** [comment]
Thanks @hovsepm, merging this.

**Pull request merged**
