### PR TITLE
Updating HealthcareApis to specify Kind

### PR DESCRIPTION
**Pull request by poadhika**
Updating HealthcareApis  SDK to support more than one kind of service
 
 The *.csproj and AssemblyInfo.cs files have been updated with the new version of the SDK.
REST spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/healthcareapis/resource-manager/Microsoft.HealthcareApis/preview/2018-08-20-preview/healthcare-apis.json

### CODE REVIEW

**Comment by erich-wang** [comment]
@poadhika , could you follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec) to regenerate the PR? I did not see update in csproj and <rp-resource-manager>.txt

**Review by erich-wang — CHANGES_REQUESTED** [review]
Please address my comment above, thanks.

**Comment by poadhika** [comment]
I regenerated the code pointing towards the latest swagger spec using the powersell cmd "AutoRestCodeGenerationWithLocalConfig ". Because while I was using "AutoRestCodeGeneration", it was constantly throwing me error.  " Error: Cannot write data to 'https://github.com/Azure/azure-rest-api-specs/blob/master/specification
/healthcareapis/resource-manager/generated/HealthcareApisManagementClient.cs'. Protocol 'https:' not supported for
writing. Make sure to specify a local, absolute path as target file/folder."

**Comment by erich-wang** [comment]
I notice that there's no C# configuration in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/healthcareapis/resource-manager/readme.md, please follow other service to add, thanks.

**Comment by poadhika** [comment]
@erich-wang 
I updated the readme file and created a pull request for it. Following is the link: https://github.com/Azure/azure-rest-api-specs/pull/6890. This is blocking me to regenerate the SDK now. Is it possible for you to review this PR?

**Comment by erich-wang** [comment]
@poadhika , the spec is merged, please go update this PR

**Comment by poadhika** [comment]
@erich-wang 
I have updated the PR. Please take a look. We are hoping to meet the AzurePS deadline that is August 26. Since PS is dependent upon SDK nuget release, I am hoping to close this PR sooner.

**Review by erich-wang — CHANGES_REQUESTED** [review]
@poadhika, could you update AsssemblyFileVersion in AssemblyInfo.cs and Version in .csproj? Then I'll merge the change

**Comment by poadhika** [comment]
@erich-wang I have updated the version in Assembly.info and .csproj

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
