### PR TITLE
Azure Monitor Exporter - Split Transmitter into two classes

### PR DESCRIPTION
**Pull request by TimothyMothra**
The current AzureMonitorTransmitter has grown into a very large class. 
Most of the methods are `private static` and only exist to convert from `Batch<Activity>` to `IEnumerable<TelemetryItem>`.

## Changes
- Move all static method to a new class `AzureMonitorConverter`. This fully encapsulates translating telemetry data types.
- `AzureMonitorTransmitter` contains only the logic to transmit to the ingestion endpoint.

## Todo
- If I can get approval for this change, I can make additional changes to the Connection String parser to avoid parsing twice.

### CODE REVIEW

**Review by reyang — APPROVED** [review]
LGTM.

**Comment by TimothyMothra** [comment]
/AzurePipeline run net - monitor - ci (Build Test Windows_NetCoreApp_ProjectReferences)

**Comment by TimothyMothra** [comment]
/AzurePipeline run "net - monitor - ci (Build Test Windows_NetCoreApp_ProjectReferences)"

**Comment by TimothyMothra** [comment]
/AzurePipeline run net - monitor - ci

**Pull request merged**
