### PR TITLE
Bumped up ADF api-version to 2015-05-01-preview

### PR DESCRIPTION
**Pull request by yitao-zhang**
1. Bumped up ADF api-version
2. Synced the latest changes in Master branch
3. Re-run all the http mock test.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yitao-zhang__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (yitzhang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@yitao-zhang I think this PR has way too many changes, and lots of changes scoped outside the ADF management library.  Pleases sync with the latest in the branch and scope down.

@yugangw-msft Please take a look, as I think you created this branch.

**Comment by yugangw-msft** [comment]
Because it gets into the "DataFactories" branch, let us just merge and we will take a good review when it tries to merge into the "master" :-)

**Comment by yitao-zhang** [comment]
Great! Thank you Yugang! Yes, when we merge back into master, it should reveal we only touched our own project.

**Pull request merged**
