### PR TITLE
[Notification Hubs] Generated latest client from OpenAPI

### PR DESCRIPTION
**Pull request by stankovski**

### CODE REVIEW

**Review by isra-fel — COMMENTED** [review]
Hi @stankovski 

Your PR looks like it's based on a very old branch. I suggest rebasing latest master.
A few things to notice:

- You should initialize SDK generation by running `generate.ps1` instead of `generate.cmd`. Actually, `generate.cmd` was deleted long ago. (Guide: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-directory-structure-and-sdk-generation)
- The version in csproj is should not downgrade. `2.5.0-preview.1` would be ideal.
- The release notes in csproj need to be updated as well

**Review by isra-fel — CHANGES_REQUESTED** [review]
Meanwhile, please put a link to the openapi spec review PR here, thanks

**Comment by stankovski** [comment]
Here is a spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2017-04-01/notificationhubs.json

There was no change done to the underlying specification. The client hasn't been kept up-to-date with the OpenApi model.

As far as version, version `2.4.0` has never been released. The highest released version is: https://www.nuget.org/packages/Microsoft.Azure.Management.NotificationHubs/2.3.2-preview

We plan to release non-preview version `2.4.0` in a month.

**Comment by isra-fel** [comment]
Hi @stankovski , I got your point. I have no problem concerning the version. Just a few other things:

1. Since 2.4.0 was never published. You might want to keep the old release notes
1. I saw you removed some `NullValueHandling = NullValueHandling.Include`. It's strongly discouraged to modify generated code, because it'll be overwritten next time. Besides, the default behavior is to include null properties. Keeping `NullValueHandling` there or not shouldn't matter.
1. Upon generating, you should get a metadata txt file under `/eng/mgmt/mgmtmetadata`, be sure to check it in.

Thanks

**Comment by stankovski** [comment]
@isra-fel 
1. It looks like those release notes were left over from older builds. Current release notes are correct.
2. `NullValueHandling` was removed in the first commit and reverted later. Current PR does not have any changes to generated files.
3. Added metadata file and push it in

**Review by isra-fel — APPROVED** [review]
Looks great

**Pull request merged**
