### PR TITLE
fix(dataplane): `ServiceVersion` should be pascal case in manual codes

### PR DESCRIPTION
**Pull request by archerzz**
- fix case problem in `ServiceVersion` in manual codes
- remove suppression of `AZC0016`

part of https://github.com/Azure/autorest.csharp/issues/1524

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by archerzz** [comment]
This PR is to fix the `ServiceVersion` case issue in manually written codes. Those are all beta SDKs.

**Review by jsquire — APPROVED** [review]
Signing off on behalf of ObjectAnchors and Personalizer.     Please ensure that we have sign-off from each package included before moving forward.

**Review by kinelski — APPROVED** [review]
Form Recognizer LGTM.

**Comment by archerzz** [comment]
approved on behalf of purview

**Review by lucasrsant — APPROVED** [review]
Signing-off on behalf of Phone Numbers package.

**Pull request merged**
