### PR TITLE
Throw RequestFailedException for failed backup/restore

### LINKED ISSUE #41855: Restore (and possibly other) operations are not handling errors correctly
A customer reported an issue through CSS about restore operations not always failing correctly. No error HTTP status was reported, but a status monitor still returned an error. According to [guidelines](https://aka.ms/azapi/guidelines#obtaining-status-and-results-of-long-running-operations), this is expected.

The crux of the issue is here:

https://github.com/Azure/azure-sdk-for-net/blob/5f860d9662b99e60f1bfb500f6a6d19910d4ae58/sdk/keyvault/Azure.Security.KeyVault.Administration/src/RestoreOperationInternal.cs#L218-L222

We likely did not populate `Error.Code` or maybe not even `Error`, so we didn't create and/or throw a proper `RequestFailedException`.

### PR DESCRIPTION
**Pull request by heaths**
Fixes #41855

### CODE REVIEW

**Comment by heaths** [comment]
Note that [guidelines say we should throw](https://azure.github.io/azure-sdk/dotnet_implementation.html#dotnet-lro-return) a `RequestFailedException`, but this behavior would be breaking. That said, we provide a lot more detail for what should be a failure anyway. I think we should take this, lest customers get no exception and may think the restore operation was successful.

**Review by christothes — APPROVED** [review]

**Comment by heaths** [comment]
This does not alter fundamental behavior, so after discussions with @pallavit I will release today

**Pull request merged**
