### PR TITLE
Add linked service scenario test (resolves #3726)

### LINKED ISSUE #3726: Re-record test using latest resource manager
all ADF V2 tests needs to be recorded using latest version of resource manager 1.6.0

### PR DESCRIPTION
**Pull request by bgold09**
## Description

Add linked service scenario test (resolves #3726)

  * Adds a simple CRUD test for linked services
  * Also change all tests to check for proper HTTP response codes on
    each API call

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by bgold09** [comment]
@shahabhijeet can you take a look at this when you can? thanks!

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
@bgold09 use the latest Resource Manager nuget 1.6.0 (at least) in your test csproj to record all your tests.

**Comment by bgold09** [comment]
@shahabhijeet this was done with version 1.7.2, what do you mean?

**Comment by bgold09** [comment]
@cormacpayne since @shahabhijeet is still out, can you take a look at this?

**Comment by shahabhijeet** [comment]
@bgold09 if you look at PR #3774 I don't have your test.csproj as part of the PR, so I am not sure how can I flag this inconsistency?
The point is, you are using a really old version of resource manager and I think you should make a call if you want to test your resources using 1.1.0 (which was simply a repackaging of 1.0.0 version) which was published in April 2016

**Comment by bgold09** [comment]
discussed offline, we're going to bump the version of Microsoft.Azure.ResourceManager being used in the tests

**Pull request merged**
