### PR TITLE
Use dotnet build to generate code

### PR DESCRIPTION
**Pull request by pakrym**
`dotnet build` auto restores and is a whole 2️⃣ characters shorter! :fire:

### CODE REVIEW

**Review by MiYanni — APPROVED** [review]

**Review by christothes — APPROVED** [review]

**Comment by weshaggard** [comment]
Not sure why no build pipelines kicked off but at any rate all the changes are documentation based changes so I'll merge this.

**Comment by maririos** [comment]
Love the description :)

**Pull request merged**
