### PR TITLE
Data Box SDK upgrade based on swagger version 2022-12

### PR DESCRIPTION
**Pull request by vaishnavi-janardhan**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by vaishnavi-janardhan** [comment]
@live1206 could you please review this PR and let me know if any changes are needed from our end?

**Comment by live1206** [comment]
There are breaking changes in the new version, we need to mitigate them firstly.

**Comment by live1206** [comment]
@vaishnavi-janardhan 
There is a breaking change in your swagger:
image
The generated SDK changed from
image
to
image

I am wondering what is your purpose of this change here? If the user doesn't set `CustomerResolutionCode`, does it equal to `CustomerResolutionCode.None`?

**Comment by vaishnavi-janardhan** [comment]
@live1206, from swagger version 2022-10-01 we have introduced a new property within MitigateJobRequest called `SerialNumberCustomerResolutionMap` which is a replacement to the `CustomerResolutionCode`. This change was taken as part of supporting the `MitigateJobRequest` for disk jobs where one job could be associated with multiple disks and we needed to support resolution codes for each disk serial number. So we have made the `CustomerResolutionCode` property optional and have introduced a dictionary which maps serial numbers to resolution codes.

image

Yes, if not sent, we can default it to `CustomerResolutionCode.None`

**Review by live1206 — APPROVED** [review]

**Pull request merged**
