### PR TITLE
Changing GUID to string for AccessPolicyEntry object id

### PR DESCRIPTION
**Pull request by bganapa**
## Description

Changing GUID to string for AccessPolicyEntry object id, This is against master with hydra specs
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bganapa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bganapa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Review by pomortaz — APPROVED** [review]

**Review by pomortaz — COMMENTED** [review]
The change should go to stack branch.

**Comment by bganapa** [comment]
@shahabhijeet Can you please create stack-dev branch on SDK ? The current snapshot of master is fine

**Comment by shahabhijeet** [comment]
@pomortaz  there isn't any stack equivalent for SDK components. Hydra related stuff will always stay in Master and swagger will be always in AutoRest, AutoRest and Master will never be merged.
So this change has to go in Master.

**Comment by bganapa** [comment]
Talked to Kapil , we can merge this master , no need to create a stack-dev

**Pull request merged**
