### PR TITLE
[Storage] Support HDFS feature and web endpoint in Account properties

### PR DESCRIPTION
**Pull request by blueww**
## Description

Add HDFS feature and web endpoint support to Storage Account.
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/3289
(This PR is generated from private swagger, will re-generate when swagger PR pass review and merge. Code should be the same)

Already pass review in private repo in PR:
https://github.com/Azure/azure-sdk-for-net-pr/pull/856
https://github.com/Azure/azure-sdk-for-net-pr/pull/858

Changes include:

- Add web endpoint
- Add dfs endpoint
- Add Account property IsHndEnabled

Rest doc: https://microsoft.sharepoint.com/teams/AzureStorage/_layouts/15/Doc.aspx?sourcedoc=%7B00d45481-7f25-4170-a95e-82dbc6a3041d%7D&action=default&slrid=0d385f9e-a0fa-0000-758b-e5dde88dbd09

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by dsgouda** [comment]
@blueww Let us know when the spec is merged and we will review and merge these changes
Also, create a generate.ps1 similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/generate.ps1) and regenerate the code.  
Please delete the generate.cmd if you can successfully generate the code using generate.ps1.
The `Start-AutoRestCodeGeneration` cmdlet has options to let you specify your own branch and fork for the config file.

**Comment by blueww** [comment]
@dsgouda 
The swagger PR is merged, and I have regenerated the code based on the public swagger.
Please help to merge the PR.

For the generate.ps1, I don't think it should block this PR merge. We should merge this PR and follow it in another PR if any change is needed.
I have tried to modify it, but there are some problem:
1. when I remove the -SdkGenerationDirectory "$PSScriptRoot\Generated" in the script as the sample from you, run the script will get error " Could not find default output directory since script is not run from a sdk repo, please provide one!"
2. I don't find a "generate.cmd" in the stroage folder, so which file should I delete?

**Comment by dsgouda** [comment]
@blueww 
I was able to pulled from latest upstream and run the `generate.ps1` without issues. Won't block on this however.

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
