### PR TITLE
Use correct dev lang for .NET CLI commands

### PR DESCRIPTION
**Pull request by scottaddie**
In the SDK _README_ files, switch to using the `dotnetcli` dev lang instead of things like `bash`, `console`, and `powershell`. The result is improved display on docs.microsoft.com. For example:

image

In the preceding screenshot, notice the ".NET CLI" header text and command colorization that is applied.

### CODE REVIEW

**Review by pakrym — APPROVED** [review]
👍

**Review by Mohit-Chakraborty — APPROVED** [review]

**Review by heaths — APPROVED** [review]
QnA, KV, and VA LGTM

**Review by jsquire — APPROVED** [review]
LGTM for Event Hubs and Service Bus

**Review by petrsvihlik — APPROVED** [review]

**Comment by scottaddie** [comment]
Confirmed that the build failure is unrelated to the changes introduced in this PR.

**Pull request merged**
