### PR TITLE
Add canary configuration to smoke test matrix

### PR DESCRIPTION
**Pull request by benbp**
This PR adds a new entry to the smoke test matrix to add a public cloud test against a Canary/EUAP region (specifically eastus2euap).

Passing smoke test pipeline here (for new canary jobs, AzureChinaCloud seems to be having a transient issue but I'll keep an eye on it): https://dev.azure.com/azure-sdk/internal/_build/results?buildId=572805&view=results

Azure/azure-sdk#1879

### CODE REVIEW

**Comment by jsquire** [comment]
> AzureChinaCloud seems to be having a transient issue but I'll keep an eye on it):

This tends to time out frequently due to the linked template and the latency in requesting it from GitHub.   Daniel was looking into it at one point, but I'm not sure where that ended up.

**Comment by benbp** [comment]
> > AzureChinaCloud seems to be having a transient issue but I'll keep an eye on it):
> 
> This tends to time out frequently due to the linked template and the latency in requesting it from GitHub. Daniel was looking into it at one point, but I'm not sure where that ended up.

Yeah, it seemed like it was getting a 404 for some asset in github. I re-ran the failed job, so we'll know in a few minutes. In any case, it seemed independent of my changes.

**Comment by benbp** [comment]
As a follow-on to some of this, I'm thinking about moving towards using some of the devops looping primitives along with parameters, as opposed to using `matrix` (as @weshaggard pointed out we're starting to do in other places). But I thought it would be better to stand up canary testing first within the existing config format, before making larger changes.

**Comment by benbp** [comment]
I added a minor update based on some feedback from @mikeharder to only add a single canary instance to the matrix (sparse matrix coverage), in order to not cause resource stress regarding the build agent pool.

**Comment by weshaggard** [comment]
It should also be pointed out that the .NET smoke tests are currently testing against older packages instead of the latest packages in the repo, see issue https://github.com/Azure/azure-sdk-for-net/issues/14418.

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
