### PR TITLE
Regenerate EventGrid .NET SDK to reflect new swagger bug fixes for 20-04-01-preview

### PR DESCRIPTION
**Pull request by ahamad-MS**
Regenerate EventGrid .NET SDK to reflect new swagger bug fixes for 2020-04-01-preview.

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/8880

### CODE REVIEW

**Comment by ahamad-MS** [comment]
@isra-fel , @erich-wang Can you please review and help merge this change? thanks

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi, could you
- Add a link to the swagger spec review PR in the description
- Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update `AssemblyFileVersion` in `assemblyinfo.cs` 

Thanks

**Comment by ahamad-MS** [comment]
@isra-fel All comments are addressed. Can you please recheck.

thanks

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
