### PR TITLE
Updating LogicApps .NET SDK for API 2016-06-01

### PR DESCRIPTION
**Pull request by pscofield**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pscofield__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@pscofield We're moving all autorest-generated SDKs to supporting the RTM .NetCore.  This would require you changing the build infrastructure (simplifying) to match Storage, Compute, and the other projects.  Can you guys tackle this as part of this PR?

**Comment by pscofield** [comment]
@markcowl - I can do that but we want this change merged the soonest so that we are unblocked on the PowerShell SDK (nuget package dependency). The service has its GA on 27th of July. If it's not a mandatory requirement right now, can we do this in a follow up PR please?

**Comment by hovsepm** [comment]
@pscofield please pull from upstream and resolve conflicts.

**Comment by cormacpayne** [comment]
@pscofield Please make sure that the version you have in project.json is equal to the version in  AssemblyInfo.cs

**Pull request merged**
