### PR TITLE
Fix updateSuppressedDueIdempotence type

### PR DESCRIPTION
**Pull request by MiriBerezin**
fixing updateSuppressedDueIdempotence type to boolean instead of string

### CODE REVIEW

**Comment by MiriBerezin** [comment]
@markcowl , @allenjzhang , @YalinLi0312 , @bquantump , @m-nash , @nisha-bhatia 

Can one of you please review this PR? thanks!

**Comment by m-nash** [comment]
@MiriBerezin can you link the swagger PR associated with this change?

**Comment by MiriBerezin** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/11543/

**Comment by MiriBerezin** [comment]
The swagger PR: 
https://github.com/Azure/azure-rest-api-specs/pull/11543/

**Comment by MiriBerezin** [comment]
@m-nash what can you please review and approve? thanks!

**Review by m-nash — APPROVED** [review]

**Pull request merged**
