### PR TITLE
[Storage] HNS Encryption Scopes

### PR DESCRIPTION
**Pull request by seanmcc-msft**
This feature was moved from STG 79 to STG 80.  Continued from https://github.com/Azure/azure-sdk-for-net/pull/23130

### CODE REVIEW

**Comment by mikeharder** [comment]
Validation build: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1102675&view=results

**Review by amnguye — APPROVED** [review]

**Comment by seanmcc-msft** [comment]
Continued with https://github.com/Azure/azure-sdk-for-net/pull/24512

**Pull request closed without merging**
