### PR TITLE
Rename Raw to GetRawResponse

### PR DESCRIPTION
**Pull request by pakrym**
As discussed in the email thread renaming `Response<T>.Raw` to `Response<T>.GetRawResponse()` to make it easy for customers to discover the Value property.

### Breaking change

Before:
```
Response<Model> response = ...;
Response raw = response.Raw;
```
After:

```
Response<Model> response = ...;
Response raw = response.GetRawResponse();
```

### CODE REVIEW

**Review by tg-msft — APPROVED** [review]
I think you're missing a few other test projects per the CI, but the change to Azure.Core looks good.

Can you also add the breaking change label and include before/after code samples?

**Comment by pakrym** [comment]
Hm, I thought I have a solution with all of them, will fix.

**Comment by tg-msft** [comment]
Looks good

**Review by jsquire — APPROVED** [review]
Looks good to me.

**Pull request merged**
