### PR TITLE
Bringing SDK and Swagger in sync for GraphRBAC

### PR DESCRIPTION
**Pull request by ankushbindlish2**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/graphrbac/data-plane

### CODE REVIEW

**Comment by dsgouda** [comment]
@ankushbindlish2 do you still need this pr
https://github.com/Azure/azure-sdk-for-net/pull/5454

**Comment by ankushbindlish2** [comment]
Yes, Waiting on GraphRbac team to respond why we are seeing discrepancies

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Let's wait for the new swagger to be published and you can generate the SDK from the new swagger.
This PR should be closed.

**Comment by ankushbindlish2** [comment]
as per SDK team, closing this pr

**Comment by ankushbindlish2** [comment]
@abhijeet please sign off

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
