### PR TITLE
Add First SDK for LabServices RP 2018-10-15

### PR DESCRIPTION
**Pull request by ianhays**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [X] Please add REST spec PR link to the SDK PR
  - https://github.com/Azure/azure-rest-api-specs/pull/4621
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.
  - https://github.com/Azure/azure-rest-api-specs/issues/4738

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
  - https://github.com/Azure/azure-rest-api-specs/pull/4621
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by ianhays** [comment]
@dsgouda @carlosscastro @shahabhijeet PTAL

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Please add tests for your SDK.

**Comment by shahabhijeet** [comment]
@ianhays sorry for the delay in responding. For some reason I forgot to click on posting my review.

**Comment by shahabhijeet** [comment]
@ianhays as discussed offline, you will be opening a new PR. Closing this one or you can reopen the same PR.

**Comment by ianhays** [comment]
continued in https://github.com/Azure/azure-sdk-for-net/pull/5083

**Pull request closed without merging**
