### PR TITLE
Generate SDK from new version

### PR DESCRIPTION
**Pull request by navysingla**

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hello. The changes generally LGTM. Please add a link to your openapi spec review PR here and update the versions in AssemblyInfo.cs so I can merge. Thanks

**Comment by navysingla** [comment]
> Hello. The changes generally LGTM. Please add a link to your openapi spec review PR here and update the versions in AssemblyInfo.cs so I can merge. Thanks

Spec link - https://github.com/Azure/azure-rest-api-specs/pull/7418/files. Why we need update versions in AssemblyInfo.cs?

**Comment by isra-fel** [comment]
It's displayed in windows explorer and used when resolving dll dependencies. It should match the version of your project. See our guide to sign and publish nuget package: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#signing-and-publishing-nuget-packges

**Comment by navysingla** [comment]
> It's displayed in windows explorer and used when resolving dll dependencies. It should match the version of your project. See our guide to sign and publish nuget package: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#signing-and-publishing-nuget-packges

Updated AssemblyInfoVersion

**Review by isra-fel — APPROVED** [review]
LGTM. (failed check is not related to this PR)

**Pull request merged**
