### PR TITLE
[AMS] Add ListEdgePolicies Action on media service account on stable version of the API

### PR DESCRIPTION
**Pull request by giakas**
[AMS] Release stable version of AMS with ListEdgePolicies Action on media services account. 05/20

Link to PR for swagger changes https://github.com/Azure/azure-rest-api-specs/pull/9492

### CODE REVIEW

**Comment by isra-fel** [comment]
Hello @giakas for a new release, please update the versions in .csproj and AssemblyInfo.cs, as well as the release note in your csproj. Thanks

**Comment by giakas** [comment]
@isra-fel I guess I had a confusing title.. we are adding an action to the same existing released version, we are not releasing a new version of the API. updating the title

**Review by isra-fel — APPROVED** [review]
All right. LGTM!

**Pull request merged**
