### PR TITLE
Resolve duplicates for management plane batch 3 stable release

### PR DESCRIPTION
**Pull request by Yao725**
In this PR's comment, you can see the names that we changed and also the names that we keep unchanged.

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by Yao725** [comment]
### Storage

Changed:
```text
StorageKeyType (2):
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.StorageKeyType)
    Azure.ResourceManager.Storage (type Azure.ResourceManager.Storage.Models.StorageKeyType)
```

Unchanged:
```text
Storage (9):
    Azure.Storage.Blobs (namespace Azure.Storage.Sas)
    Azure.Storage.Blobs.Batch (namespace Azure.Storage.Blobs.Specialized)
    Azure.Storage.Blobs.ChangeFeed (namespace Azure.Storage.Blobs.ChangeFeed)
    Azure.Storage.Common (namespace Azure.Storage)
    Azure.Storage.Files.DataLake (namespace Azure.Storage.Sas)
    Azure.Storage.Files.Shares (namespace Azure.Storage.Sas)
    Azure.Storage.Queues (namespace Azure.Storage.Sas)
    Azure.ResourceManager.Storage (namespace Azure.ResourceManager.Storage)
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.FlexibleServers.Models.Storage)
LeaseState (2, this will be covered by another PR):
    Azure.Storage.Blobs (type Azure.Storage.Blobs.Models.LeaseState)
    Azure.ResourceManager.Storage (type Azure.ResourceManager.Storage.Models.LeaseState)
LeaseStatus (2, this will be covered by another PR):
    Azure.Storage.Blobs (type Azure.Storage.Blobs.Models.LeaseStatus)
    Azure.ResourceManager.Storage (type Azure.ResourceManager.Storage.Models.LeaseStatus)
TableAccessPolicy (2, this will be covered by another PR):
    Azure.Data.Tables (type Azure.Data.Tables.Models.TableAccessPolicy)
    Azure.ResourceManager.Storage (type Azure.ResourceManager.Storage.Models.TableAccessPolicy)
TableSignedIdentifier (2, this will be covered by another PR):
    Azure.Data.Tables (type Azure.Data.Tables.Models.TableSignedIdentifier)
    Azure.ResourceManager.Storage (type Azure.ResourceManager.Storage.Models.TableSignedIdentifier)
StorageExtensions (2):
    Azure.Storage.Common (type Azure.Storage.StorageExtensions)
    Azure.ResourceManager.Storage (type Azure.ResourceManager.Storage.StorageExtensions)
```

**Comment by Yao725** [comment]
### Sql

Changed:
```text
VirtualNetworkRuleState (4):
    Azure.ResourceManager.ElasticSan (type Azure.ResourceManager.ElasticSan.Models.VirtualNetworkRuleState)
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.Models.VirtualNetworkRuleState)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.Models.VirtualNetworkRuleState)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.VirtualNetworkRuleState)
MetricAvailability (3):
    Azure.Monitor.Query (type Azure.Monitor.Query.Models.MetricAvailability)
    Azure.ResourceManager.AppService (type Azure.ResourceManager.AppService.Models.MetricAvailability)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.MetricAvailability)
PrivateEndpointConnectionProperties (3):
    Azure.ResourceManager.CognitiveServices (type Azure.ResourceManager.CognitiveServices.Models.PrivateEndpointConnectionProperties)
    Azure.ResourceManager.IotHub (type Azure.ResourceManager.IotHub.Models.PrivateEndpointConnectionProperties)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.PrivateEndpointConnectionProperties)
VirtualNetworkRuleData (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.VirtualNetworkRuleData)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.VirtualNetworkRuleData)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.VirtualNetworkRuleData)
VirtualNetworkRuleCollection (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.VirtualNetworkRuleCollection)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.VirtualNetworkRuleCollection)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.VirtualNetworkRuleCollection)
VirtualNetworkRuleResource (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.VirtualNetworkRuleResource)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.VirtualNetworkRuleResource)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.VirtualNetworkRuleResource)
PrivateEndpointProvisioningState (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.Models.PrivateEndpointProvisioningState)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.Models.PrivateEndpointProvisioningState)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.PrivateEndpointProvisioningState)
PrivateLinkServiceConnectionStateActionsRequire (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.Models.PrivateLinkServiceConnectionStateActionsRequire)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.Models.PrivateLinkServiceConnectionStateActionsRequire)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.PrivateLinkServiceConnectionStateActionsRequire)
PrivateLinkServiceConnectionStateStatus (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.Models.PrivateLinkServiceConnectionStateStatus)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.Models.PrivateLinkServiceConnectionStateStatus)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.PrivateLinkServiceConnectionStateStatus)
SecurityAlertPolicyName (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.Models.SecurityAlertPolicyName)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.Models.SecurityAlertPolicyName)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.SecurityAlertPolicyName)
ServerKeyType (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.Models.ServerKeyType)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.Models.ServerKeyType)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.ServerKeyType)
ServerPrivateEndpointConnection (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.Models.ServerPrivateEndpointConnection)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.Models.ServerPrivateEndpointConnection)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.ServerPrivateEndpointConnection)
ReplicationRole (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.FlexibleServers.Models.ReplicationRole)
    Azure.ResourceManager.Redis (type Azure.ResourceManager.Redis.Models.ReplicationRole)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.ReplicationRole)
ServerVersionCapability (3):
    Azure.ResourceManager.MySql (type Azure.ResourceManager.MySql.FlexibleServers.Models.ServerVersionCapability)
    Azure.ResourceManager.PostgreSql (type Azure.ResourceManager.PostgreSql.FlexibleServers.Models.ServerVersionCapability)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.ServerVersionCapability)
RestorePointData (2):
    Azure.ResourceManager.Compute (type Azure.ResourceManager.Compute.RestorePointData)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.RestorePointData)
RestorePointCollection (2):
    Azure.ResourceManager.Compute (type Azure.ResourceManager.Compute.RestorePointCollection)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.RestorePointCollection)
RestorePointResource (2):
    Azure.ResourceManager.Compute (type Azure.ResourceManager.Compute.RestorePointResource)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.RestorePointResource)
BackupStorageRedundancy (2):
    Azure.ResourceManager.CosmosDB (type Azure.ResourceManager.CosmosDB.Models.BackupStorageRedundancy)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.BackupStorageRedundancy)
PrimaryAggregationType (2):
    Azure.ResourceManager.CosmosDB (type Azure.ResourceManager.CosmosDB.Models.PrimaryAggregationType)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.PrimaryAggregationType)
```

Unchanged:
```text
StorageKeyType (2):
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.StorageKeyType)
    Azure.ResourceManager.Storage (type Azure.ResourceManager.Storage.Models.StorageKeyType)
```

**Comment by Yao725** [comment]
CosmosDB

Changed:
```text
BackupStorageRedundancy (2):
    Azure.ResourceManager.CosmosDB (type Azure.ResourceManager.CosmosDB.Models.BackupStorageRedundancy)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.BackupStorageRedundancy)
PrimaryAggregationType (2):
    Azure.ResourceManager.CosmosDB (type Azure.ResourceManager.CosmosDB.Models.PrimaryAggregationType)
    Azure.ResourceManager.Sql (type Azure.ResourceManager.Sql.Models.PrimaryAggregationType)
```

**Comment by Yao725** [comment]
### WebPubSub

Changed:
```text
RegenerateKeyContent (5):
    Azure.ResourceManager.AppConfiguration (type Azure.ResourceManager.AppConfiguration.Models.RegenerateKeyContent)
    Azure.ResourceManager.CognitiveServices (type Azure.ResourceManager.CognitiveServices.Models.RegenerateKeyContent)
    Azure.ResourceManager.FluidRelay (type Azure.ResourceManager.FluidRelay.Models.RegenerateKeyContent)
    Azure.ResourceManager.RedisEnterpriseCache (type Azure.ResourceManager.RedisEnterpriseCache.Models.RegenerateKeyContent)
    Azure.ResourceManager.WebPubSub (type Azure.ResourceManager.WebPubSub.Models.RegenerateKeyContent)
```

**Review by ArcturusZhang — APPROVED** [review]

**Pull request merged**
