### PR TITLE
 updated Azure SDK for swagger updates regarding the new property cal…

### PR DESCRIPTION
**Pull request by hari-bodicherla**
Added Swagger tests for Single VM, VM Scaleset and Image tests to verify the DiskEncryptionSet resource usage. 

Added SetSwaggerTestEnvironment.ps1 for setting the test env variables and to invoke the solution file for updating and running the tests in record mode.

Swagger documentation Pull request for reference:
https://github.com/Azure/azure-rest-api-specs/pull/7293
https://github.com/Azure/azure-rest-api-specs/pull/7318

### CODE REVIEW

**Comment by isra-fel** [comment]
@hari-bodicherla
Azure/azure-rest-api-specs#7318 is still open. I suppose you are going to regenerate SDK after it's merged.
Please let me know if this PR is ready for review.
 Thanks

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla
> [Azure/azure-rest-api-specs#7318](https://github.com/Azure/azure-rest-api-specs/pull/7318) is still open. I suppose you are going to regenerate SDK after it's merged.
> Please let me know if this PR is ready for review.
> Thanks

Hi,
This SDK is generated from my forked branch where the azure-rest-api-specs/pull/7318 changes  already present. So I think we dont need to regenerate the SDK from the master again once the swagger documentation changes are merged. The only one thing to note is the azure-rest-api-specs/pull/7318 is going to private branch called 2019-07 ( which needs to publish into master for new api version  2019-07-01 yet) . So the current master azure-rest-api-specs branch is not aware of api version 2019-07-01 which are resulting in above failed checks it seems.

**Comment by isra-fel** [comment]
> Hi,
> This SDK is generated from my forked branch where the azure-rest-api-specs/pull/7318 changes already present. So I think we dont need to regenerate the SDK from the master again once the swagger documentation changes are merged. The only one thing to note is the azure-rest-api-specs/pull/7318 is going to private branch called 2019-07 ( which needs to publish into master for new api version 2019-07-01 yet) . So the current master azure-rest-api-specs branch is not aware of api version 2019-07-01 which are resulting in above failed checks it seems.

OK I got it. Please notify me when the spec is merged into master and your PR is ready for review.
Thanks

**Comment by hari-bodicherla** [comment]
> > Hi,
> > This SDK is generated from my forked branch where the azure-rest-api-specs/pull/7318 changes already present. So I think we dont need to regenerate the SDK from the master again once the swagger documentation changes are merged. The only one thing to note is the azure-rest-api-specs/pull/7318 is going to private branch called 2019-07 ( which needs to publish into master for new api version 2019-07-01 yet) . So the current master azure-rest-api-specs branch is not aware of api version 2019-07-01 which are resulting in above failed checks it seems.
> 
> OK I got it. Please notify me when the spec is merged into master and your PR is ready for review.
> Thanks

Sure , I will notify when the spec is merged into master @isra-fel  . Thanks

**Comment by isra-fel** [comment]
@hari-bodicherla How's going about the spec?

**Comment by isra-fel** [comment]
@hari-bodicherla I'll close this PR for now. Feel free to reopen or open a new one to continue. THanks

**Pull request closed without merging**
