### PR TITLE
Feature/storage/set blob tier snapshot version

### PR DESCRIPTION
**Pull request by seanmcc-msft**

### CODE REVIEW

**Comment by kasobol-msft** [comment]
Diff only shows changes in tests. Did actual feature go in separate PR ?

**Comment by seanmcc-msft** [comment]
> Diff only shows changes in tests. Did actual feature go in separate PR ?

The actual feature is a swagger-only change that was already present in the STG 73 base branch.

**Review by kasobol-msft — APPROVED** [review]

**Pull request merged**
