### PR TITLE
[Template] Remove unused perf and stress folders

### PR DESCRIPTION
**Pull request by jsquire**
# Summary

The focus of these changes is to remove the unused perf and stress folders from the template.  The Azure SDK team no longer requires performance tests for each library and partner teams do not use the
scaffolding when generating a new library.  Likewise, the stress folder is empty, save a README, which simply points to a wiki location that our onboarding guide also references.

### CODE REVIEW

**Comment by jsquire** [comment]
@m-nash, @AlexanderSher :  Do either of you know of any code generation areas that this would impact?
@hallipr: Do you know of any EngSys tooling that this would impact?

**Comment by pallavit** [comment]
> @m-nash, @AlexanderSher : Do either of you know of any code generation areas that this would impact? @hallipr: Do you know of any EngSys tooling that this would impact?

I think it is good to understand if this is used in DPG tooling or not. @lirenhe could you confirm if this is used in DPG tooling and if so who can help us with validation of those scenarios?

**Review by lirenhe — APPROVED** [review]

**Comment by lirenhe** [comment]
> > @m-nash, @AlexanderSher : Do either of you know of any code generation areas that this would impact? @hallipr: Do you know of any EngSys tooling that this would impact?
> 
> I think it is good to understand if this is used in DPG tooling or not. @lirenhe could you confirm if this is used in DPG tooling and if so who can help us with validation of those scenarios?

As far as I know, we don't use them in DPG.  I approved this PR.

**Comment by jsquire** [comment]
Given the lack of responses, I'm going to merge and see what happens.  If anything breaks as a result, we'll adjust.

**Pull request merged**
