### PR TITLE
Update Azure Notification Hubs SDK to 2.3.4-preview

### PR DESCRIPTION
**Pull request by mpodwysocki**
# All SDK Contribution checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ x] **Please open PR in `Draft` mode if it is:**
	- Work in progress or not intended to be merged.
	- Encountering multiple pipeline failures and working on fixes.
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md).**

### [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#general-guidelines)
- [ x] Title of the pull request is clear and informative.
- [ x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code. (Track 2 only)
- [ x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK. Please double check nuget.org current release version.

## Additional management plane SDK specific contribution checklist: 
Note: Only applies to `Microsoft.Azure.Management.[RP]` or `Azure.ResourceManager.[RP]`
 
- [ ] Include updated [management metadata](https://github.com/Azure/azure-sdk-for-net/tree/main/eng/mgmt/mgmtmetadata).
- [ ] Update AzureRP.props to add/remove version info to maintain up to date API versions.

### Management plane SDK Troubleshooting
- If this is very first SDK for a services and you are adding new service folders directly under /SDK, please add `new service` label and/or contact assigned reviewer.
- If the check fails at the `Verify Code Generation` step, please ensure:
	- Do not modify any code in generated folders.
	- Do not selectively include/remove generated files in the PR.
	- Do use `generate.ps1/cmd` to generate this PR instead of calling `autorest` directly.
	Please pay attention to the @microsoft.csharp version output after running `generate.ps1`. If it is lower than current released version (2.3.82), please run it again as it should pull down the latest version.
	
	**Note: We have recently updated the PSH module called by `generate.ps1` to emit additional data. This would help reduce/eliminate the Code Verification check error. Please run following command**:

	    `dotnet msbuild eng/mgmt.proj /t:Util /p:UtilityName=InstallPsModules`

### Old outstanding PR cleanup
 Please note:
	If PRs (including draft) has been out for more than 60 days and there are no responses from our query or followups, they will be closed to maintain a concise list for our reviewers.

### CODE REVIEW

**Comment by mpodwysocki** [comment]
As noted, this is to release a new version since 2.3.3 was delisted as it contained a regression.  This PR in the Azure Specs repo fixed the issue and now need to regenerate the SDK: https://github.com/Azure/azure-rest-api-specs/pull/16221

**Comment by mpodwysocki** [comment]
Ping @archerzz, @ArcturusZhang, @ArthurMa1978, @fengzhou-msft, @m-nash and @Yao725 for a review since this is already two weeks old and nobody has looked at it yet

**Review by archerzz — CHANGES_REQUESTED** [review]
@mpodwysocki The following files need to be updated.

- metadata file, e.g. https://github.com/Azure/azure-sdk-for-net/blob/main/eng/mgmt/mgmtmetadata/notificationhubs_resource-manager.txt
- `AssemblyInfo.cs`

See the guidelines on top:

> The *.csproj and AssemblyInfo.cs files have been updated with the new version of the SDK. Please double check nuget.org current release version.

>  Include updated management metadata.

**Comment by mpodwysocki** [comment]
> @mpodwysocki The following files need to be updated.
> 
> * metadata file, e.g. https://github.com/Azure/azure-sdk-for-net/blob/main/eng/mgmt/mgmtmetadata/notificationhubs_resource-manager.txt
> * `AssemblyInfo.cs`
> 
> See the guidelines on top:
> 
> > The *.csproj and AssemblyInfo.cs files have been updated with the new version of the SDK. Please double check nuget.org current release version.
> 
> > Include updated management metadata.

@archerzz  Not sure if the AssemblyInfo.cs needs to be updated given that this is a minor patch to bump from 2.3.3 was delisted and we're bumping to 2.3.4

**Comment by archerzz** [comment]
@mpodwysocki I think we need to update it. And it's current value seems not correct: https://github.com/Azure/azure-sdk-for-net/blob/353615e31efc13d0cfc2f549d7c5fbf7f1e60219/sdk/notificationhubs/Microsoft.Azure.Management.NotificationHubs/src/Properties/AssemblyInfo.cs#L10

```
 [assembly: AssemblyVersion("2.0.0.0")]
 [assembly: AssemblyFileVersion("2.4.0.0")]
```

Normally the value of those two properties should be the same as the package version, see [MSDoc](https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/general/general/assembly-version-assembly-file-version) for details. Here is an example: https://github.com/Azure/azure-sdk-for-net/blob/353615e31efc13d0cfc2f549d7c5fbf7f1e60219/sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/Properties/AssemblyInfo.cs#L9

**Comment by mpodwysocki** [comment]
@archerzz What do you propose changing it to since our version is 2.3.4 as per this PR, however, the `AssemblyFileVersion` is 2.4.  Should we just update the entire package to 2.4 to avoid downgrades?

**Comment by archerzz** [comment]
> [mpodwysocki](/mpodwysocki)

@mpodwysocki Let's bump the `AssemblyVersion` to `2.3.4` this time, since only `AssemblyVersion` is used by .Net framework according to the [doc](https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/general/general/assembly-version-assembly-file-version).

Next time when the version exceeds `2.4.0`, let's bump the `AssemblyFileVersion` as well.

**Comment by mpodwysocki** [comment]
@archerzz Done!

**Review by archerzz — APPROVED** [review]

**Comment by archerzz** [comment]
> @archerzz Done!

@mpodwysocki Thanks! Merging~~~

**Pull request merged**
