### PR TITLE
Changes related to dedicated host group automatic placement

### PR DESCRIPTION
**Pull request by dochung4**

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @dochung4 please put a link to your openapi spec PR here, thanks

**Comment by dochung4** [comment]
> Hi @dochung4 please put a link to your openapi spec PR here, thanks

Here it is: https://github.com/Azure/azure-rest-api-specs/pull/9684

**Comment by isra-fel** [comment]
The openapi spec PR is not merged. Please regerente SDK after that. Thanks

**Comment by dochung4** [comment]
> The openapi spec PR is not merged. Please regerente SDK after that. Thanks

SDK in this PR is based on the latest change in the openapi spec PR. Whenever the openapi spec PR is updated, I will regenerate the SDK and update this PR accordingly. You don't have to approve now, but please review, so that it could be completed in a timely manner, after the openapi spec PR is checked in.

**Comment by isra-fel** [comment]
Generally looks good

**Pull request merged**
