### PR TITLE
Fix Azure.Core dependencies for .NET 5.0

### PR DESCRIPTION
**Pull request by pentp**
This removes dependencies that are inbox for .NET 5.0.

### CODE REVIEW

**Comment by pakrym** [comment]
We tried this change and it didn't work. See #10326 for details.

**Comment by pentp** [comment]
`Microsoft.Bcl.AsyncInterfaces` looks a bit "special", but all the System.* packages should be fine to remove even if other packages are compiled against the netstandard2.0 version.

**Comment by pakrym** [comment]
What are you trying to improve in this PR? When published for net5.0 the extra dependencies are trimmed away.

**Comment by pentp** [comment]
I'm trying to get rid of obsolete dependencies when using Azure libraries from .NET 5 apps.

**Comment by pakrym** [comment]
Do you see them when you publish?

**Comment by pentp** [comment]
No, this is mostly about cleaning up the restore phase (where the packages are actually downloaded, even if eventually they are not published).

**Comment by pakrym** [comment]
>No, this is mostly about cleaning up the restore phase (where the packages are actually downloaded, even if eventually they are not published).

Unfortunately Azure.Core change won't help with that. Most of the client libraries target netstandard and take a direct dependency on System.* packages. We would have to cross-compile all of them as well.

**Comment by pentp** [comment]
It should help somewhat - the other packages don't need to take a direct dependency (and at least some of them don't) - they take the System.* dependencies indirectly through Azure.Core.

**Comment by pakrym** [comment]
Hi @pentp, thank you for the contribution. Unfortunately, the benefit/risk ratio is very low for this change.

It doesn't bring a major improvement for customers and the last time we did a similar change it created a lot of disruption.

**Comment by pentp** [comment]
Can we do the change at least for a future .NET 6.0 target?

**Comment by pakrym** [comment]
I don't think this change is worth doing as there is no clear benefit to it.

**Comment by pentp** [comment]
But you're going to drop those legacy package references at some point, why not do it for .NET 6?

**Pull request closed without merging**
