### PR TITLE
SDK client changes for Traffic Manager API 2018-04-01

### PR DESCRIPTION
**Pull request by allencal**
## Description

https://github.com/azure/azure-rest-api-specs/pull/3361
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by dsgouda** [comment]
@MikhailTryakhov is this a part of the release plan for network?
@allencal please discuss with Mikhail.

**Comment by MikhailTryakhov** [comment]
@allencal @dsgouda all these changes are in traffic manager... not quite sure what can I do here

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please regenerate the code using `generate.ps1` [here](https://github.com/allencal/azure-sdk-for-net/blob/5cd124e5340133e8bb9b426ccbc4474c77fd36ce/src/SDKs/TrafficManager/Management.TrafficManager/generate.ps1) and update the PR

**Comment by allencal** [comment]
AzSdk.RP.props deleted. Operations and models regenerated.

**Comment by allencal** [comment]
Deleting - I'll create a fresh pull request. Accidentally clobbered this one.

**Pull request closed without merging**
