### PR TITLE
Update CDN package base on Latest Swagger

### PR DESCRIPTION
**Pull request by hytao**
Regenerated SDK package base on latest CDN swagger.
Feature Added:
UrlRewrite and CacheKeyQueryString Action for RulesEngine.

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hey @hytao , the changes generally look good to me. However the metadata txt is in the wrong path -- should be `eng\mgmt\mgmtmetadata\<rpName>.txt`.

This could be caused by out-dated build tools. Could you try rebuilding the tools by `msbuild eng/mgmt.proj /t:Util /p:UtilityName=InstallPsModules`, then run `generate.ps1` again?

Thanks

**Comment by hytao** [comment]
Hi @isra-fel , I have re-built the tool and re-run the generate.ps1. However, I did not see any change in metadata txt. Do you know other way to fix the problem? Is it possible to fix it manually?

**Comment by isra-fel** [comment]
I'm sorry, it seems no only the path is wrong, so is the content. I'm trying to figure out what is the cause. Will get back to you soon. Thanks

**Comment by isra-fel** [comment]
OK I got it now. Instead of using `generate.cmd`, please create a `generate.ps1` file containing
```ps1
Start-AutoRestCodeGeneration -ResourceProvider "cnd/resource-manager" -AutoRestVersion "latest"
```
Run the script and you'll get everything right 😁 
BTW please delete old `generate.cmd`

Thanks

**Comment by hytao** [comment]
I have regenerated SDK with generate.ps1. Thanks

**Comment by isra-fel** [comment]
Removed the metadata txt under `src/`

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
