### PR TITLE
Fix for Azure Pack websites site slot operation

### PR DESCRIPTION
**Pull request by theadriangreen**
Azure Pack returns 202 which is semantically correct for starting slot swapping operation. This change fixes the cmdlet.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@theadriangreen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (adriang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@theadriangreen please provide a link to hydra specs PR as well

**Comment by markcowl** [comment]
@theadriangreen Please respond to feedback and sync the PR, there are now merge conflicts

**Comment by markcowl** [comment]
@theadriangreen I have not seen any responses to feedback or updates to fix merge conflicts in this PR, therefore, I am assuming this is no longer relevant.  If you would still like to make these changes, please open a new PR.

**Comment by theadriangreen** [comment]
I'm sure it's still relevant, however I'm not on the team any more. Perhaps @jvano could comment.

**Pull request closed without merging**
