### PR TITLE
Remove deprecated Hybrid Data SDK

### PR DESCRIPTION
**Pull request by heaths**
Relates to #37660

### CODE REVIEW

**Review by ArthurMa1978 — CHANGES_REQUESTED** [review]
This is Track 2 SDK, don't remove

**Review by jsquire — DISMISSED** [review]
This one looks weird and inconsistent.   NuGet doesn't list this package as deprecated nor retired, and it's had a release in the last two months.  The previous releases are marked as unsupported - so something is weird here.  

Unsure if it should actually be retired or the data is incorrect.

//cc: @scottaddie, @MrJustinB

**Comment by heaths** [comment]
> This is Track 2 SDK, don't remove

@ArthurMa1978 that doesn't mean it's not deprecated. If the service was, so should the SDK. We need to find out whether it truly is deprecated regardless of whether it's track 1 or track 2.

**Comment by ArthurMa1978** [comment]
> > This is Track 2 SDK, don't remove
> 
> @ArthurMa1978 Arthur Ma FTE that doesn't mean it's not deprecated. If the service was, so should the SDK. We need to find out whether it truly is deprecated regardless of whether it's track 1 or track 2.

Let me confirm this with LaDonna

**Comment by ArthurMa1978** [comment]
@heaths confirmed, this RP has been deprecated, thank you!

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
