### PR TITLE
Re-enable key release tests

### LINKED ISSUE #38375: HTTP 400 trying to create key rotation policy: no "version" recognized
Despite using the same key rotation policy - decoded below - Managed HSM only is responding with,

> HTTP 400
> Key Release Policy: missing 'version' property (Activity ID: 2bb45756-439e-11ee-9480-6045bd6e6f36)

The request payload is:

```json
{
  "kty": "RSA-HSM",
  "key_size": 2048,
  "attributes": {
    "exportable": true
  },
  "release_policy": {
    "data": "ew0KICAgICJhbnlPZiI6IFsNCiAgICAgICAgew0KICAgICAgICAgICAgImFueU9mIjogWw0KICAgICAgICAgICAgICAgIHsNCiAgICAgICAgICAgICAgICAgICAgImNsYWltIjogInNkay10ZXN0IiwNCiAgICAgICAgICAgICAgICAgICAgImVxdWFscyI6ICJ0cnVlIg0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIF0sDQogICAgICAgICAgICAiYXV0aG9yaXR5IjogImh0dHBzOi8vdGNhYzdlOWM0MWVmNTJjZWNzaXRlLmF6dXJld2Vic2l0ZXMubmV0LyINCiAgICAgICAgfQ0KICAgIF0sDQogICAgInZlcnNpb24iOiAiMS4wLjAiDQp9",
    "immutable": false
  }
}
```

The decoded policy is:

```json
{
    "anyOf": [
        {
            "anyOf": [
                {
                    "claim": "sdk-test",
                    "equals": "true"
                }
            ],
            "authority": "https://tcac7e9c41ef52cecsite.azurewebsites.net/"
        }
    ],
    "version": "1.0.0"
}
```

### PR DESCRIPTION
**Pull request by heaths**
Resolves #38375

### CODE REVIEW

**Comment by heaths** [comment]
This won't work quite yet

**Review by vcolin7 — APPROVED** [review]

**Pull request closed without merging**
