### PR TITLE
[Azure Search] Add ability to generate from a path using tags

### PR DESCRIPTION
**Pull request by arv100kri**
To facilitate targeting specific swagger versions (data plane) generate scripts now take a tag parameter.
To generate from track 1 swagger

`.\generate.ps1 -SpecsRepoFork arv100kri -SpecsRepoBranch arv100kri/track1-freeze -Tag track1-package-2019-05`

### CODE REVIEW

**Review by bleroy — APPROVED** [review]

**Comment by brjohnstmsft** [comment]
No need to have special tags for api-versions older than 2019-05-06 (see my comment on the Swagger PR).

**Review by bitsforthought — APPROVED** [review]
Approving now, but won't merge until the Swagger change is merged.

**Comment by arv100kri** [comment]
> No need to have special tags for api-versions older than 2019-05-06 (see my comment on the Swagger PR).

Yup, think I fixed it in that PR

**Comment by arv100kri** [comment]
> Approving now, but won't merge until the Swagger change is merged.

No worries - I have the power to squash and merge here... So once that PR is checked in, I'll merge here

**Pull request merged**
