### PR TITLE
Add IsLoggingPIIEnabled to TokenCredentialOptions

### LINKED ISSUE #20140: [FEATURE REQ]Enable MSAL log
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
Azure.Identity should allow customers to configure MSAL logging levels, including PII info and platform loggings.

### PR DESCRIPTION
**Pull request by christothes**
This change adds a new property to DiagnosticsOptions to indicate whether logging of trace statements that possibly contain PII is enabled. There are various scenarios in Identity where this could be used, but it could also be utilized by clients.

closes #20140

### CODE REVIEW

**Comment by pakrym** [comment]
Are you sure anything identity has is PII? PII has a rather specific definition of `Personally identifiable information (PII) is any data that could potentially identify a specific individual.`.

**Comment by pakrym** [comment]
The other question about this flag is would I have to set it on my client only or both in the client and credential options/

**Comment by christothes** [comment]
> Are you sure anything identity has is PII? PII has a rather specific definition of `Personally identifiable information (PII) is any data that could potentially identify a specific individual.`.

There are a lot of other terms that specify the exact data classification, but PII seems like the general one that most people recognize. Do you have a suggestion for a better name?

**Comment by christothes** [comment]
> The other question about this flag is would I have to set it on my client only or both in the client and credential options?

TokenCredentialOptions derrives from ClientOptions 
https://github.com/Azure/azure-sdk-for-net/blob/5e6bcc0dd446cd0cbe204c00d190ef655e9d9c96/sdk/identity/Azure.Identity/src/TokenCredentialOptions.cs#L12

**Comment by pakrym** [comment]
`IsLoggin[Security/Authentication][Details/Diagnostics]Enabled`?

**Comment by jsquire** [comment]
> Do you have a suggestion for a better name?

`IsLoggingSensitiveInformationEnabled` ?   That may cover us for different categories, but I think it still asserts that it's not a good idea to do this in untrusted scenarios.

**Comment by christothes** [comment]
> > Do you have a suggestion for a better name?
> 
> `IsLoggingSensitiveInformationEnabled` ? That may cover us for different categories, but I think it still asserts that it's not a good idea to do this in untrusted scenarios.

I like this name the best, so far.

**Comment by pakrym** [comment]
I would like to see what features would go behind this switch and how they work first.

**Comment by christothes** [comment]
Here is one https://github.com/Azure/azure-sdk-for-net/pull/20354 

Another is using this setting as a hint to turn on the `EnablePiiLogging` switch for MSAL.

**Review by schaabs — APPROVED** [review]

**Pull request merged**
