### PR TITLE
[App Config] Fix test failures

### PR DESCRIPTION
**Pull request by ShivangiReja**
Fixting test failures: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1896914&view=results

These failures introduced in https://github.com/Azure/azure-sdk-for-net/pull/31588 PR.

### CODE REVIEW

**Comment by ShivangiReja** [comment]
I wonder why the CI pipeline didn't run this https://github.com/Azure/azure-sdk-for-net/pull/31588 PR?

**Comment by ShivangiReja** [comment]
I wonder why the CI pipeline didn't run this https://github.com/Azure/azure-sdk-for-net/pull/31588 PR?

CC: @weshaggard, @hallipr

**Review by jsquire — APPROVED** [review]

**Comment by ShivangiReja** [comment]
Ahh I see...it did trigger the ci pipeline https://dev.azure.com/azure-sdk/public/_build/results?buildId=1893557&view=results for [this](https://github.com/Azure/azure-sdk-for-net/pull/31588) PR but there was an issue in the ci.yaml that's why the tests cases didn't run for [this](https://github.com/Azure/azure-sdk-for-net/pull/31588) PR.

The issue in ci.yaml is now fixed here https://github.com/Azure/azure-sdk-for-net/commit/2b44628fd882aeaf77f6c59705fcb2c0b84f925f and test cases are runing for this PR.

**Comment by weshaggard** [comment]
@ShivangiReja exactly.

**Pull request merged**
