### PR TITLE
[Cogs Face] Generate latest Face SDK from Swagger, including the Snapshot features of Face API.

### PR DESCRIPTION
**Pull request by lebronJ**
Regenerate Face SDK with latest spec Azure/azure-rest-api-specs#5074
* Add unit test cases for new Snapshot feature (new API interfaces), record unit-test session records.
* Increment package version to 2.3.0-preview.
* Add release notes.
* This has been internally reviewed (lebronJ/azure-sdk-for-net#3) inside Face SDK team.

**Hopefully this can take short time and catch our rollout (started on Jan 21st and will last a week) timeline.**
(This should also upgrade the documentation to [Face .NET SDK documentation](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/cognitiveservices/client/face?view=azure-dotnet).)

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@lebronJ  Please join the Azure org on github [here](aka.ms/azuregithub) to kick off the build.

**Comment by lebronJ** [comment]
> @lebronJ Please join the Azure org on github [here](aka.ms/azuregithub) to kick off the build.

@dsgouda Thanks. I think I am already a member of Azure org, could you please help show me how to kick off this build? (BTW, as I know this build is not mandatory).

And who will be the second reviewer? Thanks!

image

**Comment by dsgouda** [comment]
@azuresdkci Test this please

**Comment by dsgouda** [comment]
@azuresdkci retest this please

**Comment by dsgouda** [comment]
@lebronJ Please note that we have switched our default branch to master instead of psSdkJson6 now

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
