### PR TITLE
Adding DataLake endpoints

### PR DESCRIPTION
**Pull request by begoldsm**
DataLake endpoints being added to the public repo

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@begoldsm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (begoldsm). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@begoldsm TestDependencies\Packages.config: there should be no management libraries here, this is specifically test libraries that are common across all versions.  Also, you need to update the Hyak version hgere to 1.0.3

**Comment by markcowl** [comment]
@begoldsm:  why all the changes to the authorization library?

**Comment by markcowl** [comment]
@begoldsm changes look good.  one last thing, all your nuspec files still havethe phrase 'microsoft confidential - not ship in public'  in the package summary and description that will show up in the nugget gallery.  You will want to update this and review the other metadata before we merge and publish these.

Everything else looks good.

**Comment by begoldsm** [comment]
@markcowl I have removed the "do not ship" text and the references to "internal". I also reverted the change to KeyVault and ensured it is really the same as what is in Azure AutoRest. Once the CI job completes successfully we should be good to merge.

**Pull request merged**
