### PR TITLE
Disable public anonymous blob access for live resource tests

### PR DESCRIPTION
**Pull request by benbp**
Putting this PR up to help get us in compliance, and to raise any discussions about places where this is necessary for SDK testing

### CODE REVIEW

**Comment by seanmcc-msft** [comment]
@benbp, can we wait until https://github.com/Azure/azure-sdk-for-net/pull/44427 merges?  Otherwise basically all storage live tests will fail.  In that PR, I removed our dependency on Entra app secrets and modified our tests to not require public access.

**Review by mikeharder — APPROVED** [review]

**Comment by benbp** [comment]
> @benbp, can we wait until #44427 merges? Otherwise basically all storage live tests will fail. In that PR, I removed our dependency on Entra app secrets and modified our tests to not require public access.

Sounds good, thanks for letting me know @seanmcc-msft!

**Review by weshaggard — APPROVED** [review]

**Review by jsquire — APPROVED** [review]

**Comment by weshaggard** [comment]
@seanmcc-msft do you think the storage tests are ready for this update now? I kicked of a test pipeline to verify.

**Pull request closed without merging**
