### PR TITLE
CDN regeneration after swagger cleanup

### PR DESCRIPTION
**Pull request by hovsepm**

### CODE REVIEW

**Comment by markcowl** [comment]
@hovsepm We should ask the service team contact to sign off on the PR.

**Comment by csmengwan** [comment]
Sign off!

**Review by markcowl — CHANGES_REQUESTED** [review]
This requires a major version update

**Comment by hovsepm** [comment]
csmengwan will create a new PR with after latest swagger fixes and will do the major version update there.

**Pull request closed without merging**
