### PR TITLE
Enum value changes and samples for traffic manager, dns and vm from custom and specialized image

### PR DESCRIPTION
**Pull request by anuchandy**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anuchandy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anuchan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
> using System.Reflection;

where is my license headers? :))

---
Refers to: Samples/ResourceManagement/Dns/ManageDns/Properties/AssemblyInfo.cs:1 in cfe168f. [](commit_id = cfe168f27f7cdbe86f6ae61f1db32e40caeb9d7f, deletion_comment = False)

**Comment by hovsepm** [comment]
> using System.Reflection;

where are my license headers? :))

---
Refers to: Samples/ResourceManagement/TrafficManager/ManageTrafficManager/Properties/AssemblyInfo.cs:1 in cfe168f. [](commit_id = cfe168f27f7cdbe86f6ae61f1db32e40caeb9d7f, deletion_comment = False)

**Comment by hovsepm** [comment]
> using System.Reflection;

where are my license headers? :))

---
Refers to: Samples/ResourceManagement/Compute/CreateVMsUsingCustomImageOrSpecializedVHD/Properties/AssemblyInfo.cs:1 in cfe168f. [](commit_id = cfe168f27f7cdbe86f6ae61f1db32e40caeb9d7f, deletion_comment = False)

**Comment by anuchandy** [comment]
@hovsepm ah.. your license header is on the way.. :) // thanks - will update PR

**Comment by anuchandy** [comment]
@hovsepm uncommented the app service usage sections in the samples as we discussed, please review..

**Comment by jianghaolu** [comment]
@azureadkci retest this please

**Pull request merged**
