### PR TITLE
Added support for Application Gateway Web Application Firewall

### PR DESCRIPTION
**Pull request by allanbomsft**
Added a field to the application gateway object to hold the configuration for the web application firewall.
Added the new SKUs.
Bumped up the version number.
Updated the test code and mock recording (hardcoded location to "West Central US" as this is a region that gets updated early, and resource provider rollout is very time consuming these days).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@allanbomsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (allanbo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by shahabhijeet** [comment]
@azuresdkci retest this please

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Pull request merged**
