### PR TITLE
Dh resize

### PR DESCRIPTION
**Pull request by cakarata**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by archerzz — CHANGES_REQUESTED** [review]
Make sure you update the following files, according to [the guide](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=track-1-sdk-generation-from-updated-spec).

- `AzSDK.RP.Props`
- `eng\mgmt\mgmtmetadata\<rpName>.txt`
- `AssemblyInfo.cs`

**Comment by archerzz** [comment]
@grizzlytheodore FYI

**Comment by grizzlytheodore** [comment]
this PR needs to go to feature/cplat-2023-03-01 branch @cakarata

**Comment by cakarata** [comment]
> this PR needs to go to feature/cplat-2023-03-01 branch @cakarata

I have changed the target branch. @grizzlytheodore and @archerzz let me know if I still need to generate these files :

AzSDK.RP.Props
eng\mgmt\mgmtmetadata\<rpName>.txt
AssemblyInfo.cs

**Review by grizzlytheodore — APPROVED** [review]

**Review by grizzlytheodore — APPROVED** [review]

**Pull request merged**
