### PR TITLE
Fix keyvault Readme issues

### PR DESCRIPTION
**Pull request by Tianyun-G**
Fix issues https://github.com/Azure/azure-sdk-for-net/issues/14531, https://github.com/Azure/azure-sdk-for-net/issues/14530, https://github.com/Azure/azure-sdk-for-net/issues/14529.

### CODE REVIEW

**Review by heaths — APPROVED** [review]
The changes look fine, but why were they necessary? We normally only use a link table when links are used multiple times. Specifying them inline is valid and easier when they are only used once. Should we expect more such changes?

**Comment by Tianyun-G** [comment]
@heaths - We do this to unify the format, as it is used in other readme files. Such as: [TextAnalytics Readme](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/textanalytics/Azure.AI.TextAnalytics#contributing).

**Comment by heaths** [comment]
Okay, but the format is markdown. Both inline and reference table links are supported. I'm just pointing out that changing these links isn't necessary.

If anything, customers reading the raw markdown (the format was designed to be human-readable even without rendering, drawing on common text file patterns for "formatting" text) will find this harder, since now they have to go hunt for the link instead of just clicking on it (e.g. in VSCode, shift+click on the inline link opens it in your browser or, if relative within the repo, right in VSCode).

**Comment by Tianyun-G** [comment]
@heaths  -First of all, in the KeyVault Certificates readme, `CONTRIBUTING.md` is an incorrect inline format, as shown in the figure below.
Secondly, because the readme of other services is in the reference format, we changed it to the reference format.
image

**Pull request merged**
