### PR TITLE
Azure Security Center - Update AdvancedThreatProtection

### PR DESCRIPTION
**Pull request by yoavfr**
- Swagger change here https://github.com/Azure/azure-rest-api-specs/pull/8264
- [security_resource-manager.txt](https://microsofteur-my.sharepoint.com/:t:/g/personal/yoavf_microsoft_com/EVarBIY--IxDo6PU-1CD808B4_LTFlW000CARtdYDnIpcg?e=aLfuYY)

### CODE REVIEW

**Comment by yoavfr** [comment]
Swagger change here https://github.com/Azure/azure-rest-api-specs/pull/8264

**Comment by yoavfr** [comment]
Hi,
@erich-wang & @isra-fel 
Awaiting your CR on this.
Thanks,
Yoav

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @yoavfr , please
- Add a link to the swagger spec review PR in the description
- Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update api tag in `AzSdk.RP.props`, release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release
- Write new tests to cover new generated code

Thanks

**Comment by yoavfr** [comment]
> Hi @yoavfr , please
> 
> * Add a link to the swagger spec review PR in the description
> * Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
> * Update api tag in `AzSdk.RP.props`, release notes in csproj
> * Update versions in csproj and `assemblyinfo.cs` if you are going to release
> * Write new tests to cover new generated code
> 
> Thanks

@isra-fel 
* link was included before. Moved to description field
* Done
* Done
* Done
* Not applicable - this is an API version change

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi, there are still some things left:
- Because of API version update, I believe there are breaking changes, so the major version needs to be updated, i.e. becomes 2.0.0. (Applies to csproj and AssemblyInfo.cs)
  - Besides the  `<AzureApiTag>` section in src/AzSdk.RP.props needs to be updated
- Need to check in `eng/mgmt/mgmtmetadata/security_resource-manager.txt`
Thanks

**Comment by yoavfr** [comment]
> Hi, there are still some things left:
> 
> * Because of API version update, I believe there are breaking changes, so the major version needs to be updated, i.e. becomes 2.0.0. (Applies to csproj and AssemblyInfo.cs)
>   
>   * Besides the  `<AzureApiTag>` section in src/AzSdk.RP.props needs to be updated
> * Need to check in `eng/mgmt/mgmtmetadata/security_resource-manager.txt`
>   Thanks

Hi,
* I don't think this qualifies as a breaking change. The API itself has not changed - just the version. We GA'd so we removed the "preview" and updated the date. The Resource Provider has not changed. If I am getting this wrong, please let me know.
* I don't think anything has changes as a result of this version update in `<AzureApiTag>` section in src/AzSdk.RP.props. What am I missing?
* There were no changes in  `eng/mgmt/mgmtmetadata/security_resource-manager.txt` or any other files under eng.

**Comment by yoavfr** [comment]
@erich-wang & @isra-fel
Awaiting your approval of this.
Thanks,
Yoav

**Comment by yoavfr** [comment]
@isra-fel & @erich-wang 
Hi,
This has been languishing for quite some time now, can you please push this through?
Thanks,
Yoav

**Comment by isra-fel** [comment]
I agree with the api version thing. As for the metadata txt, first it is required for every PR, second it can't be unchanged, I mean it contains the actual git commit hashcode that your SDK is generated from, so it must be different from last checkin.

One possibility is your build tools is out of data, please [follow this](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools) to update and generate again.

Thanks

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
