### PR TITLE
[DataFactorySDK]-Add AzureFileStorage and GoogleCloudStorage

### PR DESCRIPTION
**Pull request by wenbof-zz**
SDK for https://github.com/Azure/azure-rest-api-specs/pull/7308

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @wenbof , could you pleaes include the `.txt` file generated when you run `generate.ps1`? [(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)

Thanks

**Comment by wenbof** [comment]
> Hi @wenbof , could you pleaes include the .txt file generated when you run generate.ps1? (details)
> Thanks

Thanks for your quick review. This is the rehearsal SDK change for the swagger change. these were generated using local swagger. will generate with the remote master swagger and update another commit to this PR once my swagger change is checked in which will then include the .txt file.

**Comment by isra-fel** [comment]
> @isra-fel
> Thanks for your quick review. This is the rehearsal SDK change for the swagger change. these were generated using local swagger. will generate with the remote master swagger and update another commit to this PR once my swagger change is checked in which will then include the .txt file.

Got it. Let me know when it's ready for review. Thanks

**Comment by isra-fel** [comment]
@wenbof ping on this

**Comment by wenbof** [comment]
Thanks Yeming. Abandon this.

**Pull request closed without merging**
