### PR TITLE
Fix tests so they delete any settings they add. Azure#8068

### LINKED ISSUE #8068: Fix tests so they delete any settings they add.
Currently the AZConfig library has tests that add some settings but does not clean them up after execution. Need to clean up settings added by tests.

### PR DESCRIPTION
**Pull request by Prince269090**
Deleted keys generated by below test methods 

GetBatchSettingStartsWith
GetBatchSettingEndsWith
GetBatchSettingContains
GetBatchSettingsWithMultipleLabels

Fixes #8068

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
Hi and thanks for the contribution!

With the test change we also need to update the test recordings as the request we send will be different.

/cc @AlexanderSher @annelo-msft

**Comment by Prince269090** [comment]
Thanks @AlexGhiondea for the update. I have updated the PR with recordings change. 

/cc @AlexanderSher  @annelo-msft

**Comment by annelo-msft** [comment]
It looks like some of the special character configuration settings  "~`!@#$^&()_+=[]{}|;"'<>./--<id>" still aren't being deleted.

**Comment by Prince269090** [comment]
@annelo-msft , i have updated the test records. So CI is passing now. Regarding the 'special characters', i have observed that its not working with Azure Portal as well. So it could have been the same case (the API is not deleting) while we send request to Azure API.

**Azure Portal**

Key-Value Deletion

**Comment by annelo-msft** [comment]
@Prince269090, thanks for this investigation! 

Would you be willing to file issues for the item's you've found?  If you have a consistent repro for the issue with the service, it would be great to file an issue in their repo: https://github.com/Azure/AppConfiguration/issues

For issues on the client side, please file an issue here and tag it with the AzConfig label, so we can follow these items through.

Thanks so much for all your help with this!

**Review by annelo-msft — APPROVED** [review]
Per offline discussion and comments in this PR, please file issues for remaining settings that aren't correctly deleted from by our tests.  Thanks so much for your contribution!

**Comment by Prince269090** [comment]
@annelo-msft , i have created issue in the repo. [https://github.com/Azure/azure-sdk-for-net/issues/8624](url). Seems i don't have rights to add the 'AzConfig' label.

Also, issue added in another repo for azure key deletion. [https://github.com/Azure/AppConfiguration/issues/181](url)

**Pull request merged**
