### PR TITLE
[Monitor] SDK Version 0.20.0-preview - Add Metric Alerts SDK

### PR DESCRIPTION
**Pull request by sanjaypavan**
## Description
- Adding Metric Alerts SDK. This is a new SDK is used to create metric alerts on Azure. 
- There are a series of pull requests merged before we generated the SDK. Added all the changes below. 
    https://github.com/Azure/azure-rest-api-specs/pull/3108
    https://github.com/Azure/azure-rest-api-specs/pull/2787
    https://github.com/Azure/azure-rest-api-specs/pull/3108
    https://github.com/Azure/azure-rest-api-specs/pull/3128

- The link to Swagger spec for this SDK
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/microsoft.insights/stable/2018-03-01/metricAlert_API.json
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by dsgouda — CHANGES_REQUESTED** [review]
- Please link the old PR to make the review easier
- Please regenerate the code using generate.ps1 and commit changes to the txt file.

**Comment by sanjaypavan** [comment]
1. Here is the old PR for which was closed because of not able to Squash the commits https://github.com/Azure/azure-sdk-for-net/pull/4417
2. As requested the monitor_resource-manager.txt file is added to the PR.

**Comment by dsgouda** [comment]
@azuresdkci Retest this please

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
