### PR TITLE
API Management onboarding

### PR DESCRIPTION
**Pull request by ailn**
This is an SDK for managing API Management service (http://azure.microsoft.com/en-us/documentation/articles/api-management-key-concepts/):

CRUD services
backup/restore
manage deployments, custom hostname, vpn configuration
any questions please email to ailn@microsoft.com or apicore@microsoft.com

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ailn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ailn). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@ailn there are merge conflicts, please update

**Comment by ogail** [comment]
@azuresdkci add to whitelist

**Comment by yugangw-msft** [comment]
recommend to update azure.common to 2.0.3

**Pull request merged**
