### PR TITLE
Updated readme.md to fix formatting issues

### PR DESCRIPTION
**Pull request by amitbapat**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@amitbapat__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by amitbapat** [comment]
I am Microsoft employee, so I wonder why CLA is required?

**Comment by hovsepm** [comment]
CC @pomortaz

**Comment by pomortaz** [comment]
@hovsepm and @amitbapat thanks! LGTM.

**Pull request merged**
