### PR TITLE
[Resources] Add deployment scripts resource type to the Resources SDK

### PR DESCRIPTION
**Pull request by filizt**
The new preview version of Resources SDK will support deployment scripts resource type. This new resource type is added to the Resources namespace. 

Link to the swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/7486

### Question for the reviewer

There was a name clash while generating the Page.cs - I renamed our Page.cs file temporarily. I see that there are already two separate page classes in the SDK (see Page.cs and Page1.cs) Should we rename our page class to Page2? If so, is there a automated way of doing it through Autorest(AFAIK there is none) or should we do it manually? I would think doing it manually will create extra work in the future if/when we re-generate the SDK since we need to rename the class again. It'd be good to know if this can be done through Autorest.

Another option would be using the class that is already in the project. Though this also might not be ideal since we'll be tying our code to a class that is being generated by some other swagger. 

What would be a good way to solve this issue? Your help in this matter is appreciated.

### CODE REVIEW

**Comment by isra-fel** [comment]
@AlexGhiondea @kurtzeborn Hi, resources team met something like an autorest bug. Could you help investigate? Thanks

**Comment by isra-fel** [comment]
Hi @filizt , you'll need the following things:
- Add a link to the swagger spec review PR in the description
- Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update versions, tags, if necessary
- Tests
Thanks

**Comment by AlexGhiondea** [comment]
@erich-wang could you help with this?

**Comment by fearthecowboy** [comment]
Where is the spec that contains the schema that is called `page`?

**Comment by filizt** [comment]
> Where is the spec that contains the schema that is called `page`?

Here's the swagger that we use to generate our SDK. The page.cs gets created by the autorest since we have a pagable list call.

` "x-ms-pageable": {
          "nextLinkName": "nextLink"
        }
`

**Comment by fearthecowboy** [comment]
Ok, I'm thoroughly confused here.

Are you saying the generator is creating a third `Page.cs` class in addition to the `Page` and `Page1` classes in Models?

Where does the extra `Page.cs`  that you have to delete come from? 

>> Another option would be using the class that is already in the project. Though this also might not be ideal since we'll be tying our code to a class that is being generated by some other swagger.

The `Page.cs` class that generated by the c# generator will be the same no matter which swagger file created it. 

And given that no new work is going into that generator, it's not going to change.

**Comment by filizt** [comment]
> Hi @filizt , you'll need the following things:
> 
> * Add a link to the swagger spec review PR in the description
> * Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
> * Update versions, tags, if necessary
> * Fix existing tests and write new ones to cover new code
>   Thanks

@isra-fel I have included the generated .txt file, updated versions, and tags. Could you see if I'm missing anything?

I'm recording tests and will submit them soon.

**Comment by filizt** [comment]
> Ok, I'm thoroughly confused here.
> 
> Are you saying the generator is creating a third `Page.cs` class in addition to the `Page` and `Page1` classes in Models?
> 
> Where does the extra `Page.cs` that you have to delete come from?
> 
> > > Another option would be using the class that is already in the project. Though this also might not be ideal since we'll be tying our code to a class that is being generated by some other swagger.
> 
> The `Page.cs` class that generated by the c# generator will be the same no matter which swagger file created it.
> 
> And given that no new work is going into that generator, it's not going to change.

@fearthecowboy Sorry for the confusion. Let me try to elaborate. 

I think the root of my question is coming from the fact that there are two Page files in Models in the Microsoft.Resources SDK: Page.cs and Page1.cs.  I'm curious to find out why that is and if autorest tool created these two separate Page files. 

Here're the Page files I am referring to: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/resources/Microsoft.Azure.Management.Resource/src/Generated/Models

**Comment by fearthecowboy** [comment]
The C# generator did create both of those.

I'm not entirely sure why it does that. It's not going to affect anything, there's not any reason to do anything with them.

**Comment by filizt** [comment]
> > Hi @filizt , you'll need the following things:
> > 
> > * Add a link to the swagger spec review PR in the description
> > * Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
> > * Update versions, tags, if necessary
> > * Fix existing tests and write new ones to cover new code
> >   Thanks
> 
> @isra-fel I have included the generated .txt file, updated versions, and tags. Could you see if I'm missing anything?
> 
> I'm recording tests and will submit them soon.

Submited the test recordings. Also updated the version number as per out discussion. Is there anything else missing from the PR?

**Comment by isra-fel** [comment]
> Submited the test recordings. Also updated the version number as per out discussion. Is there anything else missing from the PR?

Looks good to me

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
