### PR TITLE
Add link management client

### PR DESCRIPTION
**Pull request by vivsriaus**

### CODE REVIEW

**Comment by markcowl** [comment]
@vivsriaus There are build failures, please fix.

**Comment by vivsriaus** [comment]
@markcowl I was missing updates to generated code. It's now fixed. Thanks.

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by vivsriaus** [comment]
@shahabhijeet @markcowl Can we please merge this PR? Thanks.

**Pull request merged**
