### PR TITLE
New SDK update for Automation - 3.2.0-preview

### PR DESCRIPTION
**Pull request by vrdmr**
## Description
Contains changes introduced in the following spec changes:
https://github.com/Azure/azure-rest-api-specs/pull/3363
https://github.com/Azure/azure-rest-api-specs/pull/3420

Other changes:
- Enabled the Runbook tests and rerecorded them.
- Bumped up the version of the SDK - `3.2.0-preview`.

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by shahabhijeet — APPROVED** [review]

**Comment by shahabhijeet** [comment]
@vrdmr how come you have a breaking change in your stable API version for runbook spec?
is that something you intend to do in a stable version of API?

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@vrdmr will merge once you address @shahabhijeet 's comments

**Comment by vrdmr** [comment]
@shahabhijeet The changes in the Runbook resource are to revert the resource to its original shape (which were changed in https://github.com/Azure/azure-rest-api-specs/pull/2466). The changes are in the RunbookContent (Get and Put) call to now use `format:file`, which in the SDK now Streams rather than string (which was failing earlier).

Please let me know if you have any more questions.

**Comment by shahabhijeet** [comment]
@vrdmr from what we talked, this change is about restoring the old behavior and not introducing breaking change.

**Pull request merged**
