### PR TITLE
[ServiceBus] RuleManager small improvements

### PR DESCRIPTION
**Pull request by danielmarbach**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by jsquire — APPROVED** [review]
The title of the PR is concerning, but the changes look good!   I'm doing to defer to @JoshLove-msft for the authoritative review.

**Comment by danielmarbach** [comment]
Sorry my bad. Fixed

**Comment by jsquire** [comment]
> Sorry my bad. Fixed

All good.   I'm just being a goon.

**Review by JoshLove-msft — APPROVED** [review]
Thanks @danielmarbach!

**Pull request merged**
