### PR TITLE
[Azure Search] Prepare for Autocomplete API and merge from GA branch

### PR DESCRIPTION
**Pull request by bitsforthought**
## Description
See individual commits for details.

FYI @mhko @Yahnoosh 
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by mhko — APPROVED** [review]
Please see my question about the target api-version.

**Comment by dsgouda** [comment]
@azuresdkci retest this please

**Review by dsgouda — APPROVED** [review]

**Comment by brjohnstmsft** [comment]
@mhko Yes, as discussed we will bump the REST API version too.

**Comment by brjohnstmsft** [comment]
@dsgouda @shahabhijeet Any idea what this "default" check is that is blocking merge? There's no "Details" link to click on. Is this a configuration issue with this branch?

**Comment by brjohnstmsft** [comment]
@dsgouda Yes, please merge. I'll make the suggested changes in a subsequent PR.

Do you know why it won't let me merge though? @shahabhijeet should have set my team up with push access to this branch.

**Pull request merged**
