### PR TITLE
Messaging APIs for IoT Hub - Option 2

### PR DESCRIPTION
**Pull request by abhipsaMisra**
Bare minimum swagger modification required to be able to use the send c2d messaging API over HTTP.

- Confirm the names of the keys to be added to http request hedaer.
- All fields have been marked as "required". Service team needs to scrub through it, and confirm which fields are required.
- This swagger version does not have a setter for setting user application properties into the http request header. The current Amqp implementation sets it to Amqp message application properties, so the service team needs to provide the corresponding holder for http.

Current swagger: https://github.com/Azure/azure-sdk-for-net/commit/0730149ca3564a3a69f0c427eb13825573c2a7d0?w=1
Proposed modifications: https://github.com/Azure/azure-sdk-for-net/compare/0730149ca3564a3a69f0c427eb13825573c2a7d0..ead1428af32539c4419445065ca28386345aa50e?w=1

The public API that the SDK would expose would still take in a `CloudToDeviceMessage` object. Internally the SDK would translate each field in `CloudToDeviceMessage` to corresponding header required by the autorest generated code.

### CODE REVIEW

**Comment by vinagesh** [comment]
Update API surface too

**Review by vinagesh — APPROVED** [review]

**Comment by abhipsaMisra** [comment]
> Update API surface too?

Sure, will do!

**Comment by jsquire** [comment]
Hi @abhipsaMisra.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by abhipsaMisra** [comment]
This work item isn't being currently worked on. I'll close this PR, and will revisit it once we resume the work on this.
Thanks for the reminder!

**Comment by abhipsaMisra** [comment]
Closing this until service team addresses the open issue with the swagger doc.

**Pull request closed without merging**
