### PR TITLE
[App Configuration] Rename protocol methods

### LINKED ISSUE #31563: [App Configuration] Rename protocol methods and use the same names as convenience APIs
### Library name

Azure.Data.AppConfiguration

### Please describe the feature.

Update protocol method names as below:

**Methods**-

| Description                             | Convenience Methods                     |  Current Protocol Method Names                            | Rename Protocol Method Names
|-----------------------------------------|-----------------------------------------|-----------------------------------------|-----------------------------------------|
|  Creates a setting only if it does not already exist                |  AddConfigurationSetting                | PutKeyValue                             | SetConfigurationSetting                             |
| Deletes a setting from the configuration store                          |  DeleteConfigurationSetting             | DeleteKeyValue                          |  DeleteConfigurationSetting                          |
| Retrieves an existing setting from the configuration store                             |  GetConfigurationSetting                | GetKeyValue                             | GetConfigurationSetting                |
| Retrieves one or more settings from the configuration store                          |  GetConfigurationSettings               | GetKeyValues                            |   GetConfigurationSettings |
| Retrieves the revisions of one or more settings                            |  GetRevisions                           | GetRevisions                            |  GetRevisions |
| Creates a setting if it doesn't exist or overwrites the existing setting   |  SetConfigurationSetting                | PutKeyValue                             |   SetConfigurationSetting |
| Sets an existing setting to read only or read write state in the configuration store.        |  SetReadOnly                            | isReadOnly ? PutLock: DeleteLock        |         isReadOnly ? CreateReadOnlyLock: DeleteReadOnlyLock      |

### PR DESCRIPTION
**Pull request by ShivangiReja**
Rename protocol methods as per https://github.com/Azure/azure-sdk-for-net/issues/31563

Fixes: https://github.com/Azure/azure-sdk-for-net/issues/31563

### CODE REVIEW

**Comment by ShivangiReja** [comment]
Hi @annelo-msft - Some of the test cases are failing in this PR with [this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1900979&view=logs&j=d3fdcdd1-7a8e-5668-5e2b-ac9753b27d6a&t=f5732798-2186-52b7-c01a-94bd4fc48c7a&l=478) error and I think it's coming from [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs#L207).
```
Message: 
  Expected: <Azure.RequestFailedException>
  But was:  <System.InvalidOperationException: Expected scope ConfigurationClient.SetConfigurationSetting to be marked as failed but it succeeded
```
Here is one of the case: [This](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationMockTests.cs#L251-L263) mock test is calling `SetConfigurationSettingAsync` method. In this convenience method, I'm setting [ErrorOptions.NoThrow](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L270) in RequestContext when it calls the protocol method because I want the response from the protocol method and throw the same error message as GA'ed library. When we throw an error from the convenience API, it throws `<System.InvalidOperationException: Expected scope ConfigurationClient.SetConfigurationSetting to be marked as failed but it succeeded` error. 

I believe the issue is we are not marking scope as failed in the convenience method. @annelo-msft  Do you know if there is any way I can access scope [here](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L280-L283) and call scope.Failed(exception) or `ClientDiagnostics.CreateRequestFailedExceptionAsync` should internally call scope.Failed(exception) method?

**Comment by ShivangiReja** [comment]
Hi @lmolkova and @annelo-msft - Some of the test cases are failing in this PR with [this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1900979&view=logs&j=d3fdcdd1-7a8e-5668-5e2b-ac9753b27d6a&t=f5732798-2186-52b7-c01a-94bd4fc48c7a&l=478) error and I think it's coming from [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs#L207).
```
Message: 
  Expected: <Azure.RequestFailedException>
  But was:  <System.InvalidOperationException: Expected scope ConfigurationClient.SetConfigurationSetting to be marked as failed but it succeeded
```
Here is one of the case: [This](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationMockTests.cs#L251-L263) mock test is calling `SetConfigurationSettingAsync` method. In this [convenience method](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L266)(outer method), I'm setting [ErrorOptions.NoThrow](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L270) in RequestContext when it calls the [protocol method](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/Generated/ConfigurationClient.cs#L291)(inner method) because I want the response from the protocol method and throw the same error message as GA'ed library. When we throw an error from the convenience API, it throws `<System.InvalidOperationException: Expected scope ConfigurationClient.SetConfigurationSetting to be marked as failed but it succeeded` error. 

I believe the issue is we are not marking scope as failed in the convenience method. @lmolkova /@annelo-msft  Do you know if there is any way I can access scope [here](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L280-L283) and call `scope.Failed(exception)` or `ClientDiagnostics.CreateRequestFailedExceptionAsync` should internally call `scope.Failed(exception)` method or do we need to create an outer scope for this method?

**Comment by annelo-msft** [comment]
@JoshLove-msft is doing a lot of work in the .NET Distributed Tracing, space, @JoshLove-msft, is this something you'd be willing to look into?

**Comment by JoshLove-msft** [comment]
> I believe the issue is we are not marking scope as failed in the convenience method. @lmolkova /@annelo-msft Do you know if there is any way I can access scope [here](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L280-L283) and call `scope.Failed(exception)` or `ClientDiagnostics.CreateRequestFailedExceptionAsync` should internally call `scope.Failed(exception)` method or do we need to create an outer scope for this method?

I think the convenience method should be creating its own scope here. We are correctly setting the `suppressNestedScopes` flag to `true` [here](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L54), so we don't need to worry about there being nested scopes.

**Comment by ShivangiReja** [comment]
>I think the convenience method should be creating its own scope here. We are correctly setting the suppressNestedScopes flag to true [here](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L54), so we don't need to worry about there being nested scopes.

@JoshLove-msft  Convenience method name is same as protocol method name. If I add outer scope, I get below error even if `suppressNestedScopes` is enabled.

```Csharp
 Expected: <Azure.RequestFailedException>
  But was:  <System.InvalidOperationException: A scope has already started for event 'ConfigurationClient.SetConfigurationSetting'
```

image

CC: @lmolkova as she is also looking for other approaches for this case.

**Comment by lmolkova** [comment]
> I think the convenience method should be creating its own scope here. We are correctly setting the `suppressNestedScopes` flag to `true` [here](https://github.com/Azure/azure-sdk-for-net/blob/d6781235d7f22210c862efb0fa133b93d6860fe0/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L54), so we don't need to worry about there being nested scopes.

I agree it's a good option! I was thinking if we can do better and optimize it a bit, so inner scope is not created at all or not create outer scope and tell inner one to still set errors. Still, optimization can be done later and would not change anything for users. 

I believe if we created outer scope, the tests would fail in https://github.com/Azure/azure-sdk-for-net/blob/78dcb9725b7320e9086b43b57c0c9b79eb609289/sdk/core/Azure.Core.TestFramework/src/ClientDiagnosticListener.cs#L153 - scopes are duplicated with DiagnsoticSource 4.6.0 in our tests, but I think we can remove this check now since we have suppression in user apps (that use DiagnsoticSource 5.0+)

**Comment by JoshLove-msft** [comment]
> ```cs
> stem.InvalidOperationException: A
> ```

Sounds good - we can at least condition that check to only run for .NET 5+.

**Comment by JoshLove-msft** [comment]
@ShivangiReja, would you mind surrounding this code - https://github.com/Azure/azure-sdk-for-net/blob/78dcb9725b7320e9086b43b57c0c9b79eb609289/sdk/core/Azure.Core.TestFramework/src/ClientDiagnosticListener.cs#L153

with an #ifdef NET5_0_OR_GREATER?

**Review by JoshLove-msft — APPROVED** [review]
Scope related changes and Test Framework update LGTM.

**Comment by ShivangiReja** [comment]
>@ShivangiReja, would you mind surrounding this code - https://github.com/Azure/azure-sdk-for-net/blob/78dcb9725b7320e9086b43b57c0c9b79eb609289/sdk/core/Azure.Core.TestFramework/src/ClientDiagnosticListener.cs#L153
with an #ifdef NET5_0_OR_GREATER?


@JoshLove-msft Added this condition. Now tests are working fine after adding outer scopes for the convenience APIs.

Thanks @JoshLove-msft, @lmolkova and @annelo-msft!

**Comment by ShivangiReja** [comment]
@JoshLove-msft AppConfig pipeline is now green -https://dev.azure.com/azure-sdk/public/_build/results?buildId=1902997&view=results but after adding that condition, core ci pipeline is failing https://dev.azure.com/azure-sdk/public/_build/results?buildId=1902998&view=results

**Review by jsquire — APPROVED** [review]

**Pull request merged**
