### PR TITLE
[Fluent] Porting and passing two unit tests + some bug fixes

### PR DESCRIPTION
**Pull request by martinsawicki**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@martinsawicki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (marcins). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@martinsawicki please resolve merge conflicts.

**Review by hovsepm — CHANGES_REQUESTED** [review]
@martinsawicki your PR contains commits from the previous PR - https://github.com/Azure/azure-sdk-for-net/pull/2631 
till this one "@martinsawicki	correcting dictionary puts in app gateway, 34891c5". 
Please rebase or reset --soft and then push to your fork with -f to clean up commits that are already merged.

**Comment by martinsawicki** [comment]
hmm, not sure why that happens - i just do the same thing as usual. 
i'll look into this when i'm finished adding the rest of the test work soon.

**Comment by hovsepm** [comment]
@martinsawicki here is the sequence:
1. git pull upstream Fluent
2. git reset --soft upstream/Fluent
3. git commit -m "name for your commit"
4. git push origin Fluent -f

However for safety I'd suggest you to create a new brunch form your origin/Fluent and then create a pr from that new branch and close this one.

**Pull request closed without merging**
