### PR TITLE
[Synapse] - General Available Release

### PR DESCRIPTION
**Pull request by idear1203**
Code generated based on the Swagger spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/synapse/resource-manager/readme.md
Tag: package-2020-12-01

### CODE REVIEW

**Comment by YalinLi0312** [comment]
@idear1203 Could you link the swagger PR that your updates are associated with?

**Comment by idear1203** [comment]
Related PR: https://github.com/Azure/azure-rest-api-specs/pull/12502

**Comment by YalinLi0312** [comment]
@idear1203 Please:
* update versions in `*.csproj` and `AssemblyInfo.cs`, and follows semver
* update release notes in `*.csproj`
* update API tags in `Az.Sdk.props` if there's a API-version update
* make sure generated code is not touched
* make sure has proper test coverage

**Review by YalinLi0312 — APPROVED** [review]
LGTM

**Comment by YalinLi0312** [comment]
@idear1203 Please fix the hanging check-enforcer.

**Pull request merged**
