### PR TITLE
Renaming data-plane to client and reordering

### PR DESCRIPTION
**Pull request by Petermarcu**
Removing the name data plane from the list as well as putting client libraries first to account it being a shorter list as well as likely the ones more people will be looking for in the repo.

### CODE REVIEW

**Review by KrzysztofCwalina — APPROVED** [review]

**Review by AlexGhiondea — APPROVED** [review]

**Review by weshaggard — APPROVED** [review]

**Comment by shahabhijeet** [comment]
@Petermarcu any reason you have not included Cognitive services as part of dataPlane libraries in your list?
But apart from that, looks good.

**Review by shahabhijeet — APPROVED** [review]

**Comment by Petermarcu** [comment]
I didn't change the contents. In the end, I'd like this page to be generated so everything is always up to date.

**Comment by Petermarcu** [comment]
@shahabhijeet do you know what I need to do to get that one CI leg to actually pass? It has failed to report on multiple PR's now. I'm going to merge this because its clearly not breaking anything.

**Comment by shahabhijeet** [comment]
@Petermarcu can you clarify what you mean by CI leg? Are you referring to the CLA job that intermittently is stuck and shows yellow?

**Comment by weshaggard** [comment]
@Petermarcu  if you are referring to `azure-sdk-for-net.client` that was renamed recently but was showing as failing because it was a required check. We fixed that earlier this week.

**Pull request merged**
