### PR TITLE
[AppServie]:Azure .Net SDK update for PowerShell

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**

### CODE REVIEW

**Comment by Kotasudhakarreddy** [comment]
@panchagnula & @ThejaChoudary - FYI

**Comment by panchagnula** [comment]
FYI @naveedaz

**Review by isra-fel — CHANGES_REQUESTED** [review]
Please follow our guideline when generate management-plane SDK: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#generating-net-sdk

A few things I notice:
- There are two metadata txts: `eng/mgmt/mgmtmetadata/web_resource-manager.txt` and `src/SDKs/_metadata/web_resource-manager.txt`. The latter is in the old format and wrong folder, but its date is newer. So I suggest remove the latter and regenerate again.
- The file `sdk/websites/Microsoft.Azure.Management.WebSites/src/Generated/code-model-v1` indicates you used the wrong version of autorest. Please remove it and generate again.
- When updating api-version, please also update the tags in `AzSdk.RP.props`

Thanks

**Comment by Kotasudhakarreddy** [comment]
> Please follow our guideline when generate management-plane SDK: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#generating-net-sdk
> A few things I notice:
> 
> There are two metadata txts: eng/mgmt/mgmtmetadata/web_resource-manager.txt and src/SDKs/_metadata/web_resource-manager.txt. The latter is in the old format and wrong folder, but its date is newer. So I suggest remove the latter and regenerate again.
> The file sdk/websites/Microsoft.Azure.Management.WebSites/src/Generated/code-model-v1 indicates you used the wrong version of autorest. Please remove it and generate again.
> When updating api-version, please also update the tags in AzSdk.RP.props
> 
> Thanks

Done the changes as per review comments. Please review.

**Comment by panchagnula** [comment]
@isra-fel can you also help us figure our the BUILD failures and how to fix them? Thank you.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
