### PR TITLE
Switch live test pipelines to use 1ES pools.

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR makes changes to the pipeline definitions for live tests to make use of the 1ES pools for Windows.

### CODE REVIEW

**Comment by mitchdenny** [comment]
@benbp we need to figure out how to insert pool selections into the new multi-cloud live test model that you've got going on here. At the end of the day we need the following value set for Windows (and soon Linux), but not macOS:

```
pool:
  name: [name of our new pool]
  vmImage: should be nothing
```

The storage tests work fine, but it seems that the ```Clouds``` parameter makes the live test pipelines take a different path. Ultimate what I think I would like to do is have a set of default pool names, and then base on OS selection we select the right pool.

**Review by weshaggard — APPROVED** [review]

**Comment by benbp** [comment]
@mitchdenny I think if we set pool as a matrix variable on a per-platform basis via the platform config (where OSVmImage is set), then that should allow for easy customization.

**Comment by benbp** [comment]
@mitchdenny yeah it seems that $(Pool) needs to evaluate prior to the job execution context stage, which is when matrix variables are populated (makes sense):

##[error]The pipeline is not valid. Could not find a pool with name $(Pool). The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.

**Comment by benbp** [comment]
@mitchdenny [here's a fix](https://github.com/benbp/azure-sdk-for-net/commit/400b9dd67a38862a0bd66b364bf2e28a3b74f38e) that gets this working with the live test config model.

We have to switch on host/pool at a higher template level because of the either/or definition behavior (i.e. devops doesn't like empty fields, they want the field to not exist). Luckily we already had this problem for container builds, so we can plug in to that solution.

Working live test pipeline example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=651855&view=logs&j=6558b98b-3d3e-504f-99d0-4f904aed18dc

**Comment by jsquire** [comment]
Hi @mitchdenny.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream by removing the `no-recent-activity` label?  Otherwise, we'll close this out in 7 days.

**Pull request closed without merging**
