### PR TITLE
Update the Azure Batch data plane SDK with new REST API version

### PR DESCRIPTION
**Pull request by matthchr**
## Description

1. Update the Azure Batch data plane library to target a new REST API version (see [here](https://github.com/Azure/azure-rest-api-specs/pull/892) for the Swagger specification)
2. Refactor things such that Azure Storage is no longer required as a dependency for the Azure.Batch package.
3. Various other clean ups and changes.
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by matthchr** [comment]
## Reviewers please note:
1. This pull request _does_ introduce breaking changes (they were there in the Swagger specification too).
  a. This causes the major version to be revved for all 3 of the packages which were touched in this PR.
2. The commits while somewhat plentiful are for the most part relatively well titled and actually coincide with logical changes done. There really were 15+ things we did in this release (see the commit list for the full set of changes). We prefer that you **not** squash upon merge if at all possible.

**Comment by matthchr** [comment]
Pinging on this, can somebody take a look?

**Comment by cormacpayne** [comment]
src\Batch\Client\Src\FileStaging\FileStagingUtils.cs

File is missing a license header

**Comment by cormacpayne** [comment]
@matthchr 

**src\Batch\Client\Src\FileStaging\FileStagingUtils.cs**

At the top there is a using defined for `System.Threading.Tasks`, but it is used throughout the file multiple times

Line 45, 47, 53 for example

**Comment by cormacpayne** [comment]
@matthchr 

**src\Batch\Client\Tests\ObjectModel\BatchClientIntegrationTests\IntegrationTestUtilities\FileUploadUtilities.cs**

File is missing a license header

**Comment by cormacpayne** [comment]
@matthchr 

**src\Batch\Client\Tests\ObjectModel\BatchClientIntegrationTests\IntegrationTestUtilities\FileUploadUtilities.cs**

Similar issue with `System.Threading.Tasks`

**Comment by cormacpayne** [comment]
@matthchr 

**src\Batch\Client\Tests\ObjectModel\BatchClientIntegrationTests\IntegrationTestUtilities\FileUploadUtilities.cs**

Line 558 - use [`TestUtilities.Wait(30)`](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/TestFramework/Microsoft.Rest.ClientRuntime.Azure.TestFramework/Utilities/TestUtilities.cs#L75) instead of `Thread.Sleep(30)`

**Comment by cormacpayne** [comment]
@matthchr 

**src\Batch\FileConventions\Tests\AzureBatchFileConventions.IntegrationTests\app.config**

Is this file needed?

**Comment by cormacpayne** [comment]
@matthchr 

**src\Batch\FileConventions\Tests\AzureBatchFileConventions.Tests\app.config**

Same comment

**Comment by matthchr** [comment]
Hi Cormac, thanks for looking. It seems I can't reply directly to your comments so summarizing here:
**src\Batch\Client\Src\FileStaging\FileStagingUtils.cs** - Fixed missing license header and System.Threading.Tasks issues

**src\Batch\Client\Tests\ObjectModel\BatchClientIntegrationTests\IntegrationTestUtilities\FileUploadUtilities.cs** - Fixed missing license header and System.Threading.Tasks issue

**src\Batch\Client\Tests\ObjectModel\BatchClientIntegrationTests\IntegrationTestUtilities\FileUploadUtilities.cs** - Our integration tests don't refer to your common test libraries (or use your test framework), so I can't use that method.

**src\Batch\FileConventions\Tests\AzureBatchFileConventions.Tests\app.config** - Removed (same for the other App.config here)

**Comment by matthchr** [comment]
@cormacpayne This PR has been open for more than a week now. Can we get it signed off today?

Thanks

**Comment by cormacpayne** [comment]
LGTM

**Pull request merged**
