### PR TITLE
Fix OpenID Connect Cmdlets due to change in Resource Path

### PR DESCRIPTION
**Pull request by solankisamir**
https://github.com/Azure/azure-sdk-for-net/issues/1981

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@solankisamir__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sasolank). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by kirthik** [comment]
Code looks good to me. @hovsepm - Should this change go to AutoRest or netcore branch?

**Comment by markcowl** [comment]
@solankisamir For hydra specs, the master branch is correct.  Please update the package version, or these changes cannot be published.

**Comment by markcowl** [comment]
@solankisamir Please update the nuget.proj and AssemblyInfo.cs versions for this change, or the change will have no effect.

**Comment by solankisamir** [comment]
Update the package versions.

**Pull request merged**
