### PR TITLE
[DataFactory]Deleted 8 files from Extemsions and Added maxRowPerFile/f…

### PR DESCRIPTION
**Pull request by Jingshu923**
- Added maxRowPerFile/fileNamePrefix to tabular format settings:  https://github.com/Azure/azure-rest-api-specs/pull/10666

- Deleted 8 files from Extemsions folder

### CODE REVIEW

**Review by YalinLi0312 — CHANGES_REQUESTED** [review]
Hi @Jingshu923, do you have any reason to remove these source files? It looks like a potential breaking change.

**Comment by Jingshu923** [comment]
> Hi @Jingshu923, do you have any reason to remove these source files? It looks like a potential breaking change.

@YalinLi0312  Yes, I will update the swagger project later, these files will generate code into Models dic.

**Comment by YalinLi0312** [comment]
@Jingshu923 Thanks for your response. Please reference the PR for updating the swagger here, after it gets merged I can start to review this PR.

**Comment by Jingshu923** [comment]
@YalinLi0312  If  I update swagger first, there will be some errors on .net sdk test, some models which I deleted in this PR will be conflicted. Could not I merge this PR first?

**Pull request closed without merging**
