### PR TITLE
[MetricsAdvisor] Updated test hook ID

### PR DESCRIPTION
**Pull request by kinelski**
The hook we were using was deleted by accident, which has been causing some test failures in the last couple of days.

### CODE REVIEW

**Review by maririos — APPROVED** [review]
curious, do u know what happened? and how we can avoid that in the future?

**Comment by kinelski** [comment]
> 
> 
> curious, do u know what happened? and how we can avoid that in the future?

Because of client-side failures (already fixed, in theory), we couldn't delete some of the hooks we created during the tests. I was deleting the accumulated hooks manually, and ended up deleting the one we were using for samples.

I think it could have been avoided if I had given it a better name, something like "DONT DELETE Hook used in samples". There are other resources that need the same attention, though (such as Data Feeds, Alert Configurations, Detection Configurations...), so I'll track this with an issue to work on after our next release.

**Pull request merged**
