### PR TITLE
Initial commit of the DevTestLabs SDK.

### PR DESCRIPTION
**Pull request by iouri-s**
Just submitting one test for now, but will add more.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@iouri-s__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (iouris). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@iouri-s 
in DevTestLabs\Microsoft.Azure.Management.DevTestLabs\project.json 
```
{
  "version": "2.2.0-preview",
  "description": "Microsoft.Azure.Management.DevTestLabs",
```

Any reason to start packages from version 2.2.0-preview? Doesn't 1.0.0-preview work here?

**Comment by hovsepm** [comment]
@iouri-s 
you can use 0.16.0-Nightly20160426 of autorest generator in generate.cmd script. That is almost the latest one.

**Comment by hovsepm** [comment]
please align AssemlyInfo.cs for Microsoft.Azure.Management.DevTestLabs with the package version in project.json file
```
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.1.1.0")]
```

**Pull request merged**
