### PR TITLE
[BillingRP] - SDK for GA version of APIs

### PR DESCRIPTION
**Pull request by asarkar84**
BillingRP - SDK for GA version of APIs

Spec PR link: https://github.com/Azure/azure-rest-api-specs/pull/9541

### CODE REVIEW

**Comment by isra-fel** [comment]
@asarkar84  please add a link to the openapi spec review PR here, thanks

**Comment by asarkar84** [comment]
@isra-fel Please find below the link to spec review PR:
https://github.com/Azure/azure-rest-api-specs/pull/9541

**Comment by asarkar84** [comment]
@isra-fel We have fixed all the functional tests. Please review this PR.

**Comment by isra-fel** [comment]
There is still one case failing on linux:
```
 Billing.Tests.ScenarioTests.ProductsOperationsTest.UpdateProductAutoRenewTest
17:00:33.649     1>EXEC : error Message:  [/home/vsts/work/1/s/mgmt.proj]
                      System.ArgumentException : Unable to find recorded mock file '/home/vsts/work/1/s/artifacts/bin/Microsoft.Azure.Management.Billing.Tests/Debug/netcoreapp2.0/SessionRecords/ProductsOperationsTest/UpdateProductAutoRenewTest.json'.
                     Parameter name: callerIdentity
                     Stack Trace:
                        at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity, HttpRecorderMode mode)
                        at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(String className, String methodName)
                        at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(Type type, String methodName)
                        at Billing.Tests.ScenarioTests.ProductsOperationsTest.UpdateProductAutoRenewTest() in /home/vsts/work/1/s/sdk/billing/Microsoft.Azure.Management.Billing/tests/ScenarioTests/ProductsOperationsTest.cs:line 182
```
It's caused by different casing of the test case name and recording file name.

**Comment by asarkar84** [comment]
@isra-fel I have fixed the issue. Please take a look again. Thanks!

**Review by isra-fel — APPROVED** [review]
LGTM

**Comment by asarkar84** [comment]
@isra-fel CI has been completed. Please merge the PR.

**Pull request merged**
