### PR TITLE
SDK changes for Dynamics, Salesforce and JSONFormat

### PR DESCRIPTION
**Pull request by smilenow**
## Description

This PR is aimed to add SDK changes for Dynamics sink, Salesforce dataset, Salesforce sink and update JSONFormat in ADF, and add some new test cases to validate the swagger changes in
src/SDKs/DataFactory/DataFactory.Tests/JsonSamples/DatasetJsonSamples.cs
src/SDKs/DataFactory/DataFactory.Tests/JsonSamples/PipelineJsonSamples.cs

Swagger spec pull request:
1. Dynamics swagger change: https://github.com/Azure/azure-rest-api-specs/pull/1850 (merged)
2. Salesforce and JSONFormat swagger change: https://github.com/Azure/azure-rest-api-specs/pull/1903 (merged)

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by bgold09** [comment]
do not merge: waiting on formal internal approval

**Comment by bgold09** [comment]
approved via internal item [97878](https://msdata.visualstudio.com/Azure%20Data%20Factory/_workitems/edit/97878)

**Comment by smilenow** [comment]
Hi folks, both two swagger changes had been merged, please go ahead this pull request.
cc @bgold09 , @shahabhijeet

**Comment by shahabhijeet** [comment]
@smilenow the PR has conflicts and please regenerate the SDK not that the Spec has been merged and update this PR

**Comment by smilenow** [comment]
Please look at #3824 to prevent double merging. I propose that close this PR after #3824 merged.

**Pull request closed without merging**
