### PR TITLE
[DoNotMerge] [Microsoft.Maintenance] Generated code from 2023-04-01 API version

### PR DESCRIPTION
**Pull request by KalpeshChavan12**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by KalpeshChavan12** [comment]
Please review PR, do not merge PR.

**Comment by live1206** [comment]
@KalpeshChavan12 Track 1 SDK is deprecated, please update [Azure.ResourceManager.Maintenance](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/maintenance/Azure.ResourceManager.Maintenance) instead.

**Review by live1206 — CHANGES_REQUESTED** [review]
@KalpeshChavan12 Track 1 SDK is deprecated, please update [Azure.ResourceManager.Maintenance](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/maintenance/Azure.ResourceManager.Maintenance) instead.

**Comment by KalpeshChavan12** [comment]
@live1206 we need track1 sdk for powershell module, we cant use track2 sdk

**Review by live1206 — APPROVED** [review]

**Pull request merged**
