### PR TITLE
Add overloads to send email using operation ID passed in from consumer

### PR DESCRIPTION
**Pull request by alexwiese**
Currently the methods for sending email via the `EmailClient` do not allow the _Operation ID_ to be specified.
`EmailRestClient` which is used by `EmailClient` _does_ allow the operation ID to be specified.
Currently the `EmailClient` will always generate a new operation ID using `Guid.NewGuid()` before passing it to the `EmailRestClient`.

Consumers may want to specify their own operation ID to correlate send email operations with their own long-running operations, or to ensure that the same operation is not processed more than once even if it's submitted multiple times (idempotency).

This PR adds new overloads that allow the operation ID to be specified:

```diff
+        public virtual Azure.Communication.Email.EmailSendOperation Send(Azure.WaitUntil wait, Azure.Communication.Email.EmailMessage message, System.Guid operationId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
+        public virtual Azure.Communication.Email.EmailSendOperation Send(Azure.WaitUntil wait, string senderAddress, string recipientAddress, string subject, string htmlContent, System.Guid operationId, string plainTextContent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
+        public virtual System.Threading.Tasks.Task<Azure.Communication.Email.EmailSendOperation> SendAsync(Azure.WaitUntil wait, Azure.Communication.Email.EmailMessage message, System.Guid operationId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
+        public virtual System.Threading.Tasks.Task<Azure.Communication.Email.EmailSendOperation> SendAsync(Azure.WaitUntil wait, string senderAddress, string recipientAddress, string subject, string htmlContent, System.Guid operationId, string plainTextContent = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
```

### CODE REVIEW

**Comment by alexwiese** [comment]
@KrzysztofCwalina any feedback for this one?

**Comment by alexwiese** [comment]
@tg-msft  can you take a look please?

**Comment by alexwiese** [comment]
@kagbakpem  @yogeshmo
can you review this PR please?

/cc @acsdevx-msft

**Review by yogeshmo — APPROVED** [review]

**Comment by alexwiese** [comment]
Can anyone merge this?

**Comment by alexwiese** [comment]
@yogeshmo can you merge this PR please?

**Comment by yogeshmohanraj** [comment]
Hi @alexwiese - It looks like I don't have permissions to merge this.

**Comment by alexwiese** [comment]
@scottaddie are you able to merge this please?

**Review by kagbakpem — APPROVED** [review]

**Pull request merged**
