### PR TITLE
Managed instance failover

### PR DESCRIPTION
**Pull request by milanbrkic-ms**
This changes adds support for new feature - failover managed instance. 

azure-rest-api-specs PR: https://github.com/Azure/azure-rest-api-specs/pull/8911

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi Milan, please regenerate SDK from Azure repo after the spec is merged.
BTW you'll need to update the release notes in csproj, and if you are going to release this PR, update the versions in csproj and AseemblyInfo.cs as well.
Thanks

**Comment by MilanBrkicFON** [comment]
@isra-fel spec PR is merged so I regenerated and made changes in csproj and AssemblyInfo files. Can you check again?

**Review by isra-fel — COMMENTED** [review]
Looks good.
I recently checked in a commit to fix the timeout issue in CI. Could you merge or rebase master? Thanks

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
