### PR TITLE
Update tests.yml to new layout

### PR DESCRIPTION
**Pull request by XuGuang-Yao**
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

Using this RR to trace and fix issues we encounter in the tests. Will close it once we finish all the tests and send PR per services.

Updated list:
Text analytics
Core
Extensions
Event hubs
Identity
key vault
Search
Storage account
Form recognizer
Service bus
Event grid
Tables

### CODE REVIEW

**Comment by jsquire** [comment]
@XuGuang-Yao : Would you please advise as to whether this is still an active work stream or if the PR should be closed?

**Comment by XuGuang-Yao** [comment]
@jsquire -  We are using the PR to do Sovereign cloud test. So yes, it is active.

**Comment by jsquire** [comment]
Thanks @XuGuang-Yao.  Tagging this up and leaving it be.

**Comment by tzhanl** [comment]
close this for there is new PR #17277  to follow up.

**Pull request closed without merging**
