### PR TITLE
Regen for remover

### LINKED ISSUE #2157: Remove the models that are not even internally referenced
We have some logic to make the models that are not publicly referenced `internal`.
We need to remove the models that are not even internally referenced.

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Fixes https://github.com/Azure/autorest.csharp/issues/2157

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
The CI failures are all complaining about LongRunningOperation method - I believe this should be introduced by recent LRO changes such as this: https://github.com/Azure/autorest.csharp/pull/2213

**Comment by ArcturusZhang** [comment]
Updated the autorest.csharp version to a newer one, this should contain the missing files and resolve the compile issues.

**Review by Yao725 — APPROVED** [review]
I roughly checked `Cdn`, `DeviceUpdate` and `Dynatrace`, code change LGTM, thanks!

**Comment by weshaggard** [comment]
@ArcturusZhang how often do you think these types of changes will need to be made? I ask because it causes a large amount of CI jobs to be triggered which can cause what we call is a build storm which can consume a lot of our resources and cause delays in processing jobs.

**Pull request merged**
