### PR TITLE
[DataMovement] [Storage] Change Default CreateMode from Overwrite to Fail on existing destination resource

### PR DESCRIPTION
**Pull request by amnguye**
- Adding a new API for `StorageResourceCreateMode` to have a `None` value to default to, if not set
- The new default is `None` if `TransferOptions.CreateMode` is not set
- If `None` is set then we default to `StorageResourceCreateMode.Fail` (which fails on if the destination file already exists)
- Originally we were overwriting on default
- Rerecorded tests since almost all tests were affected by this change (e.g. added a If-None-Match:*)

### CODE REVIEW

**Review by jaschrep-msft — APPROVED** [review]

**Comment by amnguye** [comment]
Live test Mac errors are unrelated to this PR

**Pull request merged**
