### PR TITLE
Creating SDT client with endpoint only and making source input options public

### PR DESCRIPTION
**Pull request by hamshavathimunibyraiah**
SouceInput options are made public. 
Tests are updated to access storage accounts using managed identity and no longer through SAS urls. 
Single document translation client can be created using endpoint alone, mainly for SDK to work against containers.

### CODE REVIEW

**Review by jsquire — DISMISSED** [review]
@hamshavathimunibyraiah:

Your account lacks the required public Azure GitHub organization membership required of an internal contributor.  Please review the Azure SDK onboarding documentation and use the associated Teams channel for support.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

You can verify the state of your account by running the [Validate-AzsdkCodeOwner](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/scripts/Validate-AzsdkCodeOwner.ps1) script from the Azure SDK tools repository.

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

**Review by vikaspalaskar — APPROVED** [review]

**Comment by rahmlad-aramide** [comment]
Hi @hamshavathimunibyraiah I'm trying to use this synchronous document translation service to translate document, in the sample here: [https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/translation/ai-translation-document-rest/samples/v1-beta/typescript/src/synchronousDocumentTranslation.ts](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/translation/ai-translation-document-rest/samples/v1-beta/typescript/src/synchronousDocumentTranslation.ts), a raw document was used, I'm trying to upload pdf document and get pdf document as my response, please how can I go about it?
Thanks in advance.

**Comment by jsquire** [comment]
@rahmlad-aramide:  A pull request comment is not the appropriate place to request help.  Please open an issue in the JavaScript repository where that sample is located so that the right folks to assist have visibility.

**Comment by rahmlad-aramide** [comment]
Okay, I've done that thank you @jsquire

**Pull request merged**
