### PR TITLE
[Storage] Add test cases to support Revoke UserDelegationKeys

### PR DESCRIPTION
**Pull request by blueww**
This is to add test case for a new feature: Revoke UserDelegationKeys
Upgrade the SDK version to 10.1.0, but we might won't release it with 10.1.0, but release it in a latest release with 11.0.0

### CODE REVIEW

**Comment by dsgouda** [comment]
@blueww So are you planning to release `10.1.0` or not?

**Comment by blueww** [comment]
We might not release, since we might will release a new feature on 2019-04-01 apiversion first. 
But I would like to be prepared for the release, since I am not sure which feature will be release first.

**Comment by dsgouda** [comment]
> 
> 
> We might not release, since we might will release a new feature on 2019-04-01 apiversion first.
> But I would like to be prepared for the release, since I am not sure which feature will be release first.

Thanks for the information. I shall go ahead and merge this but please be cognizant of the versioning story depending on what API version you are working on.

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
