### PR TITLE
fix incomplete run details

### PR DESCRIPTION
**Pull request by M-Hietala**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by nick863 — APPROVED** [review]

**Review by jhakulin — APPROVED** [review]

**Comment by M-Hietala** [comment]
@microsoft-github-policy-service rerun

**Comment by ShivangiReja** [comment]
We can start by adding test cases to cover incomplete run details in this PR to ensure the functionality works.

Other tests can be added as part of https://github.com/Azure/azure-sdk-for-net/issues/47347.

**Comment by M-Hietala** [comment]
Created item https://github.com/Azure/azure-sdk-for-net/issues/47400

**Review by ShivangiReja — APPROVED** [review]

**Pull request merged**
