### PR TITLE
Update code owners for Azure.DevCenter SDK

### PR DESCRIPTION
**Pull request by pallavit**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by pallavit** [comment]
@ronniegeraghty could you please include this tag in the bot as well. Also, please bear with me while I add other service contacts as well :)

**Comment by chrissmiller** [comment]
@pallavit I am no longer a code owner for devcenter SDK, I just did the initial generation (although I have context here so please feel free to leave me in this list). I believe @sebrenna and @mharlan would be the appropriate contacts for both DevCenter and DevTestLabs (please correct me if I'm wrong on the DTL owners Sean/Matt!)

**Comment by pallavit** [comment]
> @pallavit I am no longer a code owner for devcenter SDK, I just did the initial generation (although I have context here so please feel free to leave me in this list). I believe @sebrenna and @mharlan would be the appropriate contacts for both DevCenter and DevTestLabs (please correct me if I'm wrong on the DTL owners Sean/Matt!)

Thank you @chrissmiller. I will wait for the ack from @sebrenna and @mharlan and update the list.

**Comment by sebrenna** [comment]
> > @pallavit I am no longer a code owner for devcenter SDK, I just did the initial generation (although I have context here so please feel free to leave me in this list). I believe @sebrenna and @mharlan would be the appropriate contacts for both DevCenter and DevTestLabs (please correct me if I'm wrong on the DTL owners Sean/Matt!)
> 
> Thank you @chrissmiller. I will wait for the ack from @sebrenna and @mharlan and update the list.

Yes, @sebrenna and @mharlan are the appropriate points of contact! :)

**Review by jsquire — APPROVED** [review]
@ronniegeraghty :  Do you mind doing the bot rules for this?   The label has been created.

**Comment by ronniegeraghty** [comment]
> @ronniegeraghty : Do you mind doing the bot rules for this? The label has been created.

No problem.

**Pull request merged**
