### PR TITLE
#17662 [bug] add setters to LengthTokenilter

### PR DESCRIPTION
**Pull request by nokternol**
The simplest approach to fixing the defect and it's the one used by all the other filter class with non-IList properties

### CODE REVIEW

**Comment by nokternol** [comment]
Looks like I need to kick off some code generation process from Powershell.
Not sure where that is and it's unlikely I'll have permissions to the resources required to run it.
Apologies, I was just trying to be helpful.

**Comment by nokternol** [comment]
I ran Export-API.ps1 it created the gen code I believe the analyzer is complaining about.
However, it also created the below file
sdk\mixedreality\Azure.MixedReality.Authentication\api\Azure.MixedReality.Authentication.netstandard2.0.cs
Which it feels is unrelated.

Pushed the change to the generated file but omitted the mixedreality as this feels related to other work.

**Comment by jsquire** [comment]
Hi @nokternol.  Thank you, again, for your interest in helping to improve the Azure SDK experience and for your contribution.   I've routed this to the team members best able to assist with review and guidance.   Please be aware that due to the holidays, responses may be delayed.

**Review by heaths — APPROVED** [review]

**Comment by heaths** [comment]
Thank you for your contribution and catching this error! The model properties are indeed read/write.

**Comment by AlexGhiondea** [comment]
@nokternol we should release a new version in early February -- would that work?

**Comment by nokternol** [comment]
I would need to check but for now I have broken of the functionality that relies on this code into a separate work item so I can process the rest. So that gives us a bit more freedom.

**Comment by nokternol** [comment]
Apologies for my lack of knowledge of on how GitHub links things.
It says my commit is not part of any branch on this repo which I'm assuming means it was squash merged and then the branch deleted.
@AlexGhiondea @annelo-msft How do I then find out what release sdk (nuget version) this fix is contained in so I can upgrade our dependencies?

**Pull request merged**
