### PR TITLE
Add Edition and Customized script support for SSIS IR

### PR DESCRIPTION
**Pull request by chinadragon0515**
## Description
This change is add edition and customized script support for SSIS IR, there is no manually code change, all the code change are generated with spec change in this PR
https://github.com/Azure/azure-rest-api-specs/pull/2266

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ Y] Please add REST spec PR link to the SDK PR
- [ Y] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ Y] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ Y] Title of the pull request is clear and informative.
- [ Y] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ Y] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ Y] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ Y] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ Y] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by fan130 — APPROVED** [review]

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Can you do the following in the below order:
1)	Pull latest from upstream (if you have already done this good)
2)	Execute msbuild.exe build.proj from the repo root
a.	This will update the build tools in the current repo
3)	Generate your SDK using generate.cmd
a. this creates meta data files that are needed.
4)	Build you sdk at least once from command line of IDE
a.	(From command line use this) Msbuild.exe build.proj /t:build /p:Scope=SDKs\DataFactory
b. this will create another additional meta data file that is also needed.
5)	Update the PR

**Comment by chinadragon0515** [comment]
Have follow the steps, and for step 3, I use this command to generate code
src\SDKs\DataFactory\Management.DataFactory\generate.cmd

**Comment by shahabhijeet** [comment]
@chinadragon0515 can you resolve the conflict.

**Comment by chinadragon0515** [comment]
Just update the code with regenerated code based on newest specification, can someone help to review and merge the PR, thanks.

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Still missing 1 meta data file.
Build your project from command line to get the new meta data file
msbuild build.proj /t:build /p:Scope=SDKs\DataFactory

**Comment by chinadragon0515** [comment]
I have run msbuild build.proj /t:build /p:Scope=SDKs\DataFactory, and there is meta file changed, I just commit the meta file change into single commit,  the file changed is src/SDKs/_metadata/datafactory_resource-manager.txt

Anything else I missed and need to be done? thanks

**Comment by shahabhijeet** [comment]
@chinadragon0515 I just cloned your fork and regenerated the SDK.
My hunch is that you are not using latest autorest
Do the following:
1) Pull from upstream
2) msbuild build.proj (this will also update the build tools)
3) generate.cmd (this should generate SDKInfo*.cs) 
4) msbuild build.proj /t:Build /p:Scope=SDKs\DataFactory (this should generate AzSdk.RP.props)

**Comment by chinadragon0515** [comment]
1. I checked my autoreset, it is newest version.
2. I follow the process again, there is no change on file AzSdk.RP.props, and note file AzSdk.RP.props is checked in 24 days ago, refer to https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/DataFactory/AzSdk.RP.props and this is same case for SDKInfo*.cs

Detail steps I have done,
1. pull newest specification
2 reset my sdk change, and rebase newest SDK
3. msbuild build.proj
4. run command src\SDKs\DataFactory\Management.DataFactory\generate.cmd
5. msbuild build.proj /t:Build /p:Scope=SDKs\DataFactory 
Anything I missed?

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
