### PR TITLE
[AzureMonitorExporter] update dependent projects for Exporter

### PR DESCRIPTION
**Pull request by TimothyMothra**
Azure.Monitor.OpenTelemetry.Exporter.Perf has a dependency on Azure.Test.Perf.
I added that project to our solution.

image

### CODE REVIEW

**Review by rajkumar-rangaraj — APPROVED** [review]

**Comment by reyang** [comment]
Curious, why do we want to do this?

**Comment by TimothyMothra** [comment]
> Curious, why do we want to do this?

Our Perf project has a dependency on this project and will fail to build if the Azure.Test.Perf is not also built.

**Comment by reyang** [comment]
> > Curious, why do we want to do this?
> 
> Our Perf project has a dependency on this project and will fail to build if the Azure.Test.Perf is not also built.

What if Azure.Test.Perf later added another dependency, are you going to keep maintaining the dependency chain?

**Review by reyang — CHANGES_REQUESTED** [review]
Need to understand the direction https://github.com/Azure/azure-sdk-for-net/pull/35499#issuecomment-1503918461.

**Comment by reyang** [comment]
> > What if Azure.Test.Perf later added another dependency, are you going to keep maintaining the dependency chain?
> 
> At the moment, yes. :(
> 
> This could be mitigated if Azure.Test.Perf was published and we could take a PackageDependency. But for as long as we have ProjectDependencies we can have issues like this.

Would you investigate what's the right approach? I suggest that we avoid any hacks that require ongoing obligations (e.g. "are you going to keep maintaining the dependency chain - yes" is something I'm very concerned about).

**Pull request closed without merging**
