### PR TITLE
Server disaster recovery no content

### PR DESCRIPTION
**Pull request by jaredmoo**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jaredmoo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jaredmoo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jamestao** [comment]
Looks good to me.

**Comment by kirthik** [comment]
LGTM @hovsepm let me know if I can merge it.

**Comment by hovsepm** [comment]
@kirthik :shipit: :)

**Comment by kirthik** [comment]
lol..thanks! will merge it

**Comment by jaredmoo** [comment]
Thanks @kirthik and @hovsepm !

**Pull request merged**
