### PR TITLE
Produce ActivitySource events

### PR DESCRIPTION
**Pull request by pakrym**
This is a prototype of producing ActivitySource events without taking a dependency on a newer version for System.Diagnostics.DiagnosticsSource package.

TODO: test with OpenTelemetry exporter to make sure things are functioning correctly.

Depends on https://github.com/microsoft/ApplicationInsights-dotnet/pull/2185

### CODE REVIEW

**Comment by pakrym** [comment]
cc @reyang @cijothomas

**Comment by jsquire** [comment]
Hi @pakrym.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by pakrym** [comment]
>Hi @pakrym. There hasn't been recent engagement on this PR. Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

I've pushed a commit a few days ago :) Still working on it.

**Comment by jsquire** [comment]
Hi @pakrym.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream by removing the `no-recent-activity` label?  Otherwise, we'll close this out in 7 days.

**Comment by pakrym** [comment]
This needs actual E2E testing with OT.

**Comment by cijothomas** [comment]
See also: https://github.com/dotnet/aspnetcore/issues/29132

**Comment by cijothomas** [comment]
@shirhatti FYI

**Pull request closed without merging**
