### PR TITLE
Generated SDK for v2023-04-01 (GA)

### PR DESCRIPTION
**Pull request by gargankit-microsoft**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by archerzz — APPROVED** [review]

**Comment by archerzz** [comment]
Since it's beta and there is no official release before, the breaking change is fine.

**Comment by gargankit-microsoft** [comment]
Hi @archerzz 
This would be a stable release since it's for a GA api-version. We are still improving tests internally, so please hold the merge before we confirm here. We'll communicate for release separately as we want it close to GA announcement i.e. 15/5/2023.

**Comment by archerzz** [comment]
CC @ArthurMa1978 for his awareness

**Comment by gargankit-microsoft** [comment]
Hi @archerzz  @ArthurMa1978 
Please help with release dates.

**Pull request merged**
