### PR TITLE
Personalizer : Delete apis other than rank, reward and activate

### PR DESCRIPTION
**Pull request by dwaijam**
Delete apis other than rank, reward and activate

azure-rest-api-specs PR - https://github.com/Azure/azure-rest-api-specs/pull/5835

### CODE REVIEW

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please regenerate this code using generate.ps1 and commit all changes generated (including .txt files)
While you are at it, please remove `-SdkGenerationDirectory "$PSScriptRoot\Generated\Personalizer"` and check where the code is generated. The generated files must be under Personalizer\Personalizer\Generated instead of Personalizer\Personalizer\Generated\Personalizer

**Comment by dwaijam** [comment]
> Please regenerate this code using generate.ps1 and commit all changes generated (including .txt files)
> While you are at it, please remove `-SdkGenerationDirectory "$PSScriptRoot\Generated\Personalizer"` and check where the code is generated. The generated files must be under Personalizer\Personalizer\Generated instead of Personalizer\Personalizer\Generated\Personalizer

fixed

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
Will merge once CIs pass

**Pull request merged**
