### PR TITLE
build(analyzer): bump NetAnalyzers to 7.0.4

### PR DESCRIPTION
**Pull request by archerzz**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by pallavit** [comment]
@archerzz could you please share what motivated this change? Also what kind of validation have we done here?

**Comment by archerzz** [comment]
> @archerzz could you please share what motivated this change? Also what kind of validation have we done here?

@pallavit I kept getting messages like `warning : The .NET SDK has newer analyzers with version '7.0.4' than what version '7.0.1' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference.` which is a little bit annoying. Besides, I think it's not a bad idea to keep up with the latest version of analyzers.

**Review by m-nash — APPROVED** [review]
This looks good to me, but lets someone else weigh in from azure core virtual team before merging

**Review by jsquire — CHANGES_REQUESTED** [review]
Along the lines of what Pallavi asked, can we also please include details in the description that discuss what changes or additional rules this brings in?    As it stands, there's no context for what this does to our repository.

**Comment by m-nash** [comment]
Resolved here https://github.com/Azure/azure-sdk-for-net/pull/40761

**Pull request closed without merging**
