### PR TITLE
[Resources] Update .NET SDK based on swagger update of Validate API

### PR DESCRIPTION
**Pull request by filizt**

### CODE REVIEW

**Comment by filizt** [comment]
Looking at the test failures.

**Comment by isra-fel** [comment]
Hi @filizt , we need all SDKs to be generated basing on rest api spec on master branch, so please regenerate after the spec PR is merged.
Besides, please also write tests to cover new operations; update versions and reslease notes.
Thanks

**Comment by filizt** [comment]
> Hi @filizt , we need all SDKs to be generated basing on rest api spec on master branch, so please regenerate after the spec PR is merged.
> Besides, please also write tests to cover new operations; update versions and reslease notes.
> Thanks

Swagger PR is merged and I regenerated the SDK. Versions and release notes are updated.  We need this PR to be merged asap since we have a customer affecting bug in a previously released SDK. This PR is fixing that issue.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
