### PR TITLE
Install git into identity keyring test container image

### LINKED ISSUE #26354: [Identity] Sparse checkout repositories failing intermittently in nightly runs
Identity nightly test runs are failing with:

> Starting: Sparse checkout repositories
> ==============================================================================
> Task         : PowerShell
> Description  : Run a PowerShell script on Linux, macOS, or Windows
> Version      : 2.194.0
> Author       : Microsoft Corporation
> Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
> ==============================================================================
> Generating script.
> ========================== Starting Command Output ===========================
> /usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/__w/_temp/9cea2d7c-90aa-4e11-a318-eb2dfa064e4b.ps1'
> 
>     Directory: /__w/1
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> d----           1/14/2022  6:01 AM                s
> Repository Azure/azure-sdk-for-net is being initialized.
> git clone --no-checkout --filter=tree:0 https://github.com/Azure/azure-sdk-for-net .
> git: /__w/_temp/9cea2d7c-90aa-4e11-a318-eb2dfa064e4b.ps1:18
> Line |
>   18 |        git clone --no-checkout --filter=tree:0 https://github.com/$($r …
>      |        ~~~
>      | The term 'git' is not recognized as a name of a cmdlet,
>      | function, script file, or executable program. Check the
>      | spelling of the name, or if a path was included, verify that
>      | the path is correct and try again.
> 
> ##[error]PowerShell exited with code '1'.

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1295826&view=results

@jsquire for notification.

### PR DESCRIPTION
**Pull request by benbp**
The live test container image job for identity keyring tests appears to be failing because git is not installed on the image. This would have been recently broken with https://github.com/Azure/azure-sdk-for-net/pull/25983 as git commands are now executed directly on the container as a pipeline step.

Fixes https://github.com/Azure/azure-sdk-for-net/issues/26354

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]

**Review by weshaggard — APPROVED** [review]

**Comment by benbp** [comment]
Git issue has been fixed as of 80fa3130ee9771f65a290c53b6a25d6bdddadb61 so now the pre-existing issue in the [Install Devops Logger](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1350434&view=logs&j=a193ede0-9885-5d40-0426-f58fbbbff2c5&t=44ace3b3-6ccb-52c4-a33b-642c892dca73) step has re-surfaced. I will address that in this PR too.

**Pull request merged**
