### PR TITLE
[Fluent][Testing in progress - do not merge] Expose UpdateResourceAsync so that resources that uses different API …

### PR DESCRIPTION
**Pull request by anuchandy**
…call for update can override it

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anuchandy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anuchan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by cormacpayne** [comment]
@azuresdkci test this please

**Comment by cormacpayne** [comment]
http://azuresdkci.cloudapp.net/view/2-.NET%20SDK/job/sdk-for-net/3340/

**Comment by cormacpayne** [comment]
@azuresdkci retest this please

**Comment by anuchandy** [comment]
Closing this, as this change can be on hold

**Pull request closed without merging**
