### PR TITLE
Regenerate CDN SDK

### PR DESCRIPTION
**Pull request by fore5fire**

### CODE REVIEW

**Comment by isra-fel** [comment]
Please follow the steps here to generate SDK: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#generating-net-sdk

SdkInfo_CdnManagementClient.cs shouldn't be deleted, and a metadata txt under `/eng/mgmt` should be checked in.

Besides, if you want to have a release, you'll need to update the versions. Refer to the doc for more info. Thanks

**Comment by lsmith130** [comment]
@isra-fel Is there a way to run the generate.ps1 tool against a specific API version? When I ran the tool it generated the SDK against a newer version of the CDN swagger that isn't stable yet.

**Comment by isra-fel** [comment]
> @isra-fel Is there a way to run the generate.ps1 tool against a specific API version? When I ran the tool it generated the SDK against a newer version of the CDN swagger that isn't stable yet.

Use `-ConfigFileTag` in your `generate.ps1`. Run `help Start-AutoRestCodeGeneration -Detailed` for more details.

**Comment by lsmith130** [comment]
Thanks for the help @isra-fel. I've updated the PR with the SDK generated by the CDN generate.ps1 script. I've also checked in the to generate.ps1 that pins the current version until the latest version is stable again. Let me know if I wasn't supposed to do that.

**Comment by isra-fel** [comment]
> Thanks for the help @isra-fel. I've updated the PR with the SDK generated by the CDN generate.ps1 script. I've also checked in the to generate.ps1 that pins the current version until the latest version is stable again. Let me know if I wasn't supposed to do that.

That's fine. You'll also need to update `AssemblyFileVersion` in `AssemblyInfo.cs`

**Comment by lsmith130** [comment]
@isra-fel, AssemblyFileVersion has now been updated.

**Comment by lsmith130** [comment]
@isra-fel sorry to bug you again, but we're blocked preparing for our upcoming public preview until this pull request is merged. Let me know if you need me to do anything else.

**Comment by isra-fel** [comment]
> @isra-fel sorry to bug you again, but we're blocked preparing for our upcoming public preview until this pull request is merged. Let me know if you need me to do anything else.

Sorry for the delay. There is one problem left, the version in `.csproj` and `assemblyinfo.cs` do not match.
We are using sememtic versioning so the idea is: if you're making a breaking change, update t he major version. If you are doing feature adding, update the minor version. otherwise the patch version

**Comment by lsmith130** [comment]
> > @isra-fel sorry to bug you again, but we're blocked preparing for our upcoming public preview until this pull request is merged. Let me know if you need me to do anything else.
> 
> Sorry for the delay. There is one problem left, the version in `.csproj` and `assemblyinfo.cs` do not match.
> We are using sememtic versioning so the idea is: if you're making a breaking change, update t he major version. If you are doing feature adding, update the minor version. otherwise the patch version

Fixed

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
