### PR TITLE
[FR] Add tests for tables with fixed and variable rows with empty cells

### PR DESCRIPTION
**Pull request by maririos**
Thanks @kristapratico for the training files and table forms!!!

### CODE REVIEW

**Comment by maririos** [comment]
/ azp run net - formrecognizer - tests

**Comment by maririos** [comment]
/ azp run net - formrecognizer - tests

**Review by kinelski — APPROVED** [review]
LGTM

**Review by kristapratico — APPROVED** [review]

**Review by mssfang — APPROVED** [review]

**Pull request merged**
