### PR TITLE
Reservations RP: converting ARM attributes from enum to string

### PR DESCRIPTION
**Pull request by juhee0202**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by dsgouda — APPROVED** [review]
LGTM subject to CIs passing.

**Comment by juhee0202** [comment]
@shahabhijeet I want to make sure that I have the correct versions for the following with this minor fix.

1. Package version: 1.8.0-preview
2. Assembly version: 1.0.0.0
3. Assembly file version: 1.8.0.0

Should I make the corresponding changes in this pull request?

**Review by dsgouda — CHANGES_REQUESTED** [review]
@shahabhijeet I don't think this needs a version update. The version `1.1.0-preview` is not yet published for this package.

**Comment by juhee0202** [comment]
@dsgouda Is it possible to not publish the `1.1.0-preview` but instead publish with this change as `1.8.0-preview`?

**Comment by dsgouda** [comment]
Talked to @shahabhijeet and this looks good

**Review by dsgouda — APPROVED** [review]

**Comment by dsgouda** [comment]
@juhee0202 Yes, you can kick the publish job once this is merged and it should publish the `1.8.0-preview` version only

**Pull request merged**
