### PR TITLE
Asaflevi/fix/nuget references

### PR DESCRIPTION
**Pull request by asaflevi-ms**
update nuget links in readme files.

### CODE REVIEW

**Comment by asaflevi-ms** [comment]
@pallavit , @chunyu3 
Can one of you approve and merge this one?
I just updated links to our nuget packages.

**Comment by pallavit** [comment]
@asaflevi-ms thank you for fixing these. Could you please also add the SDK to the codeowners alias file - https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS. We usually add two people from the team (primary, secondary).

**Review by pallavit — APPROVED** [review]

**Comment by pallavit** [comment]
@chunyu3, @asaflevi-ms  please let me know if you have any comments before I merge.

**Comment by asaflevi-ms** [comment]
Hi @pallavit 
I updated codeowners file.
Please review and let me know if I did it correctly.
If it's ok, you may merge the changes, no other comments.

**Review by pallavit — APPROVED** [review]

**Comment by pallavit** [comment]
Done.

**Pull request merged**
