### PR TITLE
CognitiveServices NetworkRule support

### PR DESCRIPTION
**Pull request by yangyuan**

### CODE REVIEW

**Comment by yangyuan** [comment]
Hi @dsgouda, can you take a look at this PR.
Just code re-gen and version bump.

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
@yangyuan can you provide me the link to the REST spec PR you have it for this SDK?

**Comment by yangyuan** [comment]
Here is the spec PR:
https://github.com/Azure/azure-rest-api-specs/pull/6009/files

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
This is breaking change, you will have to bump the version to 6.0

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
