### PR TITLE
[TA] Expose ActionName and enable multiple actions from same type

### PR DESCRIPTION
**Pull request by ZulaMostafa**
This PR is for exposing ActionName again as it was disabled in the issue [#22311](https://github.com/Azure/azure-sdk-for-net/pull/22311). It also includes enabling multi actions from the same type as the service supports that right now. Resolves both #24441 and #24430. 

I have some concerns regarding this issue: 

- How should I deal with the breaking change that happened because of adding a new parameter to existing functions? for now I built the project with adding `/p:BaselineAllAPICompatError=true`. I am suggesting that we make overloaded functions for them, with validating that all actions from the same type have unique names. 
- How should the tests be maintained? Should I add a test for every type of action? I am welcoming any suggestions for that.

### CODE REVIEW

**Review by kristapratico — COMMENTED** [review]
Maybe update the changelog with the new feature

**Review by deyaaeldeen — APPROVED** [review]
Implementation looks good!

**Review by jsquire — APPROVED** [review]
LGTM;  failures seem to indicate that the recordings need to be redone to accommodate the API version change.

**Comment by ZulaMostafa** [comment]
> LGTM; failures seem to indicate that the recordings need to be redone to accommodate the API version change.

Should we make a separate PR to run the tests? I noticed that only 4 of them needs to be redone.

**Review by maririos — APPROVED** [review]

**Pull request merged**
