### PR TITLE
[Data Factory] Adding Chaining Trigger

### PR DESCRIPTION
**Pull request by haricr**
Adding new feature Chaining Trigger 

Swagger Spec PR - https://github.com/Azure/azure-rest-api-specs/pull/7076

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @haricr could you
- Add a link to the orginal spec review PR in the description
- Add the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update versions, tags, if necessary

Thanks

**Comment by haricr** [comment]
> Hi @haricr could you
> 
> Add a link to the orginal spec review PR in the description
> Add the .txt file generated when you run generate.ps1(details)
> Update versions, tags, if necessary
> 
> Thanks

I added the Link and verified don't need version update. While running generate.ps1.. I get an error
PS E:\GitHub\azure-sdk-for-net\sdk\datafactory\Microsoft.Azure.Management.DataFactory\src> .\generate.ps1
Start-AutoRestCodeGeneration : Could not find root for output directory since script is not run from SDK repo, please
provide this using the -SdkRepoPath parameter!

If I try to pass the parameter .. It does not work. Can you please help

**Comment by isra-fel** [comment]
@haricr 
That looks strange 🤔 You didn't copy the file out of SDK directory, did you?
Could you try just double click or right-click and choose "Run with PowerShell"?
The last choice is to specify `-SdkRepoRootPath "$PSScriptRoot\..\..\..\.."`, be sure to point to the right folder.

**Comment by haricr** [comment]
> @haricr
> That looks strange 🤔 You didn't copy the file out of SDK directory, did you?
> Could you try just double click or right-click and choose "Run with PowerShell"?
> The last choice is to specify -SdkRepoRootPath "$PSScriptRoot\..\..\..\..", be sure to point to the right folder.

Thanks... passing -SdkRepoRootPath worked.. Updated the review

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
