### PR TITLE
Move SdkCommon -> mgmtcommon

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Move SdkCommon -> mgmtcommon

### CODE REVIEW

**Comment by chidozieononiwu** [comment]
@/azp run azure-sdk-for-net - mgmt

**Comment by chidozieononiwu** [comment]
@Azure/azure-sdk-eng

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Dozie we do not need sdkcommon directory inside mgmtcommon
the sole reason we created mgmtcommon, because of the feedback from @weshaggard that there should not be anything like sdkcommon
So it's better if we simply move all the directories into mgmtcommon

**Comment by chidozieononiwu** [comment]
> Dozie we do not need sdkcommon directory inside mgmtcommon
> the sole reason we created mgmtcommon, because of the feedback from @weshaggard that there should not be anything like sdkcommon
> So it's better if we simply move all the directories into mgmtcommon

I have it updated now

**Comment by shahabhijeet** [comment]
@chidozieononiwu can you disable running the tests that is failing to run.
I will have to fix it once this PR is merged.

**Review by shahabhijeet — APPROVED** [review]

**Comment by weshaggard** [comment]
@shahabhijeet this change broke the full client CI builds. I'm fixing that as part of https://github.com/Azure/azure-sdk-for-net/pull/6623.

**Pull request merged**
