### PR TITLE
Delete .github/pull_request_assignment.yml

### PR DESCRIPTION
**Pull request by konrad-jamrozik**
This is a leftover config file for assignment bot: https://github.com/Azure/azure-sdk-tools/issues/7812#issue-2167999712

### CODE REVIEW

**Comment by weshaggard** [comment]
@m-nash @live1206 would you folks please confirm you weren't depending on this?

**Comment by live1206** [comment]
> @m-nash @live1206 would you folks please confirm you weren't depending on this?

@weshaggard  I guess this file is used for PR auto-assignment, is there any reason we want to remove this?

cc @ArthurMa1978

**Comment by jsquire** [comment]
We should not be using this; the PR associations in CODEOWNERS should be the single point of assigment in this repository.

**Review by jsquire — APPROVED** [review]

**Comment by weshaggard** [comment]
@live1206 @ArthurMa1978 I don't believe this auto-assignment piece has worked for a long time. We are deprecating the bot code as Jesse mentioned we are trying to use codeowners as the source of truth for any automation that requires review and approval.

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
