### PR TITLE
Add dispose to LiveModelAdapter.

### PR DESCRIPTION
**Pull request by zwd-ms**

### CODE REVIEW

**Review by jsquire — DISMISSED** [review]
@zwd-ms:

Please review the Azure SDK onboarding documentation and ensure that your GitHub organization membership and permissions are correct.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

**Comment by jsquire** [comment]
@zwd-ms:  Your organization memberships are not public and your permissions are not correct.   Please review the Azure SDK onboarding documentation.

**Comment by jsquire** [comment]
> @jsquire I've made my memberships public. Scott Kurtzeborn also helped with adding permissions. Could you please clarify if there is still some specific permission I need?

- You now have necessary write permission for the repository.  
- None of your organizations are public.  _([how to from GitHub docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership))_   **_This still needs to be corrected_**

**Comment by zwd-ms** [comment]
@jsquire I believe my memberships were changed to public. I didn't find the doc saying my profile also has to be public, but I just changed it to public. Does it work now?

**Comment by jsquire** [comment]
> @jsquire I believe my memberships were changed to public. I didn't find the doc saying my profile also has to be public, but I just changed it to public. Does it work now?

Yes, it works now.  I'll mention to the onboarding team that it needs to be documented that accounts also need to be public.  Removing my block.

**Comment by zwd-ms** [comment]
> > @jsquire I believe my memberships were changed to public. I didn't find the doc saying my profile also has to be public, but I just changed it to public. Does it work now?
> 
> Yes, it works now. I'll mention to the onboarding team that it needs to be documented that accounts also need to be public. Removing my block.

Thanks!

**Review by tyclintw — APPROVED** [review]

**Review by Tparuchuri — APPROVED** [review]

**Review by Tparuchuri — APPROVED** [review]

**Comment by zwd-ms** [comment]
@jsquire would you help approve this PR?

**Comment by jsquire** [comment]
> @jsquire would you help approve this PR?

Since my team does not own the package, I'd like to see an approval from the registered [code owner](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS#L232) before I help get this merged.   If you and the folks who have reviewed are taking over ownership, would you please update CODEOWNERS as appropriate?   The two approvers will also need to fix up permissions and group memberships if they're being added as owners.

**Comment by tyclintw** [comment]
> > @jsquire would you help approve this PR?
> 
> Since my team does not own the package, I'd like to see an approval from the registered [code owner](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS#L232) before I help get this merged. If you and the folks who have reviewed are taking over ownership, would you please update CODEOWNERS as appropriate? The two approvers will also need to fix up permissions and group memberships if they're being added as owners.

@jsquire I have approved this PR and you can see I'm listed as the owner of this SDK https://github.com/Azure/azure-sdk-for-net/blob/f6a9c7597d269cc1c3384ef08deddf93e74a8c28/.github/CODEOWNERS#L819

**Comment by jsquire** [comment]
> > > @jsquire would you help approve this PR?
> > 
> > 
> > Since my team does not own the package, I'd like to see an approval from the registered [code owner](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS#L232) before I help get this merged. If you and the folks who have reviewed are taking over ownership, would you please update CODEOWNERS as appropriate? The two approvers will also need to fix up permissions and group memberships if they're being added as owners.
> 
> @jsquire I have approved this PR and you can see I'm listed as the owner of this SDK

Thanks for the clarification, @tyclintw.   I see the disconnect, we have two entries for Personalizer in the CODEOWNERS and in the one that I referenced, you were not listed:

 https://github.com/Azure/azure-sdk-for-net/blob/f6a9c7597d269cc1c3384ef08deddf93e74a8c28/.github/CODEOWNERS#L233

I'll get this merged in and the duplicate cleaned up.   In the meantime, would you please make your Microsoft and Azure memberships public and request write access to the repository as referenced in the onboarding docs linked above?

**Review by jsquire — APPROVED** [review]

**Pull request merged**
