### PR TITLE
Use tools package from tools feed instead of local folder

### PR DESCRIPTION
**Pull request by weshaggard**
- Remove local package for our tools and use from feed
- Remove scoped package cache from nuget.config

 @erich-wang @shahabhijeet @chidozieononiwu

cc @Azure/azure-sdk-eng

### CODE REVIEW

**Comment by weshaggard** [comment]
@erich-wang - Do you have a work-item to remove the other nuget packages that are committed under the https://github.com/Azure/azure-sdk-for-net/tree/master/tools/LocalNugetFeed? We need to get the mgmt libraries upgraded to a published release version of those dependency and eliminate those checked in packages.

**Comment by erich-wang** [comment]
@weshaggard, yes, it is on my TODO list and hopefully will finish it next week. I'll update this thread if any progress.

**Comment by weshaggard** [comment]
@shahabhijeet I'm going to close this and let you fix the package with #6937. After that I will clean-up the nuget.config stuff.

**Pull request closed without merging**
