### PR TITLE
Stop building ClientRuntime before every build

### PR DESCRIPTION
**Pull request by matthchr**
- The client runtime doesn't need to be built before every build. In the scope == all case, it is already
    covered by the recursive *.sln include, and in the individual package case it should be included by the target .sln if it's really needed.

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by hovsepm** [comment]
sign job: http://azuresdkci.cloudapp.net/view/2-.NET%20SDK/job/sdk-for-net-sign/1399/

**Comment by matthchr** [comment]
The signing job seems to have failed, but I am not sure it's related:
`  csu.exe Error: 0 : Unable to retrieve User Policy`

**Comment by shahabhijeet** [comment]
@matthchr couple of things we do not want to do this:
1) First when the Scope != all, you are making an assumption that clientRuntime will be included in the "Scoped".sln
2) Also an assumption is being made that both configuration (release and debug) are included in the .sln file for the "Scoped".sln
3) The entire reasoning it does not need to be build on every build is true and it will not get build twice if it's already built, dotnet will simply skip building with the following message
Project TestFramework.Tests (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.

**Comment by matthchr** [comment]
@shahabhijeet 
1. Of course -- that's how references work, they're included in the project.json/.csproj. If it's not in the csproj or project.json then it's not referenced and shouldn't be built. That's the whole point of the references. Additionally, CI passed, so this assumption seems valid anyway right?
2. I'm not sure I follow you here. I didn't change anything to do with release or debug builds, are you suggesting that a project might depend on the client runtime in a project.json or .csproj but only include a reference to it in either debug or release (but not both?)
3. But in the scope != All case, it gets built every time (since the scope targets a single project). It gets built even if that project doesn't reference it, which adds 5m to a build for no reason.

**My assertion is this:** If a project (project.json or csproj) has dependencies (either nuget packages or project dependencies), then *it should reference them*. If it doesn't reference them, then that is a problem *with that particular project*, not something that should be solved by shoehorning in a build step to always build the client runtime no matter what.

**Comment by shahabhijeet** [comment]
@matthchr you are right about "how references work".
If I understand your reasoning, aren't you suggesting ClientRuntime is being build implicitly, why build it explicitly?
I don't know the history of the target that you are deleting, but if I have to guess, it's another target that can be used just build the entire runtime stack and I think that is definitely helpful if I am only working on ClientRuntime. If I remove that target I might end up doing an entire build just to build ClientRuntime.

Is your main concern here is, why is it explicitly getting dependent for build target and you would like to remove it from dependsTarget?
Maybe I am still not able to understand your concern, you have to build Clientruntime once, it will never get build again after it's built once.
So please explain me your main concern here?

**Comment by matthchr** [comment]
@shahabhijeet There is no "implicitly" -- if the project is referenced then it should be built. If it is not referenced it won't be built.

My problem is this: If I have a project (lets call it project A) which doesn't depend on the client runtime project in the source code (for example it uses a nuget package reference instead), then when I do a scoped build targeting project A, we still build the client runtime first. Except that project A _doesn't need the client runtime, since it refers to a nuget package not the project_ -- so I just waste 5 minutes every single time we do this -- and on my team we do this quite a bit.

My second problem is that the way it is set up today is just plain incorrect. References should be built only when referenced. There is no point (as evidenced by the passing build) to build any project "all the time"

**Comment by matthchr** [comment]
Spoke with @shahabhijeet offline and will close this for now as he is planning on rewriting the build system entirely in a few weeks. I will leave this closed and reopen if it becomes a major issue for us in the meantime.

**Pull request closed without merging**
