### PR TITLE
Apply analyzer with updated AZC0002

### PR DESCRIPTION
**Pull request by pshao25**
Apply https://github.com/Azure/azure-sdk-tools/pull/6771 to remove suppressed AZC0002. This PR will be merged after https://github.com/Azure/azure-sdk-tools/pull/6771 merged.

The left suppressions are because they have required cancellationToken but don't have an optional cancellationToken equivalent.

### CODE REVIEW

**Review by annelo-msft — COMMENTED** [review]
This is great!  It would be helpful if we could remove all suppressions of AZC0002 when the analyzer is applied - you can find the full set here: https://grep.app/search?q=AZC0002&filter[repo][0]=Azure/azure-sdk-for-net&filter[path][0]=sdk/

**Comment by pshao25** [comment]
> This is great! It would be helpful if we could remove all suppressions of AZC0002 when the analyzer is applied - you can find the full set here: [https://grep.app/search?q=AZC0002&filter[repo][0]=Azure/azure-sdk-for-net&filter[path][0]=sdk/](https://grep.app/search?q=AZC0002&filter%5Brepo%5D%5B0%5D=Azure/azure-sdk-for-net&filter%5Bpath%5D%5B0%5D=sdk/)

I removed all that could be removed.

**Review by heaths — APPROVED** [review]
LGTM for sdk/cognitivelanguage, sdk/keyvault

**Review by jsquire — APPROVED** [review]
Looks good for AppConfig, Event Hubs, and Service Bus.

**Pull request merged**
