### PR TITLE
Replacing the KeyVault attribute 'purgeDisabled' with a string, enumerated deletion recovery level

### PR DESCRIPTION
**Pull request by dragav**
The purgeDisabled attribute of KeyVault entities (a flag) is not sufficiently detailed to convey the level of protection against deletion/purge currently in effect in a vault. 

The flag, which is not yet publicly released, is retired and replaced with the new RecoveryLevel attribute, which is an enumerated string value indicating clearly reflects the current recovery level for a given vault.

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
I don't see any version bump, publish will fail when you try to publish to nuget.
Please add link to the swagger spec PR.
This PR cannot be merged unless corresponding swagger is merged.

**Review by pomortaz — APPROVED** [review]

**Comment by pomortaz** [comment]
@dragav please update the version.

**Comment by dragav** [comment]
[Corresponding swagger changes](https://github.com/dragav/azure-rest-api-specs/commit/88d067c425212d85c1aa609fc64782f1cf30ff90). Please note these will not be merged into Azure yet since they contain 'preview'-style protocol changes, and we haven't identified a mechanism to designate them as such.

**Comment by shahabhijeet** [comment]
@dragav please understand that this PR cannot be merged, if specs cannot be merged to the main repo.

**Comment by dragav** [comment]
Swagger PR created: https://github.com/Azure/azure-rest-api-specs/pull/1195

**Comment by dragav** [comment]
I'm withdrawing this PR, as it seems to cause a mismatch in the version of the Newtonsoft.Json dependency, and subsequently causing a type loading exception in KV cmdlets. Furthermore, accepting this PR would mean our SDK and PSH are implementing different server protocols.

This SDK build itself is fit for release, and aligns with the current version of the KV REST API spec. Will resubmit it once we've figured out the PSH issue.

**Pull request closed without merging**
