### PR TITLE
Add NUnit Constraint extensions

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Comment by heaths** [comment]
@pakrym @christothes I ended up writing something like this for Question Answering and got to thinking: why don't we start some useful, generic NUnit assertion extensions. I believe all three of us have in the past, though maybe not all generally useful. But these are a couple that are missing - though there are some non-generic, similar classes that don't quite cut it or are more cumbersome to use - from NUnit.

Thoughts?

**Comment by christothes** [comment]
This improves the syntax a bit, but I'm not sure that it's significantly better than the built in collection constraint. Ex:

```c#
Assert.That(dict, Contains.Item(KeyValuePair.Create("foo", 1)));
```
The failure syntax is pretty nice too:

```
Expected: some item equal to ["Foo", 1]
  But was:  < ["Foo", 2], ["Bar", 2] >
```

**Comment by pakrym** [comment]
Or my favorite version:

```C#
CollectionAssert.Contains(activity.Tags, new KeyValuePair<string, string>("http.status_code", "201"));
```

To me, the largest risk with extensions like this is that no one knows they exist. There are already too many ways of doing the same thing (as indicated by this thread :)). I wonder if adding a new one would help people of just make the test code more inconsistent.

**Comment by heaths** [comment]
I didn't know about the `Contains`. Thanks. NUnit is poorly documented. Good docs on concepts, but terrible API docs.

I can omit that one. What do you think about the `Match<T>` one, though? That can satisfy a lot of other cases.

Moreover, I wanted to start this for people to add other value-add assertions that are missing or sub-par in NUnit.

**Comment by pakrym** [comment]
I might be missing something. What's the difference between `Match<>` and `Matches<>`
(https://github.com/nunit/nunit/blob/b34eba3ac1aa6957157857bddd116256c634afab/src/NUnitFramework/framework/Constraints/ConstraintExpression.cs#L326)

**Comment by heaths** [comment]
As an aside, while I am more used to the classic assertions, I've been slowly migrating toward `Assert.That` which is more flexible. I know @christothes is a fan, and I'm growing my fandom as well. For example, NUnit's `Assert.Throws` is type-specific, while xUnit's is not. With `Assert.That(action, Throws.InstanceOf<T>())` you can do that.

Actually, that's another one I should add that xUnit has I really miss: when any `ArgumentException` is thrown, have an optional param to assert it's the `ParamName` expected. NUnit doesn't have this, though there's a long workaround I'd rather abbreviate:

```c#
Assert.That(() => new string(null), Throws.ArgumentException.And.Property("ParamName").EqualTo("value"));
```

Instead, mimicking xUnit somewhat:

```c#
Assert.That(action, Throws.InstanceOf<ArgumentNullException>().WithParamName("value"));
```

Or maybe even define our own top-level object akin to `Is`, `Throws`, etc. Can't extend those, or the above could be even shorter like xUnit.

**Comment by heaths** [comment]
https://github.com/nunit/nunit/issues/3947

**Comment by jsquire** [comment]
> Assert.That(action, Throws.InstanceOf<ArgumentNullException>().WithParamName("value"));

Now that, I would love.   I always seem to mangle the `.And.` chain.

**Comment by heaths** [comment]
I'll address this when I return (or maybe while I'm out), probably something like this: https://github.com/nunit/nunit/issues/2820#issuecomment-511488287

**Pull request closed without merging**
