### PR TITLE
[Blueprints] Management group level assignment

### PR DESCRIPTION
**Pull request by shenglol**
The PR adds support for saving a Blueprint assignment at management group level:
- Regenerated from the latest Swagger.
- Added `ManagementGroupAssignmentsExtensions`.
- Added `ManagementGroupAssignmentOperationsExtensions`.
- Added a scenario test for MG level assignment.

### CODE REVIEW

**Comment by shenglol** [comment]
@filizt mind taking a look as well when you get a chance?

**Review by isra-fel — APPROVED** [review]
LGTM

**Comment by shenglol** [comment]
> LGTM

Can we merge this now? No Blueprints internal team review needed anymore. Thanks!

**Comment by isra-fel** [comment]
Sorry I must have forgotten..

**Pull request merged**
