### PR TITLE
Support for 4 byte AS Numbers

### PR DESCRIPTION
**Pull request by pashukl**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Can you link the spec PR. Please link the PR and not the spec.
Also when you use generate.cmd to generate the SDK, it will add metadata txt file. that is missing also.

**Comment by pashukl** [comment]
Abhijeet,

I used autorest to generate the SDK. This is the new suggested way to generate the SDK.
I have linked the spec PR in Summary of Changes.  I don’t know how to explicitly link it?
This is how it shows to me.  Let me know if I am missing something here.

pashukl<https://github.com/pashukl> added some commits 4 hours ago <https://github.com/Azure/azure-sdk-for-net/pull/3906#commits-pushed-d8ca7d5>
[@pashukl]<https://github.com/pashukl>
Summary of Changes:<https://github.com/Azure/azure-sdk-for-net/pull/3906/commits/d8ca7d50b78879a1a73efc0ceb3f26495087b5c1> …
 - These are SDK changes due to change in azure-rest-api-specs as shown:
   Azure/azure-rest-api-specs#2066<https://github.com/Azure/azure-rest-api-specs/pull/2066>

The overall change is to support 4 byte unsigned values for AS Numbers.
This change will be accomodated in Azure Powershell.
d8ca7d5<https://github.com/Azure/azure-sdk-for-net/pull/3906/commits/d8ca7d50b78879a1a73efc0ceb3f26495087b5c1>
[@pashukl]<https://github.com/pashukl>
Merge branch 'psSdkJson6' of<https://github.com/Azure/azure-sdk-for-net/pull/3906/commits/3a2771047c0814aca9fe9e31d5a39aad96f8efc0> https://github.com/Azure/azure-sdk-for-net<https://github.com/Azure/azure-sdk-for-net/pull/3906/commits/3a2771047c0814aca9fe9e31d5a39aad96f8efc0>…<https://github.com/Azure/azure-sdk-for-net/pull/3906/commits/3a2771047c0814aca9fe9e31d5a39aad96f8efc0> …
… into psSdkJson6

**Comment by pashukl** [comment]
Reminder for reviewers.  Please let me know if anything else is missing.

**Comment by shahabhijeet** [comment]
@pashukl when you use generate.cmd to generate the sdk, it creates a meta data text file that reflects the commit for the spec it used to generate.
That file is missing, hence you need to use generate.cmd to generate your sdk for the spec you listed above.
This PR cannot be merged without you regenerating using generate.cmd

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
