### PR TITLE
Changing customConfig to long and making it a required parameter

### PR DESCRIPTION
**Pull request by q3blend**
## Description
Changing customConfig parameter to reflect the recent updates to bing custom search updates.

1. customConfig is now a required parameter
2. customConfig is a long instead of int

https://github.com/Azure/azure-rest-api-specs/pull/2324
https://github.com/Azure/azure-rest-api-specs/pull/2304
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
use generate.cmd to generate your sdk.
If you would like to publish this sdk, you will have to bump up the version in .csproj as well as assemblyInfo.
Pleaes update the PR once all spec PRs are merged.

**Comment by shahabhijeet** [comment]
@q3blend using generate.cmd allows us to create meta data about what version of spec was used to generated this SDK. I do not see that meta data file (which is a .txt file)

**Comment by q3blend** [comment]
spec is now merged

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Please use generate.cmd to generate your SDK.
This will update the meta data file to reflect the branch/commit you are using to generated your SDK from the spec that is already checked inside spec repo.

**Comment by q3blend** [comment]
Regenerated using generate.cmd

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
If you are planning to publish this, you will have to rev up your version using semver.io rules
If there are any breaking changes, you will have rev up your major version of stable(non preview) nuget package
if this is preview package, just rev up you minor version

**Comment by q3blend** [comment]
@shahabhijeet The current version is broken for 50% of the instances, I think it should be replaced instead of a rev up.

**Comment by shahabhijeet** [comment]
@q3blend nuget packages can never be replaced/deleted.
So your only option is to rev the version and create a new one as soon as possible.

**Comment by q3blend** [comment]
https://docs.microsoft.com/en-us/vsts/package/nuget/unlist-delete why would this not work?

**Comment by shahabhijeet** [comment]
@q3blend this PR is almost a month old now.
If you think this is not urgent right now, please open this PR when you are ready to be published.
If this PR is not addressed by EOW, it will be closed.

**Comment by q3blend** [comment]
How should I update the assembly file? There are AssemblyVersion and AssemblyFileVersion

**Comment by shahabhijeet** [comment]
@q3blend update nuget package version (in .csproj) to 1.3.0-preview
AssemblyFileVersion shold be 1.3.0, but AssemblyVersion remains unchanged

**Comment by q3blend** [comment]
@shahabhijeet why 1.3.0 and not 1.2.0? previous version is 1.1.0

**Comment by shahabhijeet** [comment]
@q3blend I overlooked existing published version. In this case it will be 1.2.0

**Pull request merged**
