### PR TITLE
add mvad list model record test

### PR DESCRIPTION
**Pull request by luxiong-ms**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by pshao25 — APPROVED** [review]

**Comment by dw511214992** [comment]
aaa

**Comment by dw511214992** [comment]
aaa

**Comment by dw511214992** [comment]
aaa

**Comment by dw511214992** [comment]
aaa

**Pull request merged**
