### PR TITLE
BGP over IPsec APIs for ServiceManagement

### PR DESCRIPTION
**Pull request by lamchester**
New BGP APIs, fixing an issue with creating local network gateways, and tests to back that up

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lamchester__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (chelam). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@lamchester please update the package version in nugget.proj and assemblyinfo.cs

**Comment by lamchester** [comment]
Changed the version numbers to 7.0.5 (from 7.0.4) in both files.

**Comment by azurecla** [comment]
Hi __@lamchester__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (chelam). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@lamchester please fix failed test

**Comment by lamchester** [comment]
Added references in the csproj file to the recorded test data

**Pull request merged**
