### PR TITLE
Bring back removed code from TestEnvironment for Search

### PR DESCRIPTION
**Pull request by cormacpayne**
Search uses the method `LookupEnvironmentFromBaseUri` from the class `TestEnvironment` in TestFramework. However, in [this commit](https://github.com/Azure/azure-sdk-for-net/commit/141cc6d9a9b46cce0a61f3abf3644f9440cb127b#diff-97df25f566ca6081d373b5a222d925c7L729), that method was accidentally removed.

Since we will be bumping all TestFramework versions to 1.4.1-preview for the ADAL upgrade, we need to bring back to the code so there are no breaks for Search.

### CODE REVIEW

**Comment by cormacpayne** [comment]
@markcowl @brjohnstmsft would you mind taking a look and letting me know if this is OK?

**Comment by brjohnstmsft** [comment]
@cormacpayne Thanks for catching this!

The change looks good, but what is the plan long-term? Search tests need to be able to tell what environment they are running in, otherwise it isn't possible to construct the correct base URI. Will this functionality eventually go back into TestFramework? I'm surprised no other Azure services with data plane APIs have a dependency on this.

**Comment by markcowl** [comment]
@brjohnstmsft Would you file an issue for the functionality you would like from the test environment?

**Comment by brjohnstmsft** [comment]
@markcowl It doesn't matter to me where that code lives, as long as it works. I'm just curious what was the rationale for removing it from the Test Framework in the first place.

**Comment by cormacpayne** [comment]
@brjohnstmsft I believe it was accidentally removed by @shahabhijeet when he was making changes to the testing environment for .NET SDK

**Pull request merged**
