### PR TITLE
fix: ResourceDetails discriminator Source vs. source

### PR DESCRIPTION
**Pull request by eliagrady**
The resourceDetails object, that was shared in both of our sub assessments api and our assessment api was not aligned.
The current discriminator for assessments is 'Source' and it should have been 'source' (bug).
It cannot be changed.

The subAssessment APIs are using 'source' as expected - and are working properly.

This change allows the ResourceDetails to be populated correctly by the SDK for both assessments and sub assessments.

### CODE REVIEW

**Comment by YalinLi0312** [comment]
@eliagrady Could you please follow the checklist below?
- [ ] Swagger review PR(s) link in PR description, and the PR(s) is merged
- [ ] Metadata file `eng/mgmt/mgmtmetadata_{RP}.txt` is updated
- [ ] Versions in `*.csproj` and `AssemblyInfo.cs` are updated, and follows semver
- [ ] Release notes in `*.csproj` is updated
- [ ] If there's a API-version update, the API tags in `Az.Sdk.props` are updated
- [ ] Generated code is not touched
- [ ] Proper test coverage

**Comment by eliagrady** [comment]
Thanks @YalinLi0312 - this PR is pending on that one: https://github.com/Azure/azure-rest-api-specs/pull/11400 - I'll update

**Comment by jsquire** [comment]
Hi @eliagrady.  There hasn't been recent engagement on this PR.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by eliagrady** [comment]
Closing as this moved to a different PR

**Pull request closed without merging**
