### PR TITLE
Enable Active-Active gateway feature operations.

### PR DESCRIPTION
**Pull request by Nilambari**
Changes in files:-
1. Generated/Models/VirtualNetworkGateway.cs :- Added Active-Active feature flag
2. Properties/AssemblyInfo.cs and project.json :- Network package version increment.
3. GatewayOperationsTests.cs :- Added new test: VirtualNetworkGatewayActiveActiveFeatureTest to validate enabled Active-Active gateway feature related operations. Recorded and added this test result.
4. Most files have some typo fixes which got picked up in generated files.

### CODE REVIEW

**Comment by markcowl** [comment]
@Nilambari Please clean up these commits - a change of thsi size should have only a few commits with logical commit comments.

**Comment by Nilambari** [comment]
@markcowl I had done Previous commits till e23fe6e, to validate some changes and reverted back them to make the repo same as Azure repo. If you see the files changes, there are no major changes. I have mentioned what files are changed with what are the changes in details. How can I clean up commits which are already done on this repo?

**Comment by markcowl** [comment]
@Nilambari the commits in your PR are the commits that differ between the AutoRest branch and your branch.  You need to rebase your branch on the AutoRest branch to remove these commits.

You can use ```git rebase``` and ```git cherry-pick``` for this purpose.

**Comment by Nilambari** [comment]
Sure. closing this PR. Opened new one:-https://github.com/Azure/azure-sdk-for-net/pull/2307

**Pull request closed without merging**
