### PR TITLE
Rename FormRecognizer directory to remove Vision. suffix

### PR DESCRIPTION
**Pull request by ramparab**
Vision. suffix in directory name was added unintentionally.

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
Why are there so many commits? Do you need to rebase?

**Comment by yangyuan** [comment]
Hi @ramparab, each time you do create a new branch for PR, better practice is to create a branch from **current master**.

**Comment by ramparab** [comment]
> Why are there so many commits? Do you need to rebase?
done.

**Comment by ramparab** [comment]
reopening to continue work.

**Comment by ramparab** [comment]
> Hi @ramparab, each time you do create a new branch for PR, better practice is to create a branch from **current master**.
makes sense.

**Review by yangyuan — APPROVED** [review]

**Review by AlexGhiondea — APPROVED** [review]

**Pull request merged**
