### PR TITLE
Fix storage extension build

### PR DESCRIPTION
**Pull request by JoshLove-msft**
FYI @annelo-msft @christothes @pakrym this highlights another place where build breaks can slip through the cracks - cross library code sharing.

### CODE REVIEW

**Review by amnguye — APPROVED** [review]

**Comment by annelo-msft** [comment]
@JoshLove-msft, do we know why this build break made it past CI?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft, do we know why this build break made it past CI?

Yep, it is because this file is pulled in via shared source by Storage, but it doesn't originate from Core so we don't end up running the core pipeline (which would have caught it).

**Comment by annelo-msft** [comment]
I see, this project pulls it in from EG not Core, where the Core pipeline would have caught it since it runs CIs for all libraries ... Would we be able to prevent this class of build breaks by running pipelines for all libraries that pull in shared source from a given library?

**Comment by JoshLove-msft** [comment]
> I see, this project pulls it in from EG not Core, where the Core pipeline would have caught it since it runs CIs for all libraries ... Would we be able to prevent this class of build breaks by running pipelines for all libraries that pull in shared source from a given library?

Yes, that would catch issues like this.

**Comment by annelo-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/26482

**Pull request merged**
