### PR TITLE
Added IKeyVaultClient 

### PR DESCRIPTION
**Pull request by omerlh**
Hey
I've created an interface for keyvaultclient class. This done in order to improve testability of classes that depended on keyvaultclient.
Thanks
Omer

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omerlh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by azurecla** [comment]
__@omerlh__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by pomortaz** [comment]
Thanks @omerlh for your contribution. The interface will change with the next major version of the Key Vault SDK and we don’t want any dependency to this interface. I will make sure the next major version of the SDK will have an IKeyVaultClient interface.

**Pull request closed without merging**
