### PR TITLE
Update SDK (2020-11-01)

### PR DESCRIPTION
**Pull request by digavino**
Added version 2020-11-01 which introduces WAF JSON and Body exclusion support.

### CODE REVIEW

**Comment by bquantump** [comment]
Please ensure the following checklist is complete: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#appendix-a-pr-review-checklist

**Comment by bquantump** [comment]
Please look into the CI failures.

**Comment by allenjzhang** [comment]
The code checke result looks fine. Will help merge once approved.

**Comment by bquantump** [comment]
Please ensure the following checklist is complete: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#appendix-a-pr-review-checklist

**Comment by digavino** [comment]
> Please ensure the following checklist is complete: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#appendix-a-pr-review-checklist

Am I missing anything ? I think that it should be fine now, right ?

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
