### PR TITLE
Cont'd simplifying constructor impl logic leveraging Manager.Inner

### PR DESCRIPTION
**Pull request by martinsawicki**
Continued port of plumbing simplifications from Java SDK, based on commits:
- KeyVault: https://github.com/Azure/azure-sdk-for-java/commit/6aa3d41291e95c8a87d607557acf94cba6ece500
- Networking: https://github.com/Azure/azure-sdk-for-java/commit/703e68d45b0f444b34d2bb53b7444d74dc3ab77c
- Redis: https://github.com/Azure/azure-sdk-for-java/commit/0962961761efc20bb5762f6044e114d578824e15
- SQL: https://github.com/Azure/azure-sdk-for-java/commit/013d2ca0614c28986bf9478e62e8c6c43c41dacc
- Storage: https://github.com/Azure/azure-sdk-for-java/commit/e0a629613d070236dc49afd827df87051fbae70b
- Traffic Manager: https://github.com/Azure/azure-sdk-for-java/commit/12bad88eaf2d590189f16925f6d1874a4d2f91f5

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@martinsawicki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (marcins). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Pull request merged**
