### PR TITLE
Add files from API Design Tutorial branch to Implementation Tutorial branch

### PR DESCRIPTION
**Pull request by annelo-msft**
The implementation/starter branch currently lacks the Design Activity project and the ci.yml and test.yml files.  Adding these for completeness.  After this is merged, I will create the api-design/complete branch from the implementation/starter branch.

### CODE REVIEW

**Review by christothes — APPROVED** [review]

**Comment by christothes** [comment]
If this is relevant for the implementation section, we'll need to merge this into `/engsys/starter` also.

**Comment by annelo-msft** [comment]
> If this is relevant for the implementation section, we'll need to merge this into `/engsys/starter` also.

The yml files at least are necessary to make the engsys tutorial work.
@mitchdenny

**Comment by mitchdenny** [comment]
@christothes grab the ci.yml and tests.yml files from sdk/template and adjust for your package names. Although this might be moot with the other automation that I'm putting into place.

**Pull request merged**
