### PR TITLE
[AMS] Update Media services to 2022-07 version of encoding services.

### PR DESCRIPTION
**Pull request by giakas**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by archerzz — COMMENTED** [review]
@giakas The sample codes are still out-of-sync. 
Could you please run `dotnet build /t:GenerateTest`? The sample codes are out-of-sync. Thanks.

**Review by archerzz — CHANGES_REQUESTED** [review]
Need to rename `Fade` class. For details, see the comment in API view.

**Comment by giakas** [comment]
> @giakas The sample codes are still out-of-sync. Could you please run `dotnet build /t:GenerateTest`? The sample codes are out-of-sync. Thanks.

Getting some errors when I try to run the generate test
image
Not sure where these packages are being installed. Can you help me fix this error.

**Review by archerzz — APPROVED** [review]

**Pull request merged**
