### PR TITLE
Ensure receive link is established when renewing session lock

### LINKED ISSUE #16092: RenewSessionLockAsync behavior
An interesting issue was brought up by @slav and @chris-skuvault – with our change to retry on transient errors for session receivers, the behavior of RenewSessionLock becomes a bit weird – sometimes SessionLockLost can be retried successfully, and sometimes not. 

The issue is that it will be successful if the receiver link has already been reconnected, and otherwise it will fail with SessionLockLost. A simple fix would be to make RenewSessionLock establish the receiver link if it isn’t already open. It would still be possible to get into a situation where the session lock is expired due to passing the expiry time, in which case RenewSessionLock will still fail, but by making this adjustment we would make it so that a SessionLockLost error is once again not retriable.

Note that this doesn't apply to message lock renewal, since once the receiver link is lost, reconnecting will not enable the same message lock to be renewed since the lock is maintained per message rather than per link.

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/16092

### CODE REVIEW

**Review by MiYanni — APPROVED** [review]
Is this a kind of issue I'd see with the stress tests I'm making? (One of them is refreshing session locks). Also, is there any way to have a test for this?

**Comment by JoshLove-msft** [comment]
> Is this a kind of issue I'd see with the stress tests I'm making? (One of them is refreshing session locks). Also, is there any way to have a test for this?

Can the stress test simulate a network fault? Otherwise it is kind of tricky to test.

**Comment by jsquire** [comment]
> > Is this a kind of issue I'd see with the stress tests I'm making? (One of them is refreshing session locks). Also, is there any way to have a test for this?
> 
> Can the stress test simulate a network fault? Otherwise it is kind of tricky to test.

Not presently.   Some induced failures are on the wish list, but I'd speculate that they're a ways out.

**Pull request merged**
