### PR TITLE
Media Services Version 2.0.3

### PR DESCRIPTION
**Pull request by BrianBlum**
Based on https://github.com/Azure/azure-rest-api-specs/pull/6143

### CODE REVIEW

**Comment by dsgouda** [comment]
@BrianBlum Please manually generate the SDK and update the PR. We have disabled auto PR

**Comment by BrianBlum** [comment]
@dsgouda, thanks, I'll update the PR. Is there somewhere I should look for the latest process?

**Comment by dsgouda** [comment]
@BrianBlum you can use the generate.ps1 script as before to generate the code.

**Comment by BrianBlum** [comment]
@dsgouda, it looks like you already merged the auto PR change [#6431](https://github.com/Azure/azure-sdk-for-net/pull/6431). 

I reran generate.ps1, and there were no differences in the newly generated files.

6431 contained just the 21 files that changed based on [Azure/azure-rest-api-specs#6143](Azure/azure-rest-api-specs#6143)

**Comment by dsgouda** [comment]
> 
> 
> @dsgouda, it looks like you already merged the auto PR change [#6431](https://github.com/Azure/azure-sdk-for-net/pull/6431).
> 
> I reran generate.ps1, and there were no differences in the newly generated files.
> 
> 6431 contained just the 21 files that changed based on [Azure/azure-rest-api-specs#6143](Azure/azure-rest-api-specs#6143)

Thanks for confirming this.

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by BrianBlum** [comment]
@dsgouda  Thanks for the merge. In the future, will the .net sdk be merging autoPRs?

And the generate.ps1 is a step we should run to confirm that the correct changes are in the repo?

**Comment by dsgouda** [comment]
Auto PRs will be merged after 06/11

**Comment by BrianBlum** [comment]
Thanks!

**Pull request merged**
