### PR TITLE
[AppConfig] Adding new parameter 'PublicNetworkAccess' for ConfigurationStoreUpdateParameters

### PR DESCRIPTION
**Pull request by avanigupta**
This PR is for updating management plane SDK for AppConfig after we made some changes to the REST API specs [here](https://github.com/Azure/azure-rest-api-specs/pull/10479).

### CODE REVIEW

**Comment by allenjzhang** [comment]
Please see failure [details](https://github.com/Azure/azure-sdk-for-net/pull/14682/checks?check_run_id=1064761536) and make correction. We will revisit this PR once checks are passing.

**Comment by avanigupta** [comment]
Hi @allenjzhang, the PR is ready for review.

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
