### PR TITLE
Add missing token credentials for ShareServiceClient when configured using dependency injection

### PR DESCRIPTION
**Pull request by daedam**
*First time contributor, so apologies if I missed anything.* 😄

The `Azure.Files.Storage.Shares` API includes extension methods (`AddFileServiceClient`) for configuring a `ShareServiceClient` that can be used to work with Azure Files shares. One of the extension methods allows for configuration using only the URI of the file share service, and it is supposed to use the token credential provided via `AzureClientFactoryBuilder.UseCredential`. For example:

```c#
var host = Host.CreateDefaultBuilder()
    .ConfigureServices(services =>
    {
        services.AddAzureClients(clientBuilder =>
        {
            clientBuilder.AddFileServiceClient(new Uri("https://[account].file.core.windows.net/"))
                .ConfigureOptions(options =>
                {
                    // Required for data operations using token credentials
                    // Figuring out that this is needed was not very straightforward
                    options.ShareTokenIntent = ShareTokenIntent.Backup;
                });
            clientBuilder.UseCredential(new DefaultAzureCredential());
        });
    })
    .Build();
```

Then, in the consuming class (assuming an injected instance of `ShareServiceClient` called `_serviceClient`):

```c#
ShareClient sc = _serviceClient.GetShareClient("myshare");
ShareDirectoryClient dir = sc.GetDirectoryClient("testdir");
dir.CreateIfNotExists(); // Fails because sc.ClientConfiguration.TokenCredential is null
```

However, this is not currently working (as of version 12.16.0). `ShareClient` instances created from `ShareServiceClient` have their `ClientConfiguration.TokenCredential` property set to `null` and therefore cannot authenticate. This is because the extension method extends `IAzureClientFactoryBuilder` instead of `IAzureClientFactoryBuilderWithCredential` and fails to pass the credential into the constructor for `ShareServiceClient`.

I referenced the extension methods for [`SecretClientBuilderExtensions`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/SecretClientBuilderExtensions.cs) and [`BlobClientBuilderExtensions`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobClientBuilderExtensions.cs) implementations in researching this issue. This change aligns with the way it is handled in those classes, where configuration using the service URI is working. I did not include the conditional or the `requiresCredential: false` parameter as in the Blob service implementation because my understanding is that credentials are always required for file shares (though please let me know if I'm mistaken).

I didn't add any new unit tests since this is a bug fix for existing functionality, but I can take a shot at it if needed. I did build this package with my proposed fix and tested that it works as expected in the Azure Functions app I was building that led me to this bug and in a small console test app (which I'm happy to provide if it would be helpful).

### CODE REVIEW

**Comment by amnguye** [comment]
Hey Adam! Thanks for the contribution!

I think we should probably follow the pattern of making a new overload to take in the `TokenCredential`, and leave the one that only takes the `Uri`.

```
        /// <summary>
        /// Registers a <see cref="ShareServiceClient"/> instance with the provided <paramref name="serviceUri"/> and <paramref name="tokenCredential"/>
        /// </summary>
        public static IAzureClientBuilder<ShareServiceClient, ShareClientOptions> AddFileServiceClient<TBuilder>(this TBuilder builder, Uri serviceUri, TokenCredential tokenCredential)
            where TBuilder : IAzureClientFactoryBuilder
        {
            return builder.RegisterClientFactory<ShareServiceClient, ShareClientOptions>(options => new ShareServiceClient(serviceUri, tokenCredential, options));
        }
 ```
 
 that way when you need to call the `AddFileServiceClient`, it will look like this instead.
 
 ```
 clientBuilder.AddFileServiceClient(new Uri("https://[account].file.core.windows.net/"), new DefaultAzureCredential())
                .ConfigureOptions(options =>
                {
                    // Required for data operations using token credentials
                    // Figuring out that this is needed was not very straightforward
                    options.ShareTokenIntent = ShareTokenIntent.Backup;
                });
```

**Comment by daedam** [comment]
Hi Amanda! Thank you so much for reviewing!

Respectfully, I'm not sure I understand the rationale of your suggestion to add an additional extension method that takes the `TokenCredential`. Would you mind sharing your thoughts?

As I see it, adding such an overload would create a disparate experience in configuring the Azure Files client as compared to all other Azure clients and could cause confusion. For instance:

```c#
services.AddAzureClients(clientBuilder =>
{
    // Configure credential to use for all Azure clients EXCEPT file service
    clientBuilder.UseCredential(new DefaultAzureCredential());

    // Blob client uses token from `UseCredential` call above
    clientBuilder.AddBlobServiceClient(new Uri("https://[account].blob.core.windows.net/");

    // Key Vault client uses token from `UseCredential` call above
    clientBuilder.AddSecretClient(new Uri("https://[vaultname].vault.azure.net/");

    // File service client ignores `UseCredential` and must be passed the token explicitly
    clientBuilder.AddFileServiceClient(new Uri("https://[account].file.core.windows.net/"), new DefaultAzureCredential())
        .ConfigureOptions(options =>
        {
            options.ShareTokenIntent = ShareTokenIntent.Backup;
        });
});
```

I looked at a handful of other client builder extensions in the SDK, but I haven't seen any other `Add[Service]Client` extension methods that directly take a `TokenCredential` as a parameter; rather, they expect the token to be provided via `UseCredential` if the URI-only extension method was called.

In examining this further and considering your suggestion along with the idea of not changing current behavior, I still think the existing extension method should be altered, but perhaps it should actually match what was done in the [`BlobClientBuilderExtensions`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobClientBuilderExtensions.cs) class, which is almost identical to this one. Bringing the method in line with the Blob service would look like this:

```c#
public static IAzureClientBuilder<ShareServiceClient, ShareClientOptions> AddFileServiceClient<TBuilder>(this TBuilder builder, Uri serviceUri)
    where TBuilder : IAzureClientFactoryBuilderWithCredential
{
    return builder.RegisterClientFactory<ShareServiceClient, ShareClientOptions>(
        (options, token) => token != null ? new ShareServiceClient(serviceUri, token, options) : new ShareServiceClient(serviceUri, options),
        requiresCredential: false);
}
```

That way, if `UseCredential` is not called, the existing behavior of constructing without a token would be respected (although I'm not sure that's useful...see below). However, if `UseCredential` is called, the `ShareServiceClient` and resulting `ShareClient` instances would use the configured token.

That said, I'm curious as to the point of the `new ShareServiceClient(Uri, ShareClientOptions)` constructor in the first place. As I understand it, Azure Files does not allow anonymous access (at least not currently). If a `ShareServiceClient` instance is created with no credentials (neither token, SAS, nor connection string), is it actually able to do anything at all?

If, indeed, Azure Files is not meant to be accessed anonymously, then I think `requireCredential` should really be set to `true`, calling only `new ShareServiceClient(Uri, TokenCredential, ShareClientOptions)` as in my original submission. This would throw an exception if someone attempted to configure with only a URI and no call to `UseCredential`, alerting them that a credential is needed.

Thanks for indulging me. I look forward to hearing your thoughts!

**Comment by jaschrep-msft** [comment]
@daedam looking over your PR, I'm surprised our API compat tool isn't flagging this. Since you're changing the generic type restrictions on a public method from one interface to another, and neither interface inherits from the other, this seems like a breaking change to me. I'll check in with some people to see whether this is my mistake or the tooling, and I'll pull this locally to run some manual checks, but if I'm right then I don't think we can take this change even if it's correct.

I do see what you're saying though about it being a bit off to take a token credential as a parameter rather than something provided through the factory, as it seems the factory interfaces were designed for precisely this. I'm not sure off the top of my head if .NET will allow two identical signatures but with different generic type constraints. hmm...

**Comment by jaschrep-msft** [comment]
Ah. it seems a current flakey error we're having in our analyze step was masking that it would have caught this breaking change issue. We can really only accept additive changes when it comes to our public API.

@daedam if you could modify this PR such that it adds your existing change as a new method, rather than changing the existing one, we can discuss from there. I also checked and .NET will not accept methods with the same signature but different generic type constraints. You'll need to give this method a different name to build. I suggest appending "WithCredential" to the name for the new method. It won't mirror blobs as you point out, but that's impossible for us to do while maintaining compatibility.

You'll also want to run `.\eng\scripts\Export-API.ps1 storage` from the repository root. If I recall correctly, this requires Powershell 7 to run properly.

**Comment by daedam** [comment]
@jaschrep-msft Thank you for your feedback and guidance! I have revised the PR to revert the existing extension method and add a new one named `AddFileServiceClientWithCredential` as you and @amnguye suggested. I also included the same notes that are on the corresponding constructor for `ShareServiceClient` in the XML doc comments because I think it adds valuable context about what operations are supported using token authentication and the necessity to configure `ShareClientOptions.ShareTokenIntent`. Finally, I ran the `.\eng\scripts\Export-API.ps1 storage` script that you mentioned, which produced two additional changed files.

I understand and respect the need to avoid breaking changes in the SDK. Would there be any value in marking the original extension method that takes only a URI as obsolete? One thing I'm still unclear on is whether that method actually produces a usable client. If all operations for Azure Files Shares require authentication and that method does not configure any authentication, would it make sense to mark it as obsolete so that developers know to avoid it? Perhaps it could later be removed as a breaking change in the next major version release.

Thank again for your assistance and consideration!

**Comment by amnguye** [comment]
Looks like you need to agree to the Contributor License Agreement.

At the same time looks like CI is failing, but doesn't look like it's due to the changes in this PR. I'm going to keep trying to rerun it until it passes.

**Comment by jaschrep-msft** [comment]
@daedam We don't typically use `[Obsolete]` markers to my knowledge, but we do use `[EditorBrowsable(EditorBrowsableState.Never)]`. I think since there are currently no plans for a major version release, an obsolete tag is not necessary to warn developers at this time.

**Comment by daedam** [comment]
> Looks like you need to agree to the Contributor License Agreement.

I'm working on making sure I don't have a conflict with my company's policies about this and will complete the agreement once I get the go-ahead from them. I don't anticipate that it will be an issue.

> At the same time looks like CI is failing, but doesn't look like it's due to the changes in this PR. I'm going to keep trying to rerun it until it passes.

@amnguye Thanks for investigating! Any insight you have is much appreciated.

> We don't typically use `[Obsolete]` markers to my knowledge, but we do use `[EditorBrowsable(EditorBrowsableState.Never)]`.

Makes sense. Thanks for the tip @jaschrep-msft. Any objections to applying `[EditorBrowsable(EditorBrowsableState.Never)]` to the old extension method and adding a note to the XML doc about how that method ignores the factory credential?

**Comment by jaschrep-msft** [comment]
> Any objections to applying `[EditorBrowsable(EditorBrowsableState.Never)]` to the old extension method and adding a note to the XML doc about how that method ignores the factory credential?

I'm not well-versed in the actual implementation classes that tend to be provided to these sorts of things. But if Azure SDK provides types that implement both interfaces, it's probably best to do that.

**Comment by daedam** [comment]
@microsoft-github-policy-service agree

**Comment by daedam** [comment]
I have agreed to the CLA and added the attribute to disable editor browsing of the old method. Please let me know if any further revisions are needed. Thanks!

**Review by jaschrep-msft — APPROVED** [review]

**Comment by daedam** [comment]
This pull request was approved quite some time ago but never merged, and I don't appear to have permission to merge it. Can someone on the Azure SDK team please proceed with merging so that this PR isn't auto-closed? Thanks! @amnguye @jaschrep-msft

**Pull request merged**
