### PR TITLE
Added support for DeveloperPortal and Open Api Json format

### PR DESCRIPTION
**Pull request by solankisamir**
- Added support for `developerPortal` endpoint in apimanagement service resource.
- Added support for overriding the `common` tenant when configuring AAD identity provider.
- Added support for specifying `httpCorrelationProtocol` and `verbosity` when configuring diagnostics on global and api level.
- Added support for importing OpenApi 3.0 document in Json format.

Related rest spec
https://github.com/Azure/azure-rest-api-specs/pull/8279
https://github.com/Azure/azure-rest-api-specs/pull/8271
https://github.com/Azure/azure-rest-api-specs/pull/8155
https://github.com/Azure/azure-rest-api-specs/pull/7378

### CODE REVIEW

**Comment by jeepdude1980** [comment]
Hey I suggest you close this down before I hunt you down

**Comment by solankisamir** [comment]
@jeepdude1980 happy to chat, you can reach me at samir.solanki@microsoft.com

**Comment by jeepdude1980** [comment]
Someone has hacked my Accounts please do not assist them any further

**Comment by jeepdude1980** [comment]
Please close down the repository immediately I will be getting into work
soon I will message you with more details

**Comment by jeepdude1980** [comment]
What is your contact phone number

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @solankisamir  please also check in the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
Thanks

**Comment by solankisamir** [comment]
@isra-fel I tried running the following, but it just hangs there forever
> Start-AutoRestCodeGeneration -ResourceProvider "apimanagement/resource-manager" -AutoRestVersion "latest" -ConfigFileTag "package-2019-01" -SdkRepoRootPath "D:\git\azure-sdk-for-net"

Last statement
> cmd.exe /c autorest.cmd https://github.com/Azure/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/readme.md --csharp --version=latest --refle
ct-api-versions --tag=package-2019-01 --csharp-sdks-folder=D:\git\azure-sdk-for-net

**Comment by solankisamir** [comment]
> Hi @solankisamir please also check in the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
> Thanks

fixed

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
