### PR TITLE
fix c cref

### PR DESCRIPTION
**Pull request by mairaw**
The correct tag is see cref

This causes content to dropout in docs

e.g. https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.search.models.fieldmappingfunction.base64encode?view=azure-dotnet#Microsoft_Azure_Search_Models_FieldMappingFunction_Base64Encode
image

### CODE REVIEW

**Comment by mairaw** [comment]
Any feedback here @arv100kri @bleroy @brjohnstmsft?

**Review by bleroy — APPROVED** [review]
Seems good, all in customizations. Thanks!

**Comment by mairaw** [comment]
You're welcome. Who can merge this? I don't have permissions here 😄

**Comment by mairaw** [comment]
@heaths is this something you can help merge? Thanks!

**Review by heaths — APPROVED** [review]

**Comment by heaths** [comment]
I can merge it, but we're only releasing older Microsoft.Azure.* packages for critical updates where a comparable Azure.* package exists, such as these (Azure.Search.Documents replaces these).

**Pull request merged**
