### PR TITLE
Update Compute library with DiskRP specs, add tests, and bump up the …

### PR DESCRIPTION
**Pull request by hyonholee**
…version number to 14.0.0

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/dev/Documentation/breaking-changes.md).**

Breaking change: 

- Container Service client name is changed from ContainerService to ContainerServices, due to the Swagger update, which now follows other spec conventions.

- ContainerService AgentPoolProfile.Count is changed from int? to int

- Linux Admin user name does not allow upper case letters

- ContainerService ListAll is changed to List. (to match with conventions)

- ContainerService List is changed to ListByResourceGroup (to match with conventions)

- ContainerService API version is updated from 2016-03-30 to 2016-09-30

- Compute API version is updated from 2016-03-30 to 2016-04-30-preview

- Because of many breaking changes, Compute SDK version is upgraded from 13.1.0-preview to 14.0.0-preview

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

Link to PR containing these Swagger spec changes:

Azure/azure-rest-api-specs#876

This SDK is generated from the following specs:

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/compute.json

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/disk.json

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-09-30/swagger/containerService.json

- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [x] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by markcowl** [comment]
@hyonholee please fill out the checklist or we cannot review this PR.  This includes adding the link to the corresponding azure-rest-api-specs PR.

**Comment by Pacort** [comment]
@markcowl checklist reviewed, please take a look at the PR. Thanks. @hyonholee

**Comment by hyonholee** [comment]
Sorry I only linked the spec, not the PR before.  Here is the link to PR: https://github.com/Azure/azure-rest-api-specs/pull/876
Thanks.

**Review by markcowl — COMMENTED** [review]
This PR requires 2 changes to generate.cmd:  (1) You should update generate.cmd to point to the snapshot of the spec used to geenrate this code (for example: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/99b77b4ff1ecbfb41cf33fc2b8e1d6e957312214/arm-compute/compositeComputeClient.json)

(2) You should update to a later version oF AutoRest, which will clean up the unnecessary  fully qualified type names used in much of this code.

Otherwise, this looks good.

**Comment by colemickens** [comment]
For container service, did you also need to fix the SSH key used, and specify a count for the agent pool... or do you have all tests passing?

**Comment by colemickens** [comment]
Also, there seem to be bugs in the Compute test code after I updated. Did you have to make changes for that as well?

**Comment by hyonholee** [comment]
@colemickens I pulled your update to this PR.  Thanks.

**Comment by Pacort** [comment]
@colemickens Thank you, do you think we could get it approved today? Thanks!

**Comment by huangpf** [comment]
It used to be "OverProvision". Why is it "Overprovision" now? @hyonholee

**Comment by hyonholee** [comment]
@huangpf  It was fixed in Oct.  There was an issue about the typo.  Overprovision is correct.

https://github.com/Azure/azure-rest-api-specs/commit/96137a5ea70eda917d7a7009514ea134df35ab39#diff-32c44936fe36d535f8c42dcb1ab29264

**Comment by Pacort** [comment]
@markcowl @colemickens please review and approve if correct. Thanks.

**Comment by Pacort** [comment]
@markcowl 
Ping...

**Comment by Pacort** [comment]
@colemickens Ping... please approve :)

**Comment by Pacort** [comment]
sorry re-opening, I closed it by mistake...

**Comment by colemickens** [comment]
I'm still concerned about this PR, I thought I'd commented here, but I guess I commented on mine:

1. The same set of Compute tests *still* seem to fail on my machine with the same pattern.

2. The git history now splits the SDK update across 4 different commits that flap back and forth between autorest 0.17 and two different nightlies of 1.0.0.

3. My PR was open longer and had a cleaner git history.

4. This disable key data verification which was unnecessary and increases the chance that a regression will slip by.

**Pull request merged**
