### PR TITLE
Azure OpenAI: remove SseReader's use of subtly blocking StreamReader.EndOfStream

### LINKED ISSUE #41838: [BUG] Azure.Core.Sse.SseReader ends up erroneously blocking
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.13

### Describe the bug

The IAsyncEnumerables produced by OpenAIClient rely on asynchronously consuming an SSE response stream from the OpenAI HTTP response. That parsing happens via Azure.Core.Sse.SseReader, which repeatedly calls TryReadLineAsync to parse the next line. However, the first thing that method does is call StreamReader.EndOfStream, **which does synchronous I/O** to fill the StreamReader's buffer if the buffer is empty. That means most if not all of the calls which are supposed to be doing async I/O end up doing synchronous I/O and blocking the caller who's expecting to be asynchronous.

### Expected behavior

Consuming an IAsyncEnumerable for streaming OpenAI responses is asynchronous.

### Actual behavior

After the very first read that initiates the request, most or all subsequent operations end up being synchronous rather than asynchronous, as the I/O performed ends up being synchronous rather than asynchronous.

### Reproduction Steps

```C#
using Azure.AI.OpenAI;

string apikey = "";

OpenAIClient client = new OpenAIClient(apikey);
var options = new ChatCompletionsOptions() { DeploymentName = "gpt-3.5-turbo-0125" };
options.Messages.Add(new ChatRequestUserMessage("Write a 10 stanza poem about dogs"));

var strings = (await client.GetChatCompletionsStreamingAsync(options)).EnumerateValues();
var e = strings.GetAsyncEnumerator();
while (true)
{
    ValueTask<bool> vt = e.MoveNextAsync();
    Console.Write($"{vt.IsCompleted}: ");
    if (!await vt)
    {
        break;
    }
    Console.WriteLine(e.Current.ContentUpdate);
}
```
After the first line is output, all subsequent IsCompleted's being printed out are true.

### Environment

_No response_

### PR DESCRIPTION
**Pull request by trrwilson**
## Problem

`StreamReader.EndOfStream` introduces a subtle but important bit of blocking I/O to the project's server-sent event reader that causes the underlying `IAsyncEnumerator` for streaming chat completions to invariantly report a completed state for its MoveNext. This causes issues in downstream consumption scenarios that block on this, e.g. via JsonSerializer:

```
await JsonSerializer.SerializeAsync(Console.OpenStandardOutput(), GetStrings(await client.GetChatCompletionsStreamingAsync(options)));

static async IAsyncEnumerable<string> GetStrings(IAsyncEnumerable<StreamingChatCompletionsUpdate> source)
{
    await foreach (var update in source)
    {
        //await Task.Yield();
        yield return update.ContentUpdate;
    }
}
```

## Fix

Rather than use `EndOfStream`, we replace the EoS check with an implicit one performed via a null return by ReadLine*. This produces the desired behavior without inducing the blocking I/O that erroneously makes streaming output appear blocking.

fixes #41838 and thanks/credit to @stephentoub for the investigation and fix confirmation.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
Thanks for the fix

**Comment by stephentoub** [comment]
> invariantly report a completed state for its MoveNext. This causes issues in downstream consumption scenarios that block on this, e.g. via JsonSerializer:

The more general impact is scalability: even though it looks like it's async, it's actually doing synchronous I/O, blocking the thread while waiting for data to arrive rather than allowing the thread to do other things in the meantime.

What you cite is also impactful to streaming latency and is how I first noticed an issue: returning one of these IAsyncEnumerables from an ASP.NET minimal API results in that blocking behavior negatively impacting how buffering happens in the implicit JSON serialization, causing the steamed tokens to be batched rather than written to the wire individually.

**Review by KrzysztofCwalina — APPROVED** [review]

**Comment by joakimriedel** [comment]
@trrwilson I'm trying to find a nightly build including this fix, but it seems [this feed](https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json) from the [documentation](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#nuget-package-dev-feed) only carries the beta.13 version without this fix. Could you help me point to where the nightly builds are published?

**Comment by trrwilson** [comment]
@joakimriedel the package feeds seemingly prioritize the beta/alpha tagging in semantic versioning over recency, which I've always found a bit odd.

If you check the full list of versions, you'll find the nightly/alpha/dev builds beneath the published beta builds:
https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Azure.AI.OpenAI/versions/1.0.0-beta.13

E.g. here's the latest:
https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Azure.AI.OpenAI/overview/1.0.0-alpha.20240214.1

**Comment by joakimriedel** [comment]
@trrwilson oh 🤦‍♂️ thanks a lot, that do make sense though with alpha < beta sort order.

**Pull request merged**
