### PR TITLE
Generate new sql client form swagger containing instance pools and usages changes.

### PR DESCRIPTION
**Pull request by johnpaulkee**
Generated new sql client which adds new instance pool and usages changes.
Tests have been recorded showing its end to end usage.

An instance pool is a “resource container” or a set pre-allocated virtual machines organized in an isolated private cluster.
Azure SQL managed instances will be able to be provisioned and deployed within an instance pool and consume it’s allocated capacity.

### CODE REVIEW

**Comment by erich-wang** [comment]
@johnpaulkee 
1. Please follow **step 8** in [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-directory-structure-and-sdk-generation). It will really help us a lot to review your PR if it contains sdk\_metadata\<rpName>.txt which is generated by generate.ps1

2. Please update **Version** and **PackageReleaseNotes** in your csproj file

**Comment by johnpaulkee** [comment]
Sure thing @erich-wang. Thanks for providing links to instructions.
I’ll go ahead and make those updates when possible.

**Comment by johnpaulkee** [comment]
Hi @erich-wang, I've gone ahead and updated the review based on your feedback.
Thank you.

**Review by erich-wang — APPROVED** [review]

**Comment by johnpaulkee** [comment]
Thanks @erich-wang !

**Pull request merged**
