### PR TITLE
Fix Unity NotImplementedException error

### LINKED ISSUE #22901: [BUG] The latest change for Azure.Core doesn't fix the bug in Unity
Hi, I test the new fix in Unity, I found that the [#22539](https://github.com/Azure/azure-sdk-for-net/pull/22539#issue-686142286) PR for Azure.Core didn't fix the bug, the code actually catch the wrong exception

Unity uses a very old version of Mono, so the access to some https functions throws NotImplementedException rather than NotSupportedException, in their code [Unity Https](https://github.com/Unity-Technologies/mono/blob/unity-2021.1-mbe/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs#L448).

**Environment:**
-Azure.Data.tables 12.1.0, Unity 2020.3.6f LTS
-.NET SDKs 5.0.301 and Windows 10 10.0.19041
-IDE and version : [e.g. Visual Studio Version 16.10.2

I just created a new PR to fix the issue, tested in Unity.

### PR DESCRIPTION
**Pull request by daiyk**
fix [#22901](https://github.com/Azure/azure-sdk-for-net/issues/22901#issue-954099707)

### CODE REVIEW

**Comment by pakrym** [comment]
Thank you for the verification. Let's keep both branches in the `catch()`

**Comment by daiyk** [comment]
> Thank you for the verification. Let's keep both exception types in the `catch()` just in case.

Updated with catch NotSupportedException

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
@daiyk, you might need to sign the CLA (https://cla.opensource.microsoft.com/)

**Comment by daiyk** [comment]
> @daiyk, you might need to sign the CLA (https://cla.opensource.microsoft.com/)

Hi, I have authorized Microsoft CLA to access my account on that page, seems doesn't work?

**Comment by pakrym** [comment]
Thank you, @daiyk !

**Pull request merged**
