### PR TITLE
{Azure Functions} Nuget package for Azure Functions used in Isolated Process should be mentioned. 

### LINKED ISSUE #37957: Should indicate that it cannot be used in Isolated Process
This document should perhaps say at the top that the package is not compatible with Azure Functions used in Isolated Process mode; this can only be used with an in-process Azure Functions app.

That might hopefully save people a little time, rather than them trying to use it in Azure Functions being written in, or in my case migrated to, Isolated Process mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4483c61-5340-02ca-4668-9cb8a843cfb5
* Version Independent ID: c60433c0-0752-46b2-08d6-82f67561ccd6
* Content: [Azure WebJobs Storage Blobs client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.storage.blobs-readme?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/microsoft.azure.webjobs.extensions.storage.blobs-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/microsoft.azure.webjobs.extensions.storage.blobs-readme.md)
* Service: **storage**
* GitHub Login: @seanmcc-msft
* Microsoft Alias: **seanmcc**

### PR DESCRIPTION
**Pull request by navba-MSFT**
Docs: https://learn.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.storage.blobs-readme?view=azure-dotnet
This document should perhaps say at the top that the package is not compatible with Azure Functions used in Isolated Process mode; this can only be used with an in-process Azure Functions app. This will avoid confusion mong our customers.
As the isolated functions use : [Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs NuGet package](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs), version 5.x.

fixes https://github.com/Azure/azure-sdk-for-net/issues/37957

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by navba-MSFT** [comment]
@seanmcc-msft @amnguye Could you please review this PR once you get a chance ? Thanks in advance.

**Review by amnguye — COMMENTED** [review]
I'm not entirely sure this is something we want in our README. I think the point of the README is to give an introduction to the library.. and not a "but if this is your scenario, you want to go here or go there". I think that should be rather put in the getting started guide. Or the introduction to the feature of the azure functions worker, like if this is your scenario, use this, and if it's this  use that.

I understand the customer's frustration of "if only this was said exactly here then I wouldn't have gone down the rabbit hole here" however at some point we need to draw the line. It's going to increase to us including all kinds of products to use in our read me.

**Comment by amnguye** [comment]
I'm comfortable updating the first line to something like "This extension provides functionality for accessing Azure Storage Blobs in Azure Functions within the process."

I think this would ease the customer's ask here while not becoming a one stop shop of a guide map to other Azure Products.

**Comment by navba-MSFT** [comment]
> I'm comfortable updating the first line to something like "This extension provides functionality for accessing Azure Storage Blobs in Azure Functions within the process."
> 
> I think this would ease the customer's ask here while not becoming a one stop shop of a guide map to other Azure Products.

@amnguye Your suggestions have been incorporated. Could you please review and marge this once you get a chance ?

**Review by amnguye — APPROVED** [review]

**Pull request merged**
