### PR TITLE
Add permalink validation for code generation inputs

### PR DESCRIPTION
**Pull request by pakrym**

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]
This seems pretty strick but I'm OK with starting here and seeing if we run into any issues.

**Comment by pakrym** [comment]
FYI @allenjzhang 

Because we are running generated code up-to-date checks on every build we can't be pointing to a changing Swagger reference or the builds would start breaking when something changes in azure-rest-api-spec repo.

**Comment by allenjzhang** [comment]
Add @erich-wang 

Since we don’t auto refresh SDKs, what’s the purpose of up-to-date daily check? The swagger in rest api repo is supposed to in complete state at any given time and not work in progress. So reference the current one should just be fine as fast as I can think of the scenarios right now. We have not had this in track 1 nor other languages as far as I know.

**Comment by pakrym** [comment]
The purpose of code check is to make sure the developer ran the generator and didn't forget to check in the output or didn't change it manually. We don't run it daily we run it as part of PRs.

The purpose of permalink is to be able to checkout any old commit run the generator and get the same exact output without suddenly getting all the new features from updated swaggers.

This was possible to do manually in Track 1 by looking at SdkInfo.cs file and handcrafting the autorest command line but we'd like the generation to always be reproducible for track 2 libraries.

**Comment by pakrym** [comment]
See https://github.com/Azure/azure-rest-api-specs/issues/8955 for a bit more context.

**Pull request merged**
