### PR TITLE
Microsoft.Capacity .Net SDK release

### PR DESCRIPTION
**Pull request by rahuls-microsoft**
Microsoft.Capacity .Net SDK release

### CODE REVIEW

**Comment by rahuls-microsoft** [comment]
Can we get it approved, so that we can provide the updated SDK to users.

**Comment by bquantump** [comment]
@rahuls-microsoft Can you please link the swagger PR this is based of off?

**Comment by rahuls-microsoft** [comment]
> @rahuls-microsoft Can you please link the swagger PR this is based of off?
Swagger PR 
https://github.com/Azure/azure-rest-api-specs/pull/9720

**Comment by bquantump** [comment]
@weshaggard I can't seem to get the check enforcer going again here. It looks like it was working until the recent merge commit.

**Pull request closed without merging**
