### PR TITLE
Add reboot parameters for multiple replicas per master.

### PR DESCRIPTION
**Pull request by Priya91**
Updating sdk as per the swagger spec documentation for reboot feature on multiple replicas per master.

### CODE REVIEW

**Comment by Priya91** [comment]
cc @MECHANDR

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @Priya91 ,  could you
- Add a link to the openapi spec review PR here
- Update release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release

Thanks

**Comment by Priya91** [comment]
OpenAPI spec review PR: https://github.com/Azure/azure-rest-api-specs/pull/9426

**Comment by Priya91** [comment]
@isra-fel We are still in preview version, so I just updated the version in csproj, but the assembly version is still simply 6.0.0.0.. Let me know if there needs to be a change here..

**Review by MECHANDR — APPROVED** [review]

**Comment by isra-fel** [comment]
> @isra-fel We are still in preview version, so I just updated the version in csproj, but the assembly version is still simply 6.0.0.0.. Let me know if there needs to be a change here..

You are right. No problem

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
