### PR TITLE
Removing SP certificate from Datalake test recordings

### PR DESCRIPTION
**Pull request by vahemesw**
## Description

The HDinsight test recordings contain sensitive certificate contents and passwords that needs to be stripped off.
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by ro-joowan** [comment]
Hi Varada (@vahemesw),

I'm not familiar with the inner workings of HDInsight, but did you make sure that the tests were passing via Playback mode without the certificate/passwords that you just removed?

**Comment by vahemesw** [comment]
Hi ro-joowan,

I did a test run of all the HDInsight tests in playback mode after removing the cert contents,password and it was successful.

**Comment by ro-joowan** [comment]
Sounds good to me then!  

As a side note, I'm not sure if you checked off some of the boxes under the Guidelines (or the checklist), but if not, please keep in mind to check off the boxes appropriately in the future.

**Comment by vahemesw** [comment]
Sure ro-joowan. Thanks for pointing it out.

**Review by ro-joowan — APPROVED** [review]

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@azuresdkci add to whitelist

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
