### PR TITLE
Fix test infrastructure to allow running in arbitrary clouds

### PR DESCRIPTION
**Pull request by JoshLove-msft**

### CODE REVIEW

**Review by jsquire — APPROVED** [review]
This would also need a value for the China cloud.   I wonder if we should make this an environment variable that the test resource creation spits out?

**Comment by JoshLove-msft** [comment]
> This would also need a value for the China cloud. I wonder if we should make this an environment variable that the test resource creation spits out?

Yep, was about to add China and Germany. It could be an env var but that would require conditional statements in the ARM template which isn't too fun. But as I think about this more, we can probably just restrict the functionality of `CreateWithQueue` to only allow specifying primary or secondary namespace. That would remove the need to form the fully qualified namespace ourselves and we could rely entirely on the env vars.

**Pull request merged**
