### PR TITLE
CDN Net SDK

### PR DESCRIPTION
**Pull request by injyzarif**
This SDK includes:
- All generated code by AutoRest using cdn.json swagger.
- Generate.cmd script.
- Tests to cover all CDN entities and operations.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@injyzarif__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (inzarif). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@azuresdkci - Add to white list

**Comment by amarzavery** [comment]
@azuresdkci - Test this please!

**Comment by amarzavery** [comment]
@azuresdkci Test this please

**Comment by amarzavery** [comment]
@azuresdkci - Add to whitelist.

**Pull request merged**
