### PR TITLE
[SQL] Add a new API for Azure Active Directory only authentication for SQL DB. remove old disable AzureADOnlyAuthentication API

### PR DESCRIPTION
**Pull request by amolagar5**
Since we are adding a new API for AD Only auth workflow, disable api is no longer needed. 
Also making parameter read only  in AAD Admin API.

Link to open api PR
https://github.com/Azure/azure-rest-api-specs/pull/9710

### CODE REVIEW

**Comment by isra-fel** [comment]
@allenjzhang  could you review this one ? Thanks

**Comment by amolagar5** [comment]
@allenjzhang , please take a look at the PR when possible.

**Comment by amolagar5** [comment]
@allenjzhang , we are aware of the breaking change in this . Discussed this with ARM team in swagger review already.

**Comment by allenjzhang** [comment]
There are outstanding concurrent [SQL SDK PR](https://github.com/Azure/azure-sdk-for-net/pull/13935). Please coordinate release and version numbers. 

Could you also:

 - Add a link to the openapi spec review PR here

 - Check in the metadata TXT file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)

Thanks

**Comment by amolagar5** [comment]
@allenjzhang , please go ahead and merge the other PR, once that is merged, I will sync to master and regenerate the files for my PR.  I believe that will be cleaner with no pre-merging needed. That is what would have happened any way if we were to these PRs separately. Right. let me know if my assumptions are wrong.

**Comment by amolagar5** [comment]
@allenjzhang , reverted the assembly version to 1.45 as per our offline discussion. please take a look when possible.

**Review by allenjzhang — APPROVED** [review]

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
