### PR TITLE
version bump for SQL management nuget

### PR DESCRIPTION
**Pull request by hchungmsft**
Bump version of Nuget package containing classes for LTR.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hchungmsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@hchungmsft This is just a version change, were the actual changes pushed earlier?

**Comment by hchungmsft** [comment]
Yes, https://github.com/Azure/azure-sdk-for-net/pull/2034

**Comment by markcowl** [comment]
@azuresdkci ass to whitelist

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Pull request merged**
