### PR TITLE
Revert ManagedIdentityTokenProvider change

### PR DESCRIPTION
**Pull request by serkantkaraca**
This reverts commit 94a6962738a4a7e47a78af350f053763d4f22928.

### CODE REVIEW

**Review by nemakam — CHANGES_REQUESTED** [review]
Instead of reverting this, if the change looks good, can we fix the test that's failing. Its an API test..

**Comment by serkantkaraca** [comment]
@nemakam, makes sense. Can you own the fix?

**Comment by nemakam** [comment]
Yeah will do it..

**Comment by nemakam** [comment]
Closing in favor of #10174

**Pull request closed without merging**
