### PR TITLE
Fixed memory leak (event handler leak) in RetryDelegatingHandler

### PR DESCRIPTION
**Pull request by MarkusGeigerDev**
Changed RetryPolicy.Retrying to regular delegate, added code to assign it only once in RetryDelegatingHandler

(see https://github.com/Azure/azure-sdk-for-net/issues/2593)

## Description

In RetryDelegatingHandler an event handler is registered on every round-trip but never de-registered. This lead to a memory leak. This pull request attempts to fix this issue by changing the RetryPolicy.Retrying event from a event to a simple delegate.
For a full discussion, see: https://github.com/Azure/azure-sdk-for-net/issues/2593

Reproduction test: I have tried to show the issue in a unit test, but because I haven't found a way to get the internal invocationList field of the multicast delegate via reflection, there is no way (at least none that I am aware of) of showing the event handler leak in a test.

Unit tests: There are three tests failing, (DateSerializationWithMaxValue,  DateSerializationWithNulls, DateSerializationWithoutNulls) but those are failing with or without my changes.

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by MarkusGeigerITD** [comment]
In the checks list, die "default" check is in "Waiting for status to be reported" state for 3 days now.
Am I missing something here? Have I failed to trigger something or provide a certain information?

**Comment by shahabhijeet** [comment]
@azuresdkci  add to whitelist

**Comment by Porges** [comment]
Also; this should really be expedited, it's a pretty leaky leak and affects all the SDKs:

image

**Comment by shahabhijeet** [comment]
@azuresdkci retest this please

**Comment by shahabhijeet** [comment]
@MarkusGeigerITD sorry for the delay. But this change cannot be absorbed until end of March.
I need to start adding tests around here, but regardless of that, we cannot merge this until march as we are cutting a build that is going out and we cannot bundle this change as this is a risky change and needs more testing around it.
Will appreciate your patience until then.

**Comment by MarkusGeigerITD** [comment]
@shahabhijeet I absolutely understand!
Will there be a quick bug-fix release after the upcoming vNext and after the tests are in place?
Until now, we can live with our private build for our service-to-service communication, but we are about to distribute an SDK for our product with a ClientRuntime-based client in it and there I would very much prefer a nuget dependency to a non-leaky official version :)

**Comment by swannman** [comment]
@shahabhijeet is there a timeframe for merging this fix?

**Comment by dsgouda** [comment]
@azuresdkci Retest this please

**Comment by VanHelSeenG** [comment]
@MarkusGeigerITD is there any movements to merge the pull request?

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
