### PR TITLE
Add time zone related changes + files which were reverted in a mean time

### PR DESCRIPTION
**Pull request by NMijat1024**
This is the swagger PR where changes are introduced: https://github.com/Azure/azure-rest-api-specs/pull/5224

@stefanb995, @lixiachena and @bashahee please check if your changes can be merged in as is?
These got reverted here https://github.com/Azure/azure-sdk-for-net/pull/5419 .
@dsgouda You approved the changes, is there a reason why their changes got reverted?

### CODE REVIEW

**Comment by dsgouda** [comment]
@NMijat1024 The auto generated PR [here](https://github.com/Azure/azure-sdk-for-net/pull/5419) for REST spec PR [here](https://github.com/Azure/azure-rest-api-specs/pull/5070) could have introduced those changes. The auto generation module simply generates the SDK for default tag.

**Comment by dsgouda** [comment]
@NMijat1024 there is another autogenerated PR here https://github.com/Azure/azure-sdk-for-net/pull/5642
for the REST spec PR here
https://github.com/Azure/azure-rest-api-specs/pull/5517

**Comment by bashahee** [comment]
@NMijat1024 My changes can be merged, thanks!

**Comment by NMijat1024** [comment]
I'll close this PR, as changes are merged in https://github.com/Azure/azure-sdk-for-net/pull/5666. Tnx @jaredmoo

**Pull request closed without merging**
