### PR TITLE
Regenerate SDK for EventGrid 2020-04-01-preview and add more test cases

### PR DESCRIPTION
**Pull request by ahamad-MS**
Regenerate SDK for EventGrid 2020-04-01-preview and add more test cases for the new resources.

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/8600

### CODE REVIEW

**Comment by ahamad-MS** [comment]
@isra-fel / @erich-wang  Can you please help review/merge this change ASAP. We need to catch some deadlines urgently. thanks

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @ahamad-MS , please
- Put a link of the swagger review PR in the description
- Update `AssemblyFileVersion` in `AssemblyInfo.cs`
- Remove this file `sdk/eventgrid/Microsoft.Azure.Management.EventGrid/src/Generated/code-model-v1`
    - There are some limitations regarding the latest autorest such as it produces this code-model-v1 file. We recommend updating the `-AutoRestVersion` in your `generate.ps1` from `latest` to `2.0.4413`.

**Comment by ahamad-MS** [comment]
Hello @isra-fel  All comments were addressed. thanks.

**Review by isra-fel — APPROVED** [review]
LGTM!

**Pull request merged**
