### PR TITLE
Shorten diagnostics event names

### PR DESCRIPTION
**Pull request by serkantkaraca**
Shortening diagnostic event names as recommended.

"DO - keep the names reasonably short (< 16 characters). Keep in mind that event names are already qualified by the Listener so the name only needs to be unique within a listener. Short names make IsEnabled() faster."

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md#event-names

### CODE REVIEW

**Review by jsquire — APPROVED** [review]
LGTM

**Comment by pakrym** [comment]
The line you've quoted is about diagnostic source event names, not activity names. Unfortunately, Activity user guide also shows a short name like `"Http_in"` but it doesn't seem to be consistent with what corefx itself is doing e.g. https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandlerLoggingStrings.cs#L17

cc @lmolkova should we update the guildelines with more up-to-date naming rules for activities?

Also filed https://github.com/Azure/azure-sdk/issues/554 to add this topic to .net guidelines.

**Comment by lmolkova** [comment]
1. this is technically a breaking change - existing listeners won't receive any events if they expect an exact match with the old name. I'm ok with it if we are breaking things this time anyway. 

2.  updating guidance. I've thought it's a good idea to keep activity names small until https://github.com/grpc/grpc-dotnet/pull/348#discussion_r296426969
Someone can use Activity without DiagnosticSource or write one listener for all sources (yes, this is hard and not efficient, but possible). 

So while I think a fully qualified name is overkill in the majority of cases, I'm not sure short name is good guidance either. I hope with the Activity vs OpenTelemetry we'll come up with better guidelines including this part.

**Comment by mikhail-anfimau** [comment]
@lmolkova you are right, this is a breaking change.

The change broke ApplicationInsights DependencyCollector [https://github.com/microsoft/ApplicationInsights-dotnet-server/blob/2.11.2/Src/DependencyCollector/Shared/Implementation/EventHandlers/EventHubsDiagnosticsEventHandler.cs](url)

EventHubsDiagnosticsEventHandler still depends on fully qualified event names emitted by EventHubclient. Hence, the version 4.1 is not usable, when dependency telemetry tracking is essential.

`
        public override void OnEvent(KeyValuePair<string, object> evnt, DiagnosticListener ignored)
        {
            Activity currentActivity = Activity.Current;

            switch (evnt.Key)
            {
                case "Microsoft.Azure.EventHubs.Send.Start":
                case "Microsoft.Azure.EventHubs.Receive.Start":
                    break;
                case "Microsoft.Azure.EventHubs.Send.Stop":
                case "Microsoft.Azure.EventHubs.Receive.Stop":
                    this.OnDependency(evnt.Key, evnt.Value, currentActivity);
                    break;
            }
        }
`

**Comment by mikhail-anfimau** [comment]
I opened an issue in microsoft/ApplicationInsights-dotnet repository 
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1317

**Pull request merged**
