### PR TITLE
[COMMUNICATION] - [LIVE TESTS] - adding missing env var

### PR DESCRIPTION
**Pull request by JoshuaLai**
Live tests are failing because of a new environment variable that was introduced. 
Introducing it into the test resources to fix tests

### CODE REVIEW

**Comment by JoshuaLai** [comment]
\azp pipeline net - communication - tests

**Comment by minnieliu** [comment]
/azp pipeline net - communication - tests

**Review by minnieliu — APPROVED** [review]

**Review by sacheu — APPROVED** [review]
Thanks for the quick fix.

**Pull request merged**
