### PR TITLE
Enable Policy Assignment user-assigned identity support

### PR DESCRIPTION
**Pull request by calecarter**
# All SDK Contribution checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] **Please open PR in `Draft` mode if it is:**
	- Work in progress or not intended to be merged.
	- Encountering multiple pipeline failures and working on fixes.
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md).**

### [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code. (Track 2 only)
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK. Please double check nuget.org current release version.

## Additional management plane SDK specific contribution checklist: 
Note: Only applies to `Microsoft.Azure.Management.[RP]` or `Azure.ResourceManager.[RP]`
 
- [x] Include updated [management metadata](https://github.com/Azure/azure-sdk-for-net/tree/main/eng/mgmt/mgmtmetadata).
- [x] Update AzureRP.props to add/remove version info to maintain up to date API versions.

### Management plane SDK Troubleshooting
- If this is very first SDK for a services and you are adding new service folders directly under /SDK, please add `new service` label and/or contact assigned reviewer.
- If the check fails at the `Verify Code Generation` step, please ensure:
	- Do not modify any code in generated folders.
	- Do not selectively include/remove generated files in the PR.
	- Do use `generate.ps1/cmd` to generate this PR instead of calling `autorest` directly.
	Please pay attention to the @microsoft.csharp version output after running `generate.ps1`. If it is lower than current released version (2.3.82), please run it again as it should pull down the latest version.
	
	**Note: We have recently updated the PSH module called by `generate.ps1` to emit additional data. This would help reduce/eliminate the Code Verification check error. Please run following command**:

	    `dotnet msbuild eng/mgmt.proj /t:Util /p:UtilityName=InstallPsModules`

### Old outstanding PR cleanup
 Please note:
	If PRs (including draft) has been out for more than 60 days and there are no responses from our query or followups, they will be closed to maintain a concise list for our reviewers.

### CODE REVIEW

**Review by pilor — APPROVED** [review]

**Comment by calecarter** [comment]
@m-nash anything I need to do to get this in?  The two automation failures are for a missing file for ARC (eng/mgmt/mgmtmetadata/azurearcdata_resource-manager.txt).  I didn't touch anything to do with ARC so not sure what is up with that.

**Review by archerzz — APPROVED** [review]

**Comment by calecarter** [comment]
Thx @archerzz for approval.  Anything else I need to do to get this merged?

**Review by fengzhou-msft — APPROVED** [review]

**Comment by archerzz** [comment]
@calecarter There is a mistake in https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurearcdata/resource-manager/readme.csharp.md
`output-folder: $(csharp-sdks-folder)/resources/Microsoft.Azure.Management.AzureArcData/src/Generated`

You're generating codes to https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resources which belongs to `Resources` SDK. You need to point to the folder which belong to `ArcData`.

**Comment by calecarter** [comment]
> @calecarter There is a mistake in https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurearcdata/resource-manager/readme.csharp.md
> `output-folder: $(csharp-sdks-folder)/resources/Microsoft.Azure.Management.AzureArcData/src/Generated`
> 
> You're generating codes to https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resources which belongs to `Resources` SDK. You need to point to the folder which belong to `ArcData`.

Sorry @archerzz but I don't understand.  I am not updating anything to do with ARC and didn't touch that file.  I am updating the resources SDK, and I believe it is pointing to the proper spot.  If there is an error it would be with the last person to touch it, no?

**Review by yungezz — APPROVED** [review]

**Pull request merged**
