### PR TITLE
Anh/2023 version

### PR DESCRIPTION
**Pull request by marstr**
### Changelist:

- Uses RP API Version 2023-10-01-preview
- Adds support for Private Link
- Adds support for FCM V1 platform
- Adds support for Browser platform
- Adds support for Xiaomi platform

This PR replaces #42555 because the original author has left the company.

### CODE REVIEW

**Review by jsquire — CHANGES_REQUESTED** [review]
@marstr :

Your account lacks the public organization memberships and write permissions required of a Microsoft contributor.  Please review the Azure SDK onboarding documentation and use the associated Teams channel for support.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

**Comment by marstr** [comment]
@jsquire, I've made my organization membership public, so I believe I should be allowed write permissions.

I will not be a good long-term owner for this library, so I will refrain from adding myself to the CODEOWNERS file for now. We're working on establishing who would be a better fit, but we're probably still several months away from having a good owner.

**Comment by marstr** [comment]
Got it - I'll take another, closer look.

**Comment by marstr** [comment]
I too have taken a new role at the company, and will no longer be around to complete this PR. Sorry for all of the noise.

**Pull request closed without merging**
