### PR TITLE
Regenerated EventGrid dataplane SDK to include new event types

### PR DESCRIPTION
**Pull request by kalyanaj**
## Description
Regenerated EventGrid DataPlane SDK to include new event types.

Links to the corresponding swagger spec pull request that has been merged in the azure-rest-api-specs repository:

https://github.com/Azure/azure-rest-api-specs/pull/3061
https://github.com/Azure/azure-rest-api-specs/pull/3097
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [X] Please add REST spec PR link to the SDK PR
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [X] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [X] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please create a generate.ps1 similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Language/Language/Language/generate.ps1) and regenerate the code
Looks good otherwise

**Comment by kalyanaj** [comment]
Thanks @dsgouda for the review!  The generate script I used for this is at https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/EventGrid/DataPlane/generate.cmd. Please let me know if that's sufficient / covers what you were looking for.  Thanks!

**Comment by dsgouda** [comment]
@kalyanaj yes, I understand you used the .cmd but we are moving RPs towards using a ps1 script similar to one I linked to generate the code, would appreciate if you could do the same.

**Comment by kalyanaj** [comment]
@dsgouda, thanks for the info. Can I take this up for the next SDK refresh (unless there's a big difference in the generated code)?

**Comment by dsgouda** [comment]
Sure, that works, please consider doing this in the next iteration.

**Review by dsgouda — APPROVED** [review]

**Pull request merged**
