### PR TITLE
Added GeoBackupPolicy SDK to SQL Azure Database Geo Backup model

### PR DESCRIPTION
**Pull request by alazad-msft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alazad-msft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@alazad-msft__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@alazad-msft please pull from upstream master branch and resolve merge conflicts.

**Comment by alazad-msft** [comment]
Completed the merge and conflict resolution.

**Pull request merged**
