### PR TITLE
Auto rest composite client

### PR DESCRIPTION
**Pull request by pankajsn**
Integration account updates in the Logic App

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pankajsn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pankajsn). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@pankajsn looks like you have targeted the wrong branch.  I think you wanted to target the AutoRest branch

**Comment by pankajsn** [comment]
I targeted the AutoRest branch earlier but I got confused with the documentation.
https://github.com/Azure/adx-documentation-pr/blob/master/engineering/autorest-to-powershell.md#standard-process
#10.ii

I will send the new pull request.

Regards,
~Pankaj

**Comment by pankajsn** [comment]
Removing this pull request & creating a new one targeting AutoRest branch.

**Pull request closed without merging**
