### PR TITLE
Update Key Vault NuGet package config to new version of nuget package…

### PR DESCRIPTION
**Pull request by pomortaz**
… manager schema

### CODE REVIEW

**Comment by markcowl** [comment]
@pomortaz Why is this needed?  This seems to add another place we need to change for moving to the v3 api, or adding a different source.  Is this actually required to build the package?

**Comment by pomortaz** [comment]
The new version of NuGet package manager needs <configuration> tag for the visual studio project to be able to download the packages. This change is to fix the issue for the sample code to be build for visual studio 2015 nuget package manager and fix the same issue for for the SDK. In the new version of API we would not need this for the SDK.

**Comment by markcowl** [comment]
I understand why this is here for the sample, not sure I understand why it is here for the sdk itself, as all sdks use the same nuget config.

**Comment by pomortaz** [comment]
This is actually broken for all the SDKs that are not using 'configuration' tag in their NuGet.config e.g. for [gallery](https://github.com/Azure/azure-sdk-for-net/blob/master/src/Gallery/NuGet.Config). You can try it yourself by upgrading the NuGet package manager in Visual Studio 2015 and then try to open the project in VS2015.

**Comment by pomortaz** [comment]
@markcowl ping.. :)

**Comment by markcowl** [comment]
This is out of date and should be unnecessary.  Closing for now.  Please reopen if this issue still persists.

**Pull request closed without merging**
