### PR TITLE
[Azure Search] Add several indexer features to SDK

### PR DESCRIPTION
**Pull request by chaosrealm**
## Description

Add several missing indexer features to get to parity with REST API:
- Warnings
- Parameters to Base64Encode and Base64Decode functions
- Text parsing mode
- Removed some obsolete features 
---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by bitsforthought — APPROVED** [review]

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please link the related rest spec repo PR
Please create a `generate.ps1` file similar to [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/generate.ps1) and regenerate the code here
Looks good other than that

**Comment by chaosrealm** [comment]
Link to the specs PR: https://github.com/Azure/azure-rest-api-specs/pull/2759 
The code was regenerated already.

**Comment by brjohnstmsft** [comment]
@dsgouda Please note that the target of this PR is a branch owned by the Azure Search team for which we have merge permissions. This is for our preview SDK. Customers are waiting for a hotfix in this branch, which I'd like to publish to NuGet today. I'll make the changes to the generate scripts when we merge these latest changes back to the `psSdkJson6` branch.

**Review by dsgouda — APPROVED** [review]

**Comment by dsgouda** [comment]
@brjohnstmsft acknowledged, approving at my end.

**Comment by dsgouda** [comment]
@brjohnstmsft acknowledged, approving at my end.

**Pull request merged**
