### PR TITLE
[ACR] Split Data Plane and Management Plane Pipeline

### PR DESCRIPTION
**Pull request by ShivangiReja**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by ArthurMa1978 — APPROVED** [review]

**Review by annelo-msft — APPROVED** [review]

**Review by jsquire — APPROVED** [review]

**Comment by pallavit** [comment]
I am curious which other SDKs need this change? Based on the thread with Wes --> can we assume a grep for SDKType: client in ci.mgmt.yml is the right way to go about it?

**Comment by jsquire** [comment]
Event Hubs and Service Bus split out the management libraries a while back in order to reduce consistent test failures unrelated to the client libraries.

**Comment by weshaggard** [comment]
> I am curious which other SDKs need this change? Based on the thread with Wes --> can we assume a grep for SDKType: client in ci.mgmt.yml is the right way to go about it?

That might find some but I suspect not many. Ultimately if we want to take this fully to the extreme we would need to make sure every service directory that has both a ci.yml and ci.mgmt.yml also has a service.project and the correct SDKType's set.

**Comment by pallavit** [comment]
Thank you. I have created the following issue - https://github.com/Azure/azure-sdk-for-net/issues/31323 to track. We do not have to proactively fix all - however any instances where this poorly reflects on pipeline health for our team owned SDKs should be a priority.

**Pull request merged**
