### PR TITLE
Use LinkBase for shared source

### PR DESCRIPTION
**Pull request by pakrym**

### CODE REVIEW

**Review by JoshLove-msft — APPROVED** [review]

**Review by maririos — APPROVED** [review]

**Comment by weshaggard** [comment]
Is there docs on this? Or how did you discover it?

**Comment by pakrym** [comment]
https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#linkbase

**Review by christothes — APPROVED** [review]

**Comment by pakrym** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/24058 fixes the attestation build error.

**Pull request merged**
