### PR TITLE
[Synapse] Add test case for track 2 mgmt sdk - phase 1

### PR DESCRIPTION
**Pull request by wonner**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by wonner** [comment]
cc: @yanjungao718

**Review by archerzz — APPROVED** [review]

**Comment by JoshLove-msft** [comment]
This seems to have broken the Core CI - https://dev.azure.com/azure-sdk/public/_build/results?buildId=2158531&view=ms.vss-test-web.build-test-results-tab&runId=39162609&resultId=100153&paneView=debug. Can we investigate how this was able to merge successfully?

**Comment by JoshLove-msft** [comment]
It looks like no tests were run for synapse -mgmt. @m-nash @weshaggard do you know why the tests wouldn't be run?

**Comment by m-nash** [comment]
@JoshLove-msft they are ran as part of the sparse matrix in resorucemanager similar to how core runs all, resourcemanager runs all mgmt plane, but we don't want them to be duplicated.

**Pull request merged**
