### PR TITLE
[Blueprint] SDK update due to API schema change

### PR DESCRIPTION
**Pull request by filizt**
Blueprint service API schema changed with updated parameter value model and addition of managedResource property. Updating SDK along with tests and adding new recorded tests

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @filizt , Could you
- Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release

Thanks

**Comment by filizt** [comment]
> Hi @filizt , Could you
> 
> * Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
> * Update release notes in csproj
> * Update versions in csproj and `assemblyinfo.cs` if you are going to release
> 
> Thanks

Updated the PR with above asks. The SDK changes are breaking changes, let me know if there is anything extra I need to do due to having breaking changes.

**Review by isra-fel — APPROVED** [review]

**Comment by isra-fel** [comment]
The module is in preview, so it should be fine.

**Comment by filizt** [comment]
@isra-fel is there anything I can do for the CI failures?

**Comment by isra-fel** [comment]
`net - mgmt - ci` passed. Merging this PR

**Pull request merged**
