### PR TITLE
Corrected path to Hyak.Common.dll

### PR DESCRIPTION
**Pull request by Sam7**
The reference to the Hyak.Common.dll was wrong and therefor this exception is thrown:

Method 'CreateHttpTransportHandler' in type 'Microsoft.Azure.Common.Platform.HttpTransportHandlerProvider' from assembly 'Microsoft.Azure.Common.NetFramework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

   at Hyak.Common.ServiceClient`1..ctor()
   at Microsoft.Azure.Management.Resources.ResourceManagementClient..ctor()
   at Microsoft.Azure.Management.Resources.ResourceManagementClient..ctor(SubscriptionCloudCredentials credentials)
   at Monkii.Bmw.Engage.AzureManager.AzureManagementContext..ctor(AuthenticationConfig config, INamingConventionProvider namingConventionProvider) in c:\code\bmw-engage\src\AzureManager\AzureManagementContext.cs:line 71

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Sam7__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@Sam7__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@Sam7 we've made some large infrastructure changes - can you please update the PR to fix merge conflicts?

**Comment by Sam7** [comment]
I updated my changes.
However I'm really only concerned with the Common nuget package.
I noticed the wrong reference is used throughout most projects. (once I haven't fixed)
where
packages\Hyak.Common.1.0.2\lib\portable-net403+win+wpa81\Hyak.Common.dll
is being used instead of
packages\Hyak.Common.1.0.2\lib\net45\Hyak.Common.dll

Might be worth looking into.

Cheers.

**Comment by ogail** [comment]
@yugangw-msft please follow up with this change as it does not look covering all scenarios.

**Comment by yugangw-msft** [comment]
Most projects build for portable, net40, and net45 using the same project file, so we can't hard code to point to "net45"; hence this PR will regress and we can't take it.
Using "packages\Hyak.Common.1.0.2\lib\portable-net403+win+wpa81" is not correct as well, rather less evil, because it at least points to a portable version which could work for net4.0.3+, which includes the net45. Regardless it is a bug, and we are actively addressing this. 
@Sam7 , could you please send me a slimmed down version of project which reproduce this issue. So far the stack trace shows it is a pretty simple client code and it should just work. I can be reached to yugangw at microsoft dot com

**Comment by yugangw-msft** [comment]
closing for the reasons i mentioned earlier

**Pull request closed without merging**
