### PR TITLE
AutoPr-Compute-hyonholee-REST Spec PrNumber 5692

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by hyonholee** [comment]
I think the test failed, because we updated API version.   I will update the tests.  Can you merge this PR with disabling failed tests?

**Comment by shahabhijeet** [comment]
@azuresdkci retest this please

**Comment by hyonholee** [comment]
Hi, could you merge this PR?  I will update tests after this is merged.  Spec is merged, BTW.  Thanks.

**Comment by hyonholee** [comment]
@shahabhijeet Can you merge this PR?

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
