### PR TITLE
Enable unified pipelines for service bus.

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR enables service bus for unified pipelines.

### CODE REVIEW

**Comment by nemakam** [comment]
@mitchdenny , I'm not familiar with "unified pipeline" concept. Could you explain what does this PR do and how will it affect us?

Also, I noticed you updated the version to `-preview`. I need to release `4.1.1` soon (probably today. Couldn't finish the pipeline run on friday). Should I just go ahead and revert this change, publish nuget, and reapply this?

**Comment by jsquire** [comment]
I hadn't seen this when it went through.   I don't think the version change is applicable to Service Bus, as it is a track one artifact and ownership lies with the Service Bus team.

**Comment by weshaggard** [comment]
You can find instructions on the unified pipelines and how to use them at https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/8/Releasing-Packages?anchor=.net-to-nuget.org.

As for the version yes go ahead and revert back to 4.1.1 and do your release. 

>I don't think the version change is applicable to Service Bus, as it is a track one artifact and ownership lies with the Service Bus team.

Even for track 1 libraries they should use the versioning guidance at https://github.com/Azure/azure-sdk-for-net/blob/master/Documentation/Versioning.md. It is best to try and keep things as consistent as possible.

**Pull request merged**
