### PR TITLE
[Translation] Change folder name to translation

### PR DESCRIPTION
**Pull request by maririos**
Following namespace name, changing folder to `translation`. This was agreed with Python as well for the release of `1.0.0-beta.1`.

*Note* that the namespace and client name might change for the next release and that will likely cause a rename in this folder too.

### CODE REVIEW

**Review by kristapratico — APPROVED** [review]
rename LGTM

**Comment by maririos** [comment]
Some of the live test failures are errors on the service side. Errors have already been communicated with them

**Pull request merged**
