### PR TITLE
[Datafactory] Updated UserProperties model in Activities

### PR DESCRIPTION
**Pull request by hvermis**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
This is a breaking change and should be reflected in the version.
You have a download base of ~1600 as of now for V1.0.0.
With this change you are essentially breaking all of them.
Remove addtionalProperties could have been discussed if it falls under breaking change as it's still a optional parameter, but changing data type of userProperties is for user a breaking change and should be treated according.
Also PackageRelease notes should reflect accordingly.
The code change seems fine.
You need to update version to 2.0.0 and mention the breaking change in the package release notes.

**Comment by shahabhijeet** [comment]
@hvermis can you add the link to the spec PR that was merged for this change.

**Comment by hvermis** [comment]
We didn't mean to remove additionaProperties, bringing them back.
The user properties is a new feature not used by customers yet, but we will add them as breaking change.

**Comment by hvermis** [comment]
Azure spec PR-s
https://github.com/Azure/azure-rest-api-specs/pull/3483/
https://github.com/Azure/azure-rest-api-specs/pull/3493

**Review by shahabhijeet — APPROVED** [review]

**Pull request merged**
