### PR TITLE
Treat service directory as single scope

### LINKED ISSUE #14969: SnippetGenerator behavior is different when running for a single service directory or all of them
This fix only affects core build but not serviceregistry run: https://github.com/Azure/azure-sdk-for-net/pull/14966

### PR DESCRIPTION
**Pull request by heaths**
Fixes #14969

Also write error output as red for easy identification in development environment.

### CODE REVIEW

**Comment by heaths** [comment]
This is blocking use in writing a MigrationGuide.md for Key Vault secrets, pull snippets from track 1 and track 2 to verify code correctness (and caught a couple typos, so there is value).

**Comment by pakrym** [comment]
/azr run net - storage - ci

**Comment by heaths** [comment]
I'll push my actual work that necessitated this to a new PR, which includes sdk/keyvault so the pipeline will trigger.

**Comment by heaths** [comment]
Talked to @pakrym offline and he believes this is an adequate fix to #14969 so I'll close that when I merged this PR.

**Review by pakrym — APPROVED** [review]

**Comment by heaths** [comment]
I'll wait to merge until after both this PR and #15118 pass.

**Comment by heaths** [comment]
The other PR had only 1 random test failure with Service Bus (on MacOS, which all passed here) so I'm going to merge.

**Pull request merged**
