### PR TITLE
OpenRead flag to aggressively deliver requested bytes

### LINKED ISSUE #17673: [FEATURE REQUEST] OpenRead(): loop downloads for Read() calls larger than internal buffer
**Describe the bug**
We discovered an issue that when we use `OpenRead` on `BlockBlobClient`, the returned stream doesn't handle reads of more than 4mb well. When reading more than 4mb, it only reads 4mb:

image

**Expected behavior**
I expect that when I read the entire length of the stream into a buffer, it reads the entire stream

**Actual behavior (include Exception or Stack Trace)**
The current behavior seems to be that even when you pass a number larger than 4mb to the read method, it only reads 4mb.

**To Reproduce**
Use the following snippet to download a file larger than 4mb from a blob container:

```
 var connectionString = "<connectionstring>";
 var blobContainerName = "<containername>";
 var blobName = "<blobName>";
 var targetPath = "<targetPath>";

 var blobClient = new BlobServiceClient(connectionString);
 var blobContainer = blobClient.GetBlobContainerClient(blobContainerName);
 var blob = blobContainer.GetBlockBlobClient(blobName);

 using (var stream = blob.OpenRead())
 {
    using (var destStream = new System.IO.FileStream(targetPath, System.IO.FileMode.Create, System.IO.FileAccess.ReadWrite))
    {
        byte[] buffer = new byte[stream.Length];
        var read = stream.Read(buffer, 0, (int)stream.Length);
        destStream.Write(buffer, 0, (int)stream.Length);
    }
}
```

**Environment:**
 - Name and version of the Library package used:Azure.Storage.Blobs 12.7.0

### PR DESCRIPTION
**Pull request by jaschrep-msft**
Resolves #17673

### CODE REVIEW

**Review by seanmcc-msft — APPROVED** [review]
Approved pending live tests

**Review by amnguye — APPROVED** [review]

**Comment by jaschrep-msft** [comment]
After further design discussion, agreed to drop the feature.

**Pull request closed without merging**
