### PR TITLE
Remove autorest models with internal properties

### PR DESCRIPTION
**Pull request by AlexanderSher**

### CODE REVIEW

**Comment by pakrym** [comment]
Can we get rid of https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/EventGridModelFactory.cs#L11-L19 ?

**Review by pakrym — APPROVED** [review]

**Review by annelo-msft — COMMENTED** [review]
For ACR, this is removing a model type that customers may still want to mock ... are there plans to replace the methods in model factory so they can be created with only the public properties?

**Comment by AlexanderSher** [comment]
@annelo-msft The problem is that we can't be sure that public properties are enough for the model to be fully initialized, so we can't simply supply default values for property types.

**Review by JoshLove-msft — APPROVED** [review]
EG changes look good

**Review by christothes — APPROVED** [review]
tables looks good

**Pull request merged**
