### PR TITLE
Make Response.IsError functional for clients

### LINKED ISSUE #24225: [LLC] Make Response.IsError work on LLC clients
We'll need to find a way to add the `ResponsePropertiesPolicy` to client pipelines by default.

Essentially, we want to make this work: https://github.com/Azure/azure-sdk-for-net/compare/main...annelo-msft:llc-use-iserror
(The test `CanGetOutputModelOnSuccessCodeAsync` fails right now because `System.InvalidOperationException : IsError was not set on the response. Please ensure the pipeline includes ResponsePropertiesPolicy.`)

### PR DESCRIPTION
**Pull request by annelo-msft**
Missed this in the last [IsError PR](https://github.com/Azure/azure-sdk-for-net/pull/24122).  Fixes https://github.com/azure/azure-sdk-for-net/issues/24225

As long as `Response.IsError` lives in Azure.Core.Experimental, we'll need to add the `ResponsePropertiesPolicy` to LLC clients' pipelines in their constructors, as we're doing here.  When this functionality moves into Azure.Core, we can add this to PipelineBuilder.

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
Test?

**Comment by annelo-msft** [comment]
> Test?

`CanGetOutputModelOnSuccessCodeAsync` was failing before this fix with the following exception:

  **Message: 
    System.InvalidOperationException : IsError was not set on the response. Please ensure the pipeline includes ResponsePropertiesPolicy.**

**Comment by pakrym** [comment]
Do we have a test for the error scenario?

**Comment by annelo-msft** [comment]
> Do we have a test for the error scenario?

[CannotGetOutputModelOnFailureCodeAsync](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.Experimental/tests/LowLevelClientTests.cs#L70) is intended to do this, but is there a case you're thinking of that's not covered here?  Happy to add...

**Comment by pakrym** [comment]
That test throws inside the client. Do we have one that throws in the cast operator?

**Pull request merged**
