### PR TITLE
Use Version instead of VersionPrefix, Remove deprecated Language package

### PR DESCRIPTION
**Pull request by yangyuan**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by dsgouda** [comment]
@yangyuan why is the SDK being deleted? Is the service deprecated/removed? We do not delete an SDK for a published Nuget package.
@shahabhijeet Please take a look

**Comment by yangyuan** [comment]
@dsgouda The Microsoft.Azure.CognitiveServices.Language package has been deprecated and replaced with Microsoft.Azure.CognitiveServices.Language.TextAnalytics.

I can understand we do not remove a published Nuget package for back compatibility, but what's the reason we cannot delete the source?
Actually we deleted the SDK (source code) of Microsoft.Azure.CognitiveServices.Vision. But for some reason the previous owner didn't delete the CognitiveServices.Language together with CognitiveServices.Vision.

https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Vision, it's unlisted, I was planning to ask you help to unlist CognitiveServices.Language as well.

I actually think it's the right thing to remove that folder. It can void confusion, and make it easier for developers who want to read the source code.

**Comment by dsgouda** [comment]
I'll let @shahabhijeet make the call here
@yangyuan was this service deprecation approved by the API review board?

**Comment by yangyuan** [comment]
@dsgouda The API service is not deprecated, we just replaced this package with another package: Microsoft.Azure.CognitiveServices.Language.TextAnalytics

Original words from previous owner.
"Originally, we wanted a single Nuget package for each category but later decided to go for granularity."

**Comment by dsgouda** [comment]
@yangyuan I understand. I am curious about the REST service endpoints here. Do they still exist or have they been deprecated too?

**Comment by yangyuan** [comment]
@dsgouda the API endpoint is still working, there is no change on server side.

**Comment by dsgouda** [comment]
Thanks for clarifying that

**Comment by dsgouda** [comment]
@yangyuan please start an email thread requesting unlisting of the package in question.

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
