### PR TITLE
updated Azure SDK with new Property DiffDiskPlacement swagger updates for Ephemeral OS disk

### PR DESCRIPTION
**Pull request by hari-bodicherla**
Added Swagger tests for Single VM and VM Scaleset to verify the ephemeral os disk using DiffDiskPlacement property.

Swagger documentation Pull request for reference:
https://github.com/Azure/azure-rest-api-specs/pull/8847

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi, please regenerate SDK basing on rest api spec on the master branch (after it's merged). Thanks

**Comment by hari-bodicherla** [comment]
Swagger Spec PR got merged. And regenerated SDK based on latest master API Spec .

**Comment by hari-bodicherla** [comment]
@isra-fel  Swagger Spec PR got merged. And regenerated SDK based on latest master API Spec .

**Comment by hari-bodicherla** [comment]
@isra-fel / @erich-wang  Can you please approve the PR and merge

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
