### PR TITLE
1es pool centralcanada test

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR moves the pools over to Central Canada as an experiment for storage. We won't merge this because if this has an impact we'll probably want to make pool selectable in the ```ci.yml``` file.

### CODE REVIEW

**Comment by weshaggard** [comment]
I assume this is just for testing so tagged as do-not-merge. I don't know that we want to move everyone over to one region here just because of storage.

**Comment by mitchdenny** [comment]
> I assume this is just for testing so tagged as do-not-merge. I don't know that we want to move everyone over to one region here just because of storage.

Nope that isn't the intention. This is just data gathering.

**Comment by weshaggard** [comment]
>I don't know that we want to move everyone over to one region here just because of storage.

@kasobol-msft - Just to clarify. If it makes sense for storage to have a machine pool in this region I'd want to do that just for the storage pipelines and not for everyone in the repo, which is what this PR currently does. I didn't mean to imply that we are ignoring this as a potential option for storage.

**Comment by mitchdenny** [comment]
Closing this PR down now. I think this validates that there are some benefits to colocating in Canada Central. We'll address configurability on a per-service directory basis in another PR (which is when we'll setup a proper pool etc).

**Pull request closed without merging**
