### PR TITLE
Delete legacy directory

### PR DESCRIPTION
**Pull request by pakrym**

### CODE REVIEW

**Comment by weshaggard** [comment]
Triggered https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1211407&view=results manually.

**Review by weshaggard — APPROVED** [review]

**Comment by pakrym** [comment]
The run you triggered didn't actually build/test all the libraries. mgmt pipeline has some logic to figure that out based on files changed. I'll poke at some props file to trigger it.

**Comment by weshaggard** [comment]
It didn't build all but it built some which should give us some basic testing to make sure things don't break.

**Pull request merged**
