### PR TITLE
AutoPr-Compute-vamuzumd-REST Spec PrNumber 5560

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by dsgouda** [comment]
@vamuzumd Please join the Azure org [here](https://aka.ms/azuregithub) and open a manual PR against this repo. Cannot merge this PR.

**Comment by vamuzumd** [comment]
> @vamuzumd Please join the Azure org [here](https://aka.ms/azuregithub) and open a manual PR against this repo. Cannot merge this PR.

@dsgouda, I have already joined Azure org, the link you pointed to does not give any team to join. Can you specify the team name to join?

**Comment by dsgouda** [comment]
@azuresdkci retest this please

**Comment by dsgouda** [comment]
@vamuzumd Apologize for the inconvenience but we cannot automatically resolve merge conflicts. Could you please manually create a PR with the changes and test fixes.

**Pull request closed without merging**
