### PR TITLE
update gallery application test example

### PR DESCRIPTION
**Pull request by kangsun-ctrl**
update gallery application test example

### CODE REVIEW

**Comment by nisha-bhatia** [comment]
@kangsun-ctrl This PR has changes to the generated code which is not allowed. Could you revert the change in the generated folder or include the usual artifacts associated with regeneration? Thanks

**Comment by kangsun-ctrl** [comment]
> @kangsun-ctrl This PR has changes to the generated code which is not allowed. Could you revert the change in the generated folder or include the usual artifacts associated with regeneration? Or if there were changes to the Swagger, could you please post the Swagger PR? Thanks

**Comment by kangsun-ctrl** [comment]
This sdk change is because we are making change in swagger: https://github.com/Azure/azure-rest-api-specs/pull/12438

**Comment by grizzlytheodore** [comment]
changes in the generated folder are derived from change in swagger here https://github.com/Azure/azure-rest-api-specs/pull/12438

**Comment by Sandido** [comment]
RElated Swagger change: https://github.com/Azure/azure-rest-api-specs/pull/12438

**Comment by ashvermamsft** [comment]
@markcowl we need this to get checked in so that the cloudServices PR (https://github.com/Azure/azure-sdk-for-net/pull/17341) can go in. On the latest SDK generation from master, we have started facing the gallery test build failures.

**Comment by markcowl** [comment]
/ azp run net - mgmt -ci

**Comment by grizzlytheodore** [comment]
@kangsun-ctrl  @allenjzhang  why was this closed? 
the changes in this PR are a reflection of changes in swagger: https://github.com/Azure/azure-rest-api-specs/pull/12438

**Comment by kangsun-ctrl** [comment]
> @kangsun-ctrl @allenjzhang why was this closed? Also what is the reason for 'Do not Merge' ?
> the changes in this PR are a reflection of changes in swagger: [Azure/azure-rest-api-specs#12438](https://github.com/Azure/azure-rest-api-specs/pull/12438)

@grizzlytheodore  This pr got merged to another pr which contains whole change for 2020-10-preview. The change is already merged to sdk 2020-12-preview release.

**Comment by grizzlytheodore** [comment]
@kangsun-ctrl  ty

**Pull request closed without merging**
