### PR TITLE
Fix recommendation engine APIs along with resource property fixes, add new APIs and tests

### PR DESCRIPTION
**Pull request by michimune**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR [2548](https://github.com/Azure/azure-rest-api-specs/pull/2548)
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please run `generate.cmd` to generate the code. This should also generate a `.txt` file, please commit the file.
(If the file is not generate please pull down the latest changes and try again)

**Comment by michimune** [comment]
I ran generate.cmd and a file named src\SDKs\_metadata\web_resource_manager.txt was created. Is this what I need to commit?

**Comment by dsgouda** [comment]
@michimune yes

**Comment by michimune** [comment]
@dsgouda Pushed the .txt file.

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@shahabhijeet please merge when ready

**Comment by dsgouda** [comment]
@michimune There are few more things to be done here

1) Msbuild build.proj (this will download latest build tools)
2) Use generate.cmd to generate your SDK
3) Build you sdk using msbuild build.proj /t:Build /p:Scope=SDKs\Websites
4) This will add all the meta data that is required

This should update the `.props` file and also generate a new `SDKInfo*.cs` file. Please commit these changes.

**Comment by michimune** [comment]
@dsgouda Pushed another commit. How does this look?

**Comment by dsgouda** [comment]
@michimune taking a look

**Review by dsgouda — APPROVED** [review]
LGTM @shahabhijeet PTAL and merge

**Comment by michimune** [comment]
Thank you!

**Pull request merged**
