### PR TITLE
Websites SDK: Regenerated from 2016-09-01 Swagger update

### PR DESCRIPTION
**Pull request by nking-1**
This change updates the Websites SDK to the 2016-09-01 API level. We have significantly changed our API surface this time, so this update contains many breaking changes. Several models have been renamed (for example, ServerFarm -> AppServicePlan), and the naming convention for methods has changed.

The version has been updated from 1.3.2-preview to 1.4.0-preview to indicate this is a major update.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Nking92__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nicking). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Nking92** [comment]
Tests are failing due to this issue: https://github.com/Azure/azure-sdk-for-net/issues/2501.

**Comment by markcowl** [comment]
@Nking92 We have this fix scheduled in the current sprint

**Comment by Nking92** [comment]
@markcowl Any updates on this?

**Comment by markcowl** [comment]
@Nking92 The changes were just merged into the AutoRest branch, and should be published soon

**Comment by Nking92** [comment]
@markcowl Great. It looks like that fixed the tests here as well. #signoff for merging this now that it's passing checks.

**Comment by shahabhijeet** [comment]
@Nking92  from the description, it seems this PR has introduced many breaking changes.
just FYI: PS code complete is next week and we are not accepting any breaking change for PS, so plan accordingly for applicable PS changes (if any)

**Comment by Nking92** [comment]
@shahabhijeet This does include many breaking changes that will probably affect our Powershell code. Thanks for the heads up.

**Pull request merged**
