### PR TITLE
Remove hard coded location from tests

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**
Remove hard coded location from tests and re-record tests

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by DeepakRajendranMsft** [comment]
The build succeeds but in the end it fails with exception below. Could we please re-trigger the build?

[ANALYSIS-COLLECTOR] Computing warning deltas based on reference build #884
Archiving artifacts
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level D:/workspace/sdk-for-net/TestResults to F:\Jenkins\jobs\sdk-for-net\htmlreports\Unit_Test_Report
FATAL: HTML Publisher failure
java.nio.file.FileSystemException: F:\Jenkins\jobs\sdk-for-net\htmlreports\Unit_Test_Report\Compute.Tests.html: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.nio.file.Files.delete(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at hudson.Util.deleteFile(Util.java:247)
	at hudson.FilePath.deleteRecursive(FilePath.java:1204)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1213)
	at hudson.FilePath.deleteRecursive(FilePath.java:1195)
	at hudson.FilePath.access$1000(FilePath.java:191)
	at hudson.FilePath$14.invoke(FilePath.java:1174)
	at hudson.FilePath$14.invoke(FilePath.java:1171)
	at hudson.FilePath.act(FilePath.java:991)
	at hudson.FilePath.act(FilePath.java:969)
	at hudson.FilePath.deleteRecursive(FilePath.java:1171)
	at htmlpublisher.HtmlPublisher.perform(HtmlPublisher.java:210)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Build step 'Publish HTML reports' changed build result to FAILURE
Setting commit status on GitHub for

**Comment by stankovski** [comment]
@azuresdkci retest this please

**Comment by stankovski** [comment]
@azuresdkci retest this please

**Pull request merged**
