### PR TITLE
Stash selected credential in DefaultAzureCredential exceptions

### LINKED ISSUE #22424: Enrich authentication failed exceptions with more information about credential
It's hard to debug auth errors and even harder with DefaultAzureCredential when you don't know which one was selected.

Can we attach more diagnostic information to 403 failures in clients?

related https://github.com/Azure/azure-sdk-for-net/issues/8948

### PR DESCRIPTION
**Pull request by christothes**
fixes #22424

### CODE REVIEW

**Comment by pakrym** [comment]
I think my issue is not entirely correct. What I was trying to say, enrich the exception that's being thrown because the service returns 403.

It's often the case when retrieving of the token credential succeeds but the service authentication fails. This is where it would be nice to have more information to be able to debug better.

**Comment by christothes** [comment]
> I think my issue is not entirely correct. What I was trying to say, enrich the exception that's being thrown because the service returns 403.
> 
> It's often the case when retrieving of the token credential succeeds but the service authentication fails. This is where it would be nice to have more information to be able to debug better.

It may be helpful if you could provide a real-world example of an exception with actual / expected exception details.

**Comment by christothes** [comment]
related to #22540

**Comment by pakrym** [comment]
I'm sorry that it took me forever to come back to this.

Let's take the following code:

```C#
BlobClient c = new BlobClient(new Uri("https://2hdjwpjcai7ymazfunctions.blob.core.windows.net/azure-webjobs-hosts/changeanalysis/fnapp2hdjwpjcai7ym/sentinel"), new DefaultAzureCredential());

c.DownloadContent();
```

The following exception would get thrown:

```
RequestFailedException: This request is not authorized to perform this operation using this permission.
RequestId:a3d3f03a-601e-005a-5946-7f52f3000000
Time:2021-07-22T22:11:41.8515402Z
Status: 403 (This request is not authorized to perform this operation using this permission.)
ErrorCode: AuthorizationPermissionMismatch

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:a3d3f03a-601e-005a-5946-7f52f3000000
Time:2021-07-22T22:11:41.8515402Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: a3d3f03a-601e-005a-5946-7f52f3000000
x-ms-client-request-id: 25394e54-0070-42d9-adad-0740a0a1dc48
x-ms-version: 2020-08-04
x-ms-error-code: AuthorizationPermissionMismatch
Date: Thu, 22 Jul 2021 22:11:41 GMT
Content-Length: 279
Content-Type: application/xml
```

What I was thinking about is enriching the error with more authentication-related information.

``` diff
RequestFailedException: This request is not authorized to perform this operation using this permission.
RequestId:a3d3f03a-601e-005a-5946-7f52f3000000
Time:2021-07-22T22:11:41.8515402Z
Status: 403 (This request is not authorized to perform this operation using this permission.)
ErrorCode: AuthorizationPermissionMismatch

+ EnvironmentCredential was used with client id <...> and tenant id <...>
or 
+ VisualStudioCredential was used for user <...> 

```

I understand it might be hard to implement or considered insecure all together but helps to debug situations where you don't know which one of many possible local credential sources was used.

**Comment by christothes** [comment]
Thanks for the example!

> I understand it might be hard to implement or considered insecure all together but helps to debug situations where you don't know which one of many possible local credential sources was used.

Yes, anything beyond the credential chosen could potentially be considered PII, so we'd most likely not expose that in logging or the exception. 

In your example scenario, what piece of info would have helped you determine the issue more quickly? Was an unexpected TokenCredential selected, or was an unexpected clientId, UserId, TenantId selected. If the latter, I wonder if there is more we could do to indicate where the credential was taken from, without exposing its value. 

For example, knowing that the ClientId was taken from an environment variable rather than the constructor might be enough of a clue to point you to the problem.

**Comment by pakrym** [comment]
>In your example scenario, what piece of info would have helped you determine the issue more quickly? Was an unexpected TokenCredential selected, or was an unexpected clientId, UserId, TenantId selected. If the latter, I wonder if there is more we could do to indicate where the credential was taken from, without exposing its value.

Every time an exception like this happens when I'm connecting to the new service my immediate question is whether it's RBAC configuration or did DAC just pick up the wrong account. So anything that can point me to what I was effectively authenticated with helps.

**Comment by christothes** [comment]
> So anything that can point me to what I was effectively authenticated with helps.

It seems like the current changes provide some additional context towards that goal. Would it be better if the credential details were in the message rather than stashed in Data?

**Comment by pakrym** [comment]
>It seems like the current changes provide some additional context towards that goal.

You are stashing it on the wrong exception :) 

The authentication with AAD succeeds in this case, but the authentication with the service using AAD token doesn't.

**Comment by christothes** [comment]
@msftbot, you so cray.

**Review by schaabs — COMMENTED** [review]
I think the selected credential type will already be part of the exception method no? Also as we discussed offline, the issue is requesting we add this data to 403 and 401 failures where we successfully got a token, so there will be no exception from DefaultAzureCredential. Based on that do we still feel this change is necessary or can this PR be closed?

**Pull request closed without merging**
