### PR TITLE
Update Azure Key Vault SDK components for .NET Standard 1.5

### PR DESCRIPTION
**Pull request by herveyw-msft**

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@azurecla add to whitelist

**Comment by hovsepm** [comment]
@herveyw  .vscode folders should be excluded through gitignore. Do you really need to have them on github?

**Comment by herveyw** [comment]
@hovsepm None of the .vscode content is user specific and gets auto-added when you work on VSCode on Mac. I don't see any reason to exclude them. We do want to make them better over time.

**Comment by herveyw** [comment]
Updated with a merge from AutoRest to re-run CI.

**Comment by herveyw** [comment]
Updated with a dependency clean up.

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@hovsepm please sign off.
LGTM

**Pull request merged**
