### PR TITLE
Fix the path for all ci settings

### PR DESCRIPTION
**Pull request by ArthurMa1978**

### CODE REVIEW

**Comment by jsquire** [comment]
@ArthurMa1978:  Can you help me understand why this change is needed?

**Comment by ArthurMa1978** [comment]
> @ArthurMa1978: Can you help me understand why this change is needed?

https://github.com/Azure/azure-sdk-for-net/pull/29059#discussion_r888302856
@benbp suggested to change this.

**Comment by ArthurMa1978** [comment]
> > @benbp suggested to change this.
> 
> Thank you for the context. In that case, I'll defer to the engsys team for approvals.

I will ping @benbp ~

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
Thanks for the fix @ArthurMa1978. For future we need to be careful about changing a ton of ci.yml files across the repo because as you can see it triggers a ton of pipelines and can cause a build storm where our queue gets backed up.

**Pull request merged**
