### PR TITLE
[MetricsAdvisor] Add tests for Skip and MaximumPageSize input options in AnomalyAlertConfigurationLiveTests and AnomalyDetectionConfigurationLiveTests

### PR DESCRIPTION
**Pull request by Gyeonghun-Park**
Changes:

- Add test for Size input option in AnomalyAlertConfigurationLiveTests
- Add test for MaximumPageSize input option in AnomalyAlertConfigurationLiveTests
- Add test for Size input option in AnomalyDetectionConfigurationLiveTests
- Add test for MaximumPageSize input option in AnomalyDetectionConfigurationLiveTests

Part of #20621

### CODE REVIEW

**Review by kinelski — COMMENTED** [review]
Once again, thank you for contributing! I liked the approach taken for both `Skip` and `MaxPageSize` tests, but left a few questions/suggestions. Let me know what you think.

**Comment by Gyeonghun-Park** [comment]
If you don't mind, could you review the records for those tests? Although I have generated records, they may not be perfect because they are based on my personal server, not on js-metrics-advisor server.

**Comment by kinelski** [comment]
> If you don't mind, could you review the records for those tests? Although I have generated records, they may not be perfect because they are based on my personal server, not on js-metrics-advisor server.

Records look good! Recorded tests are run as part of PR validation, so they should be working fine if the PR checks passed.

**Review by kinelski — APPROVED** [review]
Let me know whenever you're ready to have this PR merged!

**Comment by kinelski** [comment]
There's some Metrics Advisor parallel work going on right now. I'm merging this so you don't have to deal with merge conflicts that will likely emerge. Feel free to open a new PR or an issue if you feel we missed anything on this one.

**Pull request merged**
