### PR TITLE
Delete old Mgmt plane, Restructure GraphRbac to Dataplane

### PR DESCRIPTION
**Pull request by chidozieononiwu**
- Delete old Management Libraries Except Search and SDKCommon
- Make GraphRBAC a DataPlane library.

### CODE REVIEW

**Comment by chidozieononiwu** [comment]
azp run net - client - ci

**Comment by chidozieononiwu** [comment]
azp run net - client - ci

**Review by shahabhijeet — APPROVED** [review]

**Comment by chidozieononiwu** [comment]
azp run net - client - ci

**Pull request merged**
