### PR TITLE
Update sqlmanagement SDK and tests for ReadScale

### PR DESCRIPTION
**Pull request by bradrich-msft**
spec: Azure/azure-rest-api-specs#6902

### CODE REVIEW

**Review by jaredmoo — APPROVED** [review]
Looks great other than release notes update

**Review by erich-wang — CHANGES_REQUESTED** [review]
@bradrich-msft , please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec) to:
- add a link to the spec review PR in the description
- Update Version, tags if necessary
- A .txt file should be in `eng\mgmt\mgmtmetadata` if you use generate.ps1

**Comment by bradrich-msft** [comment]
PR was updated to address feedback.  Please have a look.

**Review by erich-wang — CHANGES_REQUESTED** [review]
@bradrich-msft , please
- eng/mgmt/mgmtmetadata/sql_resource-manager.txt should be under root folder your repo
- add a link to the spec review PR in the description

**Comment by bradrich-msft** [comment]
This has been done.  Thank you.

**Comment by isra-fel** [comment]
Hi @bradrich-msft we still need a link to the swagger review PR. You can put it in the description or comments. Thanks

**Comment by bradrich-msft** [comment]
I already put a link to the swagger review PR in this commit: https://github.com/Azure/azure-sdk-for-net/pull/7592/commits/af07b21eea6fe215dc1283080e95e0fbf853fdbf


“Based on updated spec. PR for updated spec: Azure/azure-rest-api-specs#6902<https://github.com/Azure/azure-rest-api-specs/pull/6902>”

**Comment by bradrich-msft** [comment]
> Hi @bradrich-msft we still need a link to the swagger review PR. You can put it in the description or comments. Thanks

Hi.  It was already there: "Based on updated spec. PR for updated spec: Azure/azure-rest-api-specs#6902"

**Comment by isra-fel** [comment]
> > Hi @bradrich-msft we still need a link to the swagger review PR. You can put it in the description or comments. Thanks
> 
> Hi. It was already there: "Based on updated spec. PR for updated spec: [Azure/azure-rest-api-specs#6902](https://github.com/Azure/azure-rest-api-specs/pull/6902)"

Oh that was a little hard to find... could you please put the link in the description of the PR next time, thanks?

**Review by isra-fel — APPROVED** [review]

**Comment by isra-fel** [comment]
Erich's comments have been resolved. I'll merge it.

**Pull request merged**
