### PR TITLE
Rebranding Microsoft Entra

### PR DESCRIPTION
**Pull request by cilwerner**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by jsquire** [comment]
//cc: @hakimms, @HarmanDhunna

**Comment by jsquire** [comment]
@cilwerner:  Thank you for your contribution and your interest in improving the Azure development experience.  I've assigned this over to the owners of this package for review.

**Review by hakimms — APPROVED** [review]
These changes looks good to me

**Review by HarmanDhunna — APPROVED** [review]

**Comment by HarmanDhunna** [comment]
@jsquire or @AlexanderSher  could you please merge this in for us?

**Pull request merged**
