### PR TITLE
Regenerate Event Grid .NET SDK for 2020-04-01-preview to include new properties changes

### PR DESCRIPTION
**Pull request by ahamad-MS**
Regenerate Event Grid .NET SDK for 2020-04-01-preview to include new properties changes

- Link to Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/9402
- Link to Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2020-04-01-preview/EventGrid.json

### CODE REVIEW

**Comment by ahamad-MS** [comment]
Hello @isra-fel @erich-wang ... Can you please help reviewing this change?

Also, it seem check-enforcer is stuck in running state since yesterday. Is this infra issue?

thanks

**Review by isra-fel — APPROVED** [review]
LGTM.
Check-enforcer was yellow because test mac os was failed, and that's because there's something wrong with test environment. I'll get back to you when I find a solution

**Comment by isra-fel** [comment]
Hello, I just merged a PR to skip that test: https://github.com/Azure/azure-sdk-for-net/pull/12097
Could you rebase latest master?

**Comment by ahamad-MS** [comment]
Hello @isra-fel  .. Thanks for merging the test fix.. I rebased and resubmitted. All checks passe snow. Kindly merge the change.

thanks

**Pull request merged**
