### PR TITLE
Support short parameter strings for Deployments API.

### PR DESCRIPTION
**Pull request by TianoMS**

### CODE REVIEW

**Comment by vivsriaus** [comment]
@TianoMS how about templates without schema? Are those supported as well? 

On a separate note - now that our SDK can handle templates and parameters with schema "natively", we should consider removing the current powershell deployment cmdlet code (where we handle "schema" separately, before constructing the deployment object) and instead let the sdk handle the logic (like you do in the tests). Cc @ravbhatnagar

**Comment by markcowl** [comment]
@vivsriaus @TianoMS is this ready to merge?

**Comment by TianoMS** [comment]
@markcowl Not yet. Need to update with one change.

**Comment by TianoMS** [comment]
@vivsriaus Updated and fixed the V1 schema.

**Comment by vivsriaus** [comment]
LGTM

**Pull request merged**
