### PR TITLE
Add server connection policy and test

### PR DESCRIPTION
**Pull request by jaredmoo**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
Resolve merge conflicts.
Also please provide link to the swagger changes.
Once we have all this changes, this PR will be reviewed.

**Comment by jaredmoo** [comment]
This brings net sdk up to latest swagger commit , e26c0c7bcf6557dc33c29d371be0b59613d03415

**Comment by shahabhijeet** [comment]
@jaredmoo is there a reason the commit mentioned above is not being used in generate.cmd?
can you update generate.cmd and regenerate with latest autorest.

**Comment by jaredmoo** [comment]
Generate.cmd actually is using that commit id. See https://github.com/Azure/azure-sdk-for-net/pull/3437/files#diff-e1b985120438960f348d90dcf9dfebedR8

**Review by shahabhijeet — APPROVED** [review]

**Comment by jaredmoo** [comment]
Thanks!

**Pull request merged**
