### PR TITLE
Distinguish the ASA variables so they don't clash with the ARR ones.

### PR DESCRIPTION
**Pull request by matyrr-havok**
The environment variables used in mixed reality are named generically, but it would be better if they were declared as ASA specific variables so when we add ARR ones, it's less confusing.

### CODE REVIEW

**Comment by craigktreasure** [comment]
Not sure I agree with this since those variables aren't specific to ASA accounts. You could use any Mixed Reality account details.

**Comment by craigktreasure** [comment]
ARR account details can be differentiated by using ARR specific prefixes so that they don't clash.

**Comment by MalcolmTyrrell** [comment]
That account information is obtained using the "Microsoft.MixedReality/spatialAnchorsAccounts" endpoint. The equivalent ARR accounts will be generated using the "Microsoft.MixedReality/remoteRenderingAccounts" endpoint.

**Comment by MalcolmTyrrell** [comment]
So while I agree that the current auth tests don't need an ASA account, that's what is created. There's no clash (because I have a prefix on mine) but the naming is a little surprising due to the asymmetry. The renaming will be particularly useful if ASA gets its a data plane SDK. This is very low priority, so feel free to reject this if you really feel it doesn't add value.

**Comment by craigktreasure** [comment]
I'd prefer not to have product specific details bleed into the Authentication SDK. I realize that the live tests are using an ASA resource, but they have to have something and that's the only time we use something ASA specific. When\if ASA onboards a Data Plane SDK, they could either reuse the resource or setup a new one. It doesn't matter to me.

**Pull request closed without merging**
