### PR TITLE
[Datafactory] Updating Assembly version for release and adding a serialization test for new activities

### PR DESCRIPTION
**Pull request by hvermis**

### CODE REVIEW

**Comment by hvermis** [comment]
The tests failed on this build because they need the changes from PR https://github.com/Azure/azure-sdk-for-net/pull/5607.

**Comment by hvermis** [comment]
@dsgouda Can you please restart the build on this PR?

**Comment by dsgouda** [comment]
@azuresdkci Retest this please

**Comment by hvermis** [comment]
@dsgouda, thanks for restarting the build. They passed, could you please merge this so I can release ADF SDK?

**Review by dsgouda — APPROVED** [review]
LGTM

**Pull request merged**
