### PR TITLE
Configuration_ApplyOnEdgeDevice should only return empty response

### PR DESCRIPTION
**Pull request by bikamani**

### CODE REVIEW

**Review by timtay-microsoft — APPROVED** [review]

**Review by abhipsaMisra — APPROVED** [review]
FWIW, in the past we haven't merged these "recommended changes" to `master` until the changes have been deployed by the service team.

**Comment by bikamani** [comment]
> FWIW, in the past we haven't merged these "recommended changes" to `master` until the changes have been deployed by the service team.

Do you mean for swagger changes in modified json?

**Comment by abhipsaMisra** [comment]
> > FWIW, in the past we haven't merged these "recommended changes" to `master` until the changes have been deployed by the service team.
> 
> Do you mean for swagger changes in modified json?

Yes.
[iothubservice.json](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/src/swagger/iothubservice.json) - The swagger file that the service team provides. This should represent the state of the service that is currently deployed.
[iothubservice_modified.json](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/src/swagger/iothubservice_modified.json) - This version is maintained by us to keep track of changes that we recommend to the service team (historically this has been changes to comments/ marking fields as required, etc.)

**Comment by bikamani** [comment]
> > > FWIW, in the past we haven't merged these "recommended changes" to `master` until the changes have been deployed by the service team.
> > 
> > 
> > Do you mean for swagger changes in modified json?
> 
> Yes.
> [iothubservice.json](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/src/swagger/iothubservice.json) - The swagger file that the service team provides. This should represent the state of the service that is currently deployed.
> [iothubservice_modified.json](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/iot/Azure.Iot.Hub.Service/src/swagger/iothubservice_modified.json) - This version is maintained by us to keep track of changes that we recommend to the service team (historically this has been changes to comments/ marking fields as required, etc.)

Later is what I am doing then here --> changes that we recommend to the service team

**Comment by abhipsaMisra** [comment]
Oh yes, you are right, @bikamani ! My bad, I misread the name of the file!

**Pull request merged**
