### PR TITLE
ClientCertificateCredential implements IDisposable

### LINKED ISSUE #12080: [FEATURE REQ] Make ClientCertificateCredential disposable and dispose of the underlying X509Certificate2
**Library or service name.**
`Azure.Identity`
 
**Is your feature request related to a problem? Please describe.**
`ClientCertificateCredential` accepts a `X509Certificate2` and keeps it as an internal property: 
https://github.com/Azure/azure-sdk-for-net/blob/727ab08412e60394b6fea8b13cac47d83aca1f3b/sdk/identity/Azure.Identity/src/ClientCertificateCredential.cs#L33

However `X509Certificate2` and `ClientCertificateCredential`, which burdens the developer with having to dispose of one object only when they're done using another.

Making `ClientCertificateCredential` disposable, allowing the developer to dispose of the underlying `X509Certificate2` would prevent the need to construct custom holder objects.

### PR DESCRIPTION
**Pull request by christothes**
closes #12080

### CODE REVIEW

**Review by schaabs — APPROVED** [review]
This changes look good from my perspective. It fixes a resource leak in the case this credential instantiates the `X509Certificate2` from a path. @KrzysztofCwalina and @pakrym I know you both expressed a want to avoid making SDK types disposable unless absolutely necessary. Do you feel making `ClientCertificateCredential` disposable is warranted in this case to avoid a possible native resource leak? Also are there any compatibility concerns with making a type `IDisposable` which previously was not?

**Comment by pakrym** [comment]
It won't be a leak, the finalizer would clean the native resource up. And for customers that want to do it earlier, we can recommend loading cert themselves and disposing the instance.

**Comment by schaabs** [comment]
> It won't be a leak, the finalizer would clean the native resource up.

On .NET core finalizers are not guaranteed to execute. And while users can create the `X509Certificate2` themselves to control the lifetime when using `ClientCertificateCredential` they don't have this ability when using it indirectly such as with the `EnivornmentCredential` or `DefaultAzureCredential`. So if we made this change we would want to make those types disposable as well.

**Comment by pakrym** [comment]
>On .NET core finalizers are not guaranteed to execute

Do you mean the shutdown scenario?

>using it indirectly such as with the EnivornmentCredential or DefaultAzureCredential.

Don't forget the `ChainedTokenCredential` as well :)

**Comment by christothes** [comment]
I'm going to close this for now unless there is more customer interest. It seems that the finalizer is mostly sufficient and I hadn't considered the potential fan out of types that would also need to handle conditional dispose logic.

**Pull request closed without merging**
