### PR TITLE
[HDInsight]Release version 1.1.0

### PR DESCRIPTION
**Pull request by yuc-Li**
Release non beta versions based on API version 2021-6.

### CODE REVIEW

**Comment by yuc-Li** [comment]
Hi @ArthurMa1978 , there is an error in the pipeline now, could you help take a look?

**Error : When the project has a release version it shouldn't reference any pre-release libraries. Found the following pre-release references: Azure.Core.Expressions.DataFactory**

But when I checked Azure.Core.Expressions.DataFactory in [NuGet Gallery](https://www.nuget.org/packages/Azure.Core.Expressions.DataFactory/1.0.0-beta.2#versions-body-tab), it did only have a pre-release version.
image

**Comment by yuc-Li** [comment]
The above problem has been resolved without any action.

**Comment by aim-for-better** [comment]
Hi team, we are HDInsight team, could you please help review this PR ? Thanks

**Comment by aim-for-better** [comment]
We want to release a 1.1.0 version for Azure.ResourceManager.HDInsight package.

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
