### PR TITLE
API updates from AppConfig cross-language comparison

### PR DESCRIPTION
**Pull request by annelo-msft**
- Make Set() with MatchConditions internal (only allow opt-in to conditional requests via bool onlyIfChanged, onlyIfUnchanged parameters in the API)
- Bring back Get() that takes an acceptDateTime (not doing for this release, tracked in #8211)

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
Do we want to remove these methods?

**Comment by annelo-msft** [comment]
Yes, the most common conditional scenario for Set (PUT) is If-Match=ETag.  We enable this with the boolean onlyIfUnchanged parameter to Set, which makes it so that all the CRUD operations let you opt-in to the common conditional case with a simple boolean.  For Set only if not exists we have Add.  We don't have user scenarios to allow app config users to "set only if server version doesn't match the client's version" or "update only if it it's present on the server."  If these later come up, we can re-enable these methods.

**Comment by pakrym** [comment]
My question was should we remove them instead of leaving internal? Keeping unused methods increases maintenance cost.

**Comment by annelo-msft** [comment]
Ah, I see.  https://github.com/Azure/azure-sdk-for-net/issues/8255

**Pull request merged**
