### PR TITLE
[Search] Add missing property when cloning `SearchOptions`

### PR DESCRIPTION
**Pull request by Mohit-Chakraborty**
Copy all properties using reflection to alleviate the issue of missing some properties in the copy code.

### CODE REVIEW

**Comment by Mohit-Chakraborty** [comment]
Issue #27549

**Comment by Mohit-Chakraborty** [comment]
> Issue #27549

This is the category of issues I am trying to kill with this approach. It has happened a few times now. The current issue is for an old property, so the bug has existed for a while.

**Comment by Mohit-Chakraborty** [comment]
cc: @tg-msft
What do you think of this solution? Alternatively, we could add the one we know is missing currently and be more diligent in the future.

**Comment by JoshLove-msft** [comment]
It looks like these are all value types, would a [MemberwiseClone](https://docs.microsoft.com/en-us/dotnet/api/system.object.memberwiseclone?redirectedfrom=MSDN&view=net-6.0#System_Object_MemberwiseClone) work?

**Comment by JoshLove-msft** [comment]
Another idea would be to just do the reflection in the unit test, and keep the production code up to date by hand. This way you will catch future missing properties automatically in the test, but won't have to use reflection in production code.

**Comment by Mohit-Chakraborty** [comment]
> Another idea would be to just do the reflection in the unit test, and keep the production code up to date by hand. This way you will catch future missing properties automatically in the test, but won't have to use reflection in production code.

What would the test check? The count of the properties?

**Comment by JoshLove-msft** [comment]
> > Another idea would be to just do the reflection in the unit test, and keep the production code up to date by hand. This way you will catch future missing properties automatically in the test, but won't have to use reflection in production code.
> 
> What would the test check? The count of the properties?

The test could check that each property on the source is equal to the corresponding property on the destination.

**Review by JoshLove-msft — APPROVED** [review]

**Pull request merged**
