### PR TITLE
Instrument events when they are enqueued in the buffered producer

### LINKED ISSUE #38224: [BUG] distributed tracing inconsistency
### Library name and version

Azure.Messaging.EventHubs 5.9.2

### Describe the bug

an `EventHubBufferedProducerClient.EnqueueEventAsync(eventData);` is used to enqueue a message. I think it's safe to assume, that the activity used to enqueue that message has since ended and its activity is no longer in scope.

the following are all set on that message when it was enqueued:
```
AppContext.SetSwitch("Azure.Experimental.EnableActivitySource", true)
eventData.Properties.TryAdd("traceparent", Activity.Current?.Id);
eventData.Properties.TryAdd("tracestate", Activity.Current?.TraceStateString);
```

The distributed traces in application insights do not link the consumer traces to the producer traces unless i manually set `_telemetryClient.Context.Operation.ParentId = args.Properties["traceparent"]` in the corresponding consumer service application. If there are a chain of services to follow then the same would hold true for them; neither the producer nor the consumer traces to follow would show in the distributed trace.

### Expected behavior

I feel like the sdk has all the information it needs to reconstruct the activity so that the consumer clients don't need to set `_telemetryClient.Context.Operation.ParentId = args.Properties["traceparent"]`. Moreover, any traces/requests/dependencies would not be correlated if they occur before i have the opportunity to set that ParentId.

It should also probably be documented that the BufferedProducerClient requires the setting of those three properties/appswitches so that full distributed tracing works when using a buffered producer. It wasn't documented anywhere I could find and I had to read the source code to figure it out.

### Actual behavior

without setting `_telemetryClient.Context.Operation.ParentId = args.Properties["traceparent"]` the distributed trace looks like so

image

with none of the distributed tracing that would include or follow that consumer service and its downstream services

### Reproduction Steps

use an `EventHubBufferedProducerClient.EnqueueEventAsync(eventData);` to enqueue a message. ensure that the activity used to enqueue that message has since ended and its activity is no longer in scope.

set the following are all set on that message when it was enqueued:
```
AppContext.SetSwitch("Azure.Experimental.EnableActivitySource", true)
eventData.Properties.TryAdd("traceparent", Activity.Current?.Id);
eventData.Properties.TryAdd("tracestate", Activity.Current?.TraceStateString);
```

use a consumer service application, in our case we used the EventProcessorClient, to consume a message from that eventhub and then write it to another eventhub. Then check the transactions in app insights for that original request. The traces for the first producer and first consumer app are there, but not the downstream consumer app. The first consumer's requests/dependencies/links are all missing from within the timeline of the consumer app as well and you won't see the chain of services to follow in that timeline and the second producer and second consumer traces, requests, dependencies would all be missing.

### Environment

bacon on  bugfix/tracing via .NET v7.0.400 on 󰠅 REZI_HOM_Eng_Titan_QA took 2s 
❯ dotnet --info
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/38224

### CODE REVIEW

**Review by lmolkova — APPROVED** [review]
LGTM, thank you!

**Review by jsquire — APPROVED** [review]
If you'd be so kind as to include the change log with this, it would be appreciated.   I expect that I'll forget to add it, otherwise.

**Review by m-redding — APPROVED** [review]

**Comment by jsquire** [comment]
@JoshLove-msft, @lmolkova:  The buffered producer passes events to an inner producer client, which will add the diagnostic id and trace information.  Are we now adding double-traces with this update?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft, @lmolkova: The buffered producer passes events to an inner producer client, which will add the diagnostic id and trace information. Are we now adding double-traces with this update?

The buffered producer creates batches and sends them with the inner producer client. The events added to a batch are instrumented via calls to _[InstrumentMessage](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/MessagingClientDiagnostics.cs#L161)_. InstrumentMessage is idempotent - it won't overwrite any existing instrumentation.

**Pull request merged**
