### PR TITLE
vso # 6946663 accelerated networking changes for sdk

### PR DESCRIPTION
**Pull request by skomarag**
1. New field called accelerated networking added to network interface
2. Tested sure the field is serialized and deserialized for putnic

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@skomarag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (skomar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@skomarag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (skomar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by skomarag** [comment]
merge intermittent issues

**Comment by markcowl** [comment]
closing as I believe this is superseded by the new PR

**Pull request closed without merging**
