### PR TITLE
Improve the GetHashCode and Equals methods in JsonWebKey 

### PR DESCRIPTION
**Pull request by pomortaz**
1. Improve the GetHashCode and Equals methods in JsonWebKey 
2. Take the class to its previous format of Json property validator (from master branch)
3. Added tests

### CODE REVIEW

**Comment by pomortaz** [comment]
@msfcolombo please review. The change is to replicate the behavior of Java for JsonWebKey for Equals and GetHashCode and add back some functionalities that was removed from JsonWebKey initially for Json properties.

**Comment by pomortaz** [comment]
@rohmano please review.

**Review by rohmano — APPROVED** [review]

**Comment by pomortaz** [comment]
@hovsepm please merge.

**Comment by markcowl** [comment]
@pomortaz, there are merge conflicts - you'll need to pull the latest from the Extensions project

**Comment by pomortaz** [comment]
@markcowl I merged the changes and resolved the conflict.

**Pull request merged**
