### PR TITLE
Changes to v3.0 of TA

### LINKED ISSUE #10443: Update TextAnalyticsServiceVersion when service GA
Currently, service is still under preview and using version V3_0_preview_1("v3.0-preview.1").

When service GA, this required to be updated.

### LINKED ISSUE #10635: Detect language rename from Score to Confidence Score
changes from v2 and v3. What can we do?

### LINKED ISSUE #10636: Add sentimentText to result for AnalyzeSentiment

### LINKED ISSUE #10976: Rename Category and Subcategory
Service did the rename instead of using Type and Subtype. We need to reflect this change too.

### PR DESCRIPTION
**Pull request by maririos**
Fixes: https://github.com/Azure/azure-sdk-for-net/issues/10635
Fixes: https://github.com/Azure/azure-sdk-for-net/issues/10976
Fixes: https://github.com/Azure/azure-sdk-for-net/issues/10443
Fixes: https://github.com/Azure/azure-sdk-for-net/issues/10636

Note: Creating as draft until I get internal CI working. Then I will update recordings

### CODE REVIEW

**Review by iscai-msft — APPROVED** [review]
Looks good, like that you updated samples with the new properties too!

**Comment by maririos** [comment]
@danieljurek issue https://github.com/Azure/azure-sdk-for-net/issues/11598 created.
I tested our internal pipelines and everything is green.

**Comment by maririos** [comment]
@chidozieononiwu @mitchdenny I accidentally trigger pipelines that are not related to this PR and because those are failing, the check enforcer doesn't let me merge my changes.
Is there a way to detach the formrecognizer pipelines from my PR?

**Comment by maririos** [comment]
created a new PR https://github.com/Azure/azure-sdk-for-net/pull/11606

**Pull request closed without merging**
