### PR TITLE
[DataFactory]Delete 1 file in Extensions dic  and add maxRowPerFile/fileNamePrefix to tabular format settings 

### PR DESCRIPTION
**Pull request by Jingshu923**
- Delete 1 file in Extensions dic: https://github.com/Azure/azure-rest-api-specs/pull/10807

- Added maxRowPerFile/fileNamePrefix to tabular format settings: https://github.com/Azure/azure-rest-api-specs/pull/10666

- add support for azure databricks delta lake:https://github.com/Azure/azure-rest-api-specs/pull/10794

### CODE REVIEW

**Comment by YalinLi0312** [comment]
Hi @Jingshu923, here have two questions:
- Why you remove the file in `src/Extenisons`? Do you restore the file in another path? Otherwise, it would cause a breaking change.
- Could you update versions in `*.csproj` and `AssemblyInfo.cs` if you are going to release?

Thanks

**Comment by Jingshu923** [comment]
Hi @YalinLi0312 , for #1 The files I deleted in src/Extenisons have been restored in src/Models dic, It will not cause break changes.
for #2 The versions has been updated in previous PR, so this PR need not update the versions.

BTW, could you response my question in my email why the models could not generate the attribute of JsonObject when model name is the same with ‘x-ms-discriminator-value’ value. e.g 'WebActivity'.

**Comment by Jingshu923** [comment]
@YalinLi0312  delete TabularPartitionOption file due swagger has delete this model and sdk has no referrences with this file, so there is no break change.

**Comment by allenjzhang** [comment]
> @YalinLi0312 delete TabularPartitionOption file due swagger has delete this model and sdk has no referrences with this file, **so there is no break change.**

Our definitions of breaking change is different. Breaking change for us means that new version will break customer's code (compile/runtime) and require user to modify the code, recompile and re-deploy. So yes, this is a breaking change for SDK even though it is intentional breaking change originated from REST API model change.

**Review by allenjzhang — APPROVED** [review]

**Pull request merged**
