### PR TITLE
Add Gallery Application API

### PR DESCRIPTION
**Pull request by koralski**

### CODE REVIEW

**Comment by erich-wang** [comment]
@koralski , could you share the Swagger spec PR link  related to this change.

**Comment by koralski** [comment]
> @koralski , could you share the Swagger spec PR link  related to this change.

https://github.com/Azure/azure-rest-api-specs/pull/6411

**Comment by erich-wang** [comment]
@koralski , please ping me after [Azure/azure-rest-api-specs#6411](https://github.com/Azure/azure-rest-api-specs/pull/6411) is merged

**Comment by koralski** [comment]
> @koralski , please ping me after Azure/azure-rest-api-specs#6411 is merged

@erich-wang the swagger spec is merged now

**Comment by erich-wang** [comment]
@koralski , please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec) to complete all 6 steps

**Comment by erich-wang** [comment]
@koralski，is this PR still valid? Please follow my previous comment to update this PR if you still need it. Otherwise I'll close it by end of next Friday.

**Comment by erich-wang** [comment]
@koralski, close this PR since no response from author for two weeks.

**Pull request closed without merging**
