### PR TITLE
Add link to ignore list

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Adding link to ignore list https://docs.microsoft.com/samples/azure/azure-sdk-for-net/share-link/
False positive by the link checker https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1101667&view=logs&j=10327055-d4d6-50a6-a312-3d2cd4bd9cb9&t=ad46a22d-116f-52e4-392d-de8aa8f403d8

### CODE REVIEW

**Comment by weshaggard** [comment]
We should try to fix the link where it is as oipposed to adding it to the ignore list.

**Comment by chidozieononiwu** [comment]
> We should try to fix the link where it is as oipposed to adding it to the ignore list.

Its actually a flase positive, not sure why it was flagged.

**Comment by weshaggard** [comment]
Where is the link being flagged as a broken link?

**Comment by chidozieononiwu** [comment]
> Where is the link being flagged as a broken link?

I really don't know. I did a local run which did not catch the link but caught other links. Ther seems to be some issues with the link checker

**Comment by weshaggard** [comment]
Is there a pipeline which has this being showed as an error?

**Comment by chidozieononiwu** [comment]
> Is there a pipeline which has this being showed as an error?

This run https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1101667&view=results
Although it seems to not be an issue in more recent runs.

**Comment by weshaggard** [comment]
That looks to be a valid link https://docs.microsoft.com/samples/azure/azure-sdk-for-net/share-link/, at least today. What I suspect happen is that maybe that site was down temporarily when that one job ran. In that case we should just close this PR as we shouldn't be adding things like that to the ignore list.

**Pull request closed without merging**
