### PR TITLE
Add support for Redis Enterprise.

### PR DESCRIPTION
**Pull request by greenms**
Swagger PR was merged: https://github.com/Azure/azure-rest-api-specs/pull/11360
Swagger: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/redisenterprise/resource-manager

### CODE REVIEW

**Comment by greenms** [comment]
I anyone able to take a look? Thanks.

**Comment by bquantump** [comment]
@greenms Please ensure all the items in this list are cheeked: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#appendix-a-pr-review-checklist

For example, there is no swagger link in here.

**Comment by greenms** [comment]
@bquantump I believe all of the items in the list are checked.  Please let me know if you discover otherwise.

**Comment by bquantump** [comment]
@greenms Is this a brand new service? That is, this is the first release of Reddis Enterprise?

**Comment by greenms** [comment]
@bquantump Yes, this is the first release of Redis Enterprise.  Our public preview started 10/31/2020.

**Comment by bquantump** [comment]
RedisEnterpriseCache

/azp run net - RedisEnterpriseCach - ci

**Comment by bquantump** [comment]
@greenms since this a new service, please add it to this file: https://github.com/Azure/azure-sdk-for-net/blob/master/eng/pipelines/mgmt.yml

**Comment by bquantump** [comment]
@weshaggard @mitchdenny 

https://dev.azure.com/azure-sdk/public/_build/results?buildId=615894&view=results

Why is this timing out? Can we bypass the timeout for now?

**Comment by weshaggard** [comment]
@bquantump it doesn't look like a timeout it looks like a unique failure on when the retry. You it a limitation in how Devops cannot publish the same artifact more then once. To workaround this I've retriggered the entire pipeline. Hopefully that will get this unblocked.

@bquantump given there are still a number of new track 1 mgmt libraries coming in that need to be added to the mgmt.yml file, you could add information about how to handle then in the check-enforcer commenting. Just submit a PR to https://github.com/Azure/azure-sdk-for-net/blob/master/eng/CHECKENFORCER#L42 with some information about how to get a pipeline working for these type of changes.

**Review by bquantump — APPROVED** [review]

**Pull request merged**
