### PR TITLE
App service generated code

### PR DESCRIPTION
**Pull request by jianghaolu**

### CODE REVIEW

**Comment by hovsepm** [comment]
Please resolve merge conflicts

**Comment by hovsepm** [comment]
"Credential scanner match found exception" in the ps1 files.

**Comment by hovsepm** [comment]
@jianghaolu 
in `src\ResourceManagement\Azure.Fluent\Microsoft.Azure.Management.Fluent\project.json` line 34     `"Microsoft.Azure.Management.AppService.Fluent": "1.0.0-beta3"` - please put a range of dependencies as other projects have.

**Comment by hovsepm** [comment]
`src\ResourceManagement\Azure.Fluent\Fluent.Tests\project.json` line 34 - `"Microsoft.Azure.Management.AppService.Fluent": "1.0.0-beta3",` same comment - please use dependency range.

**Comment by hovsepm** [comment]
@jianghaolu All assemblyInfo files in the samples should have license headers. Please fix all

**Comment by hovsepm** [comment]
`Samples\global.json` line 11 - `"../src/ResourceManagement/AppService"` you do not need to reference product library here, only sample's project -> remove `../src/` from the path.

**Comment by hovsepm** [comment]
this comment is not addressed:
@jianghaolu 
in `src\ResourceManagement\Azure.Fluent\Microsoft.Azure.Management.Fluent\project.json` line 34     `"Microsoft.Azure.Management.AppService.Fluent": "1.0.0-beta3"` - please put a range of dependencies as other projects have.

**Comment by hovsepm** [comment]
LGTM. Please fix PS1 comments and you can merge the PR.

**Comment by jianghaolu** [comment]
@anuchandy this is merged! You can merge your pr too

**Comment by anuchandy** [comment]
@jianghaolu thanks! updated TM, DNS pr - waiting for CI pass

**Pull request merged**
