### PR TITLE
[ADLA] - Adding Scope APIs/Properties, existing Catalog APIs, and existing Account APIs

### PR DESCRIPTION
**Pull request by ro-joowan**
- I did not add unit tests for anything related to Scope.  These APIs/properties are for internal use only, as noted in their descriptions, and we have internal tests for them.

### REST spec PR link to the SDK PR

- https://github.com/Azure/azure-rest-api-specs/pull/2013
- https://github.com/Azure/azure-rest-api-specs/pull/1952
- https://github.com/Azure/azure-rest-api-specs/pull/1857
- https://github.com/Azure/azure-rest-api-specs/pull/1848
- https://github.com/Azure/azure-rest-api-specs/pull/1842
- https://github.com/Azure/azure-rest-api-specs/pull/1807
- https://github.com/Azure/azure-rest-api-specs/pull/1745

### [ADLA] Changes in 3.2.3-preview

**Breaking changes**

- Changed the `ODataQuery` parameter type from `DataLakeAnalyticsAccount` to `DataLakeAnalyticsAccountBasic` for these APIs:
    - Account_List
    - Account_ListByResourceGroup
- For `USqlJobProperties`, fixed the property name of `TotalPauseTime` to `TotalPausedTime` 

**Notes**

- Added more properties to `JobStatisticsVertexStage`
- Added two more states to `DataLakeAnalyticsAccountStatus` enum: `Undeleting` and `Canceled`
- Added new Account APIs:
    - Account_CheckNameAvailability
    - Location_GetCapability
    - Operation_List
- Added new Catalog APIs:
    - Catalog_ListAclsByDatabase
    - Catalog_ListAcls
    - Catalog_GrantAclToDatabase
    - Catalog_RevokeAclFromDatabase
    - Catalog_GrantAcl
    - Catalog_RevokeAcl

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
1) Get latest updates from upstream (if you have not done so in last 3 weeks)
2) Then execute msbuild build.proj to update your build tools
3) Then regenerate your SDK (this will regenerate couple of additional files, this file is required and usually starts with SDK_*.cs
4) build you project (ether IDE or command line, this will create addition file *.props. This file is also reqired)
5) Then update your PR
With the latest changes, every regeneration will generate couple of additional meta data files that are needed in each PR.

**Comment by ro-joowan** [comment]
@shahabhijeet I followed those steps already as you noted them in my initial PR: https://github.com/Azure/azure-sdk-for-net/pull/3954

**Comment by shahabhijeet** [comment]
@ro-joowan those files required. See my previous comment where I specified which step will create which file and all those files are required.

**Comment by ro-joowan** [comment]
@shahabhijeet Thank you pointing them out in detail!  The process makes more sense now.  I have updated this PR.

**Comment by ro-joowan** [comment]
@shahabhijeet Not sure why Travis failed, is there a way to restart?

**Review by shahabhijeet — APPROVED** [review]
This PR looks good, once the CI passes this is good to be merged

**Pull request merged**
