### PR TITLE
Add Microsoft.Storage.LifecyclePolicyCompleted event

### PR DESCRIPTION
**Pull request by xioyi**

### CODE REVIEW

**Comment by ahamad-MS** [comment]
LGTM ...

**Review by ahamad-MS — APPROVED** [review]
LGTM.. Please wait for the spec PR to complete and resolve the checks issues here

**Comment by jsquire** [comment]
Hi @xioyi.  Thank you for your contribution.  Your changes were approved but there are test failures.   If you are still interested in this contribution, we'll look to get this merged once the tests are passing.

**Comment by jsquire** [comment]
Thank you for your contribution.  Since there hasn't been recent engagement, I'm going to close this out.  Please feel free to reopen if you'd like to continue working on these changes.

**Pull request closed without merging**
