### PR TITLE
Adding detailed failure event handler for DataMovement Tests and fixed Cancellation Exception event being raised unnecessarily

### PR DESCRIPTION
**Pull request by amnguye**
~I'm also trying to catch some flakey tests in this PR too.~

Fixed unrelated issue where `OperationCancelledException` was raising the `TransferFailed` Events in the TransferOptions.

### CODE REVIEW

**Comment by amnguye** [comment]
Related to https://github.com/Azure/azure-sdk-for-net/issues/35439

Looks like there might not be a test we can fully reenable due to this issue we havent fully resolved yet.
https://github.com/Azure/azure-sdk-for-net/issues/33082

**Review by jalauzon-msft — APPROVED** [review]

**Comment by amnguye** [comment]
CI failures are unrelated to the PR

**Pull request merged**
