### PR TITLE
Add api to toggle using the tag resource apis

### PR DESCRIPTION
**Pull request by m-nash**
In azure stack environments the TagResource apis will not be deployed so our convenience methods need to fallback to the PUT / PATCH methods when its not present.  This PR introduces a manual toggle as well as an automatic look up to see if the TagResource is currently available in your ArmEnvironment.

[This is an example](https://github.com/Azure/azure-sdk-for-net/pull/29379/files#diff-b3ee7301f592bdbbbd53970e5b2929df1bf351e9e3a24b144202be9d9675144fR128) of what the new body implementation would look like that autorest will create once this PR gets merged.

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by JoshLove-msft — APPROVED** [review]

**Review by JoshLove-msft — COMMENTED** [review]
Woops wrong PR, please disregard my approval :)

**Comment by m-nash** [comment]
> Woops wrong PR, please disregard my approval :)

Too late!!! :-)

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by weshaggard** [comment]
@m-nash @ArthurMa1978 PR's like this are causing a large build storm because it is triggering so many pipelines. We need to get trigger paths for these pipelines cleaned up to remove the resourcemanager path now that we have GA'ed (i.e. delete all the lines like https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/apimanagement/ci.yml#L23). And we likely need to update the resourcemanger pipeline to do a BuildFromSource job to build the other resource manager libraries as part of its pipeline. @sima-zhu has just finished the work on running the core tests in multiple jobs which I think will help address earlier concerns about amount of time it takes to run.

**Comment by m-nash** [comment]
@weshaggard these are needed the same way core runs all pipelines.  The issue tracking this is here https://github.com/Azure/azure-sdk-for-net/issues/27703 I will let @ArthurMa1978  comment on timeline when he is back.

**Comment by weshaggard** [comment]
We have implemented the support needed for https://github.com/Azure/azure-sdk-for-net/pull/30106 so we should now be able to tackle https://github.com/Azure/azure-sdk-for-net/issues/27703. We should try to do that ASAP as the number of pipelines that are getting triggers is stressing our agent pool.

**Comment by sima-zhu** [comment]
Will help resource manager onboard with the new splitting framework.

**Pull request merged**
