### PR TITLE
Move to .NET Core 3.0 rc 1 toolset

### PR DESCRIPTION
**Pull request by weshaggard**
@chidozieononiwu @pakrym I'm testing out a move to rc1 toolset to move us forward as well as to see if it helps with https://github.com/Azure/azure-sdk-for-net/issues/7490.

### CODE REVIEW

**Comment by weshaggard** [comment]
Well I hit the #7490 on the first try with the new sdk so that doesn't seem to help. I'll keep trying things to see if I can figure out what is going wrong.

**Comment by pakrym** [comment]
Let's still merge this if it passes. Doesn't hurt to be ready for RTM.

**Comment by weshaggard** [comment]
@pakrym .NET Core 3.0 GA is next monday so I think we should wait until then to update the toolset to the GA version.

**Comment by pakrym** [comment]
People who update dogfood VS see the errors that you've fixed in this PR in local builds

**Comment by weshaggard** [comment]
>People who update dogfood VS see the errors that you've fixed in this PR in local builds

I agree we will get this fixed next week. I'm not even sure that disabling that warning is the best way to fix this issue yet.

**Pull request closed without merging**
