### PR TITLE
[Datafactory] Enable Excel SDK

### PR DESCRIPTION
**Pull request by yuzhangyi**

### CODE REVIEW

**Comment by yuzhangyi** [comment]
@isra-fel and @erich-wang could you help review and merge this change into sdk? thanks!

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @yuzhangyi , could you
- put a link to your openapi spec review PR here
- we often combine code generation and version bump up in one PR, could you follow our guideline to update versions and release notes, if you decide to publish the packge afterwards https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#signing-and-publishing-nuget-packges

Thanks

**Comment by yuzhangyi** [comment]
> * en combine code generation and version bump up in one PR, could you follow our guideline to update versions and release notes, if you decide to publish the packge afterwards

@isra-fel ,related swagger change is here: https://github.com/Azure/azure-rest-api-specs/pull/8875

**Comment by yuzhangyi** [comment]
> > * en combine code generation and version bump up in one PR, could you follow our guideline to update versions and release notes, if you decide to publish the packge afterwards
> 
> @isra-fel ,related swagger change is here: [Azure/azure-rest-api-specs#8875](https://github.com/Azure/azure-rest-api-specs/pull/8875)

@isra-fel  and @erich-wang, could you help merge my change? Thanks

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
