### PR TITLE
Added AmbiguousMatchException exception handling in telemetry

### PR DESCRIPTION
**Pull request by hovsepm**
Fix for https://github.com/Azure/azure-libraries-for-net/issues/24
Fix for https://github.com/Azure/autorest/issues/1542

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@hovsepm as we talked earlier in person, this PR is missing a repro test.
Once you have a repro test, please reopen this PR.
I still feel this error is a side effect of an external dependency and has nothing to do with our ClientRuntime.
Doing the fix that you have suggested will make our telemetry not send data as it will swallow the exception.
But let's revisit this once you have a repro test.
Closing it for now.

**Comment by hovsepm** [comment]
@shahabhijeet I'm not clear on how to have a repro steps of a broken environment on the VM. Can you suggest any?

**Comment by hovsepm** [comment]
@shahabhijeet we have same logic (catch ambiguous exception) just in the method above - https://github.com/Azure/azure-sdk-for-net/pull/3752/files#diff-c5d340c5463828f90b80c7ec9d43162aL185  So this PR adds consistency in behavior.

**Comment by hovsepm** [comment]
@shahabhijeet PR failure is because there is no way to upgrade the ClientRuntime version and reference the new CR in the tests. Do you suggest opening 2 PRs - one for version upgrade and fix and the other one with CR version upgrade on the dependent projects?

**Comment by shahabhijeet** [comment]
@hovsepm I am closing this. Let's talk before you reopen this PR.

**Pull request closed without merging**
