### PR TITLE
Bug fix and small perf improvement to MJD WriteTo()

### PR DESCRIPTION
**Pull request by annelo-msft**
This PR addresses a few outstanding issues in https://github.com/Azure/azure-sdk-for-net/issues/33856
- Fixes a bug in MutableJsonDocument.WriteTo() wrt format parameter
- Makes MutableJsonDocument.WriteTo(Utf8JsonWriter) public, to enable perf work
- Makes a small perf improvement for writing primitive values in MutableJsonElement.WriteTo()
- Removes ToArray() call in Parse(BinaryData) 🤦🏻‍♀️

Addresses https://github.com/Azure/azure-sdk-for-net/issues/33856

### CODE REVIEW

**Review by heaths — APPROVED** [review]
The changes look good sans context, but I have to admit seeing the change to use `ReadOnlyMemory<byte>` threw me a bit for something called "mutable". With tests passing, and because you're using `WriteTo` to write to another stream (or throw), I see no reason to block.

**Review by jsquire — APPROVED** [review]

**Review by christothes — APPROVED** [review]

**Comment by annelo-msft** [comment]
> I have to admit seeing the change to use ReadOnlyMemory<byte> threw me a bit for something called "mutable". 

That makes sense!  The thinking is -- we never make changes to the original JSON buffer -- instead, changes are held in the changelist and any reads/serialization operations consult the changelist prior to returning a value.

**Comment by heaths** [comment]
@annelo-msft thanks for the explanation. I hadn't really been following the development of this part of the JSON-related code, but seems pretty handy. From your tests, seems it can also serialize/format a JSON merge+patch, yeah?

**Comment by annelo-msft** [comment]
>  From your tests, seems it can also serialize/format a JSON merge+patch, yeah?

Not today, but that is definitely on our roadmap!  The changelist approach should enable that without a lot of addition.

**Pull request merged**
