### PR TITLE
updated chaos SDK and tests

### PR DESCRIPTION
**Pull request by brrusino**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by archerzz — CHANGES_REQUESTED** [review]
- There are a few single-word classes (`Action`, `Filter`, `Selector`...) generated. Please give more specific names for them.
- The breaking changes in API signature is fine, since the SDK is still in beta release.
- Need to re-record some tests which are failing probably due to code changes.

**Comment by brrusino** [comment]
@archerzz can you please take another look at this PR?

**Comment by archerzz** [comment]
> > * There are a few single-word classes (`Action`, `Filter`, `Selector`...) generated. Please give more specific names for them.
> > * The breaking changes in API signature is fine, since the SDK is still in beta release.
> > * Need to re-record some tests which are failing probably due to code changes.
> 
> @archerzz Thanks for the response! Regarding the above:
> 
> 1. Is there standardized Azure guidance around use of single-word class names? If not, we will likely leave these as-is unless there is a reasonable way to modify for .NET SDK class names only (not altering the open API spec).
> 2. Sound good, thanks for the heads-up.
> 3. Yep, we're taking care of this. This is our first SDK update after the migration to using the Test Proxy, so we need write access to that repository before we can push our test recordings. Should be sorted out in the next day or so.

@brrusino For 1, yes it's the general review guidelines to avoid naming conflict between SDKs. And more specific names help users understand the intent of the types.

**Comment by brrusino** [comment]
> > > * There are a few single-word classes (`Action`, `Filter`, `Selector`...) generated. Please give more specific names for them.
> > > * The breaking changes in API signature is fine, since the SDK is still in beta release.
> > > * Need to re-record some tests which are failing probably due to code changes.
> > 
> > 
> > @archerzz Thanks for the response! Regarding the above:
> > 
> > 1. Is there standardized Azure guidance around use of single-word class names? If not, we will likely leave these as-is unless there is a reasonable way to modify for .NET SDK class names only (not altering the open API spec).
> > 2. Sound good, thanks for the heads-up.
> > 3. Yep, we're taking care of this. This is our first SDK update after the migration to using the Test Proxy, so we need write access to that repository before we can push our test recordings. Should be sorted out in the next day or so.
> 
> @brrusino For 1, yes it's the general review guidelines to avoid naming conflict between SDKs. And more specific names help users understand the intent of the types.

@archerzz We now [have an active azure-rest-api-spec PR](https://github.com/Azure/azure-rest-api-specs/pull/25708/commits/71b1ed9498cda06bd5a2dfec8eec52678f8d07b5) with appropriate `x-ms-client-name` usage to rename these classes appropriately:
 Action -> ChaosExperimentAction
Branch -> ChaosExperimentBranch
Step -> ChaosExperimentStep
Filter -> ChaosTargetFilter
Selector -> ChaosTargetSelector

With that said, can we allow the class names in this SDK version as-is, knowing that the next version will include these renamed classes?

**Comment by archerzz** [comment]
> > > > * There are a few single-word classes (`Action`, `Filter`, `Selector`...) generated. Please give more specific names for them.
> > > > * The breaking changes in API signature is fine, since the SDK is still in beta release.
> > > > * Need to re-record some tests which are failing probably due to code changes.
> > > 
> > > 
> > > @archerzz Thanks for the response! Regarding the above:
> > > 
> > > 1. Is there standardized Azure guidance around use of single-word class names? If not, we will likely leave these as-is unless there is a reasonable way to modify for .NET SDK class names only (not altering the open API spec).
> > > 2. Sound good, thanks for the heads-up.
> > > 3. Yep, we're taking care of this. This is our first SDK update after the migration to using the Test Proxy, so we need write access to that repository before we can push our test recordings. Should be sorted out in the next day or so.
> > 
> > 
> > @brrusino For 1, yes it's the general review guidelines to avoid naming conflict between SDKs. And more specific names help users understand the intent of the types.
> 
> @archerzz We now [have an active azure-rest-api-spec PR](https://github.com/Azure/azure-rest-api-specs/pull/25708/commits/71b1ed9498cda06bd5a2dfec8eec52678f8d07b5) with appropriate `x-ms-client-name` usage to rename these classes appropriately: Action -> ChaosExperimentAction Branch -> ChaosExperimentBranch Step -> ChaosExperimentStep Filter -> ChaosTargetFilter Selector -> ChaosTargetSelector
> 
> With that said, can we allow the class names in this SDK version as-is, knowing that the next version will include these renamed classes?

Sure. Do you want to release a new beta version? If so, don't forget to update `CHANGELOG.md`.

**Review by archerzz — APPROVED** [review]

**Review by archerzz — APPROVED** [review]

**Review by archerzz — APPROVED** [review]

**Pull request merged**
