### PR TITLE
[OperationalInsights] Fix the deserialization issue caused by the outdated Swagger version

### PR DESCRIPTION
**Pull request by dvbb**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by archerzz — APPROVED** [review]

**Comment by dvbb** [comment]
@microsoft-github-policy-service rerun

**Comment by alvaro-vantis-pt** [comment]
Is there any workaround for this issue while we wait by this fix availability?

**Comment by alvaro-vantis-pt** [comment]
> Is there any workaround for this issue while we wait by this fix availability?

I found a workaround. I encapsulated http request described [here](https://learn.microsoft.com/en-us/rest/api/loganalytics/tables/create-or-update?view=rest-loganalytics-2022-10-01&tabs=HTTP) in a class and created my own set of classes to serialize/deserialize json related objects.

**Pull request merged**
