### PR TITLE
AutoPr-Blueprint-filizt-REST Spec PrNumber 5535

### PR DESCRIPTION
**Pull request by adxsdknet**

### CODE REVIEW

**Comment by dsgouda** [comment]
@filizt is this good to be merged?

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by filizt** [comment]
> @filizt is this good to be merged?

@dsgouda we don't want to merge this change. I still need to create a new PR for our SDK after adding our customizations.

**Comment by dsgouda** [comment]
Thanks for confirming. Will close this PR.

**Pull request closed without merging**
