### PR TITLE
Generate XML documentation for all libraries.

### PR DESCRIPTION
**Pull request by twitchax**
## Description
This PR adds `"xmlDocs": "true"` to all `project.json` files for shipping client libraries.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as a link to the swagger spec, used to generate the code.
- [ ] The `project.json` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by twitchax** [comment]
Should I go ahead and peg the patch version in each project.json I touched?

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
unable to find the build job for this PR, restarting CI

**Comment by shahabhijeet** [comment]
@twitchax I spot checked couple of nugets, I do not see any .xml files inside nuget.
Possibility they do not have any xml comments inside their code or package step fails to include it in the nuget package. I cannot verify this as I was not able to log onto the CI machine due to password change or possibly, old user do not have access on the new CI machine yet.
Please verify if the nuget packages that you generate locally has .xml files

**Comment by twitchax** [comment]
@shahabhijeet, which ones did you spot check?

**Comment by shahabhijeet** [comment]
Verify by running msbuild build.proj /t:"Build;Package" locally.

**Comment by shahabhijeet** [comment]
@twitchax ok my bad, I checked data plane packages and forgot the change was for management plane. Yes now I can see the files.

**Comment by twitchax** [comment]
Awesome: thanks!  #2989 is almost the same thing, by the way. :)

**Pull request merged**
