### PR TITLE
Fix Quantum Jobs Readme issues

### PR DESCRIPTION
**Pull request by v-yilinhu**
Fix issue https://github.com/Azure/azure-sdk-for-net/issues/20213

@scottaddie , @AlexGhiondea , @vxfield and @jongio for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@jongio Who should we ping to review this PR?

**Review by vxfield — APPROVED** [review]

**Comment by v-xuto** [comment]
@vxfield - Please help us merge this PR.

**Comment by vxfield** [comment]
Hi @v-xuto, since this PR touches other service SDKs, I'm not comfortable in merging this PR before the other service owners approving it.
Ideally you should create one PR per service and them they can be reviewed/approved/merged on a per service basis.
I can only approve/merge for the quantum service...

**Comment by v-yilinhu** [comment]
@vxfield I've finished modifying it. Now there's only quantum service, can you help us merge this PR?

**Comment by vxfield** [comment]
Great. Thank you!

**Pull request merged**
