### PR TITLE
RetryExponential in EventHub can return invalid values

### PR DESCRIPTION
**Pull request by christothes**
# Summary
`ComputeRetryFactor` will return a negative value if the calculated value `Math.Log(deltaBackoff)` is negative.

### CODE REVIEW

**Review by serkantkaraca — APPROVED** [review]
Looks good. Thx for fixing this.

**Comment by diogorolo** [comment]
While this prevents the error, with this fix the Retry period is no longer exponential. Setting the retry factor = 0 makes it so that all the retries have the same delta backoff (equal to the minimum value).

**Comment by diogorolo** [comment]
Should all the calculations be made in the smallest unit, is this case milliseconds?
At the moment, we're saying that the RetryExponential does not support smaller than second differences between minimumBackoff and maximumBackoff (and if that's the case, shouldn't a exception be thrown when setting those invalid values? instead of falling back to a Retry mode that's not exponential)

**Comment by christothes** [comment]
> Should all the calculations be made in the smallest unit, is this case milliseconds?
> At the moment, we're saying that the RetryExponential does not support smaller than second differences between minimumBackoff and maximumBackoff (and if that's the case, shouldn't a exception be thrown when setting those invalid values? instead of falling back to a Retry mode that's not exponential)

Thanks for reviewing! I had the same question, but when I encountered the logic in the line below inside `RetryPolicy` it made me question whether that level of granularity was intentionally avoided. Practically speaking, I'm not sure it has significant impact.

Do any of the reviewers have any insight into how `ClientConstants.TimerToleranceInSeconds` was selected? 

https://github.com/Azure/azure-sdk-for-net/blob/5e8206d4875d08087d411672d540680c8a04bd20/sdk/eventhub/Microsoft.Azure.EventHubs/src/Primitives/RetryPolicy.cs#L100

Regarding the exception behavior, do you feel like this enforcement would be worth the breaking change for existing consumers?

**Comment by serkantkaraca** [comment]
Most clients today run with default RetryExponential policy which calculates deltaBackoff as 30 seconds. I don't really expect many clients running with deltaBackoff smaller than a second.

I believe having calculations at millisecond levels won't mean much for a client making service calls over network.

**Comment by serkantkaraca** [comment]
> Do any of the reviewers have any insight into how `ClientConstants.TimerToleranceInSeconds` was selected?

I think that is legacy from old SDK where we stop retrying if remaining time is not meaningful enough like in this case 5 seconds.

**Comment by jsquire** [comment]
@serkantkaraca:  It looks like this has been stable for a bit; do you mind if I merge or are we waiting on something further?

**Pull request merged**
