### PR TITLE
[Search] Remove all instances of [IgnoreOnNet5]

### PR DESCRIPTION
**Pull request by Mohit-Chakraborty**

### CODE REVIEW

**Comment by Mohit-Chakraborty** [comment]
fixes #16963

**Review by pakrym — APPROVED** [review]

**Comment by pakrym** [comment]
Can you remove the attribute as well? I don't think anyone else used it.

**Comment by Mohit-Chakraborty** [comment]
> Can you remove the attribute as well? I don't think anyone else used it.

It is also being used in [[KV](https://github.com/Azure/azure-sdk-for-net/blob/c3a14a5257f2a4254e31260dd650dff652c4fefc/sdk/keyvault/Azure.Security.KeyVault.Keys/tests/AesCryptographyProviderTests.cs#L141)].

**Pull request merged**
