### PR TITLE
Converted app gateway sample

### PR DESCRIPTION
**Pull request by martinsawicki**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@martinsawicki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (marcins). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
LGTM

**Comment by hovsepm** [comment]
> using System.Reflection;

Please add license header. 

---
Refers to: Samples/ResourceManagement/Network/ManageApplicationGateway/Properties/AssemblyInfo.cs:1 in 8d2da64. [](commit_id = 8d2da644653dd5e7e082376642153e393286efbe, deletion_comment = False)

**Comment by martinsawicki** [comment]
added license headers to this and also some files in sql samples

**Comment by hovsepm** [comment]
@martinsawicki please pull from upstream and resolve build breaks. Jianghao changed country codes and I've merged his PR already. Please pull from your fork first since I've fixed merge conflicts in your PR directly from github webpage.

**Comment by hovsepm** [comment]
@martinsawicki please ignore my previous comment. The build break is not related to your code.

**Pull request merged**
