### PR TITLE
Create end-to-end sample for an indexer

### LINKED ISSUE #12518: Additional end-to-end tests
We want to have at least one good end-to-end example of creating skillsets attached to an indexer to populate an index, and query it for that enrichment information.

For skillsets, I propose common examples like one or more of the following:
- ~Sentiment analysis on reviews (perhaps a movie example like some languages used for their UX studies, though paired with a user rating it's not clear how much value this adds outside an example)~
- ~Image extraction and recognition (perhaps recognize celebrities, which goes along nicely with the movie example if we do it base solely on movie posters)~

The rest of the sample would include:
- [x] Creating an index
- [x] Setting up and populating a data source container
- [x] Setting up an indexer to pull from that container into the index with at least one field mapping
- [x] Manually running the indexer as a matter of coverage
- [x] Getting a query client from the index client
- [x] Querying for a result containing our enriched data

### PR DESCRIPTION
**Pull request by heaths**
Includes AI enrichments. Fixes #12518

### CODE REVIEW

**Comment by heaths** [comment]
I added .gitattributes to force line endings to use LF:

```
countries.txt text eol=lf
```

All tests passed on my machine. However, on Windows agents it still got checked out to the working directory with CRLF. Upon checking this branch back out (I had switch to another branch without this file), it's checked out with CRLF again. <https://www.git-scm.com/docs/gitattributes#_effects> confirms this should've worked. I may instead have to implement a `TextReader` to normalize line endings across platforms.

**Comment by heaths** [comment]
@weshaggard is this change fine to add a line to .gitattributes? Originally I tried a file in a subdirectory but later remembered that only works for .gitignore. I need to force the line endings to LF. If not, I could write a TextReader that normalizes the line endings while the file stream is being read, but this easier to maintain.

**Comment by heaths** [comment]
I could also just "pretend" to read from a file for the sample's purpose, and in a line prepended with `/*@@*/` that our sample code extractor will ignore, actually pull from a C# string literal that would be delimited by `\n` only. It would be nice - though not required - if we actually read from a file, though, in case customers actually look at the full sample source.

**Comment by weshaggard** [comment]
If we can eliminate the LF requirement that would be ideal but if we cannot it would be nice to keep the workaround scoped to the sample so that the sample is more portable for others that might want to consume it outside of our repo. Barring that working nicely then I'd be OK with the gitattributes change given it shouldn't impact anything else.

**Comment by heaths** [comment]
Portability is a good concern. I wouldn't expect customers to copy the full sample, but if we were to reorg the sample directory structure it would break, and figuring out why the tests all of a sudden fail wouldn't be very intuitive. I'll consider one of the alternatives.

**Review by bleroy — APPROVED** [review]

**Pull request merged**
