### PR TITLE
Move X509Certificate2 module to eng/common

### PR DESCRIPTION
**Pull request by benbp**
Moving the x509 module to azure-sdk-tools eng/common in https://github.com/Azure/azure-sdk-tools/pull/6543

CC @christothes

### CODE REVIEW

**Review by christothes — APPROVED** [review]

**Review by heaths — CHANGES_REQUESTED** [review]
You should replace https://github.com/Azure/azure-sdk-for-net/blob/c13edd04867d8a5e0c91a3b2a67bdc4350390f2f/sdk/keyvault/test-resources-post.ps1#L32-L88 with what you did for confidentialledger as well. This is where my module came from originally, which was then copied to eng/scripts and you've now copied to eng/common/scripts (effectively).

**Review by heaths — APPROVED** [review]
Maybe should run `net - keyvault - tests-weekly`, but it'll likely fail on one particular sovereign cloud, showing a broken check (or more). Could merge regardless. Your call. We can always wait and see next week after the weekly run.

**Comment by benbp** [comment]
Running weekly but skipping china: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2946884&view=results

**Review by heaths — APPROVED** [review]

**Pull request merged**
