### PR TITLE
Update ARM generate.cmd

### PR DESCRIPTION
**Pull request by vivsriaus**

### CODE REVIEW

**Comment by TianoMS** [comment]
Looks good to me.

**Comment by markcowl** [comment]
@vivsriaus why haven't any of the generated files been changed for the new spec version  target?

**Comment by markcowl** [comment]
@vivsriaus ping?  Where are the file changes for this spec update?

**Comment by vivsriaus** [comment]
@markcowl This is for the [PR ](https://github.com/Azure/azure-sdk-for-net/pull/2312) that was already merged. I didn't include the changes to generate.cmd in that PR, so had to do this separately.

This way, we'll ensure that the next time we update our other clients (Resources, Feature, Policy and Locks), we use the updated autorestclient in this cmdfile.

**Pull request merged**
