### PR TITLE
Add note about preview text analytics sdk to track1 readme

### LINKED ISSUE #9383: Update information about TA preview 1 in TA track1 documentation

### PR DESCRIPTION
**Pull request by maririos**
Fixes #9383

### CODE REVIEW

**Review by samvaity — APPROVED** [review]

**Review by mssfang — APPROVED** [review]

**Comment by maririos** [comment]
Legs are failing because of a validation check from eng services team.
@chidozieononiwu is looking into it

**Comment by bingisbestest** [comment]
> Legs are failing because of a validation check from eng services team.
> @chidozieononiwu is looking into it

Any update on the fix ? my pr is also affected : https://github.com/Azure/azure-sdk-for-net/pull/9375

**Comment by chidozieononiwu** [comment]
> > Legs are failing because of a validation check from eng services team.
> > @chidozieononiwu
> >             
> >             Dozie Ononiwu
> >             FTE is looking into it
> 
> Any update on the fix ? my pr is also affected : #9375

#9392 is up to fix this. Cannot test against the PR because of an issue that DevOps developed yesterday. But that should fix it.

**Comment by maririos** [comment]
@chidozieononiwu is it ok to merge this PR then?

**Comment by chidozieononiwu** [comment]
Changes have been included in https://github.com/Azure/azure-sdk-for-net/pull/9410

**Pull request closed without merging**
