### PR TITLE
[Automation] New SDK for 2018-06-30 changes and other nit fixes

### PR DESCRIPTION
**Pull request by jemex**
## Description
1. Python2Packages for azure automation. Added new API specs, re-recorded tests for Automation scenarios. Added a new test for Python2Package scenarios.
API PR: https://github.com/Azure/azure-rest-api-specs/pull/3713

2. Dynamic Group support change 
API PR :  https://github.com/Azure/azure-rest-api-specs/pull/4165
3. Pre- post support change
API PR :  https://github.com/Azure/azure-rest-api-specs/pull/4298

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by dsgouda** [comment]
1. Please provide a meaningful title for the PR
2. Looks like you are bumping the REST API version, this would require major version bumps for the nuget package in csproj and AssemblyInfo.cs files

**Comment by jemex** [comment]
@dsgouda - Thanks for the catch. I've updated the files you mentioned. Could you please take a look?

@vrdmr FYI.

**Review by dsgouda — CHANGES_REQUESTED** [review]
@jemex this looks like a stable API version. We recommend publishing stable Nuget packages for stable API versions and preview Nuget packages for preview API versions.
Please consider publishing a stable Nuget version here.
Also, please squash commits into a single commit (this may require recreating the branch with these changes)

**Review by dsgouda — CHANGES_REQUESTED** [review]
Why was `tools/PS-VSPrompt.lnk` added?
Please remove this file if not required

**Comment by D1v38om83r** [comment]
@dsgouda can't we just squash the commits while merging? its way more efficient than having to rebase.

**Comment by dsgouda** [comment]
If changes from a remote have been merged the squash is not very effective

**Comment by D1v38om83r** [comment]
changes have been squashed and changes to tools/PS-VSPrompt.lnk have been reverted

**Comment by dsgouda** [comment]
@D1v38om83r Do you still plan to release a preview Nuget package?

**Comment by jemex** [comment]
@dsgouda - can you please answer @vrdmr question? we are waiting to address the feedback and merge the change

**Comment by vrdmr** [comment]
@dsgouda Ping

**Comment by dsgouda** [comment]
@vrdmr @jemex Talked to @shahabhijeet and our recommendation is to change the version here to `3.8.0-preview`. That way if you plan to publish some changes to the previous API version you'll still have bandwidth upto `3.7.0-preview` to publish those changes and whenever you plan to release a stable version for the Nuget package you can simply start with `4.0.0`.

**Comment by D1v38om83r** [comment]
@dsgouda do we need to make any changes at our end after your commits?

Is the PR good to go? I have made the change you asked for "Why was tools/PS-VSPrompt.lnk added?
Please remove this file if not required" in this commit https://github.com/Azure/azure-sdk-for-net/pull/4916/commits/5db0efc7c054b7258a73b7a6ae23fff1069c43f2

**Comment by dsgouda** [comment]
@D1v38om83r like I mentioned please set the version to `3.8.0-preview` in the csproj and in the `AssemblyInfo.cs` file
Also, squash the commits and this PR is good to merge

**Comment by D1v38om83r** [comment]
Changed the versions and squashed the commits.

**Comment by dsgouda** [comment]
@jemex there are a lot of unrelated changes introduced, please sync the branch correctly with remote psSdkJson6, we can get on an offline chat if you need help

**Comment by jemex** [comment]
@dsgouda, if we had not  squashed the commits before the final approval, we would have easier to fix this . now we have to go through 268 files to see what changes are unrelated. can you please help us on Friday or Monday to fix this?

**Comment by dsgouda** [comment]
There is a simple way to do it.
1. Copy all the files you have modified in a temp location outside the repo
2. Checkout psSdkJson6 branch, pull latest changes from remote (git pullhttps://github.com/Azure/azure-sdk-for-net.git psSdkJson6)
3. Create a new branch (git checkout -b branch_name)
4. Copy over the changes from temp location to this branch
5. Push this branch to remote (git push upstream branch_name)
6. Close this PR and open a new PR with the new branch and reference this PR there

Hope this helps

**Comment by D1v38om83r** [comment]
Closing this PR, new PR is here https://github.com/Azure/azure-sdk-for-net/pull/4971

**Comment by jemex** [comment]
Closing this PR, we have new PR in https://github.com/Azure/azure-sdk-for-net/pull/4971

**Pull request closed without merging**
