### PR TITLE
Anh/2023 support

### PR DESCRIPTION
**Pull request by lomagdal2**
Changelist:
Uses RP API Version 2023-10-01-preview
Adds support for Private Link
Adds support for FCM V1 platform
Adds support for Browser platform
Adds support for Xiaomi platform
This PR replaces https://github.com/Azure/azure-sdk-for-net/pull/43105 because the author has left the team.

### CODE REVIEW

**Comment by lomagdal2** [comment]
Hello @ArthurMa1978. I see that you were helping us with this work previously. Can you help us move this PR forward? What do we need to do next?

**Comment by lomagdal2** [comment]
Hello @m-nash! We need to move this PR forward. Can you help me understand what our next steps are to getting this merged in?

**Comment by ArthurMa1978** [comment]
Hey @lomagdal2 , please follow the https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/TestGuide.md to re-record the failed test cases.

**Comment by lomagdal2** [comment]
@ArthurMa1978 i have re-recorded the test cases and pushed them up

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
