### PR TITLE
Planned maintenance - package - 2023 - 10

### PR DESCRIPTION
**Pull request by adana-popescu**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by archerzz — CHANGES_REQUESTED** [review]
A couple of things.

## Track1 SDK is deprecated

We're not supposed to release new versions of Track1 SDK without exemption. CC @ArthurMa1978 

## Need to update some Track1 SDK metadata

Make sure you update the following files, according to [the guide](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=track-1-sdk-generation-from-updated-spec).

- `AzSDK.RP.Props`: https://github.com/Azure/azure-sdk-for-net/blob/6bc542b5d1ec2e896a956a475be0c14c4927b466/sdk/maintenance/Microsoft.Azure.Management.Maintenance/AzSdk.RP.props#L4
- `eng\mgmt\mgmtmetadata\<rpName>.txt`: https://github.com/Azure/azure-sdk-for-net/blob/main/eng/mgmt/mgmtmetadata/maintenance_resource-manager.txt
- `.csproj`: https://github.com/Azure/azure-sdk-for-net/blob/6bc542b5d1ec2e896a956a475be0c14c4927b466/sdk/maintenance/Microsoft.Azure.Management.Maintenance/src/Microsoft.Azure.Management.Maintenance.csproj#L9
- `AssemblyInfo.cs`: https://github.com/Azure/azure-sdk-for-net/blob/6bc542b5d1ec2e896a956a475be0c14c4927b466/sdk/maintenance/Microsoft.Azure.Management.Maintenance/src/Properties/AssemblyInfo.cs#L18

## Test recording

Test recording seems out-of-date (see the error log). Please update it. Thanks.

**Comment by ArthurMa1978** [comment]
@adana-popescu track 1 is being deprecated, so we need to close this pr.

**Comment by adana-popescu** [comment]
From what I understand, I will need the Track 1 changes for the Powershell module. 
I currently cannot update the tests because I'm waiting for a PR with Swagger changes to merge. Will update the rest of the files.
@ArthurMa1978 @archerzz

**Comment by adana-popescu** [comment]
Hi @archerzz !

As requested, I've updated the versions in some of the files you mentioned, with the exception of:
- `eng\mgmt\mgmtmetadata\<rpName>.txt` - I couldn't update this file as running `generate.ps1` first requires the swagger changes to be merged to the public repo. Once that is done I'll update it.
- `AssemblyInfo.cs` - as per the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=track-1-sdk-generation-from-updated-spec), this file should only be updated "If it's a major version update (e.g. from 1.2.3.0 to 2.0.0.0)". It's not very clear to me if I should actually update it or not for this PR, can you please confirm if the AssemblyFileVersion needs to be updated?

**Comment by archerzz** [comment]
> Hi @archerzz !
> 
> As requested, I've updated the versions in some of the files you mentioned, with the exception of:
> 
> * `eng\mgmt\mgmtmetadata\<rpName>.txt` - I couldn't update this file as running `generate.ps1` first requires the swagger changes to be merged to the public repo. Once that is done I'll update it.
> * `AssemblyInfo.cs` - as per the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=track-1-sdk-generation-from-updated-spec), this file should only be updated "If it's a major version update (e.g. from 1.2.3.0 to 2.0.0.0)". It's not very clear to me if I should actually update it or not for this PR, can you please confirm if the AssemblyFileVersion needs to be updated?

@adana-popescu For `assemblyInfo.cs`, it depends on whether there is any breaking change in the SDK API. I quickly browse the changes, and it looks fine. So this PR is a minor change.

BTW, could you update test recordings? You've added test cases but the corresponding recordings are missing. Thanks.

**Comment by adana-popescu** [comment]
Closing this as it is no longer needed for PowerShell. Thank you!

**Pull request closed without merging**
