### PR TITLE
Update the env variable we use to be the default value used by Azure.…

### PR DESCRIPTION
**Pull request by azabbasi**
…Core

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Review by bikamani — APPROVED** [review]

**Comment by azabbasi** [comment]
azp run net - digitaltwins - tests, net - iot - tests

**Review by abhipsaMisra — APPROVED** [review]

**Review by drwill-ms — APPROVED** [review]

**Review by vinagesh — APPROVED** [review]

**Pull request merged**
