### PR TITLE
[Farmbeats] Initial Package Generation

### PR DESCRIPTION
**Pull request by ellismg**
Scaffold out the project and run the code generator based off what is in `azure-rest-api-specs` today.

### CODE REVIEW

**Comment by ellismg** [comment]
(We should have clarity on the package namespace and group tomorrow, at which point I will make any needed changes and generate the pipelines)

**Review by chamons — APPROVED** [review]

**Comment by jianghaolu** [comment]
Should it be `AgirFood` or `AgriFood`?

**Comment by ellismg** [comment]
Eep!  Thanks for catching my typo here, @jianghaolu, you are correct it should be `AgriFood`

**Comment by ramya-rao-a** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/14408 was merged only today though...

**Comment by ellismg** [comment]
> Azure/azure-rest-api-specs#14408 was merged only today though...

Yup.  @lmazuel pointed it out to us this morning so I proactively did the regeneration before landing this.

**Pull request merged**
