### PR TITLE
Move the tests for Azure.Core to XUnit

### PR DESCRIPTION
**Pull request by AlexGhiondea**
This will move from NUnit to XUnit for the tests we have for Azure.Core. This matches the standard for this repo.

### CODE REVIEW

**Review by KrzysztofCwalina — APPROVED** [review]
looks good.

**Comment by maririos** [comment]
Not sure if we still want this according to what @mikeharder was saying yesterday in our teams channel.

**Comment by mikeharder** [comment]
I would leave the tests in NUnit for now, until we decide if we want to standardize on XUnit.

**Comment by AlexGhiondea** [comment]
Yeah -- I'll close this PR for now until we decide on what we want.

**Comment by weshaggard** [comment]
FWIW our build-pipeline currently only indexes xunit test results so these tests will not be indexed by devops.

**Comment by weshaggard** [comment]
Correction I think that might only be necessary if we PublishTestResults directly https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml, however we don't need to do that the way we are currently using the DotNetCoreCLI task to run the tests. At any rate we should just be cautious that we don't drop any results if we mix the different testing frameworks.

**Pull request closed without merging**
