### PR TITLE
Remove experimental from profile session tag

### PR DESCRIPTION
**Pull request by pharring**
The OpenTelemetry profiling data model spec has been merged: https://github.com/open-telemetry/oteps/pull/239
This confirms the use of the "profile_id" tag to link from spans to profiles.
We can now drop the "_experimental" suffix from the tag we write in ProfilingSessionTraceProcessor.

### CODE REVIEW

**Comment by pallavit** [comment]
@pharring:

You are missing the needed permissions and public group memberships for an internal contributor. Please review the Azure SDK onboarding documentation and use the onboarding teams channel for any questions.

[Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) (Microsoft internal)
[Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) (Microsoft internal)
Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

**Comment by TimothyMothra** [comment]
LGTM. 

Let me sync with Raj since he has more context on this.
But this is a very small change, I think we can get this merged today.

**Comment by rajkumar-rangaraj** [comment]
> The OpenTelemetry profiling data model spec has been merged: https://github.com/open-telemetry/oteps/pull/239
oteps is not a spec repository; it’s one step behind the spec. Initial ideas are discussed here, then they move to the spec. Should we remove the experimental flag based on this?

**Comment by TimothyMothra** [comment]
@rajkumar-rangaraj looks like the original PR didn't update the Changelog. https://github.com/Azure/azure-sdk-for-net/pull/41594

@pharring how would you like this feature described in our changelog?

**Comment by pharring** [comment]
@TimothyMothra, I added a line in the CHANGELOG about removing the experimental suffix. As for documenting the original feature, is it OK to retro-actively add it to the CHANGELOG? Given the timeline, I think it would go in 1.1.0.

**Comment by pharring** [comment]
@TimothyMothra looks like this missed the last beta. Can we get it in now?

**Comment by rajkumar-rangaraj** [comment]
> > The OpenTelemetry profiling data model spec has been merged: [open-telemetry/oteps#239](https://github.com/open-telemetry/oteps/pull/239)
> 
> oteps is not a spec repository; it’s one step behind the spec. Initial ideas are discussed here, then they move to the spec. Should we remove the experimental flag based on this?

@pharring Review was pending on this question.

**Comment by pharring** [comment]
Oh, I see. Sorry.

**Pull request closed without merging**
