### PR TITLE
Update ubuntu VMImage

### PR DESCRIPTION
**Pull request by chidozieononiwu**

### CODE REVIEW

**Review by mikeharder — APPROVED** [review]
Approved once all checks are passing

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
looks like a few batch tests are failing so triggering a batch run just to confirm.

**Comment by weshaggard** [comment]
Also based on our issue in java I'm going to trigger the form recognizer test pipeline.

**Comment by weshaggard** [comment]
@maririos @annelo-msft looks like the formrecognizer tests have been failing for a while now is someone investigating? https://dev.azure.com/azure-sdk/internal/_build?definitionId=1629&_a=summary

**Comment by weshaggard** [comment]
@matthchr any ideas why some batch tests start to fail when moving from ubuntu 16 to 18?

**Comment by mikeharder** [comment]
The Batch failures could be the same DNS issue impact Form Recognizer, though given most of the Batch tests passed it could be unrelated.

**Comment by annelo-msft** [comment]
@kinelski

**Comment by kinelski** [comment]
@weshaggard Thanks for letting us know! We weren't aware. I believe I know what's causing the issue (had the same problem in a PR I'm working on right now), and I'll push a fix in an hour or so.

**Review by mikeharder — CHANGES_REQUESTED** [review]

**Comment by weshaggard** [comment]
Looks like batch tests are still failing on the new OS so we still need to investigate to understand that. @matthchr any insight you can provide about those tests would be helpful.

**Comment by matthchr** [comment]
Hey @weshaggard - I've actually recently changed teams - @bgklein is looking at this some I believe and I'll work with him offline if he has any questions.

The tests that are failing all do some reflection shennanigans to discover all the types matching certain patterns in the SDK and perform some assertions about them (i.e. that certain interfaces they implement behave as expected). When moving to the new OS was an underlying change in installed .NET core version a consequence? The only thing I can think of is that there was some underlying change in behavior of `Activator` or some other reflection stuff which is causing issues here but wasn't on the old OS. 

We will probably need to look into them more closely to see what specifically is failing.

**Comment by weshaggard** [comment]
We should be using the same version of the .NET Core runtime, however there might be differences across platforms but I wouldn't expect any.

**Comment by weshaggard** [comment]
@mattchr @bgklein it would also be great if you guys could update the CODEOWNERS file at https://github.com/Azure/azure-sdk-for-net/blob/master/.github/CODEOWNERS#L20.

**Comment by bgklein** [comment]
As Matt mentioned The main thing with these tests is they use Reflection to populate random values. The actual tests/generation code/models don't seem to be related to the break so initially it seems like something introduced/updated in 18.04 is causing it to break. interesting its only some of them that are breaking so looking into their model structures to see if there are any similarity's.

And yea we can update that. Since Matt is staying in Microsoft the transition has been gradual so haven't deleted all the references to him on Batch yet, but this one should be fine :)

**Comment by bgklein** [comment]
I added some better logs in a seperate PR, but it looks like something is messing up the DataDisk equality check in the test.

It looks like there are too things which could be falsing the text. While this is just from a Newtonsoft serialization of the objects, it looks like either the parameter names are getting messed with or the enums are somehow getting converted to raw values causing a difference:
```
  Stack Trace:
     at Azure.Batch.Unit.Tests.PropertyUnitTests.TestRandomBoundCloudJobScheduleProperties() in /home/vsts/work/1/s/sdk/batch/Microsoft.Azure.Batch/tests/UnitTests/PropertyUnitTests.cs:line 383
  X Azure.Batch.Unit.Tests.PropertyUnitTests.TestRandomBoundCloudPoolProperties [40ms]
  Error Message:
   Collection mismatch. Erroring comparing Microsoft.Azure.Batch.DataDisk to Microsoft.Azure.Batch.Protocol.Models.DataDisk. Values: 
 data disk 0
list1
{"Caching":null,"DiskSizeGB":1529208084,"Lun":1958822876,"StorageAccountType":0}
list2
{"lun":1958822876,"caching":null,"diskSizeGB":1529208084,"storageAccountType":"standard_lrs"}
 data disk 1
list1
{"Caching":null,"DiskSizeGB":0,"Lun":859776312,"StorageAccountType":null}
list2
{"lun":859776312,"caching":null,"diskSizeGB":0,"storageAccountType":null}
 data disk 2
list1
{"Caching":null,"DiskSizeGB":0,"Lun":0,"StorageAccountType":null}
list2
{"lun":0,"caching":null,"diskSizeGB":0,"storageAccountType":null}
Expected: True
Actual:   False
```

This code is relatively unchanged and the same as other classes which are succeeding the same test so seems like something introduced with the OS change but still will need to find out what.

**Comment by bgklein** [comment]
Ah
```
 .NET Core running on Linux and macOS systems only: The collation behavior for the C and Posix cultures is always case-sensitive because these cultures do not use the expected Unicode collation order. We recommend that you use a culture other than C or Posix for performing culture-sensitive, case-insensitive sorting operations.
```
    https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.currentcultureignorecase?view=netcore-3.1
StringComparer.CurrentCultureIgnoreCase Property (System)Gets a  object that performs case-insensitive string comparisons using the word comparison rules of the current culture. docs.microsoft.com

**Comment by bgklein** [comment]
This should now be fixed in master

**Comment by chidozieononiwu** [comment]
@jsquire Do you know why EventHubs tests are failing here?

**Comment by jsquire** [comment]
> @jsquire Do you know why EventHubs tests are failing here?

Apologies for the inconvenience.  That looks like the safety check ticked for a suspected hang that we're still investigating.   If nothing else, that proves we found the right test - which means that I can add an [Ignore] while we dig deeper.    The hang is very intermittent, so kicking the failure should unblock.

**Review by mikeharder — APPROVED** [review]

**Pull request merged**
