### PR TITLE
Update .NET SDK to remove property

### PR DESCRIPTION
**Pull request by emmeliaAra**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by emmeliaAra** [comment]
Recorded Tests are not creating new recordings for this Pr.

**Review by archerzz — APPROVED** [review]
If you are going to release a new version, don't forget to update `CHANGELOG.md`. See [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=signing-and-publishing-nuget-packges) for details.

**Comment by archerzz** [comment]
> Recorded Tests are not creating new recordings for this Pr but test cases are successful: image
> 
> [teams.microsoft.com/l/message/19:7b87fb348f224b37b6206fa9d89a105b@thread.skype/1727698157815?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1727698157815&teamName=Azure%20SDK&channelName=Language%20-%20DotNet&createdTime=1727698157815](https://teams.microsoft.com/l/message/19:7b87fb348f224b37b6206fa9d89a105b@thread.skype/1727698157815?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1727698157815&teamName=Azure%20SDK&channelName=Language%20-%20DotNet&createdTime=1727698157815)

@emmeliaAra I cannot merge this without the tests are fixed (otherwise it will break other pipelines). Please double check your local environment, especially the record mode or any hard-code value.

**Review by archerzz — APPROVED** [review]

**Pull request merged**
