### PR TITLE
Enable track 2 mgmt projects by default

### LINKED ISSUE #17090: Improve code coverage for track 2 management, then re-enable code coverage
In PR https://github.com/Azure/azure-sdk-for-net/pull/17067 I'm disabling code coverage of track 2 management libraries because there is very little coverage and it significantly reduces the reported coverage of other track 2 libraries. For example, track 2 Key Vault client coverage at this moment is over 70% on average, but with track 2 management coverage brings that down to 60% - itself only at 30%.

I'll add details about how to re-enable code coverage when the PR is complete .

### PR DESCRIPTION
**Pull request by heaths**
Resolves #17090 - at least for re-enabling mgmt-plane. Still needs coverage improvement but that's being handled separately.

### CODE REVIEW

**Review by jsquire — COMMENTED** [review]
LGTM

**Review by AlexGhiondea — APPROVED** [review]

**Comment by weshaggard** [comment]
FYI @allenjzhang @m-nash @markcowl

**Pull request merged**
