### PR TITLE
[Do not merge] Strong typing of a class when a member is an AvroUnion of null and a …

### PR DESCRIPTION
**Pull request by adammodlin**
…non-primitive type.

This is a fix for #1982 

It looks like there was a bug in the T4 template "TypeTemplate". Ideal behavior for an AvroUnion between only null and a non-primitive type should be the non-primitive type.

The repro schema is:

```
{
    "type":"record",
    "name":"MyRepro",
    "namespace":"custom.avro",
    "doc": "Repro of bad code gen",
    "fields": [
        {"name": "shouldNotBeObject", "type":
            [  
                "null",
                {"type":"map", "values": 
                    { "type": "array", "items":
                        {"type":"string","avro.java.string":"String"} 
                    } 
                }
            ]
        }
    ]
}
```

Before the fix the generated code was:

```
//<auto-generated />
namespace custom.avro
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record custom.avro.MyRepro.
    /// </summary>
    [DataContract(Namespace = "custom.avro")]
    public partial class MyRepro
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""custom.avro.MyRepro"",""doc"":""Repro of bad code gen"",""fields"":[{""name"":""shouldNotBeObject"",""type"":[""null"",{""type"":""map"",""values"":{""type"":""array"",""items"":""string""}}]}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }

        /// <summary>
        /// Gets or sets the shouldNotBeObject field.
        /// </summary>
        [DataMember]
        [AvroUnion(typeof(AvroNull), typeof(Dictionary<string, List<string>>))]
        public object shouldNotBeObject { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyRepro"/> class.
        /// </summary>
        public MyRepro()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyRepro"/> class.
        /// </summary>
        /// <param name="shouldNotBeObject">The shouldNotBeObject.</param>
        public MyRepro(object shouldNotBeObject)
        {
            this.shouldNotBeObject = shouldNotBeObject;
        }
    }
}
```

After the fix it has the expected typing:

```
//<auto-generated />
namespace custom.avro
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record custom.avro.MyRepro.
    /// </summary>
    [DataContract(Namespace = "custom.avro")]
    public partial class MyRepro
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""custom.avro.MyRepro"",""doc"":""Repro of bad code gen"",""fields"":[{""name"":""shouldNotBeObject"",""type"":[""null"",{""type"":""map"",""values"":{""type"":""array"",""items"":""string""}}]}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }

        /// <summary>
        /// Gets or sets the shouldNotBeObject field.
        /// </summary>
        [DataMember]
        [AvroUnion(typeof(AvroNull), typeof(Dictionary<string, List<string>>))]
        public IDictionary<string, IList<string>> shouldNotBeObject { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyRepro"/> class.
        /// </summary>
        public MyRepro()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyRepro"/> class.
        /// </summary>
        /// <param name="shouldNotBeObject">The shouldNotBeObject.</param>
        public MyRepro(IDictionary<string, IList<string>> shouldNotBeObject)
        {
            this.shouldNotBeObject = shouldNotBeObject;
        }
    }
}
```

Please let me know if this is not the correct way to submit a PR here. Maxim Lukiyanov suggested I submit a PR for this.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adammodlin__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by adammodlin** [comment]
I should have clarified - I am an FTE and my alias is admodlin. Do I still need to sign the CLA?

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by adammodlin** [comment]
It looks like this is causing an Avro Serialization issue. Can we put this PR on hold while I research?

**Comment by adammodlin** [comment]
This is causing an error when attempting to create a writer for my generated class like so:

`var avroWriter = AvroContainer.CreateWriter<MyRepro>(myStream, Codec.Deflate);`

Causes an exception:

`InvalidOperationException occurred. Additional information: No coercion operator is defined between types 'System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.List`1[System.String]]' and 'Microsoft.Hadoop.Avro.AvroNull'`

I suggest that this PR not be merged until I am able to solve this problem. Sorry about this...

**Comment by hovsepm** [comment]
@adammodlin please remove [Do not merge] prefix once you are done with your investigation

**Comment by adammodlin** [comment]
Roger that, will probably have another chance to look at this during the
weekend

**Comment by markcowl** [comment]
@adammodlin Please change this PR in the  next two days or we will have to close it.  You can open a new P%R when you take this back up.

**Comment by adammodlin** [comment]
Mark,

Go ahead and close it for now, I haven't had a chance to get back to this
and will be traveling for the next 14 days.

**Pull request closed without merging**
