### PR TITLE
[Storage] [WebJobs] Do not pass cancelled token to ExecuteAsync when draining 

### PR DESCRIPTION
**Pull request by amnguye**
Adding same fix that was applied in Service Bus (https://github.com/Azure/azure-sdk-for-net/pull/38063) and Event Hubs (https://github.com/Azure/azure-sdk-for-net/pull/38067) WebJobs Extension libraries.

### CODE REVIEW

**Review by liliankasem — APPROVED** [review]

**Comment by amnguye** [comment]
live test failures unrelated to PR changes.

**Pull request merged**
