### PR TITLE
Consume latest SQL API version

### PR DESCRIPTION
**Pull request by bradrich-msft**
This change consumes newly released SQL API version 2020-08-01 and tests new functionality in it.

Merged swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/11063

### CODE REVIEW

**Review by jamestao — APPROVED** [review]

**Comment by bradrich-msft** [comment]
Hi @markcowl any updates on this PR?  Thank you.

**Review by markcowl — CHANGES_REQUESTED** [review]
Need changes to:
(1) Csproj and assemblyinfo.cs to update package version
(2)Az.Sdk.props to add the new api-version tag

Also, please provide a link to the merged swagger PR in the description of this PR

**Comment by bradrich-msft** [comment]
> Need changes to:
> (1) Csproj and assemblyinfo.cs to update package version
> (2)Az.Sdk.props to add the new api-version tag
> 
> Also, please provide a link to the merged swagger PR in the description of this PR

@markcowl I have revised per request.  Thank you.

**Review by markcowl — APPROVED** [review]

**Pull request merged**
