### PR TITLE
Hide deprecated German cloud option in ACR Audience extensible enum

### LINKED ISSUE #32883: [ACR] Remove support for Germany cloud
### Information

We should remove the support for Germany cloud in our SDK as the cloud has already been deprecated.

### PR DESCRIPTION
**Pull request by annelo-msft**
Fixes https://github.com/Azure/azure-sdk-for-net/issues/32883

Removing support from tests as well.

### CODE REVIEW

**Comment by pallavit** [comment]
Curious do we have any other SDKs that take dependency on Germany cloud that we should be removing? Also, should we be adding this check to our analyzers?

**Comment by annelo-msft** [comment]
@pallavit, it looks like there are [types for these](https://grep.app/search?q=germany&filter[repo][0]=Azure/azure-sdk-for-net&filter[path][0]=sdk/&filter[lang][0]=C%23) in Core, Identity, and several management plane libraries.  I can file issues for those separately.

**Comment by pallavit** [comment]
> @pallavit, it looks like there are [types for these](https://grep.app/search?q=germany&filter%5Brepo%5D%5B0%5D=Azure/azure-sdk-for-net&filter%5Bpath%5D%5B0%5D=sdk/&filter%5Blang%5D%5B0%5D=C%23) in Core, Identity, and several management plane libraries. I can file issues for those separately.

I wanted to understand if we are consistent across the board and if not is it deliberate? Do we have scenarios in core, identity for it or is it just tech debt we have not gotten to. If tech debt, I am not too worried we can get to it based on priorities.

**Comment by christothes** [comment]
> > > @pallavit, it looks like there are [types for these](https://grep.app/search?q=germany&filter%5Brepo%5D%5B0%5D=Azure/azure-sdk-for-net&filter%5Bpath%5D%5B0%5D=sdk/&filter%5Blang%5D%5B0%5D=C%23) in Core, Identity, and several management plane libraries. I can file issues for those separately.
> > 
> > 
> > I wanted to understand if we are consistent across the board and if not is it deliberate? Do we have scenarios in core, identity for it or is it just tech debt we have not gotten to. If tech debt, I am not too worried we can get to it based on priorities.
> 
> /cc: @christothes, @schaabs - we saw identity supports Germany as a national cloud and were under the impression it is not considered a national cloud anymore and were removing it from ACR. Any particular reason why identity continues to support it?

/cc: @scottaddie

**Review by pallavit — APPROVED** [review]

**Comment by pallavit** [comment]
@annelo-msft I have approved these changes. The changes in core\identity seem to be debt so it is ok for us to remove it in ACR.

**Comment by annelo-msft** [comment]
Great, thank you, @pallavit!

**Pull request merged**
