### PR TITLE
Update SystemEventTypeMappings.cs

### PR DESCRIPTION
**Pull request by xioyi**

### CODE REVIEW

**Comment by xioyi** [comment]
My previous PR was closed. I think it'd be better to create a new PR to address the only missing piece.

**Comment by jsquire** [comment]
Thank you for your contribution, @xioyi.   Tagging and routing to the team best able to provide feedback.

**Comment by jsquire** [comment]
@jfggdl  - Would you be kind enough to help route to the appropriate folks to review?

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @ellismg

**Comment by jsquire** [comment]
@ahamad-MS:  Would you please provide feedback or help route to the appropriate individual to review?

**Comment by ahamad-MS** [comment]
@jsquire  We are working with author to understand the scope of the change and why is it failing... I am taking care of the review.. 

thanks

**Review by ahamad-MS — APPROVED** [review]
LGTM...

**Comment by ahamad-MS** [comment]
Please work with on resolving the checks failures..

**Comment by JoshLove-msft** [comment]
> Please work with on resolving the checks failures..

The error indicates that StorageLifecyclePolicyCompletedEventData hasn't been generated in the SDK.

**Comment by xioyi** [comment]
Can anyone help to check why StorageLifecyclePolicyCompletedEventData was not generated? The definition of it is in:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json

Thanks.

**Comment by ahamad-MS** [comment]
@jsquire  Can you please help assigning this issue to someone who can help Yi resolving the failed jobs? From my side and my team side, we approved the change but don't know what is failing here. Thanks.

**Comment by jsquire** [comment]
> @jsquire Can you please help assigning this issue to someone who can help Yi resolving the failed jobs? From my side and my team side, we approved the change but don't know what is failing here. Thanks.

Will do; the build was old enough that details expired.  Kicking off another run to allow for investigation.

**Comment by jsquire** [comment]
@JoshLove-msft:  Looks like the failures are related to your observation that `StorageLifecyclePolicyCompletedEventData` hasn't been generated.  Do you have any insight as to what steps would need to be taken to resolve that?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft: Looks like the failures are related to your observation that `StorageLifecyclePolicyCompletedEventData` hasn't been generated. Do you have any insight as to what steps would need to be taken to resolve that?

I'm not super familiar with the Track 1 code gen, but I believe these instructions would need to be followed - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/readme.md#getting-started

**Comment by jsquire** [comment]
Thanks, @JoshLove-msft.

@ahamad-MS:  The failure appears to be due to drift between the [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json) that @xioyi mentioned and the generated code.  Speculatively, running code generation should resolve; are you able to walk @xioyi through your code generation process or run generation and patch so that this PR can be rebased on those changes?

**Comment by xioyi** [comment]
After reading the instructions, I am still confused what I should do. Should I clone the whole thing locally and run autorest then check-in something? Please advise.

@jsquire @JoshLove-msft

**Comment by jsquire** [comment]
> After reading the instructions, I am still confused what I should do. Should I clone the whole thing locally and run autorest then check-in something? Please advise.
> 
> @jsquire @JoshLove-msft

Apologies, @xioy.   In a nutshell, there is some code generation that needs to take place to pull the missing value out of the Swagger and into the code.   

As the process for generation is a bit different between teams, neither Josh nor I are entirely sure what needs to happen either.   As the team that owns the library, we need @ahamad-MS to be the authoritative voice on whether that needs to happen internally or what the steps for you take are.    @ahamad-MS, would you please offer your thoughts?

**Comment by jsquire** [comment]
@ahamad-MS:  Following-up to see if you had any insight into what steps need to be taken to regenerate for the track one library.

**Comment by jsquire** [comment]
//cc: @pakrym, in case he has any insight into the common areas of the T1 generation process.

**Comment by jsquire** [comment]
@AlexGhiondea:  Do you have any insight into who can help resolve this?

**Comment by ahamad-MS** [comment]
@jsquire  there is not additional action or information from service side. We provided all info to Yi and followed up with him couple of times on how to resolve these issues. I will let @xioyi provide additional info here on where he wants this PR to go next.

**Comment by jsquire** [comment]
Hi @xioyi.  Thank you, again, for your contribution and helping to make the Azure SDKs better.  Would you please let us know if you're blocked and in need of assistance and, if not, whether you're still interested in working with us to get this merged in?

**Comment by jsquire** [comment]
Thank you for your contribution.  Since there hasn't been recent engagement, I'm going to close this out.  Please feel free to reopen if you'd like to continue working on these changes.

**Pull request closed without merging**
