### PR TITLE
Update Azure Notification Hubs SDK for 100% swagger coverage

### PR DESCRIPTION
**Pull request by aimankhan**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
https://github.com/Azure/azure-rest-api-specs/pull/3034
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by aimankhan** [comment]
@blocphan

**Review by dsgouda — CHANGES_REQUESTED** [review]
- Please generate the code using generate.ps1 similar to one [here](https://github.com/Azure/azure-sdk-for-net/blob/2f06b23dc0a5d74c10a263312e05ceb54654f58c/src/SDKs/Compute/Management.Compute/generate.ps1) and commit all artifacts generated
- Run `msbuild build.proj /t:Build /p:Scope=SDKs\NotificationHubs` and commit all files generated/modified
- There are breaking changes introduced here, if a package has already been published, please bump the package id

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please run `msbguild build.proj /t:build /p:Scope=SDKs\NotificationHubs` and commit changes to the .props file

**Review by dsgouda — CHANGES_REQUESTED** [review]
Apologize for the turnaround, there are breaking changes being introduced into the sdk here. Please update the package version in csproj and AssemblyInfo files and this should be good to go.

**Review by dsgouda — APPROVED** [review]
LGTM subject to CIs passing
@aimankhan thanks for addressing feedback

**Pull request merged**
