### PR TITLE
[Azure Search] Merge master to search-preview

### PR DESCRIPTION
**Pull request by bitsforthought**
This is to fix build errors fixed by recent changes in master.

FYI @dsgouda @ishansrivastava90 @shmed @Yahnoosh @updixit

### CODE REVIEW

**Review by dsgouda — APPROVED** [review]
LGTM
@brjohnstmsft merge when ready

**Review by ishansrivastava90 — APPROVED** [review]
LGTM

**Comment by brjohnstmsft** [comment]
@dsgouda I want to merge this as a merge commit to ensure history isn't messed up, but there's some kind of policy preventing me.

**Comment by weshaggard** [comment]
You list of commits doesn't look correct. Can you please rebase on top of master first to ensure it only contains your set of changes and then if we need to preserve commit history then we can override and merge.

**Comment by weshaggard** [comment]
Sorry my fault I thought this was a PR against master but it looks like you are merging master changes into the search-preview branch. I'll go ahead and do the merge.

**Comment by brjohnstmsft** [comment]
Thanks @weshaggard!

**Pull request merged**
