### PR TITLE
[PolicyInsights] Add trigger evaluation methods

### PR DESCRIPTION
**Pull request by pilor**
Generating off the latest PolicyInsights swagger spec.  This adds methods for triggering compliance evaluation on a scope and adds policy entity version columns to policyStates query responses.

### CODE REVIEW

**Comment by pilor** [comment]
@calecarter FYI

**Review by calecarter — APPROVED** [review]
:shipit:

**Review by isra-fel — CHANGES_REQUESTED** [review]
The generated code looks good to me, but it seems some tests are failing because sub id cannot be found in the recordings, e.g. https://github.com/Azure/azure-sdk-for-net/pull/10688/files#diff-812a913339e9ce75af8516e7a5973d4fR71

@pilor could you try recording them again? Thanks

**Comment by pilor** [comment]
> The generated code looks good to me, but it seems some tests are failing because sub id cannot be found in the recordings, e.g. https://github.com/Azure/azure-sdk-for-net/pull/10688/files#diff-812a913339e9ce75af8516e7a5973d4fR71
> 
> @pilor could you try recording them again? Thanks

Yeah, I was trying to solve this yesterday.  The "SubscriptionId" only gets persisted in the recording when I run the tests individually.  When run together (in VS or via the dotnet command line) it is not persisted.  I'll run each individually for now to unblock but its odd behavior.

**Comment by pilor** [comment]
@isra-fel test recording problem has been fixed

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
