### PR TITLE
Custom vision 3.0

### PR DESCRIPTION
**Pull request by areddish**
Updates for 3.0 SDK

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/5164

### CODE REVIEW

**Comment by areddish** [comment]
Getting this out now so it can be looked at while waiting on Swagger merge.. 
Will regenerate meta-data once Swagger PR is in.

**Review by dsgouda — CHANGES_REQUESTED** [review]

**Comment by dsgouda** [comment]
@areddish  we have switched our base from psSdkJson6 to master, please sync from master and update the PR

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
Will merge once CIs pass

**Pull request merged**
