### PR TITLE
Add discrete Encrypt/Decrypt operations

### PR DESCRIPTION
**Pull request by scottcot-msft**
Add discrete Encrypt/Decrypt operations

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@scottrille__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (scottcot). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Pull request merged**
