### PR TITLE
[Do not merge] Update Azure Batch .Net SDK to meet API version 2018-03-01.6.1.

### PR DESCRIPTION
**Pull request by xingwu1**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by xingwu1** [comment]
The PR of REST API is https://github.com/Azure/azure-rest-api-specs/pull/2556.

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please run `msbuild build.proj /t:build /p:Scope=SDKs\Batch`
This should generate a `.props` file, please commit this file.

**Comment by xingwu1** [comment]
@dsgouda this is dataplane SDK, should I still need this and named as AzSDK.RP.props?

**Comment by dsgouda** [comment]
Yes, if you see the `.props` file being generated please commit it.

**Comment by xingwu1** [comment]
@dsgouda the .props files had been added.

**Comment by shahabhijeet** [comment]
@xingwu1 couple of things to keep in mind.
When a PR has more than 100 files, it's better you create a PR that has been created after the spec PR is merged.
The current approach you have taken forces us to review your PR now and then again when you will have a generated SDK from the merged spec.
This is acceptable for RPs who are brand new and are going through this process for the first time.

Our SLA is 2 business days and when you are ready to merge your PR we will review it in due time.
This PR will be closed by EOW (please reopen when you are ready with your generated SDK from the merged spec PR)

**Comment by shahabhijeet** [comment]
@xingwu1 please reopen this PR or create a new PR when spec is merged and new SDK is generated from the merged spec.

**Pull request closed without merging**
