### PR TITLE
[Schema Registry] Prototype for alternative serializer API

### PR DESCRIPTION
**Pull request by m-redding**
## Prototype for alternative API for the schema registry serializer
Suggested by @danielmarbach in https://github.com/Azure/azure-sdk-for-net/pull/36926#discussion_r1337310153

API difference: https://apiview.dev/Assemblies/Review/26accfd449ee4d83acf4a31d5926b0f5?diffRevisionId=77043988996443119a2a982924958151&diffOnly=False&revisionId=1c17c10d4d594f148b2a7083c11dd9f2&doc=False

#### Example 1:
Before:
```csharp
EventData eventData = await serializer.SerializeAsync<EventData, Employee>(employee);
```
After:
```csharp
EventData eventData = new();
await serializer.SerializeAsync(eventData, employee);
````

#### Example 2:
Before:
```csharp
EventData eventData = (EventData)await serializer.SerializeAsync(employee, messageType: typeof(EventData));
```
After:
```csharp
EventData eventData = new();
await serializer.SerializeAsync(eventData, employee);
````

# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by danielmarbach — COMMENTED** [review]
I'm obviously biased but I think this is way simpler times use due to type inference and has other benefits as I mentioned in the discussion thread on the other PR. Nice!

Thanks @m-redding for turning my suggestions into reality 🙇

**Review by danielmarbach — APPROVED** [review]

**Comment by danielmarbach** [comment]
Approved the prototype (not that my approval matters 😂🤣)

I assume the final version will also have the XML documentation updated

**Comment by m-redding** [comment]
@danielmarbach After a bit of discussion, we're planning on sticking with the current implementation primarily because it aligns with what [Newtonsoft](https://www.newtonsoft.com/json/help/html/DeserializeObject.htm) / [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/how-to?pivots=dotnet-8-0#how-to-read-json-as-net-objects-deserialize) do when deserializing into an object. (It's a bit of a different scenario, but it's similar in the sense that both are populating an object).
```csharp
Account account = JsonConvert.DeserializeObject<Account>(json);
```
```csharp
WeatherForecast? weatherForecast = JsonSerializer.Deserialize<WeatherForecast>(jsonString);
```
The current approach also avoids some additional complexities like how we should handle instances that aren't empty. 

This was a good idea though and I appreciated the opportunity to explore it. Thanks for your input!

**Comment by danielmarbach** [comment]
Let me try to recap to make sure I understand it. 

In your discussions you are treating the `EventData`  or `MessageContent` objects as the objects to be populated which then makes them in your design closer to the deserialize semantics which populates an object out of a binary data. That is the primary decision driver to leave the current API as is.

For my own edutainment I would love to hear your thoughts on the different angle I provided because it seems intuitively I would value the alignment with the serialization ecosystem and most importantly with how serialize and deserialize methods behave higher.

Let me try to re-explain why I looked at the API from a different perspective. When I "reviewed" the API I looked at it from the perspective of a serializer. A serializer serializes a payload into a writable data structure that receives the binary data (stream or Binarydata) (aka WriteInto semantics) and it deserializes from a readable data structure that contains binary data into an object that it populates (aka populate semantics). Following that semantic I found it counter intuitive for the schema registry serializer to treat the serialize path the same as the deserialize path by populating  the writable data structure. That' s why I suggested to keep the semantics of the APIs which are clearly following the serialization/deserialization domain aligned with the general expectations of how a serialize and deserialize API would behave. Examples:

## Serialize

### Newtonsoft

```csharp
public void Serialize(TextWriter textWriter, Object value)
public void Serialize(JsonWriter jsonWriter, Object value)
public void Serialize(TextWriter textWriter, Object value, Type objectType)
public void Serialize(JsonWriter jsonWriter, Object value, Type objectType)
```
### System.Text.Json

```csharp
public static string Serialize (object? value, Type inputType, System.Text.Json.Serialization.JsonSerializerContext context);
public static string Serialize (object? value, Type inputType, System.Text.Json.JsonSerializerOptions? options = default);
public static void Serialize (System.IO.Stream utf8Json, object? value, Type inputType, System.Text.Json.Serialization.JsonSerializerContext context);
public static void Serialize (System.Text.Json.Utf8JsonWriter writer, object? value, Type inputType, System.Text.Json.Serialization.JsonSerializerContext context);
...
```

As you can see all serialize APIs accept the payload and write them into a writable data structure (string, stream, Utf8JsonWriter, TextWriter, JsonWriter) (aka WriteInto semantics). The string case is slightly different since the string is returned but given the nature of strings this makes sense.

## Deserialize

### Newtonsoft

```csharp
public Object Deserialize(
	JsonReader reader
)
public T Deserialize<T>(
	JsonReader reader
)
public Object Deserialize(
	TextReader reader,
	Type objectType
)
public Object Deserialize(
	JsonReader reader,
	Type objectType
)
```

### System.Text.Json
```csharp
public static object? Deserialize (ReadOnlySpan<byte> utf8Json, Type returnType, System.Text.Json.Serialization.JsonSerializerContext context);
public static object? Deserialize (ReadOnlySpan<byte> utf8Json, Type returnType, System.Text.Json.JsonSerializerOptions? options = default);
...
public static object? Deserialize (System.IO.Stream utf8Json, Type returnType, System.Text.Json.Serialization.JsonSerializerContext context);
...
public static object? Deserialize (string json, Type returnType, System.Text.Json.JsonSerializerOptions? options = default);
...
public static object? Deserialize (ref System.Text.Json.Utf8JsonReader reader, Type returnType, System.Text.Json.Serialization.JsonSerializerContext context);
...
```

As you can see the Deserialize methods accept a readable data structure that they use to read from and then populate the payload type with the information contained in the readable data structure (aka populate semantics).

**Comment by m-redding** [comment]
> In your discussions you are treating the EventData or MessageContent objects as the objects to be populated which then makes them in your design closer to the deserialize semantics which populates an object out of a binary data

Yes, at least that was my interpretation.

> A serializer serializes a payload into a writable data structure that receives the binary data (stream or Binarydata) (aka WriteInto semantics) and it deserializes from a readable data structure that contains binary data into an object that it populates (aka populate semantics)

I definitely see what you mean by our API being confusing when thinking about this in terms of populate vs write into semantics. We don't follow the standard serialization pattern. But I do also think that our serializer kind of falls into a weird gray area where MessageContent and its deriving types aren't "writable" in the same way that a stream or writer is. The complexity I mentioned above is one side-effect of that, i.e if someone passed in an already populated `EventData` instance, do we just overwrite the `ContentType`/`Data`? This is different from, for example, a stream where the expectation is to start writing at the starting position.

**Comment by danielmarbach** [comment]
@m-redding Thanks for your patience and your reply. I do enjoy this design discussion :heart_eyes: 

> But I do also think that our serializer kind of falls into a weird gray area where MessageContent and its deriving types aren't "writable" in the same way that a stream or writer is. The complexity I mentioned above is one side-effect of that, i.e if someone passed in an already populated EventData instance, do we just overwrite the ContentType/Data? This is different from, for example, a stream where the expectation is to start writing at the starting position, regardless of the contents / if it has to overwrite something.

And that is where I personally see not much difference and consider these cases boundary conditions that any serialize / deserialize method has to deal with. As an example. When you serialize to a stream the method doesn't know which derived type of stream you are passing. It can for example check some basic things like whether the stream is writable or not and decide to throw if it isn't (for example in the case of a serialize into a stream). For everything that cannot be checked based on the base type definition it will call `WriteAsync` and assume the overwritten method does the necessary checks. If the checks are successful it write the data into the current position and advances the position. So if the stream happens to be at position 0 the data is inserted there. If there is existing data there it will be appended or if someone decides to rewind an existing stream with data the data will be overwritten. There are other "boundary conditions" that apply to other overloads too. For example if you pass a buffer / span and the span doesn't have enough space it will throw. If the span is in a position that accidentally (or deliberately) contains existing data it is overwritten.

For me similar boundary conditions apply in our examples too and are a matter of design choices this type of serializer wants or deliberately doesn't want to support. For example I can see how `EventData` or `MessageContent` data could be overwritten (this would enable scenarios for pooling EventData or MessageContent) or it would throw should `Data` be a non-default value.

**Pull request closed without merging**
