### PR TITLE
[FormRecognizer] Preview 1: Removed _cancellationToken field from Operation subclasses

### LINKED ISSUE #10802: [LROs:] Incorporate use of private _cancellationToken into UpdateStatusAsync

### PR DESCRIPTION
**Pull request by kinelski**
~Internal constructors of the `*Operation` classes now must take a `CancellationToken` parameter. This token can be used to cancel the operation's result polling.~

Parallel to this change, protected parameterless constructors have been added to the aforementioned classes to make them mockable.

EDIT:
The cancellation token matter has been discussed internally and the following has been decided:
- `*Operation` classes won't have a `private _cancellationToken` field anymore as there's no good reason for having these two tokens controlling the lifetime of a single request.
- To cancel the POST request that starts the long-running operation, the token passed to the method in the client (`StartRecognizeReceiptsAsync`, etc) will be used.
- To cancel any GET requests that poll the result of the long-running operation, the token passed to the polling method will be used: `UpdateStatus` or `WaitForCompletion`.

Fixes #10802.

### CODE REVIEW

**Comment by AlexanderSher** [comment]
What should happen in the following hypothetical case:
```cs
using var cts = new CancellationTokenSource(5000);
var op = await client.StartRecognizeContentAsync(cts.Token);
await Task.Delay(10000); // Some other long running operations
var response = await op.UpdateStatusAsync();
```

**Comment by kinelski** [comment]
> 
> 
> What should happen in the following hypothetical case:
> 
> ```cs
> using var cts = new CancellationTokenSource(5000);
> var op = await client.StartRecognizeContentAsync(cts.Token);
> await Task.Delay(10000); // Some other long running operations
> var response = await op.UpdateStatusAsync();
> ```

Once the token has been canceled, the `Operation` instance won't be able to make requests anymore. So `op.UpdateStatusAsync()` will throw. Which makes me wonder... if we have the same scenario you suggested, but call:
```
using var cts2 = new CancellationTokenSource();
var response = await op.UpdateStatusAsync(cts2.Token);
```
We'll be able to get the response from the server, which I think it's a weird behavior...

I'm using the same approach used in storage:
https://github.com/Azure/azure-sdk-for-net/blob/acb086a1fba635973b12567419d1f365964ee9ca/sdk/storage/Azure.Storage.Blobs/src/Models/CopyFromUriOperation.cs#L164-L168

Maybe using a linked token source would make more sense?

**Comment by AlexanderSher** [comment]
> Once the token has been canceled, the `Operation` instance won't be able to make requests anymore. 

Hm... and what exception will user get in this case?

> Maybe using a linked token source would make more sense?

If both tokens can cancel the operation, then you'll probably need a linked token source.

**Comment by kinelski** [comment]
> Hm... and what exception will user get in this case?

A `TaskCanceledException`.

**Comment by kinelski** [comment]
The cancellation token matter has been discussed internally and the following has been decided:
- `*Operation` classes won't have a `private _cancellationToken` field anymore as there's no good reason for having these two tokens controlling the lifetime of a single request.
- To cancel the POST request that starts the long-running operation, the token passed to the method in the client (`StartRecognizeReceiptsAsync`, etc) will be used.
- To cancel any GET requests that poll the result of the long-running operation, the token passed to the polling method will be used: `UpdateStatus` or `WaitForCompletion`.

**Review by annelo-msft — APPROVED** [review]
Thanks for driving this to resolution, @kinelski !  It might be worth updating the name of the PR to reflect that it's a design change and not an addition.

**Pull request merged**
