### PR TITLE
[Storage][Blobs] Fix null reference when overwriting binary data with client-side encryption enabled

### LINKED ISSUE #26012: [BUG] NullReferenceException when using overwrite true for Upload in BlobClient
### Library name and version

Azure.Storage.Blobs 12.10.0.0

### Describe the bug

If using following function with overwrite = true:

```
public virtual Task<Response<BlobContentInfo>> UploadAsync(
            BinaryData content,
            bool overwrite = false,
            CancellationToken cancellationToken = default) =>
            UploadAsync(
                content,
                options: overwrite ? null : new BlobUploadOptions(){ Conditions = new BlobRequestConditions { IfNoneMatch = new ETag(Constants.Wildcard) }},
                cancellationToken: cancellationToken);
```
				
				
The StagedUploadInternal within the BlobClient throws a NullReferenceException because of probably setting above overwrite to null
It tries to access a member of the BlobUploadOptions in the BlobClient.cs in either line 1628 or 1639 ([Source](https://github.com/Azure/azure-sdk-for-net/blob/7603179c430e33c1e561f6a3d39a1038f4d2920c/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs))

This issue happens with all Upload functions where the options get set like this:
`options: overwrite ? null : new BlobUploadOptions(){ Conditions = new BlobRequestConditions { IfNoneMatch = new ETag(Constants.Wildcard) }}`
 
If overwrite is true, then the options are null and the StagedUploadInternal throws a NullReferenceException

### Expected behavior

No NullReferenceExceptions are thrown

### Actual behavior

NullReferenceException gets thrown when overwrite is set to true

### Reproduction Steps

Create a BlobClient und use the Upload function with overwrite parameter set to true.
NullReferenceException gets thrown

### Environment

Local debug

### PR DESCRIPTION
**Pull request by PramodValavala-MSFT**
When calling `Upload` or `UploadAsync` on `BlobClient` with `BinaryData` and Client-Side Encryption enabled to overwrite a blob, it results in a `NullReferenceException` since the `BlobUploadOptions` object is `null` when `overwrite: true` is passed. This PR resolves that by sending the default object instead of `null`.

resolves #26012

### CODE REVIEW

**Review by jaschrep-msft — CHANGES_REQUESTED** [review]
We try to have any new code not instantiate more options on the heap when unnecessary. The bug is not that we passed null, but that `StagedUploadInternal()` assumed it was not null.

Since client-side encryption needs to instantiate metadata and pass that on through options, the fix should be to add `options ??= new BlobUploadOptions;` when StagedUploadInternal branches for client-side encryption.

**Comment by jaschrep-msft** [comment]
Note to reviewers:

There does not appear to be an easy way to make this test recordable. We'll need to run a live test pass to validate this change.

**Comment by PramodValavala-MSFT** [comment]
> We try to have any new code not instantiate more options on the heap when unnecessary. The bug is not that we passed null, but that `StagedUploadInternal()` assumed it was not null.
> 
> Since client-side encryption needs to instantiate metadata and pass that on through options, the fix should be to add `options ??= new BlobUploadOptions;` when StagedUploadInternal branches for client-side encryption.

Understood. Done. 👍

**Comment by PramodValavala-MSFT** [comment]
@jaschrep-msft Hope the changes here are good. I did do a force push of the commit instead of just pushing another commit, which messed up the requested changes reference in GitHub, I think. Sorry about that.

**Review by jaschrep-msft — APPROVED** [review]

**Comment by jaschrep-msft** [comment]
The need for a live test for such a simple fix is unfortunate. Filed #26037 for investigation into reducing client-side encryption test reliance on live testing only.

**Comment by PramodValavala-MSFT** [comment]
@jaschrep-msft I'm not authorized to merge. Could you merge this one? Thanks!

**Pull request merged**
