### PR TITLE
Fix #14297: [BUG] BlobClient.Exist and other non-async methods throws InvalidOperationException

### LINKED ISSUE #14297: [BUG] BlobClient.Exist and other non-async methods throws "InvalidOperationException: Synchronously waiting on non-completed task isn't allowed." when used in ASP.NET application
**Describe the bug**
Using non-async methods in ASP.NET application (ie. WebForms) causes the exception is thrown:

```
[InvalidOperationException: Synchronously waiting on non-completed task isn't allowed.]
   Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(Task`1 task) +126
   Azure.Storage.Blobs.Specialized.BlobBaseClient.Exists(CancellationToken cancellationToken) +28
   WebApplication7.Default.Page_Load(Object sender, EventArgs e) in C:\Users\kanda\source\repos\WebApplication7\WebApplication7\Default.aspx.cs:17
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +85
   System.Web.UI.Control.OnLoad(EventArgs e) +79
   System.Web.UI.Control.LoadRecursive() +130
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2853
```

**To Reproduce**
* Run the Visual Studio, Create new project.
* Choose ASP.NET Web Application (.NET Framework)
* Use "Empty" template, uncheck "Configure for HTTPS" (to keep the solution simple)
* Add nuget package Azure.Storage.Blobs **version 12.5.0** to the project
* Add New Item to the solution, choose Web Form, name it "Default.aspx"
* Open the new Default.aspx.cs file
* Add the following snippet to the method Page_Load (you can use real credentials but the following fake credentials also reproduces the bug)
```csharp
Azure.Storage.Blobs.BlobServiceClient serviceClient = new Azure.Storage.Blobs.BlobServiceClient("DefaultEndpointsProtocol=https;AccountName=havittempstorage;AccountKey=/0000000000000000000000000000000000000000000000000000000000000000000000000000000000000==;EndpointSuffix=core.windows.net");
Azure.Storage.Blobs.BlobContainerClient containerClient = serviceClient.GetBlobContainerClient("any_container");
Azure.Storage.Blobs.BlobClient blobClient = containerClient.GetBlobClient("abc.txt");
blobClient.Exists(); // just run the method
```
* Run (debug) the application

Alternatively, download the solution from repository https://github.com/jirikanda/AzureSDKRepro. Then open the WebApplication7.sln, build and run (or debug) the application.

**Workaround**
Azure.Storage.Blobs **version 12.4.4** works well.

**Special note**
The issue is NOT related to STA thread (despite #14184).

### PR DESCRIPTION
**Pull request by AlexanderSher**

### CODE REVIEW

**Comment by jsquire** [comment]
Hi @AlexanderSher.   Can you please advise if this is an active work stream or if we should close out this PR?

**Comment by AlexanderSher** [comment]
This is a fix for the change that made us re-release most of the packages in August. Instead of applying a fix, we decided to rollback the change, as it was a safer option. @pakrym , do we want to restore that change (with this fix) back in the future?

**Comment by pakrym** [comment]
I think we should get it in but only after we get testing going in different environments that have sync contexts.

**Comment by jsquire** [comment]
Thanks, folks.   I'll leave this be for now, then.

**Comment by jsquire** [comment]
I'm going to close this out as its been stalled for ~6 months.   Please feel free to reopen when we're unblocked and you're ready to start working on this again.

**Pull request closed without merging**
