### PR TITLE
Adding .Net SDK support for setting Azure AD administrator on Managed Instance

### PR DESCRIPTION
**Pull request by SanjaMalesevic**

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hello @SanjaMalesevic , please provide the corresponding Spec review PR, and also please follow these [instructions](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#generating-net-sdk) when you generate .Net SDK. Thanks.

**Comment by SanjaMalesevic** [comment]
This changes for .NET client are generated using managedInstanceAdministrators.json from PR  https://github.com/Azure/azure-rest-api-specs/pull/5095.

**Comment by SanjaMalesevic** [comment]
> Hello @SanjaMalesevic , please provide the corresponding Spec review PR, and also please follow these [instructions](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#generating-net-sdk) when you generate .Net SDK. Thanks.

Hi, I've just added comment below with link to corresponding PR on azure-rest-api-specs branch.

**Review by isra-fel — APPROVED** [review]

**Comment by isra-fel** [comment]
Hi @SanjaMalesevic , there are some test failures. Please fix them then assign the PR back to me. Thanks

**Comment by SanjaMalesevic** [comment]
> Hi @SanjaMalesevic , there are some test failures. Please fix them then assign the PR back to me. Thanks

I made some changes in creating vnet, new route is added there. So, I need to record all test that create vnet and add new session records. Because of that build has failed. Execution takes lot of time, so I couldn't finish today and I will be out of office next week. It will be solved for 10 days.

**Pull request merged**
