### PR TITLE
[ACR] add time trigger

### PR DESCRIPTION
**Pull request by ankurkhemani**

### CODE REVIEW

**Comment by jaysterp** [comment]
LGTM

**Comment by ankurkhemani** [comment]
// cc @jaysterp

**Review by jaysterp — APPROVED** [review]

**Comment by jaysterp** [comment]
@maririos these changes LGTM

**Comment by jaysterp** [comment]
Please see the merged swagger PR here https://github.com/Azure/azure-rest-api-specs/pull/6221

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
