### PR TITLE
Update SDK to refer to ARM API version 2020-03-01

### PR DESCRIPTION
**Pull request by matthchr**
Please note that this _is_ a breaking change.

### CODE REVIEW

**Comment by matthchr** [comment]
@isra-fel and @erich-wang can you take a look at this?

**Comment by isra-fel** [comment]
Hi Matthew, I'm OK with the changes. Please update [the API tag](https://github.com/Azure/azure-sdk-for-net/blob/5c89e1a689f9f7369fb85086bfb2aade4af8ac55/sdk/batch/Microsoft.Azure.Management.Batch/AzSdk.RP.props#L4) since you are based on a new API version.
Thanks

**Comment by matthchr** [comment]
I updated the API tag

**Comment by matthchr** [comment]
@isra-fel Can we merge this so that I can ship it?

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
