### PR TITLE
Support for Identity in Patch for Microsoft.RecoveryServices/Vaults

### PR DESCRIPTION
**Pull request by asmaskar**

### CODE REVIEW

**Comment by nisha-bhatia** [comment]
@asmaskar Could you please add the Swagger PR link?

**Comment by asmaskar** [comment]
@nisha-bhatia  This is the link to the swagger pr    
https://github.com/Azure/azure-rest-api-specs/pull/11646
Thanks.

**Comment by nisha-bhatia** [comment]
@asmaskar I noticed that the Swagger PR had a breaking change label, but the breaking change checklist is not filled out. Is the breaking change label supposed to be there? 
Screenshot 2020-11-17 135626

**Comment by asmaskar** [comment]
@nisha-bhatia as per one of the comments in that Pr, it is supposed to be there due to other reasons. You can have a check in the conversations/discussion in that PR

**Comment by asmaskar** [comment]
Screenshot_20201118-094108

**Comment by nisha-bhatia** [comment]
@asmaskar Thank you for clarifying. Is there also supposed to be a breaking change in this PR? I noticed the PatchVault constructor on Line 43 of PatchVault.cs has changed. There is a new parameter added to the middle of the constructor.

**Comment by bquantump** [comment]
@asmaskar In the screenshot you sent, you admit there was a breaking change. Hence the swagger should have never been merged unless the breaking change was approved by the breaking change review board, even if just GO (although not sure how this would just effect GO)

**Comment by asmaskar** [comment]
@bquantump, in the swagger PR, it was just showing a breaking change for Go and @ArcturusZhang mentioned it that the breaking change is expected due to some external changes. As far the review board, sorry but i am not aware of it but it was approved by the GO folks when asked by them and post that the PR was merged.

@nisha-bhatia, in this PR yes the patch vault has changed as the identity field is added but i dont think this should be breaking change as the swagger PR showed that there were no breaking changes for other languages (except Go which as mentioned by @ArcturusZhang  was expected)

**Comment by nisha-bhatia** [comment]
@asmaskar This is a breaking change for dotnet, as the parameters for the PatchVault constructor now has an extra field in it. Since this is a breaking change in dotnet, this change will first have to be approved by the API Review Board.

**Comment by asmaskar** [comment]
@nisha-bhatia I agree the parameter is added but in the constructor, we see that an default value is being assigned to it, which supports the behaviour that the identity field is optional during patch operation. Please let me know if I am missing something here.

**Review by JeffreyRichter — APPROVED** [review]

**Comment by asmaskar** [comment]
@nisha-bhatia  Can you please merge these changes if it looks fine to you.
Thanks.

**Review by nisha-bhatia — APPROVED** [review]

**Pull request merged**
