### PR TITLE
Install dotnet when running smoke tests

### PR DESCRIPTION
**Pull request by pakrym**

### CODE REVIEW

**Comment by pakrym** [comment]
The build is past the original failure: 
image

**Review by AlexGhiondea — APPROVED** [review]

**Comment by pakrym** [comment]
Failures are USGov deployment failures

**Comment by jsquire** [comment]
US Gov deployment failures are related to an environment change that broke IoT Hub.  The engineering team and I have been discussing and will be following up next week if the Tuesday service deployment does not fix the issue.

**Pull request merged**
