### PR TITLE
AzureSecurityCenter - Update Microsoft.Security SDK generation

### PR DESCRIPTION
**Pull request by eliagrady**
Regenerate SDK & fix tests.
Missing ExternalSecuritySolutionsTests sessionRecords - should not block since current ones are invalid as well.

### CODE REVIEW

**Comment by eliagrady** [comment]
This only fixed existing code.
This PR did not add missing test coverage or fix any outstanding bugs - it provides a 'green' baseline to build from.

**Comment by eliagrady** [comment]
@YalinLi0312 \ @allenjzhang  Could you please follow the checklist below?
- [x] Swagger review PR(s) link in PR description, and the PR(s) is merged - _no specific swagger changes resulted in this PR_
- [x] Metadata file `eng/mgmt/mgmtmetadata_{RP}.txt` is updated
- [x] Versions in `*.csproj` and `AssemblyInfo.cs` are updated, and follows semver
- [x] Release notes in `*.csproj` is updated
- [x] If there's a API-version update, the API tags in `Az.Sdk.props` are updated - _please review this part_
- [x] Generated code is not touched
- [x] Proper test coverage

**Comment by eliagrady** [comment]
@allenjzhang , can you approve?

**Comment by m-nash** [comment]
@eliagrady can you link the swagger PR that this is associated with?

**Comment by eliagrady** [comment]
> @eliagrady can you link the swagger PR that this is associated with?

There are no specific changes in the API in this PR - this PR is regen of the SDK and adding test coverage.

**Comment by m-nash** [comment]
Typically a release of new swagger goes out ahead of the SDK.  The SDK is then regenerated off of that new swagger commit id (associated with the PR).  It appears from the metadata file that this was the swagger PR? https://github.com/Azure/azure-rest-api-specs/pull/11518  Is that correct?

**Comment by eliagrady** [comment]
> Typically a release of new swagger goes out ahead of the SDK. The SDK is then regenerated off of that new swagger commit id (associated with the PR). It appears from the metadata file that this was the swagger PR? [Azure/azure-rest-api-specs#11518](https://github.com/Azure/azure-rest-api-specs/pull/11518) Is that correct?

https://github.com/Azure/azure-rest-api-specs/pull/10100 is more likely - I believe there were a few merges to azure-rest-api-specs without SDK respective generations - this PR is indented to downsize this growing gap.

**Comment by eliagrady** [comment]
Here's a Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/10418 (I've added the missing tests for this one)

Can you please squash-merge-approve this?

**Review by m-nash — APPROVED** [review]
https://github.com/Azure/azure-rest-api-specs/pull/10100 was the one I was looking for which has the breaking change in it and the approved-breakingchange label.

**Comment by VeryEarly** [comment]
Hi @m-nash ,

This SDK doesn't have api version generated, is that expected?

**Pull request merged**
