### PR TITLE
Fix sample code error and content error of Azure Identity readme

### PR DESCRIPTION
**Pull request by wantedfast**
To fix issue #11330

### CODE REVIEW

**Review by schaabs — APPROVED** [review]

**Comment by jsquire** [comment]
@wantedfast:  This has been open for a bit in an approved state.   May I ask if there is a reason that it hasn't yet been merged?

**Comment by tzhanl** [comment]
@jsquire  can you help to merge? We can't merge.

**Comment by wantedfast** [comment]
@jsquire Could you please help me to merge this PR since I don't have the permission to do this.
Thanks in advance.

**Review by jsquire — APPROVED** [review]
LGTM

**Comment by jsquire** [comment]
> @jsquire Could you please help me to merge this PR since I don't have the permission to do this.
> Thanks in advance.

You got it.   Done!

**Pull request merged**
