### PR TITLE
Generate from latest api spec, bump version to 7.2.0-preview

### PR DESCRIPTION
**Pull request by yangyuan**

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Please add a link to the openapi spec review PR here and update the version in AssemblyInfo.cs as well.
Thanks

**Comment by yangyuan** [comment]
Hi, here is the link to swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/9298

**Comment by yangyuan** [comment]
and version updated. :)

**Review by isra-fel — APPROVED** [review]
LGTM

**Comment by isra-fel** [comment]
The failed data plane pipeline is not related to this PR and `net - mgmt - ci (Test MacOs)` failed because of ADO environment issue.

**Pull request merged**
