### PR TITLE
Restore Session Records for BackUp Admin

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Some strange gitignore behavior prevented these files from being added during directory restructure.

### CODE REVIEW

**Comment by chidozieononiwu** [comment]
@Azure/azure-sdk-eng

**Comment by weshaggard** [comment]
Did you double check to see if there were any other files dropped?

**Review by weshaggard — APPROVED** [review]

**Comment by chidozieononiwu** [comment]
> Did you double check to see if there were any other files dropped?

For AzureStack there are no other dropped files. I will have to look through the folders again to make this did not occur anywhere else.

**Pull request merged**
