### PR TITLE
Generate 2019-09-01 policy operations

### PR DESCRIPTION
**Pull request by pilor**
Re-generate SDK classes for Microsoft.Authorization/policy* entities.

Generated from the package-policy-2019-09 tag here:  https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @pilor , could you
- Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
  - If you have problem generating this file, please try [updating build tools](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools)
- Update api tag in `AzSdk.RP.props`

Thanks

**Comment by pilor** [comment]
@isra-fel Done.  Updating the tools and following those docs (instead of old methods which I was following) generated the content successfully.

**Comment by isra-fel** [comment]
Hi this file SDKs/_metadata/resources_resource-manager.txt is in the wrong path. Should be `eng/mgmt/mgmtmetadata/resources_resource-manager.txt`.

**Comment by pilor** [comment]
> Hi this file SDKs/_metadata/resources_resource-manager.txt is in the wrong path. Should be `eng/mgmt/mgmtmetadata/resources_resource-manager.txt`.

I found the problem.  If you enable the new [MSIT Onedrive backup](https://aka.ms/OneDriveBackup) of your desktop the target that installs the updated Powershell modules puts them in the wrong location.  It is placing them in C:\Users\cheggert\Documents\WindowsPowerShell\Mo
  dules\CodeGenerationModules\generateTemplate.ps1 instead of C:\Users\cheggert\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules which is where Powershell is looking for modules.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
