### PR TITLE
Add Key Vault-managed Storage sample

### PR DESCRIPTION
**Pull request by heaths**
This is a sample that contains generated code for a would-be Azure.Security.KeyVault.Storage, though we don't want to release a package for that since we want to encourage developers to RBAC. As such, this sample can only build in our repo since it requires shared source from Azure.Core we do not want to duplicate; however, I added a custom target - `CopySource` - that copies all relevant source files except the *.csproj* and *Program.cs*.

The idea - and I tested that this works - is someone can copy the would-be Azure.Security.KeyVault.Storage files to a new or existing project, and with a minimal *.csproj* (just need to reference Azure.Core and *maybe* update/set the `LangVersion` to 7.3 or newer) build the source.

The sample itself demonstrates several APIs in a functional manner: after following the initial steps to set up managed storage in <https://docs.microsoft.com/azure/key-vault/secrets/overview-storage-keys> this sample will generate timed tokens to generate a SAS token you can append to blob or file URIs.

### CODE REVIEW

**Comment by pakrym** [comment]
Feels like this sample has to be somewhere under keyvault

**Comment by heaths** [comment]
It's not specific to a package we have - in fact, the point is to produce a working "package". We don't have a precident for package "family"-level samples.

**Comment by pakrym** [comment]
Is it specific to keyvault? Can it go into `/sdk/keyvault/samples`?

**Comment by heaths** [comment]
Is that supported? Not sure if our hooks pick anything like that up. If so, that looks reasonable. /cc @maggiepint @jongio

**Comment by pakrym** [comment]
We should check and/or implement. The root samples directory is for cross-service samples and we would like to keep it reasonably clean. If the sample is service-specific it should go into a service directory.

**Review by schaabs — APPROVED** [review]

**Comment by heaths** [comment]
@jongio is fine with sdk/keyvault/samples so I'll move it when I add the README.md with front matter.

**Comment by heaths** [comment]
Alex also reviewed the README in our 1:1.

**Pull request merged**
