### PR TITLE
 [DataFactory]Update Rest Sink properties And Added support lzo in orc format, MongoDbAtlas Source Connector in DataFactory

### PR DESCRIPTION
**Pull request by Jingshu923**
Update Rest Sink properties Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/10815
Added support lzo in orc format: https://github.com/Azure/azure-rest-api-specs/pull/10886
Added MongoDbAtlas Source Connector in DataFactory:  https://github.com/Azure/azure-rest-api-specs/pull/10890

### CODE REVIEW

**Comment by bquantump** [comment]
Since the swagger PR was a breaking change, we need to bump the version for the SDK based on the new rules. @allenjzhang

**Review by kalyanrk61 — APPROVED** [review]

**Comment by Jingshu923** [comment]
@allenjzhang  @bquantump  Need I do some change to bump the version for the SDK based on the new rules, I don't know what it mean.

**Comment by bquantump** [comment]
> @allenjzhang @bquantump Need I do some change to bump the version for the SDK based on the new rules, I don't know what it mean.

Follow this:

 Swagger review PR(s) link in PR description, and the PR(s) is merged
 Metadata file eng/mgmt/mgmtmetadata_{RP}.txt is updated
 Versions in *.csproj and AssemblyInfo.cs are updated,
 Release notes in *.csproj is updated
 If there's a API-version update, the API tags in Az.Sdk.props are updated
 Generated code is not touched

**Comment by Jingshu923** [comment]
@bquantump   These things I have updated, could you please review it again?

**Comment by bquantump** [comment]
> @bquantump These things I have updated, could you please review it again?

Were are the version bumps
Versions in *.csproj and AssemblyInfo.cs are updated, and follows semver

**Comment by Jingshu923** [comment]
@bquantump  The versions will be updated in the PR after our sdk release, so this PR will not  update version.

**Review by bquantump — APPROVED** [review]

**Pull request merged**
