### PR TITLE
Azure Security Center - Added support for IoT security endpoints

### PR DESCRIPTION
**Pull request by amiramit**
link to the spec review PR: Azure/azure-rest-api-specs#7047

### CODE REVIEW

**Review by erich-wang — CHANGES_REQUESTED** [review]
@amiramit,  please follow the [instruction](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec) to:
- add a link to the spec review PR in the description
- Update Version, tags if necessary
- One .txt should be generated under `eng\mgmt\mgmtmetadata` if you use generate.ps1
- Fix merge conflicts

**Comment by amiramit** [comment]
Done. Thanks for the comments.

**Comment by amiramit** [comment]
Done rebase on master. Note that only new tests which I've added passes for me now, rest are failing with error similar to:

Message: System.ArgumentException : Unable to find recorded mock file 'C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.Management.SecurityCenter.Tests\Debug\netcoreapp2.0\SessionRecords\**SecurityCenter.Tests.**AdvancedThreatProtectionTests\AdvancedThreatProtection_CreateOrUpdate.json'.
Parameter name: callerIdentity


I see these recorded mock files do exists but without the **SecurityCenter.Tests.** prefix.

Can you please advise?

**Comment by erich-wang** [comment]
> Done rebase on master. Note that only new tests which I've added passes for me now, rest are failing with error similar to:
> 
> Message: System.ArgumentException : Unable to find recorded mock file 'C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.Management.SecurityCenter.Tests\Debug\netcoreapp2.0\SessionRecords**SecurityCenter.Tests.**AdvancedThreatProtectionTests\AdvancedThreatProtection_CreateOrUpdate.json'.
> Parameter name: callerIdentity
> 
> I see these recorded mock files do exists but without the **SecurityCenter.Tests.** prefix.
> 
> @erich-wang , Can you please advise?

@amiramit, please do a full replacement in your test project:
Replace `this.GetType().FullName` with `this.GetType()`

**Comment by amiramit** [comment]
> > Done rebase on master. Note that only new tests which I've added passes for me now, rest are failing with error similar to:
> > Message: System.ArgumentException : Unable to find recorded mock file 'C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.Management.SecurityCenter.Tests\Debug\netcoreapp2.0\SessionRecords**SecurityCenter.Tests.**AdvancedThreatProtectionTests\AdvancedThreatProtection_CreateOrUpdate.json'.
> > Parameter name: callerIdentity
> > I see these recorded mock files do exists but without the **SecurityCenter.Tests.** prefix.
> > @erich-wang , Can you please advise?
> 
> @amiramit, please do a full replacement in your test project:
> Replace `this.GetType().FullName` with `this.GetType()`

Done

**Comment by isra-fel** [comment]
Hi @amiramit , please 
1. add the link to swagger review PR in description
1. and update `AssemblyFileVersion` in `AssemblyInfo.cs`

**Comment by amiramit** [comment]
> * d the link to swagger review PR in description
> * and update `AssemblyFileVersion` in `AssemblyInfo.cs`
>   Thanks
1. Not sure how to edit in description - I've put the link in what seems to be first comment and it's also in the commit description. Lmk if you want me to update it anywhere else. For reference here it is again: link to the spec review PR: Azure/azure-rest-api-specs#7047
* Updated AssemblyVersion and AssemblyFileVersion from 1.0.0.0 to 1.0.1.0. Is that ok?

**Comment by amiramit** [comment]
> Hi @amiramit , please
> 
> 1. add the link to swagger review PR in description
> 2. and update `AssemblyFileVersion` in `AssemblyInfo.cs`
>    Thanks

1. Not sure how to edit in description - I've put the link in what seems to be first comment and it's also in the commit description. Lmk if you want me to update it anywhere else. For reference here it is again: link to the spec review PR: Azure/azure-rest-api-specs#7047
2. Upated AssemblyVersion and AssemblyFileVersion from 1.0.0.0 to 1.0.1.0. Is that ok?

**Comment by isra-fel** [comment]
> 1. Not sure how to edit in description - I've put the link in what seems to be first comment and it's also in the commit description. Lmk if you want me to update it anywhere else. For reference here it is again: link to the spec review PR: [Azure/azure-rest-api-specs#7047](https://github.com/Azure/azure-rest-api-specs/pull/7047)
> 2. Upated AssemblyVersion and AssemblyFileVersion from 1.0.0.0 to 1.0.1.0. Is that ok?

@amiramit 
1. I suppose description and the first comment are the exact same thing so it is perfectly OK 😄 
1. Update only `AssemblyFileVersion` to `1.0.1.0` please. `AssemblyVersion` should be updated when there's a major version change

Thanks

**Comment by amiramit** [comment]
> > 1. Not sure how to edit in description - I've put the link in what seems to be first comment and it's also in the commit description. Lmk if you want me to update it anywhere else. For reference here it is again: link to the spec review PR: [Azure/azure-rest-api-specs#7047](https://github.com/Azure/azure-rest-api-specs/pull/7047)
> > 2. Upated AssemblyVersion and AssemblyFileVersion from 1.0.0.0 to 1.0.1.0. Is that ok?
> 
> @amiramit
> 
> 1. I suppose description and the first comment are the exact same thing so it is perfectly OK 😄
> 2. Update only `AssemblyFileVersion` to `1.0.1.0` please. `AssemblyVersion` should be updated when there's a major version change
> 
> Thanks

done

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
