### PR TITLE
Event Grid: Add missing pagination support to listing nested event subscriptions

### PR DESCRIPTION
**Pull request by Brandon411**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by fengzhou-msft** [comment]
What is the release plan? I do not see a version update in csproj file and AssemblyInfo.cs in this PR.

**Comment by Brandon411** [comment]
> What is the release plan? I do not see a version update in csproj file and AssemblyInfo.cs in this PR. Considering this is a breaking change, we need to bump the major version.

We got approval from ARM to update the swagger with the missing pagination as a breaking change without bumping the version number. https://github.com/Azure/azure-rest-api-specs/pull/18895

**Comment by Brandon411** [comment]
I have updated the version from 7.1.0 to 7.1.1.

**Comment by Brandon411** [comment]
Updated the major version because of the breaking change

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
