### PR TITLE
Remove workaround for final-state-schema

### PR DESCRIPTION
**Pull request by live1206**
Cleanup after resolving https://github.com/Azure/autorest.csharp/issues/3546

### CODE REVIEW

**Review by archerzz — APPROVED** [review]

**Comment by archerzz** [comment]
Is there a preview PR?

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by live1206** [comment]
> Is there a preview PR?

The generated SDK remain the same during the CI, no preview PR needed.

**Comment by live1206** [comment]
> Is there a preview PR?

Tried to check the output of `autorest.core`, there is no difference with or without this change.

**Comment by archerzz** [comment]
> > Is there a preview PR?
> 
> Tried to check the output of `autorest.core`, there is no difference with or without this change.

Thanks

**Pull request merged**
