### PR TITLE
Network- 2022-05-01 release

### PR DESCRIPTION
**Pull request by htippanaboya**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by ArthurMa1978** [comment]
Please make sure this is only for private build not publish to nuget

**Comment by MikhailTryakhov** [comment]
>> Please make sure this is only for private build not publish to nuget

But actually why? Azure Networking is not ready yet for track 2, so we need to update track 1...

**Comment by m-nash** [comment]
merged in a separate pr to non main branch https://github.com/Azure/azure-sdk-for-net/pull/31291

**Comment by MikhailTryakhov** [comment]
reopened due to we need to merge this changes due to they have actual info

**Pull request merged**
