### PR TITLE
Added EnvironmentConnectionStringCredential to support AzureServicesAuthConnectionString

### LINKED ISSUE #17652: [FEATURE REQ] Azure.Identity doesn't support AzureServicesAuthConnectionString
**Library or service name.**

`Azure.Identity`
 
**Is your feature request related to a problem? Please describe.**

Rather a regression as the old library `Microsoft.Azure.Services.AppAuthentication` did support.

**Problem statement:**

Let's start from the fact that over the years the Managed Identity team refused to provide the support for [local development](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication#local-development-authentication), told to go elsewhere.

The now-legacy library `AppAuthentication` has the built-in fallback mechanism via environment variable `AzureServicesAuthConnectionString` which would be used instead of a managed identity and enable to run the service code locally.

Moreover, the connection string could point to a certificate in the store that marked as non-exportable, see more below.

In the new `Azure.Identity` the support for a connection string is absent.

**Details:**

Currently I'm using [DefaultAzureCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) which by default would fallback to (among others):

- [ManagedIdentityCredential](
https://docs.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet)
- [EnvironmentCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet)

The problem with the latter is that it supports only the following [environment variables](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#environment-variables) in the scope of a certificate:

- AZURE_TENANT_ID
- AZURE_CLIENT_ID
- AZURE_CLIENT_CERTIFICATE_PATH

What means:

1. If the path to a certificate is checked in under the source control then it means it's hard-coded and must be same for every engineer on a 25-person team
2. It must be a pfx what means it's an "open" secret. In the contrast to its imported version in the store which is makers as non-exportable

**Potential workaround (which I don't see would work)**:

I could've used [ChainedTokenCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.chainedtokencredential?view=azure-dotnet) with:
- [ManagedIdentityCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet)
- [ClientCertificateCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientcertificatecredential?view=azure-dotnet)

The problem with the latter that it doesn't support lazy loading of a certificate: it must be present at the time of construction. In production the certificate won't be present and [the ctor will throw exception](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/ClientCertificateCredential.cs#L121).

What means that there is no one-fits-all solution that will fallback automatically, I need to manually detect whether the code is running locally or not and use the appropriate subtype of [token credential](https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet). I even potentially can parse the connection string from the environment variable myself. But I rather would prefer the library to do it for me.

**Potential solution:**

- Add a constructor parameter accepting `Func<X509Certificate2> certificateFactory`
- Add a constructor parameter accepting `string thumbprint` and/or `string subjectName`
- Add a constructor parameter indicating lazy loading `bool lazyLoad`

### PR DESCRIPTION
**Pull request by abatishchev**
Resolves #17652.

### CODE REVIEW

**Comment by jsquire** [comment]
@schaabs, @christothes:  Would you please be so kind as to offer your thoughts?

**Comment by schaabs** [comment]
I've discussed this with @abatishchev offline and we decided to create a PR to merge this into the [Azure Identity Extensions](https://github.com/jongio/azidext) rather than Azure.Identity directly since the target of that library is applications transistioning from Track 1. I'm currently working on a PR for this and will link to it here once it's available. I'm closing this PR.

**Comment by kitkitkemik** [comment]
@schaabs was this ever merged into [Azure Identity Extensions](https://github.com/jongio/azidext) ?

**Comment by Darko-git** [comment]
@schaabs this does not seem to be merged, what is the plan going forward?

**Pull request closed without merging**
