### PR TITLE
[Compute] SDK version from 2023-10-02

### PR DESCRIPTION
**Pull request by haagha**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

Swagger PR https://github.com/Azure/azure-rest-api-specs/pull/27120

### CODE REVIEW

**Review by archerzz — APPROVED** [review]
LGTM. If you are going to release a new version, don't forget to update `CHANGELOG.md`. See [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=signing-and-publishing-nuget-packges) for details.

**Comment by haagha** [comment]
@archerzz when will 1.4.0-beta.1 be released?

**Comment by archerzz** [comment]
> @archerzz when will 1.4.0-beta.1 be released?

@haagha Please update the release date in `	CHANGELOG.MD`. Right now the release date is not updated:
> ## 1.4.0-beta.1 (Unreleased)

**Comment by haagha** [comment]
Updated Changelog to add release date.

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
