### PR TITLE
[Azure.Monitor.Query]Update tests.yml

### PR DESCRIPTION
**Pull request by nisha-bhatia**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by pallavit** [comment]
Why are we onboarding monitor ingestion, query to national cloud? Is this purely for supporting the customer ask?

**Comment by nisha-bhatia** [comment]
> Why are we onboarding monitor ingestion, query to national cloud? Is this purely for investigating the customer ask?

This PR is only for testing sovereign cloud support - I do not intend to merge it :)

**Comment by pallavit** [comment]
> This PR is only for testing sovereign cloud support - I do not intend to merge it :)

It may be easier to run the test locally if you would like to debug this further.

**Comment by JoshLove-msft** [comment]
> > This PR is only for testing sovereign cloud support - I do not intend to merge it :)
> 
> It may be easier to run the test locally if you would like to debug this further.

Is there an issue with debugging using the test pipelines? It seems easier than deploying test resources locally to China region.

**Comment by nisha-bhatia** [comment]
Will be addressed in May milestone

**Pull request closed without merging**
