### PR TITLE
[NO MERGE] Added AsyncEnumerable-based ConfigurationClient.GetAll

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
This is just an illustration, thus NO MERGE.

This PR illustrates how we can use C#8's async enumerable / foreach support to expose service call operations that return large number of items through batch operations.

Here are some caveats with the approach:
1. It somewhat hides service calls.
2. In .NET Core 3.0, there is a support for async yield return. Since we want the SDKs to work on .NET Framework and older versions of .NET Core, the async enumerators need to be implemented manually, i.e. without using yield return.
3. We cannot expose IAsyncEnumerable<T> as it exists in .NET Core 3.0 only. Instead the solution relies on duck typing (pattern) to be able to foreach the nested Enumerator class.
4. I need to think what to do with errors, quotas, access to headers, etc. in MoveNext. 
5. I am not sure what to do with the cancellation token passed to GetAsyncEnumerator. The token is passed by the compiler when the foreach statement used WithCancellation. But then, I would need to create a new instance in GetAsyncEnumerator, which I was trying to avoid (for various reasons). I will think about it more.

```c#
await foreach (var result in GetAllAsync(batchOptions).WithCancellation(token)) { ...}
```

Lastly, the build fails in the lab as I don't think it can pull C#8.0. It does build and run fine on my lacal machine with VS2019 Preview 3 installed. cc: @weshaggard 

UPDATE: changed the code such that it now does not require C#8.0, but if the caller has C#8.0, they can use nicer syntax.

UPDATE: added the ability to enumerate batches. I think we should consider changing our GetBatch APIs to it, i.e.  hide the GetBatch API.

### CODE REVIEW

**Comment by bterlson** [comment]
I like this approach, although it comes with downsides you mention: abstracts very much how many actual service calls are happening (which I think will manifest with harder error handling/recovery as well). I also vaguely worry that APIs like this would be a footgun - you want to use it because it's convenient, but it does too much and costs too much. If it's rare in practice that users want to list and then get every item in a list, this design could cause some harm. If it's common, services should maybe consider lifting the properties users need when listing into the list response payload rather than requiring a subsequent get.

I attacked this same problem a bit differently in this [storage gist](https://gist.github.com/bterlson/5c67ba57fe612e478c7a5bfc84dbf5e5#file-storage-pref-js-L46), rather than getting each item, I just provide an async iterator over pages. This is a huge improvement over the non-async iterator code, but preserves a tighter mapping between code and service calls and also I think will make error handling and recovery more straightforward. I also have a dream that JS will get itertools eventually, allowing for such code as `for (const item = service.listItems().flatMap(page => page.items)) { }`.

Possibly also relevant is this [service bus PR](https://github.com/Azure/azure-sdk-for-js/pull/1279). Async iterators are a nice way to consume a queue.

**Review by bterlson — APPROVED** [review]

**Comment by johanste** [comment]
I'm very curious about use cases where we believe that the client will abort the loop before reading all data (which is one of the concerns that I keep hearing about w. regards to the danger of the providing an enumerator of the items). 

I understand the second concerns that is typically raised (too much stuff to get into memory), but for that case, my assumption is that one would chain the enumerator (using pipes or whatever construct the language prefers) into a consumer accepting a stream/enumerator whatever.

**Comment by bterlson** [comment]
To some approximation, all the scenarios that drive a service to paginate results would also apply to client applications. If the client application needs to provide a paginated view of things and the page size from the service can't be controlled, breaking out early seems likely. I can also imagine clients wanting to search through pages until they find N things they're looking for.

I would bet if we looked at twitter API usage, the vast majority of queries for tweets in a timeline are getting a subset of all the tweets. Getting all the tweets would be super time consuming and costly.

**Comment by KrzysztofCwalina** [comment]
PR #6220 properly productizes this draft PR

**Pull request closed without merging**
