### PR TITLE
[Storage][DataMovement] Fixed bug when downloading zero length blobs in a directory will throw an exception

### PR DESCRIPTION
**Pull request by amnguye**
When attempting to download a zero length `StorageResource` (or blob) in a `StorageResourceContainer` (or directory/container) an exception will be thrown because the `DownloadChunkHandler` is being enabled without any data to be really transferred.

### CODE REVIEW

**Comment by amnguye** [comment]
For the live test pipelines we want to see our empty / 0 length file in directory upload to pass.

Known live pipeline failures include the AESGcM Mac OS tests and the StartTransfer Download Directory tests as well. (The Start Transfer Download DIrectory live tests will be fixed in a separate PR).

**Review by jalauzon-msft — APPROVED** [review]

**Pull request merged**
