### PR TITLE
Remove broken links in README.md and update test scenario

### PR DESCRIPTION
**Pull request by bquantump**

### CODE REVIEW

**Review by nisha-bhatia — CHANGES_REQUESTED** [review]
On Line 57 and 65 of the cs file, are the CreateOrUpdate methods supposed to be LROs?

**Comment by bquantump** [comment]
> On Line 57 and 65 of the cs file, are the CreateOrUpdate methods supposed to be LROs?

No, LRO start with "start" in track 2

**Review by nisha-bhatia — APPROVED** [review]

**Review by YalinLi0312 — COMMENTED** [review]
Just see updates in one unit test `delete`, pls also update in the rest tests.

**Comment by bquantump** [comment]
> Just see updates in one unit test `delete`, pls also update in the rest tests.

I'm only testing it once, don't need to wait on the others

**Review by YalinLi0312 — APPROVED** [review]

**Pull request merged**
