### PR TITLE
Classifier for Expected Errors in `BlobBaseClient.Exists()`

### LINKED ISSUE #18592: [BUG] BlobBaseClient.Exists always logs exceptions to App Insights when the blob does not exist.
**Describe the bug**
BlobBaseClient.Exists files lots of false exceptions in App Insights when the blob does not exist.

**Expected behavior**
Checking if a blob exists should simply return false, not log an exception in App Insights.

**Actual behavior (include Exception or Stack Trace)**
App Insights is littered with false-positive exceptions due to a 404 response code to a HEAD request.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create an app that connects to a valid blob storage
2. Enable AppInsights
3. Access BlobBaseClient.Exists for a blob you know does not exist
4. Look in AppInsights

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.4.4
 - Hosting platform or OS and .NET runtime version: Azure Function app (net core 3.1)

The problem seems to be here
https://github.com/Azure/azure-sdk-for-net/blob/f01cbdc6b939331123af0c682892f3f478350f27/sdk/storage/Azure.Storage.Queues/src/Generated/ServiceRestClient.cs#L162

The code throws an exception for anything other than a 200 response - but 404 is not an exceptional response, it is very much expected - in fact, I expect to call it for non-existent blobs more often than any other blob scenario.

Ultimately, the exception is swallowed here
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L2952

But, by this point in time, the exception has already been logged to App Insights.

### PR DESCRIPTION
**Pull request by jaschrep-msft**
Resolves #18592

Classifies expected HTTP failures from GET BlobProperties as not errors when calling from `BlobBaseClient.Exists()`.

### CODE REVIEW

**Review by amnguye — APPROVED** [review]

**Comment by benbp** [comment]
@jaschrep-msft there was an issue with `/check-enforcer reset` that caused the above behavior. It's fixed now for future reference.

**Comment by janid1967** [comment]
In which release will this be available? I guess it is not released yet, ref: https://github.com/Azure/azure-sdk-for-net/blob/Azure.Storage.Blobs_12.14.1/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md

**Comment by ChristopherLenz** [comment]
I have upgraded to the latest version (12.15.1). From what I can see, there shouldn't be any errors appearing in the trace anymore. Unfortunately, this is still the case. We are using methods such as `CreateIfNotExists`. Technically, it shouldn't be classified as an error anymore, right?

azure_404

**Comment by jaschrep-msft** [comment]
> I have upgraded to the latest version (12.15.1). From what I can see, there shouldn't be any errors appearing in the trace anymore. Unfortunately, this is still the case. We are using methods such as `CreateIfNotExists`. Technically, it shouldn't be classified as an error anymore, right?

This change does not affect the HTTP status code from the Storage service, which doesn't expose a separate "exists" mechanism. This change prevents the Azure SDK logging system from logging the response as an error.

**Pull request merged**
