### PR TITLE
[Storage] [DataMovement] Added separate sln file for Storage Data Movement and start of stress testing for DM Blobs

### PR DESCRIPTION
**Pull request by amnguye**
- Added a separate .sln specific for DataMovement
- Added starting structure for stress testing for DataMovement Blobs

### CODE REVIEW

**Comment by jaschrep-msft** [comment]
Is there a reason we're using a `.sln` instead of a `.slnf`? It seems this is just a subset of the base Azure.Storage.sln and so the latter just makes more organizational sense.

**Comment by amnguye** [comment]
> Is there a reason we're using a `.sln` instead of a `.slnf`? It seems this is just a subset of the base Azure.Storage.sln and so the latter just makes more organizational sense.

Eventually we're going to remove the DataMovement projects out of the Azure.Storage.sln and will only live in the Azure.Storage.DataMovement.sln. Like how WebJobs Storage Extension currently lives.

I also enjoyed the fact that I could use the solution explorer without having to scroll since half of this is unloaded.

Azure.Storage.sln with the filter
image

Azure.Storage.DataMovement.sln

image

**Review by jaschrep-msft — APPROVED** [review]

**Pull request merged**
