### PR TITLE
remove some redundant state machines

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by pakrym** [comment]
Hi, thank you for the contribution,


In azure-sdk-for-net we are avoiding this optimization to keep the code easier to maintain unless the code path is performance-critical.

**Comment by SimonCropp** [comment]
does this change make it more difficult to maintain?

**Comment by pakrym** [comment]
What is the benefit of this change?

**Comment by SimonCropp** [comment]
better perf. and i had assumed things like async  serialization and request interactions would be on the fast path?

**Comment by pakrym** [comment]
To respond to your question.

>does this change make it more difficult to maintain?

Yes, we had cases where someone added a try/catch around code like this or use a using clause without realizing how the flow works and had unexpected consequences. That's why we only make this change in places where it provably matters.

**Comment by SimonCropp** [comment]
fair enough. i would have though some of these were on the fast path. but will close :)

**Comment by pakrym** [comment]
The one in JsonObjectSerializer is, happy to take the PR if we scope it down to that.

**Pull request closed without merging**
