### PR TITLE
[Search] Add option to not throw when doc does not exist

### PR DESCRIPTION
**Pull request by Mohit-Chakraborty**

### CODE REVIEW

**Comment by Mohit-Chakraborty** [comment]
#17445

**Review by bitsforthought — APPROVED** [review]

**Comment by Mohit-Chakraborty** [comment]
cc: @tg-msft

**Comment by tg-msft** [comment]
Can we hold off on this for a week or two while we wait for https://gist.github.com/KrzysztofCwalina/21dc06df369ad85d3b3d8e868227630f to settle?  It's trying to solve the same problem more generally and I'd like to make sure the APIs/approaches align.

**Comment by Mohit-Chakraborty** [comment]
> Can we hold off on this for a week or two while we wait for https://gist.github.com/KrzysztofCwalina/21dc06df369ad85d3b3d8e868227630f to settle? It's trying to solve the same problem more generally and I'd like to make sure the APIs/approaches align.

Sure. I was not aware of that initiative. Would love to participate and contribute to a unified approach.

**Pull request closed without merging**
