### PR TITLE
Rename Files to Files.Shares

### LINKED ISSUE #8477: Storage: Rename Files to Files.Shares

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Fixes #8477

### CODE REVIEW

**Comment by tg-msft** [comment]
To any potential reviewers - please skim #8477 first to see all the renames in one place.

**Review by tg-msft — APPROVED** [review]
Nice!  Thank you very much.  That was a massive rename and I appreciate you getting it done so quickly.

**Review by seanmcc-msft — COMMENTED** [review]
Looks good.

**Review by amnguye — APPROVED** [review]

**Comment by mitchdenny** [comment]
You'll need to update ```sdk/storage/ci.yml``` if you intend this package to be releasable via the pipelines.

**Pull request merged**
