### PR TITLE
Style Checking Storage Common, Files and Queues

### PR DESCRIPTION
**Pull request by chidozieononiwu**

### CODE REVIEW

**Comment by pakrym** [comment]
Azure.Core again

**Comment by chidozieononiwu** [comment]
> Azure.Core again

Was still working on the PR. Core changes are now removed.

**Comment by pakrym** [comment]
You can use [draft feature ](https://github.blog/2019-02-14-introducing-draft-pull-requests/)if PR is still work in progress

**Review by tg-msft — APPROVED** [review]
Thank you Dozie!

**Review by seanmcc-msft — APPROVED** [review]

**Pull request merged**
