### PR TITLE
customization fix 

### PR DESCRIPTION
**Pull request by grizzlytheodore**
Need to update customization. Is giving build error when using this package in PowerShell https://github.com/Azure/azure-powershell/pull/15801

Looked at all the customization files and cleaned up ones that needed clean up. All the overload constructors in the customization files should not have any default parameter values. Default parameter values should come from the generated constructor. 

Logic: 
#Old version
int Foo( int bar, string baz=default(string);

#New version
int Foo(int bar, float bar2=default(float), string baz=default(string))

#customization 
int Foo(int bar, string baz)

initialization like this: Foo(1) 
should be using generated constructor (#New version)
if #customization had default parameter value like this: 
int Foo(int bar, string baz=default(string))
we would get build error from having two constructor signatures to choose from. (this is what is happening in the powershell build) 

# All SDK Contribution checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] **Please open PR in `Draft` mode if it is:**
	- Work in progress or not intended to be merged.
	- Encountering multiple pipeline failures and working on fixes.
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md).**

### [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code. (Track 2 only)
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK. Please double check nuget.org current release version.

## Additional management plane SDK specific contribution checklist: 
Note: Only applies to `Microsoft.Azure.Management.[RP]` or `Azure.ResourceManager.[RP]`
 
- [ ] Include updated [management metadata](https://github.com/Azure/azure-sdk-for-net/tree/main/eng/mgmt/mgmtmetadata).
- [ ] Update AzureRP.props to add/remove version info to maintain up to date API versions.

### Management plane SDK Troubleshooting
- If this is very first SDK for a services and you are adding new service folders directly under /SDK, please add `new service` label and/or contact assigned reviewer.
- If the check fails at the `Verify Code Generation` step, please ensure:
	- Do not modify any code in generated folders.
	- Do not selectively include/remove generated files in the PR.
	- Do use `generate.ps1/cmd` to generate this PR instead of calling `autorest` directly.
	Please pay attention to the @microsoft.csharp version output after running `generate.ps1`. If it is lower than current released version (2.3.82), please run it again as it should pull down the latest version.
	
	**Note: We have recently updated the PSH module called by `generate.ps1` to emit additional data. This would help reduce/eliminate the Code Verification check error. Please run following command**:

	    `dotnet msbuild eng/mgmt.proj /t:Util /p:UtilityName=InstallPsModules`

### Old outstanding PR cleanup
 Please note:
	If PRs (including draft) has been out for more than 60 days and there are no responses from our query or followups, they will be closed to maintain a concise list for our reviewers.

### CODE REVIEW

**Comment by VeryEarly** [comment]
@grizzlytheodore can you help understand why these customizations are necessary?
for instance: https://github.com/Azure/azure-sdk-for-net/blob/9d38a8a8ec8a47b68caf9fcfe222a67139fc2841/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations/VirtualMachinesOperations.cs#L113-L121

The only reason I can think of is to hide parameter "bool? hibernate = default(bool?)", still the original method is public and has default value for this parameter, I don't see how the customization can stop customer to use this parameter.

Also if this customization is needed, 
```
public async Task<AzureOperationResponse> DeallocateWithHttpMessagesAsync(string resourceGroupName, string vmName, Dictionary<string, List<string>> customHeaders, CancellationToken cancellationToken = default(CancellationToken))
```
is enough, what is the purpose to have https://github.com/Azure/azure-sdk-for-net/blob/9d38a8a8ec8a47b68caf9fcfe222a67139fc2841/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations/VirtualMachinesOperations.cs#L118-L121

**Review by archerzz — CHANGES_REQUESTED** [review]
@grizzlytheodore Since it's a new version, you may want to update [compute_resource-manager.txt](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/mgmt/mgmtmetadata/compute_resource-manager.txt)

**Comment by VeryEarly** [comment]
if I call 
```
DeallocateWithHttpMessagesAsync("rg", "vm",  new Dictionary<string, List<string>>, default(CancellationToken))
```
will it not complain by compiler?
https://github.com/Azure/azure-sdk-for-net/blob/9d38a8a8ec8a47b68caf9fcfe222a67139fc2841/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations/VirtualMachinesOperations.cs#L113
https://github.com/Azure/azure-sdk-for-net/blob/feature/cplat-fixCustomization/sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/VirtualMachinesOperations.cs#L792

**Comment by VeryEarly** [comment]
@archerzz I'm wondering how the previous PR passed CI with apparent bug. I think some test cases are needed to prevent bad SDK being published.

**Comment by grizzlytheodore** [comment]
> @grizzlytheodore Since it's a new version, you may want to update [compute_resource-manager.txt](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/mgmt/mgmtmetadata/compute_resource-manager.txt)

what do I need to change in that file? the swagger file stayed the same.

**Comment by grizzlytheodore** [comment]
> @grizzlytheodore can you help understand why these customizations are necessary?
> for instance:
> 
> https://github.com/Azure/azure-sdk-for-net/blob/9d38a8a8ec8a47b68caf9fcfe222a67139fc2841/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations/VirtualMachinesOperations.cs#L113-L121
> 
> The only reason I can think of is to hide parameter "bool? hibernate = default(bool?)", still the original method is public and has default value for this parameter, I don't see how the customization can stop customer to use this parameter.
> 


To answer this first part, there may have been existing scripts that use the class like this: 
public async Task<AzureOperationResponse> DeallocateWithHttpMessagesAsync(string resourceGroupName, string vmName, Dictionary<string, List<string>> customHeaders)

but the default constructor changed to 
Task<AzureOperationResponse> DeallocateWithHttpMessagesAsync(string resourceGroupName, string vmName, bool? hibernate = default(bool?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

So to preserve the initialization that may already exist without the hibernate parameter, we add the customization 
> Also if this customization is needed,
> 
> ```
> public async Task<AzureOperationResponse> DeallocateWithHttpMessagesAsync(string resourceGroupName, string vmName, Dictionary<string, List<string>> customHeaders, CancellationToken cancellationToken = default(CancellationToken))
> ```
> 
> is enough, what is the purpose to have
> 
> https://github.com/Azure/azure-sdk-for-net/blob/9d38a8a8ec8a47b68caf9fcfe222a67139fc2841/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations/VirtualMachinesOperations.cs#L118-L121

**Comment by VeryEarly** [comment]
> @VeryEarly
> 
> > @grizzlytheodore can you help understand why these customizations are necessary?
> > for instance:
> > https://github.com/Azure/azure-sdk-for-net/blob/9d38a8a8ec8a47b68caf9fcfe222a67139fc2841/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations/VirtualMachinesOperations.cs#L113-L121
> > 
> > The only reason I can think of is to hide parameter "bool? hibernate = default(bool?)", still the original method is public and has default value for this parameter, I don't see how the customization can stop customer to use this parameter.
> 
> To answer this first part, there may have been existing scripts that use the class like this:
> public async Task DeallocateWithHttpMessagesAsync(string resourceGroupName, string vmName, Dictionary<string, List> customHeaders)
> 
> but the default constructor changed to
> Task DeallocateWithHttpMessagesAsync(string resourceGroupName, string vmName, **bool? hibernate = default(bool?)**, Dictionary<string, List> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
> 
> So to preserve the initializations that may already exist without the hibernate parameter, we add the customization
> 
> > Also if this customization is needed,
> > ```
> > public async Task<AzureOperationResponse> DeallocateWithHttpMessagesAsync(string resourceGroupName, string vmName, Dictionary<string, List<string>> customHeaders, CancellationToken cancellationToken = default(CancellationToken))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is enough, what is the purpose to have
> > https://github.com/Azure/azure-sdk-for-net/blob/9d38a8a8ec8a47b68caf9fcfe222a67139fc2841/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations/VirtualMachinesOperations.cs#L118-L121
> 
> For this second part, that is indeed enough.
> I was following the convention that I found when I began adding on to this, which is having all the parameters be mandatory and having a signature for each increment. But somewhere along the way some people (including me) forgot to make the parameters mandatory.
> 
> But I do agree with you that if we made it mandatory for the parameter that comes directly after the newly added parameter that changed the signature, and all the parameters following it optional, there would be less redundancy and would work the same.
> 
> @markcowl could you provide your thoughts?

Hi @grizzlytheodore 
Got it, thanks!

**Comment by archerzz** [comment]
> > @grizzlytheodore Since it's a new version, you may want to update [compute_resource-manager.txt](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/mgmt/mgmtmetadata/compute_resource-manager.txt)
> 
> @archerzz what do I need to change in that file? the swagger file stayed the same.

You're correct. It's the commit ID of change in swagger. No need to change.

**Comment by archerzz** [comment]
> @archerzz I'm wondering how the previous PR passed CI with apparent bug. I think some test cases are needed to prevent bad SDK being published.

The test cases are up to the service team. From our side, we could seek a linter tool to help detect potential problems. For the cases above, Visual Studio won't show any warning/error.

**Review by archerzz — APPROVED** [review]

**Pull request merged**
