### PR TITLE
Redis track 1 .NET SDK 2022-06-01 API version updates

### PR DESCRIPTION
**Pull request by austintolani**
**Summary**
These changes contain the newly generated code for the `Microsoft.Azure.Management.Redis` package based on the new `2022-06-01` API version. This generation actually includes new code for changes made in both the `2022-06-01` and `2022-05-01` API versions:
- [OpenAPI specification changes for 2022-06-01 API version](https://github.com/Azure/azure-rest-api-specs/pull/20869)
- [OpenAPI specification changes for 2022-05-01 API version](https://github.com/Azure/azure-rest-api-specs/pull/19506)

**Testing**

I have added unit tests and functional tests (with updated recorded session results) to test the newly generated code.

### CODE REVIEW

**Review by Yao725 — CHANGES_REQUESTED** [review]
Hi @austintolani, as we announced the [deprecation](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/) for Track 1 .NET SDK, we can't release Track 1 SDK anymore. If you still need this release, you need to provide the business impact or other strong justification of this release for @ArthurMa1978.

**Review by Yao725 — APPROVED** [review]
Thanks for the clarification @austintolani, approved with comment.

**Comment by austintolani** [comment]
@Yao725 thanks for the review. Could you merge the PR as well? Merging is blocked for me.

**Comment by Yao725** [comment]
@austintolani, merged. By the way, I believe if you want to release track 1 SDK, you should follow this [guide](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=track-1-sdk-signing-and-publishing-nuget-packages) and go to run the net - mgmt pipeline. Considering it is not a public release, please **do not select** `ShouldPublishToNuget`, which will publish the package to nuget.

**Comment by austintolani** [comment]
Will do. Thanks for your help @Yao725

**Pull request merged**
