### PR TITLE
[Crash consistent RestorePoints]SDK changes

### PR DESCRIPTION
**Pull request by prchin**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by Yao725 — CHANGES_REQUESTED** [review]
Could you please fix the broken pipeline?

**Review by grizzlytheodore — APPROVED** [review]

**Review by Yao725 — APPROVED** [review]
Do we need to merge this PR now? @prchin @grizzlytheodore

**Review by shahja1 — APPROVED** [review]

**Pull request merged**
