### PR TITLE
Added secure score operations

### PR DESCRIPTION
**Pull request by giromm2ms**
Swagger review PR(s):
https://github.com/Azure/azure-rest-api-specs/pull/11133
https://github.com/Azure/azure-rest-api-specs/pull/11262

V Swagger review PR(s) link in PR description, and the PR(s) is merged
 Metadata file eng/mgmt/mgmtmetadata_{RP}.txt is updated
V Versions in *.csproj and AssemblyInfo.cs are updated, and follows semver
V Release notes in *.csproj is updated
V If there's a API-version update, the API tags in Az.Sdk.props are updated
V Generated code is not touched
V Proper test coverage

### CODE REVIEW

**Comment by giromm2ms** [comment]
Waiting for input on ExternalSecuritySolutionsTests and AdaptiveApplicationControls_Put

**Comment by giromm2ms** [comment]
@bquantump , I see you've been assigned to review this PR.
Please review since it is prerequisite for PS/CLI enhancements for secure score.

Thanks

**Comment by bquantump** [comment]
> @bquantump , I see you've been assigned to review this PR.
> Please review since it is prerequisite for PS/CLI enhancements for secure score.
> 
> Thanks

Please ensure all the following are done (for example no swagger is linked here):

https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#appendix-a-pr-review-checklist

**Comment by bquantump** [comment]
@giromm2ms are you planning updating this soon? If we do not hear anything by the end of the week, we will be closing this.

**Comment by giromm2ms** [comment]
@bquantump , I intend to work on it tomorrow.
Please don't close it yet

**Comment by giromm2ms** [comment]
As this one contains lots of merge content, I am closing it.
Please refer to https://github.com/Azure/azure-sdk-for-net/pull/16985

**Pull request closed without merging**
