### PR TITLE
Azure.ResourceManager.ArcVm Release

### PR DESCRIPTION
**Pull request by pathuang-sia**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by pathuang-sia** [comment]
> **API change check**
> 
> APIView has identified API level changes in this PR and created following API reviews.
> 
> [Azure.ResourceManager.ArcVm](https://apiview.dev/Assemblies/Review/9c10e34f3f05454c80d6ba745915d178)

from adding the cspell word to the wrong location

**Review by archerzz — COMMENTED** [review]
@pathuang-sia 
If you have a release date, don't forget to update `CHANGELOG.md`.

**Comment by pathuang-sia** [comment]
> @pathuang-sia If you have a release date, don't forget to update `CHANGELOG.md`.

I've updated the changelog to the latest date but pipeline seems to be unhappy with it?

**Review by ArthurMa1978 — CHANGES_REQUESTED** [review]
There is already an existing sdk `Azure.ResourceManager.Hci` for the same swagger spec, and this namespace was approved long time ago. So you can't create a new sdk for this swagger spec.
Please just update existing `Hci` SDK to the new version.

**Comment by pathuang-sia** [comment]
> There is already an existing sdk `Azure.ResourceManager.Hci` for the same swagger spec, and this namespace was approved long time ago. So you can't create a new sdk for this swagger spec. Please just update existing `Hci` SDK to the new version.

Hi @ArthurMa1978, addressed this on teams but I'll add it here too: since the namespace azurestackhci is shared by two teams owning different set of non-overlapping resources, we were instructed to create a separate child folder but remain in the same azurestackhci sdk folder according to this post: https://teams.microsoft.com/l/message/19:7b87fb348f224b37b6206fa9d89a105b@thread.skype/1698264241364?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1698255395129&teamName=Azure%20SDK&channelName=Language%20-%20DotNet&createdTime=1698264241364

**Comment by pathuang-sia** [comment]
closing this branch as the sdk is merged under Azure.ResourceManager.Hci

**Pull request closed without merging**
