### PR TITLE
[ContainerRegistry] SDK Update for container registry, 2022-02-01-preview API

### PR DESCRIPTION
**Pull request by cegraybl**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by ankurkhemani — APPROVED** [review]

**Comment by ankurkhemani** [comment]
@archerzz Can you please help review the PR and guide us publish the sdk to NuGet.

**Review by archerzz — APPROVED** [review]

**Comment by archerzz** [comment]
@ankurkhemani approved. Please see the [guide here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=track-1-sdk-signing-and-publishing-nuget-packges) on how to publish the package. Thanks.

**Comment by cegraybl** [comment]
@archerzz can you share the documentation for track 2?
we only have access/used [these instructions](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=track-1-sdk-signing-and-publishing-nuget-packges) for track 1

**Comment by ArthurMa1978** [comment]
As we offline talked, will move to track 2

**Comment by ankurkhemani** [comment]
@ArthurMa1978 Can you please share the guidelines for track2?

**Comment by archerzz** [comment]
@ankurkhemani  It's here: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process

**Pull request closed without merging**
