### PR TITLE
[Storage] Resolving generated code issues

### PR DESCRIPTION
**Pull request by amnguye**
Looks like an unexpected changed to the generator or something. Had to regenerate the code in storage as the Verify generated code started failing.

### CODE REVIEW

**Comment by amnguye** [comment]
Could I get someone to review this for Azure.ResourceManager as well? Looks like it needs everything to be regenerated in order for Verify Generated Code to pass.

**Comment by amnguye** [comment]
@jsquire @JoshLove-msft Any clue to what changes happened and why this happened? We didn't change anything in storage. (I can't speak for ResourceManager, but doesn't look like anything changed there too).

I don't think I saw any generator changes in the commit history.

**Comment by annelo-msft** [comment]
@amnguye once https://github.com/Azure/azure-sdk-for-net/pull/38396 merges, this issue should be resolved.

**Comment by amnguye** [comment]
Sounds good! I will just close my PR then!

**Pull request closed without merging**
