### PR TITLE
Add azure regional authority name to options

### PR DESCRIPTION
**Pull request by mchilders-msft**
Allows regional authority for ESTS-R to be set as an option OR as an environment variable.

### CODE REVIEW

**Comment by mchilders-msft** [comment]
> 

@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by mchilders-msft** [comment]
> @microsoft-github-policy-service agree company="your company"

@microsoft-github-policy-service agree company="Microsoft"

**Review by christothes — CHANGES_REQUESTED** [review]
Hi @mchilders-msft Could you explain the scenario for which these changes are needed? Up to now, we have intentionally not exposed the regional authority in the public API.

**Comment by tommymarkmamake** [comment]
Hello @christothes .
I am the PM for ESTS-R. In fact, we are looking at the possibility to support 3P now. So  Just invited you to our meeting next week. Happy to chat more.

**Pull request closed without merging**
