### PR TITLE
Update SDK to version R3.5 of RP using Master

### PR DESCRIPTION
**Pull request by leonardbf**
Update SDK to version R3.5 of RP.
Includes active directory and export policy.
Still in preview - breaking changes are not an issue

Swagger:
https://github.com/leonardbf/azure-rest-api-specs/tree/master/specification/netapp/resource-manager

Last swagger PR:
Azure/azure-rest-api-specs#5446

This replaces Azure#5565. Now merging to master.

(NetApp internal ticket NFSAAS-2235)

### CODE REVIEW

**Comment by dsgouda** [comment]
@leonardbf this commit history is unexpected. Could you explain how you go about creating a new branch and generating your sdk for a new PR?

**Comment by leonardbf** [comment]
@dsgouda I first tried to merge the azure master into my forked master but this had conflicts. I also tried this in the command line by fetching from upstream. There were some 1500 conflicts mostly deleted files. In the end I deleted all files from master local and origin and then performed fetch from upstream and merged (git fetch upstream followed by git merge upstream/master) then pushed back to origin master. And then I overwrote the NetApp folder with the updates and applied that commit. From what I see here and previously the merge from upstream introduces the commit history.

**Comment by dsgouda** [comment]
> 
> 
> @dsgouda I first tried to merge the azure master into my forked master but this had conflicts. I also tried this in the command line by fetching from upstream. There were some 1500 conflicts mostly deleted files. In the end I deleted all files from master local and origin and then performed fetch from upstream and merged (git fetch upstream followed by git merge upstream/master) then pushed back to origin master. And then I overwrote the NetApp folder with the updates and applied that commit. From what I see here and previously the merge from upstream introduces the commit history.

I think the best solution in such cases is to clone the repo again, check out a feature branch and regenerate the sdk. This will ensure a clean commit history and no conflicts. Please follow these steps and open a new PR. Will close this PR once acknowledged

**Comment by leonardbf** [comment]
> > @dsgouda I first tried to merge the azure master into my forked master but this had conflicts. I also tried this in the command line by fetching from upstream. There were some 1500 conflicts mostly deleted files. In the end I deleted all files from master local and origin and then performed fetch from upstream and merged (git fetch upstream followed by git merge upstream/master) then pushed back to origin master. And then I overwrote the NetApp folder with the updates and applied that commit. From what I see here and previously the merge from upstream introduces the commit history.
> 
> I think the best solution in such cases is to clone the repo again, check out a feature branch and regenerate the sdk. This will ensure a clean commit history and no conflicts. Please follow these steps and open a new PR. Will close this PR once acknowledged

Clone the repo again? Do you mean delete and re-fork? The repo locally was freshly cloned. I did not pull into my existing repo (I realise I did not state that above).

**Comment by dsgouda** [comment]
> 
> 
> > > @dsgouda I first tried to merge the azure master into my forked master but this had conflicts. I also tried this in the command line by fetching from upstream. There were some 1500 conflicts mostly deleted files. In the end I deleted all files from master local and origin and then performed fetch from upstream and merged (git fetch upstream followed by git merge upstream/master) then pushed back to origin master. And then I overwrote the NetApp folder with the updates and applied that commit. From what I see here and previously the merge from upstream introduces the commit history.
> > 
> > 
> > I think the best solution in such cases is to clone the repo again, check out a feature branch and regenerate the sdk. This will ensure a clean commit history and no conflicts. Please follow these steps and open a new PR. Will close this PR once acknowledged
> 
> Clone the repo again? Do you mean delete and re-fork? The repo locally was freshly cloned. I did not pull into my existing repo (I realise I did not state that above).

So here is what I suggest.
- Clone the repo here: https://github.com/Azure/azure-sdk-for-net 
- Check out its master and force push it to your fork's master here: https://github.com/leonardbf/azure-sdk-for-net/tree/master 
This will ensure your fork is an exact copy of our master.
Then
- re-clone your fork locally in a new location, check out a feature branch and commit your changes.
- open a new pr using this feature branch

Hope this helps.

**Comment by leonardbf** [comment]
> > > > @dsgouda I first tried to merge the azure master into my forked master but this had conflicts. I also tried this in the command line by fetching from upstream. There were some 1500 conflicts mostly deleted files. In the end I deleted all files from master local and origin and then performed fetch from upstream and merged (git fetch upstream followed by git merge upstream/master) then pushed back to origin master. And then I overwrote the NetApp folder with the updates and applied that commit. From what I see here and previously the merge from upstream introduces the commit history.
> > > 
> > > 
> > > I think the best solution in such cases is to clone the repo again, check out a feature branch and regenerate the sdk. This will ensure a clean commit history and no conflicts. Please follow these steps and open a new PR. Will close this PR once acknowledged
> > 
> > 
> > Clone the repo again? Do you mean delete and re-fork? The repo locally was freshly cloned. I did not pull into my existing repo (I realise I did not state that above).
> 
> So here is what I suggest.
> 
> * Clone the repo here: https://github.com/Azure/azure-sdk-for-net
> * Check out its master and force push it to your fork's master here: https://github.com/leonardbf/azure-sdk-for-net/tree/master
>   This will ensure your fork's master is an exact copy of our master.
>   Then
> * re-clone your fork locally in a new location, check out a feature branch and commit your changes.
> * open a new pr using this feature branch
> 
> Hope this helps.

I hope so too :) 
Anyway I have created new PR https://github.com/Azure/azure-sdk-for-net/pull/5660 and closed this one. It is currently running the validation pipeline.

**Pull request closed without merging**
