### PR TITLE
Generated files for new api version 2022-11-15-preview

### PR DESCRIPTION
**Pull request by firstaye-zz**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Comment by firstaye-zz** [comment]
@m-nash , would you be able to review the PR and give me some feedback?
I've followed the instructions but there is no instructions to generate new test record. And there are other two failure checks that seems not related to my change, could we ignore that since it's not required?

**Comment by firstaye-zz** [comment]
When I tried to Record new Session, it does not reflect the information I enter for SubId, Tenant_ID, could you advise how to record the new session? I don't find how does the subscription comes from the code.

 GetIotHubUserSubscriptionQuota
   Source: IotHubMiscTests.cs line 43
   Duration: 1.9 sec

  Message: 
The [RecordedTest] attribute attempted to re-record, but failed:

Azure.RequestFailedException : The client 'b92b1619-589b-455d-90de-89aa07424253' with object id 'b92b1619-589b-455d-90de-89aa07424253' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourcegroups/IotHub-RG-6149' or the scope is invalid. If access was recently granted, please refresh your credentials.
Status: 403 (Forbidden)
ErrorCode: AuthorizationFailed

Content:
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client 'b92b1619-589b-455d-90de-89aa07424253' with object id 'b92b1619-589b-455d-90de-89aa07424253' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourcegroups/IotHub-RG-6149' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}

Headers:
Connection: close
Date: Tue, 02 May 2023 18:46:01 GMT
Server: Kestrel
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-request-id: 2372eceb-24a3-4d23-a685-b5e20e7d588d
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Content-Length: 443
Content-Type: application/json; charset=utf-8
Expires: -1


Original failure:

Azure.Core.TestFramework.TestRecordingMismatchException : Unable to find a record for the request PUT https://management.azure.com/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/IotHub-RG-6149/providers/Microsoft.Devices/IotHubs/IotHub-1345?api-version=2022-11-15-preview
Uri doesn't match:
    request <https://management.azure.com/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/IotHub-RG-6149/providers/Microsoft.Devices/IotHubs/IotHub-1345?api-version=2022-11-15-preview>
    record  <https://management.azure.com/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/IotHub-RG-6149/providers/Microsoft.Devices/IotHubs/IotHub-1345?api-version=2021-07-02>
Header differences:
Body differences:


  Stack Trace: 
TaskExtensions.GetResultFromTask(Object returnValue) line 130
ManagementInterceptor.Intercept(IInvocation invocation) line 44
AbstractInvocation.Proceed()
ResourceGroupResourceProxy.GetAsync(CancellationToken cancellationToken)
IotHubMiscTests.TestSetUp() line 38
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await(Func`1 invoke)
SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
SetUpTearDownItem.RunSetUp(TestExecutionContext context)
<.ctor>b__0(TestExecutionContext context)
<>c__DisplayClass1_0.<Execute>b__0()
BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

**Comment by firstaye-zz** [comment]
@ArthurMa1978, @m-nash. 
Sorry for the delay. I was on leave for couple months as the project was on pause. Could we re-open this PR again?

**Comment by firstaye-zz** [comment]
Hi @m-nash , I replied to the comments in APIView, could you take a look?

**Comment by ArthurMa1978** [comment]
Hey @firstaye-zz the last release of IotHub is 2023-06-30, so can't move back to 2022-11-15-preview

**Comment by ArthurMa1978** [comment]
Close this pr after offline synced with @firstaye-zz .

**Pull request closed without merging**
