### PR TITLE
[NetAppFiles]Anf 8257 net app files 2020 09 01

### PR DESCRIPTION
**Pull request by audunn**
This PR relates to NetApp Files (ANF) 2020-09-01.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/netapp/resource-manager/Microsoft.NetApp/stable/2020-09-01/netapp.json

1. Added Security operators to ActiveDirectory
2. smbEncryption, smbContinuouslyAvailable to Volume
3. Added ListNextLink.GetAllResourcesByPollingNextLink()  to query large result sets (volumes)

### CODE REVIEW

**Comment by audunn** [comment]
Hi would be nice to get this reviewed has been waiting.

**Comment by audunn** [comment]
@bquantump  can we please get this looked at?

**Comment by bquantump** [comment]
Can you please reference the swagger?

**Comment by audunn** [comment]
@bquantump  https://github.com/Azure/azure-rest-api-specs/blob/master/specification/netapp/resource-manager/Microsoft.NetApp/stable/2020-09-01/netapp.json

**Comment by bquantump** [comment]
Please ensure this checklist is complete

https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#appendix-a-pr-review-checklist

**Comment by audunn** [comment]
I think everything should be done. Are we missing something?

**Review by bquantump — APPROVED** [review]

**Pull request merged**
