### PR TITLE
Update activity kind and do not set extra tags

### PR DESCRIPTION
**Pull request by JoshLove-msft**
Helpful code pointers when reviewing:
- [DiagnosticScope ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs)primitive that we are using throughout the .NET SDK codebase.
- Start Diagnostic scope when [sending messages](https://github.com/JoshLove-msft/azure-sdk-for-net/blob/tracing-updates/sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusSender.cs#L191-L192).
- Start Diagnostic scope when [receiving messages](https://github.com/JoshLove-msft/azure-sdk-for-net/blob/tracing-updates/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs#L253-L257).
- [Service Bus factory](https://github.com/JoshLove-msft/azure-sdk-for-net/blob/tracing-updates/sdk/servicebus/Azure.Messaging.ServiceBus/src/Diagnostics/EntityScopeFactory.cs#L15) for creating Diagnostic scope and containing helper methods.

### CODE REVIEW

**Review by jsquire — APPROVED** [review]
The implementation looks good to me;  I'll defer to more authoritative folks on compliance with the expected formats.

**Review by MiYanni — APPROVED** [review]

**Pull request merged**
