### PR TITLE
Added back Backup, regenerated using updated generate.ps1

### PR DESCRIPTION
**Pull request by deathly809**
## Description

The .gitignore in the root directory ignores all Backup* matches.  I made a .gitignore under AzureStack that removes that ignore so that this directory and changes under it are included.

I updated the generate.ps1 and regenerated.  Tests still pass.

https://github.com/Azure/azure-rest-api-specs/pull/2838

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [X] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [X] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [X] The generate.ps1 file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by dsgouda** [comment]
@deathly809 please link the rest spec PR

**Comment by deathly809** [comment]
@dsgouda I thought that was only needed for new specs.  When I did the move to AzureStack\Admin folders I forgot to do a git add --force.

https://github.com/Azure/azure-rest-api-specs/pull/2838

**Comment by dsgouda** [comment]
@deathly809 its good bookkeeping for us. Thanks!

**Pull request merged**
