### PR TITLE
[ADLS] fix auto generated changes

### PR DESCRIPTION
**Pull request by lewu-msft**
REST spec [PR here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F5977&data=02%7C01%7CRay.Wu%40microsoft.com%7Cd8a15c0e23b74484b87108d6da2c5d26%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636936281402598357&sdata=AW%2B4JjCNNaEGiVD%2F6IT8Sx5aSsJWAP8k0iFf2%2BHbYkk%3D&reserved=0), 
.NET SDK PR auto generated [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F6297&data=02%7C01%7CRay.Wu%40microsoft.com%7Cd8a15c0e23b74484b87108d6da2c5d26%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636936281402598357&sdata=mjVpjPVyzSmSrTjwuKlFjih4mnkHNc%2BLC2zYH0dWbbw%3D&reserved=0)
removed some unnecessary changes so that the tests won't fail

### CODE REVIEW

**Review by dsgouda — CHANGES_REQUESTED** [review]
Are you generating this code using a generate.ps1 script? If yes, there should be a .txt file generated, please commit this file too

**Comment by lewu-msft** [comment]
> Are you generating this code using a generate.ps1 script? If yes, there should be a .txt file generated, please commit this file too

I didn't generate this code myself. It was from .NET SDK PR auto generated [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F6297&data=02%7C01%7CRay.Wu%40microsoft.com%7Cd8a15c0e23b74484b87108d6da2c5d26%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636936281402598357&sdata=mjVpjPVyzSmSrTjwuKlFjih4mnkHNc%2BLC2zYH0dWbbw%3D&reserved=0)
I found it generated some unnecessary changes, which is the reason the tests failed. I just removed those unnecessary changes here. Still, I'm not sure how those unnecessary changes were generated based on my  [spec PR here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F5977&data=02%7C01%7CRay.Wu%40microsoft.com%7Cd8a15c0e23b74484b87108d6da2c5d26%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636936281402598357&sdata=AW%2B4JjCNNaEGiVD%2F6IT8Sx5aSsJWAP8k0iFf2%2BHbYkk%3D&reserved=0)

**Comment by dsgouda** [comment]
> 
> 
> > Are you generating this code using a generate.ps1 script? If yes, there should be a .txt file generated, please commit this file too
> 
> I didn't generate this code myself. It was from .NET SDK PR auto generated [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fpull%2F6297&data=02%7C01%7CRay.Wu%40microsoft.com%7Cd8a15c0e23b74484b87108d6da2c5d26%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636936281402598357&sdata=mjVpjPVyzSmSrTjwuKlFjih4mnkHNc%2BLC2zYH0dWbbw%3D&reserved=0)
> I found it generated some unnecessary changes, which is the reason the tests failed. I just removed those unnecessary changes here. Still, I'm not sure how those unnecessary changes were generated based on my [spec PR here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F5977&data=02%7C01%7CRay.Wu%40microsoft.com%7Cd8a15c0e23b74484b87108d6da2c5d26%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636936281402598357&sdata=AW%2B4JjCNNaEGiVD%2F6IT8Sx5aSsJWAP8k0iFf2%2BHbYkk%3D&reserved=0)

The auto generated PR is based on the default tag in the readme file. You should not manually modify anything under the `Generated` directory. If some changes were generated unexpectedly please fix the swagger or modify the `Customizations` layer to work with latest changes

**Comment by shahabhijeet** [comment]
Please open a new PR aligning to the new directory structure

**Pull request closed without merging**
