### PR TITLE
Fix Key Vault Test project

### PR DESCRIPTION
**Pull request by rohmano**
1. Key Vault test dependency fixed a typo in a property name. Updating to consuming the correct property now.
2. Clean up duplicate Key Vault test project dependencies

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rohmano__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rohmano). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rohmano** [comment]
Private build - http://azuresdkci.cloudapp.net/view/2-MAML/job/sdk-for-net-sign/656/

**Comment by azurecla** [comment]
Hi __@rohmano__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rohmano). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Pull request merged**
