### PR TITLE
[DO NOT MERGE] Add Cognitive Skillset Operations

### PR DESCRIPTION
**Pull request by jeji1101**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] Please add REST spec PR link to the SDK PR
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [ ] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by vl8163264128** [comment]
#sign-off

**Comment by dsgouda** [comment]
@jeji1101 please reference the rest spec PR

**Review by dsgouda — CHANGES_REQUESTED** [review]
Please regenerate the code using generate.ps1 and commit all changes

**Comment by jeji1101** [comment]
The corresponding swagger spec PR is: https://github.com/Azure/azure-rest-api-specs/pull/3386. Thanks.

**Comment by dsgouda** [comment]
@azuresdkci Retest this please

**Comment by dsgouda** [comment]
@jeji1101 please pull latest changes from upstream and update the PR

**Comment by dsgouda** [comment]
@brjohnstmsft could you please update the `search-preview` branch with the latest `psSdkJson6` in order to fix these build issues

**Comment by dsgouda** [comment]
@azuresdkci Retest this please

**Comment by dsgouda** [comment]
@jeji1101 Please update your branch with remote `search-preview` and update the PR

**Comment by brjohnstmsft** [comment]
@dsgouda I've updated the branch. Please do not merge until I've had a chance to review it.

**Comment by dsgouda** [comment]
@jeji1101 would you like to close this in favor of https://github.com/Azure/azure-sdk-for-net/pull/4609

**Comment by brjohnstmsft** [comment]
@dsgouda @jeji1101 Fine by me.

**Pull request closed without merging**
