### PR TITLE
Added SDK project templates, adding common repo tasks, adding shortcu…

### PR DESCRIPTION
**Pull request by shahabhijeet**
Adding AutoRest Project template as well as SDK test project template
Adding module for common repo task
Adding a shortcut to start vs dev prompt in powershell

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@azurecla add to whitelist

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by sphibbs** [comment]
@azurecla add to whitelist

**Comment by sphibbs** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
Documentation?  Can we add documentation for the new cmdlets and templates in the documentation folder

**Pull request merged**
