### PR TITLE
Updated HealthcareApis SDK

### PR DESCRIPTION
**Pull request by kenziedolish**
Looking to release a new version of the HealthcareApis .NET SDK from updated spec

PR Changes:

- Generated new version of .NET HealthcareApis SDK with packageTag=2021-11-01 using generate.ps1 script
- Updated the following information in the .csproj
    - Version - bumped to 4
    - PackageTags
    - PackageReleaseNotes
- Updated AzSdk.RP.props
    - AzureApiTag
- Updated AssemblyInfo.cs
    - AssemblyFileVersion - bumped to 4
    - AssemblyVersion - bumped to 4

### CODE REVIEW

**Review by Yao725 — CHANGES_REQUESTED** [review]
Please fix the broken pipeline, I think you need to update the tests.

**Comment by kenziedolish** [comment]
Hi @Yao725, can you re-review this PR? All the checks have passed

**Review by Yao725 — APPROVED** [review]
LGTM

**Pull request merged**
