### PR TITLE
Update Information Protection SDK Clients

### PR DESCRIPTION
**Pull request by bashahee**
SDK clients of Information Protection were updated according to changes introduced in corresponding swagger. No new clients were added.
This PR is based on https://github.com/Azure/azure-rest-api-specs/pull/8677 swagger spec review PR.

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi, could you
- Add a link to the swagger spec review PR in the description
- Include the `.txt` file generated when you run `generate.ps1`[(details)](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec)
- Update `AssemblyFileVersion` in `assemblyinfo.cs`

Thanks

**Comment by bashahee** [comment]
@isra-fel Thanks for the review! You comments were addressed.

**Comment by bashahee** [comment]
@isra-fel Can we please merge, as you comments were addressed?

**Comment by isra-fel** [comment]
Hi @bashahee sorry for late response. We were just back from holiday.
The metadata txt should be under /eng/mgmt/mgmtmetadata . Perhaps you need to [update your build tools](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools). Or you can simply move it there.

**Comment by bashahee** [comment]
@isra-fel Done, thanks!

**Comment by bashahee** [comment]
@isra-fel Can we please merge?

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
