### PR TITLE
apimanagement api version 2019-12-01 and gateway entity added

### PR DESCRIPTION
**Pull request by vfedonkin**
New api version 2019-12-01. Change log:
- Switch the .NET client to use api-version `2019-12-01`
- `properties` entity renamed to `namedValues` 
- new `gateway` entity added
- Added POST operations to get entities secret properties. Secret properties will not be returned with GET or LIST operations anymore. Entities are: `accessInformation`, `authorizationServers`, `delegationSettings`, `identityProviders`, `namedValues`, `openIdConnectProviders`, `subscriptions`. 
- `diagnostics` entity: `enableHttpCorrelationHeaders` property is not supported, `loggerId` is a required property now.
- Breaking Change: `capacity` is a required parameter with creating ApiManagement service.
- Added support for creating `userAssignedIdentity`. 
- Added support for `disableGateway` property, which allows taking a region out of a multi-region premium sku ApiManagement service
- Added support for `apiVersionConstraint` property which allows limiting all control plane calls higher than a specific api-version
- Breaking Change: Exception thrown in case of failure changed from `CloudException` to `ErrorResponseException`.

### CODE REVIEW

**Comment by vfedonkin** [comment]
Need to regenerate clients to move to 2019-12-01 but waiting for rest specification to be updated first. Closing PR till that

**Comment by isra-fel** [comment]
Hi Vitaliy, I saw you reopened right after you closed it. What's the state now?

**Comment by vfedonkin** [comment]
@isra-fel , the PR is active, I suspended it while making some changes but now it's ready

**Review by solankisamir — APPROVED** [review]
:shipit:

**Comment by isra-fel** [comment]
Hey, please update version in your csproj and assemblyinfo.cs files.

**Comment by solankisamir** [comment]
@isra-fel we did not release any NuGet with version 5.0.0. 
https://www.nuget.org/packages/Microsoft.Azure.Management.ApiManagement/

Do we still need to version?

**Comment by vfedonkin** [comment]
@isra-fel , we updated the version in previous PR https://github.com/Azure/azure-sdk-for-net/pull/10578 , and we didn't release any nugets.
The current PR is just an addition to that, and we want to include these 2 PRs as one update/nuget/update notes, so we want to release both PRs as 5.0.0

**Review by isra-fel — APPROVED** [review]
Got it. I just need to confirm with you ;)

**Pull request merged**
