### PR TITLE
[FormRecognizer] Updated tests after recent service deployment

### LINKED ISSUE #35809: [FormRecognizer] Service returning 'expirationDateTime' on 2022-08-31
The latest Form Recognizer service preview (version 2023-02-28-preview) introduced a new property to some models: `expirationDateTime`. This new property is accidently being returned in an older service version: 2022-08-31, which is causing some of our tests to fail.

The service team has already been notified about this and a fix is expected to be rolled out in a couple of days.

Meanwhile, we have updated the validation in our tests to match the current behavior of the service. Affected validation methods are: `AdministrationOperationsLiveTests.ValidateDocumentModelDetails` and `DocumentModelAdministrationLiveTests.BuildDocumentModel`.

Once the service has fixed the issue, tests need to be updated again to reflect the expected behavior.

**Important update:** the service fixed the issue in calls to `GetDocumentModel` and `GetDocumentModels`, but it's still present in `GetOperation`. This caused new failures in tests `DocumentModelAdministrationLiveTests.GetDocumentModel` and `DocumentModelAdministrationLiveTests.GetDocumentModels`, so more assertions were commented out. These need to be updated as well once the service fixes the issue.

### PR DESCRIPTION
**Pull request by kinelski**
A recent service deployment introduced a couple of behavior changes that deterministically broke some of our tests. This PR updates tests, aligning them with the new service behavior, to make our pipeline greener.

Fixes https://github.com/Azure/azure-sdk-for-net/issues/35809 as the corresponding service bug has been fixed.

### CODE REVIEW

**Comment by pallavit** [comment]
Given these are behavioral breaking changes do they need breaking change approval?

**Comment by kinelski** [comment]
> Given these are behavioral breaking changes do they need breaking change approval?

These changes are updates in their ML models, improving the result of the document analysis, in theory.

There are disagreements between the service and our architects about what constitutes a breaking change, though. The service claims that these model changes are necessary in an ML-based service, while our architects insist that some kind of model versioning would be ideal to ensure a consistent behavior.

In the end, these changes are very common in Form Recognizer. Our tests need to follow these service updates, otherwise our pipeline will stay broken.

**Comment by pallavit** [comment]
Got it, thanks.

**Review by pallavit — APPROVED** [review]

**Pull request merged**
