### PR TITLE
Remove subscription id since it is not needed in test-resources.json

### PR DESCRIPTION
**Pull request by sacheu**
Remove subscription id in test-resources.json since it is not needed to be defined there

### CODE REVIEW

**Review by beltr0n — APPROVED** [review]
lgtm, test failures are the expected ones from PSTN

**Comment by sacheu** [comment]
Live test passed. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=871564&view=ms.vss-test-web.build-test-results-tab. The failed test is caused by service bug.

**Pull request merged**
