### PR TITLE
[Azure Cognitive Search] Updating SDK for most recent stable api version.

### PR DESCRIPTION
**Pull request by tjacobhi**

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi @tjacobhi , please
- Add a link to the swagger spec review PR in the description
- Update api tag in `AzSdk.RP.props` since you are changing api version
- Update release notes in csproj
- Update versions in csproj and `assemblyinfo.cs` if you are going to release this version

Thanks

**Comment by isra-fel** [comment]
Still, please
- Add a link to the swagger spec review PR in the description
- Update api tag in AzSdk.RP.props since you are changing api version
Thanks

**Comment by isra-fel** [comment]
@tjacobhi I still think it's a bad idea to cover changes to both data- and management-plane in one PR. They have different review criteria and are reviewed by different team.
Please split them in two PRs. Thank you.

**Comment by tjacobhi** [comment]
@isra-fel The changes were only covering managment-plane in this PR. The data-plane had tests that were dependent on the management-plane build, so I had to update the tests, but the actual generated sdk code was not changed for data-plane. I was blocked on a PR for api-specs, but that should be done this week. I would like to re-open this PR.

**Pull request closed without merging**
