### PR TITLE
Generate stub services

### PR DESCRIPTION
**Pull request by RikkiGibson**
## Description
This PR uses new AutoRest templates found in https://github.com/RikkiGibson/autorest/tree/azure-gen-manager to generate service clients, managers and project files.

Includes generated stubs for the following services:
- EventHub
- ServiceFabric
- NotificationHubs
- AnalysisServices
- Billing
- CognitiveServices
- Consumption
- CustomerInsights
- DevTestLab
- IoTHub/Devices
- Logic
- MachineLearning
- Relay
- StorSimple
- Monitor (management and data plane)

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by hovsepm** [comment]
@RikkiGibson please remove all generated Sync methods

**Review by hovsepm — CHANGES_REQUESTED** [review]
Each project should contain Properties\AssemlbyInfo.cs file

**Comment by RikkiGibson** [comment]
@hovsepm I've made the requested changes.

**Comment by hovsepm** [comment]
Please remove comments form the top of the csproj file:
src\ResourceManagement\StorSimple\Microsoft.Azure.Management.StorSimple.Fluent.csproj

**Comment by hovsepm** [comment]
@RikkiGibson please start sign job to verify that we produce all the packages.

**Comment by RikkiGibson** [comment]
http://azuresdkci.cloudapp.net/view/NetCore-SDK/job/Fluent-NetCore-SDK-Sign/9/

**Comment by RikkiGibson** [comment]
@hovsepm Signing job seems to have worked just fine. I created a small sample project and pulled in the nupkg for one of the SDKs I generated as part of this PR, and it seems to work.

**Comment by RikkiGibson** [comment]
Looks like I don't have permission to view the Jenkins build failure.

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Review by hovsepm — APPROVED** [review]

**Pull request merged**
