### PR TITLE
Add New Version for the Network, prepare for the new fields to be added

### PR DESCRIPTION
**Pull request by azhao155**
## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] Please add REST spec PR link to the SDK PR
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by azhao155** [comment]
- These are SDK changes due to change in azure-rest-api-specs as shown:
  https://github.com/Azure/azure-rest-api-specs/pull/2185
It will add new version 20180101, and we will add some attribute based on this version

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
1) Get latest updates from upstream (if you have not done so in last 3 weeks)
2) Then execute msbuild build.proj to update your build tools
3) Then regenerate your SDK using generate.cmd (this will regenerate couple of additional files)
4) build you project (ether IDE or command line, this will generate Azsdk.RP.props file)
5) Then update your PR
With the latest changes, every regeneration will generate couple of additional meta data files that are needed in each PR.

**Comment by azhao155** [comment]
Have used genearate.cmd and now it has metadata

**Comment by shahabhijeet** [comment]
The meta data files are sdkInfo_*.cs and AzSdk.RP.props file.

**Comment by azhao155** [comment]
Can't merge the change, need to wait for the NRP new api version, will follow up later

**Comment by shahabhijeet** [comment]
@azhao155 closing this PR as you need to wait for few things to happen at your end and now it has merge conflicts.
Please create a new PR and submit it with all the intended changes.

**Pull request closed without merging**
