### PR TITLE
[HDInsight] Support Relayoutbound feature and returning ClusterId

### PR DESCRIPTION
**Pull request by aim-for-better**
1. Remove previous NetworkSettings: related swagger spec PR https://github.com/Azure/azure-rest-api-specs/pull/10793
2. Add NetworkProperties and ClusterId : related swagger spec PR https://github.com/Azure/azure-rest-api-specs/pull/11134

### CODE REVIEW

**Comment by aim-for-better** [comment]
Could you please help review this PR? Thanks in advance

**Comment by YalinLi0312** [comment]
Could you:
* update versions in `AssemblyInfo.cs`
* update the API tags in `Az.Sdk.props` if there is an API-version update

**Review by YalinLi0312 — CHANGES_REQUESTED** [review]
Could you:
* update versions in `AssemblyInfo.cs`
* update the API tags in `Az.Sdk.props` if there is an API-version update

**Comment by aim-for-better** [comment]
> Could you:
> 
> * update versions in `AssemblyInfo.cs`
> * update the API tags in `Az.Sdk.props` if there is an API-version update

Hi @YalinLi0312  I have updated the assembly info. Thanks for your review.

**Review by YalinLi0312 — APPROVED** [review]

**Pull request merged**
