### PR TITLE
Updating the readme file in autorest to use latest Api spec preview

### PR DESCRIPTION
**Pull request by amruthashree18**
Regenerated the Azure SDK by updating readme file in the autorest.md to use the latest API spec preview.

### CODE REVIEW

**Review by jsquire — DISMISSED** [review]
@amruthashree18:

Your account lacks the required public GitHub organizations and permissions required of an internal contributor.  Please review the Azure SDK onboarding documentation and use the associated Teams channel for support.
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

You can verify the state of your account by running the [Validate-AzsdkCodeOwner](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/scripts/Validate-AzsdkCodeOwner.ps1) script from the Azure SDK tools repository.

Please also be sure to add yourself to [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) for this library, if you will be maintaining it going forward.

**Comment by amruthashree18** [comment]
Hi @jsquire , I have changed it to public now. Please review.

**Comment by jsquire** [comment]
> Hi @jsquire , I have changed it to public now. Please review.

You do not have a public `Azure` membership nor do you have the needed "write" permissions.   Please refer to the links that I shared above for more details and assistance.

**Comment by amruthashree18** [comment]
Hi @jsquire , I have now got write access and joined azure org as public.

**Review by ArthurMa1978 — APPROVED** [review]

**Pull request merged**
