### PR TITLE
CDN generated code after swagger change 04/06/2016

### PR DESCRIPTION
**Pull request by csmengwan**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@csmengwan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (qinwa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@ankurchoubeymsft please pull from upstream and resolve conflicts

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist.

**Comment by markcowl** [comment]
@ankurchoubeymsft There are still merge conflicts.  Please update the PR or we will have to close it.

**Comment by markcowl** [comment]
@ankurchoubeymsft Closing for lake of activity.  Please reopen this PR if you would like to make the chenges.

**Pull request closed without merging**
