### PR TITLE
Added new Models and operations for the new Customer Disk SKU

### PR DESCRIPTION
**Pull request by ammaralavi**
# All SDK Contribution checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.
- [ ] **Please open PR in `Draft` mode if it is:**
	- Work in progress or not intended to be merged.
	- Encountering multiple pipeline failures and working on fixes.
- [x] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md).**

### [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code. (Track 2 only)
- [x] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK. Please double check nuget.org current release version.

## Additional management plane SDK specific contribution checklist: 
Note: Only applies to `Microsoft.Azure.Management.[RP]` or `Azure.ResourceManager.[RP]`
 
- [x] Include updated [management metadata](https://github.com/Azure/azure-sdk-for-net/tree/main/eng/mgmt/mgmtmetadata).
- [x] Update AzureRP.props to add/remove version info to maintain up to date API versions.

### Management plane SDK Troubleshooting
- If this is very first SDK for a services and you are adding new service folders directly under /SDK, please add `new service` label and/or contact assigned reviewer.
- If the check fails at the `Verify Code Generation` step, please ensure:
	- Do not modify any code in generated folders.
	- Do not selectively include/remove generated files in the PR.
	- Do use `generate.ps1/cmd` to generate this PR instead of calling `autorest` directly.
	Please pay attention to the @microsoft.csharp version output after running `generate.ps1`. If it is lower than current released version (2.3.82), please run it again as it should pull down the latest version.
	
	**Note: We have recently updated the PSH module called by `generate.ps1` to emit additional data. This would help reduce/eliminate the Code Verification check error. Please run following command**:

	    `dotnet msbuild eng/mgmt.proj /t:Util /p:UtilityName=InstallPsModules`

### Old outstanding PR cleanup
 Please note:
	If PRs (including draft) has been out for more than 60 days and there are no responses from our query or followups, they will be closed to maintain a concise list for our reviewers.

### CODE REVIEW

**Review by archerzz — CHANGES_REQUESTED** [review]
@ammaralavi 

- There are several breaking changes. So we need to bump a major version (e.g. `2.0.0`). Otherwise, we need to provide customizations for backward compatibility. You can refer to [compute](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/compute/Microsoft.Azure.Management.Compute/src/Customizations) for example. But since there is interface change, backward compatibility might not be available, so you probably have to bump a major version.
- Build is broke, please fix it.

Thanks.

**Comment by ammaralavi** [comment]
@archerzz Hi, I have updated the version to 2.0.0 and the build might be broken due to the API version not being applied in ARM manifest, I've fixed that, can you please review again.

Thanks

**Comment by fengzhou-msft** [comment]
@!ammaralavi there is discrepancy between auto-generated code and the code submitted in the PR, which caused a CI failure. Can you take a look at the CI log and fix the CI failure?

**Comment by ammaralavi** [comment]
@parvezah @fengzhou-msft there is some issue in autorest code generation due to which there are some issues in model generation due to which we had to manually fix some models which caused this issue of discrepancy between auto-generated code and the code submitted in the PR, I have asked feng zhou if we can add the manually fixed code and models in the sdk repo.

**Comment by ammaralavi** [comment]
Hi Feng,
This is regarding the PR : Added new Models and operations for the new Customer Disk SKU by ammaralavi * Pull Request #24724 * Azure/azure-sdk-for-net (github.com)<https://github.com/Azure/azure-sdk-for-net/pull/24724>

These are the issues in the models generated:

1. AddressValidationProperties model is not auto-generated: One of our team member had created an issue for the same in the AutoRest C# repo,  Autorest not generating a model class in c# * Issue #198 * Azure/autorest.csharp (github.com)<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fautorest.csharp%2Fissues%2F198&data=04%7C01%7Cammaralavi%40microsoft.com%7C0674ed307e014b072f4b08d9b71743ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637742132854084167%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9OQ5X9UKdOVX0R7NjjRi5AiNIB5U%2B43urzpTc7fEXZk%3D&reserved=0>, which is still open.

2. Using directive for CloudError property is not present in the generated models: We are using the x-ms-external tag for CloudError and the documentation for this calls out that "in strongly typed languages the code will not compile unless the assembly containing the type is referenced with the project/library" (autorest/readme.md at main * Azure/autorest (github.com)<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fautorest%2Fblob%2Fmain%2Fdocs%2Fextensions%2Freadme.md%23x-ms-external&data=04%7C01%7Cammaralavi%40microsoft.com%7C0674ed307e014b072f4b08d9b71743ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637742132854084167%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jeisTBROxm5NB0YqlWx6mopNlsws5NR8O7XvYIheD3c%3D&reserved=0>).

3. Discriminators not getting generated: This as well seems to be an issue with the AutoRest v2 generator.

@Feng ***@***.***>, we looked at the method that you suggested but it doesn't have any way to include directives in generated model

these are known issues associated with autorest that have been present in the earlier versions of our sdk as well hence we have to make manual changes to the auto generated code to address these issues, so is there a way to get an exemption and check in the code after making these manual changes.

Thanks
Ammar

**Comment by ammaralavi** [comment]
resolved merge conflicts

**Comment by ammaralavi** [comment]
@fengzhou-msft I think the check enforcer is blocking the merge, can you please take a look

**Review by fengzhou-msft — APPROVED** [review]
Approve with the customized code.

**Review by archerzz — APPROVED** [review]

**Comment by archerzz** [comment]
@ammaralavi Would you mind if you could take a look at the pipeline error? Thanks.

**Pull request merged**
