### PR TITLE
[AutoManage] [ManagementPlane] fixes serialization bug, adds test

### PR DESCRIPTION
**Pull request by stowen-msft**
Uses less restrictive JSON serialization behavior, needed for one of our endpoints.

Adds an override for two properties which were string but need to be JOBject.

Adds a recorded test for this case as well.

### CODE REVIEW

**Comment by jsquire** [comment]
Hi @stowen-msft.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by stowen-msft** [comment]
Hi,

  Please leave open for now, I will prioritize it early next week.

**Comment by jsquire** [comment]
Hi @stowen-msft. It doesn't look like there's been engagement since our last conversation.  Would you please be so kind as to let us know if this is still an active work stream or if the PR should be closed out?

**Comment by jsquire** [comment]
Since there hasn't been recent engagement, I'm going to close this out.  Please feel free to reopen if you'd like to continue working on these changes.

**Pull request closed without merging**
