### PR TITLE
[Storage] Upgrade API version to 2022-05-01

### PR DESCRIPTION
**Pull request by Yao725**
# Contributing to the Azure SDK

Please see our [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) if you are not familiar with contributing to this repository or have questions.

For specific information about pull request etiquette and best practices, see [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#pull-request-etiquette-and-best-practices).

### CODE REVIEW

**Review by ArthurMa1978 — APPROVED** [review]

**Comment by JoshLove-msft** [comment]
This change is breaking the Sql VM tests which is blocking the core pipeline - https://dev.azure.com/azure-sdk/public/_build/results?buildId=1791614&view=ms.vss-test-web.build-test-results-tab

**Comment by JoshLove-msft** [comment]
@ArthurMa1978, can you update the affected session records or revert this change to unblock the core pipeline? We should also add a dependency in the storage ci.yml so that the Sql tests are triggered for changes to storage files.

**Comment by Yao725** [comment]
> @ArthurMa1978, can you update the affected session records or revert this change to unblock the core pipeline? We should also add a dependency in the storage ci.yml so that the Sql tests are triggered for changes to storage files.

@JoshLove-msft, I have merged a [PR](https://github.com/Azure/azure-sdk-for-net/pull/30627) to fix the broken tests and now the core ci is not blocked: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1792903&view=results

**Comment by JoshLove-msft** [comment]
> > @ArthurMa1978, can you update the affected session records or revert this change to unblock the core pipeline? We should also add a dependency in the storage ci.yml so that the Sql tests are triggered for changes to storage files.
> 
> @JoshLove-msft, I have merged a [PR](https://github.com/Azure/azure-sdk-for-net/pull/30627) to fix the broken tests and now the core ci is not blocked: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1792903&view=results

Thank you!

**Pull request merged**
