### PR TITLE
VoiceServices SDK release 1.0.0

### PR DESCRIPTION
**Pull request by sebastianrex**
We've now had >30 days of the beta, and so want to release the GA SDK

### CODE REVIEW

**Comment by live1206** [comment]
Since this is the first stable release for voiceservices, we need to polish the naming of the SDK, similar to https://github.com/Azure/azure-sdk-for-net/pull/35414.
@sebastianrex Do you have a due date for the stable release? Due to the work load in SDK team, it would be best if we take it in May.

**Comment by sebastianrex** [comment]
> Since this is the first stable release for voiceservices, we need to polish the naming of the SDK, similar to #35414. @sebastianrex Do you have a due date for the stable release? Due to the work load in SDK team, it would be best if we take it in May.

We had thought that releasing the stable version would be quick, since it's the same code as the beta version, so we'd hoped to get it done in April. But if May is the earliest that we can get it, then I'm sure we can live with that (I'll ask for an extension to our workitem requiring the release)

The polishing of the naming - is that something you want me to take on, or something that the SDK team want to do? I could take a look at that PR and make the equivalent changes here to save some time

**Comment by live1206** [comment]
> > Since this is the first stable release for voiceservices, we need to polish the naming of the SDK, similar to #35414. @sebastianrex Do you have a due date for the stable release? Due to the work load in SDK team, it would be best if we take it in May.
> 
> We had thought that releasing the stable version would be quick, since it's the same code as the beta version, so we'd hoped to get it done in April. But if May is the earliest that we can get it, then I'm sure we can live with that (I'll ask for an extension to our workitem requiring the release)

Thanks!

> The polishing of the naming - is that something you want me to take on, or something that the SDK team want to do? It looks like a lot of the changes are tweaks to the autogenerated code - presumably there's some config to the code generator that's required in order to make those changes persist (rather than just manually changing them). Can you point me at the changes that that PR required in their `readme.md.csharp`?

SDK team will take care of the polishing.

**Comment by live1206** [comment]
Created https://github.com/Azure/azure-sdk-for-net/issues/35827 for next sprint, close this PR.

**Pull request closed without merging**
