### PR TITLE
[AzureMonitorExporter] fix NU1505 Duplicate PackageDownload items found. Microsoft.NETCore.App.Host.win-x64

### PR DESCRIPTION
**Pull request by TimothyMothra**
This PR applies the mitigation that was described here: https://github.com/dotnet/sdk/issues/24747#issuecomment-1126298533

## Details

I'm getting a lot of these errors:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	NU1505	Duplicate 'PackageDownload' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageDownload' items are: Microsoft.NETCore.App.Host.win-x64 [6.0.4], Microsoft.NETCore.App.Host.win-x64 [6.0.4], Microsoft.NETCore.App.Host.win-x64 [6.0.4], Microsoft.NETCore.App.Host.win-x64 [6.0.4].

image

## Version Info

- Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
  Version 17.3.4

- Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
  Version 17.4.0 Preview 2.1

- 
  ```
  > dotnet --info
  .NET SDK:
   Version:   7.0.100-rc.1.22431.12
   Commit:    f1cf61e1c0
  
  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.22621
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\
  
  Host:
    Version:      7.0.0-rc.1.22426.10
    Architecture: x64
    Commit:       06aceb7015
  
  .NET SDKs installed:
    3.1.423 [C:\Program Files\dotnet\sdk]
    5.0.403 [C:\Program Files\dotnet\sdk]
    5.0.408 [C:\Program Files\dotnet\sdk]
    6.0.202 [C:\Program Files\dotnet\sdk]
    6.0.401 [C:\Program Files\dotnet\sdk]
    7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]
  
  .NET runtimes installed:
    Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0-rc.1.22427.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  
  ```

### CODE REVIEW

**Comment by TimothyMothra** [comment]
@joshfree @lmolkova  have you seen this?

**Comment by lmolkova** [comment]
do we know why it affects AzMon Exporter but not other projects in this repo? Or does it repro for other packages and we need to do something centrally?

**Comment by TimothyMothra** [comment]
> do we know why it affects AzMon Exporter but not other projects in this repo? Or does it repro for other packages and we need to do something centrally?

I spotchecked a few other solutions and I haven't seen this issue affecting any other projects.

**Comment by lmolkova** [comment]
@weshaggard can you please take a look? It it known? Thanks!

**Comment by weshaggard** [comment]
I'm not familiar with this issue but I suspect based on https://github.com/dotnet/sdk/issues/24747#issuecomment-1126298533 that it is only an issue when using a newer version of Visual Studio. @heaths I know you were seeing some other issues with the newer VS is this one of them? I wonder if we should wait for a VS update that fixes this.

**Comment by heaths** [comment]
This wasn't one of them, no. The issue I was having was resolved. I'm on the Preview channel for VS, which is currently at version 17.4 Preview 2.1.

**Pull request closed without merging**
