### PR TITLE
SDK update for Soft Delete feature

### PR DESCRIPTION
**Pull request by SanjayHukumRana**
Updating SDK for soft delete properties of protected Item

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hello @SanjayHukumRana , please
- follow the instructions [here](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec) when generating SDK. Remember to track the .txt file, update versions and tags, etc.
- put a link to the spec review PR in comments

**Comment by SanjayHukumRana** [comment]
rest api spec closed PR:  https://github.com/Azure/azure-rest-api-specs/pull/6818

**Comment by isra-fel** [comment]
Sorry for that. Now as a member of Azure orgnization you should be able to view the link.

**Comment by SanjayHukumRana** [comment]
Updated PR based on the instructions here.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
