### PR TITLE
Updating Key Vault to use the 2016-10-01 API version

### PR DESCRIPTION
**Pull request by JeffSimmer**
This change moves Key Vault onto the 2016-10-01 API version and adds an InnerError property on Error.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@JeffSimmer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jesimmer@ntdev.microsoft.com). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@pomortaz please sign off

**Comment by pomortaz** [comment]
@JeffSimmer Thanks for the change. It looks great. Can you please add or extend a test case to test the innererror scenario?

**Review by markcowl — COMMENTED** [review]
@JeffSimmer Please add test for InnerError as Pooneh asks

**Review by markcowl — DISMISSED** [review]
@JeffSimmer  Please add test as suggested by Pooneh

**Review by pomortaz — APPROVED** [review]

**Comment by herveyw** [comment]
@JeffSimmer @pomortaz Why are we bumping all packages versions when only the core SDK changed? Won't this cause all packages to be published, some unnecessarily?

**Comment by pomortaz** [comment]
@herveyw the only package version that is bumped is the SDK.
@JeffSimmer, you need to update this file as well: https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/KeyVault/Microsoft.Azure.KeyVault/Properties/AssemblyInfo.cs

**Pull request merged**
