### PR TITLE
Marking DNS SDK version as GA

### PR DESCRIPTION
**Pull request by vladrai**
Removing pre-release status for Dns

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vladrai__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vladrai). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@vladrai Please change the PR title to something meaningful, like "Moving the xx library to GA"

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@vladrai can you make similar changes to AssemblyInfo.cs, this way we stay consistent across.

**Pull request closed without merging**
