### PR TITLE
Add support for schema create or update for Swagger, WSDL and OpenApi

### PR DESCRIPTION
**Pull request by solankisamir**
Fix based on REST Spec https://github.com/Azure/azure-rest-api-specs/pull/5824

### CODE REVIEW

**Comment by solankisamir** [comment]
@dsgouda the build failure is related to an EventHub test.

**Comment by dsgouda** [comment]
@weshaggard Please take a look at the failures.

**Review by dsgouda — APPROVED** [review]
LGTM

**Comment by solankisamir** [comment]
@dsgouda  I wanted to add an extension to one of the models for better usability. Give me an hour.

**Comment by weshaggard** [comment]
@dsgouda I re-queued the failing test leg but I don't believe it is related to the changes in this PR so if it fails again merge anyway. 

@jsquire looks like another EventHubs test reliability failure

```
Failed   Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.OptionsTests.RuntimeInformationTest
Error Message:
 Assert.True() Failure
Expected: True
Actual:   False
Stack Trace:
   at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.OptionsTests.RuntimeInformationTest() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\ServiceFabricProcessor\OptionsTests.cs:line 191
```

I added a note about this test in issue https://github.com/Azure/azure-sdk-for-net/issues/5995, and if we see it keep failing then I'll disable it.

**Comment by solankisamir** [comment]
@dsgouda I have pushed my changes. Feel free to merge it as soon as CI passes or fails with EventHub test failure.

**Review by dsgouda — CHANGES_REQUESTED** [review]
LGTM

**Review by dsgouda — APPROVED** [review]

**Comment by solankisamir** [comment]
@dsgouda can you merge this.

**Pull request merged**
