### PR TITLE
added operations for logger, properties, openIdConnect and Git

### PR DESCRIPTION
**Pull request by solankisamir**
- Added operations for Logger
- Added Operations for Properties 
- Added operations for OpenIDConnect
- Added Operations for GIT. /save, /deploy and /validate are long running operations.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@solankisamir__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sasolank). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by ailn** [comment]
Looks good to me

**Comment by solankisamir** [comment]
adding a few more overloads for powershell commandlets.

**Pull request merged**
