### PR TITLE
Adding InMemory and Scenario Tests for Microsoft.Management

### PR DESCRIPTION
**Pull request by muazmian**
…ated code.

## Description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md).**
- [x] **The pull request does not introduce [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/breaking-changes.md).**

### [General Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.

### [SDK Generation Guidelines](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/.github/CONTRIBUTING.md#sdk-generation-guidelines)
- [ ] If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.
- [ ] The generate.cmd file for the SDK has been updated with the version of AutoRest, as well as the commitid of your swagger spec or link to the swagger spec, used to generate the code.
- [ ] The `*.csproj` and `AssemblyInfo.cs` files have been updated with the new version of the SDK.

### CODE REVIEW

**Comment by sphibbs** [comment]
@muazmian names are too long. Please shorten the test names so we don't hit the path limit. This should allow the PR to build.

**Comment by muazmian** [comment]
@sphibbs I renamed my tests but the build still failed. I can't find the error in the console or log output. Not sure but it seems some of the older tests are failing.

Both of the following commands successfully worked on my local

msbuild build.proj /t:Build /p:scope=SDKs\Resource
msbuild build.proj /t:RunTests /p:scope=SDKs\Resource

Any guidance?

**Review by shahabhijeet — CHANGES_REQUESTED** [review]
If you are not able to build locally, opening a PR will fail CI.
Can you fix all the errors locally.
If you are getting file name too long, changing file name will not help if the path is still long.
You need to give a shorter name for your tests, rather than using reflection to get the name of the test class.

**Comment by shahabhijeet** [comment]
@muazmian pleaes reopen this PR once you can address your build breaks.
Keeping PR open for more than a week affects our SLA data collection.

**Pull request closed without merging**
