### PR TITLE
OperationalInsights: Change int to long

### PR DESCRIPTION
**Pull request by chfunk**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chfunk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@chfunk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@chfunk was there an accompanying change in hydra-specs-pr this was generated from?

**Comment by chfunk** [comment]
Yes, it can be found here: https://github.com/Azure/hydra-specs-pr/pull/1299

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Pull request merged**
