### PR TITLE
[Resources] Regenerate from v2020-06-01

### PR DESCRIPTION
**Pull request by shenglol**
Regenerate from v2020-06-01 to add MG and tenant level What-If support.

### CODE REVIEW

**Comment by shenglol** [comment]
Hi @isra-fel, could we get a quick sign off for this PR? We are planning to release a new SDK for Resources as soon as possible once this is merged.

**Comment by shenglol** [comment]
@erich-wang Can you help take a look at this?

**Comment by isra-fel** [comment]
Hi @shenglol sorry for the delay!
The changes LGTM, but you need to bump up the version (and release notes)

**Comment by shenglol** [comment]
> Hi @shenglol sorry for the delay!
> The changes LGTM, but you need to bump up the version (and release notes)

No worries for the delay! I updated the version and release notes.

**Review by isra-fel — APPROVED** [review]
LGTM

**Review by erich-wang — APPROVED** [review]

**Pull request merged**
