### PR TITLE
[TA] Clean last Action classes

### PR DESCRIPTION
**Pull request by maririos**
Last part of https://github.com/Azure/azure-sdk-for-net/issues/21605

### CODE REVIEW

**Review by deyaaeldeen — APPROVED** [review]

**Review by mshaban-msft — APPROVED** [review]

**Review by kristapratico — APPROVED** [review]
changelog if you haven't already

**Comment by maririos** [comment]
>changelog if you haven't already

I thought about it, but because this is just removing the inheritance, this shouldn't affect the user, so didn't put it in the changelog. Do you think I should still do it?

**Comment by kristapratico** [comment]
> > changelog if you haven't already
> 
> I thought about it, but because this is just removing the inheritance, this shouldn't affect the user, so didn't put it in the changelog. Do you think I should still do it?

I thought I saw you add that it was removed for the other ones? I think just do whatever is consistent, but do agree that since it's an implementation detail that no one depends on you probably don't need to mention it.

**Review by kinelski — APPROVED** [review]
LGTM

**Comment by maririos** [comment]
>I thought I saw you add that it was removed for the other ones? I think just do whatever is consistent, but do agree that since it's an implementation detail that no one depends on you probably don't need to mention it.

Ahh yeah, so for the other types I actually removed the type. For this too, I can't remove them because both `xxOptions` actually have properties specifics for that endpoint. What I removed was the inheritance from `xxActions` to `xxOptions` to be consistnet on each `xxAction` having it's own properties

**Pull request merged**
